--IS_CACHE=Y
SELECT * FROM TD_S_STAFF_BIZLIST WHERE 1 = 1
AND STAFF_ROLE IN 
(
SELECT (ID_VALUE)STAFF_ROLE FROM TD_S_ECHANNAL_STAFF A
WHERE 1=1 AND A.EPARCHY_CODE = :EPARCHY_CODE
)
AND BIZ_CODE = :BIZ_CODE
AND TRANS_CODE = :TRANS_CODE
AND STAFF_ROLE = :STAFF_ROLE
AND STATUS = :STATUS