--IS_CACHE=Y
SELECT DISTINCT(trans.TRANS_CODE),trans.TRANS_NAME FROM TD_S_TRANSLIST trans,TD_S_STAFF_BIZLIST staff WHERE 1 = 1
 AND trans.TRANS_CODE = staff.TRANS_CODE
 AND staff.STAFF_ROLE = :STAFF_ROLE
 AND staff.BIZ_CODE = :BIZ_CODE