SELECT A.ELEMENT_ID,
       A.ELEMENT_TYPE_CODE,
       A.LABEL_ID,
       A.STATE,
       A.EPARCHY_CODE,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK
  FROM TD_B_ELEMENT_LABEL A
 WHERE A.ELEMENT_ID = :PRODUCT_ID
   AND A.ELEMENT_TYPE_CODE = 'P'
   AND A.STATE = '1'