SELECT A.CONTRACT_ID, A.CONTRACT_NAME,
C.ELEMENT_TYPE_CODE,C.ELEMENT_ID,C.TARIFF_CODE
FROM TD_B_CONTRACT A, TI_B_CONTRACT_DETAIL B, TI_B_CONTRACT_RESOURCE C
where A.CONTRACT_ID=:CONTRACT_ID
AND A.CONTRACT_CODE=B.CONTRACT_CODE
AND B.RESOURCE_CODE=C.RESOURCE_CODE
AND B.RESOURCE_TYPE=C.RESOURCE_TYPE
AND A.CONTRACT_STATUS='2'
AND b.VALID_END_DATE>SYSDATE
AND C.ISVALID='1'