INSERT  INTO TF_B_SMALL_PAYMENT_LOG(SEQ_ID,SERIAL_NUMBER,INTF_TRADE_ID,CHNL_CODE,PAY_FEE,SP_ID,SP_NAME,REMARK,
ACCEPT_DATE,OPER_TIME,TRADE_STAFF_ID,TRADE_DEPART_ID,CHARGE_ID,UPDATE_TIME,RSRV_STR1,RSRV_STR2,RSRV_STR3)
VALUES (f_Sys_Getseqid('0898','seq_trade_id'),:SERIAL_NUMBER,:INTF_TRADE_ID,:CHNL_CODE,TO_NUMBER(:PAY_FEE),:SP_ID,:SP_NAME,:REMARK,
to_date(:ACCEPT_DATE,'yyyymmdd'),to_date(:OPER_TIME,'yyyymmddhh24miss'),:TRADE_STAFF_ID,:TRADE_DEPART_ID,:CHARGE_ID,SYSDATE,
:RSRV_STR1,:RSRV_STR2,:RSRV_STR3)