SELECT  SEQ_ID,ACCEPT_MONTH,SERIAL_NUMBER,INTF_TRADE_ID,CHNL_CODE,to_char(PAY_FEE/10) RSRV_STR8 ,SP_ID,SP_NAME||'-'||REMARK  RSRV_STR3,REMARK,to_char(OPER_TIME,'yyyy-mm-dd hh24:mi:ss') RSRV_STR1,to_char(OPER_TIME,'yyyy-mm-dd hh24:mi:ss') OPER_TIME,
TRADE_STAFF_ID,TRADE_DEPART_ID,CHARGE_ID,UPDATE_TIME,'通信账户支付' RSRV_STR2
FROM TF_B_SMALL_PAYMENT_LOG
WHERE 1=1
AND  SERIAL_NUMBER=:SERIAL_NUMBER
AND (:START_TIME IS　NULL OR ACCEPT_DATE>=TO_DATE(:START_TIME,'yyyy-mm-dd hh24:mi:ss'))
AND (:END_TIME IS　NULL OR ACCEPT_DATE<=TO_DATE(:END_TIME,'yyyy-mm-dd hh24:mi:ss'))
order by SERIAL_NUMBER,ACCEPT_DATE,OPER_TIME