insert into TF_F_PO_MBMP_SUB
(PARTITION_ID       ,USER_ID            ,POSPECNUMBER  
,PRODUCTSPECNUMBER  ,PRODUCTID        ,STATUS          ,BIZ_CODE           ,RB_LIST           
,RSRV_STR1     
,RSRV_STR2          ,RSRV_STR3  ,RSRV_STR4,RSRV_STR5        ,RSRV_NUM1          ,RSRV_NUM2  ,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5        ,RSRV_DATE1        
,RSRV_DATE2 ,RSRV_DATE3   
,START_DATE         ,END_DATE,REMARK  ,UPDATE_STAFF_ID       , UPDATE_DEPART_ID,UPDATE_TIME )
select PARTITION_ID       ,USER_ID            ,POSPECNUMBER  
,PRODUCTSPECNUMBER  ,PRODUCTID       
,decode(b.oper_code,'1','A','2','E','3','N','4','A',5,'A')          ,BIZ_CODE           ,RB_LIST           
,RSRV_STR1     
,RSRV_STR2          ,RSRV_STR3    ,RSRV_STR4,RSRV_STR5      ,RSRV_NUM1          ,RSRV_NUM2 ,RSRV_NUM3  ,RSRV_NUM4,RSRV_NUM5       ,RSRV_DATE1        
,RSRV_DATE2    ,RSRV_DATE3
,START_DATE         ,END_DATE, REMARK,            UPDATE_STAFF_ID,   UPDATE_DEPART_ID ,UPDATE_TIME
from TF_B_POPRODUCT_MBMP b where trade_id=TO_NUMBER(:TRADE_ID)