--IS_CACHE=Y
SELECT PARA_CODE1
  FROM TD_S_COMMPARA
 WHERE PARAM_ATTR = :PARAM_ATTR
   AND SUBSYS_CODE = :SUBSYS_CODE
   AND PARAM_CODE = :PARAM_CODE
   AND START_DATE < SYSDATE
   AND END_DATE > SYSDATE