SELECT COUNT(*) RECORDCOUNT
  FROM tf_f_user_discnt d
 WHERE d.user_id = TO_NUMBER(:USER_ID)
   AND d.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND d.discnt_code = '80176874'
   AND SYSDATE BETWEEN d.START_DATE AND d.END_DATE  