/*系统拦截条件*/
SELECT B.PARTITION_ID,
       TO_CHAR(B.USER_ID) USER_ID,
       A.PRODUCT_ID,
       A.PRODUCT_NAME,
       A.CAMPN_TYPE,
       B.PRODUCT_ID,
       B.PACKAGE_ID,
       TO_CHAR(B.INST_ID) INST_ID,
       TO_CHAR(B.CAMPN_ID) CAMPN_ID,
       B.SERIAL_NUMBER_B,
       GOODS_ID,
       GOODS_NAME,
       TO_CHAR(GOODS_NUM) GOODS_NUM,
       TO_CHAR(GOODS_VALUE) GOODS_VALUE,
       GOODS_STATE,
       RES_TAG,
       RES_TYPE_CODE,
       RES_ID,
       RES_CODE,
       DEVICE_MODEL_CODE,
       DEVICE_MODEL,
       TO_CHAR(DEVICE_COST) DEVICE_COST,
       DEVICE_BRAND_CODE,
       DEVICE_BRAND,
       DESTROY_FLAG,
       GIFT_MODE,
       POST_NAME,
       POST_ADDRESS,
       POST_CODE,
       TO_CHAR(B.RELATION_TRADE_ID) RELATION_TRADE_ID,
       TO_CHAR(B.CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS') CANCEL_DATE,
       TO_CHAR(B.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE
  FROM TF_F_USER_SALE_ACTIVE A, TF_F_USER_SALE_GOODS B
 WHERE A.USER_ID = B.USER_ID
   AND A.PACKAGE_ID = B.PACKAGE_ID 
   AND A.USER_ID =TO_NUMBER(:USER_ID)
   AND A.CAMPN_TYPE NOT IN('YX04','YX07')
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND B.PARTITION_ID = A.PARTITION_ID
   AND SYSDATE BETWEEN A.START_DATE AND END_DATE
   AND B.GOODS_STATE = :GOODS_STATE
   --新增活动列表过滤--
   AND NOT EXISTS (
       SELECT C.PARA_CODE1   FROM TD_S_COMMPARA C
       WHERE C.PARAM_ATTR='9995' 
       AND C.PARAM_CODE='FILTER'
       AND C.PARA_CODE1=B.PRODUCT_ID
   )