DELETE FROM TF_F_USER_BRANDCHANGE A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND (A.END_DATE > SYSDATE OR EXISTS
        (SELECT 1
           FROM  TF_B_TRADE_BRANDCHANGE_BAK B
          WHERE B.USER_ID = A.USER_ID
            AND B.START_DATE = A.START_DATE
            AND B.TRADE_ID = :TRADE_ID))