--IS_CACHE=Y
SELECT 
T.PRODUCT_NAME ELEMENT_NAME,T.BIZ_DESC ELEMENT_EXPLAIN, 
T.EFFECTIVE_TYPE EFFECT_TYPE ,T.PACKAGE_BRAND_CODE,TO_CHAR(T.ADDED_BDATE,'YYYYMMDDHH24MISS') START_DATE,
TO_CHAR(T.ADDED_EDATE,'YYYYMMDDHH24MISS') END_DATE,T.PACKAGE_PRICE||T.PACKAGE_PRICE_UNIT PRICE
 FROM TD_B_MARKET_PACKAGE  T 
 WHERE T.PROVINCE =:PROVINCE