--IS_CACHE=Y
SELECT
  SEQ_NO,
  ACTIVITY_NUMBER,
  TYPE_NAME,  
  TRADE_TYPE_CODE,
  EXTRA_CONFIG_SIGN,
  ELEMENT_TYPE,
  ELEMENT_ID
FROM TD_S_UECLOTTERY
WHERE START_DATE <= SYSDATE AND END_DATE >= SYSDATE
AND ACTIVITY_NUMBER=:ACTIVITY_NUMBER