SELECT  F.SERIAL_NUMBER,to_char(D.USER_ID) USER_ID, to_char(USER_ID_A) USER_ID_A,D.DISCNT_CODE,to_char(INST_ID) INST_ID,S.DISCNT_NAME,S.DISCNT_EXPLAIN,
S.ITEM_TYPE,S.ITEM_CODE, HIGH_FEE,decode(S.HALF_NET,0,'ÕûÔÂ',1,'°ëÔÂ',S.HALF_NET) HALF_NET,S.ADJUST_TAG,
S.DISCNT_CODE_A,S.DISCNT_STATE,S.ENABLE_TAG
FROM tf_f_user_discnt D ,TD_B_DISCNT_SHARE S,TF_F_USER F
WHERE D.user_id=TO_NUMBER(:USER_ID)
AND D.partition_id=MOD(TO_NUMBER(:USER_ID),10000)
AND D.DISCNT_CODE=S.DISCNT_CODE
AND D.USER_ID=F.USER_ID
AND S.RSRV_STR1=:SHARE_TYPE
AND Sysdate Between D.Start_Date And D.End_Date