--IS_CACHE=Y
SELECT C.PARA_CODE1 PAY_NAME_REMARK 
 FROM TD_S_COMMPARA C 
 WHERE C.SUBSYS_CODE = :SUBSYS_CODE 
 AND C.PARAM_ATTR = :PARAM_ATTR
 AND C.PARAM_CODE = :PARAM_CODE
 AND C.PARAM_NAME = :PARAM_NAME
