SELECT USER_ID,
       LTEB_USER_ID,
       STATE_CODE,
       STATE_VALUE,
       STATE_ATTR,
       STATE_ATTR_VALUE,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TF_F_LTEB_USER_STATE 
 WHERE LTEB_USER_ID = :USER_ID
   AND END_DATE > TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS')
   AND ((UPDATE_TIME <= TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') AND
       SYSDATE BETWEEN START_DATE AND END_DATE) OR
       (UPDATE_TIME > TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') AND
       START_DATE <= TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS')))
