SELECT T.RULE_ID,
       T.RECEIVE_TYPE,
       T.REMARK,
       T.VALID_TAG,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_TASK_RECEIVE_RULE T 
 WHERE T.RECEIVE_TYPE = :RECEIVE_TYPE
   AND T.VALID_TAG = :VALID_TAG
