SELECT to_char(a.TRADE_ID) TRADE_ID,a.CANCEL_TAG CANCEL_TAG,to_char(a.ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
a.TRADE_DEPART_ID TRADE_DEPART_ID,a.TRADE_STAFF_ID TRADE_STAFF_ID,a.TRADE_TYPE_CODE TRADE_TYPE_CODE,a.PARAM_CODE PARAM_CODE,
a.REMARK REMARK,a.AUDIT_STAFF_ID AUDIT_STAFF_ID,to_char(a.AUDIT_DATE,'yyyy-mm-dd hh24:mi:ss') AUDIT_DATE,
a.AUDIT_TAG AUDIT_TAG,a.RSRV_STR1 RSRV_STR1,a.RSRV_STR2 RSRV_STR2,a.RSRV_STR3 RSRV_STR3,a.RSRV_STR4 RSRV_STR4,a.RSRV_STR5 RSRV_STR5,
decode(b.STATE_CODE,'4','二级稽核通过','5','二级稽核回退','1','营业员自查通过','2','一级稽核通过','3','一级稽核回退','其他') RSRV_STR6,
decode(a.AUDIT_TAG,'0','未修改','1','已修改','其他') RSRV_STR7,a.RSRV_STR8 RSRV_STR8
 FROM TS_A_DIFFERINFO a,TS_A_AUDITRESULT_DETAIL b
 WHERE a.AUDIT_DATE >= TRUNC(TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'))
   AND a.AUDIT_DATE <  TRUNC(TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'))+1  
   AND a.TRADE_DEPART_ID in
   (
    SELECT DEPART_ID
       FROM TD_M_DEPART
      WHERE VALIDFLAG = '0'
        and area_code =
        ( select area_code
            from TD_M_DEPART
           where DEPART_ID =:TRADE_DEPART_ID
          )
    )
   AND a.trade_id=b.trade_id
   and a.CANCEL_TAG=b.CANCEL_TAG