UPDATE TF_F_USER_SERVICE_TIMER
   SET PROCESS_TAG = '1'
  where TRADE_ID = to_number(:TRADE_ID) and  ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE and ELEMENT_ID = :ELEMENT_ID AND EXEC_TIME<=TRUNC(ADD_MONTHS(SYSDATE,1), 'mm')