INSERT INTO TF_F_USER_UPMS_ORDER
  (ORDER_SEQ, ORDER_ID, ORDER_SUB_ID, USER_ID, ITEM_ID, ITEM_NUM,
   PROC_STATE, ORDER_STATE, DELIV_PROVINCE, CITY, DISTRICT, CUS_ADD, CUS_TEL,
   CUS_ADDCODE, TIME_REQUEST, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
   RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10,
   REG_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK)
VALUES
  (:ORDER_SEQ, :ORDER_ID, :ORDER_SUB_ID, :USER_ID, :ITEM_ID,
   :ITEM_NUM, :PROC_STATE, :ORDER_STATE, :DELIV_PROVINCE, :CITY,
   :DISTRICT, :CUS_ADD, :CUS_TEL, :CUS_ADDCODE, :TIME_REQUEST,
   :RSRV_STR1, :RSRV_STR2, :RSRV_STR3, :RSRV_STR4, :RSRV_STR5,
   :RSRV_STR6, :RSRV_STR7, :RSRV_STR8, :RSRV_STR9, :RSRV_STR10,
   TO_DATE(:REG_DATE, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'), :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID, :REMARK)