SELECT to_char(TRADE_ID) TRADE_ID,ACCEPT_MONTH ,to_char(USER_ID_A) USER_ID_A,SERIAL_NUMBER_A ,
to_char(USER_ID_B) USER_ID_B,SERIAL_NUMBER_B ,RELATION_TYPE_CODE ,ROLE_TYPE_CODE ,ROLE_CODE_A ,
ROLE_CODE_B ,ORDERNO ,SHORT_CODE ,to_char(INST_ID) INST_ID,
to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,
to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,MODIFY_TAG ,
to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,UPDATE_STAFF_ID ,UPDATE_DEPART_ID ,REMARK ,RSRV_NUM1 ,RSRV_NUM2 ,
RSRV_NUM3 ,RSRV_NUM4 ,RSRV_NUM5 ,RSRV_STR1 ,RSRV_STR2 ,RSRV_STR3 ,
to_char(RSRV_STR4) RSRV_STR4,to_char(RSRV_STR5) RSRV_STR5,
to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
RSRV_TAG1 ,RSRV_TAG2 ,RSRV_TAG3 
 FROM tf_b_trade_relation
 WHERE trade_id = TO_NUMBER(:TRADE_ID)
   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
   AND relation_type_code = :RELATION_TYPE_CODE
   AND USER_ID_B = TO_NUMBER(:USER_ID_B)