UPDATE TF_B_TRADE_LTEB 
   SET RSPCODE=:RSPCODE,
       RSPDESC=:RSPDESC,
       RSRV_STR2=:RSRV_STR2,
       STATE=:STATE,
       RSRV_STR1=:TRADE_ID
 WHERE MSISDN=:SERIAL_NUMBER
   AND OPR_NUMB=:OPR_NUMB
   AND STATE=:STATE_COND
