SELECT A.TRADE_ID,
       A.USER_ID,
       A.SERIAL_NUMBER,
       A.CITY_CODE,
       A.WIDENET_TYPE,
       A.WIDENET_WIDE,
       B.CONSTRUCTION_ADDR,
       TO_CHAR(A.CONSTRUCTION_DATE, 'yyyy-mm-dd hh24:mi:ss') CONSTRUCTION_DATE,
       A.CONST_STAFF_ID,
       A.CONST_PHONE,
       A.DEAL_TAG,
       A.DEAL_STAFF_ID,
       TO_CHAR(A.DEAL_DATE, 'yyyy-mm-dd hh24:mi:ss') DEAL_DATE,
       A.REMARK,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_STR6,
       A.RSRV_STR7,
       A.RSRV_STR8,
       A.RSRV_STR9,
       A.RSRV_STR10
FROM TF_B_CONSTRUCTION_ADDR A ,TF_F_USER_WIDENET B
     WHERE A.USER_ID = B.USER_ID
     AND B.PARTITION_ID = MOD(TO_NUMBER(A.USER_ID), 10000)
	 AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
     AND TRUNC(A.CONSTRUCTION_DATE) >= TO_DATE(:START_DATE, 'yyyy-mm-dd')
     AND TRUNC(A.CONSTRUCTION_DATE) <= TO_DATE(:END_DATE, 'yyyy-mm-dd')
     AND A.CITY_CODE = :CITY_CODE
     AND A.DEAL_TAG = :DEAL_TAG
     AND A.DEAL_TAG != '1'