SELECT
 A.IBSYSID,REPLACE(REPLACE(A.XML_REQUEST_HEAD,'<','{'),'>','}') XML_REQUEST_HEAD,REPLACE(REPLACE(A.XML_REQUEST_BODY1,'<','{'),'>','}') XML_REQUEST_BODY,
 REPLACE(REPLACE(A.XML_RESPONE,'<','{'),'>','}') XML_RESPONE,A.HTTP_REQUEST_STRING,A.HTTP_RESPONSE_STRING,A.BML_BUFFER_REQ,A.BML_BUFFER_RES,A.SRC_DOMAIN,A.REMARK
 FROM UCR_IBOSS.TL_B_IBTRADE_LOG A
WHERE 1=1
 AND A.TRANSIDO = :TRANSIDO
