UPDATE TD_B_ISSP_BUSI_SPEC_RELE T
   SET T.VALID_TAG = :VALID_TAG
 WHERE T.BUSI_TYPE = :BUSI_TYPE
   AND T.BUSI_CODE = :BUSI_CODE
   AND T.BUSIFORM_OPER_TYPE = :BUSIFORM_OPER_TYPE
   AND T.IN_MODE_CODE = :IN_MODE_CODE
