UPDATE TF_B_TRADE_TELEPHONE T
   SET T.RSRV_STR1 = :RSRV_STR1,
       T.RSRV_STR2 = :RSRV_STR2,
       T.RSRV_STR3 = :RSRV_STR3
 WHERE T.USER_ID = :USER_ID
   AND T.END_DATE > SYSDATE
   AND T.INST_ID = :INST_ID
   AND T.TRADE_ID = :TRADE_ID