--IS_CACHE=Y
SELECT A.SUBSYS_CODE,
       A.PARAM_ATTR,
       A.PARAM_CODE TRADE_TYPE_CODE,
       A.PARAM_NAME CLASS_NAME,
       A.PARA_CODE1 RULE_TYPE,
       A.PARA_CODE2 RULE_DESC
  FROM TD_S_COMMPARA A
 WHERE A.SUBSYS_CODE = :SUBSYS_CODE
   AND A.PARAM_ATTR = :PARAM_ATTR
   AND A.PARAM_CODE = :PARAM_CODE
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE