SELECT to_char(TRADE_ID) TRADE_ID,ACCEPT_MONTH,to_char(USER_ID) USER_ID,SALE_PROJECT_ID,SALE_PACKAGE_ID,ELEMENT_TYPE_CODE,ELEMENT_ID,PARA_CODE1,PARA_CODE2,PARA_CODE3,PARA_CODE4,PARA_CODE5,PARA_CODE6,PARA_CODE7,PARA_CODE8,MODIFY_TAG,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_B_TRADE_SALEPROJECT_SUB
 WHERE trade_id=TO_NUMBER(:TRADE_ID)

   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))