SELECT OPRNUMB OPER_TRADE_ID, DEALTYPE DEAL_TYPE, IMEI TERMINAL_ID,
	RESULT, UNSUCREASON UNSUC_REASON, REMARK UNSUC_COMMENT
FROM TI_R_WHOLESALESDATA_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')