--IS_CACHE=Y
SELECT B.TRADE_TYPE_CODE, B.TRADE_TYPE
  FROM TD_S_TRADETYPE B
 WHERE B.TRADE_TYPE_CODE IN
       (SELECT A.TRADE_TYPE_CODE
          FROM TD_B_TRADE_HINT A
         GROUP BY A.TRADE_TYPE_CODE)