UPDATE TF_F_USER_SALEACTIVE_BOOK A
   SET A.CANCEL_DATE     = SYSDATE,
       A.PROCESS_TAG     = '2',
       A.CANCEL_TRADE_ID = :TRADE_ID,
       A.CANCEL_STAFF_ID = :CANCEL_STAFF_ID,
       A.UPDATE_TIME = SYSDATE,
       A.UPDATE_STAFF_ID = :UPDATE_STAFF_ID
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND A.PROCESS_TAG = '0'