UPDATE TF_B_TRADE_OFFER_REL
   SET START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE   = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND REL_OFFER_INS_ID = :REL_OFFER_INS_ID