UPDATE TD_R_TERMINAL_PRICE SET VALID_TAG='1' ,UPDATE_STAFF_ID=:UPDATE_STAFF_ID,UPDATE_DEPART_ID=:UPDATE_DEPART_ID,UPDATE_TIME=SYSDATE
WHERE MATERIAL_CODE 
IN
(
SELECT price.MATERIAL_CODE FROM TF_R_PRODUCT_GRP product,TD_R_TERMINAL_PRICE price
WHERE product.MATERIAL_CODE=price.MATERIAL_CODE AND product.MATERIAL_CODE=:MATERIAL_CODE
 )