SELECT ROWNUM,T.OPR_NUM,T.RETURN_ID,T.ACCEPT_MONTH,T.RETURN_TYPE,T.EXT_RETURN_ID,T.ORDER_ID,T.SUB_ORDER_ID,T.CHANNEL_ID,T.SHOP_CODE,
T.SHOP_NAME,T.BUYER_RETURN_TIME,T.EXT_CHANNEL_RETURN_TIME,T.BUYER_NICK_NAME,T.TRADE_ID,T.STATUS,T.IS_SYNC,T.RSRV_STR1,T.RSRV_STR2,T.RSRV_STR3,
T.UPDATE_DEPART_ID,T.UPDATE_STAFF_ID,T.ACCEPT_DATE,T.UPDATE_TIME 
FROM TF_B_CTRM_RETURN T
WHERE ROWNUM <= 500 AND  ROWNUM > 0
AND T.IS_SYNC='0'
