server:
  port: 9004

spring:
  application:
    name: wms-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 192.168.3.60:8848
        # 指定集群名称
        cluster-name: BJ
        metadata:
          version: v1