SELECT A.*
  FROM TF_F_USER_DISCNT A,TF_F_USER_OFFER_REL C, TD_S_COMMPARA B
 WHERE A.INST_ID = C.REL_OFFER_INS_ID
   AND C.REL_OFFER_TYPE = 'D'
   AND C.OFFER_TYPE = 'P'
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE 
   AND C.OFFER_CODE = B.PARA_CODE1
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND C.USER_ID = A.USER_ID
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR ='173'
   AND B.PARAM_CODE = :PARAM_CODE
   AND A.PARTITION_ID = C.PARTITION_ID
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE