INSERT INTO TI_B_MOSP_FOLLOWMSISDN(MSISDN,IMSI,PRI_PROVINCE,PRI_CITY,MSISDN_STATUS,SYNC_TYPE,RESULT_CODE,USER_STATUS,SYNC_STATUS,INSERT_TIME,MSISDN_TYPE,CLASS_ID)
values(:SERIAL_NUMBER,:IMSI,'898',:EPARCHY_CODE,:EXEC_STATUS,:OPERTYPE,:SPRING_RESULT_CODE,:USER_STATUS,:DEAL_STATUS,sysdate,:MSISDN_TYPE,:CLASS_ID)
