SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       SERVICE_ID,
       SERIAL_NUMBER,
       SP_CODE,
       BIZ_CODE,
       BIZ_TYPE_CODE,
       BIZ_STATE_CODE,
       PRODUCT_NO,
       ORG_DOMAIN,
       OPER_CODE,
       OPR_SOURCE,
       BILL_TYPE,
       PRICE,
       TO_CHAR(FIRST_DATE, 'yyyy-mm-dd hh24:mi:ss') FIRST_DATE,
       TO_CHAR(FIRST_DATE_MON, 'yyyy-mm-dd hh24:mi:ss') FIRST_DATE_MON,
       GIFT_SERIAL_NUMBER,
       GIFT_USER_ID,
       TO_CHAR(SUBSCRIBE_ID) SUBSCRIBE_ID,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       TO_CHAR(RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(RSRV_NUM5) RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_F_USER_PLATSVC
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND SERVICE_ID = :SERVICE_ID
   AND START_DATE BETWEEN TRUNC(SYSDATE, 'mm') AND
       ADD_MONTHS(TRUNC(SYSDATE, 'mm'), 1) - 1 / 24 / 3600
   AND sysdate between start_date and end_date
   AND ROWNUM < 2
