SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID TRADE_ID, B.INST_ID, PARTITION_ID, B.ID, B.ID_TYPE, B.CUST_TYPE,
		B.POST_NAME, B.POST_TAG, B.POST_CONTENT, B.POST_TYPESET,
		B.POST_CYC, B.POST_ADDRESS, B.POST_CODE, B.EMAIL,
		B.FAX_NBR, B.START_DATE, B.END_DATE, B.UPDATE_TIME,
		B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK,
		B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4,
		B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3,
		B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1, B.RSRV_DATE2,
		B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3
  FROM TF_F_POSTINFO B
 WHERE B.ID = :ID
   AND B.PARTITION_ID = MOD(:ID, 10000)