UPDATE /*+INDEX(a PK_TD_M_RES_COMMPARA)*/ td_m_res_commpara a
   SET rdvalue1=DECODE(:CHECK_TAG,'1',SYSDATE,'4',SYSDATE,rdvalue1),
       rdvalue2=DECODE(:CHECK_TAG,'2',SYSDATE,'4',SYSDATE,rdvalue2),
       remark=:REMARK,
       update_time=SYSDATE,update_staff_id=:UPDATE_STAFF_ID,update_depart_id=:UPDATE_DEPART_ID  
 WHERE eparchy_code=:EPARCHY_CODE
   AND para_attr=:PARA_ATTR
   AND (:PARA_CODE1 IS NULL OR para_code1=:PARA_CODE1)
   AND (:PARA_CODE2 IS NULL OR para_code2=:PARA_CODE2)
   AND (:PARA_NAME IS NULL OR :PARA_NAME IS NOT NULL)
   AND (:PARA_VALUE1 IS NULL OR :PARA_VALUE1 IS NOT NULL)
   AND (:PARA_VALUE2 IS NULL OR :PARA_VALUE2 IS NOT NULL)
   AND (:PARA_VALUE3 IS NULL OR :PARA_VALUE3 IS NOT NULL)
   AND (:PARA_VALUE4 IS NULL OR :PARA_VALUE4 IS NOT NULL)
   AND (:PARA_VALUE5 IS NULL OR :PARA_VALUE5 IS NOT NULL)
   AND (:PARA_VALUE6 IS NULL OR :PARA_VALUE6 IS NOT NULL)
   AND (:PARA_VALUE7 IS NULL OR :PARA_VALUE7 IS NOT NULL)
   AND (:PARA_VALUE8 IS NULL OR :PARA_VALUE8 IS NOT NULL)
   AND (:PARA_VALUE9 IS NULL OR :PARA_VALUE9 IS NOT NULL)
   AND (:PARA_VALUE10 IS NULL OR :PARA_VALUE10 IS NOT NULL)
   AND (:PARA_VALUE11 IS NULL OR :PARA_VALUE11 IS NOT NULL)
   AND (:PARA_VALUE12 IS NULL OR :PARA_VALUE12 IS NOT NULL)