UPDATE td_m_res_commpara
   SET para_value11=DECODE(para_value11,NULL,DECODE(:CHECKTAG,1,-TO_NUMBER(:PARA_VALUE11),TO_NUMBER(:PARA_VALUE11)),DECODE(:CHECKTAG,1,para_value11-TO_NUMBER(:PARA_VALUE11),para_value11+TO_NUMBER(:PARA_VALUE11))),rdvalue1=SYSDATE,update_time=SYSDATE,update_staff_id=:UPDATE_STAFF_ID,update_depart_id=:UPDATE_DEPART_ID  
 WHERE eparchy_code=:EPARCHY_CODE
   AND para_attr=:PARA_ATTR
   AND (:PARA_CODE1 IS NULL OR (:PARA_CODE1 IS NOT NULL AND para_code1=:PARA_CODE1))
   AND para_code2=:PARA_CODE2