insert into TI_B_WHITECONFIRM(INST_ID,EC_ID,PROD_ID,BIZ_CODE,PROD_NAME,SERV_CODE,OP_TYPE,OP_CODE,SERIAL_NUMBER,EFFT_TIME,DATA_TYPE,
SYNC_FLAG,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5)
values (:INST_ID,:EC_ID,:PROD_ID,:BIZ_CODE,:PROD_NAME,:SERV_CODE,:OP_TYPE,:OP_CODE,:SERIAL_NUMBER,TO_DATE(:EFFT_TIME,'yyyy-MM-dd HH24:mi:ss'),:DATA_TYPE,
:SYNC_FLAG,:REMARK,:RSRV_NUM1,:RSRV_NUM2,:RSRV_NUM3,:RSRV_STR1,:RSRV_STR2,:RSRV_STR3,:RSRV_STR4,:RSRV_STR5)
