INSERT INTO TI_B_RELATION_UU (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
        FROM tf_f_relation_uu a
             WHERE a.user_id_b IN (             
             SELECT b.user_id_a FROM tf_b_trade_relation b WHERE b.trade_id =:TRADE_ID
             UNION 
             SELECT b.user_id_b FROM tf_b_trade_relation b WHERE b.trade_id =:TRADE_ID ) 
       AND NOT EXISTS (SELECT 1 FROM TI_B_RELATION_UU 
                           WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.PARTITION_ID=PARTITION_ID
                           AND a.USER_ID_A = USER_ID_A
                           AND a.PARTITION_ID=PARTITION_ID                                          
                           AND a.USER_ID_B =USER_ID_B
                           AND a.RELATION_TYPE_CODE = RELATION_TYPE_CODE
                           AND a.START_DATE=START_DATE
                           )        
 UNION  
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
        FROM tf_f_relation_uu t
             WHERE t.user_id_a IN (             
             SELECT b.user_id_a FROM tf_b_trade_relation b WHERE b.trade_id =:TRADE_ID
             UNION 
             SELECT b.user_id_b FROM tf_b_trade_relation b WHERE b.trade_id =:TRADE_ID  )      
      AND NOT EXISTS (SELECT 1 FROM TI_B_RELATION_UU 
                           WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND t.PARTITION_ID=PARTITION_ID
                           AND t.USER_ID_A = USER_ID_A
                           AND t.PARTITION_ID=PARTITION_ID                                          
                           AND t.USER_ID_B =USER_ID_B
                           AND t.RELATION_TYPE_CODE = RELATION_TYPE_CODE
                           AND t.START_DATE=START_DATE
                           )