SELECT TO_CHAR(B.USER_ID_A) USER_ID_A,
       '' SERIAL_NUMBER_A,
       TO_CHAR(USER_ID) USER_ID_B,
       '' SERIAL_NUMBER_B,
       '81' RELATION_TYPE_CODE,
       TO_CHAR(B.INST_ID) INST_ID,
       TO_CHAR(B.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(B.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_USER_PRODUCT B
 WHERE B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND B.USER_ID = TO_NUMBER(:USER_ID_B)
   AND B.END_DATE > SYSDATE
   AND B.PRODUCT_ID = 9981011
UNION ALL
SELECT TO_CHAR(U.USER_ID_A) USER_ID_A,
       U.SERIAL_NUMBER_A,
       TO_CHAR(U.USER_ID_B) USER_ID_B,
       U.SERIAL_NUMBER_B,
       U.RELATION_TYPE_CODE,
       TO_CHAR(U.INST_ID) INST_ID,
       TO_CHAR(U.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(U.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_RELATION_UU U,TD_S_COMMPARA C
 WHERE U.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND U.USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND U.END_DATE > SYSDATE
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '7355'
   AND C.PARAM_CODE = 'RELA_TYPECODE'
   AND U.RELATION_TYPE_CODE = C.PARA_CODE1
   AND C.PARA_CODE1 != :RELATION_TYPE_CODE
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE