SELECT  TRADE_ID,TRADE_TYPE,CUST_NAME,ACCEPT_DATE,'??????',SUM(BUSI_FEE) BUSI_FEE
FROM (
  SELECT A.TRADE_ID,A.ACCEPT_DATE,A.CUST_NAME,B.FEE_MODE,B.BUSI_FEE,T.TRADE_TYPE
  FROM TF_B_TRADE A,TF_B_TRADEFEE_TAX B,TD_S_TRADETYPE T
  WHERE A.TRADE_ID=B.TRADE_ID
  AND B.FEE_MODE='0'
  AND A.TRADE_TYPE_CODE=T.TRADE_TYPE_CODE
  AND A.EPARCHY_CODE=T.EPARCHY_CODE
  AND A.CUST_ID=:CUST_ID
  AND NOT EXISTS(SELECT 1 FROM TF_B_VATPRINTLOG L  WHERE L.TRADE_ID=A.TRADE_ID)
  AND A.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE,'yyyy-mm-dd') AND TO_DATE(:END_DATE,'yyyy-mm-dd')+1
)
GROUP BY TRADE_ID,TRADE_TYPE,CUST_NAME,ACCEPT_DATE
UNION ALL
SELECT  TRADE_ID,TRADE_TYPE,CUST_NAME,ACCEPT_DATE,'??????',SUM(BUSI_FEE) BUSI_FEE
FROM (
  SELECT A.TRADE_ID,A.ACCEPT_DATE,A.CUST_NAME,B.FEE_MODE,B.BUSI_FEE,T.TRADE_TYPE
  FROM TF_BH_TRADE A,TF_B_TRADEFEE_TAX B,TD_S_TRADETYPE T
  WHERE A.TRADE_ID=B.TRADE_ID
  AND B.FEE_MODE='0'
  AND A.TRADE_TYPE_CODE=T.TRADE_TYPE_CODE
  AND A.EPARCHY_CODE=T.EPARCHY_CODE
  AND A.CUST_ID=:CUST_ID
  AND NOT EXISTS(SELECT 1 FROM TF_B_VATPRINTLOG L WHERE L.TRADE_ID=A.TRADE_ID)
  AND A.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE,'yyyy-mm-dd') AND TO_DATE(:END_DATE,'yyyy-mm-dd')+1
)
GROUP BY TRADE_ID,TRADE_TYPE,CUST_NAME,ACCEPT_DATE