SELECT TO_CHAR(USER_ID),
       TEL_URL,
       SIP_URL,
       IMPI,
       SUBSTR(IMPI, INSTR(IMPI, '@') + 1, LENGTH(IMPI)) HSS_REALM,
       IMS_USER_ID,
       IMS_PASSWORD,
       START_DATE,
       END_DATE,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TF_F_USER_IMPU
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   and (RSRV_STR1 is null OR RSRV_STR1 <> '2')
   AND SYSDATE BETWEEN START_DATE AND END_DATE