--IS_CACHE=N
SELECT U.USER_ID_A 主号码,U.INST_ID 实例标识
 FROM TF_F_RELATION_UU U
WHERE U.USER_ID_B = TO_NUMBER(:USER_ID)
  AND U.RELATION_TYPE_CODE = '45' -- 亲亲网
  AND U.ROLE_CODE_B = '2'
  AND U.START_DATE >= TRUNC(SYSDATE) - 3
  AND U.END_DATE > TRUNC(LAST_DAY(SYSDATE) + 1) - 1 / 86400
  AND ROWNUM < 2