UPDATE TF_F_USER_GRP_PACKAGE SET 
END_DATE = to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss') , UPDATE_TIME = to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, REMARK = :REMARK
WHERE 
PARTITION_ID = MOD(to_number(:USER_ID),10000) and USER_ID = to_number(:USER_ID) and PRODUCT_ID = :PRODUCT_ID and PACKAGE_ID = :PACKAGE_ID and ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE and ELEMENT_ID = :ELEMENT_ID and START_DATE = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss')