SELECT B.PARAM_NAME, B.PARA_CODE2, B.PARA_CODE3,B.PARA_CODE4,Count(B.PARA_CODE2) SUN,Count(B.PARA_CODE2)*B.PARA_CODE3 SCORE
  FROM CHNL_CU_REGI A, TD_S_COMMPARA B
 WHERE A.CUMU_ID = :CUMU_ID
   AND A.CUMU_ACYC BETWEEN TO_CHAR(SYSDATE, 'yyyymm') - 3 AND
       TO_CHAR(SYSDATE, 'yyyymm') - 1
   AND B.PARA_CODE2 = A.OPER_CODE
   AND A.CAL_FLAG = '2'
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = '17'
   AND B.PARA_CODE1 = 'CUMU'
	 AND B.PARA_CODE2 = :PARA_CODE2
	 GROUP BY B.PARAM_NAME, B.PARA_CODE2, B.PARA_CODE3,B.PARA_CODE4