SELECT TRADE_ID,
       ACCEPT_MONTH,
       OPER_NUMBER,
       TO_CHAR(VERIFY_TIME, 'YYYY-MM-DD hh24:mi:ss') VERIFY_TIME,
       TO_CHAR(ORDER_TIME, 'YYYY-MM-DD hh24:mi:ss') ORDER_TIME,
       ORDER_CODE,
       BIZ_CATALOG,
       OPER_IDENTIFY,
       SERIAL_NUMBER,
       PROMOTION_CODE,
       TO_CHAR(START_DATE, 'YYYY-MM-DD hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD hh24:mi:ss') END_DATE,
       REMARK
  FROM TF_B_TRADE_CUSTSALE_PROMOTION
 WHERE ORDER_CODE = :ORDER_CODE