--IS_CACHE=Y
SELECT A.ELEMENT_ID_A,A.ELEMENT_ID_B
FROM TD_B_ELEMENT_LIMIT A 
WHERE A.ELEMENT_TYPE_CODE_A='D'
AND A.ELEMENT_TYPE_CODE_B='D' 
AND (A.ELEMENT_ID_A = :ELEMENT_ID OR A.ELEMENT_ID_B = :ELEMENT_ID)
AND (A.ELEMENT_ID_A IN(:ELEMENT_ID_A) OR A.ELEMENT_ID_B IN (:ELEMENT_ID_A))
AND A.LIMIT_TAG='0'
AND SYSDATE BETWEEN START_DATE AND END_DATE
AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')