SELECT A.LOG_ID, 
F_RES_GETCODENAME('td_m_restrade',A.RES_TRADE_ID,'','') TRADE_TYPE, A.RES_TRADE_ID, 
F_RES_GETCODENAME('depart_id',A.DEPART_ID_O,'','') STOCK_NAME, 
TO_CHAR(A.OPER_DATE, 'YYYY-MM-DD HH24:MI') OPER_DATE,
F_RES_GETCODENAME('staff_id', A.OPER_STAFF_ID, '', '') OPER_STAFF_NAME
FROM TF_B_RES_ASSIGN_LOG A
WHERE 1 = 1 
   AND A.LOG_ID =:LOG_ID
   AND A.RES_TRADE_ID=:TRADE_TYPE
   AND A.AUDIT_TAG=:AUDIT_TAG
   AND A.DEPART_ID_O=:STOCK_ID
   AND A.OPER_STAFF_ID=:OPER_STAFF_ID