DELETE FROM TI_B_USER_SVC T
 WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
 AND T.SERVICE_ID IN(SELECT b.PARA_CODE1 FROM TD_S_COMMPARA b WHERE b.SUBSYS_CODE='CSM' AND b.PARAM_ATTR ='555' AND b.PARAM_CODE ='REMIND')