SELECT * FROM TF_F_USER_DISCNT WHERE USER_ID = :USER_ID AND PRODUCT_ID IN 
(SELECT TO_NUMBER(PARA_CODE1) FROM TD_S_COMMPARA WHERE SUBSYS_CODE='CSM'
AND PARAM_ATTR='199' AND PARAM_CODE='0' AND END_DATE > SYSDATE)
AND END_DATE >SYSDATE