INSERT INTO TF_B_TRADE_RELA
  (ORDER_ID_A, TRADE_ID_A, ORDER_ID_B, TRADE_ID_B, TYPE, CTRL_TYPE)
VALUES
  (TO_NUMBER(:RSRV_STR1),
   TO_NUMBER(:RSRV_STR2),
   TO_NUMBER(:RSRV_STR3),
   TO_NUMBER(:RSRV_STR4),
   :RSRV_STR5,
   :RSRV_STR6)