SELECT ORDER_ID,
       TRADE_ID,
       ACCEPT_MONTH,
       PRODUCT_ID,
       ACCOUNT_DATE,
       ACCEPT_DATE,
       SERIAL_NUMBER,
       SCORE_VALUE
  FROM TF_B_SCORE_ACCOUNTS
 WHERE TRADE_ID = TO_NUMBER( :TRADE_ID )
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))