SELECT *
  FROM (SELECT a.trade_id,
               a.order_id,
               a.bpm_id,
               a.trade_type_code,
               a.in_mode_code,
               a.priority,
               a.next_deal_tag,
               a.product_id,
               a.brand_code,
               a.user_id,
               a.cust_id,
               a.acct_id,
               a.serial_number,
               a.cust_name,
               to_char(a.accept_date, 'yyyy-mm-dd hh24:mi:ss') accept_date,
               a.accept_month,
               a.trade_staff_id,
               a.trade_depart_id,
               a.trade_city_code,
               a.trade_eparchy_code,
               a.term_ip,
               a.eparchy_code,
               a.city_code,
               a.olcom_tag,
               to_char(a.exec_time, 'yyyy-mm-dd hh24:mi:ss') exec_time,
               to_char(a.finish_date, 'yyyy-mm-dd hh24:mi:ss') finish_date,
               a.oper_fee,
               a.foregift,
               a.advance_pay,
               a.Invoice_No,
               a.fee_state,
               to_char(a.fee_time, 'yyyy-mm-dd hh24:mi:ss') fee_time,
               a.fee_staff_id,
               a.cancel_tag,
               a.process_tag_set,
               a.rsrv_str1,
               a.rsrv_str2,
               a.rsrv_str3,
               a.rsrv_str4,
               a.rsrv_str5,
               a.rsrv_str6,
               a.rsrv_str7,
               a.rsrv_str8,
               a.rsrv_str9,
               a.rsrv_str10,
               a.remark
          FROM tf_b_trade a
         WHERE a.user_id = to_number(:USER_ID)
           AND (a.trade_type_code = :TRADE_TYPE_CODE OR  :TRADE_TYPE_CODE = '-1')
           AND (a.accept_date >=
               to_date(:START_DATE, 'yyyy-mm-dd hh24:mi:ss') OR  :START_DATE IS NULL)
           AND (a.accept_date <= to_date(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')  +1 OR :END_DATE IS NULL)
        UNION ALL
        SELECT a.trade_id,
               a.order_id,
               a.bpm_id,
               a.trade_type_code,
               a.in_mode_code,
               a.priority,
               a.next_deal_tag,
               a.product_id,
               a.brand_code,
               a.user_id,
               a.cust_id,
               a.acct_id,
               a.serial_number,
               a.cust_name,
               to_char(a.accept_date, 'yyyy-mm-dd hh24:mi:ss') accept_date,
               a.accept_month,
               a.trade_staff_id,
               a.trade_depart_id,
               a.trade_city_code,
               a.trade_eparchy_code,
               a.term_ip,
               a.eparchy_code,
               a.city_code,
               a.olcom_tag,
               to_char(a.exec_time, 'yyyy-mm-dd hh24:mi:ss') exec_time,
               to_char(a.finish_date, 'yyyy-mm-dd hh24:mi:ss') finish_date,
               a.oper_fee,
               a.foregift,
               a.advance_pay,
               a.Invoice_No,
               a.fee_state,
               to_char(a.fee_time, 'yyyy-mm-dd hh24:mi:ss') fee_time,
               a.fee_staff_id,
               a.cancel_tag,
               a.process_tag_set,
               a.rsrv_str1,
               a.rsrv_str2,
               a.rsrv_str3,
               a.rsrv_str4,
               a.rsrv_str5,
               a.rsrv_str6,
               a.rsrv_str7,
               a.rsrv_str8,
               a.rsrv_str9,
               a.rsrv_str10,
               a.remark
          FROM tf_bh_trade a
         WHERE a.user_id = to_number(:USER_ID)
           AND (a.trade_type_code = :TRADE_TYPE_CODE OR  :TRADE_TYPE_CODE = '-1')
           AND (a.accept_date >=
               to_date(:START_DATE, 'yyyy-mm-dd hh24:mi:ss') OR  :START_DATE IS NULL)
           AND (a.accept_date <= to_date(:END_DATE, 'yyyy-mm-dd hh24:mi:ss') +1 OR :END_DATE IS NULL))
 ORDER BY accept_date
