SELECT T.SERVICE_ID FROM TF_F_USER_SVC T WHERE T.USER_ID = TO_NUMBER(:USER_ID) 
AND T.PARTITION_ID =  MOD(TO_NUMBER(:USER_ID),10000)
AND T.SERVICE_ID=22
AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE