SELECT A.DEPART_NAME,A.DEPART_CODE,C.AREA_NAME,C.AREA_CODE,D.BRAND_CODE,D.IN_MODE_CODE,A.AREA_CODE,COUNT(D.TRADE_ID) SUMS
  FROM TD_M_DEPART A,TD_M_AREA C,
      (SELECT * FROM TF_B_TRADE
     UNION ALL
       SELECT * FROM TF_BH_TRADE
　WHERE ACCEPT_MONTH = TO_NUMBER(TO_CHAR(TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),'MM'))
) D,TD_S_TRADETYPE E
 where 
    A.DEPART_ID = D.TRADE_DEPART_ID  
       AND A.AREA_CODE = C.AREA_CODE            
   AND D.TRADE_TYPE_CODE = E.TRADE_TYPE_CODE    
　 AND D.TRADE_TYPE_CODE IN ('10','11')
   AND A.DEPART_ID = :DEPART_ID
   AND D.ACCEPT_DATE >= TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')
   AND D.ACCEPT_DATE <  TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS')
   GROUP BY A.DEPART_CODE,A.DEPART_NAME,C.AREA_NAME,C.AREA_CODE,D.IN_MODE_CODE,D.BRAND_CODE,A.AREA_CODE