select
   to_char(trade_id)trade_id,
   to_char(accept_month) accept_month,
   to_char(user_id) user_id,
   to_char(cust_id) cust_id,
   to_char(usecust_id) usecust_id,
   brand_code ,
   to_char(product_id),
   eparchy_code,
   city_code,
   city_code_a,
   user_passwd,
   user_diff_code,
   user_type_code,
   user_tag_set,
   user_state_codeset,
   net_type_code,
   serial_number,
   to_char(score_value)core_value,
   contract_id,
   to_char(credit_class)credit_class,
   to_char(basic_credit_value) basic_credit_value,
   to_char(credit_value) credit_value,
   credit_control_id,
   acct_tag ,
   prepay_tag ,
   mpute_month_fee,
   to_char(mpute_date,'yyyy-mm-dd hh24:mi:ss') mpute_date,
   to_char(first_call_time,'yyyy-mm-dd hh24:mi:ss') first_call_time,
   to_char(last_stop_time,'yyyy-mm-dd hh24:mi:ss') last_stop_time,
   to_char(changeuser_date,'yyyy-mm-dd hh24:mi:ss') changeuser_date,
   in_net_mode ,
   to_char(in_date,'yyyy-mm-dd hh24:mi:ss') in_date,
   in_staff_id ,
   in_depart_id,
   open_mode,
   to_char(open_date,'yyyy-mm-dd hh24:mi:ss')open_date,
   open_staff_id,
   open_depart_id,
   develop_staff_id,
   to_char(develop_date,'yyyy-mm-dd hh24:mi:ss') develop_date,
   develop_depart_id,
   develop_city_code,
   develop_eparchy_code,
   develop_no,
   to_char(assure_cust_id)assure_cust_id,
   assure_type_code,
   to_char(assure_date,'yyyy-mm-dd hh24:mi:ss')assure_date,
   remove_tag,
   to_char(pre_destroy_time,'yyyy-mm-dd hh24:mi:ss')pre_destroy_time,
   to_char(destroy_time,'yyyy-mm-dd hh24:mi:ss') destroy_time,
   remove_eparchy_code,
   remove_city_code,
   remove_depart_id,
   remove_reason_code,
   modify_tag,
   to_char(update_time,'yyyy-mm-dd hh24:mi:ss')update_time,
   update_staff_id ,
   update_depart_id ,
   remark ,
   to_char(rsrv_num1)rsrv_num1,
   to_char(rsrv_num2) rsrv_num2,
   to_char(rsrv_num3) rsrv_num3,
   to_char(rsrv_num4) rsrv_num4,
   to_char(rsrv_num5) rsrv_num5,
   rsrv_str1,
   rsrv_str2,
   rsrv_str3,
   rsrv_str4,
   rsrv_str5,
   rsrv_str6,
   rsrv_str7,
   rsrv_str8,
   rsrv_str9,
   rsrv_str10,
   to_char(rsrv_date1,'yyyy-mm-dd hh24:mi:ss') rsrv_date1,
   to_char(rsrv_date2,'yyyy-mm-dd hh24:mi:ss') rsrv_date2,
   to_char(rsrv_date3,'yyyy-mm-dd hh24:mi:ss') rsrv_date3,
   rsrv_tag1,
   rsrv_tag2,
   rsrv_tag3
   from tf_b_trade_user t
   where t.trade_id=:TRADE_ID