SELECT T.*
  FROM TF_B_TRADE T
 WHERE (T.SERIAL_NUMBER = :SERIAL_NUMBER OR
       T.SERIAL_NUMBER = 'KD_' || :SERIAL_NUMBER)
   AND T.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND T.ACCEPT_DATE BETWEEN
       TO_DATE(:CONTACT_TIME, 'YYYY-MM-DD HH24:MI:SS') AND
       (TO_DATE(:CONTACT_TIME, 'YYYY-MM-DD HH24:MI:SS') + 1 / 24)
 ORDER BY T.ACCEPT_DATE DESC
