SELECT SERIAL_NUMBER,TRADE_TYPE_CODE,RSRV_STR2
  FROM TF_B_TRADE
 WHERE TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND SERIAL_NUMBER = :SERIAL_NUMBER
   AND RSRV_STR2 = :SUB_ORDER_ID
UNION
SELECT SERIAL_NUMBER,TRADE_TYPE_CODE,RSRV_STR2
  FROM TF_BH_TRADE
 WHERE TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND SERIAL_NUMBER = :SERIAL_NUMBER
   AND RSRV_STR2 = :SUB_ORDER_ID