SELECT TO_CHAR(trade_id) trade_id,
       accept_month,
       TO_CHAR(batch_id) batch_id,
       TO_CHAR(order_id) order_id,
       TO_CHAR(prod_order_id) prod_order_id,
       bpm_id,
       user_id_b,
       to_char(campn_id) campn_id,
       trade_type_code,
       priority,
       subscribe_type,
       subscribe_state,
       next_deal_tag,
       in_mode_code,
       TO_CHAR(cust_id) cust_id,
       cust_name,
       TO_CHAR(user_id) user_id,
       TO_CHAR(acct_id) acct_id,
       serial_number,
       net_type_code,
       decode(substr(eparchy_code,0,1),'0',substr(eparchy_code,2,length(eparchy_code)),eparchy_code) eparchy_code,
       city_code,
       product_id,
       brand_code,
       TO_CHAR(accept_date, 'yyyy-mm-dd hh24:mi:ss') accept_date,
       trade_staff_id,
       trade_depart_id,
       trade_city_code,
       trade_eparchy_code,
       term_ip,
       TO_CHAR(oper_fee) oper_fee,
       TO_CHAR(foregift) foregift,
       TO_CHAR(advance_pay) advance_pay,
       invoice_no,
       fee_state,
       TO_CHAR(fee_time, 'yyyy-mm-dd hh24:mi:ss') fee_time,
       fee_staff_id,
       process_tag_set,
       olcom_tag,
       TO_CHAR(finish_date, 'yyyy-mm-dd hh24:mi:ss') finish_date,
       TO_CHAR(exec_time, 'yyyy-mm-dd hh24:mi:ss') exec_time,
       exec_action,
       exec_result,
       exec_desc,
       cancel_tag,
       TO_CHAR(cancel_date, 'yyyy-mm-dd hh24:mi:ss') cancel_date,
       cancel_staff_id,
       cancel_depart_id,
       cancel_city_code,
       cancel_eparchy_code,
       TO_CHAR(update_time, 'yyyy-mm-dd hh24:mi:ss') update_time,
       update_staff_id,
       update_depart_id,
       remark,
       rsrv_str1,
       rsrv_str2,
       rsrv_str3,
       rsrv_str4,
       rsrv_str5,
       rsrv_str6,
       rsrv_str7,
       rsrv_str8,
       rsrv_str9,
       rsrv_str10
  FROM tf_b_trade
 WHERE trade_id = TO_NUMBER(:TRADE_ID)
 AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))