SELECT T.SERIAL_NUMBER SERIAL_NUMBER_B,
       T.USER_ID       USER_ID_B,
       B.USER_ID_A     USER_ID_A
  FROM TF_B_TRADE T, TD_S_COMMPARA A, TF_B_TRADE_RELATION B
 WHERE T.CUST_ID = :CUST_ID
   AND T.TRADE_TYPE_CODE = TO_NUMBER(A.PARAM_CODE)
   AND A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 9025
   AND A.END_DATE > SYSDATE
   AND T.TRADE_ID = B.TRADE_ID
   AND B.RELATION_TYPE_CODE = '47'
   AND B.USER_ID_B = T.USER_ID