select * from TF_B_TRADE_PLATSVC 
where ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = TO_NUMBER(:TRADE_ID)
 --  AND BIZ_TYPE_CODE = :BIZ_TYPE_CODE
and service_id in (98003701,98006701)