UPDATE TF_F_USER_OTHER SET 
END_DATE = to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss') , UPDATE_TIME = to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, REMARK = :REMARK
WHERE 
PARTITION_ID = MOD(to_number(:USER_ID),10000) and USER_ID = to_number(:USER_ID) and RSRV_VALUE_CODE = :RSRV_VALUE_CODE  and RSRV_VALUE = :RSRV_VALUE and START_DATE = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss')