SELECT to_char(TRADE_ID) TRADE_ID,to_char(BATCH_ID) BATCH_ID,to_char(BPM_ID) BPM_ID,TRADE_TYPE_CODE,IN_MODE_CODE,PRIORITY,SUBSCRIBE_STATE,NEXT_DEAL_TAG,PRODUCT_ID,BRAND_CODE,to_char(USER_ID) USER_ID,to_char(CUST_ID) CUST_ID,to_char(ACCT_ID) ACCT_ID,SERIAL_NUMBER,CUST_NAME,to_char(ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,ACCEPT_MONTH,TRADE_STAFF_ID,TRADE_DEPART_ID,TRADE_CITY_CODE,TRADE_EPARCHY_CODE,TERM_IP,EPARCHY_CODE,CITY_CODE,OLCOM_TAG,to_char(EXEC_TIME,'yyyy-mm-dd hh24:mi:ss') EXEC_TIME,to_char(FINISH_DATE,'yyyy-mm-dd hh24:mi:ss') FINISH_DATE,to_char(OPER_FEE) OPER_FEE,to_char(FOREGIFT) FOREGIFT,to_char(ADVANCE_PAY) ADVANCE_PAY,INVOICE_NO,FEE_STATE,to_char(FEE_TIME,'yyyy-mm-dd hh24:mi:ss') FEE_TIME,FEE_STAFF_ID,CANCEL_TAG,to_char(CANCEL_DATE,'yyyy-mm-dd hh24:mi:ss') CANCEL_DATE,CANCEL_STAFF_ID,CANCEL_DEPART_ID,CANCEL_CITY_CODE,CANCEL_EPARCHY_CODE,PROCESS_TAG_SET,
f_sys_getcodename('staff_id',TRADE_STAFF_ID,NULL,NULL)  RSRV_STR1,
f_sys_getcodename('depart_id',TRADE_DEPART_ID,NULL,NULL) RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,REMARK
  FROM TF_BH_TRADE
where ACCEPT_DATE+0>= trunc(to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss'))
  AND ACCEPT_DATE+0< trunc(to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'))+1
 AND (cancel_tag='0' OR cancel_tag='2' OR ((cancel_tag='1')AND(EXEC_TIME>FINISH_DATE)))
 AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE
 AND SERIAL_NUMBER = :SERIAL_NUMBER
UNION ALL
SELECT to_char(TRADE_ID) TRADE_ID,to_char(BATCH_ID) BATCH_ID,to_char(BPM_ID) BPM_ID,TRADE_TYPE_CODE,IN_MODE_CODE,PRIORITY,SUBSCRIBE_STATE,NEXT_DEAL_TAG,PRODUCT_ID,BRAND_CODE,to_char(USER_ID) USER_ID,to_char(CUST_ID) CUST_ID,to_char(ACCT_ID) ACCT_ID,SERIAL_NUMBER,CUST_NAME,to_char(ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,ACCEPT_MONTH,TRADE_STAFF_ID,TRADE_DEPART_ID,TRADE_CITY_CODE,TRADE_EPARCHY_CODE,TERM_IP,EPARCHY_CODE,CITY_CODE,OLCOM_TAG,to_char(EXEC_TIME,'yyyy-mm-dd hh24:mi:ss') EXEC_TIME,to_char(FINISH_DATE,'yyyy-mm-dd hh24:mi:ss') FINISH_DATE,to_char(OPER_FEE) OPER_FEE,to_char(FOREGIFT) FOREGIFT,to_char(ADVANCE_PAY) ADVANCE_PAY,INVOICE_NO,FEE_STATE,to_char(FEE_TIME,'yyyy-mm-dd hh24:mi:ss') FEE_TIME,FEE_STAFF_ID,CANCEL_TAG,to_char(CANCEL_DATE,'yyyy-mm-dd hh24:mi:ss') CANCEL_DATE,CANCEL_STAFF_ID,CANCEL_DEPART_ID,CANCEL_CITY_CODE,CANCEL_EPARCHY_CODE,PROCESS_TAG_SET,
f_sys_getcodename('staff_id',TRADE_STAFF_ID,NULL,NULL) RSRV_STR1, f_sys_getcodename('depart_id',TRADE_DEPART_ID,NULL,NULL)  RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,REMARK
  FROM TF_B_TRADE
where ACCEPT_DATE+0>= trunc(to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss'))
  AND ACCEPT_DATE+0< trunc(to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'))+1
 AND (cancel_tag='0' OR cancel_tag='2' OR ((cancel_tag='1')AND(EXEC_TIME>FINISH_DATE)))
 AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE
 AND SERIAL_NUMBER = :SERIAL_NUMBER