SELECT A.FEE_STAFF_ID STAFF_ID, 
       A.TRADE_DEPART_ID DEPART_ID,
       B.TRADE_ID,
       B.TRADE_TYPE_CODE,
       B.SERIAL_NUMBER,
       B.FEE_TIME,
       B.OPER_FEE + B.FOREGIFT + B.ADVANCE_PAY TRADE_FEE,
       -1 TRADE_NUM,
       '返销' CANCEL_TAG,
       B.FEE_STAFF_ID CANCEL_STAFF_ID 
  FROM TF_BH_TRADE A ,TF_BH_TRADE B
 WHERE B.CANCEL_TAG = '2'   
   AND B.ACCEPT_DATE >= TO_DATE(:START_DATE,'YYYYMMDD')
   AND B.ACCEPT_DATE <  TO_DATE(:END_DATE,'YYYYMMDD') + 1
   AND A.TRADE_ID = B.TRADE_ID  
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(TO_CHAR(B.TRADE_ID),5,2))
   AND A.CANCEL_TAG = '1'   
   AND A.TRADE_DEPART_ID >= :START_DEPART_ID
   AND A.TRADE_DEPART_ID <= :END_DEPART_ID