SELECT T1.*
  FROM TF_BH_TRADE T1
 WHERE 1 = 1
   AND T1.TRADE_TYPE_CODE = '14'
   AND T1.FINISH_DATE BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') AND TRUNC(SYSDATE,'MM')
   AND T1.SERIAL_NUMBER = :SERIAL_NUMBER
