SELECT /*+ use_nl(b t)*/T.SERIAL_NUMBER,T.USER_ID,T.SERIAL_NUMBER,T.CUST_ID,T.TRADE_STAFF_ID,
                        T.TRADE_DEPART_ID,T.TRADE_ID
  FROM TF_BH_TRADE T
 WHERE T.SUBSCRIBE_STATE = :SUBSCRIBE_STATE
   AND T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND T.FINISH_DATE >= TRUNC(SYSDATE, 'DD')
   AND T.FINISH_DATE < TRUNC(SYSDATE, 'DD') + 1 
