SELECT A.INFO_ID,
       A.INFO_CHILD_TYPE,
       A.INFO_SIGN,
       A.INFO_TOPIC,
       A.INFO_TYPE,
       A.INFO_STATUS,
       A.INFO_LEVEL,
       A.INFO_URL,
       A.INFO_CONTENT,
       A.INFO_AUTH,
       TO_CHAR(A.INFO_SEND_TIME, 'YYYY-MM-DD HH24:MI:SS') INFO_SEND_TIME,
       TO_CHAR(A.END_TIME, 'YYYY-MM-DD HH24:MI:SS') END_TIME,
       B.INST_ID,
       B.RECE_OBJ,
       B.RECE_OBJ_TYPE,
       B.INST_STATUS,
       TO_CHAR(B.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(B.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_INFO A, TF_F_INFO_INSTANCE B
 WHERE A.INFO_ID = B.INFO_ID
   AND A.INFO_TOPIC LIKE '%' || :INFO_TOPIC || '%'
   AND A.INFO_TYPE = :INFO_TYPE
   AND A.INFO_CHILD_TYPE IN ('40','41','42','43','44','45')
   AND A.INFO_STATUS <> :INFO_STATUS
   AND B.RECE_OBJ_TYPE = :RECE_OBJ_TYPE
   AND B.RECE_OBJ = :STAFF_ID
   AND B.INST_ID = :INST_ID
 ORDER BY B.SEND_TIME DESC,B.INST_ID DESC