SELECT B.TERMINAL_ID,  (SELECT corp_name FROM TD_R_TERMINAL_CORP WHERE corp_no=B.DEALER_CODE AND COOP_TYPE_CODE ='05' ) DEALER,
F_RES_GETCODENAME('td_m_res_para', '4001', 'DEAL_TYPE', B.DEAL_TYPE) DEAL_TYPE,
B.DEAL_PRICE, TO_CHAR(B.DEAL_TIME, 'YYYY-MM-DD') DEAL_TIME,
DECODE(B.UP_FLAG,'0','未上传','1','已上传','2','上传失败') UP_FLAG, OPER_TRADE_ID,
F_RES_GETCODENAME('td_m_res_para', '4001', 'RESULT', B.RESULT) RESULT, 
F_RES_GETCODENAME('td_m_res_para', '4001', 'RECERRCODE', B.UNSUC_REASON) UNSUC_REASON,UNSUC_COMMENT
FROM  TF_B_TERMINAL_WHOLESALES_LOG B
WHERE 1=1
AND B.DEALER_CODE = :DEALER_CODE
AND B.TERMINAL_ID =:TERMINAL_ID
AND B.DEAL_TYPE =:DEAL_TYPE
AND B.UP_FLAG =:UP_FLAG
AND B.RESULT =:RESULT
AND B.UNSUC_REASON =:UNSUC_REASON