  SELECT 
  PRODUCT_OFFERING_ID, 
  PRODUCT_CODE, 
  PO_ORDER_NUMBER, 
  CUSTOMER_PHONE,
  MEM_NUMBER, 
  ROLE_CODE_B, 
  POID_CODE, 
  POID_LABLE,
  MEM_LABLE,
  FINISH_TAG, 
  TO_CHAR(ADD_TIME, 'YYYY-MM-DD HH24:MI:SS') ADD_TIME,
  REMARK, 
  RSRV_STR1, 
  RSRV_STR2,
  RSRV_STR3,    
  RSRV_STR4, 
  RSRV_STR5, 
  UUID, 
  MEM_ORDER_NUMBER, 
  RSRV_STR6, 
  RSRV_STR7, 
  RSRV_STR8, 
  RSRV_STR9, 
  RSRV_STR10, 
  TO_CHAR(EFF_TIME, 'YYYY-MM-DD HH24:MI:SS') EFF_TIME,
  TO_CHAR(EXP_TIME, 'YYYY-MM-DD HH24:MI:SS') EXP_TIME,  
  ACTION
  FROM TF_B_FAMILY_OTHER
  WHERE PRODUCT_OFFERING_ID = :PRODUCT_OFFERING_ID
  AND  CUSTOMER_PHONE = :CUSTOMER_PHONE
  ORDER BY EFF_TIME DESC