SELECT POID_CODE,POID_LABLE,MEM_LABLE FROM  TF_B_FAMILY_OTHER
			WHERE 1=1
			AND FINISH_TAG='1'
			AND MEM_NUMBER=:MEM_NUMBER
			AND PRODUCT_OFFERING_ID=:PRODUCT_OFFERING_ID
			ORDER BY ADD_TIME DESC
