INSERT INTO TI_B_CONTRACT_UNORDER(PROVINCE_ID,BIZ_TYPE,TRADE_ID,SERIAL_NUMBER,CONTRACT_TYPE,RESOURCE_CODE,CONSUME_LIMIT,CONTRACT_DURATION,IMEI,
VALID_START_DATE,TRADE_STAFF_ID,TRADE_DEPART_ID,TRADE_CITY_CODE,TRADE_EPARCHY_CODE,ACCEPT_DATE)
 VALUES(:PROVINCE_ID,:BIZ_TYPE,:TRADE_ID,:SERIAL_NUMBER,:CONTRACT_TYPE,:RESOURCE_CODE,:CONSUME_LIMIT,:CONTRACT_DURATION,:IMEI,
TO_DATE(:VALID_START_DATE,'YYYY-MM-DD HH24:MI:SS'),:TRADE_STAFF_ID,:TRADE_DEPART_ID,:TRADE_CITY_CODE,:TRADE_EPARCHY_CODE,
TO_DATE(:ACCEPT_DATE,'YYYY-MM-DD HH24:MI:SS'))