--IS_CACHE=Y
select t.SEQ_ID, t.PARAM_CODE, t.TOP_PARAM_CODE, t.TOP_PARAM_VALUE, t.OPTION_NAME, t.OPTION_VALUE, t.UPDATE_TIME, t.UPDATE_STAFF_ID, t.REMARK from TD_S_BOUND_DATA t where  TOP_PARAM_CODE=:PROVINCE_ATTR_CODE AND TOP_PARAM_VALUE =:PROVINCE_ATTR_VALUE AND PARAM_CODE =:CITY_ATTR_CODE
