--IS_CACHE=Y
select t.SEQ_ID, t.PARAM_CODE, t.TOP_PARAM_CODE, t.TOP_PARAM_VALUE, t.OPTION_NAME, t.OPTION_VALUE, t.UPDATE_TIME, t.UPDATE_STAFF_ID, t.REMARK from TD_S_BOUND_DATA t where  param_code=:PARAMCODE
