--IS_CACHE=Y
SELECT TRADE_TYPE_CODE,
       IN_MODE_CODE,
       ID_TYPE,
       ID,
       SMS_TYPE,
       NOTICE_CONTENT,
       START_TIME,
       END_TIME,
       UPDATE_TIME,
       UPDATE_DEPART_ID,
       UPDATE_STAFF_ID,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4
  FROM TD_B_SEC_AFFIRM
 WHERE (TRADE_TYPE_CODE = :TRADE_TYPE_CODE OR TRADE_TYPE_CODE = '-1')
   AND IN_MODE_CODE = :IN_MODE_CODE
   AND ID_TYPE = :ID_TYPE
   AND ID = :ID
   AND SYSDATE BETWEEN START_TIME AND END_TIME