SELECT T.INST_ID INST_ID,
       T.SERVICE_ID OFFER_CODE,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       A.PARAM_CODE PARAM_CODE,
       A.PARA_CODE1 PARA_CODE1,
       A.PARA_CODE2 PARA_CODE2,
       A.PARA_CODE3 PARA_CODE3,
       B.INST_TYPE INST_TYPE,
       B.PROD_INST_ID PROD_INST_ID
  FROM TF_F_USER_SVC T, TD_S_COMMPARA A, TF_F_INSTANCE_PF B
 WHERE T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.END_DATE > SYSDATE
   AND A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 9014
   AND A.EPARCHY_CODE IN ('ZZZZ', '0898')
   AND A.END_DATE > SYSDATE
   AND TO_CHAR(T.SERVICE_ID) = A.PARAM_CODE
   AND B.INST_ID = T.INST_ID
   AND B.INST_TYPE = 'P'
UNION
SELECT T.INST_ID INST_ID,
       T.DISCNT_CODE OFFER_CODE,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       A.PARAM_CODE PARAM_CODE,
       A.PARA_CODE1 PARA_CODE1,
       A.PARA_CODE2 PARA_CODE2,
       A.PARA_CODE3 PARA_CODE3,
       B.INST_TYPE INST_TYPE,
       B.PROD_INST_ID PROD_INST_ID
  FROM TF_F_USER_DISCNT T, TD_S_COMMPARA A, TF_F_INSTANCE_PF B
 WHERE T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.END_DATE > SYSDATE
   AND A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 9013
   AND A.EPARCHY_CODE IN ('ZZZZ', '0898')
   AND A.END_DATE > SYSDATE
   AND TO_CHAR(T.DISCNT_CODE) = A.PARAM_CODE
   AND B.INST_ID = T.INST_ID
   AND B.INST_TYPE = 'P'