SELECT COUNT(1) as ROW_COUMT
  FROM TF_F_USER_SALE_GOODS A
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND PRODUCT_ID = :PARAM_CODE
   AND A.PACKAGE_ID = :PARA_CODE1
   AND A.RES_CODE = :PARA_CODE2
   AND A.RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND RSRV_DATE2 > SYSDATE