--IS_CACHE=Y
SELECT PACKAGE_ID,SP_SVC_ID,CP_ID,PACKAGE_TYPE,PACKAGE_NAME,PACKAGE_DESC,PACKAGE_AREA_CODE,BIZ_TYPE_CODE,ACCESS_MODEL,to_char(PRICE) PRICE,BILLING_TYPE,BIZ_STATUS,AREA_CODE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,REMARK,UPDATE_STAFF_ID,UPDATE_DEPART_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TD_M_SPPACKAGE
 WHERE sp_svc_id = :SP_SVC_ID
   AND biz_status NOT IN ('N','E')