INSERT INTO TF_F_USER_SVCSTATE
  (PARTITION_ID,
   USER_ID,
   SERVICE_ID,
   MAIN_TAG,
   STATE_CODE,
   START_DATE,
   END_DATE,
   UPDATE_TIME)
  SELECT PARTITION_ID,
         USER_ID,
         SERVICE_ID,
         MAIN_TAG,
         '0',
         START_DATE,
         END_DATE,
         SYSDATE
    FROM TF_F_USER_SVC A
   WHERE USER_ID = TO_NUMBER(:USER_ID)
     AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND END_DATE > SYSDATE
     AND EXISTS
   (SELECT 1
            FROM TD_S_SERVICESTATE
           WHERE SERVICE_ID = A.SERVICE_ID
             AND A.START_DATE BETWEEN START_DATE AND END_DATE)