--IS_CACHE=Y
SELECT DEVICE_MODEL_CODE PARA_CODE,DEVICE_MODEL_CODE||'|'||DEVICE_MODEL PARA_NAME 
	FROM TD_S_RES_MODEL WHERE 1=1 
	AND RES_TYPE_CODE = :RES_TYPE_CODE 
	AND CARD_KIND_CODE = :CARD_KIND_CODE
	AND BRAND_CODE = :BRAND_CODE 
	AND VALID_TAG = :VVALID_TAG 
	ORDER BY DEVICE_MODEL