SELECT T.GROUP_ID RSRV_STR3, S.TRADE_CITY_CODE RSRV_STR4, S.DEPART_ID RSRV_STR5, S.PRODUCT_ID RSRV_STR6, T.ACCEPT_TIME RSRV_DATE1, S.STAFF_ID TRADE_STAFF_ID
FROM TF_B_EOP_SUBSCRIBE T, TF_B_EOP_NODE S, TF_B_EOP_EOMS_DETAIL D
WHERE
T.BPM_TEMPLET_ID IN('EDIRECTLINECHANGEDLINENEW', 'EDIRECTLINEOPENNEW', 'EDIRECTLINECANCELNEW', 'DIRECTLINECHANGEDLINENEW', 'DIRECTLINEOPENNEW', 'DIRECTLINECANCELNEW', 'DIRECTLINECHANGEINCOME')
AND T.IBSYSID = S.IBSYSID
AND D.IBSYSID = T.IBSYSID
AND D.TRADE_ID = :TRADE_ID
UNION ALL
SELECT T.GROUP_ID RSRV_STR3, S.TRADE_CITY_CODE RSRV_STR4, S.DEPART_ID RSRV_STR5, S.PRODUCT_ID RSRV_STR6, T.ACCEPT_TIME RSRV_DATE1, S.STAFF_ID TRADE_STAFF_ID
FROM TF_BH_EOP_SUBSCRIBE T, TF_BH_EWE_NODE S, TF_BH_EOP_EOMS_DETAIL D
WHERE
T.BPM_TEMPLET_ID IN('EDIRECTLINECHANGEDLINENEW', 'EDIRECTLINEOPENNEW', 'EDIRECTLINECANCELNEW', 'DIRECTLINECHANGEDLINENEW', 'DIRECTLINEOPENNEW', 'DIRECTLINECANCELNEW', 'DIRECTLINECHANGEINCOME')
AND T.IBSYSID = S.IBSYSID
AND D.IBSYSID = T.IBSYSID
AND D.TRADE_ID = :TRADE_ID