INSERT INTO TF_B_TRADE_USER_SPECIALEPAY(TRADE_ID, ACCEPT_MONTH, USER_ID, USER_ID_A, ACCT_ID, ACCT_ID_B, PAYITEM_CODE, START_CYCLE_ID, END_CYCLE_ID, BIND_TYPE, LIMIT_TYPE, LIMIT, COMPLEMENT_TAG, MODIFY_TAG, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, RSRV_STR1, RSRV_STR2, RSRV_STR3) 
SELECT to_char(:TRADE_ID) TRADE_ID, TO_NUMBER(SUBSTR(:TRADE_ID,5,2)) , USER_ID,  USER_ID_A,  ACCT_ID, ACCT_ID_B, PAYITEM_CODE, START_CYCLE_ID, END_CYCLE_ID, BIND_TYPE, LIMIT_TYPE,  LIMIT, COMPLEMENT_TAG, :MODIFY_TAG, TO_DATE(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'), UPDATE_STAFF_ID, UPDATE_DEPART_ID, RSRV_STR1, RSRV_STR2, RSRV_STR3
FROM TF_F_USER_SPECIALEPAY T
WHERE T.USER_ID=:USER_ID
AND T.ACCT_ID=:ACCT_ID
AND T.END_CYCLE_ID>=TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'))
AND T.END_CYCLE_ID>T.START_CYCLE_ID