SELECT *
  FROM TF_F_USER_SPECIALEPAY
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND :END_CYCLE_ID < END_CYCLE_ID
   AND USER_ID_A NOT IN
       (SELECT USER_ID_A
          FROM TF_F_RELATION_UU U
         WHERE U.USER_ID_B = USER_ID
           AND (U.RELATION_TYPE_CODE = '90' OR U.RELATION_TYPE_CODE = '81')
           AND U.END_DATE > SYSDATE)
