SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(USER_ID_A) USER_ID_A,
       TO_CHAR(ACCT_ID) ACCT_ID,
       TO_CHAR(ACCT_ID_B) ACCT_ID_B,
       PAYITEM_CODE,
       START_CYCLE_ID,
       END_CYCLE_ID,
       BIND_TYPE,
       LIMIT_TYPE,
       TO_CHAR(LIMIT) LIMIT,
       COMPLEMENT_TAG,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,INST_ID
  FROM TF_F_USER_SPECIALEPAY
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND ACCT_ID = TO_NUMBER(:ACCT_ID)
   AND PAYITEM_CODE = :PAYITEM_CODE
   AND END_CYCLE_ID > START_CYCLE_ID
   AND END_CYCLE_ID >= TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD'))
