SELECT A.TRADE_ID,
       A.USER_ID,
       A.PRODUCT_ID,
       A.PRODUCT_MODE,
       A.BRAND_CODE,
       A.INST_ID,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_B_TRADE_PRODUCT_BAK A
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.END_DATE>SYSDATE