SELECT E.STAFF_ID,
       C.DEPART_ID,
       C.DEPART_CODE,
       C.DEPART_NAME,
       C.DEPART_KIND_CODE,
       C.DEPART_FRAME,
       C.VALIDFLAG,
       C.AREA_CODE,
       C.PARENT_DEPART_ID,
       C.MANAGER_ID,
       C.ORDER_NO,
       C.USER_DEPART_CODE,
       TO_CHAR(C.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(C.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       C.DEPART_LEVEL,
       C.REMARK,
       C.RSVALUE1 PREVALUE1,
       C.RSVALUE2 PREVALUE2,
       C.RSVALUE3 PREVALUE3,
       C.RSVALUE4 PREVALUE4,
       TO_CHAR(C.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATETIME,
       C.UPDATE_STAFF_ID UPDATEDEPARTID,
       C.UPDATE_DEPART_ID UPDATESTAFFID
  FROM TF_F_USER         A,
       CHNL_ACCESS_PHONE B,
       TD_M_DEPART       C,
       TF_CHL_CHANNEL    D,
       TD_M_STAFF        E
 WHERE A.SERIAL_NUMBER = :P_SERIAL_NUMBER
   AND A.REMOVE_TAG = '0'
   AND A.USER_ID = B.PHONE_NBR
   AND B.STATE = '0'
   AND B.UPDATE_STATE = '1'
   AND B.CHANNEL_ID = C.DEPART_ID
   AND C.VALIDFLAG = '0'
   AND B.CHANNEL_ID = D.CHNL_ID
   AND C.DEPART_ID = E.DEPART_ID
   AND E.DIMISSION_TAG = '0'
   AND B.UPDATE_REF_ID = E.STAFF_ID
   AND B.TRADE_TYPE IN (4)