SELECT TRUNC((SUM(SALE_MONEY) / SUM(SALE_NUM)) * :CANSALE_NUM) SALE_MONEY,
       TRUNC((SUM(ADVANCE_PAY) / SUM(SALE_NUM)) * :CANSALE_NUM) ADVANCE_PAY,
       TRUNC((SUM(OLD_MONEY) / SUM(SALE_NUM)) * :CANSALE_NUM) OLD_MONEY,
       TRUNC((SUM(AGENT_FEE) / SUM(SALE_NUM)) * :CANSALE_NUM) AGENT_FEE,
       DISCOUNT
  FROM TF_B_CARDSALE_LOG A
 WHERE LOG_ID = TO_NUMBER(:LOG_ID)
   AND EPARCHY_CODE = :EPARCHY_CODE
   AND RES_TYPE_CODE = :RES_TYPE_CODE
   AND (:RES_KIND_CODE IS NULL OR RES_KIND_CODE = :RES_KIND_CODE)
   AND SALE_TYPE_CODE = :SALE_TYPE_CODE
   AND START_VALUE <= :RES_NO_S
   AND END_VALUE >= :RES_NO_E
   AND (:STOCK_ID IS NULL OR STOCK_ID = :STOCK_ID)
   AND EXISTS
 (SELECT 1
          FROM TF_R_SIMCARD_IDLE B
         WHERE SIM_CARD_NO >= :RES_NO_S
           AND SIM_CARD_NO <= :RES_NO_E
           AND EPARCHY_CODE = :EPARCHY_CODE
           AND (:OPEN_MODE IS NULL OR OPEN_MODE = :OPEN_MODE)
           AND (:PREOPEN_TAG IS NULL OR PREOPEN_TAG = :PREOPEN_TAG)
           AND (:FEE_TAG IS NULL OR FEE_TAG = :FEE_TAG)
           AND (:SIM_STATE_CODE IS NULL OR
               SIM_STATE_CODE = :SIM_STATE_CODE)
           AND (:CITY_CODE IS NULL OR CITY_CODE = :CITY_CODE)
           AND (:STOCK_ID_O IS NULL OR STOCK_ID_O = :STOCK_ID_O)
           AND (:STAFF_ID IS NULL OR STAFF_ID = :STAFF_ID)
           AND A.LOG_ID = B.RSRV_STR4 || '')
 GROUP BY DISCOUNT