INSERT INTO  TF_F_USER_DISCNT(PARTITION_ID,USER_ID,USER_ID_A,DISCNT_CODE,SPEC_TAG,PRODUCT_ID,package_id,inst_id,RELATION_TYPE_CODE,START_DATE,END_DATE,UPDATE_TIME, UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT MOD(:USER_ID,10000),TO_NUMBER(:USER_ID),'-1',b.element_id,'0',:PRODUCT_ID,b.package_id,f_sys_getseqid('ZZZZ','seq_inst_id'),NULL,SYSDATE,to_date('2050-12-31 23:59:59','yyyy-mm-dd hh24:mi:ss'),SYSDATE,:UPDATE_STAFF_ID,:UPDATE_DEPART_ID,:REMARK,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
FROM td_b_product_package a ,Td_b_Package_Element b
where a.product_id = :PRODUCT_ID
  AND a.package_id = b.package_id
  AND b.element_type_code = 'D'
	AND a.force_tag ='1'
	AND b.force_tag = '1'
	AND SYSDATE BETWEEN a.start_date AND  a.end_date
	AND SYSDATE BETWEEN b.start_date AND b.end_date
	AND NOT EXISTS(
	SELECT 1 FROM tf_F_user_discnt  c
	 where b.element_id = c.discnt_code
	   AND c.end_date > SYSDATE
	)