UPDATE TF_B_ORDER_DETAIL
   SET LOGISTICS_NUMBER           = :LOGISTICS_NUMBER,
       LOGISTICS_COMPANY            = :LOGISTICS_COMPANY,
       STATE   = :STATE,
       RSRV_TAG1     = :RSRV_TAG1,
       RSRV_STR1    = :RSRV_STR1,
       UPDATE_STAFF_ID = :UPDATE_STAFF_ID
 WHERE ORDER_ID = :ORDER_ID