INSERT INTO TF_B_TRADE_RELATION_AA
  (TRADE_ID,ACCEPT_MONTH,ACCT_ID_A,USER_ID_A,ACCT_ID_B,USER_ID_B,PAYITEM_CODE,RELATION_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,INST_ID,LIMIT_TYPE,LIMIT_VALUE,START_DATE,END_DATE,MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
  SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),ACCT_ID_A,USER_ID_A,ACCT_ID_B,USER_ID_B,PAYITEM_CODE,RELATION_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,INST_ID,LIMIT_TYPE,LIMIT_VALUE,START_DATE,TO_CHAR(SYSDATE,'YYYYMMDD'),:MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
    FROM TF_F_RELATION_AA
   WHERE (USER_ID_A = :USER_ID OR USER_ID_B = :USER_ID)
     AND END_DATE > TO_CHAR(SYSDATE,'YYYYMMDD')