SELECT I.SUBS_ID FROM 
TF_F_USER U,
TF_F_USER_PRODUCT P,
TF_F_INSTANCE_PF I
where 1 = 1
AND U.REMOVE_TAG= '0'
AND U.SERIAL_NUMBER = :SERIAL_NUMBER
AND U.USER_ID = I.USER_ID
AND I.INST_TYPE = 'U'
AND U.PARTITION_ID =P.PARTITION_ID
AND P.PRODUCT_ID = :PRODUCT_ID
AND I.USER_ID = P.USER_ID
AND P.END_DATE>SYSDATE