--IS_CACHE=Y
SELECT t.BEGIN_MSISDN,t.END_MSISDN,t.AREA_CODE,t.PROV_CODE,t.SERV_TYPE,t.ASP,t.HOME_TYPE,t.CALLED_TYPE 
FROM TD_M_MSISDN t 
WHERE 1=1 
AND (t.BEGIN_MSISDN<=:SERIAL_NUMBER AND t.END_MSISDN>=:SERIAL_NUMBER) 
AND t.PROV_CODE=:PROV_CODE
AND t.ASP=:ASP 
AND t.HOME_TYPE=:HOME_TYPE