--IS_CACHE=Y
SELECT SMS_CONTENT, ORG_DOMAIN, SMS_PROCESS_TAG
  FROM TD_B_PLATSVC_SMS
 WHERE ORG_DOMAIN = 'DSMP'
   AND SERVICE_ID = :SERVICE_ID
   AND OPER_CODE = :OPER_CODE
   AND BIZ_PRI <> '-1'
   AND BIZ_PRI = (SELECT MAX(BIZ_PRI)
                    FROM TD_B_PLATSVC_SMS
                   WHERE ORG_DOMAIN = 'DSMP'
                     AND SERVICE_ID = :SERVICE_ID
                     AND OPER_CODE = :OPER_CODE
                     AND BIZ_PRI <> '-1');