select to_char(trans_id) trans_id,
       user_id,
       serial_number,
       serial_number_temp,
       eparchy_code,
       state,
       TO_CHAR(start_date, 'yyyy-mm-dd hh24:mi:ss') start_date,
       TO_CHAR(end_date, 'yyyy-mm-dd hh24:mi:ss') end_date,
       TO_CHAR(update_time, 'yyyy-mm-dd hh24:mi:ss') update_time,
       imsi_new,
       pin_new,
       pin2_new,
       puk_new,
       puk2_new,
       ki_new,
       opc_new,
       sim_card_no_new,
       imsi_old,
       sim_card_no_old,
       ki_old,
       opc_old,
       opc_temp,
       ki_temp,
       imsi_temp,
       pin_temp,
       pin2_temp,
       puk_temp,
       puk2_temp,
       sim_card_no_temp,
       empty_card_id,
       remark,
       rsrv_str1,
       rsrv_str2,
       rsrv_str3,
       rsrv_str4,
       rsrv_str5,
       rsrv_tag1,
       rsrv_tag2,
       rsrv_tag3,
       rsrv_str6,
       rsrv_str7
  from TF_F_SELFHELPCARD_FLOW
  WHERE TRANS_ID = :TRANS_ID
  AND END_DATE>SYSDATE