SELECT TRADE_ID,ACCEPT_MONTH,SERIAL_NUMBER,CITY_CODE,TRADE_STAFF_ID,TRADE_STAFF_NAME,TRADE_DEPART_ID,TRADE_DEPART_NAME,OPEN_DATE,ADVANCE_PAY/100 as ADVANCE_PAY_YUAN,MAIN_PRODUCT_NAME,SALE_PRODUCT_NAME,SALE_PACKAGE_NAME 
FROM TF_B_NETCHOOSEPHONE 
WHERE 1=1 
AND OPEN_DATE >= to_date(:START_DATE, 'yyyy-mm-dd hh24:mi:ss') 
AND OPEN_DATE <= to_date(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND ADVANCE_PAY >= :LOWER_VALUE 
AND ADVANCE_PAY <= :UPPER_VALUE