SELECT to_char(TRADE_ID) TRADE_ID,
       ACCEPT_MONTH,
       to_char(USER_ID) USER_ID,
       SERIAL_NUMBER_B,
       PRODUCT_ID,
       PACKAGE_ID,
       to_char(INST_ID) INST_ID,
       to_char(CAMPN_ID) CAMPN_ID,
       GOODS_ID,
       GOODS_NAME,
       GOODS_NUM,
       GOODS_VALUE,
       GOODS_STATE,
       RES_TAG,
       RES_TYPE_CODE,
       RES_ID,
       RES_CODE,
       DEVICE_MODEL_CODE,
       DEVICE_MODEL,
       DEVICE_COST,
       DEVICE_BRAND_CODE,
       DEVICE_BRAND,
       DESTROY_FLAG,
       GIFT_MODE,
       POST_NAME,
       POST_ADDRESS,
       POST_CODE,
       RELATION_TRADE_ID,
       to_char(ACCEPT_DATE, 'yyyy-MM-dd HH24:mi:ss') ACCEPT_DATE,
       to_char(CANCEL_DATE, 'yyyy-MM-dd HH24:mi:ss') CANCEL_DATE,
       MODIFY_TAG,
       to_char(UPDATE_TIME, 'yyyy-MM-dd HH24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10,
       to_char(RSRV_DATE1, 'yyyy-MM-dd HH24:mi:ss') RSRV_DATE1,
       to_char(RSRV_DATE2, 'yyyy-MM-dd HH24:mi:ss') RSRV_DATE2,
       to_char(RSRV_DATE3, 'yyyy-MM-dd HH24:mi:ss') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_B_TRADE_SALE_GOODS
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))