SELECT A.NAVIGATE_ID,
       A.NAVIGATE_TYPE,
       A.NAVIGATE_KIND,
       A.NAVIGATE_NAME,
       A.NAVIGATE_HINT,
       A.NAVIGATE_DESC,
       B.INST_ID,
       B.INST_STATE,
       B.USER_ID,
       B.SERIAL_NUMBER,
       B.START_DATE,
       B.END_DATE,
       B.UPDATE_TIME,
       B.UPDATE_STAFF_ID,
       B.UPDATE_DEPART_ID
       
  FROM  TF_B_NAVIGATE_INST B,TD_B_NAVIGATE_DEF A
 WHERE A.NAVIGATE_ID = B.NAVIGATE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND B.USER_ID = :USER_ID