SELECT S.DISCNT_CODE,
       S.DISCNT_NAME,
       S.DISCNT_EXPLAIN,
       S.ITEM_TYPE,
       S.ITEM_CODE,
       S.HIGH_FEE,
       DECODE(S.HALF_NET, 0, '£¿£¿£¿£¿', 1, '£¿£¿£¿£¿', S.HALF_NET) HALF_NET,
       S.ADJUST_TAG,
       S.DISCNT_CODE_A,
       S.DISCNT_STATE,
       S.ENABLE_TAG
  FROM  TD_B_DISCNT_SHARE S
 WHERE S.DISCNT_CODE=:DISCNT_CODE
   AND SYSDATE BETWEEN S.START_DATE AND S.END_DATE
