SELECT SHOPPING_CART_ID,
       CUST_ID,
       USER_ID,
       DETAIL_ORDER_ID,
       DETAIL_STATE_CODE,
       DETAIL_TYPE_CODE,
       DETAIL_TYPE_CODE ORDER_TYPE_CODE,
       DISCNT_RULE_ID,
       OLDFEE,
       FREE_FEE,
       FEE,
       JOIN_TYPE,
       JOIN_SEQ,
       REQUEST_DATA,
       TRADE_STAFF_ID,
       TRADE_DEPART_ID,
       TO_CHAR(ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE 
  FROM TF_B_SHOPPING_CART_DETAIL T
WHERE T.SHOPPING_CART_ID = :SHOPPING_CART_ID
AND T.DETAIL_ORDER_ID = :DETAIL_ORDER_ID
AND T.DETAIL_STATE_CODE = :DETAIL_STATE_CODE