SELECT T.GROUP_ID,T.CUST_NAME GROUP_CUST_NAME,T.CUST_MANAGER_ID,T.CITY_CODE FROM TF_F_CUST_GROUP T 
WHERE 1=1
AND T.CITY_CODE LIKE '%' || :CITY_CODE || '%'
AND T.CUST_MANAGER_ID LIKE '%' || :CUST_MANAGER_ID || '%'
AND T.GROUP_ID LIKE '%' || :GROUP_ID || '%'
AND T.REMOVE_TAG= '0'