SELECT to_char(USER_ID) USER_ID, SERIAL_NUMBER, CARD_TYPE, ACT_TAG, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss'), to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss'), REMARK, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'), UPDATE_STAFF_ID,UPDATE_DEPART_ID
 FROM  TF_O_TESTCARD
WHERE  SERIAL_NUMBER=:SERIAL_NUMBER
AND SYSDATE BETWEEN START_DATE and END_DATE