SELECT SEND_TASK_ID,PARTITION_ID,JOB_ID,RSP_EXEC_CODE,TASK_TYPE,ACCEPT_MONTH,SEND_OBJECT,TMPL_ID,CONTENT,TASK_CHAN_ID,EXE_CHAN_ID,EXE_METHOD,EXE_TYPE,
EPARCHY_CODE,EXEC_COUNT,EXEC_INTERVAL,TRADE_TIME,EXPIRE_TIME,EXE_TIME,START_TIME,FINISH_TIME,TASK_PRI,RSP_TIME,RSP_CODE,RSP_DESC,TASK_STATUS,
REFER_TIME,REFER_STAFF_ID,REFER_DEPART_ID,DEAL_TIME,DEAL_STAFFID,DEAL_DEPARTID,PREVALUE5,PREVALUE4,PREVALUE3,PREVALUE2,PREVALUE1,REMARK,MONTH,DAY
 FROM (SELECT SEND_TASK_ID,PARTITION_ID,JOB_ID,RSP_EXEC_CODE,TASK_TYPE,ACCEPT_MONTH,SEND_OBJECT,TMPL_ID,CONTENT,TASK_CHAN_ID,EXE_CHAN_ID,EXE_METHOD,EXE_TYPE,
EPARCHY_CODE,EXEC_COUNT,EXEC_INTERVAL,TRADE_TIME,EXPIRE_TIME,EXE_TIME,START_TIME,FINISH_TIME,TASK_PRI,RSP_TIME,RSP_CODE,RSP_DESC,TASK_STATUS,
REFER_TIME,REFER_STAFF_ID,REFER_DEPART_ID,DEAL_TIME,DEAL_STAFFID,DEAL_DEPARTID,PREVALUE5,PREVALUE4,PREVALUE3,PREVALUE2,PREVALUE1,REMARK,MONTH,DAY 
 FROM TF_B_SEND_TASK WHERE to_char(EXE_TIME, 'yyyy-MM-dd HH24:mm:ss') <=:EXE_TIME OR EXE_TIME is NULL OR EXE_TIME = '') 
 WHERE TASK_STATUS =:TASK_STATUS AND (PARTITION_ID between :THREAD_NUM*100 and (:THREAD_NUM+1)*100-1)