INSERT INTO TI_B_ACCOUNT (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,ACCT_ID,CUST_ID,PAY_NAME,PAY_MODE_CODE,ACCT_DIFF_CODE,ACCT_PASSWD,ACCT_TAG,NET_TYPE_CODE,EPARCHY_CODE,CITY_CODE,BANK_CODE,BANK_ACCT_NO,SCORE_VALUE,CREDIT_CLASS_ID,BASIC_CREDIT_VALUE,CREDIT_VALUE,DEBUTY_USER_ID,DEBUTY_CODE,CONTRACT_NO,DEPOSIT_PRIOR_RULE_ID,ITEM_PRIOR_RULE_ID,OPEN_DATE,REMOVE_TAG,REMOVE_DATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10 )
        SELECT :SYNC_SEQUENCE,:MODIFY_TAG,:TRADE_ID,  PARTITION_ID,ACCT_ID,CUST_ID,PAY_NAME,PAY_MODE_CODE,nvl(ACCT_DIFF_CODE,'0'),ACCT_PASSWD,ACCT_TAG,NET_TYPE_CODE,nvl(EPARCHY_CODE,'0'),nvl(CITY_CODE,'0'),BANK_CODE,BANK_ACCT_NO,SCORE_VALUE,CREDIT_CLASS_ID,BASIC_CREDIT_VALUE,CREDIT_VALUE,DEBUTY_USER_ID,DEBUTY_CODE,CONTRACT_NO,DEPOSIT_PRIOR_RULE_ID,ITEM_PRIOR_RULE_ID,OPEN_DATE,REMOVE_TAG,REMOVE_DATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10
        FROM TF_F_ACCOUNT A
        WHERE ACCT_ID IN (
           SELECT ACCT_ID FROM TF_B_TRADE_ACCOUNT  WHERE TRADE_ID=:TRADE_ID  )
        AND NOT EXISTS (SELECT 1 FROM TI_B_ACCOUNT 
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.acct_id = ACCT_ID
                           AND a.partition_id = PARTITION_ID
                           )