--IS_CACHE=Y
SELECT PACKAGE_ID, PACKAGE_NAME, ACTIVE_FLAG, DISCNT_CODE, UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, RSRV_STR1,
       RSRV_STR2, TAG_SET,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1
  FROM TD_B_MOBILE_DISCNT
 WHERE PACKAGE_ID = :PACKAGE_ID
   AND ACTIVE_FLAG = :ACTIVE_FLAG