SELECT T.INST_ID,
       TD.TRADE_ID,
       TD.ACCEPT_MONTH,
       TD.USER_ID,
       TD.MERCH_SPEC_CODE,
       TD.PRODUCT_ORDER_ID,
       TD.PRODUCT_OFFER_ID,
       TD.PRODUCT_SPEC_CODE,
       TD.PRODUCT_DISCNT_CODE,
       TD.START_DATE,
       TD.END_DATE,
       TD.MODIFY_TAG,
       TD.UPDATE_TIME,
       TD.UPDATE_STAFF_ID,
       TD.UPDATE_DEPART_ID,
       TD.REMARK,
       TD.RSRV_NUM1,
       TD.RSRV_NUM2,
       TD.RSRV_NUM3,
       TD.RSRV_NUM4,
       TD.RSRV_NUM5,
       TD.RSRV_STR1,
       TD.RSRV_STR2,
       TD.RSRV_STR3,
       TD.RSRV_STR4,
       TD.RSRV_STR5,
       TD.RSRV_DATE1,
       TD.RSRV_DATE2,
       TD.RSRV_DATE3,
       TD.RSRV_TAG1,
       TD.RSRV_TAG2,
       TD.RSRV_TAG3
  FROM TF_B_TRADE_GRP_MERCHP_DISCNT TD, TF_B_TRADE_DISCNT T, TD_B_ATTR_BIZ AB
 WHERE T.TRADE_ID = TD.TRADE_ID
   AND T.ACCEPT_MONTH = TD.ACCEPT_MONTH
   AND TD.USER_ID = T.USER_ID
   AND T.TRADE_ID = :TRADE_ID
   AND AB.ID = '1'
   AND AB.ID_TYPE = 'B'
   AND AB.ATTR_OBJ = 'DIS'
   AND AB.ATTR_VALUE = TD.PRODUCT_DISCNT_CODE
   AND AB.ATTR_CODE = T.DISCNT_CODE
   AND SYSDATE BETWEEN AB.START_DATE AND AB.END_DATE
   AND SYSDATE BETWEEN TD.START_DATE AND TD.END_DATE
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE