--IS_CACHE=Y
SELECT S.BADNESS_INFO_PROVINCE,
       S.BADNESS_INFO,
       S.IN_MODE_CODE, S.REPORT_SERIAL_NUMBER,
       SUM(1) BADNESS_INFO_SUM
  FROM TF_F_BADNESS_INFO S
 WHERE 1 = 1
   AND (SUBSTR(S.SORT_RESULT_TYPE, 5, 2) = :REPORT_TYPE_CODE OR
       :REPORT_TYPE_CODE IS NULL)
   AND (SUBSTR(S.SORT_RESULT_TYPE, 7, 2) = :REPORT_CODE OR
       :REPORT_CODE IS NULL)
   AND (SUBSTR(S.SORT_RESULT_TYPE, 9, 2) = SUBSTR(:CONTENT_TYPE_CODE, 3, 2) OR
       :CONTENT_TYPE_CODE IS NULL)
   AND (S.IN_MODE_CODE = :IN_MODE_CODE OR :IN_MODE_CODE IS NULL)
   AND (S.BADNESS_INFO_PROVINCE = :BADNESS_INFO_PROVINCE OR
       :BADNESS_INFO_PROVINCE IS NULL)
   AND (S.BADNESS_INFO = :BADNESS_INFO OR :BADNESS_INFO IS NULL)
   AND (S.STATE = :STATE OR :STATE IS NULL)
   AND (TRUNC(S.REPORT_TIME) >= TO_DATE(:REPORT_START_TIME, 'yyyy-mm-dd') OR
       :REPORT_START_TIME IS NULL)
   AND (TRUNC(S.REPORT_TIME) <= TO_DATE(:REPORT_END_TIME, 'yyyy-mm-dd') OR
       :REPORT_END_TIME IS NULL)
 GROUP BY S.BADNESS_INFO_PROVINCE, S.BADNESS_INFO, S.IN_MODE_CODE
