UPDATE TF_F_USER_VALIDCODE
   SET SMS_CODE=:SMS_CODE,CHECK_COUNT=:CHECK_COUNT,
       UPDATE_TIME=TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS')
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER
    AND USER_ID = :USER_ID
    AND PRODUCT_ID = :PRODUCT_ID
    AND EPARCHY_CODE = :EPARCHY_CODE
    AND TO_CHAR(INDATE, 'YYYY-MM-DD')= TO_CHAR(sysdate, 'YYYY-MM-DD')