SELECT B.PARA_CODE1 PRODUCT_CODE,
         NVL(B.PARA_CODE2, 'NULL') PACKAGE_ID,
         C.PROD_INST_ID PRODUCT_INST_ID,
         TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
         TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
         D.SERIAL_NUMBER,
         SUBSTR(E.RSRV_STR1, 0, INSTR(E.RSRV_STR1, '|') - 1) CARDTYPE,
         E.RSRV_STR5 CARDPHYSICALTYPE,
         A.MODIFY_TAG,
         E.IMSI,
         E.KI,
         G.SUBS_ID,
         F.OPC_CIPHER OPCKEYID
    FROM TF_B_TRADE_PRODUCT A,
         TD_S_COMMPARA      B,
         TF_F_INSTANCE_PF   C,
         TF_B_TRADE         D,
         TF_F_USER_RES      E,
         TI_IOT_CARDDATAFILE     F,
         TF_F_INSTANCE_PF   G
   WHERE TO_CHAR(A.PRODUCT_ID) = B.PARAM_CODE
     AND B.SUBSYS_CODE = 'CSM'
     AND B.PARAM_ATTR = '9015'
     AND A.INST_ID = C.INST_ID
     AND C.INST_TYPE = 'S'
     AND A.TRADE_ID = D.TRADE_ID
     AND A.USER_ID = E.USER_ID
     AND E.RES_TYPE_CODE = '1'
     AND A.USER_ID = G.USER_ID
     AND G.INST_ID = -1
     AND F.IMSI = E.IMSI
     AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND A.MODIFY_TAG IN ('0', '1', '2')
     AND SYSDATE BETWEEN E.START_DATE AND E.END_DATE