INSERT INTO tf_f_user_svcstate (PARTITION_ID,USER_ID,SERVICE_ID,MAIN_TAG,STATE_CODE,START_DATE,END_DATE,update_time)
select TO_NUMBER(:PARTITION_ID),TO_NUMBER(:USER_ID),a.SERVICE_ID,a.MAIN_TAG,b.STATE_CODE,TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE
from tf_f_user_svc a,td_s_servicestate b
where a.SERVICE_ID=b.SERVICE_ID
and b.STATE_CODE='0'
and a.user_id=TO_NUMBER(:USER_ID)
AND a.partition_id = MOD(TO_NUMBER(:USER_ID),10000)