UPDATE TF_F_CUST_FAMILYMEB
   SET REMOVE_TAG       = '1',
       REMOVE_DATE      = TO_DATE(:REMOVE_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       REMOVE_STAFF_ID  = :REMOVE_STAFF_ID,
       REMOVE_DEPART_ID = :REMOVE_DEPART_ID,
       REMOVE_REASON    = :REMOVE_REASON,
       UPDATE_TIME      = TO_DATE(:REMOVE_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_STAFF_ID  = :REMOVE_STAFF_ID,
       UPDATE_DEPART_ID = :REMOVE_DEPART_ID
 WHERE HOME_CUST_ID = TO_NUMBER(:HOME_CUST_ID)
   AND REMOVE_TAG = '0'