--IS_CACHE=Y
SELECT PARA_CODE1 ID,
       PARA_CODE2 NAME,
       PARA_CODE3 PARENT_ID,
       (SELECT COUNT(1)
          FROM TD_S_COMMPARA C
         WHERE C.PARAM_ATTR = 2001
           AND C.SUBSYS_CODE = 'CSM'
           AND C.PARAM_CODE = :TYPE
           AND C.PARA_CODE3 = T.PARA_CODE1
           AND UPPER(C.PARA_CODE4) = 'YES'
           AND (C.EPARCHY_CODE = :EPARCHY_CODE or C.EPARCHY_CODE='ZZZZ')) NODE_COUNT
  FROM TD_S_COMMPARA T
 WHERE T.PARAM_ATTR = 2001
   AND T.SUBSYS_CODE = 'CSM'
   AND T.PARAM_CODE = :TYPE
   AND T.PARA_CODE3 = :PARENT_ID
   AND UPPER(T.PARA_CODE4) = 'YES'
   AND (T.EPARCHY_CODE = :EPARCHY_CODE or T.EPARCHY_CODE='ZZZZ')
