SELECT PARTITION_ID,
USER_ID,
OPR_NUMB,
SERIAL_NUMBER,
CHANNEL_ID,
ACCOUNT,
ERROR_TIME,
ERROR_NUMB,
BIND_TIME,
REMOVE_TAG,
REMOVE_TIME,
EFFECTIVE_TIME,
IDENT_CODE_LEVEL,
IDENT_CODE_TYPE,
IDENT_CODE,
to_char(IDENT_START_TIME,'yyyy-mm-dd hh24:mi:ss') IDENT_START_TIME,
to_char(IDENT_END_TIME,'yyyy-mm-dd Hh24:mi:ss') IDENT_END_TIME,
EPARCHY_CODE,
UPDATE_TIME,
UPDATE_STAFF_ID,
UPDATE_DEPART_ID,
REMARK,
RSRV_STR1,
RSRV_STR2,
RSRV_STR3,
RSRV_STR4,
RSRV_STR5,
RSRV_TAG1,
RSRV_TAG2,
RSRV_TAG3 
FROM TF_F_USER_ACCOUNT WHERE 1=1 
AND ACCOUNT= :MICRO_ACCOUNT 
AND SERIAL_NUMBER= :SERIAL_NUMBER 
AND USER_ID= :USER_ID 
AND PARTITION_ID= MOD(:USER_ID, 10000)
AND sysdate between IDENT_START_TIME and IDENT_END_TIME
AND REMOVE_TAG= 0 ORDER BY IDENT_END_TIME DESC