UPDATE TF_F_USER_ACCOUNT SET IDENT_END_TIME=sysdate,ERROR_NUMB=:ERROR_NUMB,ERROR_TIME=sysdate,UPDATE_TIME=sysdate,UPDATE_STAFF_ID=:UPDATE_STAFF_ID,UPDATE_DEPART_ID=:UPDATE_DEPART_ID
WHERE 1=1  
AND SERIAL_NUMBER= :SERIAL_NUMBER AND USER_ID= :USER_ID 
AND PARTITION_ID= MOD(:USER_ID, 10000) 
AND sysdate between IDENT_START_TIME and IDENT_END_TIME