UPDATE TF_F_CUST_FAMILYMEB
    SET NICK_NAME		 = :NICK_NAME,
    	MEMBER_ROLE      = :MEMBER_ROLE,
    	MEMBER_KIND		 = :MEMBER_KIND,
    	REMOVE_TAG       = '0',
        REMOVE_DATE      = '',
        REMOVE_STAFF_ID  = '',
        REMOVE_DEPART_ID = '',
        REMOVE_REASON    = '',
        UPDATE_TIME      = TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'),
        UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
        UPDATE_DEPART_ID = :UPDATE_DEPART_ID
  WHERE MEMBER_CUST_ID = TO_NUMBER(:MEMBER_CUST_ID)
    AND PARTITION_ID = MOD(TO_NUMBER(:MEMBER_CUST_ID), 10000)
    AND REMOVE_TAG = '1'
    AND REMOVE_DATE > TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS')