UPDATE TF_B_FAMILY_OTHER SET
            EXP_TIME=TO_DATE(:EXP_TIME, 'YYYY-MM-DD HH24:MI:SS'),
            REMARK=:REMARK,
            FINISH_TAG=:FINISH_TAG,
            ACTION=:ACTION
            WHERE 1=1 
            AND PRODUCT_OFFERING_ID = :PRODUCT_OFFERING_ID 
            AND CUSTOMER_PHONE = :CUSTOMER_PHONE 
            AND FINISH_TAG ='1'