UPDATE TF_F_USER_SALEACTIVE_BOOK A
   SET A.DEAL_STATE_CODE = '0',
       A.UPDATE_STAFF_ID = :TRADE_STAFF_ID,
       A.UPDATE_TIME     = SYSDATE
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.PRODUCT_ID_B = :PRODUCT_ID_B
   AND A.PACKAGE_ID_B = :PACKAGE_ID_B