--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_DISCNT UD,
       (SELECT A.PARA_CODE1 OPER_CODE, A.PARA_CODE2 DISCNT_CODE, '00' TAG
          FROM TD_S_COMMPARA A
         WHERE A.PARAM_ATTR = 156
           AND A.PARAM_CODE = 'CUMU'
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
        UNION
        SELECT A.PARA_CODE2 OPER_CODE, A.PARA_CODE1 DISCNT_CODE, '01' TAG
          FROM TD_S_COMMPARA A
         WHERE A.PARAM_ATTR = '179'
           AND A.PARAM_CODE = 'CUMU'
           AND A.PARA_CODE2 IS NOT NULL
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
        UNION
        SELECT A.PARA_CODE2 OPER_CODE, A.PARA_CODE1 DISCNT_CODE, '10' TAG
          FROM TD_S_COMMPARA A
         WHERE A.PARAM_ATTR = 138
           AND A.PARAM_CODE = 'CUMU'
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
        UNION
        SELECT A.PARA_CODE2 OPER_CODE, A.PARA_CODE1 DISCNT_CODE, '11' TAG
          FROM TD_S_COMMPARA A
         WHERE A.PARAM_ATTR = '204'
           AND A.PARAM_CODE = 'CUMU'
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE) PM
 WHERE UD.DISCNT_CODE = PM.DISCNT_CODE
   AND UD.PARTITION_ID = MOD(:USER_ID, 10000)
   AND UD.USER_ID = :USER_ID
   AND PM.OPER_CODE = :OPER_CODE
   AND UD.END_DATE >= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -2))