SELECT A.USER_ID,
       A.DISCNT_CODE,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       A.INST_ID,
       A.USER_ID_A
  FROM TF_F_USER_DISCNT A, TD_S_COMMPARA B
 WHERE A.DISCNT_CODE = B.PARA_CODE3
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 943
   AND B.PARAM_CODE = '2'
   AND B.PARA_CODE1 = :PACKAGE_ID
   AND B.PARA_CODE2 = :ELEMENT_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE