INSERT INTO TI_B_USER_DISCNT (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,DISCNT_CODE,SPEC_TAG,RELATION_TYPE_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,DISCNT_CODE,SPEC_TAG,RELATION_TYPE_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
        FROM TF_F_USER_DISCNT d
              WHERE USER_ID 
              IN (
              SELECT b.user_id_a FROM tf_b_trade_relation b WHERE b.trade_id = TO_NUMBER(:TRADE_ID)
              UNION
              SELECT c.user_id_b FROM tf_b_trade_relation c WHERE c.trade_id = TO_NUMBER(:TRADE_ID)   
              )   
              AND NOT EXISTS (SELECT 1 FROM TI_B_USER_DISCNT 
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND d.user_id = user_id
                           AND d.partition_id = PARTITION_ID
                           AND d.user_id_a = USER_ID_A
                           AND d.PRODUCT_ID = PRODUCT_ID 
                           AND d.DISCNT_CODE = DISCNT_CODE 
                           AND d.PACKAGE_ID = PACKAGE_ID
                           AND d.START_DATE =START_DATE
                           )