--IS_CACHE=Y
SELECT USER_CLUSTER_ID,NAME,USER_GROUP_ID,PRIORITY,REMARK,
to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
UPDATE_STAFF_ID,UPDATE_DEPART_ID,EPARCHY_CODE 
FROM td_o_credit_usercluster 
WHERE EPARCHY_CODE = :EPARCHY_CODE