--IS_CACHE=Y
select REASON_CODE RSRV_NUM1,0 RSRV_NUM2,0 RSRV_NUM3, '' PARA_CODE1,'' PARA_CODE2,'' PARA_CODE3,'' PARA_CODE4,'' PARA_CODE5,'' PARA_CODE6,
'' PARA_CODE7,'' PARA_CODE8,REASON PARA_CODE9,'SEL_BADDEBT_REASON' CALLING_TYPE_CODE FROM TD_A_ACCT_MGREASON WHERE FLAG='5'