SELECT A.USER_ID    USER_ID,
       A.SERVICE_ID SERVICE_ID,
       B.ATTR_CODE  ATTR_CODE,
       B.ATTR_VALUE ATTR_VALUE
  FROM TF_F_USER_SVC A, TF_F_USER_ATTR B
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.PARTITION_ID = B.PARTITION_ID
   AND A.USER_ID = B.USER_ID
   AND A.INST_ID = B.RELA_INST_ID
   AND B.END_DATE > SYSDATE
   AND B.ATTR_CODE = :ATTR_CODE