insert into TD_S_NONBOSSPARA
  (TYPE_ID,
   DATA_ID,
   DATA_NAME,
   PARAM_NAME,
   PARA_CODE1,
   PARA_CODE2,
   PARA_CODE3,
   PARA_CODE4,
   PARA_CODE5,
   PARA_CODE6,
   PARA_CODE7,
   PARA_CODE8,
   PARA_CODE9,
   PARA_CODE10,
   PARA_CODE11,
   PARA_CODE12,
   PARA_CODE13,
   PARA_CODE14,
   PARA_CODE15,
   PARA_CODE16,
   PARA_CODE17,
   PARA_CODE18,
   PARA_CODE19,
   PARA_CODE20,
   PARA_CODE21,
   PARA_CODE22,
   PARA_CODE23,
   PARA_CODE24,
   PARA_CODE25,
   PARA_CODE26,
   PARA_CODE27,
   PARA_CODE28,
   PARA_CODE29,
   PARA_CODE30,
   START_DATE,
   END_DATE,
   EPARCHY_CODE,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   UPDATE_TIME,
   REMARK)
values
  (:TYPE_ID,
   DECODE(:DATA_ID,NULL,(SELECT TO_CHAR(MAX(TO_NUMBER(DATA_ID)) + 1)
      FROM TD_S_NONBOSSPARA
     WHERE TYPE_ID = :TYPE_ID),:DATA_ID),
   :DATA_NAME,
   :PARAM_NAME,
   :PARA_CODE1,
   :PARA_CODE2,
   :PARA_CODE3,
   :PARA_CODE4,
   :PARA_CODE5,
   :PARA_CODE6,
   :PARA_CODE7,
   :PARA_CODE8,
   :PARA_CODE9,
   :PARA_CODE10,
   :PARA_CODE11,
   :PARA_CODE12,
   :PARA_CODE13,
   :PARA_CODE14,
   :PARA_CODE15,
   :PARA_CODE16,
   :PARA_CODE17,
   :PARA_CODE18,
   :PARA_CODE19,
   :PARA_CODE20,
   :PARA_CODE21,
   :PARA_CODE22,
   :PARA_CODE23,
   :PARA_CODE24,
   :PARA_CODE25,
   to_date(:PARA_CODE26, 'yyyy-mm-dd'),
   to_date(:PARA_CODE27, 'yyyy-mm-dd'),
   to_date(:PARA_CODE28, 'yyyy-mm-dd'),
   to_date(:PARA_CODE29, 'yyyy-mm-dd'),
   to_date(:PARA_CODE30, 'yyyy-mm-dd'),
   case when :START_DATE is not null
   then
   to_date(:START_DATE || ' 00.00.00', 'yyyy-mm-dd hh24:mi:ss')    
   else
   null
   end,
   case when :END_DATE is  null
   then
   to_date('2050-12-31' || ' 23.59.59', 'yyyy-mm-dd hh24:mi:ss')
   else
   to_date(:END_DATE || ' 23.59.59', 'yyyy-mm-dd hh24:mi:ss')
   end,
   '0898',
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID,
   sysdate,
   :REMARK) 