UPDATE  TL_B_COMMENDSTAFF_LOG T 
    SET
      T.DEAL_STATUS='1',
      T.CANCEL_UPDATE_STAFF_ID =:CANCEL_UPDATE_STAFF_ID,
      T.CANCEL_DEPART_ID =:CANCEL_DEPART_ID,
      T.CANCEL_TIME =:CANCEL_TIME,
      T.REMARK =:REMARK
      WHERE T.TRADE_ID =:TRADE_ID AND T.DEAL_STATUS='0'