SELECT * FROM TF_F_USER_FAMILY_CIRCLE T 
WHERE  T.STATUS = :STATUS AND 
T.GROUP_TYPE = :GROUP_TYPE AND 
T.GROUP_NAME LIKE  '%'||:GROUP_NAME||'%' AND 
T.TARGET_NAME LIKE '%'||:TARGET_NAME||'%'AND 
T.TARGET_MSISDN = :TARGET_MSISDN
