SELECT COUNT(1) NUM
FROM TF_B_TRADE_DISCNT T
WHERE 1=1
AND T.TRADE_ID IN (SELECT A.TRADE_ID FROM TF_B_TRADE A WHERE A.USER_ID = :USER_ID AND A.TRADE_TYPE_CODE = '110')
AND T.DISCNT_CODE IN (SELECT T.PARA_CODE2 FROM TD_S_COMMPARA T WHERE T.SUBSYS_CODE = 'CSM' AND T.PARAM_ATTR = 3700 AND T.PARAM_CODE = :SERVICE_ID)