UPDATE TI_BI_MO_MON
   SET DEAL_TAG = :DEAL_TAG2,
       FINISH_TIME = SYSDATE,
       RESULT_CODE = :RESULT_CODE,
       RESULT_INFO = :RESULT_INFO
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER
   AND USER_ID = to_number(:USER_ID)
   AND DEAL_TAG = :DEAL_TAG1