select * from (SELECT A.PRIORITY_LEVEL, A.TITLE_NAME, A.SALE_ACT_SCRIPT,RSRV_STR1
  FROM TL_O_REALTIMEMARKETINGTRADE A
 WHERE A.REQ_ID = :REQ_ID
 ORDER BY A.PRIORITY_LEVEL DESC)
where 1=1
 and rownum < 6 