SELECT DISTINCT (T.USER_ID)
  FROM (SELECT A.USER_ID
          FROM TI_B_USER_DISCNT A WHERE A.TRADE_ID=:TRADE_ID
        UNION
        SELECT B.USER_ID
          FROM TI_B_USER_INFOCHANGE B WHERE B.TRADE_ID=:TRADE_ID
        UNION
        SELECT C.USER_ID
          FROM TI_B_USER_ACCTDAY C WHERE C.TRADE_ID=:TRADE_ID
        UNION
        SELECT D.USER_ID_B USER_ID FROM TI_B_RELATION_UU D WHERE D.TRADE_ID=:TRADE_ID) T