UPDATE TL_B_MONITORFILE A
   SET A.PROCESS_TAG = :PROCESS_TAG,
       A.REMARK      = :REMARK,
       A.RSRV_STR2   = :USER_ID,
       A.EXEC_TIME   = SYSDATE
 WHERE A.INTF_ID = :INTF_ID
   AND A.MONTH = :MONTH
