INSERT INTO TF_B_TRADE_BLACKWHITE
  (TRADE_ID, ACCEPT_MONTH,USER_ID, USER_TYPE_CODE, SERVICE_ID, BIZ_IN_CODE, BIZ_IN_CODE_A,
   EC_USER_ID, EC_SERIAL_NUMBER,
   SERV_CODE, SERIAL_NUMBER, GROUP_ID,  BIZ_CODE,BIZ_NAME, BIZ_DESC,
   BOOK_DATE,CONTRACT_ID,PRICE, BILLING_TYPE, OPR_EFF_TIME, OPR_SEQ_ID, OPER_STATE,EXPECT_TIME,PLAT_SYNC_STATE,
   START_DATE, END_DATE,
   MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,
   REMARK,RSRV_NUM1, RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,
   RSRV_STR1,RSRV_STR2,RSRV_STR3, RSRV_STR4,  RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
  SELECT to_number(:TRADE_ID), :ACCEPT_MONTH, BL.USER_ID, BL.USER_TYPE_CODE,  BL.SERVICE_ID, BL.BIZ_IN_CODE,  BL.BIZ_IN_CODE_A, BL.EC_USER_ID,
         BL.EC_SERIAL_NUMBER,  BL.SERV_CODE,  BL.SERIAL_NUMBER, BL.GROUP_ID,  BL.BIZ_CODE,
         BL.BIZ_NAME, BL.BIZ_DESC, BL.BOOK_DATE, BL.CONTRACT_ID,  BL.PRICE, BL.BILLING_TYPE,  BL.OPR_EFF_TIME,BL.OPR_SEQ_ID, BL.OPER_STATE,
         to_date(:EXPECT_TIME, 'yyyy-mm-dd hh24:mi:ss'),  BL.PLAT_SYNC_STATE,
         SYSDATE,  to_date('2050-12-31 23:59:59', 'yyyy-mm-dd hh24:mi:ss'), '0',
         to_date(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),   :UPDATE_STAFF_ID,  :UPDATE_DEPART_ID,  BL.REMARK, '0',  BL.RSRV_NUM2,  BL.RSRV_NUM3,  BL.RSRV_NUM4,   BL.RSRV_NUM5,
         BL.RSRV_STR1, BL.RSRV_STR2,  BL.RSRV_STR3, BL.RSRV_STR4,  BL.RSRV_STR5,BL.RSRV_DATE1, BL.RSRV_DATE2, BL.RSRV_DATE3, BL.RSRV_TAG1,  BL.RSRV_TAG2,  '0'
    FROM TF_F_USER_BLACKWHITE BL
   WHERE BL.USER_ID = to_number(:USER_ID)
     AND BL.PARTITION_ID = MOD(to_number(:USER_ID), 10000)
     and bl.rsrv_num1 = '0'
     AND BL.END_DATE in
          (select max(bt.end_date) end_date
            from TF_F_USER_BLACKWHITE BT
           WHERE BT.USER_ID = to_number(:USER_ID)
             and BT.PARTITION_ID = mod(to_number(:USER_ID), 10000)
             and bt.group_id = bl.group_id
             and bt.end_date + 0 <= sysdate)
     AND EXISTS (SELECT 1
                  FROM TF_F_CUST_GROUP G
                 WHERE g.group_id = BL.GROUP_ID
                   AND G.REMOVE_TAG = '0')