Select S2.PARTITION_ID, to_char(S2.USER_ID) USER_ID, S2.RES_TYPE_CODE, S2.RES_CODE, IMSI, to_char(S2.START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(S2.END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, to_char(S2.UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'), S2.UPDATE_TIME, S2.UPDATE_STAFF_ID, S2.UPDATE_DEPART_ID, S2.REMARK, S2.RSRV_NUM1, S2.RSRV_NUM2, S2.RSRV_NUM3, to_char(S2.RSRV_NUM4) RSRV_NUM4, to_char(S2.RSRV_NUM5) RSRV_NUM5, S2.RSRV_STR1, S2.RSRV_STR2, S2.RSRV_STR3, S2.RSRV_STR4, S2.RSRV_STR5, to_char(S2.RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1, to_char(S2.RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2, to_char(S2.RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3, S2.RSRV_TAG1, S2.RSRV_TAG2, S2.RSRV_TAG3
  from TF_F_USER S1, TF_F_USER_RES S2
 WHERE S1.User_Id = S2.USER_ID
   AND S1.REMOVE_TAG = '0'
   AND S2.RES_TYPE_CODE = :RES_TYPE_CODE
   AND S2.END_DATE > SYSDATE
   AND S1.SERIAL_NUMBER = :SERIAL_NUMBER