UPDATE TF_F_USER_SALE_ACTIVE
   SET END_DATE        = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       PROCESS_TAG     = :PROCESS_TAG,
       CANCEL_DATE     = TO_DATE(:CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       CANCEL_STAFF_ID = :CANCEL_STAFF_ID,
       CANCEL_CAUSE    = :CANCEL_CAUSE,
       REMARK =:REMARK,
       UPDATE_TIME     =SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND END_DATE > SYSDATE