UPDATE TF_F_INTEGRAL_ACCT
   SET END_DATE=TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),STATUS=:STATUS
 WHERE INTEGRAL_ACCT_ID=TO_NUMBER(:INTEGRAL_ACCT_ID)
 AND PARTITION_ID = MOD(TO_NUMBER(:INTEGRAL_ACCT_ID), 10000)