select INTEGRAL_ACCT_ID,
INTEGRAL_ACCOUNT_TYPE,
PARTITION_ID,
NAME,
USER_ID,
ACCT_ID,
CUST_ID,
CONTRACT_PHONE,
PASSWORD,
EMAIL,
PSPT_TYPE_CODE,
PSPT_ID,
ADDRESS,
USE_LIMIT,
to_char(START_DATE,'yyyy-mm-dd') START_DATE,
to_char(END_DATE,'yyyy-mm-dd') END_DATE,
STATUS,
REMARK
FROM TF_F_INTEGRAL_ACCT T
 WHERE T.PSPT_ID=:VALUE
 AND T.INTEGRAL_ACCOUNT_TYPE = '1'
 AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
 AND STATUS = '10A'