 SELECT   OPR_SEQ,
  EC_ID,
  DISCNT_RATE,
  CARD_BIND,
  PROV_DOC,
  NVL(APPROVAL_RSLT,9) APPROVAL_RSLT,
  APPROVAL_NO,
  APPROVAL_COMM,
  APPROVAL_DOC,
  CREATE_TIME,
  CREATE_STAFF_ID,
  UPDATE_TIME,
  RSRV_STR1,
  RSRV_STR2,
  RSRV_STR3,
  RSRV_STR4,
  RSRV_STR5
  FROM TF_O_DISCNT_APPROVAL
  WHERE CREATE_STAFF_ID = :CREATE_STAFF_ID 
  AND  EC_ID = :EC_ID 
  AND CREATE_TIME  >= to_date(:START_DATE,'YYYY-MM-DD')
  AND CREATE_TIME <= to_date(:END_DATE,'YYYY-MM-DD')