SELECT COUNT(*)
  AS USER_COUNT
  FROM TF_F_USER_BLACKWHITE A
 WHERE A.USER_TYPE_CODE = :USER_TYPE_CODE
   AND A.EC_USER_ID = TO_NUMBER(:EC_USER_ID)
   AND A.SERVICE_ID = TO_NUMBER(:SERVICE_ID)
   AND A.START_DATE < SYSDATE
   AND A.END_DATE > SYSDATE