SELECT TO_CHAR(USER_ID) USER_ID,
       SERIAL_NUMBER,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       TO_CHAR(ADJUST_FEE) ADJUST_FEE,
       REASON,
       DECODE(METHOD
              ,'0','其他') METHOD,
       REMARK,
       STAFF_ID,
       DEPART_ID,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TF_A_SPEC_PROC
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER
   AND UPDATE_TIME >= TO_DATE(:UPDATE_TIME_START, 'YYYY-MM-DD HH24:MI:SS')
   AND UPDATE_TIME <= TO_DATE(:UPDATE_TIME_END, 'YYYY-MM-DD HH24:MI:SS')