DELETE FROM TF_F_USER_SVCSTATE A
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADE_SVCSTATE B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(TO_CHAR(:TRADE_ID), 5, 2))
           AND B.USER_ID = A.USER_ID
           AND B.SERVICE_ID = A.SERVICE_ID
           AND B.STATE_CODE = A.STATE_CODE
           AND B.START_DATE = A.START_DATE
           AND B.MODIFY_TAG = '0')