SELECT A.PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       A.SERVICE_ID,
       A.MAIN_TAG,
       A.STATE_CODE,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_USER_SVCSTATE A
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.MAIN_TAG = '1'
   AND SYSDATE + 0.00001 BETWEEN A.START_DATE AND A.END_DATE