UPDATE TI_B_USER_OTHER a SET a.modify_tag = '2'
        WHERE EXISTS(SELECT 1 FROM ( SELECT PARTITION_ID,USER_ID,RSRV_VALUE_CODE,RSRV_VALUE,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_NUM6,RSRV_NUM7,RSRV_NUM8,RSRV_NUM9,RSRV_NUM10,RSRV_NUM11,RSRV_NUM12,RSRV_NUM13,RSRV_NUM14,RSRV_NUM15,RSRV_NUM16,RSRV_NUM17,RSRV_NUM18,RSRV_NUM19,RSRV_NUM20,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_STR11,RSRV_STR12,RSRV_STR13,RSRV_STR14,RSRV_STR15,RSRV_STR16,RSRV_STR17,RSRV_STR18,RSRV_STR19,RSRV_STR20,RSRV_STR21,RSRV_STR22,RSRV_STR23,RSRV_STR24,RSRV_STR25,RSRV_STR26,RSRV_STR27,RSRV_STR28,RSRV_STR29,RSRV_STR30,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4,RSRV_DATE5,RSRV_DATE6,RSRV_DATE7,RSRV_DATE8,RSRV_DATE9,RSRV_DATE10,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,RSRV_TAG4,RSRV_TAG5,RSRV_TAG6,RSRV_TAG7,RSRV_TAG8,RSRV_TAG9,RSRV_TAG10,PROCESS_TAG,STAFF_ID,DEPART_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,INST_ID
                                     FROM TI_B_USER_OTHER
                                     WHERE sync_sequence = to_number(:SYNC_SEQUENCE)
                                     AND modify_tag = '9'
                                     MINUS
                                     SELECT PARTITION_ID,USER_ID,RSRV_VALUE_CODE,RSRV_VALUE,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_NUM6,RSRV_NUM7,RSRV_NUM8,RSRV_NUM9,RSRV_NUM10,RSRV_NUM11,RSRV_NUM12,RSRV_NUM13,RSRV_NUM14,RSRV_NUM15,RSRV_NUM16,RSRV_NUM17,RSRV_NUM18,RSRV_NUM19,RSRV_NUM20,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_STR11,RSRV_STR12,RSRV_STR13,RSRV_STR14,RSRV_STR15,RSRV_STR16,RSRV_STR17,RSRV_STR18,RSRV_STR19,RSRV_STR20,RSRV_STR21,RSRV_STR22,RSRV_STR23,RSRV_STR24,RSRV_STR25,RSRV_STR26,RSRV_STR27,RSRV_STR28,RSRV_STR29,RSRV_STR30,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4,RSRV_DATE5,RSRV_DATE6,RSRV_DATE7,RSRV_DATE8,RSRV_DATE9,RSRV_DATE10,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,RSRV_TAG4,RSRV_TAG5,RSRV_TAG6,RSRV_TAG7,RSRV_TAG8,RSRV_TAG9,RSRV_TAG10,PROCESS_TAG,STAFF_ID,DEPART_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,INST_ID
                                     FROM TF_B_TRADE_OTHER_BAK
                                     WHERE trade_id = to_number(:TRADE_ID)
                                     AND accept_month = :ACCEPT_MONTH ) t1
                     WHERE a.user_id = t1.user_id
                       )
        AND sync_sequence = to_number(:SYNC_SEQUENCE)
        AND modify_tag = '9'