INSERT INTO ti_b_user_infochange
  (SYNC_SEQUENCE         ,
   MODIFY_TAG            ,
   TRADE_ID              ,
   USER_ID               ,
   TRADE_TYPE_CODE       ,
   RELATION_TRADE_ID     ,
   PRODUCT_ID            ,
   BRAND_CODE            ,
   SERIAL_NUMBER         ,
   IMSI                  ,
   NET_TYPE_CODE         ,
   
   START_DATE            ,
   END_DATE              ,
   UPDATE_TIME           ,
   UPDATE_STAFF_ID       ,
   UPDATE_DEPART_ID      ,
   REMARK)        
VALUES
  (TO_NUMBER(:SYNC_SEQUENCE),
   :MODIFY_TAG, 
   TO_NUMBER(:TRADE_ID),  
   TO_NUMBER(:USER_ID),
   TO_NUMBER(:TRADE_TYPE_CODE),
   TO_NUMBER(:RELATION_TRADE_ID),
   TO_NUMBER(:PRODUCT_ID),
   TO_NUMBER(:BRAND_CODE),
   TO_CHAR(:SERIAL_NUMBER),
   TO_CHAR(:IMSI),
   TO_CHAR(:NET_TYPE_CODE),
   TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'),
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID,
   :REMARK)