INSERT INTO TI_B_USER_IMPU(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,TEL_URL,SIP_URL,IMPI,IMS_USER_ID,IMS_PASSWORD,START_DATE,END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,TEL_URL,SIP_URL,IMPI,IMS_USER_ID,IMS_PASSWORD,START_DATE,END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5
  FROM TF_F_USER_IMPU
 WHERE USER_ID = TO_NUMBER(:USER_ID)