INSERT INTO TI_B_REMINDTHRESHOLD(SYNC_SEQUENCE, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID, REMIND_CODE, ATTR_CODE, ATTR_VALUE, START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK)
Select A.SYNC_SEQUENCE, A.MODIFY_TAG, A.TRADE_ID, A.PARTITION_ID, A.USER_ID, A.RSRV_NUM1, A.ATTR_CODE, A.ATTR_VALUE, A.START_DATE, A.END_DATE, A.UPDATE_TIME, A.UPDATE_STAFF_ID, A.UPDATE_DEPART_ID, A.REMARK
From TI_B_USER_ATTR A
 Where A.SYNC_SEQUENCE = TO_NUMBER(:SYNC_SEQUENCE)
 AND A.INST_TYPE = 'S'
AND A.RSRV_NUM1 In (SELECT c.PARA_CODE1 FROM TD_S_COMMPARA c WHERE c.SUBSYS_CODE='CSM' AND c.PARAM_ATTR ='555' AND c.PARAM_CODE ='REMIND')
 AND NOT EXISTS (SELECT 1 FROM TI_B_REMINDTHRESHOLD B
                         WHERE A.SYNC_SEQUENCE = TO_NUMBER(:SYNC_SEQUENCE)
                           AND A.PARTITION_ID = B.PARTITION_ID
                           AND A.RSRV_NUM1 = B.REMIND_CODE
                           AND A.ATTR_CODE = B.ATTR_CODE
                           AND A.ATTR_VALUE = B.ATTR_VALUE
                           AND A.USER_ID = B.USER_ID
                           AND A.START_DATE = B.START_DATE)