INSERT INTO TI_B_FIXEDFEE_SPECINFO(SYNC_SEQUENCE, MODIFY_TAG, TRADE_ID, USER_ID, USER_MODE, RECV_AREA_TYPE, RECV_USER_ID, START_ACYC_ID, END_ACYC_ID, ACT_MODE, SERVICE_ID, FEE_VALUE1, FEE_VALUE2, FEE_VALUE3, FEE_VALUE4, FEE_VALUE5, UPDATE_TIME, UPDATE_DEPART_ID, UPDATE_STAFF_ID)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),MODIFY_TAG,TO_NUMBER(:TRADE_ID),USER_ID, USER_MODE, RECV_AREA_TYPE, RECV_USER_ID, START_ACYC_ID, END_ACYC_ID, ACT_MODE, SERVICE_ID, FEE_VALUE1, FEE_VALUE2, FEE_VALUE3, FEE_VALUE4, FEE_VALUE5, UPDATE_TIME, UPDATE_DEPART_ID, UPDATE_STAFF_ID
 FROM tf_f_fixedfee_specinfo f
 WHERE f.TRADE_ID=:TRADE_ID 
  AND f.USER_ID=:USER_ID
  AND (:MODIFY_TAG IS NOT NULL or :MODIFY_TAG IS NULL)