INSERT INTO TI_B_PLATSVC (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_PLATSVC a
 WHERE      (PARTITION_ID, a.USER_ID) IN 
                 ( select mod(t1.USER_ID,10000), t1.USER_ID 
                      from TF_B_TRADE_PLATSVC t1 
                      where trade_id = TO_NUMBER(:TRADE_ID) 
                      and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))) 
 AND NOT EXISTS (select 1 from TI_B_PLATSVC c 
                 where c.sync_sequence=TO_NUMBER(:SYNC_SEQUENCE) 
                 and a.partition_id=c.partition_id 
                 and a.USER_ID=c.USER_ID 
                 and a.SERVICE_ID=c.SERVICE_ID 
                 AND a.START_DATE=c.START_DATE)