INSERT INTO TI_B_USER_RENT(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,RENT_TYPE_CODE,SERIAL_NUMBER,SIM_CARD_NO,IMSI,RENT_SIM_CARD,RENT_IMSI,RENT_DEVICE_NO,RENT_IMEI,RENT_SERIAL_NUMBER,NATIONALITY_AREACODE,START_DATE,END_DATE,RENT_TAG,OPEN_STAFF_ID,OPEN_DEPART_ID,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
     select :SYNC_SEQUENCE,'2',:TRADE_ID,a.PARTITION_ID,a.USER_ID,a.RENT_TYPE_CODE,a.SERIAL_NUMBER,a.SIM_CARD_NO,a.IMSI,a.RENT_SIM_CARD,a.RENT_IMSI,a.RENT_DEVICE_NO,a.RENT_IMEI,a.RENT_SERIAL_NUMBER,a.NATIONALITY_AREACODE,a.START_DATE,a.START_DATE - 1/24/3600,a.RENT_TAG,a.OPEN_STAFF_ID,a.OPEN_DEPART_ID,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,'删除无效数据',a.RSRV_NUM1,a.RSRV_NUM2,a.RSRV_NUM3,a.RSRV_NUM4,a.RSRV_NUM5,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_DATE1,a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3
       FROM TF_B_TRADE_RENT_BAK a 
      WHERE a.trade_id = :TRADE_ID
        AND a.accept_month = :ACCEPT_MONTH
        AND NOT EXISTS (SELECT 1 FROM TI_B_USER_RENT
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.user_id = user_id
                           AND a.rent_serial_number = rent_serial_number
                           AND a.start_date = start_date)