UPDATE TI_B_ACCOUNT_CONSIGN a SET a.modify_tag = '2'
        WHERE EXISTS(SELECT 1 FROM ( SELECT TRADE_ID,PARTITION_ID,ACCT_ID,PAY_MODE_CODE,EPARCHY_CODE,CITY_CODE,SUPER_BANK_CODE,BANK_CODE,BANK_ACCT_NO,BANK_ACCT_NAME,CONTRACT_ID,CONTRACT_NAME,CONTACT,CONTACT_PHONE,POST_ADDRESS,POST_CODE,CONSIGN_MODE,PRIORITY,PAYMENT_ID,PAY_FEE_MODE_CODE,ASSISTANT_TAG,ACCT_BALANCE_ID,ACT_TAG,START_CYCLE_ID,END_CYCLE_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10
                                     FROM TI_B_ACCOUNT_CONSIGN
                                     WHERE sync_sequence = to_number(:SYNC_SEQUENCE)
                                     AND modify_tag = '9'
                                     MINUS
                                     SELECT TRADE_ID,PARTITION_ID,ACCT_ID,PAY_MODE_CODE,EPARCHY_CODE,CITY_CODE,SUPER_BANK_CODE,BANK_CODE,BANK_ACCT_NO,BANK_ACCT_NAME,CONTRACT_ID,CONTRACT_NAME,CONTACT,CONTACT_PHONE,POST_ADDRESS,POST_CODE,CONSIGN_MODE,PRIORITY,PAYMENT_ID,PAY_FEE_MODE_CODE,ASSISTANT_TAG,ACCT_BALANCE_ID,ACT_TAG,START_CYCLE_ID,END_CYCLE_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10
                                     FROM TF_B_TRADE_CONSIGN_BAK
                                     WHERE trade_id = to_number(:TRADE_ID)
                                     AND accept_month = :ACCEPT_MONTH) t1
                     WHERE a.acct_id = t1.acct_id
                    )
        AND sync_sequence = to_number(:SYNC_SEQUENCE)
        AND modify_tag = '9'