INSERT INTO TI_B_PLATSVC(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
     select :SYNC_SEQUENCE,'2',:TRADE_ID,a.PARTITION_ID,a.USER_ID,a.PRODUCT_ID,a.PACKAGE_ID,a.SERVICE_ID,a.SERIAL_NUMBER,a.SP_CODE,a.BIZ_CODE,a.BIZ_TYPE_CODE,a.BIZ_STATE_CODE,a.PRODUCT_NO,a.ORG_DOMAIN,a.OPER_CODE,a.OPR_SOURCE,a.BILL_TYPE,a.PRICE,a.FIRST_DATE,a.FIRST_DATE_MON,a.GIFT_SERIAL_NUMBER,a.GIFT_USER_ID,a.SUBSCRIBE_ID,a.START_DATE,a.START_DATE - 1/24/3600,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,'删除无效数据',a.RSRV_NUM1,a.RSRV_NUM2,a.RSRV_NUM3,a.RSRV_NUM4,a.RSRV_NUM5,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_STR6,a.RSRV_STR7,a.RSRV_STR8,a.RSRV_STR9,a.RSRV_STR10,a.RSRV_DATE1,a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3
       FROM TF_B_TRADE_PLATSVC_BAK a 
      WHERE a.trade_id = :TRADE_ID
        AND a.accept_month = :ACCEPT_MONTH
        AND NOT EXISTS (SELECT 1 FROM TI_B_PLATSVC
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.user_id = user_id
                           AND a.service_id = service_id
                           AND a.start_date = start_date)