INSERT INTO TI_B_RELATION_BANK(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,USER_ID,PARTITION_ID,SERIAL_NUMBER,SUB_ID,BANK_ID,USER_ACCOUNT,
            PAY_TYPE,ACCOUNT_CAT,SUB_TIME,RECH_AMOUNT,RECH_THRESHOLD,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,
            RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,PAY_MODE,USER_TYPE)
SELECT :SYNC_SEQUENCE,T.MODIFY_TAG,:TRADE_ID,T.USER_ID,T.PARTITION_ID,T.SERIAL_NUMBER,T.SUB_ID,T.BANK_ID,T.USER_ACCOUNT,
            T.PAY_TYPE,T.ACCOUNT_CAT,T.SUB_TIME,T.RECH_AMOUNT,T.RECH_THRESHOLD,T.INST_ID,T.START_DATE,T.END_DATE,T.UPDATE_TIME,T.UPDATE_STAFF_ID,
            T.UPDATE_DEPART_ID,T.RSRV_STR1,T.RSRV_STR2,T.RSRV_STR3,T.RSRV_STR4,T.RSRV_STR5,T.PAY_MODE,T.USER_TYPE FROM TF_B_TRADE_RELATION_BANK T 
            WHERE T.TRADE_ID = :TRADE_ID