INSERT INTO TI_B_USER_ATTR (SYNC_SEQUENCE,  MODIFY_TAG,  TRADE_ID, PARTITION_ID,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3 )
        SELECT :SYNC_SEQUENCE,'2',:TRADE_ID, a.PARTITION_ID,a.USER_ID,a.INST_TYPE,a.INST_ID,a.ATTR_CODE,a.ATTR_VALUE,a.START_DATE,a.START_DATE - 1/24/3600,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,'删除无效数据',a.RSRV_NUM1,a.RSRV_NUM2,a.RSRV_NUM3,a.RSRV_NUM4,a.RSRV_NUM5,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_DATE1,a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3
        FROM TF_B_TRADE_ATTR_BAK a 
        WHERE trade_id=:TRADE_ID
        AND accept_month=:ACCEPT_MONTH 
        AND not exists (SELECT 1 from TI_B_USER_ATTR b
                        WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                        AND b.user_id=a.user_id
                        AND b.inst_type=a.inst_type
                        AND b.attr_code=a.attr_code
                        AND b.inst_id=a.inst_id
                        AND b.start_date=a.start_date)