INSERT INTO TI_B_PAYRELATION (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,ACCT_ID,PAYITEM_CODE,ACCT_PRIORITY,USER_PRIORITY,ADDUP_MONTHS,ADDUP_METHOD,BIND_TYPE,DEFAULT_TAG,ACT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,INST_ID,START_CYCLE_ID,END_CYCLE_ID,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,ACCT_ID,PAYITEM_CODE,ACCT_PRIORITY,USER_PRIORITY,ADDUP_MONTHS,ADDUP_METHOD,BIND_TYPE,DEFAULT_TAG,ACT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,INST_ID,START_CYCLE_ID,END_CYCLE_ID,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10
 FROM TF_A_PAYRELATION b
 WHERE b.acct_id  IN ( SELECT acct_id  FROM tf_a_payrelation 
                              WHERE user_id=to_number(:USER_ID)
                                     AND partition_id=MOD(to_number(:USER_ID),10000)
                                     AND default_tag='1'
                                     AND act_tag='1'
                                     )                                    
        AND NOT EXISTS (SELECT 1 FROM TI_B_PAYRELATION 
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND b.user_id = user_id
                           AND b.partition_id = PARTITION_ID
                           AND b.start_cycle_id = START_CYCLE_ID 
                           AND b.acct_id = ACCT_ID
                           AND b.payitem_code = PAYITEM_CODE )