UPDATE TI_B_USER_FOREGIFT t SET t.MODIFY_TAG='2'
       WHERE EXISTS (
             SELECT 1 FROM (
                    SELECT PARTITION_ID,USER_ID,FOREGIFT_CODE,MONEY,CUST_NAME,PSPT_ID,FOREGIFT_IN_DATE,FOREGIFT_OUT_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                    FROM TI_B_USER_FOREGIFT
                    WHERE SYNC_SEQUENCE = TO_NUMBER(:SYNC_SEQUENCE)
                    AND MODIFY_TAG = '9'
                   MINUS
                    SELECT PARTITION_ID,USER_ID,FOREGIFT_CODE,MONEY,CUST_NAME,PSPT_ID,FOREGIFT_IN_DATE,FOREGIFT_OUT_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                    FROM TF_B_TRADE_USER_FOREGIFT_BAK
                    WHERE TRADE_ID = :TRADE_ID
                    AND ACCEPT_MONTH = :ACCEPT_MONTH
             ) b
             WHERE b.user_id = t.user_id
             AND b.foregift_code = t.foregift_code
       )
       AND SYNC_SEQUENCE = TO_NUMBER(:SYNC_SEQUENCE)
       AND MODIFY_TAG = '9'