INSERT INTO TI_B_ACCOUNT (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,ACCT_ID,CUST_ID,PAY_NAME,PAY_MODE_CODE,ACCT_DIFF_CODE,ACCT_PASSWD,ACCT_TAG,NET_TYPE_CODE,EPARCHY_CODE,CITY_CODE,BANK_CODE,BANK_ACCT_NO,SCORE_VALUE,CREDIT_CLASS_ID,BASIC_CREDIT_VALUE,CREDIT_VALUE,DEBUTY_USER_ID,DEBUTY_CODE,CONTRACT_NO,DEPOSIT_PRIOR_RULE_ID,ITEM_PRIOR_RULE_ID,OPEN_DATE,REMOVE_TAG,REMOVE_DATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10 )
        SELECT            :SYNC_SEQUENCE,:MODIFY_TAG,:TRADE_ID,  PARTITION_ID,ACCT_ID,CUST_ID,PAY_NAME,PAY_MODE_CODE,ACCT_DIFF_CODE,ACCT_PASSWD,ACCT_TAG,NET_TYPE_CODE,EPARCHY_CODE,CITY_CODE,BANK_CODE,BANK_ACCT_NO,SCORE_VALUE,CREDIT_CLASS_ID,BASIC_CREDIT_VALUE,CREDIT_VALUE,DEBUTY_USER_ID,DEBUTY_CODE,CONTRACT_NO,DEPOSIT_PRIOR_RULE_ID,ITEM_PRIOR_RULE_ID,OPEN_DATE,REMOVE_TAG,REMOVE_DATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10
        FROM TF_F_ACCOUNT a
        WHERE (PARTITION_ID, ACCT_ID) IN 
                     ( select mod(to_number(ACCT_ID),10000), ACCT_ID
                          from TF_B_TRADE_ACCOUNT  
                          where trade_id = TO_NUMBER(:TRADE_ID) 
                          and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))) 
        AND NOT EXISTS (select 1 from TI_B_ACCOUNT  b
                         where b.sync_sequence=TO_NUMBER(:SYNC_SEQUENCE) 
                         and a.partition_id=b.partition_id 
                         and a.ACCT_ID=b.ACCT_ID )