INSERT INTO TI_B_PAYRELATION(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,ACCT_ID,PAYITEM_CODE,ACCT_PRIORITY,USER_PRIORITY,ADDUP_MONTHS,ADDUP_METHOD,BIND_TYPE,DEFAULT_TAG,ACT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,INST_ID,START_CYCLE_ID,END_CYCLE_ID,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10)
        SELECT :SYNC_SEQUENCE,'2',:TRADE_ID,MOD(a.USER_ID,10000),a.USER_ID,a.ACCT_ID,a.PAYITEM_CODE,a.ACCT_PRIORITY,a.USER_PRIORITY,a.ADDUP_MONTHS,a.ADDUP_METHOD,a.BIND_TYPE,a.DEFAULT_TAG,a.ACT_TAG,a.LIMIT_TYPE,a.LIMIT,a.COMPLEMENT_TAG,a.INST_ID,a.START_CYCLE_ID,TO_CHAR(ADD_MONTHS(TO_DATE(START_CYCLE_ID, 'yyyymm'), -1),'yyyymm') ,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,a.REMARK,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_STR6,a.RSRV_STR7,a.RSRV_STR8,a.RSRV_STR9,a.RSRV_STR10
       FROM TF_B_TRADE_PAYRELATION_BAK a
      WHERE a.trade_id = :TRADE_ID
        AND a.accept_month = :ACCEPT_MONTH
        AND NOT EXISTS (SELECT 1 FROM TI_B_PAYRELATION
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.user_id = user_id
                           and a.inst_id=inst_id )