SELECT TO_CHAR(TRADE_ID) TRADE_ID,
       ACCEPT_MONTH,
       TO_CHAR(USER_ID) USER_ID,
       INST_TYPE,
       INST_ID,
       ATTR_CODE,
       ATTR_VALUE,
       MODIFY_TAG,
       to_char(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_char(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       to_char(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_DATE1,
       RSRV_DATE2,
       RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_B_TRADE_ATTR
WHERE TRADE_ID= TO_NUMBER(:TRADE_ID)
AND   ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
AND   USER_ID = TO_NUMBER(:USER_ID)
AND   SUBSTR(INST_TYPE,0,1) = :INST_TYPE