SELECT A.*
  FROM TF_B_TRADE A, TF_B_ORDER B
 WHERE A.USER_ID = :USER_ID
   AND A.ORDER_ID = B.ORDER_ID
   AND B.EXEC_TIME = TO_DATE(:EXEC_TIME, 'YYYY-MM-DD HH24:MI:SS')
   AND A.SUBSCRIBE_TYPE >= 200
   AND A.SUBSCRIBE_TYPE < 300