select MODIFY_TAG,
       GOODS_ID ELEMENT_ID,
       'G' ELEMENT_TYPE_CODE,
       :START_DATE START_DATE,
       :END_DATE END_DATE
  from TF_B_TRADE_SALE_GOODS
 where TRADE_ID = :TRADE_ID
   and ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   and MODIFY_TAG = :MODIFY_TAG
