--IS_CACHE=Y
SELECT DISTINCT A.CUST_MANAGER_ID, B.CUST_MANAGER_NAME
   FROM TF_SM_MANAGER_JOBTYPE A, TF_F_CUST_MANAGER_STAFF B
  WHERE A.CUST_MANAGER_ID = B.CUST_MANAGER_ID
    AND A.JOB_TYPE IN ('2', '6')
  ORDER BY A.CUST_MANAGER_ID ASC