SELECT T.PRODUCT_ID, T.GROUP_ID, T.PRODUCT_MGR_SN, T.VALID_TAG
  FROM TF_F_GRP_PRODUCT_MANAGER T
 WHERE 1 = 1
   AND GROUP_ID = :GROUP_ID
   AND PRODUCT_MGR_SN = :PRODUCT_MGR_SN
   AND VALID_TAG = '0'