SELECT ACCEPT_MONTH,START_TIME,END_TIME,MS_ID,NAT_CLIENT_IP,NAT_CLIENT_PORT,DESTINATION_URL
DESTINATION_IP,DESTINATION_PORT,CLIENT_IP,CLIENT_PORT,APN FROM TF_B_GONET_LOG
WHERE MS_ID = :MS_ID AND :START_TIME <= START_TIME AND :END_TIME >= END_TIME