Select To_Char(Trade_Id) Trade_Id,
       Accept_Month,
       To_Char(Batch_Id) Batch_Id,
       To_Char(Order_Id) Order_Id,
       To_Char(Prod_Order_Id) Prod_Order_Id,
       To_Char(Bpm_Id) Bpm_Id,
       Campn_Id,
       Trade_Type_Code,
       Priority,
       Subscribe_Type,
       Subscribe_State,
       Next_Deal_Tag,
       In_Mode_Code,
       Nvl(To_Char(Cust_Id), '0') Cust_Id,
       Cust_Name,
       To_Char(User_Id) User_Id,
       Nvl(To_Char(Acct_Id), '0') Acct_Id,
       Serial_Number,
       Net_Type_Code,
       Eparchy_Code,
       City_Code,
       Product_Id,
       Brand_Code,
       To_Char(Cust_Id_b) Cust_Id_b,
       To_Char(User_Id_b) User_Id_b,
       To_Char(Acct_Id_b) Acct_Id_b,
       Serial_Number_b,
       Cust_Contact_Id,
       Serv_Req_Id,
       Intf_Id,
       To_Char(Accept_Date, 'yyyy-mm-dd hh24:mi:ss') Accept_Date,
       Trade_Staff_Id,
       Trade_Depart_Id,
       Trade_City_Code,
       Trade_Eparchy_Code,
       Term_Ip,
       To_Char(Oper_Fee) Oper_Fee,
       To_Char(Foregift) Foregift,
       To_Char(Advance_Pay) Advance_Pay,
       Invoice_No,
       Fee_State,
       To_Char(Fee_Time, 'yyyy-mm-dd hh24:mi:ss') Fee_Time,
       Fee_Staff_Id,
       Process_Tag_Set,
       Olcom_Tag,
       To_Char(Finish_Date, 'yyyy-mm-dd hh24:mi:ss') Finish_Date,
       To_Char(Exec_Time, 'yyyy-mm-dd hh24:mi:ss') Exec_Time,
       Exec_Action,
       Exec_Result,
       Exec_Desc,
       Cancel_Tag,
       To_Char(Cancel_Date, 'yyyy-mm-dd hh24:mi:ss') Cancel_Date,
       Cancel_Staff_Id,
       Cancel_Depart_Id,
       Cancel_City_Code,
       Cancel_Eparchy_Code,
       To_Char(Update_Time, 'yyyy-mm-dd hh24:mi:ss') Update_Time,
       Update_Staff_Id,
       Update_Depart_Id,
       Remark,
       Rsrv_Str1,
       Rsrv_Str2,
       Rsrv_Str3,
       Rsrv_Str4,
       Rsrv_Str5,
       Rsrv_Str6,
       Rsrv_Str7,
       Rsrv_Str8,
       Rsrv_Str9,
       Rsrv_Str10
  From Tf_b_Trade a
 Where a.Serial_Number = :SERIAL_NUMBER
   And a.Trade_Type_Code In (600, 612, 613)
   And a.Cancel_Tag = '0'