SELECT *
  FROM TF_F_RELATION_UU U
 WHERE 1 = 1
   AND U.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND U.USER_ID_B = TO_NUMBER(:USER_ID)
   AND U.RELATION_TYPE_CODE IN ('S3')
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE
   AND U.END_DATE > LAST_DAY(TRUNC(SYSDATE)) + 1 - 1 / 24 / 3600
   AND ROWNUM < 2
