--IS_CACHE=Y
SELECT RECOMM_SOURCE,RECOMM_TYPE,PRODUCT_ID,PACKAGE_ID,ELEMENT_ID,ELEMENT_NAME,RECOMM_CONTENT,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,
to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,EPARCHY_CODE,REMARK, UPDATE_STAFF_ID,UPDATE_DEPART_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
PARA_CODE1,PARA_CODE2,PARA_CODE3,PARA_CODE4,PARA_CODE5,PARA_CODE6,PARA_CODE7,PARA_CODE8,PARA_CODE9,PARA_CODE10            
FROM   TD_B_RECOMMPARA
  WHERE RECOMM_TYPE=:RECOMM_TYPE
  AND (RECOMM_SOURCE=:RECOMM_SOURCE OR :RECOMM_SOURCE IS NULL)
  AND ELEMENT_ID=:ELEMENT_ID
  AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')
  AND SYSDATE BETWEEN START_DATE AND END_DATE