SELECT TRADE_ID,OPER_MONTH,OPER_TIME,NAME,CHSNAME,SSRQ,NSRBSM,ZYZGZH,SSGS,NSRMC,SCBH,FJDM,SBRQ,
RECORDCOUNT,KSRQ,JSRQ,MONTH,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,PARA_VALUE1,PARA_VALUE2,PARA_VALUE3,PARA_VALUE4,
PARA_VALUE5,PARA_VALUE6,PARA_VALUE7,PARA_VALUE8,PARA_VALUE9,PARA_VALUE10,PARA_VALUE11,PARA_VALUE12,PARA_VALUE13,
PARA_VALUE14,PARA_VALUE15,PARA_VALUE16,PARA_VALUE17,PARA_VALUE18,RDVALUE1,RDVALUE2,REMARK2 
FROM TF_B_TICKET_YB_LOG WHERE OPER_MONTH=:OPER_MONTH