SELECT * FROM (SELECT ROW_.*, ROWNUM ROWNUM_ FROM (SELECT (CASE WHEN R.OID IN (SELECT OID  FROM TF_B_CTRM_ORDER_PRODUCT
WHERE STATUS = '2' AND OID = R.OID AND TID=R.TID AND RSRV_STR6='IS_ABILITY_TRANS')  THEN '2' ELSE '1'  END) RESULT_CODE,
(SELECT REMARK  FROM TF_B_CTRM_ORDER_PRODUCT WHERE STATUS = '2' AND OID = R.OID AND TID=R.TID AND ROWNUM=1) RESULT_INFO, R.*  FROM TF_B_CTRM_ORDER R 
WHERE NOT EXISTS (SELECT 1 FROM TF_B_CTRM_ORDER_PRODUCT P WHERE P.STATUS = '0'  AND P.OID = R.OID AND P.TID =R.TID) 
and exists(SELECT 1 FROM  TF_B_CTRM_TLIST  WHERE distribution ='2' and tid = R.tid)
 AND  R.RSRV_STR4 IS NULL  ) ROW_ WHERE ROWNUM <= 500) WHERE ROWNUM_ > 0