SELECT
       A.USER_ID,
       A.SERVICE_ID,
       A.BIZ_STATE_CODE,
       A.INST_ID,
       TO_CHAR(A.START_DATE,'yyyy-MM-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE,'yyyy-MM-dd hh24:mi:ss') END_DATE
  FROM TF_F_USER_PLATSVC_TRACE  A
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND A.BIZ_STATE_CODE IN ('A','N','E')
   ORDER BY A.BIZ_STATE_CODE , A.START_DATE DESC