INSERT INTO TI_B_USER_SHARE
      (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, SHARE_INST_ID, PARTITION_ID,
       SHARE_ID, USER_ID, TRADE_ID, RELA_INST_ID, DISCNT_CODE, DISCNT_CODE_A,
       SHARE_TYPE, END_DATE, START_DATE, REMARK, UPDATE_DEPART_ID,
       UPDATE_STAFF_ID, UPDATE_TIME, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4,
       RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5,
       RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3) values
(:SYNC_SEQUENCE,:SYNC_DAY,:MODIFY_TAG,:SHARE_INST_ID,:PARTITION_ID,
:SHARE_ID,:USER_ID,:TRADE_ID,:RELA_INST_ID,:DISCNT_CODE,:DISCNT_CODE_A,
:SHARE_TYPE,:END_DATE,:START_DATE,:REMARK,:UPDATE_DEPART_ID,
:UPDATE_STAFF_ID,:UPDATE_TIME,:RSRV_NUM1,:RSRV_NUM2,:RSRV_NUM3,:RSRV_NUM4,
:RSRV_NUM5,:RSRV_STR1,:RSRV_STR2,:RSRV_STR3,:RSRV_STR4,:RSRV_STR5,
:RSRV_DATE1,:RSRV_DATE2,:RSRV_DATE3,:RSRV_TAG1,:RSRV_TAG2,:RSRV_TAG3)