UPDATE  TF_F_USER_PLATSVC_BOOK set BOOK_STATE=:BOOK_STATE1
 WHERE USER_ID = :USER_ID
   AND SERVICE_ID = :SERVICE_ID
   AND BOOK_STATE = :BOOK_STATE
   AND OPER_CODE in (:OPER_CODE1,:OPER_CODE2,:OPER_CODE3)
   AND START_DATE > SYSDATE