UPDATE TF_F_USER_PLATSVC_BOOK
   SET BIZ_STATE_CODE = 'N',OPER_CODE='04'
 WHERE USER_ID = :USER_ID
   AND BOOK_STATE = '0'
   AND START_DATE > SYSDATE
   AND BIZ_TYPE_CODE='53'
   AND OPER_CODE IN('06','01')