UPDATE  TL_B_ACTIVE_PSPT_ID
    SET SERIAL_NUMBER = :SERIAL_NUMBER,
        STATE = :STATE,
        ACTIVE_TIME = sysdate,
        ACTIVE_TRADE_ID = :ACTIVE_TRADE_ID
 WHERE PSPT_ID = :PSPT_ID
   AND PRODUCT_ID = :PRODUCT_ID
   AND PACKAGE_ID = :PACKAGE_ID