UPDATE TF_F_ACCOUNT_CONSIGN SET 
END_CYCLE_ID = :END_CYCLE_ID, UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, UPDATE_TIME = to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , REMARK = :REMARK
WHERE 
PARTITION_ID = MOD(to_number(:ACCT_ID),10000) and ACCT_ID = to_number(:ACCT_ID) and BANK_CODE = :BANK_CODE and BANK_ACCT_NO = :BANK_ACCT_NO and START_CYCLE_ID = :START_CYCLE_ID