INSERT INTO TF_F_ACCOUNT_CONSIGN(
PARTITION_ID, ACCT_ID, PAY_MODE_CODE, EPARCHY_CODE, CITY_CODE, SUPER_BANK_CODE, BANK_CODE, BANK_ACCT_NO, BANK_ACCT_NAME, CONTRACT_ID, CONTRACT_NAME, CONTACT, CONTACT_PHONE, POST_ADDRESS, POST_CODE, CONSIGN_MODE, PRIORITY, PAYMENT_ID, PAY_FEE_MODE_CODE, ASSISTANT_TAG, ACCT_BALANCE_ID, ACT_TAG, START_CYCLE_ID, END_CYCLE_ID, UPDATE_STAFF_ID, UPDATE_DEPART_ID, UPDATE_TIME, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10) 
SELECT
PARTITION_ID,  ACCT_ID, PAY_MODE_CODE, EPARCHY_CODE, CITY_CODE, SUPER_BANK_CODE, BANK_CODE, BANK_ACCT_NO, BANK_ACCT_NAME, '', 
'', '', '','','',CONSIGN_MODE,PRIORITY,PAYMENT_ID,PAY_FEE_MODE_CODE, ASSISTANT_TAG,  ACCT_BALANCE_ID, ACT_TAG, START_CYCLE_ID, END_CYCLE_ID, UPDATE_STAFF_ID, UPDATE_DEPART_ID, UPDATE_TIME, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10
FROM TF_B_TRADE_CONSIGN_BAK a
WHERE a.trade_id=:TRADE_ID
AND   a.acct_id =:ACCT_ID
AND   a.pay_mode_code='1'
AND   a.eparchy_code=:EPARCHY_CODE