UPDATE TF_F_ACCOUNT_CONSIGN 
   SET update_staff_id=:UPDATE_STAFF_ID,update_depart_id=:UPDATE_DEPART_ID,update_time=SYSDATE,end_cycle_id=:END_CYCLE_ID
   WHERE PARTITION_ID=MOD(TO_NUMBER(:ACCT_ID),10000)
   AND   ACCT_ID=:ACCT_ID
   AND   BANK_CODE=:BANK_CODE
   AND   BANK_ACCT_NO=:BANK_ACCT_NO
   AND   START_CYCLE_ID=:START_CYCLE_ID