SELECT  RULE_ID,VENDOR_CODE,MATERIAL_CODE,PROTECT_TYPE,START_DATE,END_DATE,
   F_RES_GETCODENAME('terminal_vendor',VENDOR_CODE,'','')VENDOR ,
   DECODE(PROTECT_TYPE,'11','提货定额价保','12','提货差额价保','21','库存定额价保','22','库存差额价保')PROTECT_TYPE_DESC ,
   (SELECT NAME FROM TF_R_PRODUCT_GRP A WHERE A.MATERIAL_CODE=B.MATERIAL_CODE)TERMINAL_NAME 
FROM  TD_R_CPPRICEPROTECT_RULE B
WHERE  1=1 AND (:RULE_ID  IS NULL OR RULE_ID=:RULE_ID)
  
AND (:VENDOR_CODE  IS NULL OR VENDOR_CODE=:VENDOR_CODE)
 
AND (:PROTECT_TYPE  IS NULL OR PROTECT_TYPE=:PROTECT_TYPE)