--IS_CACHE=N
SELECT A.TRADE_ID 台账标识
   FROM UCR_CRM1.TF_B_TRADE_RELATION A
  WHERE A.RELATION_TYPE_CODE = '45'
    AND A.USER_ID_B = :USER_ID
    AND A.USER_ID_A = :USER_ID_A
    AND A.INST_ID = :INST_ID
    AND A.MODIFY_TAG = '0'
    AND ROWNUM < 2