UPDATE TF_F_USER_PLATSVC_BOOK A
   SET A.BOOK_STATE = '1',
       A.REMARK = :REMARK
 WHERE A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.BOOK_STATE = '0'
   AND EXISTS
 (SELECT 1
          FROM TD_B_PLATSVCBOOK_CONFIG B
         WHERE B.SERVICE_ID = :SERVICE_ID
           AND B.OPER_CODE = '06'
           AND B.BOOK_TAG = '0')