SELECT COUNT(1) recordcount FROM ucr_crm1.TF_B_TRADE_RELATION a
WHERE TRADE_ID = :TRADE_ID
AND ACCEPT_MONTH = :ACCEPT_MONTH
AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
AND MODIFY_TAG = :MODIFY_TAG
AND ROLE_CODE_B = :ROLE_CODE_B
AND EXISTS (SELECT 1 FROM ucr_crm1.TF_F_USER_INFOCHANGE
            WHERE USER_ID = a.USER_ID_B
            AND PARTITION_ID = MOD(a.USER_ID_B,10000)
            AND END_DATE > ADD_MONTHS(TRUNC(SYSDATE,'MM'),1)
            AND BRAND_CODE IN (SELECT PARA_CODE1 FROM TD_S_COMMPARA
              WHERE SUBSYS_CODE='CSM'
                AND PARAM_ATTR=2001
                AND PARAM_CODE=:PARAM_CODE
                AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')
                AND SYSDATE BETWEEN START_DATE AND END_DATE))