SELECT :SYNC_SEQUENCE SYNC_SEQUENCE, substr(:SYNC_SEQUENCE,7,2) SYNC_DAY, '8' MODIFY_TAG, B.SHARE_INST_ID,
             MOD(B.USER_ID, 10000) PARTITION_ID, B.SHARE_ID, B.USER_ID, :TRADE_ID TRADE_ID,
             B.RELA_INST_ID, B.DISCNT_CODE, B.DISCNT_CODE_A, B.SHARE_TYPE,
             B.END_DATE, B.START_DATE, B.REMARK, B.UPDATE_DEPART_ID,
             B.UPDATE_STAFF_ID, B.UPDATE_TIME, B.RSRV_NUM1, B.RSRV_NUM2,
             B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2,
             B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1, B.RSRV_DATE2,
             B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3
        FROM TF_F_USER_SHARE B
       WHERE B.SHARE_ID = :SHARE_ID  and end_date>sysdate