SELECT RECORDID RESULT_ID, ORDERTYPE ORDER_TYPE, REQUESTCODE REQUEST_CODE, MATERIALCODE MATERIAL_CODE, 
	RESULT RESULT_STATE, ORDERQUANITY ORDER_QUANITY, CPORDERCODE CPORDER_CODE, TAKEDATE TAKE_DATE,
	RESULTCOMMENT RESULT_COMMENT, OPRNUMB OPER_TRADE_ID, '0' DEAL_FLAG, '0' ORDER_STATUS
FROM TI_R_CPORDERRESULT_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')