SELECT A.PRODUCTID PRODUCT_ID,
	B.ATTRIBUTEID ATTRIBUTE_ID, B.ATTRIBUTENAME ATTRIBUTE_NAME, B.ATTRIBUTEVALUE ATTRIBUTE_VALUE
FROM TI_R_PRODUCT_DOWN A, TI_R_PRODUCT_ATTRIBUTE_DOWN B
WHERE 1 = 1
AND A.RECORDID = B.RECORDID
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND (A.MODELTYPE IS NULL OR A.MODELTYPE='0')