SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_USER_SHARE_RELA R, TF_F_RELATION_UU U
 WHERE R.USER_ID_B = :USER_ID
   AND R.ROLE_CODE = '02'
   AND R.RSRV_TAG1 = '1'
   AND U.RELATION_TYPE_CODE = '56'
   AND U.ROLE_CODE_B = '2'
   AND R.USER_ID_B = U.USER_ID_B
   AND U.RSRV_TAG1 = '1'
   AND R.END_DATE > SYSDATE
   AND U.END_DATE > SYSDATE
   AND EXISTS (SELECT 1
          FROM TF_F_RELATION_UU UA,TF_F_USER_PRODUCT P
         WHERE UA.USER_ID_A = U.USER_ID_A
           AND UA.RELATION_TYPE_CODE = U.RELATION_TYPE_CODE
           AND UA.ROLE_CODE_B = '1'
           AND UA.USER_ID_B = P.USER_ID 
           AND P.MAIN_TAG = '1'
           AND P.PRODUCT_ID = 80003014
           AND P.END_DATE >SYSDATE
           AND UA.END_DATE > SYSDATE)