SELECT M.ELEMENT_ID DISCNT_CODE,
       C.PARAM_NAME DISCNT_NAME,
       COUNT(*) DISCNT_NUMBER
  FROM TF_F_USER_MEB_CENPAY M, TD_S_COMMPARA C
 WHERE 1 = 1
   AND M.PARTITION_ID = MOD(TO_NUMBER(M.USER_ID), 10000)
   AND M.MP_GROUP_CUST_CODE = :USER_ID_A
   AND M.END_DATE > SYSDATE
   AND M.OPER_TYPE = :OPER_TYPE
   AND C.PARAM_ATTR = 7347
   AND C.PARAM_CODE = 'GRP_GFFF_DINGE'
   AND M.ELEMENT_ID = TO_NUMBER(C.PARA_CODE2)
   AND C.END_DATE > SYSDATE
 GROUP BY M.ELEMENT_ID, C.PARAM_NAME