UPDATE TF_B_TRADE_OTHER
   SET RSRV_STR8  = :RSRV_STR8,
       RSRV_STR9  = :RSRV_STR9,
       RSRV_STR10 = :RSRV_STR10,
       RSRV_STR11 = :RSRV_STR11,
       RSRV_STR12 = :RSRV_STR12,
       RSRV_STR13 = :RSRV_STR13,
       RSRV_STR14 = :RSRV_STR14,
       RSRV_STR15 = :RSRV_STR15,
       RSRV_STR16 = :RSRV_STR16
 WHERE TRADE_ID = :TRADE_ID
   AND RSRV_VALUE_CODE = :RSRV_VALUE_CODE
