--IS_CACHE=Y
SELECT DEPT.DEPART_ID,
       DEPT.DEPART_CODE,
       DEPT.DEPART_NAME,
       DEPT.ORDER_NO,
       DEPT.DEPART_CODE || '|' || DEPT.DEPART_NAME DEPART_TEXT,
       DEPT.PARENT_DEPART_ID,
       DEPT.DEPART_FRAME,
       DEPT.AREA_CODE,
       DECODE(CHILDS.NODE_COUNT, NULL, 0, CHILDS.NODE_COUNT) NODE_COUNT,
       DECODE(CHILDS.NODE_COUNT, NULL, 0, 1) EXPAND_NODE
  FROM TD_M_DEPART DEPT,
       (SELECT PARENT_DEPART_ID, COUNT(DEPART_ID) NODE_COUNT
          FROM TD_M_DEPART
         WHERE 1 = 1 AND DEPART_KIND_CODE IN ('100', '801')
         GROUP BY PARENT_DEPART_ID) CHILDS
 WHERE DEPT.DEPART_ID = CHILDS.PARENT_DEPART_ID(+)
   AND DEPT.DEPART_KIND_CODE IN ('100', '801')
   AND DEPT.VALIDFLAG = '0'
   AND DEPT.PARENT_DEPART_ID = :PARENT_DEPART_ID