INSERT INTO TL_B_VALUECARD_DETAILED(
            TRADE_ID,ACCEPT_MONTH,TRADE_TYPE_CODE,KIND_NAME,CARD_NUMBER,DEVICE_PRICE,
            TRADE_STAFF_ID,ACCEPT_DATE,SALE_PRICE,GROUP_ID,CUST_ID,CITY_CODE,DEPART_CODE,UPDATE_TIME,STATE_NAME,STATE_CODE,RSRV_STR3,RSRV_STR4,RSRV_STR5)
VALUES   (
            :TRADE_ID,TO_NUMBER(:ACCEPT_MONTH),TO_NUMBER(:TRADE_TYPE_CODE),:KIND_NAME,:CARD_NUMBER,:DEVICE_PRICE,:TRADE_STAFF_ID,:ACCEPT_DATE,:SALE_PRICE,
            :GROUP_ID,TO_NUMBER(:CUST_ID),:CITY_CODE,:DEPART_CODE,:UPDATE_TIME,:STATE_NAME,:STATE_CODE,:RSRV_STR3,:RSRV_STR4,:RSRV_STR5
         )