SELECT HOME_ADDR,TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') EARLY_WARNING_DATE,rsrv_tag3 REG_STATUS,count(1) EARLY_WARNING_NUMBER
  FROM TF_F_WIDENET_BOOK A
 WHERE  (A.RSRV_DATE2 >= TO_DATE(:START_DATE, 'YYYY-MM-DD') OR :START_DATE IS NULL) 
   AND (A.RSRV_DATE2 <= TO_DATE(:END_DATE, 'YYYY-MM-DD') + 1 OR :END_DATE IS NULL)
   AND A.HOME_ADDR in (select HOME_ADDR from tf_f_widenet_book where SET_ADDR like :SET_ADDR)
   AND rsrv_tag3 = :REG_STATUS
   group by HOME_ADDR,RSRV_DATE2,rsrv_tag3
   order by RSRV_DATE2 ASC