select vip_id,
       to_char(cust_id) cust_id,
       to_char(usecust_id) usecust_id,
       to_char(user_id) user_id,
       serial_number,
       net_type_code,
       cust_name,
       usecust_name,
       usepspt_type_code,
       usepspt_id,
       usepspt_addr,
       usephone,
       usepost_addr,
       eparchy_code,
       city_code,
       vip_type_code,
       vip_class_id,
       vip_type_code_b,
       vip_class_id_b,
       vip_card_no,
       vip_card_type,
       vip_card_passwd,
       vip_card_state,
       vip_card_spell,
       vip_card_info,
       cust_manager_id,
       cust_manager_id_b,
       cust_manager_appr,
       to_char(assign_date, 'yyyy-mm-dd hh24:mi:ss') assign_date,
       assign_staff_id,
       join_type,
       to_char(join_date, 'yyyy-mm-dd hh24:mi:ss') join_date,
       join_staff_id,
       join_depart_id,
       group_id,
       group_cust_name,
       to_char(month_fee) month_fee,
       hvalue_tag,
       brand_code,
       product_id,
       user_type_code,
       user_state_codeset,
       to_char(open_date, 'yyyy-mm-dd hh24:mi:ss') open_date,
       to_char(first_call_time, 'yyyy-mm-dd hh24:mi:ss') first_call_time,
       to_char(last_stop_time, 'yyyy-mm-dd hh24:mi:ss') last_stop_time,
       to_char(score_value) score_value,
       credit_class,
       to_char(credit_value) credit_value,
       to_char(trade_id) trade_id,
       cancel_tag,
       remove_tag,
       to_char(remove_date, 'yyyy-mm-dd hh24:mi:ss') remove_date,
       remove_staff_id,
       remove_reason,
       to_char(update_time, 'yyyy-mm-dd hh24:mi:ss') update_time,
       update_staff_id,
       update_depart_id,
       remark            
  FROM     TF_F_CUST_VIP 
 WHERE     CUST_ID=to_number(:CUST_ID) 
   And (:REMOVE_TAG IS NULL OR REMOVE_TAG = :REMOVE_TAG)