SELECT SERIAL_NUMBER,USER_ID,TERM_MODEL,WAP_VERSION,MPHONE_SHOW_TAG,COLORING_TAG,GPRS_TAG,AVG_ARPU,AVG_NEW_FEE,MMS_FEE,GPRS_FEE,
SMS_FEE,COMMEND_TYPE,COMMEND_TAG,SUCCESS_TAG,COMMEND_DATE,COMMEND_STAFF_ID,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5
FROM TF_F_USER_COMMEND
WHERE USER_ID=TO_NUMBER(:USER_ID)
AND COMMEND_TYPE=:COMMEND_TYPE