select * from TF_B_CTRM_GERLSUBORDER 
	where 1=1 
	AND STATE=:STATE 
	AND ORDER_ID=:ORDER_ID 
	AND SUBORDER_ID=:SUBORDER_ID 
	AND (NUMBER_OPRTYPE='20' OR NUMBER_OPRTYPE='21' OR NUMBER_OPRTYPE='08' OR NUMBER_OPRTYPE='09' OR NUMBER_OPRTYPE='23' OR NUMBER_OPRTYPE='24')
