SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(USER_ID_A) USER_ID_A,
       DISCNT_CODE,
       SPEC_TAG,
       RELATION_TYPE_CODE,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       TO_CHAR(RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(RSRV_NUM5) RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       TO_CHAR(D.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(D.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
  FROM TF_F_USER_DISCNT D
 WHERE 1 = 1
   AND D.USER_ID = TO_NUMBER(:USER_ID)
   AND D.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND D.START_DATE < D.END_DATE
   AND SYSDATE < D.END_DATE
   AND SYSDATE < D.START_DATE
   AND D.START_DATE < (SELECT MAX(T.END_DATE)
  FROM TD_S_COMMPARA C,TF_F_USER_DISCNT T
 WHERE C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = 4455
   AND C.PARAM_CODE = 'SHARE'
   AND C.START_DATE < SYSDATE
   AND C.END_DATE > SYSDATE
   AND T.USER_ID = D.USER_ID
   AND T.PARTITION_ID = D.PARTITION_ID
   AND T.DISCNT_CODE = C.PARA_CODE1
   AND T.START_DATE < SYSDATE
   AND T.END_DATE > SYSDATE
   )
   AND NOT EXISTS (SELECT 1
          FROM TD_S_COMMPARA C
         WHERE C.SUBSYS_CODE = 'CSM'
           AND C.PARAM_ATTR = 4455
           AND C.PARAM_CODE = 'SHARE'
           AND C.START_DATE < SYSDATE
           AND C.END_DATE > SYSDATE
           AND D.DISCNT_CODE = C.PARA_CODE1)