SELECT USER_ID, RSRV_STR4
  FROM TF_F_USER_PLATSVC
 WHERE PARTITION_ID = MOD(:USER_ID, 10000)
   AND USER_ID = :USER_ID
   AND BIZ_TYPE_CODE = '37'
   AND ORG_DOMAIN = 'EWPT'
   AND BIZ_STATE_CODE IN ('A', 'N', 'L')
   AND SYSDATE BETWEEN START_DATE AND END_DATE