--IS_CACHE=Y
SELECT to_char(ID) ID, ID_TYPE, ATTR_OBJ, ATTR_CODE, ATTR_NAME, ATTR_VALUE, EPARCHY_CODE,    RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5
  FROM td_b_attr_biz t
 WHERE 1=1
 AND id=TO_NUMBER(:ID)
 AND id_type=:ID_TYPE
 AND attr_obj=:ATTR_OBJ
 AND SYSDATE BETWEEN t.START_DATE AND t.END_DATE