INSERT INTO TF_F_USER_RES(
PARTITION_ID, USER_ID, USER_ID_A, RES_TYPE_CODE, RES_CODE, IMSI, KI, INST_ID, CAMPN_ID, START_DATE, END_DATE, REMARK, RSRV_STR1, RSRV_STR2)
VALUES (MOD(to_number(:USER_ID),10000), to_number(:USER_ID) , -1,:RES_TYPE_CODE,:RES_CODE,null,null,-1,null,TRUNC(SYSDATE),ADD_MONTHS(TRUNC(SYSDATE),12),null,:RSRV_STR1,null)