SELECT PARTITION_ID,
       USER_ID,
       USER_ID_A,
       RES_TYPE_CODE,
       RES_CODE,
       IMSI,
       KI,
       INST_ID,
       CAMPN_ID,
       TO_CHAR(START_DATE, 'yyyy-MM-dd HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE,'yyyy-MM-dd HH24:MI:SS') END_DATE,
       TO_CHAR(UPDATE_TIME,'yyyy-MM-dd HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       TO_CHAR(RSRV_DATE1,'yyyy-MM-dd HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2,'yyyy-MM-dd HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3,'yyyy-MM-dd HH24:MI:SS') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_F_USER_RES T
 WHERE T.USER_ID = :USER_ID
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.RES_TYPE_CODE = :RES_TYPE_CODE
   AND T.RSRV_TAG1 = :RSRV_TAG1
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE