SELECT /*+ index(c,IDX_TF_F_USER_RES_RESTYPE)*/ C.IMSI
  FROM TF_F_USER_RES C, TF_F_USER B
 WHERE B.USER_ID = C.USER_ID
   AND B.PARTITION_ID = C.PARTITION_ID
   AND B.REMOVE_TAG = '0'
   AND SUBSTR(B.BRAND_CODE, 1, 2) = 'G0'
   AND (INSTR(B.USER_STATE_CODESET, '3', 1) > 0 OR
       INSTR(B.USER_STATE_CODESET, '4', 1) > 0 OR
       INSTR(B.USER_STATE_CODESET, '5', 1) > 0 OR
       INSTR(B.USER_STATE_CODESET, '7', 1) > 0)
   AND INSTR(B.USER_STATE_CODESET, '1', 1) = 0
   AND INSTR(B.USER_STATE_CODESET, '2', 1) = 0
   AND C.END_DATE > SYSDATE
   AND C.RES_TYPE_CODE = '1'