--IS_CACHE=Y
SELECT 
  TASK_ID,
  PLAN_INDEX,
  PLAN,
  PARAMS,
  USE_TAG,
  EXPIRED_TAG,
  LAST_EXEC_TIME,
  LAST_FINISH_TIME,
  EXCEPTION_TAG,
  RESULT_CODE,
  RESULT_INFO,
  EXCEPTION_INFO
FROM TD_M_TASK_PLAN
WHERE LAST_EXEC_TIME IS NULL
  AND LAST_FINISH_TIME IS NOT NULL
  AND TASK_ID = :TASK_ID