SELECT T.BUSIFORM_ID,T1.SUB_BUSIFORM_ID,T1.RELE_CODE,T1.RELE_VALUE
  FROM TF_B_EWE T, TF_B_EWE_RELE T1
 WHERE T.BUSIFORM_ID = T1.BUSIFORM_ID
   AND T1.RELE_VALUE = :RELE_VALUE
   AND T1.RELE_CODE = 'RECORD_NUM'
   AND T.BI_SN = :BI_SN
   AND T.STATE = :STATE  
