SELECT A.RECORDID QUOTE_ID, 
	B.RECORDID REBATE_ID, B.PRICE REBATE_PRICE, 
	B.LOWQUANTITY LOW_QUANTITY, B.HIGHQUANTITY HIGH_QUANTITY
FROM TI_R_PRICE_DOWN A, TI_R_PRICE_REBATE_DOWN B
WHERE 1 = 1
AND A.RECORDID = B.RECORDID
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')