INSERT INTO TI_B_INTEGRAL_PLAN
        (SYNC_DAY, SYNC_SEQUENCE, MODIFY_TAG, TRADE_ID, INTEGRAL_PLAN_INST_ID,
         PARTITION_ID, USER_ID, INTEGRAL_ACCT_ID, INTEGRAL_PLAN_ID, START_DATE,
         END_DATE, STATUS, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
         RSRV_STR5, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5,
         RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
        SELECT :SYNC_DAY, :SYNC_SEQUENCE,
               DECODE(MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               :TRADE_ID, INTEGRAL_PLAN_INST_ID, MOD(USER_ID, 10000), USER_ID,
               INTEGRAL_ACCT_ID, INTEGRAL_PLAN_ID, START_DATE, END_DATE, STATUS,
               REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5,
               RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_DATE1,
               RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
          FROM TF_B_TRADE_INTEGRALPLAN
         WHERE TRADE_ID = :TRADE_ID
           AND ACCEPT_MONTH = :ACCEPT_MONTH