select TRADE_ID, ACCEPT_MONTH, MODIFY_TAG, USER_ID, INST_ID, RELA_INST_ID, SERVICE_CODE, BILLING_TYPE, USAGE_STATE, START_DATE, END_DATE, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5
  FROM TF_B_TRADE_PCRF 
 WHERE trade_id = to_number(:TRADE_ID)
   and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
