SELECT T.PARTITION_ID,
       TO_CHAR(T.ACCT_ID) ACCT_ID,
       T.ACCT_DAY,
       T.CHG_TYPE,
       T.CHG_MODE,
       TO_CHAR(T.CHG_DATE, 'YYYY-MM-DD HH24:MI:SS') CHG_DATE,
       TO_CHAR(T.FIRST_DATE, 'YYYY-MM-DD HH24:MI:SS') FIRST_DATE,
       T.INST_ID,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(T.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       T.UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID,
       T.REMARK,
       T.RSRV_NUM1,
       T.RSRV_NUM2,
       T.RSRV_NUM3,
       T.RSRV_NUM4,
       T.RSRV_NUM5,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5,
       TO_DATE(T.RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_DATE(T.RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_DATE(T.RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       T.RSRV_TAG1,
       T.RSRV_TAG2,
       T.RSRV_TAG3
  FROM TF_F_ACCOUNT_ACCTDAY T
 WHERE T.ACCT_ID = TO_NUMBER(:ACCT_ID)
   AND T.PARTITION_ID = MOD(TO_NUMBER(:ACCT_ID), 10000)
   AND T.END_DATE > T.START_DATE
   AND T.END_DATE > SYSDATE
 ORDER BY T.START_DATE DESC