SELECT A.SERVICE_ID
  FROM TF_F_USER_PLATSVC A
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.BIZ_STATE_CODE <> 'E'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND NOT EXISTS (SELECT 1
          FROM TF_B_TRADE B, TF_B_TRADE_PLATSVC C
         WHERE B.TRADE_ID = C.TRADE_ID
           AND B.USER_ID = :USER_ID
           AND C.SERVICE_ID = :SERVICE_ID
           AND C.BIZ_STATE_CODE = 'E')
UNION
SELECT D.SERVICE_ID
  FROM TF_F_USER_SVC D
 WHERE D.PARTITION_ID = MOD(:USER_ID, 10000)
   AND D.USER_ID = :USER_ID
   AND D.SERVICE_ID = :SERVICE_ID
   AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
   AND NOT EXISTS (SELECT 1
          FROM TF_B_TRADE E, TF_B_TRADE_SVC F
         WHERE E.TRADE_ID = F.TRADE_ID
           AND E.USER_ID = :USER_ID
           AND F.SERVICE_ID = :SERVICE_ID
           AND F.MODIFY_TAG = '1')