UPDATE TF_F_USER_DISCNT
   SET START_DATE       = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       UPDATE_TIME      = SYSDATE,
       REMARK           = :REMARK,
       RSRV_DATE2       = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE3       = TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND DISCNT_CODE = :DISCNT_CODE
   AND INST_ID = :INST_ID
   AND END_DATE + 0 > SYSDATE