insert into TF_F_FORBIDDEN_POINT
  (INFO_RECV_ID,
   FORB_BADNESS_NUMBER,
   FORB_BADNESS_PROVINCE,
   FORB_OTHERSYS_FLAG,
   FORB_REPORT_NUMBER,
   FORB_OPERATE_TYPE,
   FORB_STAFF_ID)
values
  (:INFO_RECV_ID,
   :BADNESS_INFO,
   :BADNESS_INFO_PROVINCE,
   :FORB_OTHERSYS_FLAG,
   :REPORT_SERIAL_NUMBER,
   '1',
   :RECV_STAFF_ID)