INSERT INTO TI_B_RELATION_UU (SYNC_SEQUENCE,  MODIFY_TAG,  trade_id ,PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
        SELECT TO_NUMBER(:SYNC_SEQUENCE),'2',:TRADE_ID, a.PARTITION_ID,a.USER_ID_A,a.SERIAL_NUMBER_A,a.USER_ID_B,a.SERIAL_NUMBER_B,a.RELATION_TYPE_CODE,a.ROLE_TYPE_CODE,a.ROLE_CODE_A,a.ROLE_CODE_B,a.ORDERNO,a.SHORT_CODE,a.INST_ID,a.START_DATE,a.START_DATE - 1/24/3600,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,'删除无效数据',a.RSRV_NUM1,a.RSRV_NUM2,a.RSRV_NUM3,a.RSRV_NUM4,a.RSRV_NUM5,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_DATE1,a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3
        FROM TF_B_TRADE_RELATION_UU_BAK a 
        WHERE trade_id=:TRADE_ID
        AND accept_month=:ACCEPT_MONTH 
        AND not exists (SELECT 1 from TI_B_RELATION_UU b
                        WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                        AND b.user_id_b = a.user_id_b
                        AND b.user_id_a = a.user_id_a
                        AND b.relation_type_code = a.relation_type_code
                        AND b.start_date = a.start_date )