INSERT INTO TF_B_TRADE_WIDENET
    (TRADE_ID, ACCEPT_MONTH, USER_ID, STAND_ADDRESS, DETAIL_ADDRESS, SIGN_PATH, PORT_TYPE, MODIFY_TAG, INST_ID,
     START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3,
     RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3,
     RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, ACCT_PASSWD,STAND_ADDRESS_CODE,OLD_STAND_ADDRESS,OLD_STAND_ADDRESS_CODE,
     OLD_DETAIL_ADDRESS,PHONE,CONTACT,CONTACT_PHONE,SUGGEST_DATE)
VALUES
    (TO_NUMBER(:TRADE_ID), TO_NUMBER(:ACCEPT_MONTH), TO_NUMBER(:USER_ID), :STAND_ADDRESS, :DETAIL_ADDRESS,
     :SIGN_PATH, :PORT_TYPE, :MODIFY_TAG, TO_NUMBER(:INST_ID), TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
     TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'), TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'), :UPDATE_STAFF_ID,
     :UPDATE_DEPART_ID, :REMARK, TO_NUMBER(:RSRV_NUM1), TO_NUMBER(:RSRV_NUM2), TO_NUMBER(:RSRV_NUM3),
     TO_NUMBER(:RSRV_NUM4), TO_NUMBER(:RSRV_NUM5), :RSRV_STR1, :RSRV_STR2, :RSRV_STR3, :RSRV_STR4, :RSRV_STR5,
     TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS'), TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
     TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS'), :RSRV_TAG1, :RSRV_TAG2, :RSRV_TAG3, :ACCT_PASSWD, 
     TO_NUMBER(:STAND_ADDRESS_CODE), :OLD_STAND_ADDRESS , TO_NUMBER(:OLD_STAND_ADDRESS_CODE), :OLD_DETAIL_ADDRESS, 
     :PHONE,:CONTACT, :CONTACT_PHONE, TO_DATE(:SUGGEST_DATE, 'YYYY-MM-DD HH24:MI:SS'))