--IS_CACHE=Y
SELECT SYS_CODE,
       OPER_TYPE_CODE,
       FEE_TYPE_CODE,
       SPLIT_COLUMN,
       CHECK_COLUMN,
       CHECK_TAG,
       PARA_TYPE,
       BEGIN_DATE,
       END_DATE
  FROM TD_S_ACCT_RULES
 WHERE SYS_CODE = :SYS_CODE
   AND OPER_TYPE_CODE = :OPER_TYPE_CODE
   AND SYSDATE BETWEEN BEGIN_DATE AND END_DATE