SELECT OPR_SEQ,
       PROD_ID,
       PROD_TYPE,
       DISCNT_RATE,
       CARD_BIND,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_DATE1,
       RSRV_TAG1
  FROM TF_O_DISCNT_APPLY_SUB
 WHERE OPR_SEQ = :OPR_SEQ
