SELECT 
  SUM(PRIZE_1) PRIZE_1,
  SUM(PRIZE_2) PRIZE_2,
  SUM(PRIZE_3) PRIZE_3,
  SUM(PRIZE_4) PRIZE_4,
  SUM(PRIZE_5) PRIZE_5,
  SUM(PRIZE_6) PRIZE_6
FROM TM_O_UECLOTTERY WHERE 1=1
AND ACTIVITY_NUMBER=:ACTIVITY_NUMBER
AND (CITY_CODE=:CITY_CODE OR CITY_CODE='HNHN')
AND FIRE_DAY >= TO_DATE(:START_DATE,'YYYYMMDD')
AND FIRE_DAY <= TO_DATE(:END_DATE,'YYYYMMDD')