SELECT B.*, M.SERIAL_NUMBER LINK_PHONE
  FROM TF_B_GRP_BUSAPPLY       B,
       TF_F_CUST_GROUPMEMBER   GM,
       TF_F_CUST_GROUP         G,
       TF_F_CUST_MANAGER_STAFF M
 WHERE G.GROUP_MGR_SN = :GROUP_MGR_SN
   AND G.REMOVE_TAG = :REMOVE_TAG
   AND GM.GROUP_ID = G.GROUP_ID
   AND GM.REMOVE_TAG = :REMOVE_TAG
   AND B.SERIAL_NUMBER = GM.SERIAL_NUMBER
   AND B.OBJ_TYPE_CODE = :OBJ_TYPE_CODE
   AND B.CUST_MANAGER_ID = M.CUST_MANAGER_ID(+)