INSERT INTO TF_B_TRADE_RELATION_UU_BAK(TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A, 
USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A, 
ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE, 
END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK, 
RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5, 
RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5, 
RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID,5,2)),PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,
USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,
ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,
END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,
RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,
RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,
RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_RELATION_UU A
    WHERE A.user_id_a=TO_NUMBER(:USER_ID_A)
      AND A.end_date>SYSDATE
   AND NOT EXISTS 
    (SELECT 1 FROM tf_b_trade_relation_uu_bak C
           WHERE C.USER_ID_A = TO_NUMBER(:USER_ID_A)
             AND C.relation_type_code = A.relation_type_code
             AND C.USER_ID_B = A.USER_ID_B
             AND c.partition_id = A.Partition_Id
             AND c.trade_id = TO_NUMBER(:TRADE_ID)
             AND c.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
             AND c.Inst_Id = a.inst_id)