SELECT SUM(SCORE_ALL) FROM (SELECT SCORE_CHANGED SCORE_ALL from (SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       A.SCORE_CHANGED,
       B.TRADE_TYPE_CODE
  FROM TF_B_TRADE_SCORE A, TF_B_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND A.SERIAL_NUMBER =  :SERIAL_NUMBER
   AND B.ACCEPT_MONTH= TO_NUMBER(TO_CHAR(SYSDATE,'MM')) 
UNION ALL
SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       A.SCORE_CHANGED,
       B.TRADE_TYPE_CODE
  FROM TF_B_TRADE_SCORE A, TF_BH_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND B.ACCEPT_MONTH= TO_NUMBER(TO_CHAR(SYSDATE,'MM'))))