SELECT A.*
  FROM TF_B_TRADE A, TF_B_TRADE_OTHER B
 WHERE A.TRADE_TYPE_CODE IN (600, 4800)
   AND A.CANCEL_TAG = '0'
   AND A.USER_ID = B.USER_ID
   AND A.TRADE_ID = B.TRADE_ID
   AND B.RSRV_VALUE_CODE = 'TOPSETBOX'
   AND A.SERIAL_NUMBER IN ('KD_' || :SERIAL_NUMBER, :SERIAL_NUMBER)
