UPDATE TF_F_USER_RECOMM A      
   SET A.RECOMM_TAG = '1'
 WHERE A.RECOMM_ID =
       (SELECT MAX(RECOMM_ID)
          FROM TF_F_USER_RECOMM B
         WHERE B.USER_ID = TO_NUMBER(:USER_ID)
           AND B.RECOMM_TYPE = '5'
           AND B.RECOMM_TAG = '0'
           AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE)