SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
			:TRADE_ID TRADE_ID, MOD(B.ACCT_ID, 10000), B.ACCT_ID, '-1', '-1', '-1',
			B.DISCNT_CODE, '0', '', B.INST_ID, '', B.START_DATE,
			B.END_DATE, B.UPDATE_TIME, B.UPDATE_STAFF_ID,
			B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2,
			B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1,
			B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5,
			B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1,
			B.RSRV_TAG2, B.RSRV_TAG3, '1'
  FROM TF_F_ACCT_DISCNT B
 WHERE B.ACCT_ID = :ACCT_ID