SELECT B.TERMINAL_ID,  F_RES_GETCODENAME('eparchy_code', A.EPARCHY_CODE, '', '') EPARCHY_NAME, A.EPARCHY_CODE,
F_RES_GETCODENAME('res_kind_code','4','ZZZZ',A.TERMINAL_CATEGORY_CODE) TERMINAL_CATEGORY_NAME,
F_RES_GETCODENAME('card_kind_code', A.TERMINAL_TYPE_CODE, 'ZZZZ', '') TERMINAL_TYPE_DESC,
F_RES_GETCODENAME('terminal_brand', A.BRAND_CODE, '', '') BRAND_NAME,
F_RES_GETCODENAME('terminal_model', A.MODEL_CODE, '', '') MODEL_NAME,
F_RES_GETCODENAME('terminal_color_name',A.COLOR_CODE,'','') COLOR_NAME,
F_RES_GETCODENAME('ter_corp', A.SUPPLY_COOP_ID, '02', '') SUPPLY_COOP_DESC,
F_RES_GETCODENAME('td_m_res_para', '4001', 'TERMINAL_USE_TYPE', A.USE_TYPE) USE_TYPE,
F_RES_GETCODENAME('depart_id',A.STOCK_ID,'','') STOCK_NAME, A.ORDER_ID,
decode(A.AUTHORIZE_FLAG,'0','授权','1','非授权') AUTHORIZE_FLAG,
B.RESULT_CODE RESULT,
F_RES_GETCODENAME('td_m_res_para', '4001', 'RESULTCODE', B.RESULT_CODE) RESULT_DESC,
B.RESULT_COMMENT,
B.UPDATE_TIME,
B.UPDATE_STAFF_ID,
B.UPDATE_DEPART_ID,
B.OPER_TRADE_ID,
B.OPR_DATE,  
B.OPR_CODE, 
B.LOG_ID,   
TO_CHAR(A.TIME_IN, 'YYYY-MM-DD') TIME_IN
FROM TF_R_CEN_TERMINAL_ARCH A, TF_B_TERMINAL_AUTHORIZE_LOG B
WHERE 1 = 1 
   AND A.AUTHORIZE_FLAG=:AUTHORIZE_FLAG  
   AND A.TERMINAL_CATEGORY_CODE = :TERMINAL_CATEGORY_CODE
   AND A.TERMINAL_TYPE_CODE=:TERMINAL_TYPE_CODE
   AND A.brand_code=:BRAND_CODE
   AND A.MODEL_CODE=:MODEL_CODE
   AND B.RESULT_CODE=:RESULT_CODE
   AND A.ASSIGN_TAG=:ASSIGN_TAG
   AND A.TERMINAL_STATE=:TERMINAL_STATE
   AND A.TERMINAL_ID = B.TERMINAL_ID