select TO_CHAR(USER_ID) USER_ID,
       NP_SERVICE_TYPE,
       SERIAL_NUMBER,
       PORT_OUT_NETID,
       PORT_IN_NETID,
       HOME_NETID,
       B_NP_CARD_TYPE,
       A_NP_CARD_TYPE,
       NP_TAG,
       TO_CHAR(APPLY_DATE, 'YYYY-MM-DD HH24:MI:SS') APPLY_DATE,
       TO_CHAR(NP_DESTROY_TIME, 'YYYY-MM-DD HH24:MI:SS') NP_DESTROY_TIME,
       TO_CHAR(PORT_IN_DATE, 'YYYY-MM-DD HH24:MI:SS') PORT_IN_DATE,
       TO_CHAR(PORT_OUT_DATE, 'YYYY-MM-DD HH24:MI:SS') PORT_OUT_DATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TF_FH_USER_NP T
 WHERE T.USER_ID = to_number(:USER_ID)
 ORDER BY T.APPLY_DATE DESC