INSERT INTO TI_B_USER_ACCTDAY (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,ACCT_DAY,CHG_TYPE,CHG_MODE,CHG_DATE,FIRST_DATE,INST_ID,START_DATE,  END_DATE,  UPDATE_TIME,  UPDATE_STAFF_ID  ,  UPDATE_DEPART_ID ,  REMARK,  RSRV_NUM1,  RSRV_NUM2,  RSRV_NUM3,  RSRV_NUM4,  RSRV_NUM5,  RSRV_STR1,  RSRV_STR2,  RSRV_STR3,  RSRV_STR4,  RSRV_STR5,  RSRV_DATE1,  RSRV_DATE2,  RSRV_DATE3,  RSRV_TAG1,  RSRV_TAG2,  RSRV_TAG3 )
        SELECT  :SYNC_SEQUENCE,:MODIFY_TAG,:TRADE_ID, PARTITION_ID,USER_ID,ACCT_DAY,CHG_TYPE,CHG_MODE,CHG_DATE,FIRST_DATE,INST_ID,START_DATE,  END_DATE,  UPDATE_TIME,  UPDATE_STAFF_ID  ,  UPDATE_DEPART_ID ,  REMARK,  RSRV_NUM1,  RSRV_NUM2,  RSRV_NUM3,  RSRV_NUM4,  RSRV_NUM5,  RSRV_STR1,  RSRV_STR2,  RSRV_STR3,  RSRV_STR4,  RSRV_STR5,  RSRV_DATE1,  RSRV_DATE2,  RSRV_DATE3,  RSRV_TAG1,  RSRV_TAG2,  RSRV_TAG3
        FROM TF_F_USER_ACCTDAY A
         WHERE (PARTITION_ID, a.USER_ID) IN (
         select mod(t1.USER_ID,10000), t1.USER_ID 
                      from TF_B_TRADE_USER_ACCTDAY t1 
                      where trade_id = TO_NUMBER(:TRADE_ID) 
                      and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2)))  
         AND NOT EXISTS (
         select 1 from TI_B_USER_ACCTDAY c 
                 where c.sync_sequence=TO_NUMBER(:SYNC_SEQUENCE) 
                 and a.partition_id=c.partition_id 
                 and a.USER_ID = c.USER_ID )