SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_CUSTOMER C, TF_F_USER U
 WHERE U.USER_ID = TO_NUMBER(:USER_ID_B)
 AND U.PARTITION_ID = MOD(:USER_ID_B,10000)
 AND U.CUST_ID = C.CUST_ID
 AND C.PARTITION_ID = MOD(U.CUST_ID,10000)
 AND U.REMOVE_TAG = 0
 AND C.REMOVE_TAG = 0
 AND C.IS_REAL_NAME = '1'