select  TO_CHAR(a.trade_id) trade_id,
            a.accept_month,
            a.user_id,
            a.merch_spec_code,
            a.product_order_id,
            a.product_offer_id,
            a.product_spec_code,
            a.product_discnt_code,
            a.start_date,
            a.end_date,
            a.update_time,
            a.update_staff_id,
            a.update_depart_id,
            a.modify_tag,
            REMARK, 
  			RSRV_NUM1, 
  			RSRV_NUM2, 
  			RSRV_NUM3, 
  			RSRV_NUM4, 
  			RSRV_NUM5, 
  			RSRV_STR1, 
  			RSRV_STR2, 
  			RSRV_STR3, 
  			RSRV_STR4, 
  			RSRV_STR5, 
  			RSRV_DATE1, 
  			RSRV_DATE2, 
  			RSRV_DATE3, 
  			RSRV_TAG1, 
  			RSRV_TAG2, 
  			RSRV_TAG3            
from TF_B_TRADE_GRP_MERCHP_DISCNT a
 WHERE a.trade_id = TO_NUMBER(:TRADE_ID)
   AND a.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))