insert into TL_B_USER_SCORE_GOODS (ACCEPT_MONTH, USER_ID, RULE_ID, RULE_NAME, GOODS_NUM, REMAIN_NUM, GET_NUM, SCORE, QUANCODE, GET_QUANCODE, SERIAL_NUMBER, STATE, START_DATE, END_DATE, GET_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, EXCHANGE_TIME, EXCHANGE_STAFF_ID, EXCHANGE_DEPART_ID, TRADE_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
values (
TO_NUMBER(:ACCEPT_MONTH),
TO_NUMBER(:USER_ID),     
TO_NUMBER(:RULE_ID),     
:RULE_NAME,              
to_number(:GOODS_NUM),   
to_number(:REMAIN_NUM),  
to_number(:GET_NUM),     
to_number(:SCORE),       
:QUANCODE,               
:GET_QUANCODE,           
:SERIAL_NUMBER,          
:STATE,                  
sysdate,      
to_date(to_char(trunc(sysdate)+30,'yyyymmdd')||''||' 23:59:59','yyyy-mm-dd hh24:mi:ss'),        
null,        
null,     
:UPDATE_STAFF_ID,                 
:UPDATE_DEPART_ID,                
sysdate,       
:EXCHANGE_STAFF_ID,  
:EXCHANGE_DEPART_ID, 
:TRADE_ID,           
:REMARK,             
:RSRV_NUM1,          
:RSRV_NUM2,          
:RSRV_NUM3,          
:RSRV_NUM4,          
:RSRV_NUM5,          
:RSRV_STR1,          
:RSRV_STR2,          
:RSRV_STR3,          
:RSRV_STR4,          
:RSRV_STR5,          
:RSRV_DATE1,         
:RSRV_DATE2,         
:RSRV_DATE3,         
:RSRV_TAG1,          
:RSRV_TAG2,          
:RSRV_TAG3           
)

