SELECT PARTITION_ID,
       TO_CHAR(ACCT_ID_A) ACCT_ID_A,
       TO_CHAR(USER_ID_A) USER_ID_A,
       TO_CHAR(ACCT_ID_B) ACCT_ID_B,
       TO_CHAR(USER_ID_B) USER_ID_B,
       TO_CHAR(PAYITEM_CODE) PAYITEM_CODE,
       RELATION_TYPE_CODE,
       ROLE_CODE_A,
       ROLE_CODE_B,
       TO_CHAR(ORDERNO) ORDERNO,
       TO_CHAR(INST_ID) INST_ID,
       LIMIT_TYPE,
       TO_CHAR(LIMIT_VALUE) LIMIT_VALUE,
       START_DATE,
       END_DATE,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       TO_CHAR(RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_F_RELATION_AA
 WHERE PARTITION_ID = MOD(TO_NUMBER(:ACCT_ID_B), 10000)
   AND ACCT_ID_A = :ACCT_ID_A
   AND ACCT_ID_B = :ACCT_ID_B
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   and ACT_TAG = :ACT_TAG