UPDATE TF_F_RELATION_AA
   SET USER_ID_A        = to_number(:USER_ID_A),
       USER_ID_B        = to_number(:USER_ID_B),
       PAYITEM_CODE     = :PAYITEM_CODE,
       ROLE_CODE_A      = :ROLE_CODE_A,
       ROLE_CODE_B      = :ROLE_CODE_B,
       ORDERNO          = :ORDERNO,
       INST_ID          = to_number(:INST_ID),
       LIMIT_TYPE       = :LIMIT_TYPE,
       LIMIT_VALUE      = :LIMIT_VALUE,
       ACT_TAG           = :ACT_TAG,
       END_DATE         = :END_DATE,
       UPDATE_TIME      = to_date(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       REMARK           = :REMARK,
       RSRV_NUM1        = :RSRV_NUM1,
       RSRV_NUM2        = to_number(:RSRV_NUM2),
       RSRV_NUM3        = to_number(:RSRV_NUM3),
       RSRV_STR1        = :RSRV_STR1,
       RSRV_STR2        = :RSRV_STR2,
       RSRV_STR3        = :RSRV_STR3,
       RSRV_STR4        = :RSRV_STR4,
       RSRV_STR5        = :RSRV_STR5,
       RSRV_DATE1       = to_date(:RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss'),
       RSRV_DATE2       = to_date(:RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss'),
       RSRV_DATE3       = to_date(:RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss'),
       RSRV_TAG1        = :RSRV_TAG1,
       RSRV_TAG2        = :RSRV_TAG2,
       RSRV_TAG3        = :RSRV_TAG3
 WHERE PARTITION_ID = MOD(to_number(:ACCT_ID_B), 10000)
   and ACCT_ID_A = to_number(:ACCT_ID_A)
   and ACCT_ID_B = to_number(:ACCT_ID_B)
   and RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   and START_DATE = :START_DATE