SELECT T.BPM_TEMPLET_ID,
       T.TEMPLET_DESC,
       T.TEMPLET_NAME,
       T.TEMPLET_TYPE,
       T.REMARK,
       T.VALID_TAG,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_FLOW_TEMPLET T
 WHERE T.TEMPLET_TYPE = :TEMPLET_TYPE
   AND T.VALID_TAG = :VALID_TAG