--IS_CACHE=Y
SELECT DISTINCT(biz.BIZ_CODE),biz.BIZ_NAME FROM TD_S_BIZLIST biz,TD_S_ECHANNAL_STAFF staff,TD_S_CHANNAL_BIZLIST chnl WHERE 1 = 1
 AND staff.CHAN_ID = chnl.CHAN_ID
 AND biz.BIZ_CODE = CHNL.BIZ_CODE
 AND staff.ID_VALUE = :STAFF_ID