UPDATE TL_B_BLACKUSER
   SET EXEC_TIME = SYSDATE, EFFECT_TAG = :EFFECT_TAG, PROCESS_TAG = :PROCESS_TAG, REMARK = :REMARK
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND BEGIN_DATE < END_DATE
   AND END_DATE > SYSDATE