SELECT A.INFO_ID,
       A.INFO_SIGN,
       A.INFO_TOPIC,
       A.INFO_CHILD_TYPE,
       A.INFO_TYPE,
       A.INFO_STATUS,
       A.INFO_LEVEL,
       A.INFO_URL,
       A.INFO_CONTENT,
       A.INFO_AUTH,
       TO_CHAR(A.INFO_SEND_TIME, 'YYYY-MM-DD HH24:MI:SS') INFO_SEND_TIME,
       TO_CHAR(A.END_TIME, 'YYYY-MM-DD HH24:MI:SS') END_TIME,
       B.INST_ID,
       B.RECE_OBJ,
       B.RECE_OBJ_TYPE,
       B.INST_STATUS,
       TO_CHAR(B.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(B.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_INFO A, TF_F_INFO_INSTANCE B
 WHERE A.INFO_ID = B.INFO_ID
 AND  A.INFO_SIGN =:INFO_SIGN
 AND A.INFO_CHILD_TYPE = :INFO_CHILD_TYPE
 ORDER BY B.INST_ID DESC