--IS_CACHE=Y
SELECT A.PRODUCT_ID,
       A.ROLE_CODE,
       A.ROLE_NAME,
       A.IS_GROUP_ROLE,
       A.IS_MAIN_ROLE,
       A.MIN_NUMBER,
       A.MAX_NUMBER,
       B.NET_TYPE_CODE
  FROM TD_B_PRODUCT_ROLE A, TD_B_ROLE B
 WHERE A.ROLE_CODE = B.ROLE_CODE
   AND A.PRODUCT_ID = :PRODUCT_ID
   AND A.STATE = '1'
   AND B.STATE = '1'
 ORDER BY A.SEQ_NO