SELECT to_date(substr(:START_DATE,0,10) || ' 23:59:59','yyyy-MM-dd hh24:mi:ss')+T.RSRV_NUM1 END_DATE FROM TF_B_TRADE_DISCNT T
WHERE T.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND T.PRODUCT_ID !='-1'