UPDATE TF_O_CUSTOMERCLUB
SET  END_DATE = SYSDATE,rsrv_str4=:RETREAT_TRADE_ID,update_time=sysdate
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER 
AND  CLUB_TYPE = :CLUB_TYPE  
AND  ACCEPT_TAG = '0' 
AND  END_DATE > SYSDATE