--IS_CACHE=Y
SELECT para_value2,
 DECODE(para_value2,
 '1',TO_CHAR(TRUNC(SYSDATE-1),'YYYYMMDD'),
 '2',TO_CHAR(TRUNC(SYSDATE),'YYYYMM')||'01',
 '3',DECODE(CEIL(TO_NUMBER(EXTRACT(MONTH FROM SYSDATE))/3),
   '1',EXTRACT(YEAR FROM SYSDATE)||'0101',
   '2',EXTRACT(YEAR FROM SYSDATE)||'0401',
   '3',EXTRACT(YEAR FROM SYSDATE)||'0701',
   '4',EXTRACT(YEAR FROM SYSDATE)||'1001'),
 TO_CHAR(TRUNC(SYSDATE-1),'YYYYMMDD') 
 )  para_value5, 
 DECODE(para_value2,
 '1',TO_CHAR(TRUNC(SYSDATE-1),'YYYYMMDD'),
 '2',TO_CHAR(TRUNC(LAST_DAY(SYSDATE)),'YYYYMMDD'),
 '3',DECODE(CEIL(TO_NUMBER(EXTRACT(MONTH FROM SYSDATE))/3), 
   '1',EXTRACT(YEAR FROM SYSDATE)||'0331',
   '2',EXTRACT(YEAR FROM SYSDATE)||'0630',
   '3',EXTRACT(YEAR FROM SYSDATE)||'0930',
   '4',EXTRACT(YEAR FROM SYSDATE)||'1230'), 
 TO_CHAR(TRUNC(SYSDATE-1),'YYYYMMDD')
 ) para_value6 
  FROM td_m_res_commpara
 WHERE para_attr=1036
  AND  para_code1='DISCOUNTDAY' 
  AND  para_code2=:PARA_CODE2   
  AND  eparchy_code=:EPARCHY_CODE