--IS_CACHE=Y
SELECT to_char(ID) ID, ID_TYPE, ATTR_OBJ, ATTR_CODE, ATTR_NAME, ATTR_VALUE, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, EPARCHY_CODE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5
  FROM td_b_attr_biz t
 WHERE id=TO_NUMBER(:ID)
 AND id_type=:ID_TYPE
 AND attr_obj=:ATTR_OBJ
 AND ATTR_VALUE=:ATTR_VALUE
 AND SYSDATE BETWEEN t.START_DATE AND t.END_DATE