UPDATE TF_B_NPCHECK A SET A.STATE = :STATE,A.RSRV_STR3 = TO_CHAR(SYSDATE,'yyyy-MM-dd HH24:mi:ss')
WHERE A.SERIAL_NUMBER= :SERIAL_NUMBER
AND A.ACCEPT_DATE =
(SELECT MAX(t.accept_date)
  FROM TF_B_NPCHECK T
 WHERE 1 = 1
   AND T.SERIAL_NUMBER = :SERIAL_NUMBER)