UPDATE TF_F_USER_DISCNT
   SET END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND SPEC_TAG = :SPEC_TAG
   AND DISCNT_CODE = TO_NUMBER(:DISCNT_CODE)
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND END_DATE > SYSDATE