SELECT B.SERIAL_NUMBER, A.START_DATE, A.STAFF_ID, A.DEPART_ID,A.RSRV_STR1
FROM TF_F_USER_OTHER A, TF_F_USER B
WHERE A.USER_ID = B.USER_ID AND B.REMOVE_TAG = '0' AND B.SERIAL_NUMBER = :PARA_CODE1 AND
			B.PARTITION_ID = A.PARTITION_ID AND START_DATE >= TO_DATE(:PARA_CODE2, 'YYYY-MM-DD') AND
			START_DATE <= TO_DATE(:PARA_CODE3, 'YYYY-MM-DD hh24:mi:ss') AND A.RSRV_VALUE_CODE = :RSRV_VALUE_CODE