SELECT TRADE_ID,
       SERIAL_NUMBER,
       CHANNEL_TYPE,
       ACCEPT_DATE,
       STATUS,
       REMARK,
       FILE_NAME
  FROM TI_B_ELECTCARD_BAT_RECH T
     WHERE SERIAL_NUMBER = :SERIAL_NUMBER
     AND ACCEPT_DATE >= TRUNC(to_date(:START_DATE, 'yyyy-MM-dd'))
     AND ACCEPT_DATE < TRUNC(to_date(:END_DATE, 'yyyy-MM-dd')+1)
     AND SERIAL_NUMBER = :SERIAL_NUMBER