SELECT CPPRICE.MATERIAL_CODE, F_RES_GETCODENAME('terminal_vendor',PRODUCT.VENDOR_CODE,'','')VENDOR,PRODUCT.BRAND_DESC,PRODUCT.MODEL_DESC,CPPRICE.DEAL_PRICE,CPPRICE.DEAL_PRICE_FLORATE,CPPRICE.SALE_PRICE,CPPRICE.SALE_PRICE_FLORATE,CPPRICE.START_DATE,CPPRICE.END_DATE,
CPPRICE.DEAL_PRICE D_PRICE,CPPRICE.DEAL_PRICE_FLORATE || '%' DEAL_FLOAT ,CPPRICE.SALE_PRICE S_PRICE,CPPRICE.SALE_PRICE_FLORATE || '%' SALE_FLOAT,CPPRICE.START_DATE,CPPRICE.END_DATE,
(SELECT PRICE.SALE_PRICE  FROM TD_R_TERMINAL_PRICE PRICE WHERE PRICE.MATERIAL_CODE=CPPRICE.MATERIAL_CODE)SALES_PRICE,
(SELECT PRICE.DEAL_PRICE  FROM TD_R_TERMINAL_PRICE PRICE WHERE PRICE.MATERIAL_CODE=CPPRICE.MATERIAL_CODE)DEALS_PRICE,
DECODE((SELECT PRICE.VALID_TAG  FROM TD_R_TERMINAL_PRICE PRICE WHERE PRICE.MATERIAL_CODE=CPPRICE.MATERIAL_CODE),'0','有效','1','无效')VALID_TAG_DESC,
DECODE((SELECT  AUDIT_STATUS from TD_R_TERMINAL_PRICE),'0','未审核','1','审核通过','2','退回申请','','')AUDIT_STATUS_DESC
 FROM TF_R_PRODUCT_GRP PRODUCT  ,TF_R_CPPRICE_GRP  CPPRICE
WHERE PRODUCT.MATERIAL_CODE=CPPRICE.MATERIAL_CODE
 AND (:BRAND_CODE IS NULL OR BRAND_CODE=:BRAND_CODE) 
 AND (:MODEL_CODE IS NULL OR MODEL_CODE=:MODEL_CODE)
 AND (:MATERIAL_CODE IS NULL OR product.MATERIAL_CODE=:MATERIAL_CODE) 
 AND (:VENDOR_CODE IS NULL OR  VENDOR_CODE=:VENDOR_CODE)
 AND (:VALID_TAG IS NULL OR  product.VALID_TAG=:VALID_TAG)
 AND (:TERMINAL_TYPE_CODE IS NULL OR  TERMINAL_TYPE_CODE=:TERMINAL_TYPE_CODE)
   AND (:TERMINAL_CATEGORY_CODE IS NULL OR PRODUCT.TERMINAL_CATEGORY_CODE=:TERMINAL_CATEGORY_CODE)