SELECT 
       A.SEQ_NO,
       A.TRADE_TYPE_CODE,
       A.SUB_TRADE_TYPE,
       A.TRADE_TYPE,
       A.SERVICE_ID,
       A.SP_CODE SP_ID,
       A.BIZ_CODE,
       A.BIZ_TYPE_CODE,
       'Z' SERVICE_TYPE,
 (SELECT count(*)
          FROM TF_F_USER_PLATSVC G, TF_F_USER H
         WHERE G.USER_ID = :USER_ID
           AND G.PARTITION_ID = MOD(:USER_ID, '10000')
           AND G.USER_ID = H.USER_ID
           AND SYSDATE BETWEEN G.START_DATE AND G.END_DATE
           AND (G.BIZ_STATE_CODE = 'A' OR G.BIZ_STATE_CODE = 'N')
           AND H.REMOVE_TAG = '0'
           AND G.SERVICE_ID = A.SERVICE_ID) orderflg			 
  FROM TD_S_WELCOME       A
 WHERE A.TRADE_TYPE_CODE = '02'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE