SELECT USER_ID, MONTH, ACTIVITY_NUMBER, LOTTERY_COUNT, TO_CHAR(CHECK_DATE,'yyyy-mm-dd hh24:mi:ss') CHECK_DATE
FROM TF_F_USER_UECLOTTERY WHERE 1=1
AND PARTITION_ID=:PARTITION_ID
AND USER_ID=:USER_ID
AND MONTH=:MONTH
AND ACTIVITY_NUMBER=:ACTIVITY_NUMBER