SELECT 
       A.SEQ_NO,       
       A.TRADE_TYPE_CODE,
       A.SUB_TRADE_TYPE,
       A.TRADE_TYPE,
       A.ELEMENT_ID SERVICE_ID,
       '1001' SP_ID,
       '中国移动' SP_NAME,
       '' BIZ_CODE,
       '' SP_SHORT_NAME,
       '' BIZ_TYPE,
       '' BIZ_TYPE_CODE,
       '' ORG_DOMAIN,
       '' BIZ_STATE_CODE,
       DECODE(A.RSRV_STR1,'','2',A.RSRV_STR1) BILLFLG,
       A.RSRV_STR2  PRICE,
       '0' SERV_TYPE,
       A.ELEMENT_TYPE_CODE  SERVICE_TYPE,
			  (SELECT count(*)
          FROM TF_F_USER_DISCNT C
         WHERE C.USER_ID = :USER_ID
           AND C.PARTITION_ID = MOD(:USER_ID, '10000')
           AND C.END_DATE > SYSDATE
           AND C.DISCNT_CODE = A.ELEMENT_ID) orderflg
  FROM TD_S_WELCOME A
 WHERE A.TRADE_TYPE_CODE = '01'
   AND A.ELEMENT_TYPE_CODE = 'D'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
	 AND NOT EXISTS (SELECT 1 FROM TF_F_USER_DISCNT C,TD_S_WELCOME_MUTEX D 
	     WHERE C.USER_ID = :USER_ID
			 AND C.PARTITION_ID = MOD(:USER_ID, '10000')
			 AND D.ELEMENT_ID = A.ELEMENT_ID 
			 AND D.ELEMENT_TYPE_CODE=A.ELEMENT_TYPE_CODE 
			 AND D.MUTEX_ID = C.DISCNT_CODE
	     AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
			 AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE)