SELECT
  CASE WHEN (T.DEAL_STATE=1 OR T.DEAL_STATE=2 OR T.DEAL_STATE=0) THEN 'TRUE'ELSE 'FALSE' END SHOWDETAIL,
  T.SERIAL_NUMBER,T.SESSION_ID,T.ORDER_ID,T.DEAL_STATE,T.SEND_CONTENT,T.RSP_CONTENT,
  TO_CHAR(ACCEPT_TIME,'YYYY-MM-DD HH24:MI:SS') ACCEPT_TIME,
  TO_CHAR(RSP_TIME,'YYYY-MM-DD HH24:MI:SS') RSP_TIME
FROM TF_B_UNION_SESSIONLOG T WHERE 1=1
AND (T.SERIAL_NUMBER=:SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
AND (T.SESSION_ID=:SESSION_ID OR :SESSION_ID IS NULL)
AND (T.ORDER_ID=:ORDER_ID OR :ORDER_ID IS NULL)
AND (T.DEAL_STATE=:DEAL_STATE OR :DEAL_STATE IS NULL)
AND (T.ACCEPT_TIME > TO_DATE(:CANCEL_BEGIN_TIME,'YYYY-MM-DD HH24:MI:SS') OR :CANCEL_BEGIN_TIME IS NULL)
AND (T.ACCEPT_TIME < TO_DATE(:CANCEL_END_TIME,'YYYY-MM-DD HH24:MI:SS') OR :CANCEL_END_TIME IS NULL)
ORDER BY T.ACCEPT_TIME DESC