--IS_CACHE=Y
SELECT OPER_TYPE_CODE,
       OPER_TYPE_NAME,
       OBJECTID,
       IN_MODE_CODE,
       DEAL_TYPE,
       ACT_TAG,
       START_DATE,
       END_DATE,
       UPDATE_TIME,
       UPDATE_DEPART_ID,
       UPDATE_STAFF_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TD_B_STAFFOPERTYPE
 WHERE 1 = 1
   AND OBJECTID = :OBJECTID
   AND DEAL_TYPE = :DEAL_TYPE
   AND ACT_TAG = '1'
   AND SYSDATE BETWEEN START_DATE AND END_DATE