SELECT T.EMPTY_CARD_ID,T.ICCID,T.IMSI,T.STATE,T.OPERA_STAFF,T.OPERA_DEPART,T.OPERA_CITY_CODE,T2.IMAGES
 ,to_char(to_date(t.create_time,'yyyymmddhh24miss'),'yyyy-mm-dd hh24:mi:ss')CREATE_TIME, T.RSRV_STR1  FROM TF_B_ORDER_DETAIL T,TF_B_ORDER_ITEM T2
 WHERE T.ORDER_ID = T2.ORDER_ID
   AND T2.MOBILE = :SERIAL_NUMBER