SELECT BFAS_ID,                    
       SYS_CODE,                   
       LOG_ID,                     
       SUB_LOG_ID,                 
       PARTITION_ID,               
       EPARCHY_CODE,               
       CITY_CODE,                   
       PROFIT_CEN_ID,              
       DEPART_ID,                  
       TO_NUMBER(AGENT_CODE) AS AGENT_CODE,      
       OPER_STAFF_ID,              
       OPER_TYPE_CODE,             
       SALE_TYPE_CODE,             
       PAY_MONEY_CODE,             
       CAMPN_ID,                   
       TO_NUMBER(FEE_TYPE_CODE) AS FEE_TYPE_CODE,   
       TO_NUMBER(FEE_ITEM_TYPE_CODE) AS FEE_ITEM_TYPE_CODE,
       PAY_MODE_CODE,              
       TO_CHAR(ACCT_ID) AS ACCT_ID,           
       COLL_AGEN_CODE,             
       LOGOUT_TAG,                 
       IN_MODE_CODE,               
       NET_TYPE_CODE,              
       BRAND_CODE,                 
       PRODUCT_ID,                 
       USER_TYPE_CODE,             
       CHECK_NUMBER,               
       RES_TYPE_CODE,              
       RES_KIND_CODE,              
       CAPACITY_TYPE_CODE,         
       DEVICE_TYPE_CODE,           
       DEVICE_MODEL_CODE,          
       DEVICE_COLOR_CODE,          
       ORDER_ID,                   
       TO_CHAR(DEVICE_PRODUCT) AS DEVICE_PRODUCT,    
       SUPPLY_TYPE,                
       PROCUREMENT_TYPE,           
       AGENCY_ID,                  
       INCOME_CODE,                
       TO_CHAR(RECE_FEE) AS RECE_FEE,          
       TO_CHAR(FEE) AS FEE,               
       TO_CHAR(PRESENT_FEE) AS PRESENT_FEE,       
       TO_CHAR(FORM_FEE) AS FORM_FEE,          
       TO_CHAR(SCORE) AS SCORE,             
       TO_CHAR(ACC_DATE,'yyyy-mm-dd hh24:mi:ss') AS ACC_DATE,          
       TO_CHAR(OPER_DATE,'yyyy-mm-dd hh24:mi:ss') AS OPER_DATE,         
       CANCEL_SUB_LOG_ID,          
       TO_CHAR(CANCEL_DATE,'yyyy-mm-dd hh24:mi:ss') AS CANCEL_DATE,       
       CANCEL_TAG,                 
       TO_CHAR(DEPOSIT_BEGIN_DATE,'yyyy-mm-dd hh24:mi:ss') AS DEPOSIT_BEGIN_DATE,
       TO_CHAR(DEPOSIT_END_DATE,'yyyy-mm-dd hh24:mi:ss') AS DEPOSIT_END_DATE,  
       PROC_TAG,                   
       TO_NUMBER(RSRV_NUM1) AS RSRV_NUM1      
  FROM TF_B_TRADE_BFAS_IN          
 WHERE LOG_ID = :LOG_ID
 AND PARTITION_ID = TO_NUMBER(SUBSTR(:LOG_ID, 7, 2))           
 AND CANCEL_TAG = :CANCEL_TAG