--IS_CACHE=Y
SELECT 
	A.CONTENT_CODE,
	A.CHAN_ID,
	A.CONTENT_NAME,
	A.CONTENT_CLASS,
	A.CONTENT_KIND,
	A.CONTENT_TYPE,
	A.STORAGE_CODE,
	A.CONTENT,
	A.CONTENT_URL,
	A.START_DATE,
	A.END_DATE,
	B.NODE_CODE,
	B.NODE_NAME 
 FROM 
 	TD_S_CONTENT A, 
 	TD_S_CONT_CATEGORY_RELATION B 
 WHERE A.CONTENT_CODE = B.CONTENT_CODE(+)
 AND	  B.NODE_CODE = :NODE_CODE
 AND   A.CONTENT_CODE = :CONTENT_CODE