UPDATE ti_b_ec
   SET modify_tag = :DEAL_STATE
 WHERE trade_id = :DEAL_ID
   AND (:DEAL_TAG IS NULL OR :DEAL_TAG = :DEAL_TAG)
   AND (:DEAL_EPARCHY_CODE IS NULL OR :DEAL_EPARCHY_CODE = :DEAL_EPARCHY_CODE)