--IS_CACHE=Y
select ADJUST_REASON_ID RSRV_NUM1,0 RSRV_NUM2,0 RSRV_NUM3, '' PARA_CODE1,'' PARA_CODE2,'' PARA_CODE3,'' PARA_CODE4,'' PARA_CODE5,'' PARA_CODE6,
'' PARA_CODE7,'' PARA_CODE8,ADJUST_REASON PARA_CODE9,'Adjustreason1' CALLING_SUBTYPEE from td_a_adjustreason