SELECT /*+INDEX(A,IDX_TF_BH_TRADE_USERID)*/ COUNT(1)-1 recordcount
  FROM TF_BH_TRADE A
 WHERE  USER_ID = :USER_ID
    AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE
    AND ACCEPT_MONTH = TO_CHAR(SYSDATE,'MM')