SELECT COUNT(1) recordcount
  FROM TF_F_USER A
 WHERE A.USER_TYPE_CODE != 'X'
   AND A.USER_ID = :USER_ID
   AND EXISTS (SELECT 1
          FROM TF_B_TRADE B, TF_B_TRADE_DETAIL C
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.TRADE_ID = C.TRADE_ID
           AND B.USER_ID = A.USER_ID
           AND C.USER_TYPE_CODE = 'X')