SELECT COUNT(*) recordcount
  FROM TF_B_TRADE
 WHERE TRADE_TYPE_CODE = 110
   AND TRADE_ID != TO_NUMBER(:TRADE_ID)
   AND  SUBSTR(PROCESS_TAG_SET, 5, 1) = '1'
   and  SUBSTR(:PROCESS_TAG_SET, 5, 1) = '1'
   AND  USER_ID = TO_NUMBER(:USER_ID)
   and  rownum < 2