SELECT COUNT(1) recordcount
	FROM TF_CHL_CREDIT_TRIGGER T
   WHERE T.DEAL_STATE = '2'
	 AND t.trigger_recv_type = '-1'
	 AND T.CHNL_ID = :TRADE_DEPART_ID
	 AND (T.CREDIT_CONFIG_TRADE = 'ZZZZ'
		OR T.CREDIT_CONFIG_TRADE = :TRADE_TYPE_CODE
		OR T.CREDIT_CONFIG_TRADE LIKE '%,' || :TRADE_TYPE_CODE 
		OR T.CREDIT_CONFIG_TRADE LIKE '%' || :TRADE_TYPE_CODE || ',%'
		)
	 AND EXISTS (
		  SELECT 1
			FROM TF_CHL_CHANNEL A
		   WHERE 1 = 1
			 AND A.CHNL_ID = :TRADE_DEPART_ID
			 AND A.CHNL_KIND_FRAME LIKE '000011022%'
	 )
	 AND EXISTS (SELECT 1
					FROM TF_CHL_TRADE_CREDIT C
					WHERE 1 = 1
					 AND C.CHNL_ID = :TRADE_DEPART_ID
					 AND C.STATE = 0
					 AND C.CREDIT_TAG = 0
					 AND (C.CREDIT_START_TIME IS NULL OR C.CREDIT_START_TIME >= SYSDATE)
					 AND (C.CREDIT_END_TIME IS NULL OR C.CREDIT_END_TIME <= SYSDATE)
					)