SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_USER_RES T
 WHERE T.RES_TYPE_CODE = :RES_TYPE_CODE
   AND T.RSRV_TAG1 = :RSRV_TAG1
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
   AND T.USER_ID IN (SELECT B.USER_ID
                       FROM TF_F_USER B
                      WHERE B.REMOVE_TAG = '0'
                        AND B.SERIAL_NUMBER = :SERIAL_NUMBER)