select count(1) recordcount  from TF_F_USER T,TF_F_CUSTOMER T1
where T.CUST_ID=T1.CUST_ID 
AND T.USER_STATE_CODESET='5'
AND T.REMOVE_TAG='0'
AND (T1.IS_REAL_NAME='0' OR T1.IS_REAL_NAME IS NULL) 
AND T.PARTITION_ID=MOD(:USER_ID,10000)
AND T.USER_ID=:USER_ID