SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_USER_RES T
 WHERE T.USER_ID = :USER_ID
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.RES_TYPE_CODE = :RES_TYPE_CODE
   AND T.RSRV_TAG1 = :RSRV_TAG1
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE