SELECT COUNT(1) recordcount FROM dual
       WHERE :TRADE_DEPART_ID 
       IN (SELECT PARAM_CODE FROM TD_S_COMMPARA T 
        WHERE SUBSYS_CODE='CSM'
        AND PARAM_ATTR='7711'
        AND PARA_CODE1='1'
        AND SYSDATE BETWEEN START_DATE AND END_DATE)