SELECT COUNT(1) recordcount
  FROM TF_F_USER_BLACKWHITE T
 WHERE T.SERIAL_NUMBER = :SERIAL_NUMBER
   AND T.SERVICE_ID = :SERVICE_ID
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
   AND ROWNUM < 2