SELECT COUNT(1) recordcount
  FROM dual
WHERE NOT EXISTS --/ 销户时res必须有且只有一个s
(SELECT 1 FROM TF_F_user_res r
 WHERE r.USER_ID = TO_NUMBER(:USER_ID_B)
   AND r.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B),10000)
   AND r.END_DATE > SYSDATE
   AND r.RES_TYPE_CODE='S'
   AND r.USER_ID_A=:USER_ID
   HAVING COUNT(*) = 1
)
OR EXISTS --/ 销户时res s有-1
(SELECT 1 FROM TF_F_user_res r
 WHERE r.USER_ID = TO_NUMBER(:USER_ID_B)
   AND r.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B),10000)
   AND r.END_DATE > SYSDATE
   AND r.RES_TYPE_CODE='S'
   AND r.USER_ID_A=-1
)
OR NOT EXISTS --/ 销户时svc有且只有一个860
(SELECT 1 FROM TF_F_user_svc s
 WHERE s.USER_ID = TO_NUMBER(:USER_ID_B)
   AND s.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B),10000)
   AND s.END_DATE > SYSDATE
   AND s.SERVICE_ID=860
   AND s.USER_ID_A=:USER_ID
   HAVING COUNT(*) = 1
)
OR EXISTS --/ 销户时svc 860有-1
(SELECT 1 FROM TF_F_user_svc s
 WHERE s.USER_ID = TO_NUMBER(:USER_ID_B)
   AND s.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B),10000)
   AND s.END_DATE > SYSDATE
   AND s.SERVICE_ID=860
   AND (s.USER_ID_A=-1 OR s.PRODUCT_ID=-1 OR s.PACKAGE_ID=-1)
)
AND NOT EXISTS
(SELECT 1 FROM TF_F_RELATION_UU u, TF_F_USER_RES r, TF_F_USER_VPN_MEB m
  WHERE u.USER_ID_A=:USER_ID
    AND u.USER_ID_B=:USER_ID_B
    AND u.PARTITION_ID = MOD(:USER_ID_B, 10000)
    AND u.RELATION_TYPE_CODE='20'
    AND u.SHORT_CODE IS NOT NULL --/ 短号
    AND u.END_DATE > SYSDATE --/ 有效
    AND r.USER_ID = :USER_ID_B
    AND r.USER_ID_A = :USER_ID
    AND r.PARTITION_ID = MOD(:USER_ID_B, 10000)
    AND r.RES_TYPE_CODE='S'
    AND r.RES_CODE = u.SHORT_CODE --/ 短号
    AND r.END_DATE > SYSDATE --/ 有效
    AND m.USER_ID = :USER_ID_B
    AND m.USER_ID_A = :USER_ID
    AND m.PARTITION_ID=MOD(:USER_ID_B, 10000)
    AND m.SHORT_CODE=u.SHORT_CODE --/ 短号
    AND m.REMOVE_TAG='0'  --/ 有效
    AND r.USER_ID=u.USER_ID_B
    AND r.USER_ID_A=u.USER_ID_A
    AND r.PARTITION_ID=u.PARTITION_ID
    AND m.USER_ID=u.USER_ID_B
    AND m.USER_ID_A=u.USER_ID_A
    AND m.PARTITION_ID=u.PARTITION_ID
    AND m.SHORT_CODE=r.RES_CODE
)