SELECT COUNT(1) recordcount
  FROM dual
WHERE EXISTS
(SELECT 1 FROM TF_F_user_res r,TF_F_RELATION_UU u
 WHERE r.USER_ID = TO_NUMBER(:USER_ID)
   AND r.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND u.USER_ID_B = TO_NUMBER(:USER_ID)
   AND u.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND u.USER_ID_A = r.USER_ID_A
   AND u.USER_ID_B = r.USER_ID
   AND u.RELATION_TYPE_CODE ='20'
   AND r.END_DATE > SYSDATE
   AND r.RES_TYPE_CODE='S'
   AND rownum < 2
)
OR EXISTS
(SELECT 1 FROM TF_F_user_svc s
 WHERE s.USER_ID = TO_NUMBER(:USER_ID)
   AND s.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND s.END_DATE > SYSDATE
   AND s.SERVICE_ID=860
   AND rownum < 2
)