SELECT COUNT(1) recordcount
FROM tf_b_trade_purchase
WHERE trade_id = TO_NUMBER(:TRADE_ID)
AND (purchase_attr=:PURCHASE_ATTR OR :PURCHASE_ATTR IS NULL)
AND (purchase_desc=:PURCHASE_DESC OR :PURCHASE_DESC IS NULL)
AND (purchase_mode=:PURCHASE_MODE OR :PURCHASE_MODE IS NULL)
AND (purchase_info=:PURCHASE_INFO OR :PURCHASE_INFO IS NULL)