SELECT A.PARTITION_ID,
       A.USER_ID,
       A.USER_ID_A,
       A.DISCNT_CODE,
       A.SPEC_TAG,
       A.RELATION_TYPE_CODE,
       A.INST_ID,
       A.CAMPN_ID,
       TO_CHAR(A.START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE,
       A.UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_DATE1,
       A.RSRV_DATE2,
       A.RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3,
       DECODE(TO_CHAR(A.END_DATE, 'yyyy-mm'),
              TO_CHAR(SYSDATE, 'yyyy-mm'),
              0,
              1) FLAG
  FROM TF_F_USER_DISCNT A, TD_S_COMMPARA B
 WHERE A.DISCNT_CODE = TO_NUMBER(B.PARA_CODE1)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 532
   AND B.PARAM_CODE = TO_CHAR(:PARAM_CODE)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
