SELECT A.*, 
DECODE(TO_CHAR(A.END_DATE, 'yyyy-mm'), TO_CHAR(SYSDATE, 'yyyy-mm'), 0, 1) FLAG
  FROM TF_F_USER_SALE_ACTIVE A, TD_S_COMMPARA B
 WHERE A.PRODUCT_ID = TO_NUMBER(B.PARA_CODE1)
   AND A.PACKAGE_ID = TO_NUMBER(NVL(B.PARA_CODE2, A.PACKAGE_ID))
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 173
   AND B.PARAM_CODE = TO_CHAR(:PARAM_CODE)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE