 select max(TO_CHAR(A.END_DATE,'YYYY-MM-DD HH24:MI:SS'))   MAX_END_DATE 
 FROM TF_F_USER_DISCNT A, TD_S_COMMPARA B
 WHERE A.DISCNT_CODE = TO_NUMBER(B.PARA_CODE1)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 532
   AND B.PARAM_CODE = TO_CHAR(:PARAM_CODE)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE