select TRADE_SMS_ID, SMS_KIND_CODE, SERIAL_NUMBER, SMS_CONTENT, ACCEPT_DATE, TRADE_ID, TRADE_TYPE_CODE, IN_MODE_CODE, SMS_STATE, DEAL_DATE, REVERT_SMS_CONTENT, REVERT_DATE, REVERT_SMS_STATE, SOURCE_NUMBER, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, MONTHID
from ti_o_trade_sms 
where SERIAL_NUMBER = :SERIAL_NUMBER
AND ACCEPT_DATE >= TRUNC(SYSDATE - :DAYS)