SELECT count(1) recordcount
  FROM TF_F_RELATION_UU UU
 WHERE UU.RELATION_TYPE_CODE = '26'
   AND UU.USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND UU.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND END_DATE + 0 > SYSDATE
   AND ROWNUM < 2