UPDATE TF_F_RELATION_MM T
   SET T.SERIAL_NUMBER_B = :SERIAL_NUMBER_B, T.UPDATE_TIME = SYSDATE
 WHERE T.SERIAL_NUMBER_A = :SERIAL_NUMBER_A
   AND T.CODE_STATE_CODE = '0'
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE