INSERT INTO TS_S_TFEE_DAY_STAFF
      (CLCT_DAY,STAFF_ID,DEPART_ID,BRAND_CODE,TRADE_TYPE_CODE,
       FEE_MODE,FEE_TYPE_CODE,DEVICE_TYPE_CODE,RES_TYPE_CODE,
       SALE_NUM,SALE_MONEY,AGENT_FEE,FEE,CANCEL_TAG)
SELECT CLCT_DAY,STAFF_ID,DEPART_ID,BRAND_CODE,TRADE_TYPE_CODE,
       FEE_MODE,FEE_TYPE_CODE,DEVICE_TYPE_CODE,RES_TYPE_CODE,
       SALE_NUM,SALE_MONEY,AGENT_FEE,FEE,CANCEL_TAG
  FROM TS_S_TFEE_DAY_STAFF A
 WHERE ROWNUM < 1  --目今没有信誉保证金了，程序作废
   AND A.CLCT_DAY = :CLCT_DAY
   AND A.STAFF_ID >= :START_STAFF_ID
   AND A.STAFF_ID <= :END_STAFF_ID