UPDATE TS_A_AUDITRESULT
   SET AUDIT_TAG = :AUDIT_TAG
 WHERE ACCEPT_DATE = trunc(sysdate)-1
   AND TRADE_DEPART_ID = :TRADE_DEPART_ID
   AND TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE