SELECT T.*
  FROM TD_B_CTRM_RELATION T
 WHERE T.ELEMENT_ID = :ELEMENT_ID
   AND T.ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
   AND (T.EPARCHY_CODE = :EPARCHY_CODE OR T.EPARCHY_CODE = 'ZZZZ')
   AND T.END_DATE > SYSDATE
