INSERT INTO TF_B_TRADE_DISCNT
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   DISCNT_CODE,
   MODIFY_TAG,
   START_DATE,
   END_DATE)
  SELECT TO_NUMBER(:TRADE_ID),
         TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         A.USER_ID,
         B.DISCNT_CODE,
         '1',
         B.START_DATE,
         A.ACCEPT_DATE - 1 / 24 / 3600
    FROM TF_B_TRADE A, TF_F_USER_DISCNT B, TD_S_COMMPARA C
   WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND B.PARTITION_ID = MOD(A.USER_ID, 10000)
     AND B.USER_ID = A.USER_ID
     AND B.DISCNT_CODE = C.PARA_CODE5
     AND B.END_DATE > SYSDATE
     AND C.PARAM_ATTR = 908
     AND C.PARAM_CODE = :SERVICE_ID
     AND C.PARA_CODE2 = '1'
     AND C.PARA_CODE3 = '1'
     AND (C.EPARCHY_CODE = A.TRADE_EPARCHY_CODE OR C.EPARCHY_CODE = 'ZZZZ')
     AND NOT EXISTS
   (SELECT 1
            FROM TF_B_TRADE_DISCNT
           WHERE TRADE_ID = A.TRADE_ID
             AND ACCEPT_MONTH = TO_NUMBER(SUBSTRB(:TRADE_ID, 5, 2))
             AND DISCNT_CODE = C.PARA_CODE5)