INSERT INTO TI_B_USER
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID, CUST_ID, USECUST_ID,
         EPARCHY_CODE, CITY_CODE, CITY_CODE_A, USER_PASSWD, USER_DIFF_CODE, USER_TYPE_CODE,
         USER_TAG_SET, USER_STATE_CODESET, NET_TYPE_CODE, SERIAL_NUMBER, CONTRACT_ID, ACCT_TAG,
         PREPAY_TAG, MPUTE_MONTH_FEE, MPUTE_DATE, FIRST_CALL_TIME, LAST_STOP_TIME, CHANGEUSER_DATE,
         IN_NET_MODE, IN_DATE, IN_STAFF_ID, IN_DEPART_ID, OPEN_MODE, OPEN_DATE, OPEN_STAFF_ID,
         OPEN_DEPART_ID, DEVELOP_STAFF_ID, DEVELOP_DATE, DEVELOP_DEPART_ID, DEVELOP_CITY_CODE,
         DEVELOP_EPARCHY_CODE, DEVELOP_NO, ASSURE_CUST_ID, ASSURE_TYPE_CODE, ASSURE_DATE, REMOVE_TAG,
         PRE_DESTROY_TIME, DESTROY_TIME, REMOVE_EPARCHY_CODE, REMOVE_CITY_CODE, REMOVE_DEPART_ID,
         REMOVE_REASON_CODE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1,
         RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
         RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10, RSRV_DATE1, RSRV_DATE2,
         RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, BRAND_CODE, PRODUCT_ID)
        SELECT DISTINCT :SYNC_SEQUENCE, substr(:SYNC_SEQUENCE,7,2), '8', '', B.PARTITION_ID, B.USER_ID,
                        B.CUST_ID, B.USECUST_ID, B.EPARCHY_CODE, B.CITY_CODE, B.CITY_CODE_A,
                        B.USER_PASSWD, B.USER_DIFF_CODE, B.USER_TYPE_CODE, B.USER_TAG_SET,
                        B.USER_STATE_CODESET, B.NET_TYPE_CODE, B.SERIAL_NUMBER, B.CONTRACT_ID,
                        B.ACCT_TAG, B.PREPAY_TAG, B.MPUTE_MONTH_FEE, B.MPUTE_DATE, B.FIRST_CALL_TIME,
                        B.LAST_STOP_TIME, B.CHANGEUSER_DATE, B.IN_NET_MODE, B.IN_DATE, B.IN_STAFF_ID,
                        B.IN_DEPART_ID, B.OPEN_MODE, B.OPEN_DATE, B.OPEN_STAFF_ID, B.OPEN_DEPART_ID,
                        B.DEVELOP_STAFF_ID, B.DEVELOP_DATE, B.DEVELOP_DEPART_ID, B.DEVELOP_CITY_CODE,
                        B.DEVELOP_EPARCHY_CODE, B.DEVELOP_NO, B.ASSURE_CUST_ID, B.ASSURE_TYPE_CODE,
                        B.ASSURE_DATE, B.REMOVE_TAG, B.PRE_DESTROY_TIME, B.DESTROY_TIME,
                        B.REMOVE_EPARCHY_CODE, B.REMOVE_CITY_CODE, B.REMOVE_DEPART_ID,
                        B.REMOVE_REASON_CODE, B.UPDATE_TIME, B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID,
                        B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5,
                        B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_STR6,
                        B.RSRV_STR7, B.RSRV_STR8, B.RSRV_STR9, B.RSRV_STR10, B.RSRV_DATE1,
                        B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3,
                        C.BRAND_CODE, C.PRODUCT_ID
          FROM TF_F_USER B, TF_F_USER_PRODUCT C
         WHERE B.PARTITION_ID=MOD(:USER_ID,10000) AND B.USER_ID=:USER_ID
           AND C.USER_ID = :USER_ID
		   AND B.USER_ID = C.USER_ID 
           AND C.PARTITION_ID = MOD(:USER_ID, 10000)