UPDATE TD_B_TRADE_RECEIPT
   SET TRADE_TYPE_CODE = :TRADE_TYPE_CODE, BRAND_CODE = :BRAND_CODE,
       PRODUCT_ID = :PRODUCT_ID, TRADE_ATTR = :TRADE_ATTR,
       RECEIPT_INFO1 = :RECEIPT_INFO1, RECEIPT_INFO2 = :RECEIPT_INFO2,
       RECEIPT_INFO3 = :RECEIPT_INFO3, RECEIPT_INFO4 = :RECEIPT_INFO4,
       RECEIPT_INFO5 = :RECEIPT_INFO5,
       START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       EPARCHY_CODE = :EPARCHY_CODE, REMARK = :REMARK,
       UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       UPDATE_TIME = TO_DATE(SUBSTR(TO_CHAR(:UPDATE_TIME), 1, 10), 'YYYY-MM-DD')
 WHERE TRADE_TYPE_CODE = :OLD_TRADE_TYPE_CODE
   AND BRAND_CODE = :OLD_BRAND_CODE
   AND (PRODUCT_ID = :OLD_PRODUCT_ID)
   AND TRADE_ATTR = :OLD_TRADE_ATTR
   AND START_DATE = TO_DATE(:OLD_START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND (EPARCHY_CODE = :OLD_EPARCHY_CODE)