SELECT CATEGORYCODE CATEGORY_CODE, MATERIALCODE MATERIAL_CODE, TAKEDATE TAKE_DATE,
	QUOTATION QUOTATION
FROM TI_R_MISSIONLIST_PLAN_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')