INSERT INTO TF_B_TRADE_SCOREFACTORY(TRADE_ID,ACCEPT_MONTH,USER_ID,FACTORY_CODE,FACTORY,ACTION_NAME,SCORE_TYPE_CODE,SCORE_CHANGED_SUB,VALUE_CHANGED_SUB,ACTION_COUNT,REMARK)
VALUES(TO_NUMBER(:TRADE_ID),TO_NUMBER(:ACCEPT_MONTH),TO_NUMBER(:USER_ID),:FACTORY_CODE,:FACTORY,
:ACTION_NAME,:SCORE_TYPE_CODE,:SCORE_CHANGED_SUB,:VALUE_CHANGED_SUB,:ACTION_COUNT,:REMARK)