SELECT TASK_ID,PARTITION_ID,ORDER_ID,TASK_CHAN_ID,EXE_CHAN_ID,SEND_OBJECT,CONTENT,TITLE,APPENDIX,ACCEPT_MONTH,EXE_DIR,EXE_METHOD,EXE_TYPE,EPARCHY_CODE,EXEC_COUNT,EXEC_CURRENT,
EXPIRE_TIME,START_TIME,FINISH_TIME,TASK_PRI,RSP_TIME,TASK_STATUS,RSP_CODE,RSP_DESC,REMARK,PREVALUE1,PREVALUE2,PREVALUE3,PREVALUE4,PREVALUE5,MONTH,DAY
 FROM TF_B_ORDER WHERE 1=1
 AND TASK_ID = :TASK_ID
 AND PARTITION_ID = :PARTITION_ID
 AND ORDER_ID = :ORDER_ID
 AND SEND_OBJECT = :SEND_OBJECT
 AND TASK_CHAN_ID = :TASK_CHAN_ID
 AND EXE_CHAN_ID = :EXE_CHAN_ID
 AND EXE_DIR = :EXE_DIR
 AND TASK_PRI = :TASK_PRI
 AND EPARCHY_CODE = :EPARCHY_CODE
 AND to_char(EXPIRE_TIME,'yyyy-MM-dd') <= :EXPIRE_TIME
 ORDER BY TASK_ID DESC