SELECT
  SERIAL_NUMBER,
  AIRLINES_NAME,
  MAINAIR_PRV_NAME,
  PROVINCE_NAME,
  CITY_NAME,
  STAFF_NAME,
  IMPORT_TIME,
  UPDATE_TIME,
  UPDATE_STAFF_ID,
  UPDATE_DEPART_ID,
  REMARK,
  RSRV_NUM1,
  RSRV_NUM2,
  RSRV_NUM3,
  RSRV_STR1,
  RSRV_STR2,
  RSRV_STR3,
  RSRV_STR4,
  RSRV_STR5,
  RSRV_DATE1,
  RSRV_DATE2,
  RSRV_DATE3
FROM TF_F_AIRLINES_WHITE
WHERE 1=1
  AND (AIRLINES_NAME LIKE '%'||:AIRLINES_NAME||'%' OR :AIRLINES_NAME IS NULL)
  AND (MAINAIR_PRV_NAME LIKE '%'||:MAINAIR_PRV_NAME||'%' OR :MAINAIR_PRV_NAME IS NULL)
  AND (PROVINCE_NAME LIKE '%'||:PROVINCE_NAME||'%' OR :PROVINCE_NAME IS NULL)
  AND (CITY_NAME LIKE '%'||:CITY_NAME||'%' OR :CITY_NAME IS NULL)
  AND (STAFF_NAME LIKE '%'||:STAFF_NAME||'%' OR :STAFF_NAME IS NULL)
  AND (SERIAL_NUMBER LIKE '%'||:SERIAL_NUMBER||'%' OR :SERIAL_NUMBER IS NULL)
  AND REMOVE_TAG = :REMOVE_TAG
