SELECT COUNT(1) ACTIVE_OLD_USER_NUM, 0 ACTIVE_NEW_USER_NUM
  FROM TF_F_USER_SALE_ACTIVE T
 WHERE T.PROCESS_TAG = '0'
   AND T.PACKAGE_ID = :PACKAGE_ID_O
   AND T.PRODUCT_ID = :PRODUCT_ID
   AND T.ACCEPT_DATE = :ACCEPT_DATE
   AND T.TRADE_STAFF_ID = :STAFF_ID
UNION
SELECT 0, COUNT(1)
  FROM TF_F_USER_SALE_ACTIVE T
 WHERE T.PROCESS_TAG = '0'
   AND T.PACKAGE_ID = :PACKAGE_ID_N
   AND T.PRODUCT_ID = :PRODUCT_ID
   AND T.ACCEPT_DATE = :ACCEPT_DATE
   AND T.TRADE_STAFF_ID = :STAFF_ID