DELETE FROM TF_F_USER_ATTR A
WHERE A.USER_ID = TO_NUMBER(:USER_ID)
AND   A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
And   INST_TYPE = :INST_TYPE
AND   INST_ID   = :INST_ID
AND   ATTR_CODE = :ATTR_CODE
and   start_date=to_date(:START_DATE,'YYYY-MM-DD hh24:mi:ss')