--IS_CACHE=Y
select A.*, B.*, B.COP_CODE SI_CODE, A.ACCESS_MODE ACCESS_MODEL
  from TF_COP_SERVICE A, TF_COP_PARTNER B, TF_COP_SERVICE_REL C
 where 1 = 1
   and A.SERV_ID = C.SERV_ID
   and B.COP_ID = C.COP_ID
   and A.BIZ_CODE = :BIZ_CODE