INSERT INTO TF_F_USER_SVC
  (PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,MAIN_TAG,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
  SELECT MOD(A.USER_ID, 10000),
         A.USER_ID,A.USER_ID_A,A.PRODUCT_ID,A.PACKAGE_ID,A.SERVICE_ID,A.MAIN_TAG,A.INST_ID,A.CAMPN_ID,A.START_DATE,A.END_DATE,sysdate,A.UPDATE_STAFF_ID,A.UPDATE_DEPART_ID,A.REMARK,A.RSRV_NUM1,A.RSRV_NUM2,A.RSRV_NUM3,A.RSRV_NUM4,A.RSRV_NUM5,A.RSRV_STR1,A.RSRV_STR2,A.RSRV_STR3,A.RSRV_STR4,A.RSRV_STR5,A.RSRV_STR6,A.RSRV_STR7,A.RSRV_STR8,A.RSRV_STR9,A.RSRV_STR10,A.RSRV_DATE1,A.RSRV_DATE2,A.RSRV_DATE3,A.RSRV_TAG1,A.RSRV_TAG2,A.RSRV_TAG3
    FROM TF_B_TRADE_SVC_BAK A
   WHERE A.TRADE_ID = to_number(:TRADE_ID)