SELECT A.PARTITION_ID PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       TO_CHAR(A.USER_ID_A) USER_ID_A,
       A.PRODUCT_ID PRODUCT_ID,
       A.PRODUCT_MODE PRODUCT_MODE,
       A.BRAND_CODE BRAND_CODE,
       TO_CHAR(A.INST_ID) INST_ID,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       A.UPDATE_STAFF_ID UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID UPDATE_DEPART_ID
  FROM TF_F_USER_PRODUCT A, TD_S_COMMPARA B
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 4003
   AND B.END_DATE > SYSDATE
   AND TO_CHAR(A.PRODUCT_ID) = B.PARAM_CODE