SELECT T.*
  FROM TF_F_USER_PRODUCT T
 WHERE T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.USER_ID_A = :USER_ID_A
	 AND T.INST_ID=:INST_ID
  AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE