SELECT TO_CHAR(U.USER_ID) USER_ID, 
       U.SERIAL_NUMBER SERIAL_NUMBER
  FROM TF_F_USER_PRODUCT T, TF_F_USER U
 WHERE T.PRODUCT_ID = :PRODUCT_ID
   AND T.END_DATE > T.START_DATE
   AND T.MAIN_TAG = '1'
   AND T.PARTITION_ID = U.PARTITION_ID
   AND T.USER_ID = U.USER_ID
   AND U.REMOVE_TAG = '0'