SELECT D.INST_ID,
       D.PROD_INST_ID,
       B.PRODUCT_ID,
       C.PARA_CODE1 PRODUCT_CODE,
       B.USER_ID,
       B.USER_ID_A,
       B.START_DATE,
       B.END_DATE
  FROM TF_F_USER_PRODUCT B, TD_S_COMMPARA C, TF_F_INSTANCE_PF D
 WHERE B.USER_ID = TO_NUMBER(:USER_ID)
   AND B.USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND B.INST_ID = D.INST_ID
   AND D.INST_TYPE = 'S'
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '9015'
   AND TO_CHAR(B.PRODUCT_ID) = C.PARAM_CODE
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE