SELECT 
       
       T.PRODUCT_ID,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_USER_PRODUCT T
 WHERE 
    T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
