UPDATE TF_F_USER_PRODUCT
   SET START_DATE  = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE    = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       REMARK      = :REMARK,
       UPDATE_TIME = SYSDATE,
       RSRV_DATE2  = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE3  = TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND PRODUCT_ID = :PRODUCT_ID
   AND PRODUCT_MODE = :PRODUCT_MODE
   AND BRAND_CODE = :BRAND_CODE
   AND INST_ID = :INST_ID
   AND END_DATE + 0 > SYSDATE