INSERT INTO TF_B_TRADE_PLATSVC
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,   
   SERVICE_ID,
   SERIAL_NUMBER,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   ORG_DOMAIN,
   OPER_CODE,
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_TAG3)
  SELECT :TRADE_ID,
         SUBSTR(:TRADE_ID, 5, 2),
         :USER_ID,
         '50000000',
         '50000000',
         '98009944',
         :SERIAL_NUMBER,
         'FF',
         'A',
         'DSMP',
         '02',
         :OPR_SOURCE,
         ' ',
         ' ',
         TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss'),
         TO_DATE('2050-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
         TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '用户销户 DSMP 发送 02 指令！',
         'E'
    FROM DUAL