INSERT INTO TF_B_TRADE_PLATSVC
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   SP_CODE,
   BIZ_CODE,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   PRODUCT_NO,
   ORG_DOMAIN,
   OPER_CODE,
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   SUBSCRIBE_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_STR6,
   RSRV_STR7,
   RSRV_STR8,
   RSRV_STR9,
   RSRV_STR10,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  SELECT :TRADE_ID,
         SUBSTR(:TRADE_ID, 5, 2),
         A.USER_ID,
         A.PRODUCT_ID,
         A.PACKAGE_ID,
         A.SERVICE_ID,
         A.SERIAL_NUMBER,
         A.SP_CODE,
         A.BIZ_CODE,
         A.BIZ_TYPE_CODE,
         'N',
         A.PRODUCT_NO,
         A.ORG_DOMAIN,
         '04',
         '08',
         A.BILL_TYPE,
         A.PRICE,
         A.FIRST_DATE,
         A.FIRST_DATE_MON,
         A.GIFT_SERIAL_NUMBER,
         A.GIFT_USER_ID,
         A.SUBSCRIBE_ID,
         A.START_DATE + 1 / 24 / 3600,
         A.END_DATE,
         TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '用户停机等需要暂停SP业务',
         2,
         A.RSRV_NUM2,
         A.RSRV_NUM3,
         A.RSRV_NUM4,
         A.RSRV_NUM5,
         A.RSRV_STR1,
         A.RSRV_STR2,
         A.RSRV_STR3,
         A.RSRV_STR4,
         A.RSRV_STR5,
         A.RSRV_STR6,
         A.RSRV_STR7,
         A.RSRV_STR8,
         A.RSRV_STR9,
         A.RSRV_STR10,
         A.RSRV_DATE1,
         A.RSRV_DATE2,
         A.RSRV_DATE3,
         A.RSRV_TAG1,
         '1',
         A.RSRV_TAG3
    FROM TF_F_USER_PLATSVC_BOOK A
    WHERE A.USER_ID = :USER_ID
   AND A.BOOK_STATE = '0'
   AND A.OPER_CODE in('01','06')
   AND A.BIZ_TYPE_CODE='53'