SELECT TRADE_ID,
       ACCEPT_MONTH,
       USER_ID,
       SERVICE_ID,
       BIZ_STATE_CODE,
       TO_CHAR(FIRST_DATE, 'yyyy-mm-dd hh24:mi:ss') FIRST_DATE,
       TO_CHAR(FIRST_DATE_MON, 'yyyy-mm-dd hh24:mi:ss') FIRST_DATE_MON,
       GIFT_SERIAL_NUMBER,
       GIFT_USER_ID,
       IN_CARD_NO,
       ENTITY_CARD_NO,
       INST_ID,
       OPER_CODE,
       OPR_SOURCE,
       SUBSCRIBE_ID,
       PKGSEQ,
       UDSUM,
       INTF_TRADE_ID,
       IS_NEED_PF,
       ALL_TAG,
       ACTIVE_TAG,
       TO_CHAR(OPER_TIME, 'yyyy-mm-dd hh24:mi:ss') OPER_TIME,
       MODIFY_TAG,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_B_TRADE_PLATSVC
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = TO_NUMBER(:TRADE_ID)
 Order By User_Id, Service_Id, Start_Date
