SELECT A.*,B.CARD_NO FROM TF_B_TRADE_PLATSVC A,TF_F_USER_PLATSVC_ENTITYCARD B
WHERE A.TRADE_ID = :TRADE_ID
AND A.OPER_CODE = '07'
AND A.OPR_SOURCE <> '64'
AND A.USER_ID = B.USER_ID
AND A.SERVICE_ID = B.SERVICE_ID
AND SYSDATE BETWEEN B.START_DATE AND B.RSRV_DATE1
AND B.START_DATE = (SELECT MAX(START_DATE) FROM TF_F_USER_PLATSVC_ENTITYCARD 
                           WHERE USER_ID = A.USER_ID AND SERVICE_ID = A.SERVICE_ID)
AND NOT EXISTS(SELECT 1 FROM TF_F_USER_PLATSVC C WHERE C.USER_ID = B.USER_ID 
                                                       AND C.SERVICE_ID = B.SERVICE_ID
                                                       AND C.BIZ_STATE_CODE = 'E'
                                                       AND C.START_DATE < A.START_DATE
                                                       AND C.START_DATE BETWEEN B.START_DATE AND SYSDATE)