SELECT TRADE_ID
          FROM TF_B_TRADE_PLATSVC
         WHERE USER_ID = :USER_ID
           AND SERVICE_ID = :SERVICE_ID
           AND OPER_CODE = :OPER_CODE
           AND START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
           AND TRADE_ID !=(
           SELECT MIN(TRADE_ID) TRADE_ID FROM (
           SELECT TRADE_ID
          FROM TF_B_TRADE_PLATSVC
         WHERE USER_ID = :USER_ID
           AND SERVICE_ID = :SERVICE_ID
           AND OPER_CODE = :OPER_CODE
           AND START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')))