SELECT 
to_char(t.TRADE_ID) TRADE_ID, 
t.ACCEPT_MONTH,
to_char(t.USER_ID) USER_ID,
t.SERVICE_ID,
t.SERIAL_NUMBER,
t.SP_CODE,
t.BIZ_CODE,
t.BIZ_TYPE_CODE,
t.BIZ_STATE_CODE,
t.PRODUCT_NO,
t.ORG_DOMAIN,
t.OPER_CODE,
t.OPR_SOURCE,
t.BILL_TYPE,
t.PRICE,
to_char(t.FIRST_DATE,'yyyy-mm-dd hh24:mi:ss') FIRST_DATE,
to_char(t.FIRST_DATE_MON,'yyyy-mm-dd hh24:mi:ss') FIRST_DATE_MON,
t.GIFT_SERIAL_NUMBER,
t.GIFT_USER_ID,
to_char(t.SUBSCRIBE_ID) SUBSCRIBE_ID,
to_char(t.START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,
to_char(t.END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,
to_char(t.UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
t.UPDATE_STAFF_ID,
t.UPDATE_DEPART_ID,
t.REMARK,
t.RSRV_NUM1,
t.RSRV_NUM2,
t.RSRV_NUM3,
to_char(t.RSRV_NUM4) RSRV_NUM4,
to_char(t.RSRV_NUM5) RSRV_NUM5,
t.RSRV_STR1,
t.RSRV_STR2,
t.RSRV_STR3,
t.RSRV_STR4,
t.RSRV_STR5,
t.RSRV_STR6,
t.RSRV_STR7,
t.RSRV_STR8,
t.RSRV_STR9,
t.RSRV_STR10,
to_char(t.RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss')RSRV_DATE1,
to_char(t.RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss')RSRV_DATE2,
to_char(t.RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss')RSRV_DATE3,
t.RSRV_TAG1,
t.RSRV_TAG2,
t.RSRV_TAG3
FROM tf_b_trade_platsvc t 
WHERE  case when rsrv_str8 is null then oper_code else rsrv_str8 end in (
SELECT s.param_code FROM td_s_commpara s WHERE s.param_attr = '717' AND s.para_code1 = '3' AND s.subsys_code = 'CSM'
) AND
t.rsrv_tag2 = '1'
and
t.trade_id =TO_NUMBER(:TRADE_ID)
AND t.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
