UPDATE TF_F_USER_OTHER
   SET END_DATE   = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS') -
                    1 / 24 / 3600,
       RSRV_STR11 = :RSRV_STR11
 WHERE RSRV_VALUE_CODE = :RSRV_VALUE_CODE
   AND USER_ID = :USER_ID
   AND RSRV_STR10 = :RSRV_STR10
   AND SYSDATE BETWEEN START_DATE AND END_DATE