UPDATE TF_B_TRADE_PLATSVC
   SET RSRV_TAG2 = :RSRV_TAG2
 WHERE 
 		ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = :TRADE_ID
   AND USER_ID = :USER_ID
   AND SERVICE_ID = :SERVICE_ID
   AND OPER_CODE = :OPER_CODE
   AND OPR_SOURCE = :OPR_SOURCE
   AND BIZ_TYPE_CODE = :BIZ_TYPE_CODE
   AND ORG_DOMAIN = :ORG_DOMAIN