UPDATE TF_B_TRADE_PLATSVC
   SET RSRV_STR4 = :RSRV_STR4
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = :TRADE_ID
   AND USER_ID = :USER_ID
   AND SERVICE_ID = :SERVICE_ID
   AND OPER_CODE = :OPER_CODE