--IS_CACHE=Y
SELECT A.IMPORT_ID, A.ALLIANCE_NAME, A.AREA_CODE, A.ALLIANCE_TYPE_CODE, A.FAVOURABLETYPE, A.OFFINFO, A.APPLYTIME, A.ZKLIMIT, A.LINKPHONE, A.ADDRESS, A.ALLIANCE_RANK, A.OPER_TYPE, A.IMPORT_DATE, A.OPR_SOURCE, A.FILE_NAME, B.DATA_TYPE, B.IMPORT_TIME, B.IMPORT_STAFF_ID, B.IMPORT_DEPART_ID, B.DEAL_FLAG, B.DEAL_TIME, B.DEAL_RESULT, B.REMARK
FROM TD_B_ALLIANCE_IMPORT_DTL A, TD_B_ALLIANCE_BATIMPORT B
WHERE 1 = 1
AND (A.IMPORT_ID = B.IMPORT_ID)
AND (A.IMPORT_ID = :IMPORT_ID)
AND (B.DEAL_FLAG = :DEAL_FLAG)
AND (B.IMPORT_STAFF_ID = :IMPORT_STAFF_ID)
AND (B.IMPORT_TIME >= TO_DATE(:IMPORT_DATE_START, A. 'YYYY-MM-DD'))
AND (B.IMPORT_TIME <= TO_DATE(:IMPORT_DATE_END, A. 'YYYY-MM-DD'))
AND (A.ALLIANCE_RANK = :ALLIANCE_RANK)
AND (A.ALLIANCE_TYPE_CODE = :ALLIANCE_TYPE_CODE)
AND (A.AREA_CODE = :AREA_CODE)