--IS_CACHE=Y
select IMPORT_ID,DATA_TYPE,IMPORT_TIME,IMPORT_STAFF_ID,IMPORT_DEPART_ID,DEAL_FLAG,DEAL_TIME,DEAL_RESULT,REMARK
from TD_B_ALLIANCE_BATIMPORT a
where 1 = 1
AND (a.IMPORT_ID=:IMPORT_ID)
AND (a.IMPORT_STAFF_ID=:IMPORT_STAFF_ID)
AND (a.import_time >=to_date(:IMPORT_DATE_START,'YYYY-MM-DD hh24:mi:ss')) 
AND (a.import_time <=to_date(:IMPORT_DATE_END,'YYYY-MM-DD hh24:mi:ss')) 
AND (a.DATA_TYPE=:DATA_TYPE) 
AND (a.DEAL_FLAG=:DEAL_FLAG)
order by a.import_time desc