SELECT SERIAL_NUMBER_B,RSRV_STR1,RSRV_STR2,RSRV_DATE2,GIVE_TAG,GIVE_DATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID 
    FROM TF_F_VPMNACTIVE_RELATION 
    where 1 = 1 AND USER_ID_A = :USER_ID_A AND ACTIVE_TYPE = :ACTIVE_TYPE AND END_DATE > SYSDATE 