SELECT T.SUBORDER_ID,T.SUBEXTORDER_ID,T.ORDER_ID,T.STATE,T.DEAL_STATE,T.DEAL_DESC,T.NUMBER_OPRTYPE,T.SERVICENO,T.SERVICENO_TYPE,
T.NUMBER_BRAND,T.QUANTITY,T.NUMBER_PRICE,T.SIM_PRICE,T.LEGAL_NAME,T.CERTIFICATE_TYPE,T.CERTIFICATE_NO,T.ACTIVITY_CODE,T.ACTIVITY_TYPE,
T.ACTIVITY_NAME,T.ACTIVITY_DESC,T.ORDER_STATUS,T.RSRV_STR1,T.CREATE_TIME,T.UPDATE_TIME,T.STATE
FROM TF_B_CTRM_GERLSUBORDER T
WHERE T.SUBORDER_ID =:SUBORDER_ID and T.ORDER_ID =:ORDER_ID 

