UPDATE TF_B_TRADE_SVC
   SET RSRV_STR1='1'
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND SERVICE_ID = :SERVICE_ID