 SELECT TO_CHAR(TRADE_ID) TRADE_ID,
       ACCEPT_MONTH,
       OPER_TYPE,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(ACCT_ID) ACCT_ID,
       TO_CHAR(USER_ID2) USER_ID2,
       TO_CHAR(ACCT_ID2) ACCT_ID2,
       TO_CHAR(OPER_FEE) OPER_FEE,
       TO_CHAR(ACTION_CODE) ACTION_CODE,
       TO_CHAR(PAYMENT_ID) PAYMENT_ID,
       IN_DEPOSIT_CODE,
       OUT_DEPOSIT_CODE,
       IS_ACCTDAY,
       REQUEST_ID,
       TO_CHAR(START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE,'YYYY-MM-DD HH24:MI:SS')  END_DATE,
       TO_CHAR(UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10
  FROM UCR_CRM1.TF_B_TRADEFEE_OTHERFEE
   WHERE OPER_TYPE = 'roamFeeTrans'
   AND RSRV_STR6 NOT IN ('9999','0000')
   AND UPDATE_TIME >= TO_DATE(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS')
   AND ROWNUM < 500
   ORDER BY USER_ID,UPDATE_TIME