SELECT A.TRADE_ID,
       TO_CHAR(A.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
       A.CUST_ID,
       A.CUST_NAME,
       A.TRADE_TYPE_NAME TRADE_TYPE,
       A.UPDATE_STAFF_ID TRADE_STAFF_ID
  FROM TF_B_CRM_TAXLOG A
 WHERE 1 = 1
   AND NOT EXISTS
 (SELECT 1
          FROM TF_LOG_APPROVE_RECEIPT B
         WHERE 1 = 1
           AND (B.RECEIPT_SATE = '0' OR B.RECEIPT_SATE = '2')
           AND B.TRADE_ID = A.TRADE_ID
           AND B.ACCEPT_MONTH = A.ACCEPT_MONTH)
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADEFEE_TAX TAX
         WHERE TAX.TRADE_ID = A.TRADE_ID
           AND TAX.ACCEPT_MONTH = A.ACCEPT_MONTH)
   AND A.CUST_ID = :CUST_ID
   AND A.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'YYYY-MM-DD') AND
       TO_DATE(:END_DATE, 'YYYY-MM-DD') + 1