SELECT 
to_char(TRADE_ID) TRADE_ID,
ACCEPT_MONTH,
PARTITION_ID,
PAYRELATION_ID,
to_char(USER_ID) USER_ID,
LIMIT_TYPE,
LIMIT_VALUE,
INTEGRAL_ACCOUNT_ID,
DEFAULT_TAG,
ACT_TAG,
to_char(START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,
to_char(END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE,
REMARK,
to_char(UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
UPDATE_DEPART_ID,
UPDATE_STAFF_ID,
RSRV_STR1,
RSRV_STR2,
RSRV_STR3,
RSRV_NUM1,
RSRV_NUM2,
RSRV_NUM3,
to_char(RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
to_char(RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
to_char(RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3
FROM TF_B_TRADE_SCORERELATION_BAK 
WHERE TRADE_ID = :TRADE_ID
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))