UPDATE TF_F_USER_INFO_CLASS T
SET T.END_DATE = TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss'),
    T.RSRV_STR1 = :RSRV_STR1
WHERE T.USER_ID = TO_NUMBER(:USER_ID)
 AND  T.START_DATE < SYSDATE
 AND  T.END_DATE > SYSDATE