SELECT TO_CHAR(T.USER_ID) USER_ID,T.SERIAL_NUMBER,T.USER_CLASS,T.BIRTHDAY,TO_CHAR(T.IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE,TO_CHAR(T.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,TO_CHAR(T.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,TO_CHAR(T.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1 FROM UCR_CRM1.TF_F_USER_INFO_CLASS T WHERE 1=1 AND T.USER_ID =:USER_ID  
 AND T.RSRV_STR1 =:RSRV_STR1
 AND T.END_DATE>SYSDATE
 ORDER BY T.END_DATE DESC