Select a.USER_ID, a.SERIAL_NUMBER, a.SPEC_TYPE, a.SPEC_FLAG, a.IN_TIME, a.RSRV_DATE1, a.RSRV_DATE2, a.RSRV_STR1, a.RSRV_STR2, a.RSRV_STR3, a.RSRV_STR4, a.RSRV_STR5 
From TP_F_VPMN_SPEC_USER a, TF_F_USER b 
Where a.USER_ID=b.USER_ID 
and a.SPEC_TYPE=:SPEC_TYPE 
and a.SPEC_FLAG=:SPEC_FLAG
and b.SERIAL_NUMBER=:SERIAL_NUMBER
and b.REMOVE_TAG='0'