SELECT INST_ID,PRODUCT_ID,BIZ_CODE,PROD_NAME,SERV_CODE,SOURCE,SERIAL_NUMBER,OPER_CODE,STATUS,
EFFTT,SYNC_FLAG,UPDATE_TIME,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,RSRV_STR2,RSRV_STR3,
RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3 FROM TI_B_WHITECONFIRM_R T
WHERE T.PRODUCT_ID = :PRODUCT_ID AND T.SERIAL_NUMBER = :SERIAL_NUMBER
