SELECT A.REL_ID,
       A.ENTERPRISE_NAME,
       A.AREA_CODE,
       A.ENTERPRISE_ADDR,
       A.CUST_NAME,
       A.CONTACT_SN,
       A.PRODUCT_NAME,
       A.UPDATE_STAFF_ID,
       A.REMARK,
       TO_CHAR(A.REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_DATE1,
       A.RSRV_DATE2,
       A.RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3
  FROM TF_F_ENTERPRISE_WIDENET_BOOK A
 WHERE (A.REG_DATE >= TO_DATE(:START_DATE, 'YYYY-MM-DD') OR :START_DATE IS NULL) 
   AND (A.REG_DATE <= TO_DATE(:END_DATE, 'YYYY-MM-DD') + 1 OR :END_DATE IS NULL)
   AND (TRIM(A.ENTERPRISE_NAME) like '%' || :ENTERPRISE_NAME || '%')
   AND (TRIM(A.ENTERPRISE_ADDR) like '%' || :ENTERPRISE_ADDR || '%')
 ORDER BY A.REG_DATE ASC 
