SELECT A.USER_ID, A.SERVICE_ID
  FROM TF_F_USER_SVC A, TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND TO_CHAR(A.SERVICE_ID) = C.PARAM_CODE
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = 4012
   AND C.END_DATE > SYSDATE