--IS_CACHE=Y
SELECT PRODUCT_ID, PACKAGE_ID, ELEMENT_TYPE_CODE, ELEMENT_ID, MAX_NUMBER, MIN_NUMBER, RULE_ID, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, EPARCHY_CODE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RULE_TYPE, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4
 FROM TD_B_GROUP_DESIGN_RULE
 WHERE PRODUCT_ID=TO_NUMBER(:PRODUCT_ID)
 AND (PACKAGE_ID=TO_NUMBER(:PACKAGE_ID) or :PACKAGE_ID IS NULL)
 AND ELEMENT_TYPE_CODE=:ELEMENT_TYPE_CODE
 AND ELEMENT_ID=TO_NUMBER(:ELEMENT_ID)
 AND SYSDATE BETWEEN START_DATE AND END_DATE