SELECT A.ROWID ROWID_T,
       A.CHNL_ID,
       TRIM(A.FACTORY_CODE) CORP_NO,
       TRIM(A.CHNL_ID) SHOP_NO,
       A.YEAR,
       A.ACCEPT_MONTH,
       A.BALANCE / 100 BALANCE,
       A.UPDATE_STAFF,
       TO_CHAR(A.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       DECODE(A.STATUS, '0', '未缴纳', '1', '已缴纳') STATUS,
       RSRV_STR1 AREA_CODE,
	   RSRV_STR3 FEE_ITEM,
       REMARK
  FROM TF_R_FEE_MARKET A
 WHERE 1 = 1
   AND A.YEAR || LPAD(A.ACCEPT_MONTH,2,'0') >= :START_TIME
   AND A.YEAR || LPAD(A.ACCEPT_MONTH,2,'0') <= :END_TIME
   AND TRIM(A.CHNL_ID) = :SHOP_NAME
   AND TRIM(A.FACTORY_CODE) = :CORP_NAME
   AND A.RSRV_STR1 = :AREA_CODE