INSERT INTO TF_B_TRADE_PLATSVC_BAK(TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID,5,2)),PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
   FROM TF_F_USER_PLATSVC a
 WHERE a.user_id = TO_NUMBER(:USER_ID)
  AND a.partition_id = MOD(TO_NUMBER(:USER_ID), 10000)
  AND END_DATE >LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -2))
  AND NOT EXISTS (SELECT 1 FROM TF_B_TRADE_PLATSVC_BAK
                 WHERE  trade_id = TO_NUMBER(:TRADE_ID)
                 AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                 AND user_id = a.user_id
                 AND service_id = a.service_id
                 AND start_date = a.start_date)