INSERT INTO TF_B_TRADE_POSTINFO_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,ID,ID_TYPE,CUST_TYPE,POST_NAME,POST_TAG,POST_CONTENT,POST_TYPESET,POST_CYC,POST_ADDRESS,POST_CODE,EMAIL,FAX_NBR,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,ID,ID_TYPE,CUST_TYPE,POST_NAME,POST_TAG,POST_CONTENT,POST_TYPESET,POST_CYC,POST_ADDRESS,POST_CODE,EMAIL,FAX_NBR,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_POSTINFO a
 WHERE ID = TO_NUMBER(:USER_ID)
 AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
 AND ID_TYPE='1'
 AND NOT EXISTS (SELECT 1 FROM TF_B_TRADE_POSTINFO_BAK
                 WHERE  trade_id = TO_NUMBER(:TRADE_ID)
                 AND id = a.id
                 AND id_type = a.id_type
                 AND start_date = a.start_date
                 )