INSERT INTO TF_B_TRADE_ATTR_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_ATTR a
 WHERE (PARTITION_ID, USER_ID) IN
     ( SELECT mod(t1.USER_ID, 10000), t1.USER_ID
                      from TF_B_TRADE_attr t1
                      where t1.trade_id = TO_NUMBER(:TRADE_ID)
                      and t1.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                      )
 AND NOT EXISTS (select 1 from tf_b_trade_attr_bak c
                 where c.trade_id = TO_NUMBER(:TRADE_ID)
                 and c.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                 and a.USER_ID=c.USER_ID
                 and a.ATTR_CODE=c.ATTR_CODE
                 and a.start_date=c.start_date
                 )