INSERT INTO TF_B_TRADE_INFOCHANGE_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID,TRADE_TYPE_CODE,RELATION_TRADE_ID,PRODUCT_ID,BRAND_CODE,SERIAL_NUMBER,IMSI,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,USER_ID,TRADE_TYPE_CODE,RELATION_TRADE_ID,PRODUCT_ID,BRAND_CODE,SERIAL_NUMBER,IMSI,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_INFOCHANGE a
 WHERE (PARTITION_ID,USER_ID) in
                (select mod(user_id, 10000),user_id
                 from TF_B_TRADE_USER a
                 where trade_id = TO_NUMBER(:TRADE_ID))
 AND NOT EXISTS (SELECT 1 FROM TF_B_TRADE_INFOCHANGE_BAK
                 WHERE  trade_id = TO_NUMBER(:TRADE_ID)
                 AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                 AND user_id = a.user_id
                 AND partition_id=a.PARTITION_ID)