INSERT INTO TF_B_TRADE_RES_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID,USER_ID_A,RES_TYPE_CODE,RES_CODE,IMSI,KI,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,USER_ID,USER_ID_A,RES_TYPE_CODE,RES_CODE,IMSI,KI,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_RES a
 WHERE USER_ID IN ( SELECT DISTINCT user_id
                     FROM tf_b_trade_res
                     WHERE trade_id = TO_NUMBER(:TRADE_ID)
                     AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2)))
 AND NOT EXISTS (SELECT 1 FROM tf_b_trade_res_bak c
                   WHERE  c.trade_id = TO_NUMBER(:TRADE_ID)
                   AND c.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                   AND c.user_id = a.user_id
                   AND c.res_code = a.res_code
                   AND c.res_type_code = a.res_type_code)