UPDATE TF_F_USER_COMP_RELA
   SET END_DATE = TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),UPDATE_TIME=SYSDATE
  WHERE COMP_USER_ID = TO_NUMBER(:COMP_USER_ID)
    AND USER_ID = TO_NUMBER(:USER_ID)
    AND COMP_PRODUCT_ID = :COMP_PRODUCT_ID
    AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
    AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
    AND START_DATE = TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')