UPDATE tf_b_resapply_main
   SET CLOSE_DATE = sysdate, CLOSE_STAFF_ID = :CLOSE_STAFF_ID,CLOSE_TYPE_CODE = :CLOSE_TYPE_CODE,AUDIT_TYPE_CODE=:AUDIT_TYPE_CODE      
 WHERE APPLY_NO = :APPLY_NO
   AND APPLY_BATCH_ID = :APPLY_BATCH_ID