UPDATE tf_b_resapply_main
   SET CANCEL_REASON = :CANCEL_REASON,AUDIT_TYPE_CODE=:AUDIT_TYPE_CODE,AUDIT_STATE_CODE = :AUDIT_STATE_CODE,RSRV_DATE1 = sysdate,RSRV_STR2 = :STAFF_ID   
 WHERE APPLY_NO = :APPLY_NO
   AND APPLY_BATCH_ID = :APPLY_BATCH_ID