SELECT PARTITION_ID, TO_CHAR(USER_ID) USER_ID, TO_CHAR(USER_ID_A) USER_ID_A,
       TO_CHAR(ACCT_ID) ACCT_ID, TO_CHAR(ACCT_ID_B) ACCT_ID_B, PAYITEM_CODE,
       START_CYCLE_ID, END_CYCLE_ID, BIND_TYPE, LIMIT_TYPE, TO_CHAR(LIMIT) LIMIT,
       COMPLEMENT_TAG, RSRV_STR1, RSRV_STR2, RSRV_STR3, A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       TO_CHAR(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TF_F_USER_SPECIALEPAY A
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND TO_CHAR(SYSDATE, 'yyyymmdd') BETWEEN A.START_CYCLE_ID AND A.END_CYCLE_ID
