INSERT INTO tf_b_trade_discnt(
TRADE_ID, ACCEPT_MONTH, USER_ID, USER_ID_A, PACKAGE_ID, PRODUCT_ID, DISCNT_CODE, SPEC_TAG, RELATION_TYPE_CODE, INST_ID, CAMPN_ID, START_DATE, END_DATE, MODIFY_TAG, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK )
values(
 TO_NUMBER(:TRADE_ID),
 TO_NUMBER (SUBSTR (:TRADE_ID,5,2)),
 TO_NUMBER(:USER_ID),
 TO_NUMBER (:USER_ID_A),
 :PACKAGE_ID,
 :PRODUCT_ID,
 TO_NUMBER(:DISCNT_CODE),
 :SPEC_TAG,
 :RELATION_TYPE_CODE,
 TO_NUMBER (:INST_ID),
 to_number(:CAMPN_ID),
 TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
 TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
 :MODIFY_TAG,
 SYSDATE,
 :UPDATE_STAFF_ID,
 :UPDATE_DEPART_ID,
 :REMARK)