INSERT INTO TF_B_TRADE_ATTR(TRADE_ID, ACCEPT_MONTH, USER_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE, END_DATE, MODIFY_TAG, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3) 
select  TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID,5,2)),USER_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE, to_date(:ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss'), '1', TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'), :UPDATE_STAFF_ID, :UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
from tf_f_user_attr t
where USER_ID = TO_NUMBER(:USER_ID)
and PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
and t.end_date>sysdate
AND INST_ID IN(select INST_ID
     FROM TF_F_USER_DISCNT 
     WHERE USER_ID = TO_NUMBER(:USER_ID)
       AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
       AND END_DATE > SYSDATE
       AND product_id in (SELECT PRODUCT_ID FROM TD_B_PRODUCT T WHERE T.PRODUCT_MODE='12'))