UPDATE TF_B_TRADE_WIDENET
   SET STAND_ADDRESS = :STAND_ADDRESS,
       STAND_ADDRESS_CODE = :STAND_ADDRESS_CODE, REMARK = :REMARK
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND USER_ID = :USER_ID
   AND SYSDATE < END_DATE