SELECT A.USER_ID,
       A.RELATION_TRADE_ID, 
       TO_CHAR(A.ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE, 
       B.RES_CODE, 
       B.GOODS_NAME, 
       B.GOODS_STATE,
       TO_CHAR(B.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, 
       B.UPDATE_STAFF_ID,
       B.RSRV_STR5 CHECK_TRADE_ID,
       B.REMARK
  FROM TF_F_USER_SALE_ACTIVE A, TF_F_USER_SALE_GOODS B, TD_S_COMMPARA C
 WHERE A.USER_ID = B.USER_ID
   AND A.RELATION_TRADE_ID = B.RELATION_TRADE_ID
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(A.USER_ID, 10000)
   AND B.USER_ID = TO_NUMBER(:USER_ID)
   AND B.PARTITION_ID = MOD(A.USER_ID, 10000)
   AND LENGTH(B.RES_CODE) > 5
   AND DECODE(C.PARA_CODE2,'C',A.CAMPN_TYPE,'P',A.PRODUCT_ID,'K',A.PACKAGE_ID,A.CAMPN_TYPE) = C.PARA_CODE1
   AND C.PARAM_ATTR = '2018'
   AND C.PARAM_CODE = 'MODIFY_SALE_ACTIVE_IMEI'
   AND B.GOODS_STATE = '0'
