SELECT PARTITION_ID, TO_CHAR(USER_ID) USER_ID, SERIAL_NUMBER_B, PRODUCT_ID,
       PACKAGE_ID, TO_CHAR(INST_ID) INST_ID, TO_CHAR(CAMPN_ID) CAMPN_ID,
       GOODS_ID, GOODS_NAME, TO_CHAR(GOODS_NUM) GOODS_NUM,
       TO_CHAR(GOODS_VALUE) GOODS_VALUE, GOODS_STATE, RES_TAG, RES_TYPE_CODE,
       RES_ID, RES_CODE, DEVICE_MODEL_CODE, DEVICE_MODEL,
       TO_CHAR(DEVICE_COST) DEVICE_COST, DEVICE_BRAND_CODE, DEVICE_BRAND,
       DESTROY_FLAG, GIFT_MODE, POST_NAME, POST_ADDRESS, POST_CODE,
       TO_CHAR(RELATION_TRADE_ID) RELATION_TRADE_ID,
       TO_CHAR(ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       TO_CHAR(CANCEL_DATE, 'yyyy-mm-dd hh24:mi:ss') CANCEL_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2,
       RSRV_NUM3, TO_CHAR(RSRV_NUM4) RSRV_NUM4, TO_CHAR(RSRV_NUM5) RSRV_NUM5,
       RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6,
       RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3, RSRV_TAG1,
       RSRV_TAG2, RSRV_TAG3
  FROM TF_F_USER_SALE_GOODS
 WHERE 1 = 1
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND RES_CODE = :RES_CODE
   AND GOODS_STATE = :GOODS_STATE