UPDATE TF_F_USER_SALE_GOODS A
   SET A.RES_CODE        = :RES_CODE,
       A.UPDATE_TIME     = TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
       A.UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       A.REMARK          = :REMARK
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(A.USER_ID, 10000)
   AND A.RELATION_TRADE_ID = TO_NUMBER(:RELATION_TRADE_ID)
   AND RES_CODE = :OLD_RES_CODE
   AND A.GOODS_STATE = '0'