UPDATE TF_F_USER_SALE_GOODS
   SET GOODS_STATE = '1', CANCEL_DATE = TO_DATE(:CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS'), UPDATE_TIME = SYSDATE,
       UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID, REMARK = :REMARK
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = :USER_ID
   AND PRODUCT_ID = :PRODUCT_ID
   AND PACKAGE_ID = :PACKAGE_ID
   AND GOODS_ID = :GOODS_ID
   AND RES_CODE = :RES_CODE
   AND ACCEPT_DATE = TO_DATE(:ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS')