UPDATE TF_F_USER_SALE_GOODS
   SET CANCEL_DATE        = TO_DATE(:CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       REMARK =:REMARK,
       UPDATE_TIME     =SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID