INSERT INTO tf_b_QUEUETRADE
VALUES
(TO_NUMBER(:TRADE_ID),
 :SERIAL_NUMBER,
 to_date(:ACCEPT_DATE,'YYYY-MM-DD HH24:MI:SS'), 
 to_date(:START_TIME ,'YYYY-MM-DD HH24:MI:SS'),
 to_date(:FINISH_TIME ,'YYYY-MM-DD HH24:MI:SS'),
 :RSRV_STR1,
 :RSRV_STR2,
 :RSRV_STR3
)