SELECT USER_ID,
       SERIAL_NUMBER,
       PRODUCT_ID,
       PACKAGE_ID,
       CAMPN_TYPE,
       START_DATE,
       MONTHS,
       TOTAL_CONSUME,
       END_DATE,
       UPDATE_TIME,
       RELATION_TRADE_ID,
       REMARK
  FROM TF_F_USER_SALEACTIVE_CONSUME
  WHERE USER_ID=:USER_ID
    AND PRODUCT_ID = :PRODUCT_ID
    AND PACKAGE_ID = :PACKAGE_ID
    AND (TO_CHAR(UPDATE_TIME,'YYYYMM')=TO_CHAR(SYSDATE - INTERVAL '1' MONTH,'YYYYMM')
    AND RSRV_STR1='1' OR  TO_CHAR(UPDATE_TIME,'YYYYMM')=TO_CHAR(SYSDATE,'YYYYMM') AND RSRV_STR1='0')
    AND END_DATE >=SYSDATE