SELECT B.PARTITION_ID,B.CUST_ID,B.IS_REAL_NAME,A.USER_ID,A.SERIAL_NUMBER 
FROM TF_F_USER A, TF_F_CUSTOMER B 
WHERE 1=1 
AND B.CUST_ID = A.CUST_ID 
AND B.PARTITION_ID = MOD(A.CUST_ID,10000) 
AND A.REMOVE_TAG='0' 
AND A.SERIAL_NUMBER =:SERIAL_NUMBER