SELECT A.PRODUCTID PRODUCT_ID,	C.PROVINCEID PROVINCE_ID
FROM TI_R_PRODUCT_DOWN A, TI_R_PRODUCT_PILOT_DOWN C
WHERE 1 = 1
AND A.RECORDID = C.RECORDID
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND (A.MODELTYPE IS NULL OR A.MODELTYPE='0')