SELECT USER_ID,MSISDN,TIP_INFO,END_DATE
  FROM TI_BI_USERBRANDTRANS
 WHERE MSISDN = :SERIAL_NUMBER
   AND END_DATE =
       (SELECT MAX(END_DATE)
          FROM TI_BI_USERBRANDTRANS
         WHERE MSISDN = :SERIAL_NUMBER
           AND SYSDATE < TO_DATE(END_DATE, 'YYYY-MM-DD'))
   AND ROWNUM < 2