SELECT A.PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       A.SERVICE_MODE,
       A.SERIAL_NUMBER,
       A.PROCESS_INFO,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_STR1,
       B.RSRV_STR23 RSRV_STR2,
       B.PRODUCT_NAME RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_STR6,
       A.RSRV_STR7,
       A.RSRV_STR8,
       A.RSRV_STR9,
       A.RSRV_STR10,
       TO_CHAR(A.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(A.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(A.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       A.PROCESS_TAG,
       A.STAFF_ID,
       A.DEPART_ID,
       TO_CHAR(TRUNC(A.START_DATE - 1), 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(B.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       A.REMARK
  FROM TF_F_USER_OTHERSERV A,TF_F_USER_SALE_ACTIVE B
 WHERE A.SERVICE_MODE=:SERVICE_MODE
   AND A.SERIAL_NUMBER=:SERIAL_NUMBER
   AND B.SERIAL_NUMBER=:SERIAL_NUMBER
   AND (B.CAMPN_TYPE=:CAMPN_TYPE OR :CAMPN_TYPE IS NULL)
   AND A.SERIAL_NUMBER=B.SERIAL_NUMBER
   AND A.USER_ID=B.USER_ID