SELECT SUM(T.RSRV_NUM2) RSRV_NUM2
  FROM TF_F_USER_OTHERSERV T
 WHERE T.USER_ID = :USER_ID
   AND T.RSRV_NUM1 = :RSRV_STR1
   AND T.SERVICE_MODE = 'FG'
   AND T.PROCESS_TAG = '0'
   AND START_DATE <= SYSDATE
   AND END_DATE > SYSDATE
