UPDATE tf_f_user_otherserv
   SET PROCESS_INFO=:PROCESS_INFO,RSRV_NUM1=TO_NUMBER(:RSRV_NUM1),RSRV_STR1=:RSRV_STR1,RSRV_STR2=:RSRV_STR2,RSRV_STR3=:RSRV_STR3,RSRV_STR4=:RSRV_STR4,RSRV_STR5=:RSRV_STR5,RSRV_STR6=:RSRV_STR6,RSRV_STR7=:RSRV_STR7,RSRV_STR8=:RSRV_STR8,RSRV_STR9=:RSRV_STR9,RSRV_STR10=:RSRV_STR10 
 WHERE user_id=TO_NUMBER(:USER_ID)
   AND partition_id=mod(TO_NUMBER(:USER_ID),10000)
   AND service_mode='0A'
   AND process_tag='0'
   AND end_date>sysdate