--IS_CACHE=Y
SELECT PARAM_SELECT_ID,PARAM_SELECT_ID || '|' ||PARAM_MIN_VALUE || '|' ||PARAM_MAX_VALUE PARAM_TEXT,PARAM_MIN_VALUE,PARAM_MAX_VALUE,PARAM_DESC FROM TD_S_MENU_ATTR_TMPPARA WHERE 1=1
 AND MENU_TMPL_ID = :MENU_TMPL_ID
 AND PARAM_NAME = :PARAM_NAME