--IS_CACHE=Y
SELECT a.REQ_SEQ,a.SERV_ID,a.PROD_CODE,a.SERV_NAME,a.SERV_TYPE,a.SERV_SUB_TYPE,a.PRODUCT_CODE,a.SERV_AREA_TYPE,a.SERV_STATE,a.ACCESS_MODE,
a.ACCESS_TAG,a.INNOVATION_ID,a.CO_PROV_LIST,a.STATE,a.HOST_PROV,a.START_DATE,a.BIZ_TYPE,a.SERV_DESC,a.INTRO_URL,a.ACCESS_TYPE_LIST,a.FEE_INFO,
a.PKI_LIST,a.SUP_TEL,a.PRO_COUNT,a.KB_SUPPORT,a.COOP_PLAN,a.OTHER_FILE,a.SERV_CODE,a.BIZ_CODE,a.SHORT_SVC_CODE,a.SERV_KIND,a.SERV_PRICE,a.SERV_RATE_TYPE,
a.BIZ_PRI,a.SERV_ATTR,a.PROV_URL,a.PER_CHARGE,a.MAX_DAY,a.MAX_MONTH,a.END_TIME,a.START_TIME,a.IS_SIGN,a.SIGN_EN,a.SIGN_CN,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,
a.REMARK,a.RSRV_NUM3,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_STR6,a.RSRV_STR7,a.RSRV_STR8,a.RSRV_DATE1,
a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3,a.PRORATE,a.DEFAULT_SIGN,a.OUT_TYPE,a.APP_TYPE,a.COP_SERV,
a.COP_PRODUCT,a.PRODUCT_PART,a.INDUSTRY,a.SERV_INTRO,a.CUST_SERV_PLAN,a.TECH_PLAN,a.SMS_CORP_CODE,a.SMS_SERV_CODE,a.MMS_CORP_CODE,a.MMS_SERV_CODE,
a.WAP_CORP_CODE,a.SUBMIT_DATE,a.SERV_FAQ,a.CUST_SERV_DOCU,a.UPDATE_TIME,a.TRAIL_STAFF_ID,a.TRAIL_TIME,a.OUT_STATE,a.TRAIL_STATE,a.SERV_COP_TYPE,
a.BUSI_PLAN,a.USAGE_DESC,a.INCREMENT_SERV_TYPE,a.INFO_CODE,a.INFO_VALUE,a.START_TIME4,a.START_TIME2,a.END_TIME2,a.START_TIME3,
a.END_TIME4,a.END_TIME3,a.BASE_SERV_CODE,a.BASE_SERV_CODE_PROP,a.RESULT_INFO,a.SYN_STATE,a.LIMIT_AMOUNT,a.AUTH_MODE,a.OPR_SEQ,a.BIZ_PF_CODE,a.SERVICE_ID
FROM TF_COP_SERVICE a 
WHERE a.biz_code=:BIZ_CODE AND a.state='40'