INSERT INTO tf_f_user_infochange(partition_id,user_id,trade_type_code,trade_id,product_id,brand_code,brand_no,serial_number,imsi,vip_id,start_date,end_date,update_time,update_staff_id,update_depart_id,remark,rsrv_num1,rsrv_num2,rsrv_num3,rsrv_num4,rsrv_num5,rsrv_str1,rsrv_str2,rsrv_str3,rsrv_str4,rsrv_str5,rsrv_date1,rsrv_date2,rsrv_date3,rsrv_tag1,rsrv_tag2,rsrv_tag3)
 VALUES(:PARTITION_ID,
 TO_NUMBER(:USER_ID),
 :TRADE_TYPE_CODE,
 :TRADE_ID,
 :PRODUCT_ID,
 :BRAND_CODE,
 :BRAND_NO,
 :SERIAL_NUMBER,
 :IMSI,:VIP_ID,
 TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
 TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
 :UPDATE_TIME,
 :UPDATE_STAFF_ID,
 :UPDATE_DEPART_ID,
 :REMARK,  
 :RSRV_NUM1,
 :RSRV_NUM2,
 :RSRV_NUM3,
 :RSRV_NUM4,
 :RSRV_NUM5,
 :RSRV_STR1,
 :RSRV_STR2,
 :RSRV_STR3,
 :RSRV_STR4,
 :RSRV_STR5,
 :RSRV_DATE1,
 :RSRV_DATE2,
 :RSRV_DATE3,
 :RSRV_TAG1,
 :RSRV_TAG2,
 :RSRV_TAG3)