UPDATE /*+ INDEX(T IDX_TF_F_USER_INFOCHG_UID) */ TF_F_USER_INFOCHANGE T
   SET START_DATE = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss'),UPDATE_TIME = SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND PRODUCT_ID = :PRODUCT_ID
   AND TRADE_TYPE_CODE = '500'
   AND END_DATE > START_DATE AND START_DATE < SYSDATE AND END_DATE > SYSDATE