select 
A.ORDER_ID,     
A.PARENT_ID,   
A.SUB_ID,       
A.EXPTYPE,      
A.SERIALNUMBER, 
A.PROVINCE,     
A.OPRTIME,      
A.EXPREASON,    
A.EXPDESC,      
A.PROCSTATU,             
B.IBSYSID,     
B.ORDID,       
B.INFO_TYPE,   
B.CUSTNAME,       
B.CITY,        
B.CUSTADDR,    
B.CONTACT_TEL, 
B.POSTCODE,    
B.TIME_REQ 
from TI_B_SCORE_EXPORDER A, TI_B_SCORE_EXPORDER_PLUS B
where A.ORDER_ID = B.ORDID
and (A.ORDER_ID = :ORDER_ID OR :ORDER_ID IS NULL)
and (A.PARENT_ID = :PARENT_ID OR :PARENT_ID IS NULL)
and (A.SUB_ID = :SUB_ID OR :SUB_ID IS NULL)
and (A.EXPTYPE = :EXPTYPE OR :EXPTYPE IS NULL)
and (A.SERIALNUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)