SELECT U.USER_ID USER_ID, U.SERIAL_NUMBER SERIAL_NUMBER
  FROM TF_F_USER_OCS U
 WHERE U.SERIAL_NUMBER = :SERIAL_NUMBER
   AND U.USER_ID = TO_NUMBER(:USER_ID)
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE