SELECT PARTITION_ID,
       USER_ID,
       SERIAL_NUMBER,
       EPARCHY_CODE,
       CITY_CODE,
       MONITOR_TYPE,
       USER_TYPE_CODE,
       STATUS,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       BIZ_TYPE,
       MONITOR_FLAG,
       MONITOR_RULE_CODE,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_DATE1,
       RSRV_DATE2,
       RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_F_USER_OCS
 WHERE PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)
   AND USER_ID=TO_NUMBER(:USER_ID)
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') >= START_DATE
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') <= END_DATE
   AND END_DATE > START_DATE
