--IS_CACHE=Y
insert into code_code (DAO_NAME, TAB_NAME, SQL_REF, SQL_STMT, VERSION, CREA_STAFF, CREA_DATE, UPD_STAFF, UPD_DATE, CVSID, IS_CACHE, TTL, REL_TAB_NAME, REL_PARAM_NAME)
values ('', 'TF_B_TRADEFEE_OTHERFEE', 'SEL_BY_TRADEID', 'SELECT TRADE_ID, ACCEPT_MONTH, OPER_TYPE, USER_ID, ACCT_ID, USER_ID2,
       ACCT_ID2, OPER_FEE, ACTION_CODE, PAYMENT_ID, IN_DEPOSIT_CODE,
       OUT_DEPOSIT_CODE, IS_ACCTDAY, START_DATE, END_DATE, UPDATE_TIME,
       UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
       RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8,
       RSRV_STR9, RSRV_STR10
  FROM TF_B_TRADEFEE_OTHERFEE
WHERE TRADE_ID = :TRADE_ID
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))', '1', 'RC', to_date('13-05-2014 16:22:12', 'dd-mm-yyyy hh24:mi:ss'), 'RC', to_date('13-05-2014 16:22:12', 'dd-mm-yyyy hh24:mi:ss'), '', 'N', '86400', 'TF_B_TRADEFEE_OTHERFEE', 'TRADE_ID');

