SELECT A.ATTR_VALUE ATTR_VALUE FROM TF_B_EOP_ATTR A ,TF_B_TRADE_EXT B
WHERE A.IBSYSID=B.ATTR_VALUE
AND A.ATTR_CODE='CUSTOMCONTACTPHONE'
AND A.RECORD_NUM='0'
AND B.TRADE_ID=:TRADE_ID
ORDER BY A.GROUP_SEQ
