SELECT COUNT(1) RECORDCOUNT
   FROM TF_B_TRADE
  WHERE PRODUCT_ID = :PRODUCT_ID
    AND CUST_ID = TO_NUMBER(:CUST_ID)
    AND NOT EXISTS (SELECT 1
           FROM DUAL T
          WHERE :TRADE_TYPE_CODE = '4690'
            AND :IN_MODE_CODE = '6')
    AND NOT EXISTS (SELECT 1
           FROM DUAL T
          WHERE :TRADE_TYPE_CODE IN (2990,3010,3080))
    AND ROWNUM < 2