SELECT A.*
  FROM TI_B_ENCARD_PKG_EXCLUDE A
 WHERE A.EX_SP_CODE = :SP_CODE
   AND A.EX_OPER_CODE = :BIZ_CODE
UNION
SELECT A.*
  FROM TI_B_ENCARD_PKG_EXCLUDE A
 WHERE A.SP_CODE = :SP_CODE
   AND A.OPER_CODE = :BIZ_CODE
