SELECT A.BP_SERIAL_NO TYPE_CODE,
       A.BP_NAME PARAM_NAME,
       A.MATCH_CODE PARAM_CODE,
       A.SMS_SCRIPT PARA_CODE23
       FROM TF_SM_BI_BUSIMANAGE A
WHERE SALE_ACT_TYPE=:SALE_ACT_TYPE AND SYSDATE BETWEEN START_TIME AND END_TIME