SELECT S.USER_ID, S.ACCT_ID, S.ACCT_ID_B, S.PAYITEM_CODE, S.BIND_TYPE,
       S.LIMIT_TYPE, S.LIMIT, S.COMPLEMENT_TAG, S.END_CYCLE_ID, S.START_CYCLE_ID,
       A.SERIAL_NUMBER_B, A.USER_ID_A
  FROM TF_F_RELATION_UU A, TF_F_USER_SPECIALEPAY S
 WHERE A.RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND S.USER_ID = A.USER_ID_B
   AND S.PARTITION_ID = MOD(A.USER_ID_B, 10000)
   AND SYSDATE BETWEEN TO_DATE(S.START_CYCLE_ID, 'yyyyMMDD') AND
       TO_DATE(S.END_CYCLE_ID, 'yyyyMMDD')
   AND A.USER_ID_A = :USER_ID
   AND S.USER_ID_A = :USER_ID
