SELECT '' TRADE_ID,'' SUBSCRIBE_ID,'' BPM_ID, TRADE_TYPE_CODE,'' IN_MODE_CODE,-1 PRIORITY,'' SUBSCRIBE_STATE,'' NEXT_DEAL_TAG,-1 PRODUCT_ID,'' BRAND_CODE,''  USER_ID,''  CUST_ID,'' ACCT_ID,SERIAL_NUMBER,CUST_NAME,'' ACCEPT_DATE,
  -1 ACCEPT_MONTH,'' TRADE_STAFF_ID,'' TRADE_DEPART_ID,'' TRADE_CITY_CODE,'' TRADE_EPARCHY_CODE,
  '' TERM_IP,'' EPARCHY_CODE,'' CITY_CODE,'' OLCOM_TAG,'' EXEC_TIME,
  '' FINISH_DATE,'' OPER_FEE,'' FOREGIFT,
  '' ADVANCE_PAY,'' INVOICE_NO,'' FEE_STATE,'' FEE_TIME,'' FEE_STAFF_ID,
  '' CANCEL_TAG,'' CANCEL_DATE,'' CANCEL_STAFF_ID,'' CANCEL_DEPART_ID,'' CANCEL_CITY_CODE,
  '' CANCEL_EPARCHY_CODE,'' PROCESS_TAG_SET,count(*) RSRV_STR1,f_sys_getcodename('trade_type_code',trade_type_code,:TRADE_EPARCHY_CODE,NULL) RSRV_STR2, '' RSRV_STR3,'0' RSRV_STR4,'' RSRV_STR5, '' RSRV_STR6,'' RSRV_STR7,'' RSRV_STR8,
  '' RSRV_STR9,'' RSRV_STR10,'' REMARK
  FROM TF_BH_TRADE
where ACCEPT_DATE>= trunc(to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss'))
  AND ACCEPT_DATE<trunc(to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'))+1
  AND (cancel_tag='0' OR cancel_tag='2' OR ((cancel_tag='1')AND(EXEC_TIME>FINISH_DATE)))
  and trade_type_code<>1170 
  and trade_type_code<>1171
  AND SERIAL_NUMBER IS NOT NULL
 group by SERIAL_NUMBER,TRADE_TYPE_CODE,cust_name
  having count(*)>:MODIFY_TAG