SELECT COUNT(USER_ID) CARRIER_CODE
FROM TF_F_CUST_VIP
WHERE USER_ID=:USER_ID AND REMOVE_TAG='0'
AND  NOT EXISTS ( 
SELECT 1 FROM TD_O_CREDIT_COMMPARA  
WHERE PARACODE LIKE 'NOT_REFRESH_VIP%' AND VIP_TYPE_CODE LIKE PARA1 AND VIP_ID LIKE PARA2)