UPDATE TF_F_USER_PLATSVC A
   SET A.RSRV_STR8  = :RSRV_STR8
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND BIZ_STATE_CODE = 'A'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE