INSERT INTO TI_B_USER_DISCNT_ATTR (SYNC_SEQUENCE, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3) 
Select  TO_NUMBER(:SYNC_SEQUENCE), '2',to_number(:TRADE_ID), PARTITION_ID, USER_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
From tf_f_user_attr   
 Where  user_id =to_number(:USER_ID)
 AND partition_id =  mod(to_number(:USER_ID),10000)
 And inst_type = 'D' 
 AND inst_id = TO_NUMBER(:INST_ID)
	 AND end_date > SYSDATE
	 AND start_date < SYSDATE