SELECT T.PACKAGE_ID,
       T.PRODUCT_ID,
       T.ELEMENT_TYPE_CODE,
       T.ELEMENT_ID,
       T.DEFAULT_TAG,
       T.FORCE_TAG,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD') END_DATE,
       TO_CHAR(T.UPDATE_TIME, 'YYYY-MM-DD') UPDATE_TIME,
       T.UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID,
       T.REMARK
  FROM TF_F_USER_GRP_PACKAGE T
 WHERE 1 = 1
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = :USER_ID
   AND T.ELEMENT_TYPE_CODE = 'D'
   AND T.ELEMENT_ID = :ELEMENT_ID
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE