UPDATE TF_F_ACCOUNT_ACCTDAY T
   SET T.END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD hh24:mi:ss'),
       T.UPDATE_TIME      = SYSDATE,
       T.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE T.ACCT_ID = :ACCT_ID
   AND T.PARTITION_ID = MOD(TO_NUMBER(:ACCT_ID), 10000)
   AND T.END_DATE > TO_DATE(:END_DATE, 'YYYY-MM-DD hh24:mi:ss')