SELECT COUNT(*) RECORDCOUNT
  FROM (SELECT COUNT(*), A.USER_ID
          FROM TF_F_RELATION_UU U, TF_F_USER_DISCNT A, TD_S_COMMPARA B
         WHERE U.USER_ID_A = :USER_ID_A
           AND U.END_DATE > SYSDATE
           AND U.PARTITION_ID = A.PARTITION_ID
           AND U.USER_ID_B = A.USER_ID
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
		   AND A.END_DATE > TRUNC(LAST_DAY(SYSDATE))+ 1 + 1/24/60/60
           AND TO_CHAR(A.DISCNT_CODE) = B.PARAM_CODE
           AND B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_ATTR = 9018
           AND B.END_DATE > SYSDATE
         GROUP BY A.USER_ID)