INSERT INTO TF_B_GONET_REG_LOG (KF_TRADE_ID,ACCEPT_MONTH,EVENT_ID,START_TIME,END_TIME,MS_ID,CHNL_ID,
QUERY_STATUS,QUERY_START_TIME,QUERY_END_TIME) values 
(:KF_TRADE_ID,:ACCEPT_MONTH,:EVENT_ID,TO_DATE(:START_TIME, 'YYYY-MM-DD HH24:MI:SS'),TO_DATE(:END_TIME, 'YYYY-MM-DD HH24:MI:SS'),:MS_ID,:CHNL_ID,
:QUERY_STATUS,TO_DATE(:QUERY_START_TIME, 'YYYY-MM-DD HH24:MI:SS'),TO_DATE(:QUERY_END_TIME, 'YYYY-MM-DD HH24:MI:SS'))