SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_RELATION_UU B, TF_F_RELATION_UU C
 WHERE B.RELATION_TYPE_CODE = '47'
   AND B.USER_ID_A = C.USER_ID_A
   AND C.RELATION_TYPE_CODE = '47'
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
   AND B.ROLE_CODE_B = '2'
   AND C.ROLE_CODE_B = '1'
   AND C.USER_ID_B = :USER_ID
   AND C.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND EXISTS
 (SELECT 1
          FROM TF_F_USER_DISCNT A
         WHERE A.END_DATE > TRUNC(LAST_DAY(SYSDATE) + 1) - 1 / (60 * 60 * 24)
           AND A.USER_ID = B.USER_ID_B
           AND A.PARTITION_ID = B.PARTITION_ID
           AND A.DISCNT_CODE IN
               (SELECT S.PARA_CODE1
                  FROM TD_S_COMMPARA S
                 WHERE S.SUBSYS_CODE = 'CSM'
                   AND S.PARAM_ATTR = '532'
                   AND S.PARAM_CODE = '605'
                   AND SYSDATE BETWEEN S.START_DATE AND S.END_DATE
                   AND (S.EPARCHY_CODE = '0898' OR S.EPARCHY_CODE = 'ZZZZ')))
