--IS_CACHE=Y
SELECT EPARCHY_CODE,PARA_ATTR,PARA_CODE1,PARA_CODE2,PARA_NAME,PARA_VALUE1,PARA_VALUE2,
  		 PARA_VALUE3,PARA_VALUE4,PARA_VALUE5,PARA_VALUE6,PARA_VALUE7,PARA_VALUE8,PARA_VALUE9,
  		 PARA_VALUE10,PARA_VALUE11,PARA_VALUE12,RDVALUE1,RDVALUE2,REMARK,UPDATE_TIME,
  		 UPDATE_STAFF_ID, UPDATE_DEPART_ID  RECORDCOUNT 
  FROM TD_M_ASSIGNPARA
 WHERE PARA_ATTR=8510
   AND PARA_CODE1='TD_LTE_SIM_CARDTYPE_CODE'
   AND PARA_CODE2= TO_CHAR(:PARA_CODE2)
   AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')