SELECT A.LOG_ID, A.START_VALUE TERMINAL_ID,
F_RES_GETCODENAME('card_kind_code', A.RES_KIND_CODE, 'ZZZZ', '') TERMINAL_TYPE_NAME,
F_RES_GETCODENAME('terminal_brand', A.BRAND_CODE, '', '') BRAND_NAME,
F_RES_GETCODENAME('terminal_model', A.RES_KIND_CODE, A.BRAND_CODE, A.MODEL_CODE) MODEL_NAME
FROM TF_B_TERMINAL_ASSIGN_DETAIL A
WHERE A.LOG_ID=:LOG_ID