DELETE FROM TF_A_PAYRELATION
 WHERE user_id = TO_NUMBER(:USER_ID)
   AND partition_id = mod(TO_NUMBER(:USER_ID),10000)
  AND ((START_CYCLE_ID > END_CYCLE_ID)
  OR( START_CYCLE_ID=END_CYCLE_ID AND START_CYCLE_ID=TO_CHAR(SYSDATE,'YYYYMMDD')))