SELECT A.ACCT_ID,
       A.PAY_NAME,
       A.OPEN_DATE,
       A.PAY_MODE_CODE,
       A.EPARCHY_CODE,
       A.RSRV_STR5,
       A.RSRV_STR8,
       A.RSRV_STR9,
       A.RSRV_STR10
  FROM TF_A_PAYRELATION B, TF_F_ACCOUNT A
 WHERE B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND B.USER_ID = TO_NUMBER(:USER_ID)
   AND B.DEFAULT_TAG = '1'
   AND B.ACT_TAG = '1'
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN B.START_CYCLE_ID AND
       B.END_CYCLE_ID
   AND B.ACCT_ID = A.ACCT_ID
   AND A.PARTITION_ID = MOD(B.ACCT_ID, 10000)
   AND A.REMOVE_TAG = '0'
   AND A.RSRV_STR5 = 'UnifyPayProduct'