SELECT A.USER_ID,
       A.ACCT_ID,
       A.PAYITEM_CODE,
       B.PAY_NAME,
       B.PAY_MODE_CODE,
       B.BANK_CODE,
       B.BANK_ACCT_NO
  FROM TF_A_PAYRELATION A, TF_F_ACCOUNT B
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.DEFAULT_TAG = '1'
   AND A.ACT_TAG = '1'
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN A.START_CYCLE_ID AND A.END_CYCLE_ID
   AND B.ACCT_ID = A.ACCT_ID
   AND B.PARTITION_ID = MOD(TO_NUMBER(A.ACCT_ID), 10000)