SELECT T.ACCT_ID
  FROM TF_A_PAYRELATION T, TF_F_ACCOUNT A, TF_F_CUST_GROUP GRP
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   and T.PARTITION_ID = mod(TO_NUMBER(:USER_ID), 10000)
   AND T.ACT_TAG = '1'
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN START_CYCLE_ID AND END_CYCLE_ID
   AND A.ACCT_ID = T.ACCT_ID
   AND A.PARTITION_ID = mod(TO_NUMBER(T.ACCT_ID), 10000)
   AND A.REMOVE_TAG = '0'
   AND A.CUST_ID = GRP.CUST_ID
   AND GRP.REMOVE_TAG = '0'
   AND ROWNUM < 2