SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(ACCT_ID) ACCT_ID,
       PAYITEM_CODE,
       ACCT_PRIORITY,
       USER_PRIORITY,
       BIND_TYPE,
       START_CYCLE_ID,
       END_CYCLE_ID,
       DEFAULT_TAG,
       ACT_TAG,
       LIMIT_TYPE,
       TO_CHAR(LIMIT) LIMIT,
       COMPLEMENT_TAG,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TF_A_PAYRELATION A
 WHERE ACCT_ID = TO_NUMBER(:ACCT_ID)
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN START_CYCLE_ID AND END_CYCLE_ID
   AND ACT_TAG = '1'
   AND EXISTS (SELECT 1
          FROM TF_F_USER
         WHERE PARTITION_ID = MOD(TO_NUMBER(A.USER_ID), 10000)
           AND USER_ID = A.USER_ID
           AND REMOVE_TAG = '0')
