UPDATE tf_b_resapply_detail
   SET 
   AUDIT_NO = :AUDIT_NO, AUDIT_TYPE_CODE = :AUDIT_TYPE_CODE, 
   AUDIT_STAFF_ID=:AUDIT_STAFF_ID,AUDIT_DATE = sysdate, 
   AUDIT_REMARK=:AUDIT_REMARK, AUDIT_DEPART_ID = :AUDIT_DEPART_ID
   WHERE APPLY_NO=:APPLY_NO
   AND APPLY_BATCH_ID = :APPLY_BATCH_ID
   AND (:APPLY_DETAIL_NO is null or APPLY_DETAIL_NO = :APPLY_DETAIL_NO)