SELECT t.INST_ID,t.SERVICE_ID,t.SERIAL_NUMBER,t.SERV_CODE,t.BIZ_ATTR 
FROM TF_F_USER_GRP_PLATSVC t
WHERE t.BIZ_CODE=:BIZ_CODE AND t.GROUP_ID=:GROUP_ID
 AND t.biz_in_code=:BIZ_IN_CODE 
AND SYSDATE BETWEEN t.START_DATE AND t.END_DATE