SELECT T.USER_ID, T.SERVICE_ID, T.SERIAL_NUMBER, T.GROUP_ID, T.BIZ_ATTR
FROM TF_F_USER_GRP_PLATSVC t
WHERE t.SERV_CODE=:SERV_CODE AND t.GROUP_ID=:GROUP_ID
AND SYSDATE BETWEEN t.START_DATE AND t.END_DATE