SELECT UP.PRODUCT_ID,
       U.USER_ID,
	   U.EPARCHY_CODE,
       P.SERVICE_ID SERVICE_ID,
	   P.OPER_STATE,
       P.PLAT_SYNC_STATE,
       P.BIZ_CODE,
       P.BIZ_NAME,
       P.SERV_CODE,
       P.BIZ_ATTR
  FROM TF_F_USER_GRP_PLATSVC P,
       TF_F_USER             U,
       TF_F_USER_PRODUCT     UP
 WHERE P.USER_ID = U.USER_ID
   AND U.PARTITION_ID = MOD(P.USER_ID, 10000)
   AND U.USER_ID = UP.USER_ID
   AND U.PARTITION_ID = UP.PARTITION_ID
   AND U.REMOVE_TAG = '0'
   AND P.BIZ_ATTR IN ('1', '2')
   AND P.GROUP_ID = :GROUP_ID
   AND SYSDATE BETWEEN P.START_DATE AND P.END_DATE

