INSERT INTO TF_B_TWO_CHECK
  (TRADE_ID, OUTER_TRADE_ID, SERIAL_NUMBER, REVERT_DATE, REMARK, RSRV_STR1, EXEC_FLAG)
VALUES
  (:TRADE_ID, '999999999999', :SERIAL_NUMBER, SYSDATE, :REMARK, :RERV_STR1, :EXEC_FLAG)