SELECT to_char(TRADE_ID) TRADE_ID,CANCEL_TAG,STATE_CODE,TRADE_DEPART_ID,TRADE_STAFF_ID,to_char(ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,TRADE_TYPE_CODE,ERROR_NUM,to_char(AUDIT_DATE,'yyyy-mm-dd hh24:mi:ss') AUDIT_DATE,AUDIT_STAFF_ID,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,AUDITING_STAFF_ID,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8
  FROM TS_A_AUDITRESULT_DETAIL
 WHERE TRADE_DEPART_ID = :TRADE_DEPART_ID
   AND TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND trunc(ACCEPT_DATE)=trunc(TO_DATE(:AUDIT_DATE,'YYYY-MM-DD HH24:MI:SS'))
   AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE