UPDATE TS_A_AUDITRESULT_DETAIL
   SET STATE_CODE = :STATE_CODE,
       AUDITING_STAFF_ID = :AUDITING_STAFF_ID,
       END_DATE = to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'),
      ERROR_NUM = :ERROR_NUM
 WHERE TRADE_ID = to_number(:TRADE_ID)      
   AND CANCEL_TAG = :CANCEL_TAG