--IS_CACHE=Y
SELECT a.ELEMENT_ID,a.BIZ_CODE,a.TRANS_CODE,a.INTF_CODE,a.COMMUNICATE,a.LIMIT_TAG,a.TRANSFER,a.ELEMENT_NAME,a.ACTIONCODE,
 b.CHAN_ID,b.ELEMENT_NO,b.SPEC_DEAL_TAG,b.PROCESS_ID,b.PROCESS_METHOD,b.ELEMENT_VALUE,b.START_DATE,b.END_DATE,b.OPER_STAFF_ID,b.OPER_TIME
 FROM TD_M_TRANS_PARAM a, TD_M_CHAN_PARAM b WHERE 1 = 1
 AND a.ELEMENT_ID = :ELEMENT_ID
 AND a.BIZ_CODE = :BIZ_CODE
 AND a.TRANS_CODE = :TRANS_CODE
 AND a.COMMUNICATE = :COMMUNICATE
 AND a.LIMIT_TAG = :LIMIT_TAG
 AND a.TRANSFER = :TRANSFER
 and a.INTF_CODE = :INTF_CODE
 and a.ELEMENT_NAME like '%' || :ELEMENT_NAME || '%'
 and a.ACTIONCODE = :ACTIONCODE
 and b.CHAN_ID =:CHAN_ID
 and b.ELEMENT_NO =:ELEMENT_NO
 and b.SPEC_DEAL_TAG = :SPEC_DEAL_TAG
 and b.PROCESS_ID = :PROCESS_ID
 and b.PROCESS_METHOD =:PROCESS_METHOD
 and b.ELEMENT_VALUE = :ELEMENT_VALUE
 and a.ELEMENT_ID = b.ELEMENT_ID
 order by a.ELEMENT_ID