SELECT A.PACKAGECODE PACKAGE_CODE, B.MATERIALCODE MATERIAL_CODE
FROM TI_R_PACKAGE_DOWN A, TI_R_PACKAGE_DETAIL_DOWN B
WHERE 1 = 1
AND A.RECORDID = B.RECORDID
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')