SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       B.TRADE_TYPE_CODE,
       C.TRADE_TYPE,
       A.SCORE,
       A.SCORE_CHANGED,
       TO_CHAR(NVL(A.VALUE_CHANGED / 100, 0)) VALUE_CHANGED,
       A.REMARK,
       B.SERIAL_NUMBER SERIAL_NUMBER_B,
       B.CUST_NAME,
       B.ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       DECODE(B.CANCEL_TAG,
              '0','未返销',
              '1','被返销',
              '2','返销') CANCEL_TAG,
       B.CANCEL_DATE,
       B.CANCEL_STAFF_ID,
       B.RSRV_STR5,
       B.RSRV_STR6,
       B.RSRV_STR7
  FROM TF_B_TRADE_SCORE A, TF_B_TRADE B, TD_S_TRADETYPE C
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = C.TRADE_TYPE_CODE
   AND A.TRADE_ID = :TRADE_ID
   AND A.SCORE = :SCORE
   AND A.SCORE_CHANGED = :SCORE_CHANGED
UNION ALL
SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       B.TRADE_TYPE_CODE,
       C.TRADE_TYPE,
       A.SCORE,
       A.SCORE_CHANGED,
       TO_CHAR(NVL(A.VALUE_CHANGED / 100, 0)) VALUE_CHANGED,
       A.REMARK,
       B.SERIAL_NUMBER SERIAL_NUMBER_B,
       B.CUST_NAME,
       B.ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       DECODE(B.CANCEL_TAG,
              '0','未返销',
              '1','被返销',
              '2','返销') CANCEL_TAG,
       B.CANCEL_DATE,
       B.CANCEL_STAFF_ID,
       B.RSRV_STR5,
       B.RSRV_STR6,
       B.RSRV_STR7
  FROM TF_B_TRADE_SCORE A, TF_BH_TRADE B, TD_S_TRADETYPE C
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = C.TRADE_TYPE_CODE
   AND A.TRADE_ID = :TRADE_ID
   AND A.SCORE = :SCORE
   AND A.SCORE_CHANGED = :SCORE_CHANGED