SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       A.SCORE,
       A.SCORE_CHANGED,
       A.VALUE_CHANGED,
       A.REMARK,
       A.RSRV_STR6       RSRV_STR3,
       A.RSRV_STR8       ORDER_ID,
       A.RSRV_STR9       SUBSCRIBE_ID,
       A.RSRV_STR10      OPRT,
       B.TRADE_TYPE_CODE,
       B.CUST_NAME,
       B.ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       B.CANCEL_TAG,
       B.CANCEL_DATE,
       B.CANCEL_STAFF_ID,
       B.RSRV_STR6,
       B.RSRV_STR7,
       B.RSRV_STR8,
       B.RSRV_STR9,
       B.RSRV_STR10,
       B.SUBSCRIBE_STATE
  FROM TF_B_TRADE_SCORE A, TF_B_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.RSRV_STR8 = :ORDER_ID
   AND A.RSRV_STR6 = :RSRV_STR6
   AND (A.RSRV_STR9 = :SUBSCRIBE_ID OR :SUBSCRIBE_ID IS NULL)
UNION ALL
SELECT B.TRADE_ID,
       A.SERIAL_NUMBER,
       A.SCORE,
       A.SCORE_CHANGED,
       A.VALUE_CHANGED,
       A.REMARK,
       A.RSRV_STR6       RSRV_STR3,
       A.RSRV_STR8       ORDER_ID,
       A.RSRV_STR9       SUBSCRIBE_ID,
       A.RSRV_STR10      OPRT,
       B.TRADE_TYPE_CODE,
       B.CUST_NAME,
       B.ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       B.CANCEL_TAG,
       B.CANCEL_DATE,
       B.CANCEL_STAFF_ID,
       B.RSRV_STR6,
       B.RSRV_STR7,
       B.RSRV_STR8,
       B.RSRV_STR9,
       B.RSRV_STR10,
       B.SUBSCRIBE_STATE
  FROM TF_B_TRADE_SCORE A, TF_BH_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND B.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.RSRV_STR8 = :ORDER_ID
   AND A.RSRV_STR6 = :RSRV_STR6
   AND (A.RSRV_STR9 = :SUBSCRIBE_ID OR :SUBSCRIBE_ID IS NULL)
