--IS_CACHE=Y
SELECT DISCNT_TYPE_CODE, DISCNT_CODE, START_DATE, END_DATE
  FROM TD_B_DTYPE_DISCNT A
 WHERE A.DISCNT_TYPE_CODE = :DISCNT_TYPE_CODE
   AND SYSDATE BETWEEN START_DATE AND END_DATE
   AND A.DISCNT_CODE IN
       (SELECT T.PARA_CODE1 FROM TD_S_COMMPARA T WHERE T.PARAM_ATTR = '2048')