INSERT INTO TF_F_TOPSET_ONLINE
  (USER_ID,
   PARTITION_ID,
   IN_TIME,
   IS_BACK,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID)
VALUES
  (:USER_ID,
   MOD(:USER_ID, 10000),
   TO_DATE(:IN_TIME,'YYYY-MM-DD HH24:MI:SS'),
   :IS_BACK,
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID)