SELECT 
       A.CITY_CODE, --市县
       SERIAL_NUMBER, --服务号码
       TO_CHAR(OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE, --开户时间
       (SELECT B.CUST_NAME  FROM TF_F_CUSTOMER B  WHERE B.CUST_ID = A.CUST_ID) CUST_NAME, --客户姓名
       A.DEVELOP_STAFF_ID --开户员工工号
  FROM TF_F_USER A
 WHERE A.REMOVE_TAG = '0'
   AND A.CITY_CODE = :CITY_CODE
   AND A.OPEN_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
       TO_DATE(:END_DATE, 'yyyy-mm-dd') + 1
   AND A.DEVELOP_STAFF_ID BETWEEN :START_STAFF_ID AND :END_STAFF_ID