SELECT
  EOMS_ID, EPARCHY_NAME, CITY_NAME, COUNTY_NAME, CUST_NAME, CUST_ADDR, CUST_MANAGER_NAME, CUST_MANAGER_PHONE, CUST_SIGN,
  DIRECT_TYPE, COVER_TYPE, PORT_TYPE, OPEN_DAYS, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1,
  RSRV_STR2, RSRV_STR3
FROM TF_B_EOP_EOMS_INFO T
WHERE (eparchy_name = :EPARCHY_NAME OR :EPARCHY_NAME IS NULL) AND CUST_ADDR LIKE '%' || :CUST_ADDR || '%'