SELECT
  S.IBSYSID,S.GROUP_ID, S.CUST_NAME, N.ACCEPT_STAFF_ID, T.PRODUCT_NAME, S.ACCEPT_TIME
FROM TF_B_EOP_PRODUCT T, TF_B_EWE N, TF_B_EOP_SUBSCRIBE S
WHERE T.IBSYSID = N.BI_SN AND S.IBSYSID = N.BI_SN AND
      (N.ACCEPT_STAFF_ID = :STAFF_ID OR :STAFF_ID IS NULL) AND
      (S.ACCEPT_TIME > TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS') OR :START_DATE IS NULL) AND
      (S.ACCEPT_TIME < TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS') OR :END_DATE IS NULL) AND
      (T.PRODUCT_ID = :PRODUCT_ID OR :PRODUCT_ID IS NULL) AND
      (S.GROUP_ID = :GROUP_ID OR :GROUP_ID IS NULL) AND
      T.PRODUCT_ID IN ('5080', '5081', '5083', '5093') AND
      (S.IBSYSID = :IBSYSID OR :IBSYSID IS NULL) AND S.BPM_TEMPLET_ID = 'EDIRECTLINEOPENNEW'