--IS_CACHE=Y
SELECT PACKAGE_ID, PACKAGE_NAME, ACTIVE_FLAG, DISCNT_CODE, UPDATE_STAFF_ID,
       UPDATE_DEPART_ID, UPDATE_TIME, RSRV_STR1, RSRV_STR2, TAG_SET,
       RSRV_DATE1, PRODUCT_ID_A, PACKAGE_ID_A, EPARCHY_CODE, START_DATE,
       END_DATE, CAMPN_ID_A, DEVICE_MODEL_CODE, DEVICE_MODEL
  FROM TD_B_MOBILE_DISCNT
 WHERE PACKAGE_ID = :PACKAGE_ID
   AND CAMPN_ID_A = :CAMPN_ID_A
   AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN START_DATE AND END_DATE