UPDATE TF_F_USER_ACCTDAY T
   SET T.END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD'),
       T.UPDATE_TIME      = TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD'),
       T.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE T.USER_ID = :USER_ID
   AND T.PARTITION_ID = :PARTITION_ID
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE