INSERT INTO TD_B_RECOMMPARA  VALUES (
  :RECOMM_SOURCE,
  :RECOMM_TYPE,
  to_number(:PRODUCT_ID),
  to_number(:PACKAGE_ID),
  to_number(:ELEMENT_ID),
  :ELEMENT_NAME,
  :RECOMM_CONTENT,
  to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss'),
  to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'),
  :EPARCHY_CODE,
  :REMARK,
  :UPDATE_STAFF_ID,
  :UPDATE_DEPART_ID,
  to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'),
  :PARA_CODE1,
  :PARA_CODE2,
  :PARA_CODE3,
  :PARA_CODE4,
  :PARA_CODE5,
  :PARA_CODE6,
  :PARA_CODE7,
  :PARA_CODE8,
  :PARA_CODE9,
  :PARA_CODE10
)