UPDATE TF_F_GRP_PRODUCT_MANAGER
   SET GROUP_ID = :GROUP_ID,
       GROUP_MGR_SN = :GROUP_MGR_SN, 
       PRODUCT_MGR_SN = :PRODUCT_MGR_SN,
       PRODUCT_ID = :PRODUCT_ID,
       PRODUCT_MGR_NAME = :PRODUCT_MGR_NAME,
       DEPART_NAME = :DEPART_NAME,
       EMAIL = :EMAIL,
       UPDATE_DATE = to_date(:UPDATE_DATE, 'yyyy-mm-dd hh24:mi:ss'),
       REMARK = :REMARK,
       RSRV_STR1 = :RSRV_STR1,
       RSRV_STR2 = :RSRV_STR2,
       RSRV_STR3 = :RSRV_STR3,
       RSRV_STR4 = :RSRV_STR4,
       RSRV_STR5=:RSRV_STR5
 WHERE GROUP_ID = :GROUP_ID 
   and PRODUCT_MGR_SN = :PRODUCT_MGR_SN 
   and VALID_TAG='0' 