--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.TRADE_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
  FROM  UCR_ACT1.tf_b_score_tradelog@DBLNK_ACTDBN1  A, TD_M_DEPART D
 WHERE A.svc_type_code = '340'
   AND TRUNC(A.TRADE_DATE) BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE)
   AND A.CANCEL_TAG = '0'
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.OPERATE_DEPART_ID = D.DEPART_ID
   AND ROWNUM < 2