SELECT 'B' TAB_TYPE,B.ATTR_VALUE PRODUCTNO,B.SUB_IBSYSID,A.GROUP_ID, A.*,b.record_num
   FROM TF_B_EOP_SUBSCRIBE A, TF_B_EOP_ATTR B
  WHERE A.BPM_TEMPLET_ID = 'ERESOURCECONFIRMZHZG'
    AND A.DEAL_STATE = '0'
    AND A.IBSYSID = B.IBSYSID
    AND A.BUSI_CODE= :PRODUCT_ID
    AND B.NODE_ID ='apply'
    AND B.ATTR_CODE = 'PRODUCTNO'    
    AND B.ATTR_VALUE = :PRODUCTNO
	AND A.GROUP_ID = :GROUP_ID
 union all
 SELECT 'BH' TAB_TYPE,B.ATTR_VALUE PRODUCTNO,B.SUB_IBSYSID,A.GROUP_ID, A.*,b.record_num
   FROM TF_BH_EOP_SUBSCRIBE A, TF_BH_EOP_ATTR B
  WHERE A.BPM_TEMPLET_ID = 'ERESOURCECONFIRMZHZG'
    AND A.DEAL_STATE = '9'
    AND A.IBSYSID = B.IBSYSID
    AND A.BUSI_CODE= :PRODUCT_ID
    AND B.NODE_ID ='apply'
    AND B.ATTR_CODE = 'PRODUCTNO'    
    AND B.ATTR_VALUE = :PRODUCTNO
	AND A.GROUP_ID = :GROUP_ID
  
