SELECT TASK_ID,PARTITION_ID,ORDER_ID,TASK_CHAN_ID,EXE_CHAN_ID,SEND_OBJECT,CONTENT,TITLE,APPENDIX,ACCEPT_MONTH,EXE_DIR,EXE_METHOD,
EXE_TYPE,EPARCHY_CODE,EXEC_COUNT,EXEC_CURRENT,EXPIRE_TIME,START_TIME,FINISH_TIME,TASK_PRI,RSP_TIME,TASK_STATUS,
RSP_CODE,RSP_DESC,REMARK,PREVALUE1,PREVALUE2,PREVALUE3,PREVALUE4,PREVALUE5,MONTH,DAY
 FROM TF_B_ORDER WHERE 1=1 
 AND TASK_STATUS = :TASK_STATUS 
 AND EXE_METHOD = :EXE_METHOD 
 AND (PARTITION_ID between :THREAD_NUM*100 and (:THREAD_NUM+1)*100-1)