SELECT TO_CHAR(A.TRADE_ID) TRADE_ID,
       A.ACCEPT_MONTH,
       TO_CHAR(A.USER_ID) USER_ID,
       A.SERVICE_ID,
       A.SERIAL_NUMBER,
       A.INFO_CODE,
       A.INFO_VALUE,
       to_number(B.PARA_CODE2) DISCNT_CODE,
       C.OPER_CODE,
       C.START_DATE,
       C.END_DATE,
       C.SP_CODE,
       C.BIZ_CODE,
       C.BIZ_TYPE_CODE,
       C.UPDATE_TIME,
       C.UPDATE_STAFF_ID,
       C.UPDATE_DEPART_ID,
       C.ORG_DOMAIN,
       D.EPARCHY_CODE,
       B.PARA_CODE10
  FROM TF_B_TRADE_PLATSVC_ATTR A,
       TD_S_COMMPARA           B,
       TF_B_TRADE_PLATSVC      C,
       TF_B_TRADE              D
 WHERE A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 3700
   AND A.SERVICE_ID = TO_NUMBER(B.PARAM_CODE)
   AND A.INFO_CODE = B.PARA_CODE3
   AND A.INFO_VALUE = B.PARA_CODE1
   AND C.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.TRADE_ID = C.TRADE_ID
   AND A.SERVICE_ID = C.SERVICE_ID
   AND A.USER_ID = C.USER_ID
   AND A.SERIAL_NUMBER = C.SERIAL_NUMBER
   AND D.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.TRADE_ID = D.TRADE_ID
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND C.USER_ID = :USER_ID
   AND C.SERVICE_ID = :SERVICE_ID
   AND C.OPER_CODE = :OPER_CODE
   AND A.INFO_CODE = :INFO_CODE
   AND A.INFO_VALUE = :INFO_VALUE
