SELECT A.SERIAL_NUMBER,
       A.IN_MODE_CODE,
       A.REMARK,
       A.START_DATE,
       A.END_DATE,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_DATE1,
       A.RSRV_DATE2,
       A.RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3
  FROM TF_F_ROAM_AREA_LOG A
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
 AND A.START_DATE > TRUNC(SYSDATE,'DD')
 AND A.END_DATE > SYSDATE