SELECT T.BUSIFORM_OPER_TYPE,
       T.IN_MODE_CODE,
       T.BPM_TEMPLET_ID,
       T.REMARK,
       T.BUSI_TYPE,
       T.BUSI_CODE,
       T.VALID_TAG,
       T.CONDITION_ID,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_BUSI_SPEC_RELE T
 WHERE T.BUSI_TYPE = :BUSI_TYPE
   AND T.BUSI_CODE = :BUSI_CODE
   AND T.BPM_TEMPLET_ID = :BPM_TEMPLET_ID
   AND T.IN_MODE_CODE = :IN_MODE_CODE
   AND T.VALID_TAG = :VALID_TAG