--IS_CACHE=Y
SELECT trans.TRANS_CODE,trans.TRANS_NAME FROM TD_S_TRANSLIST trans, TD_S_ECHANNAL_STAFF staff,TD_S_CHANNAL_BIZLIST chnl WHERE 1 = 1
 AND staff.CHAN_ID = chnl.CHAN_ID
 AND trans.TRANS_CODE = chnl.TRANS_CODE
 AND staff.ID_VALUE = :STAFF_ID
 AND chnl.BIZ_CODE = :BIZ_CODE