UPDATE TF_F_USER_ELEMENT 
SET END_DATE =TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')  
WHERE USER_ID = :USER_ID
AND   PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
AND   PRODUCT_ID = :PRODUCT_ID
AND   PACKAGE_ID = :PACKAGE_ID
AND   ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
AND   ELEMENT_ID = :ELEMENT_ID
AND   SYSDATE < END_DATE+0