SELECT D.SCORE_DEDUCT_ID,
       D.ID_TYPE,
       D.SCORE_TYPE_CODE,
       D.SCORE_VALUE,
       D.YEAR_ID,
       D.START_CYCLE_ID,
       D.END_CYCLE_ID,
       D.SCORE_VALUE_FEE,
       D.DEPOSIT_TAG,
       D.DEPOSIT_RATE,
       D.PAYMENT_ID,
       D.DEDUCT_LOW,
       D.SCORE_LOW,
       D.MONTHS,
       T.ENABLE_TAG,
       TO_CHAR(T.START_ABSOLUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') START_ABSOLUTE_DATE,
       T.START_OFFSET,
       T.START_UNIT,
       T.END_ENABLE_TAG,
       TO_CHAR(T.END_ABSOLUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') END_ABSOLUTE_DATE,
       T.END_OFFSET,
       T.END_UNIT,
       T.PACKAGE_ID,
       T.ELEMENT_TYPE_CODE,
       T.ELEMENT_ID,
       T.DEFAULT_TAG,
       T.FORCE_TAG,
       TO_CHAR(T.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(T.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       T.ITEM_INDEX,
       TO_CHAR(T.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       T.UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID,
       T.CANCEL_TAG,
       T.REMARK
  FROM TD_B_PACKAGE_ELEMENT T, TD_B_SALE_SCORE D
 WHERE 1 = 1
   AND T.ELEMENT_ID = D.SCORE_DEDUCT_ID
   AND T.ELEMENT_TYPE_CODE = 'J'
   AND T.PACKAGE_ID = :PACKAGE_ID
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
   AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
