
insert into TF_R_RESOURCE_INTER
  (LOG_ID, SUB_LOG_ID, PARTITION_ID, INVENT_ORG_ID, EPARCHY_CODE, CITY_CODE, OPER_DEPART_ID, OPER_STAFF_ID, STOCK_ID_O, STOCK_ID_N, OPER_TAG, COST_CEN_ID, OPER_TIME, ASSIGN_TIME, RES_TYPE_CODE, RES_KIND_CODE, CAPACITY_TYPE_CODE, DEVICE_TYPE_CODE, DEVICE_FACTORY_CODE, DEVICE_MODEL_CODE, DEVICE_COLOR_CODE, ORDER_ID, SUPPLY_ID, SUPPLY_TYPE, AGENCY_ID, PROCUREMENT_TYPE, RES_STATE, OPER_TYPE_CODE, CAMPN_ID, PRODUCT_ID, SALE_TYPE_CODE, OPER_NUM, DC_TAG, CANCEL_SUB_LOG_ID, CANCEL_DATE, REMARK, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3)
  select LOG_ID, SUB_LOG_ID, PARTITION_ID, INVENT_ORG_ID, EPARCHY_CODE, CITY_CODE, OPER_DEPART_ID, OPER_STAFF_ID, STOCK_ID_O, STOCK_ID_N, OPER_TAG, COST_CEN_ID, OPER_TIME, SYSDATE, RES_TYPE_CODE, RES_KIND_CODE, CAPACITY_TYPE_CODE, DEVICE_TYPE_CODE, DEVICE_FACTORY_CODE, DEVICE_MODEL_CODE, DEVICE_COLOR_CODE, ORDER_ID, SUPPLY_ID, SUPPLY_TYPE, AGENCY_ID, PROCUREMENT_TYPE, RES_STATE, OPER_TYPE_CODE, CAMPN_ID, PRODUCT_ID, SALE_TYPE_CODE, OPER_NUM, DC_TAG, CANCEL_SUB_LOG_ID, CANCEL_DATE, REMARK, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3
    from TF_B_TRADE_RESOURCE_INTER
   WHERE SUB_LOG_ID = :SUB_LOG_ID
     AND PARTITION_ID = TO_NUMBER(SUBSTR(:SUB_LOG_ID, 5, 2))
     AND DC_TAG = :DC_TAG
     AND NOT EXISTS
   (SELECT 1
            FROM TF_R_RESOURCE_INTER
           WHERE SUB_LOG_ID = :SUB_LOG_ID
             AND DC_TAG = :DC_TAG
             AND PARTITION_ID = TO_NUMBER(SUBSTR(:SUB_LOG_ID, 5, 2)))