INSERT INTO TF_F_USER_SALE_DEPOSIT(PARTITION_ID, USER_ID, USER_ID_A, PRODUCT_ID, PACKAGE_ID, DISCNT_GIFT_ID, A_DISCNT_CODE, DEPOSIT_TYPE, INST_ID, CAMPN_ID, MONTHS, LIMIT_MONEY, PAY_MODE, FEE, PAYMENT_ID, IN_DEPOSIT_CODE, OUT_DEPOSIT_CODE, RELATION_TRADE_ID, START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3) 
Select mod(TO_NUMBER(user_id), 10000),  to_char(USER_ID) USER_ID, to_char(USER_ID_A) USER_ID_A, PRODUCT_ID, PACKAGE_ID, DISCNT_GIFT_ID, A_DISCNT_CODE, DEPOSIT_TYPE, to_char(INST_ID) INST_ID, to_char(CAMPN_ID) CAMPN_ID, MONTHS, to_char(LIMIT_MONEY) LIMIT_MONEY, PAY_MODE, to_char(FEE) FEE, PAYMENT_ID, IN_DEPOSIT_CODE, OUT_DEPOSIT_CODE, to_char(RELATION_TRADE_ID) RELATION_TRADE_ID, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, to_char(RSRV_NUM4) RSRV_NUM4, to_char(RSRV_NUM5) RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1, to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2, to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
  FROM tf_b_trade_sale_deposit  a
  Where trade_id = TO_NUMBER(:TRADE_ID)
   AND modify_tag = '0'    
   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))  
   AND NOT EXISTS (SELECT 1 FROM TF_F_USER_SALE_DEPOSIT  b
                    WHERE user_id = a.user_id
                      AND partition_id = MOD(TO_NUMBER( a.user_id), 10000)
                      And a.PRODUCT_ID =b.PRODUCT_ID
                      And a.PACKAGE_ID =b.PACKAGE_ID
                      AND end_date > start_date
                      AND end_date > a.start_date)