SELECT TO_CHAR(B.TRADE_ID) TRADE_ID, A.SERIAL_NUMBER, B.TRADE_TYPE_CODE,
       A.SCORE, A.SCORE_CHANGED,
       TO_CHAR(NVL(A.VALUE_CHANGED / 100, 0)) VALUE_CHANGED, A.REMARK,
       B.SERIAL_NUMBER SERIAL_NUMBER_B, B.CUST_NAME,
       TO_CHAR(B.ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       DECODE(B.CANCEL_TAG, '0', '未返销', '1', '被返销', '2', '返销') CANCEL_TAG,
       B.CANCEL_DATE, B.CANCEL_STAFF_ID, B.RSRV_STR5, B.RSRV_STR6, B.RSRV_STR7 ,B.RSRV_STR10
  FROM TF_B_TRADE_SCORE A, TF_B_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND A.ACCEPT_MONTH = B.ACCEPT_MONTH
   AND A.SERIAL_NUMBER = B.SERIAL_NUMBER
   AND (B.EPARCHY_CODE = :EPARCHY_CODE OR B.EPARCHY_CODE IS NULL)
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND B.ACCEPT_DATE + 0 BETWEEN TO_DATE(:ACCEPT_START, 'YYYY-MM-DD') AND
       TO_DATE(:ACCEPT_END, 'YYYY-MM-DD') + 1
UNION ALL
SELECT TO_CHAR(B.TRADE_ID) TRADE_ID, A.SERIAL_NUMBER, B.TRADE_TYPE_CODE,
        A.SCORE, A.SCORE_CHANGED,
       TO_CHAR(NVL(A.VALUE_CHANGED / 100, 0)) VALUE_CHANGED, A.REMARK,
       B.SERIAL_NUMBER SERIAL_NUMBER_B, B.CUST_NAME,
       TO_CHAR(B.ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       B.TRADE_STAFF_ID,
       DECODE(B.CANCEL_TAG, '0', '未返销', '1', '被返销', '2', '返销') CANCEL_TAG,
       B.CANCEL_DATE, B.CANCEL_STAFF_ID, B.RSRV_STR5, B.RSRV_STR6, B.RSRV_STR7 ,B.RSRV_STR10
  FROM TF_B_TRADE_SCORE A, TF_BH_TRADE B
 WHERE A.TRADE_ID = B.TRADE_ID
   AND A.ACCEPT_MONTH = B.ACCEPT_MONTH
   AND A.SERIAL_NUMBER = B.SERIAL_NUMBER
   AND (B.EPARCHY_CODE = :EPARCHY_CODE OR B.EPARCHY_CODE IS NULL)
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND B.ACCEPT_DATE + 0 BETWEEN TO_DATE(:ACCEPT_START, 'YYYY-MM-DD') AND
       TO_DATE(:ACCEPT_END, 'YYYY-MM-DD') + 1
 ORDER BY TRADE_ID DESC