   SELECT F.FEE
   FROM 
   TF_B_TRADE_SVC T, TF_B_TRADEFEE_SUB F
      where  T.USER_ID = :USER_ID
   AND T.TRADE_ID = F.TRADE_ID
   AND T.ACCEPT_MONTH = F.ACCEPT_MONTH
   AND T.SERVICE_ID = '19'
   AND T.MODIFY_TAG = '0'
   AND T.TRADE_ID = :TRADE_IDA
   AND T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_IDA, 5, 2))