update TD_B_INFORMATION_PROMPT
SET 
UPDATE_TIME = SYSDATE,
UPDATE_STAFF_ID=:UPDATE_STAFF_ID,
UPDATE_DEPART_ID=:UPDATE_DEPART_ID,
VALID_TAG=:VALID_TAG,
END_DATE = SYSDATE
WHERE 
TRADE_TYPE_CODE = :TRADE_TYPE_CODE 
AND  CONSTRAINT_TYPE_CODE = :CONSTRAINT_TYPE_CODE
AND  CONSTRAINT_ATTR = :CONSTRAINT_ATTR
AND  VALID_TAG='0'OR VALID_TAG='2'