update TD_B_INFORMATION_PROMPT
  set TRADE_TYPE_CODE = :TRADE_TYPE_CODE,
      TRADE_TYPE =:TRADE_TYPE,
      CONSTRAINT_TYPE_CODE =:CONSTRAINT_TYPE_CODE,
      CONSTRAINT_TYPE =:CONSTRAINT_TYPE,
      CONSTRAINT_ATTR =:CONSTRAINT_ATTR,
      CONSTRAINT_ATTR_NAME=:CONSTRAINT_ATTR_NAME,
      UPDATE_STAFF_ID=:UPDATE_STAFF_ID,
      UPDATE_DEPART_ID= :UPDATE_DEPART_ID,
      PROMPT_INFO=:PROMPT_INFO,
      VERIFY_STATUE=:VERIFY_STATUE,
      VERIFY_SUGGESTION=:VERIFY_SUGGESTION
      where 
      TRADE_TYPE_CODE = :OLD_TS_TRADE_TYPE_CODE 
    AND CONSTRAINT_TYPE_CODE = :OLD_TS_CONSTRAINT_TYPE_CODE
    AND CONSTRAINT_ATTR = :OLD_TS_CONSTRAINT_ATTR 
    AND VALID_TAG = :OLD_TS_VALID_TAG