Select Partition_Id,
       To_Char(User_Id) User_Id,
       Serial_Number,
       Serial_Number_b,
       Product_Mode,
       Product_Id,
       Product_Name,
       Package_Id,
       Package_Name,
       To_Char(Campn_Id) Campn_Id,
       Campn_Code,
       Campn_Name,
       Campn_Type,
       BOOK_TYPE,
       DEVICE_BRAND_CODE,
       RES_CODE,
       DEVICE_BRAND,
       DEVICE_MODEL_CODE,
       DEVICE_MODEL,
       product_id_b,
       package_id_b,
       ACCEPT_TRADE_ID,
       DEAL_STATE_CODE,
       To_Char(Oper_Fee) Oper_Fee,
       To_Char(Foregift) Foregift,
       To_Char(Advance_Pay) Advance_Pay,
       To_Char(Score_Changed) Score_Changed,
       To_Char(Credit_Value) Credit_Value,
       Months,
       Process_Tag,
       To_Char(Accept_Date, 'yyyy-mm-dd hh24:mi:ss') Accept_Date,
       Trade_Staff_Id,
       To_Char(Relation_Trade_Id) Relation_Trade_Id,
       To_Char(Cancel_Date, 'yyyy-mm-dd hh24:mi:ss') Cancel_Date,
       Cancel_Staff_Id,
       Cancel_Cause,
       To_Char(Start_Date, 'yyyy-mm-dd hh24:mi:ss') Start_Date,
       To_Char(End_Date, 'yyyy-mm-dd hh24:mi:ss') End_Date,
       To_Char(Update_Time, 'yyyy-mm-dd hh24:mi:ss') Update_Time,
       Update_Staff_Id,
       Update_Depart_Id,
       Remark,
       Rsrv_Num1,
       Rsrv_Num2,
       Rsrv_Num3,
       To_Char(Rsrv_Num4) Rsrv_Num4,
       To_Char(Rsrv_Num5) Rsrv_Num5,
       Rsrv_Str1,
       Rsrv_Str2,
       Rsrv_Str3,
       Rsrv_Str4,
       Rsrv_Str5,
       To_Char(Nvl(Rsrv_Date1, Start_Date), 'yyyy-mm-dd hh24:mi:ss') Rsrv_Date1,
       To_Char(Nvl(Rsrv_Date2, End_Date), 'yyyy-mm-dd hh24:mi:ss') Rsrv_Date2,
       To_Char(Rsrv_Date3, 'yyyy-mm-dd hh24:mi:ss') Rsrv_Date3,
       Rsrv_Tag1,
       Rsrv_Tag2,
       Rsrv_Tag3
  From Tf_f_User_Saleactive_Book a
 Where a.Process_Tag = '0'
   And a.DEAL_STATE_CODE = '0'
   And Nvl(a.Rsrv_Date2, a.End_Date) > Sysdate   
   And a.ACCEPT_TRADE_ID = :TRADE_ID
   And a.Serial_Number = REPLACE(:SERIAL_NUMBER,'KD_','')