SELECT S.USER_ID, S.PRODUCT_ID, S.PACKAGE_ID, S.CAMPN_TYPE, S.PRODUCT_ID_B
  FROM TF_F_USER_SALEACTIVE_BOOK S
 WHERE S.USER_ID = :USER_ID
   AND S.PRODUCT_ID IN (SELECT A.PARA_CODE1
                          FROM TD_S_COMMPARA A
                         WHERE A.SUBSYS_CODE = 'CSM'
                           AND A.PARAM_ATTR = '663'
                           AND A.PARAM_CODE = :PRODUCT_ID)
   AND S.DEAL_STATE_CODE = '0'
   AND S.BOOK_TYPE = :BOOK_TYPE