select S.USER_ID, S.PRODUCT_ID, S.PACKAGE_ID, S.CAMPN_TYPE,S.PRODUCT_ID_B
 from TF_F_USER_SALEACTIVE_BOOK S
where S.USER_ID = :USER_ID
  and S.PRODUCT_ID = :PRODUCT_ID
  and S.DEAL_STATE_CODE = '0'
  and s.book_type =:BOOK_TYPE