SELECT 
to_char(TRADE_ID) TRADE_ID, FPDM, to_char(KPSL) KPSL, to_char(KPJE) KPJE, KSHM, JSHM, to_char(BFSL) BFSL,MONTH, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, PARA_VALUE1,
  PARA_VALUE2, PARA_VALUE3, PARA_VALUE4, PARA_VALUE5, PARA_VALUE6, PARA_VALUE7, PARA_VALUE8,
   to_char(PARA_VALUE9) PARA_VALUE9, to_char(PARA_VALUE10) PARA_VALUE10, to_char(PARA_VALUE11) PARA_VALUE11, to_char(PARA_VALUE12) PARA_VALUE12,
    to_char(PARA_VALUE13) PARA_VALUE13, 
   to_char(PARA_VALUE14) PARA_VALUE14, to_char(PARA_VALUE15) PARA_VALUE15, 
   to_char(PARA_VALUE16) PARA_VALUE16, to_char(PARA_VALUE17) PARA_VALUE17, to_char(PARA_VALUE18) PARA_VALUE18, 
   to_char(RDVALUE1,'YYYY-MM-DD HH24:MI:SS') RDVALUE1,
   to_char(RDVALUE2,'YYYY-MM-DD HH24:MI:SS') RDVALUE2, REMARK2
FROM TF_B_TICKET_YB01_LOG_DETAIL WHERE TRADE_ID=:TRADE_ID