INSERT INTO TF_F_PSPT_ADDR_INFO (PSPT_ID, PSPT_ADDR, UPDATE_TIME, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
VALUES (:PSPT_ID,:PSPT_ADDR, :UPDATE_TIME , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) 
