SELECT b.serial_number as RES_COUNT FROM TF_F_CUSTOMER A,TF_F_USER B 
 WHERE A.REMOVE_TAG = '0'
 AND B.REMOVE_TAG = '0'
 AND A.CUST_ID = B.CUST_ID
 AND A.PSPT_TYPE_CODE in ('0','1')
 AND A.IS_REAL_NAME = '1'
 AND A.PSPT_ID =:PSPT_ID