UPDATE TF_F_USER_PSPT
   SET CUST_NAME = :CUST_NAME
 WHERE 1=1
   AND USER_ID IN (
SELECT T.USER_ID USER_ID  
FROM TF_F_USER_PSPT T,TF_F_USER U, TF_F_USER_PRODUCT P, TF_F_CUSTOMER C
WHERE 1=1
   AND T.PSPT_ID = :PSPT_ID
   AND T.CUST_NAME <> :CUST_NAME 
   AND U.CUST_ID = C.CUST_ID
   AND T.CUST_ID = C.CUST_ID   
   AND T.USER_ID = P.USER_ID
   AND T.USER_ID = U.USER_ID
   AND T.CUST_NAME IS NOT NULL
   AND T.PSPT_TYPE_CODE IN ('0', '1','2') 
   AND P.BRAND_CODE IN ('G001','G002','G010','G005','PWLW','IMSG')
)
