SELECT *
  FROM TF_F_USER_PLATSVC T
 WHERE PARTITION_ID = TO_NUMBER(MOD(:USER_ID, 10000))
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND SERVICE_ID = TO_NUMBER(:SERVICE_ID)
   AND T.BIZ_STATE_CODE = 'E'
   AND T.OPER_CODE='07'
   AND T.START_DATE>TO_DATE(:START_DATE,'yyyy-mm-dd')