SELECT T.EC_ID EC_ID, T.APPROVAL_NO APPROVAL_NO
  FROM TF_O_DISCNT_APPLY T, TF_O_DISCNT_APPLY_SUB B, TD_S_COMMPARA A
 WHERE T.EC_ID = :EC_ID
   AND t.APPROVAL_NO = :APPROVAL_NO
   AND T.APPROVAL_RSLT = '1'
   AND T.RSRV_STR1 = '1'
   AND T.OPR_SEQ = B.OPR_SEQ
   AND A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 9013
   AND A.PARAM_CODE = :PARAM_CODE
   AND A.END_DATE > SYSDATE
   AND A.PARA_CODE1 = B.PROD_ID