INSERT INTO TF_B_TRADE_PLATSVC
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   SP_CODE,
   BIZ_CODE,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   PRODUCT_NO,
   ORG_DOMAIN,
   OPER_CODE,
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   SUBSCRIBE_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_STR8,
   RSRV_TAG2)
  SELECT :TRADE_ID,
         SUBSTR(:TRADE_ID, 5, 2),
         :USER_ID,
         '50000000',
         '50000000',
         A.SERVICE_ID,
         :SERIAL_NUMBER,
         A.SP_CODE,
         A.BIZ_CODE,
         A.BIZ_TYPE_CODE,
         'A',
         '',
         A.ORG_DOMAIN,
         '06',
         DECODE(A.BIZ_TYPE_CODE,
              '46',
              '11',
              '78',
              '11',
              '08'),
         B.BILL_TYPE,
         B.PRICE,
         SYSDATE,
         SYSDATE,
         '',
         '',
         '',
         SYSDATE,
         TO_DATE('2050-12-31 23:59:59', 'yyyy-mm-dd hh24:mi:ss'),
         SYSDATE,
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '用户开户默认开通SP业务',
         1,
         'Q',
         DECODE(A.BIZ_TYPE_CODE,'78','0','1')
    FROM TD_B_PLATSVC A,TD_M_SP_BIZ B
   WHERE A.SP_CODE = B.SP_CODE
     AND A.BIZ_CODE = B.BIZ_CODE
     AND A.BIZ_TYPE_CODE||A.BIZ_CODE IN('16+MAILMF','23IIC','72YDCY')
     AND A.BIZ_TYPE_CODE||A.BIZ_CODE NOT IN(SELECT BIZ_TYPE_CODE||BIZ_CODE FROM TF_B_TRADE_PLATSVC WHERE TRADE_ID = :TRADE_ID)