--IS_CACHE=Y
SELECT PARA_CODE1 PRODUCT_ID
  FROM TD_S_COMMPARA
 WHERE SUBSYS_CODE = 'CSM'
   AND PARAM_ATTR = 272
   AND (EPARCHY_CODE = 'ZZZZ' OR EPARCHY_CODE = :EPARCHY_CODE)
   AND PARAM_CODE = :PARAM_CODE
   AND SYSDATE BETWEEN START_DATE AND END_DATE