SELECT
 A.BIPCODE,A.ACTIVITYCODE,A.TRANSIDO,A.ORIGDOMAIN,A.OSNDUNS,A.ROUTEVALUE,A.IDITEMRANGE,A.REQTIME,A.RSPTIME,A.RSPCODE,A.RSPDESC,A.RESULTCODE,A.RESULTINFO,A.RSRV_STR1,A.RSRV_STR2,A.RSRV_STR3,B.REMARK
 FROM UOP_UIF1.TL_BH_IBTRADE A,  UOP_UIF1.TD_B_IBBUSI_SIGN B
WHERE 1=1
 AND (A.BIPCODE=SUBSTR(B.BIPCODE,0,8) or A.BIPCODE=b.bipcode )
 AND A.ACTIVITYCODE= rpad(B.ACTIVITYCODE,8,' ')
 AND (A.IDITEMRANGE = :IDITEMRANGE OR A.ROUTEVALUE = :IDITEMRANGE)  
 AND A.P_MONTH = TO_NUMBER( SUBSTR(:REQTIME,6,2))
 AND ((A.IBDIRTAG = B.DIRECTION) OR (A.IBDIRTAG IS NULL))
 order by a.reqtime