--IS_CACHE=Y
SELECT A.* FROM TD_S_CODE_CONVERT A
 WHERE 1 = 1
 AND A.SMS_CODE_IN LIKE '%' || :SMS_CODE_IN || '%'
 AND A.SMS_CODE_OUT LIKE '%' || :SMS_CODE_OUT || '%'
 AND A.SMS_SERVICE_CODE = :SMS_SERVICE_CODE