INSERT INTO TF_B_TRADE_ACCOUNT_ACCTDAY_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,ACCT_ID,ACCT_DAY,CHG_TYPE,CHG_MODE,CHG_DATE,FIRST_DATE,INST_ID,START_DATE,   END_DATE,   UPDATE_TIME,   UPDATE_STAFF_ID,   UPDATE_DEPART_ID,REMARK,   RSRV_NUM1,   RSRV_NUM2,   RSRV_NUM3,   RSRV_NUM4,   RSRV_NUM5,   RSRV_STR1,   RSRV_STR2,   RSRV_STR3,   RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),   TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,ACCT_ID,ACCT_DAY,CHG_TYPE,CHG_MODE,CHG_DATE,FIRST_DATE,INST_ID,START_DATE,   END_DATE,   UPDATE_TIME,   UPDATE_STAFF_ID,   UPDATE_DEPART_ID,REMARK,   RSRV_NUM1,   RSRV_NUM2,   RSRV_NUM3,   RSRV_NUM4,   RSRV_NUM5,   RSRV_STR1,   RSRV_STR2,   RSRV_STR3,   RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3  
 FROM TF_F_ACCOUNT_ACCTDAY A
 WHERE ACCT_ID IN (
           SELECT ACCT_ID FROM TF_B_TRADE_ACCOUNT_ACCTDAY C WHERE TRADE_ID=:TRADE_ID) 
       AND PARTITION_ID = MOD(TO_NUMBER(A.ACCT_ID), 10000)
       AND NOT EXISTS (SELECT  1
                       FROM    TF_B_TRADE_ACCOUNT_ACCTDAY_BAK B
                       WHERE B.ACCT_ID = A.ACCT_ID
                       AND   B.TRADE_ID =:TRADE_ID
                       AND   B.PARTITION_ID = MOD(TO_NUMBER(A.ACCT_ID), 10000)  
                       )