SELECT  count(1) doning_Total
  FROM TF_B_TRADE A, TF_B_TRADE_DISCNT B
 WHERE B.USER_ID = A.USER_ID
   AND B.TRADE_ID = A.TRADE_ID
   AND B.MODIFY_TAG = :MODIFY_TAG
   AND B.DISCNT_CODE  in  (select A.PARA_CODE2 from TD_S_COMMPARA a WHERE A.PARAM_ATTR = '4502' and a.para_code1 = '99' )
   AND B.USER_ID = :USER_ID