UPDATE TF_F_USER_OTHER
   SET END_DATE    = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME = sysdate,
       UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       REMARK = :REMARK
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND RSRV_VALUE_CODE = :RSRV_VALUE_CODE
   AND (RSRV_STR6 = :RSRV_STR6 OR :RSRV_STR6 IS NULL)
   AND (RSRV_STR7 = :RSRV_STR7 OR :RSRV_STR7 IS NULL)
   AND SYSDATE < END_DATE + 0