SELECT :TASK_ID TASK_ID,
       :SEARCHNUMBER SEARCHNUMBER,
       B.PSPT_TYPE_CODE IDENTITYTYPE,
       B.PSPT_ID USERIDENTITYCODE,
       B.CUST_NAME USERNAME,
decode(b.sex, 'M', '0', 'F', '1', 0) SEX,
       B.PSPT_ADDR CARDADDR,
       B.HOME_ADDRESS ADDR,
       B.CONTACT_PHONE CONTACTNUMBER,
       A.SERIAL_NUMBER USERNUMBER,
 '' PRODUCTTYPE,
 D.IMEI ESN,
 C.IMSI,
TO_CHAR(A.OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') EXT_INFO1,
'' EXT_INFO2,
'' EXT_INFO3,
'' EXT_INFO4,
'' EXT_INFO5,
'' EXT_INFO6
FROM TF_F_USER A, TF_F_CUST_PERSON B, TF_F_USER_RES C, TF_F_USER_IMEI D
WHERE D.IMEI = :SEARCHNUMBER
AND A.USER_ID = D.USER_ID
AND A.PARTITION_ID = MOD(A.USER_ID, 10000)
AND A.REMOVE_TAG = '0'
AND D.END_DATE > SYSDATE
AND B.PARTITION_ID = MOD(A.CUST_ID, 10000)
AND B.CUST_ID = A.CUST_ID
AND C.PARTITION_ID = MOD(A.USER_ID, 10000)
AND C.USER_ID = A.USER_ID
AND C.RES_TYPE_CODE = '1'
AND C.END_DATE > SYSDATE
