SELECT A.STAT_MONTH,
       A.PARTITION_ID,
       A.USER_ID,
       A.BRAND_CODE,
       A.PRODUCT_ID,
       A.EPARCHY_CODE,
       A.CITY_CODE,
       A.USER_TYPE_CODE,
       A.SERIAL_NUMBER,
       A.ACCT_TAG,
       TO_CHAR(A.IN_DATE, 'YYYY-MM-DD HH24:MI:SS') AS IN_DATE,
       TO_CHAR(A.OPEN_DATE, 'YYYY-MM-DD HH24:MI:SS') AS OPEN_DATE,
       A.REMOVE_TAG,
       A.DEVELOP_EPARCHY_CODE,
       A.DEVELOP_DEPART_ID,
       A.DEVELOP_STAFF_ID,
       A.DEVELOP_DATE,
       A.SIM_CARD_NO,
       A.SIM_TYPE_CODE,
       A.CARD_FEE,
       A.BACK_DATE,
       A.BACK_STAFF_ID,
       A.TAG,
       A.REMARK,
       A.VALUEN2 AS VALUEN1
  FROM TS_S_USER_BACK A
 WHERE A.DEVELOP_DEPART_ID = :DEVELOP_DEPART_ID
 AND A.VALUEN2 = :IS_EXTEND_TIME
 AND A.TAG = '0'
ORDER BY TO_NUMBER(A.STAT_MONTH) ASC