UPDATE TL_O_REALTIMEMARKETING
   SET PROCESS_TAG = :PROCESS_TAG,
       EXEC_TIME   = TO_DATE(:EXEC_TIME, 'YYYY-MM-DD HH24:MI:SS'),
	   EXEC_DESC   = :EXEC_DESC,
	   EXEC_RESULT = :EXEC_RESULT
 WHERE REQ_ID = :REQ_ID