SELECT TO_CHAR(A.TRADE_ID) TRADE_ID, A.EPARCHY_CODE
  FROM TF_B_TRADE A
 WHERE A.SUBSCRIBE_TYPE <> '600'
   and A.SERIAL_NUMBER = :SERIAL_NUMBER
   and A.ACCEPT_DATE + 0 > TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   and A.ACCEPT_DATE + 0 < TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
   and A.TRADE_STAFF_ID = :TRADE_STAFF_ID
   and A.CANCEL_TAG = :CANCEL_TAG
   and A.ORDER_ID = TO_NUMBER(:TRADE_ID)
   AND EXISTS (SELECT 1
          FROM TD_S_TRADETYPE B
         WHERE B.TRADE_TYPE_CODE = A.TRADE_TYPE_CODE
           AND B.PRT_TRADEFF_TAG = '1'
           AND A.EPARCHY_CODE = B.EPARCHY_CODE)
   AND (EXISTS (SELECT 1
                  FROM TF_F_CUSTOMER CU
                 WHERE CU.PARTITION_ID = MOD(A.CUST_ID, 10000)
                   AND CU.CUST_ID = A.CUST_ID
                   AND CU.REMOVE_TAG = '0') OR EXISTS
        (SELECT 1
           FROM TF_B_TRADE_CUSTOMER TCU
          WHERE TCU.ACCEPT_MONTH = A.ACCEPT_MONTH
            AND TCU.TRADE_ID = A.TRADE_ID))
   AND NOT EXISTS (SELECT 1
          FROM TF_B_TRADE_CNOTE_INFO C
         WHERE C.TRADE_ID = A.TRADE_ID
           AND C.ACCEPT_MONTH = A.ACCEPT_MONTH)
UNION ALL
SELECT TO_CHAR(A.TRADE_ID) TRADE_ID, A.EPARCHY_CODE
  FROM TF_BH_TRADE A
 WHERE A.SUBSCRIBE_TYPE <> '600'
   and A.SERIAL_NUMBER = :SERIAL_NUMBER
   and A.ACCEPT_DATE + 0 > TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   and A.ACCEPT_DATE + 0 < TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
   and A.TRADE_STAFF_ID = :TRADE_STAFF_ID
   and A.CANCEL_TAG = :CANCEL_TAG
   and A.ORDER_ID = TO_NUMBER(:TRADE_ID)
   AND EXISTS (SELECT 1
          FROM TD_S_TRADETYPE B
         WHERE B.TRADE_TYPE_CODE = A.TRADE_TYPE_CODE
           AND B.PRT_TRADEFF_TAG = '1'
           AND A.EPARCHY_CODE = B.EPARCHY_CODE)
   AND EXISTS (SELECT 1
          FROM TF_F_CUSTOMER CU
         WHERE CU.PARTITION_ID = MOD(A.CUST_ID, 10000)
           AND CU.CUST_ID = A.CUST_ID
           AND CU.REMOVE_TAG = '0')
   AND NOT EXISTS (SELECT 1
          FROM TF_B_TRADE_CNOTE_INFO C
         WHERE C.TRADE_ID = A.TRADE_ID
           AND C.ACCEPT_MONTH = A.ACCEPT_MONTH)
