SELECT COUNT(*) IS_IN3MONTH
  FROM TF_F_USER_PLATSVC C
 WHERE C.USER_ID = :USER_ID
   AND C.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000) 
   AND C.SERVICE_ID in ('55627518','55627768')
   AND (SYSDATE < ADD_MONTHS(C.START_DATE, 3))                                                  