SELECT NVL(MAX(score),0) SCORE,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-DECODE(SIGN(4-TO_NUMBER(TO_CHAR(SYSDATE,'MM'))),1,1,0)) YEAR_ID
FROM tf_f_user_newscore
WHERE id_type='0' and score_type_code='03'
AND year_id=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))-DECODE(SIGN(4-TO_NUMBER(TO_CHAR(SYSDATE,'MM'))),1,1,0)
AND user_id=:USER_ID and partition_id=MOD(:USER_ID,10000)