SELECT A.USER_ID, A.SERVICE_ID, A.BIZ_STATE_CODE
  FROM TF_F_USER_PLATSVC A
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.BIZ_STATE_CODE IN ('A', 'N')
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
