--IS_CACHE=N
SELECT TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.RELATION_TRADE_ID 台账标识,D.DEPART_KIND_CODE 部门类型
FROM TF_F_USER_SALE_ACTIVE A,TD_M_DEPART D
WHERE USER_ID = TO_NUMBER(:USER_ID)
 AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
 AND A.PRODUCT_ID = 66000207
 AND A.END_DATE > SYSDATE
 AND A.UPDATE_DEPART_ID=D.DEPART_ID
 AND (TRUNC(ADD_MONTHS(A.ACCEPT_DATE, 3), 'mm') > SYSDATE OR
             --九月份办理的活动要算四个月
             (TO_CHAR(A.ACCEPT_DATE, 'yyyymm') = '201709' AND
             TRUNC(ADD_MONTHS(A.ACCEPT_DATE, 4), 'mm') > SYSDATE))
 AND ROWNUM < 2