UPDATE TF_B_TRADE_PLATSVC
   SET START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_NUM1  = :RSRV_NUM1
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND SERVICE_ID = :SERVICE_ID
   AND OPER_CODE = :OPER_CODE