insert into tl_b_user_coupons(
ACCEPT_MONTH 
,TICKET_CODE 
,TICKET_VALUE
,TICKET_END_DATE   
,SERIAL_NUMBER
,SPEND_VALUE  
,TICKET_STATE 
,UPDATE_STAFF_ID 
,UPDATE_DEPART_ID
,UPDATE_TIME       
,REMARK
,RSRV_STR1
,RSRV_STR2
,RSRV_STR3
,RSRV_STR4
,RSRV_STR5
)values(
 :ACCEPT_MONTH 
,:TICKET_CODE
,:TICKET_VALUE
,to_date(:TICKET_END_DATE,'yyyy-mm-dd hh24:mi:ss')
,:SERIAL_NUMBER
,:SPEND_VALUE  
,:TICKET_STATE 
,:UPDATE_STAFF_ID 
,:UPDATE_DEPART_ID
,to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss')
,:REMARK
,:RSRV_STR1
,:RSRV_STR2
,:RSRV_STR3
,:RSRV_STR4
,:RSRV_STR5
)