SELECT COUNT(1) AS CC
  FROM TF_B_TRADE_BOOK T
 WHERE T.TRADE_DEPART_ID = :TRADE_DEPART_ID
   AND T.BOOK_STATUS = '0'
   AND T.ACCEPT_MONTH =:ACCEPT_MONTH
   AND T.BOOK_DATE <=TO_DATE(:BOOK_DATE, 'YYYY-MM-DD hh24:mi:ss')
   AND T.BOOK_END_DATE >TO_DATE(:BOOK_DATE, 'YYYY-MM-DD hh24:mi:ss')