SELECT T.ELEMENT_ID,
       T.ELEMENT_KEY,
       T.ELEMENT_CLASS,
       T.ELEMENT_NAME,
       T.ELEMENT_DESC,
       T.ELEMENT_VALUE,
       T.ELEMENT_OLD_VALUE,
       T.ELEMENT_JWCID,
       T.ELEMENT_DISPLAY,
       T.ELEMENT_DISABLED,
       T.ELEMENT_NULLABLE,
       T.VALID_TAG,
       T.ELEMENT_CONTENT,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4
  FROM TD_B_EOP_PAGE_ELEMENT T
 WHERE T.ELEMENT_ID = :ELEMENT_ID
   AND T.VALID_TAG = :VALID_TAG