SELECT DISTINCT A.RES_TRADE_ID,
(SELECT B.RES_TRADE_ID ||'|'|| B.RES_TRADE_NAME FROM TD_M_RESTRADE B WHERE B.RES_TRADE_ID=A.RES_TRADE_ID AND B.VALID_TAG='0') RES_TRADE_NAME
FROM TF_B_RES_ASSIGN_LOG A
WHERE 1=1
AND A.RES_TRADE_ID LIKE '4___'
ORDER BY A.RES_TRADE_ID ASC