SELECT 'B' TAB_TYPE,IBSYSID_MARKETING,IBSYSID_AUDIT,RESULT_CODE,RESULT_INFO,ACCEPT_DATE,UPDATE_DATE 
FROM TF_B_EOP_MARKETING A, TF_B_EOP_ATTR B
WHERE 1=1 
AND B.IBSYSID=A.IBSYSID_MARKETING
AND B.ATTR_CODE='NOTIN_LINE_NO'
AND B.ATTR_VALUE=:PRODUCT_NO
AND (RESULT_CODE =:RESULT_CODE or :RESULT_CODE is null)
union all
SELECT 'BH' TAB_TYPE,IBSYSID_MARKETING,IBSYSID_AUDIT,RESULT_CODE,RESULT_INFO,ACCEPT_DATE,UPDATE_DATE 
FROM TF_B_EOP_MARKETING A, TF_BH_EOP_ATTR B
WHERE 1=1 
AND B.IBSYSID=A.IBSYSID_MARKETING
AND B.ATTR_CODE='NOTIN_LINE_NO'
AND B.ATTR_VALUE=:PRODUCT_NO
AND (RESULT_CODE =:RESULT_CODE or :RESULT_CODE is null)
