UPDATE TF_B_EOP_MARKETING
   SET RESULT_CODE   =:RESULT_CODE,
       RESULT_INFO   = :RESULT_INFO,
       IBSYSID_AUDIT = :IBSYSID_AUDIT,
       HANDLE_INFO   = :HANDLE_INFO,
       HANDLE_CODE   = :HANDLE_OPINION,
       ENCLOSURE     = :COMMON_FILE,
       HANDLE_DATE   = SYSDATE
 WHERE 1 = 1
   AND IBSYSID_MARKETING = :IBSYSID_MARKETING