--IS_CACHE=Y
SELECT ITEM_ID,
       ITEM_NAME,
       ITEM_TYPE,
       ITEM_TYPE_ANAME,
       ITEM_TYPE_A,
       ITEM_TYPE_BNAME,
       ITEM_TYPE_B,
       STORE_TYPE,
       ITEM_NET_TYPE,
       PROVINCE,
       ITEM_EPRICE,
       ITEM_GPOINT,
       ITEM_MPOINT,
       ITEM_BPRICE,
       VENDOR_ID,
       VENDOR_NAME,
       ITEM_STATUS,
       STATE,
       UPDATE_TIME,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10
  FROM TD_B_UPMS_GIFT
 WHERE 1 = 1
   AND STATE = :STATE
   AND ITEM_STATUS = :ITEM_STATUS
   AND ITEM_NAME LIKE '%'||:ITEM_NAME||'%'
   AND ITEM_TYPE = :ITEM_TYPE
   AND STORE_TYPE = :STORE_TYPE
   AND ITEM_NET_TYPE = :ITEM_NET_TYPE
   AND (ITEM_GPOINT BETWEEN :ITEM_GPOINT1 AND :ITEM_GPOINT2)
   AND (ITEM_MPOINT BETWEEN :ITEM_MPOINT1 AND :ITEM_MPOINT2)