UPDATE TL_B_VALUECARD_DETAILED A 
SET A.RSRV_STR1 = :SERIAL_NUM,
A.RSRV_STR2 = :TRADE_ID,
A.STATE_NAME = '充值',
A.STATE_CODE = '3',
A.UPDATE_TIME = TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') 
WHERE A.CARD_NUMBER = :CARD_NUM 
and GROUP_ID = :GROUP_ID
