UPDATE TF_F_USER_SALE_ACTIVE
   SET  PROCESS_TAG=  :PROCESS_TAG , remark = :REMARK ||:UPDATE_STAFF_ID||:UPDATE_DEPART_ID || to_char(SYSDATE,'yyyy-mm-dd HH24:MI:SS') , END_DATE = SYSDATE , RSRV_DATE2 = decode(RSRV_DATE2,'',RSRV_DATE2 ,SYSDATE)
 WHERE user_id =to_number(:USER_ID)
   AND partition_id = MOD(TO_NUMBER(:USER_ID),10000)
   AND end_date>SYSDATE
   AND PROCESS_TAG = '0'
   AND PRODUCT_ID NOT IN
       (SELECT T.PARA_CODE1
          FROM TD_S_COMMPARA T
         WHERE T.PARAM_ATTR = '155'
           AND T.END_DATE > SYSDATE
           AND T.END_DATE > T.START_DATE)