SELECT /*+index(TL_B_IBTRADE IDX_TL_B_IBTRADE_3)*/ COUNT(1) TOTAL
  FROM TL_B_IBTRADE
 WHERE BIPCODE = :BIPCODE
   AND ACTIVITYCODE = :ACTIVITYCODE
   AND (ROUTEVALUE = :SERIAL_NUMBER OR IDITEMRANGE = :SERIAL_NUMBER)
   AND REQTIME BETWEEN TRUNC(SYSDATE) AND SYSDATE