SELECT /*+ index(a,IDX_TL_B_IBTRADE_5)*/A.BIPCODE,A.ACTIVITYCODE,A.TRANSIDO,A.ORIGDOMAIN,A.OSNDUNS,A.ROUTEVALUE,A.IDITEMRANGE,A.REQTIME,A.RSPTIME,A.RSPCODE,A.RSPDESC,A.RESULTCODE,A.RESULTINFO,A.RSRV_STR1,A.RSRV_STR2,A.RSRV_STR3,C.REMARK
  FROM UOP_UIF1.TL_B_IBTRADE A,UOP_UIF1.TD_B_IBBUSI_SIGN C
 WHERE 1=1
   AND (A.IDITEMRANGE = :IDITEMRANGE OR A.ROUTEVALUE = :IDITEMRANGE)
   AND C.BIPCODE = A.BIPCODE
   AND C.ACTIVITYCODE = A.ACTIVITYCODE
   AND C.ORIG_DOMAIN = A.ORIGDOMAIN
   AND A.REQTIME BETWEEN to_date(:REQTIME|| '00:00:00','yyyy-mm-dd hh24:mi:ss') AND to_date(:REQTIME|| '23:59:59','yyyy-mm-dd hh24:mi:ss')
UNION
SELECT  /*+ INDEX(A IDX_TL_BH_IBTRADE_5) */B.BIPCODE,B.ACTIVITYCODE,B.TRANSIDO,B.ORIGDOMAIN,B.OSNDUNS,B.ROUTEVALUE,B.IDITEMRANGE,B.REQTIME,B.RSPTIME,B.RSPCODE,B.RSPDESC,B.RESULTCODE,B.RESULTINFO,B.RSRV_STR1,B.RSRV_STR2,B.RSRV_STR3,C.REMARK
  FROM UOP_UIF1.TL_BH_IBTRADE B,UOP_UIF1.TD_B_IBBUSI_SIGN C
 WHERE 1=1 
   AND B.IDITEMRANGE = :IDITEMRANGE
   AND C.BIPCODE = B.BIPCODE
   AND C.ACTIVITYCODE = B.ACTIVITYCODE
   AND C.ORIG_DOMAIN = B.ORIGDOMAIN
   AND B.REQTIME BETWEEN to_date(:REQTIME|| '00:00:00','yyyy-mm-dd hh24:mi:ss') AND to_date(:REQTIME|| '23:59:59','yyyy-mm-dd hh24:mi:ss')
   AND B.P_MONTH = TO_NUMBER( SUBSTR(:REQTIME,6,2))  
UNION   
   SELECT  /*+ INDEX(A IDX_TL_BH_IBTRADE_3) */B.BIPCODE,B.ACTIVITYCODE,B.TRANSIDO,B.ORIGDOMAIN,B.OSNDUNS,B.ROUTEVALUE,B.IDITEMRANGE,B.REQTIME,B.RSPTIME,B.RSPCODE,B.RSPDESC,B.RESULTCODE,B.RESULTINFO,B.RSRV_STR1,B.RSRV_STR2,B.RSRV_STR3,C.REMARK
  FROM UOP_UIF1.TL_BH_IBTRADE B,UOP_UIF1.TD_B_IBBUSI_SIGN C
 WHERE 1=1 
   AND B.ROUTEVALUE = :IDITEMRANGE
   AND C.BIPCODE = B.BIPCODE
   AND C.ACTIVITYCODE = B.ACTIVITYCODE
   AND B.REQTIME BETWEEN to_date(:REQTIME|| '00:00:00','yyyy-mm-dd hh24:mi:ss') AND to_date(:REQTIME|| '23:59:59','yyyy-mm-dd hh24:mi:ss')
   --AND C.ORIG_DOMAIN = B.ORIGDOMAIN