SELECT A.BIPCODE,
       A.ACTIVITYCODE,
       A.TRANSIDO,
       A.ORIGDOMAIN,
       A.OSNDUNS,
       A.ROUTEVALUE,
       A.IDITEMRANGE,
       A.REQTIME,
       A.RSPTIME,
       A.RSPCODE,
       A.RSPDESC,
       A.RESULTCODE,
       A.RESULTINFO,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       B.REMARK
  FROM UOP_UIF1.TL_B_IBTRADE A, UOP_UIF1.TD_B_IBBUSI_SIGN B
 WHERE 1 = 1 AND (A.BIPCODE = SUBSTR(B.BIPCODE, 0, 8) or A.BIPCODE = b.bipcode )
  AND A.ACTIVITYCODE = rpad(B.ACTIVITYCODE, 8, ' ') 
  AND (A.IDITEMRANGE = :IDITEMRANGE OR A.ROUTEVALUE = :IDITEMRANGE) 
  AND A.REQTIME > TRUNC(SYSDATE)
  AND ((A.IBDIRTAG IS NULL) OR A.IBDIRTAG=B.DIRECTION)
  ORDER BY A.REQTIME