INSERT INTO  TF_B_TRADE_GRP_MEB_PLATSVC(TRADE_ID,ACCEPT_MONTH,USER_ID,SERIAL_NUMBER,EC_USER_ID,
EC_SERIAL_NUMBER,SERVICE_ID,SERV_CODE,BIZ_CODE,BIZ_NAME,
START_DATE,END_DATE,MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,
UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,
RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,
RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,
RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT to_number(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID,5,2)),USER_ID,SERIAL_NUMBER,EC_USER_ID,
EC_SERIAL_NUMBER,SERVICE_ID,SERV_CODE,BIZ_CODE,BIZ_NAME,
SYSDATE,to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'),:MODIFY_TAG,to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'),:UPDATE_STAFF_ID,
:UPDATE_DEPART_ID,REMARK,:RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,
RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,
RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,
RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_GRP_MEB_PLATSVC P
  WHERE P.PARTITION_ID=MOD(TO_NUMBER(:USER_ID), 10000)
AND P.USER_ID=:USER_ID
AND P.RSRV_NUM1 = '0'
AND P.START_DATE IN (SELECT MAX(START_DATE) START_DATE FROM TF_F_USER_GRP_MEB_PLATSVC T
                      WHERE T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
                      AND T.USER_ID = TO_NUMBER(:USER_ID)
                      AND T.EC_USER_ID = P.EC_USER_ID
                      AND T.END_DATE <= SYSDATE)
AND EXISTS (SELECT 1 FROM TF_F_CUST_GROUP G, TF_F_USER U
               WHERE U.USER_ID = P.EC_USER_ID
               AND U.PARTITION_ID = MOD(TO_NUMBER(P.EC_USER_ID), 10000)
               AND G.CUST_ID = U.CUST_ID
							 AND G.REMOVE_TAG = '0')