INSERT INTO tf_f_user_mbmp_plus(partition_id,user_id,serial_number,biz_type_code,org_domain,info_code,info_value,update_staff_id,update_depart_id,update_time)
select mod(user_id,10000),user_id,serial_number,biz_type_code,org_domain,info_code,info_value,trade_staff_id,trade_depart_id,sysdate
from tf_b_trade_mbmp_plus
where trade_id=to_number(:TRADE_ID)