SELECT ALARM_ID,
		RULE_ID,
		TO_CHAR(ALARMCREATING_TIME, 'YYYY-MM-DD HH24:mi:ss') ALARMCREATING_TIME,
		TASKWARNING_MESSAGE,
		INFORM_STAFF,
		INFORM_DEPART_ID,
		HANDLE_STAFF,
		HANDLE_DEPART_ID,
		HANDLE_STATE,
		RESULT_INFO,
		RSRV_NUM1,
		RSRV_NUM2,
		RSRV_NUM3,
		RSRV_NUM4,
		RSRV_NUM5,
		RSRV_STR1,
		RSRV_STR2,
		RSRV_STR3,
		RSRV_STR4,
		RSRV_STR5,
		RSRV_DATE1,
		RSRV_DATE2,
		RSRV_DATE3
FROM TF_B_TASKALARM
WHERE  1 = 1
  AND HANDLE_STATE = :HANDLE_STATE
  AND ALARMCREATING_TIME < to_date(:END_TIME, 'YYYY-MM-DD')
  AND ALARMCREATING_TIME > to_date(:START_TIME, 'YYYY-MM-DD')