SELECT A.PARTITION_ID,
       A.USER_ID,
       A.USER_ID_A,
       A.DISCNT_CODE,
       A.SPEC_TAG,
       A.RELATION_TYPE_CODE,
       A.INST_ID,
       A.CAMPN_ID,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(A.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       TO_CHAR(A.RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(A.RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(A.RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3,
       C.PARAM_CODE,
       C.PARAM_NAME,
       C.PARA_CODE1,
       C.PARA_CODE2,
       C.PARA_CODE3,
       C.PARA_CODE4,
       C.PARA_CODE5,
       C.PARA_CODE6,
       C.PARA_CODE7,
       C.PARA_CODE8
  FROM TF_F_USER_DISCNT A,TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.DISCNT_CODE = TO_NUMBER(C.PARAM_CODE)
   AND C.SUBSYS_CODE = :SUBSYS_CODE
   AND C.PARAM_ATTR = :PARAM_ATTR
   AND (C.EPARCHY_CODE = :EPARCHY_CODE OR C.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
   AND  A.END_DATE>A.START_DATE
   AND  A.START_DATE>SYSDATE