--IS_CACHE=Y
SELECT A.BLACKUSER_ID,
        A.CUST_ID,
        A.PSPT_TYPE_CODE,
        A.PSPT_ID,
        A.CUST_NAME,
        A.EPARCHY_CODE,
        A.USER_ID
   FROM TD_O_BLACKUSER A
  WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER