SELECT RSRV_STR10 /*会议ID*/, RSRV_STR7 /*会议密码*/, RSRV_STR8 /*主持人密码*/
  FROM TF_B_TRADE_OTHER
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND USER_ID = :USER_ID
   AND RSRV_VALUE_CODE = 'V2CP'
   AND RSRV_VALUE = '32'
   AND RSRV_STR11 = '12'
   AND SYSDATE BETWEEN START_DATE AND END_DATE