SELECT /*+ first_rows(1) */COUNT(*) RECORDCOUNT
  FROM TF_F_USER_SALE_ACTIVE A,TF_F_RELATION_UU B
 WHERE B.USER_ID_A=TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(B.USER_ID_B), 10000)
   AND A.USER_ID=B.USER_ID_B
   AND B.RELATION_TYPE_CODE=:RELATION_TYPE_CODE
   AND A.PROCESS_TAG=:PROCESS_TAG
   AND EXISTS (SELECT 1 FROM TD_S_COMMPARA B 
                WHERE B.PARAM_ATTR=9987
                  AND B.SUBSYS_CODE='CSM'
                  AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
                  AND B.EPARCHY_CODE=:EPARCHY_CODE
                  AND B.PARAM_CODE=A.PRODUCT_ID)
   AND B.END_DATE >= SYSDATE
   AND A.ADVANCE_PAY = 0
   and rownum < 2