SELECT  STAND_ADDRESS,
       DETAIL_ADDRESS,
       SIGN_PATH,
       PORT_TYPE,
       TO_CHAR(INST_ID) INST_ID,
       ACCT_PASSWD,
       TO_CHAR(STAND_ADDRESS_CODE) STAND_ADDRESS_CODE,
       PHONE,
       CONTACT,
       CONTACT_PHONE,
       TO_CHAR(SUGGEST_DATE, 'YYYY-MM-DD HH24:MI:SS') SUGGEST_DATE,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
FROM TF_B_TRADE_WIDENET T
WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)  AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)) AND
      SYSDATE BETWEEN T.START_DATE AND T.END_DATE