--IS_CACHE=Y
SELECT D.PRODUCT_ID,
       D.PACKAGE_ID,
       D.TERMINAL_TYPE_CODE,
       D.TERMINAL_MODE_CODE,
       D.EPARCHY_CODE
  FROM TD_B_SALE_TERMINAL_LIMIT D
 WHERE D.STATE = '1'
   AND D.PRODUCT_ID = :PRODUCT_ID
   AND D.PACKAGE_ID = :PACKAGE_ID
   AND D.TERMINAL_TYPE_CODE = :TERMINAL_TYPE_CODE
   AND D.TERMINAL_MODE_CODE = :TERMINAL_MODE_CODE
   AND D.EPARCHY_CODE = :EPARCHY_CODE