SELECT LOG_ID,
       TRADE_ID,
       OPER_TYPE_NAME,
       OPER_DATE,
       OPER_MONTH,
       TRADE_STAFF_ID,
       TRADE_DEPART_ID,
       AREA.AREA_NAME,
       TRADE_EPARCHY_CODE,
       PAY_MODE,
       PAY_NAME,
       PAY_NAME_REMARK,
       OPER_FEE,
       OPER_UNIT,
       OPER_PRICE,
       OPER_NUM,
       REFUND_TAG,
       RSRV_STR4
  FROM TF_F_NONBOSSFEE_LOG
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND REFUND_TAG = :REFUND_TAG