select 
 t.LOG_ID
,t.OPER_TYPE_NAME FEE_NAME --test
,t.OPER_DATE
,t.OPER_MONTH
,t.TRADE_STAFF_ID
,(select a.depart_name from td_m_depart a where a.depart_id= t.TRADE_DEPART_ID) TRADE_DEPART_ID
,t.TRADE_CITY_CODE
,t.TRADE_EPARCHY_CODE
,t.PAY_MODE
,(select T1.DATA_NAME from td_s_static t1 where t1.type_id='HAND_GATHER_PAY_MODE' AND T1.DATA_ID=T.PAY_MODE) PAY_MODE_DESC
,t.PAY_NAME
,(select T1.DATA_NAME from td_s_static t1 where t1.type_id='PAY_USER_NAME' AND T1.DATA_ID=T.PAY_NAME) PAY_NAME_TYPE
,t.PAY_NAME_REMARK
,(SELECT T1.DATA_NAME FROM TD_S_NONBOSSPARA T1 WHERE T1.TYPE_ID='PAY_USER_NAME_ALL' AND T1.DATA_ID=T.PAY_NAME_REMARK) PAY_NAME_ALL
,t.OPER_FEE
,t.OPER_UNIT
,t.OPER_PRICE
,t.OPER_NUM
,t.REFUND_TAG
,decode(t.refund_tag,'0','NO','YES') IF_CENCER
,t.RSRV_STR1
,t.RSRV_STR2
,(SELECT T1.DATA_NAME FROM TD_S_NONBOSSPARA T1 WHERE T1.TYPE_ID='INVOICE_TYPE' AND T1.DATA_ID=T.RSRV_STR2) INVOICE_TYPE
,t.RSRV_STR3
,(SELECT T1.DATA_NAME FROM TD_S_NONBOSSPARA T1 WHERE T1.TYPE_ID='ADDED_TAX_TYPE' AND T1.DATA_ID=T.RSRV_STR3) TAX_TYPE
,t.RSRV_STR4
,t.RSRV_STR5
,t.REMARK
,t.NOTAX_FEE
,t.TAX_FEE
,t.TAX_RATE
,t.RATE_TYPE
,t.RSRV_NUM1
,t.RSRV_NUM2
,t.TRADE_ID
,t.RSRV_STR6
,(select T1.DATA_NAME from td_s_static t1 where t1.type_id='INVOICE_PRINT' AND T1.DATA_ID=T.RSRV_STR6) INVOICE_PRINT_TYPE
,to_char(t.RSRV_STR7,'yyyy-mm-dd hh24:mi:ss') RSRV_STR7
,to_char(t.RSRV_STR8,'yyyy-mm-dd hh24:mi:ss') RSRV_STR8
,to_char(t.RSRV_STR9,'yyyy-mm-dd hh24:mi:ss') RSRV_STR9
,to_char(t.RSRV_STR10,'yyyy-mm-dd hh24:mi:ss') RSRV_STR10
,OPER_TYPE_NAME_DESC
,REFUND_LOG_ID
,TICKET_ID
,TICKET_TYPE
from TF_F_NONBOSSFEE_LOG t
where 1=1  
AND t.OPER_TYPE_NAME=:FEE_NAME
AND t.RSRV_STR1=:COST_CENTER
and t.RSRV_STR3=:TAX_TYPE
and t.PAY_NAME=:PAY_NAME
AND t.OPER_DATE >= to_Date(:START_DATE, 'yyyy-mm-dd')
AND t.OPER_DATE <= to_date(:END_DATE||' 23:59:59', 'yyyy-mm-dd hh24:mi:ss')
and t.RSRV_STR6=:INVOICE_PRINT
AND T.OPER_MONTH LIKE '%'||:OPER_MONTH||'%'
AND T.OPER_TYPE_NAME_DESC LIKE '%'||:OPER_TYPE_NAME_DESC||'%'
AND T.TAX_RATE LIKE '%'||:TAX_RATE||'%'
AND T.OPER_FEE LIKE '%'||:OPER_FEE||'%'
AND T.TAX_FEE LIKE '%'||:TAX_FEE||'%'
AND T.REMARK LIKE '%'||:REMARK||'%'
AND T.RSRV_STR5 LIKE '%'||:RSRV_STR5||'%'