--IS_CACHE=N
SELECT A.EPARCHY_CODE 归属地州,TO_CHAR(A.USER_ID) 用户标识,ACCT_TAG 是否激活, B.BRAND_CODE 用户品牌, A.CITY_CODE 用户业务区, A.CUST_ID 客户标识,TO_CHAR(A.OPEN_DATE,'YYYYMM') 入网月份,TRUNC(SYSDATE)-TRUNC(A.OPEN_DATE) 入网天数,TO_CHAR(A.OPEN_DATE,'YYYYMMDD') 入网日期
  FROM TF_F_USER A, TF_F_USER_PRODUCT B
 WHERE A.REMOVE_TAG = '0'
   AND A.SERIAL_NUMBER =:KD_SERIAL_NUMBER
   AND A.USER_ID = B.USER_ID
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND B.MAIN_TAG='1'
   UNION
   SELECT A.EPARCHY_CODE 归属地州,TO_CHAR(A.USER_ID) 用户标识,A.ACCT_TAG 是否激活, B.BRAND_CODE 用户品牌, A.CITY_CODE 用户业务区, A.CUST_ID 客户标识,TO_CHAR(A.OPEN_DATE,'YYYYMM') 入网月份,TRUNC(SYSDATE)-TRUNC(A.OPEN_DATE) 入网天数,TO_CHAR(A.OPEN_DATE,'YYYYMMDD') 入网日期
   FROM ucr_crm1.TF_B_TRADE_USER A, ucr_crm1.TF_B_TRADE_PRODUCT B,ucr_crm1.tf_b_trade t
  WHERE A.USER_ID = B.USER_ID
    AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
    AND B.MAIN_TAG = '1'
    AND A.SERIAL_NUMBER = :KD_SERIAL_NUMBER
    and a.serial_number = t.serial_number
    and a.trade_id = t.trade_id
    and a.trade_id = b.trade_id
    AND A.REMOVE_TAG = '0'

