SELECT COUNT(T.USER_ID) ERROR_COUNT
  FROM TF_F_USER_PASSWD_ERROR T
 WHERE T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.PASSWD_TYPE_CODE = :PASSWD_TYPE_CODE
   AND T.IN_MODE_CODE = :IN_MODE_CODE
   AND SYSDATE BETWEEN T.START_DATE + 0 AND T.END_DATE + 0