SELECT U.USER_ID,
       U.TEL_URL,
       U.SIP_URL,
       U.IMPI,
       U.IMS_USER_ID,
       U.IMS_PASSWORD,
       U.START_DATE,
       U.END_DATE,
       U.RSRV_STR1,
       U.RSRV_STR2,
       U.RSRV_STR3,
       U.RSRV_STR4,
       U.RSRV_STR5,
       U.INST_ID,
       U.PARTITION_ID
  FROM TF_F_USER_IMPU U, TF_F_RELATION_UU UU
 WHERE U.USER_ID = UU.USER_ID_B 
   AND UU.USER_ID_A = :USER_ID_A
   AND SYSDATE BETWEEN UU.START_DATE AND UU.END_DATE
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE
   AND U.PARTITION_ID = UU.PARTITION_ID
   AND U.PARTITION_ID = MOD(U.USER_ID, 10000)
   AND SUBSTR(U.RSRV_STR4, 3) = :SHORT_CODE