SELECT A.USER_ID, A.CITY_CODE, B.AREA_CODE, B.AREA_NAME
  FROM TF_F_USER_CITY A, TD_M_AREA B
 WHERE A.CITY_CODE = B.AREA_CODE
   AND A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE