SELECT PHONE_CODE_A,
       PHONE_CODE_B,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
FROM TF_F_TRANS_PHONE
WHERE PHONE_CODE_A >= :START_SERIALNUMBER
   AND PHONE_CODE_A <= :END_SERIALNUMBER
   AND SYSDATE BETWEEN START_DATE AND END_DATE