SELECT TO_CHAR(TRADE_ID) TRADE_ID,
       ACCEPT_MONTH,
       TO_CHAR(USER_ID) USER_ID,
       TRADE_TYPE_CODE,
       NP_SERVICE_TYPE,
       SERIAL_NUMBER,
       FLOW_ID,
       MESSAGE_ID,
       BRC_ID,
       MSG_CMD_CODE,
       MD5,
       PORT_OUT_NETID,
       PORT_IN_NETID,
       HOME_NETID,
       B_NP_CARD_TYPE,
       A_NP_CARD_TYPE,
       CUST_NAME,
       CRED_TYPE,
       PSPT_ID,
       PHONE,
       ACTOR_CUST_NAME,
       ACTOR_CRED_TYPE,
       ACTOR_PSPT_ID,
       TO_CHAR(ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       TO_CHAR(NP_START_DATE, 'yyyy-mm-dd hh24:mi:ss') NP_START_DATE,
       TO_CHAR(CREATE_TIME, 'yyyy-mm-dd hh24:mi:ss') CREATE_TIME,
       TO_CHAR(BOOK_SEND_TIME, 'yyyy-mm-dd hh24:mi:ss') BOOK_SEND_TIME,
       SEND_TIMES,
       RESULT_CODE RESULT_CODE_S,
        RESULT_MESSAGE,
       ERROR_MESSAGE,
       STATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM tf_b_trade_np
 WHERE trade_id = TO_NUMBER(:TRADE_ID)