UPDATE TF_B_TRADE_ACCOUNT_ACCTDAY T
   SET T.START_DATE = TRUNC(TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')), 
   T.FIRST_DATE = ADD_MONTHS(TRUNC(TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'MONTH'),1)
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))