SELECT T.BATCH_ID,
       T.SERIAL_NUMBER,
       T.PRODUCT_ID,
       T.PACKAGE_ID,
       T.ACCEPT_MONTH,
       T.IMPORT_TIME,
       T.ACCEPT_TIME,
       T.STATUS,
       T.TRADE_STAFF_ID,
       T.UPDATE_TIME,
       T.REQUEST_ID,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5
  FROM TF_B_SALEACTIVE_BAT T
 WHERE 1 = 1
   AND T.BATCH_ID = :BATCH_ID
   AND T.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND T.IMPORT_TIME + 0 >= TO_DATE(:IMPORT_START, 'YYYY-MM-DD') 
   AND T.IMPORT_TIME + 0 <= TO_DATE(:IMPORT_END, 'YYYY-MM-DD') + 1
   AND T.SERIAL_NUMBER = :SERIAL_NUMBER
   AND T.STATUS = :STATUS