UPDATE TI_B_RELATION_UU T
   SET T.MODIFY_TAG = :MODIFY_TAG
 WHERE T.SYNC_SEQUENCE = TO_NUMBER(:SYNC_SEQUENCE)
   AND T.USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND T.USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND T.END_DATE>SYSDATE