SELECT 
       D.TRADE_ID,
       D.USER_CLASS,
       D.USER_ID,
       D.SERIAL_NUMBER,
       D.GIVE_USER_ID,
       D.GIVE_SERIAL_NUMBER,
       D.FROMTRADEID,
       D.UPDATE_TIME,
       D.UPDATE_STAFF_ID,
       D.UPDATE_DEPART_ID,
       D.UPDATE_CITY_CODE,
TO_CHAR(D.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE ,
TO_CHAR(D.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE ,
       D.REMARK,
       D.RSRV_NUM1,
       D.RSRV_STR1,
       D.RSRV_STR2,
       D.RSRV_STR3,
       D.RSRV_DATE1,
       D.RSRV_TAG1

FROM TL_B_USER_GIVE_CLASS T , TL_B_USER_GIVE_CLASS_DETAIL D 
WHERE 1=1 
AND  T.SERIAL_NUMBER = :SERIAL_NUMBER 
AND  T.TRADEID=D.FROMTRADEID
AND  T.SERIAL_NUMBER=D.SERIAL_NUMBER
AND  SYSDATE>D.START_DATE AND SYSDATE<D.END_DATE

