UPDATE TL_B_USER_GIVE_CLASS_DETAIL T
SET T.END_DATE = TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
WHERE 1=1
 AND  T.GIVE_SERIAL_NUMBER = :GIVE_SERIAL_NUMBER 
 AND  SYSDATE > T.START_DATE AND  SYSDATE<T.END_DATE 