UPDATE TF_F_USER_PLATSVC A
   SET END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS') -
                  1 / 24 / 3600,
       REMARK   = 'SP全退订须终止相关订购关系',
       A.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
   WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND USER_ID = TO_NUMBER(:USER_ID)
     AND SP_CODE = :SP_CODE
     AND ORG_DOMAIN = 'DSMP'
     AND BIZ_STATE_CODE IN ('A', 'N')
	 AND NOT ( BIZ_CODE LIKE 'SW80%' OR BIZ_CODE LIKE 'SW90%' ) 	 
     AND SYSDATE BETWEEN START_DATE AND END_DATE
     AND EXISTS (SELECT 1
            FROM TD_B_PLATSVC B
           WHERE A.SERVICE_ID = B.SERVICE_ID
             AND B.SERV_TYPE = '1')