SELECT to_char(TRADE_ID) TRADE_ID,CANCEL_TAG,STATE_CODE,TRADE_DEPART_ID,TRADE_STAFF_ID,to_char(ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,TRADE_TYPE_CODE,ERROR_NUM,to_char(AUDIT_DATE,'yyyy-mm-dd hh24:mi:ss') AUDIT_DATE,AUDIT_STAFF_ID,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,AUDITING_STAFF_ID,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,
decode(STATE_CODE,'4','二级稽核通过','5','二级稽核回退','其他') RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8
  FROM TS_A_AUDITRESULT_DETAIL
 WHERE STATE_CODE = :STATE_CODE
   AND END_DATE>TRUNC(TO_DATE(:ACCEPT_DATE,'YYYY-MM-DD HH24:MI:SS'))
   AND END_DATE<TRUNC(TO_DATE(:ACCEPT_DATE,'YYYY-MM-DD HH24:MI:SS'))+1  
   AND TRADE_DEPART_ID in
   (     
      SELECT DEPART_ID
       FROM TD_M_DEPART
      WHERE VALIDFLAG = '0'
        and area_code =
        ( select area_code
            from TD_M_DEPART
           where DEPART_ID =:TRADE_DEPART_ID
        )
   )