SELECT *
  FROM TF_A_PAYRELATION A
 WHERE A.USER_ID IN
       (SELECT USER_ID_B
          FROM TF_F_RELATION_UU
         WHERE USER_ID_A IN (SELECT USER_ID_A
                               FROM TF_F_RELATION_UU
                              WHERE USER_ID_B = :USER_ID_B AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B),10000)
                                AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE AND END_DATE>SYSDATE)
           AND END_DATE > SYSDATE)
   AND (
            (SELECT ACYC_ID
             FROM TD_A_ACYCPARA
             WHERE SYSDATE BETWEEN ACYC_START_TIME AND ACYC_END_TIME) BETWEEN
             A.START_CYCLE_ID AND A.END_CYCLE_ID
          )