select count(*) CNT
 from TD_B_PACKAGE_EXT K, TD_B_PRODUCT_PACKAGE P, TF_SM_TROOP_MEMBER T
where P.PACKAGE_ID = K.PACKAGE_ID
  and USER_ID = :USER_ID
  and MEMBER_STATUS = '1'
  and T.TROOP_ID = NVL(K.COND_FACTOR1, 0)
  and P.PRODUCT_ID = :PRODUCT_ID
