--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_PRODUCT UP
 WHERE UP.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND UP.USER_ID = TO_NUMBER(:USER_ID)
   AND UP.PRODUCT_MODE IN (21, 22, 23, 24)
   AND UP.END_DATE > SYSDATE
      --零流量宽带客户剔除,不给于积分,根据经分提供的数据来判断
   AND NOT EXISTS
 (SELECT 1
          FROM TS_CHL_NOSNWIDENET_USER NU
         WHERE NU.USER_ID = :USER_ID
           AND NU.ACYC_ID = TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMM'))