Select  T.PARTITION_ID,
         TO_CHAR(T.USER_ID) USER_ID,
         T.RSRV_VALUE_CODE,
         T.RSRV_VALUE,
         T.RSRV_NUM1,
         T.RSRV_NUM2,
         T.RSRV_NUM3,
         T.RSRV_NUM4,
         T.RSRV_NUM5,
         T.RSRV_NUM6,
         T.RSRV_NUM7,
         T.RSRV_NUM8,
         T.RSRV_NUM9,
         T.RSRV_NUM10,
         T.RSRV_NUM11,
         T.RSRV_NUM12,
         T.RSRV_NUM13,
         T.RSRV_NUM14,
         T.RSRV_NUM15,
         T.RSRV_NUM16,
         T.RSRV_NUM17,
         T.RSRV_NUM18,
         T.RSRV_NUM19,
         T.RSRV_NUM20,
         T.RSRV_STR1,
         T.RSRV_STR2,
         T.RSRV_STR3,
         T.RSRV_STR4,
         T.RSRV_STR5,
         T.RSRV_STR6,
         T.RSRV_STR7,
         T.RSRV_STR8,
         T.RSRV_STR9,
         T.RSRV_STR10,
         T.RSRV_STR11,
         T.RSRV_STR12,
         T.RSRV_STR13,
         T.RSRV_STR14,
         T.RSRV_STR15,
         T.RSRV_STR16,
         T.RSRV_STR17,
         T.RSRV_STR18,
         T.RSRV_STR19,
         T.RSRV_STR20,
         T.RSRV_STR21,
         T.RSRV_STR22,
         T.RSRV_STR23,
         T.RSRV_STR24,
         T.RSRV_STR25,
         T.RSRV_STR26,
         T.RSRV_STR27,
         T.RSRV_STR28,
         T.RSRV_STR29,
         T.RSRV_STR30,
         T.RSRV_DATE1,
         T.RSRV_DATE2,
         T.RSRV_DATE3,
         T.RSRV_DATE4,
         T.RSRV_DATE5,
         T.RSRV_DATE6,
         T.RSRV_DATE7,
         T.RSRV_DATE8,
         T.RSRV_DATE9,
         T.RSRV_DATE10,
         T.RSRV_TAG1,
         T.RSRV_TAG2,
         T.RSRV_TAG3,
         T.RSRV_TAG4,
         T.RSRV_TAG5,
         T.RSRV_TAG6,
         T.RSRV_TAG7,
         T.RSRV_TAG8,
         T.RSRV_TAG9,
         T.RSRV_TAG10,
         T.PROCESS_TAG,
         T.STAFF_ID,
         T.DEPART_ID,
         T.TRADE_ID,
         TO_CHAR(T.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
         TO_CHAR(T.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
         T.UPDATE_TIME,
         T.UPDATE_STAFF_ID,
         T.UPDATE_DEPART_ID,
         T.REMARK,
         TO_CHAR(T.INST_ID) INST_ID
 From TF_F_USER_OTHER T
 where t.rsrv_value_code=:RSRV_VALUE_CODE
 and t.RSRV_TAG2 = '1'
 AND T.INST_ID=:INST_ID
 AND (TRIM(T.RSRV_STR1) = :RSRV_STR1 OR :RSRV_STR1 IS NULL)
 AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE