DELETE TF_F_USER_LIMIT T
 WHERE T.USER_ID = :USER_ID
   AND T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND T.ELEMENT_ID = :SERVICE_ID
   AND TO_NUMBER(SYSDATE - T.OCCUPY_TIME) * 24 * 60 >= to_number(:TIME)