SELECT C.CHNL_ID, C.CHNL_CODE, C.CHNL_NAME, C.STATE
  FROM TF_CHL_CHANNEL C, CHNL_CU_CUMUINFO I, TF_CHL_ARCHIVE A
 WHERE C.CHNL_ID = I.CUMU_DEPART_ID
   AND I.MOBILE_NUM = :SERIAL_NUMBER
   AND C.STATE = '0'
   AND I.UPDATE_STATE = '1'
   AND A.CHNL_ID = C.CHNL_ID
   AND A.LINKMAN_PHONE IS NOT NULL
   AND I.CUMU_ID LIKE 'AGT%'