SELECT T.PARTITION_ID PARTITION_ID,
       T.USER_ID USER_ID,
       T.INST_ID INST_ID,
       T.MP_GROUP_CUST_CODE MP_GROUP_CUST_CODE,
       T.PAY_TYPE PAY_TYPE,
       T.OPER_TYPE OPER_TYPE,
       T.PRODUCT_OFFER_ID PRODUCT_OFFER_ID,
       T.SERIAL_NUMBER SERIAL_NUMBER,
       T.LIMIT_FEE LIMIT_FEE,
       T.ELEMENT_ID ELEMENT_ID,
	   T.RSRV_STR1 DISCNT_CODE,
       TO_CHAR(T.START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(T.END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,
       T.RSRV_STR2 DISCNT_CODE_NAME
  FROM TF_F_USER_MEB_CENPAY T
 WHERE 1=1
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = TTO_NUMBER(:USER_ID)
   AND T.MP_GROUP_CUST_CODE = :MP_GROUP_CUST_CODE
   AND T.PRODUCT_OFFER_ID = :PRODUCT_OFFER_ID
   AND T.OPER_TYPE = :OPER_TYPE
   AND T.SERIAL_NUMBER = :SERIAL_NUMBER_B
   AND T.RSRV_STR1 = :DISCNT_CODE
   AND T.END_DATE >= TO_DATE(:START_DATE,'YYYY-MM-DD') 
   AND T.END_DATE <= TO_DATE(:END_DATE,'YYYY-MM-DD')
   AND T.END_DATE > SYSDATE
   ORDER BY T.START_DATE DESC