UPDATE TF_B_FAMILY_OTHER SET
			REMARK=:REMARK,
			FINISH_TAG=:FINISH_TAG,
			ACTION=:ACTION,
			EXP_TIME =TO_DATE(:EXP_TIME, 'YYYY-MM-DD HH24:MI:SS')
            WHERE 1=1 
            AND PRODUCT_OFFERING_ID = :PRODUCT_OFFERING_ID 
            AND CUSTOMER_PHONE = :CUSTOMER_PHONE 
            AND MEM_NUMBER =:MEM_NUMBER