select 
A.ORDER_ID,
A.SERIAL_NUMBER AS SERIALNUMBER,
A.PROVINCE,
A.OPERATE_TIME AS ORDER_TIME,
A.TOTAL_SCORE AS SUMPOINTS,
A.order_deliver_sum_fee,
A.order_product_sum_fee,
B.SUB_ORDER_NO AS ORDERID,
B.PAR_ORDER_NO AS PARENT_ORDERID,
B.ITEM_TYPE,
B.RECEIVER AS CUSTNAME,
B.DELIV_PROV,
B.DELIV_CITY,
B.CUST_ADDR,
B.CUST_TEL,   
B.POST_CODE,     
B.DELIV_TIME_REQ AS DELIV_TIMEREQ, 
B.ITEM_NAME AS NAME,          
B.ITEM_ID,                                    
B.ITEM_NUM,     
B.SCORE AS PAYPOINT,        
C.SUB_ORDER_ID,
C.STATE AS STATU,
C.RECORE_DATE,
C.STATE_DESC   
from TI_B_UPMS_ORDER_N A, .TI_B_UPMS_ORDER_SUB_N B, TL_B_UPMS_ORDER_STATESYNC C
where A.ORDER_ID = B.PAR_ORDER_NO
and   B.SUB_ORDER_NO = C.SUB_ORDER_ID
and   (A.SERIAL_NUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
and   (B.PAR_ORDER_NO = :PARENT_ORDERID OR :PARENT_ORDERID IS NULL)
and   (B.SUB_ORDER_NO = :ORDERID OR :ORDERID IS NULL)
and   (B.ITEM_TYPE = :ITEM_TYPE OR :ITEM_TYPE IS NULL)