SELECT REQ_ID,
  ACCEPT_MONTH,
  ACCEPT_DATE,
  TRADE_TYPE_CODE,
  IN_MODE_CODE,
  USER_ID,
  SERIAL_NUMBER,
  NET_TYPE_CODE,
  EPARCHY_CODE,
  CITY_CODE,
  TRADE_STAFF_ID,
  TRADE_DEPART_ID,
  TRADE_CITY_CODE,
  TRADE_EPARCHY_CODE,
  PROCESS_TAG,
  EXEC_DESC,
  EXEC_RESULT,
  PROCESS_TIME,
  EXEC_TIME,
  REMARK,
  UPDATE_TIME
  FROM TL_O_REALTIMEMARKETING A
 WHERE 1=1
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.USER_ID = :USER_ID
   AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND A.PROCESS_TIME + NUMTODSINTERVAL(:STEP,'second') <= SYSDATE