select T.SERVICE_ID,B.SP_CODE,B.BIZ_CODE,B.BILL_TYPE,B.PRICE from TD_B_PLATSVC_LIMIT T,TF_F_USER_PLATSVC B
where T.SERVICE_ID_L = :SERVICE_ID_L
AND T.BIZ_TYPE_CODE=:BIZ_TYPE_CODE
AND T.LIMIT_TYPE='0' 
AND T.SERVICE_ID=B.SERVICE_ID
AND B.USER_ID = :USER_ID
AND( T.OPER_CODE = :OPER_CODE OR T.OPER_CODE = 'ZZ')
AND B.BIZ_STATE_CODE = :BIZ_STATE_CODE
AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE