select T.SERVICE_ID_L
from TD_B_PLATSVC_LIMIT T,TF_F_USER_PLATSVC B
where T.SERVICE_ID = :SERVICE_ID
AND T.BIZ_TYPE_CODE=:BIZ_TYPE_CODE
AND T.LIMIT_TYPE=:LIMIT_TYPE
AND T.SERVICE_ID_L=B.SERVICE_ID
AND B.USER_ID = :USER_ID
AND T.OPER_CODE = :OPER_CODE
AND B.BIZ_STATE_CODE IN ('A','N','L')
AND T.SVC_TYPE='Z'
AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
union
select T.SERVICE_ID_L
from TD_B_PLATSVC_LIMIT T,TF_F_USER_SVC B
where T.SERVICE_ID = :SERVICE_ID
AND T.BIZ_TYPE_CODE=:BIZ_TYPE_CODE
AND T.LIMIT_TYPE=:LIMIT_TYPE
AND T.SERVICE_ID_L=B.SERVICE_ID
AND B.USER_ID = :USER_ID
AND T.OPER_CODE = :OPER_CODE
AND T.SVC_TYPE='S'
AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE