INSERT INTO TF_B_EWE_TRANS_LOG (STEP_ID, ACCEPT_MONTH, BUSIFORM_ID, UPDATE_DATE, BUSIFORM_NODE_ID, ACCEPT_DEPART_ID, ACCEPT_STAFF_ID, VALID_TAG, TRANS_TYPE, TRANS_ID, UPDATE_STAFF_ID, CREATE_DATE, TRANS_INFO, UPDATE_DEPART_ID, TRANS_CODE)

VALUES (:STEP_ID, :ACCEPT_MONTH, :BUSIFORM_ID, to_date(:UPDATE_DATE, 'yyyy-mm-dd hh24:mi:ss'), :BUSIFORM_NODE_ID,
                  :ACCEPT_DEPART_ID, :ACCEPT_STAFF_ID, :VALID_TAG, :TRANS_TYPE, :TRANS_ID, :UPDATE_STAFF_ID,
        to_date(:CREATE_DATE, 'yyyy-mm-dd hh24:mi:ss'), rawtohex(:TRANS_INFO), :UPDATE_DEPART_ID, :TRANS_CODE)