SELECT A.FILE_ID,
       A.FILE_NAME,
       A.FTP_SITE,
       A.FILE_PATH,
       A.FILE_TYPE,
       A.FILE_KIND,
       A.FILE_SIZE,
       A.CREA_STAFF,
       TO_CHAR(A.CREA_TIME, 'YYYY-MM-DD HH24:MI:SS') CREA_TIME
  FROM WD_F_FTPFILE A
 WHERE A.FILE_ID = :FILE_ID