SELECT TO_CHAR(U.USER_ID) USER_ID,
       U.INST_ID,
       U.TEL_URL,
       U.SIP_URL,
       U.SIP_URL AS IMPU,
       U.IMPI,
       SUBSTR(U.IMPI, INSTR(U.IMPI, '@') + 1, LENGTH(U.IMPI)) HSS_REALM,
       U.IMS_USER_ID,
       U.IMS_PASSWORD,
       TO_CHAR(U.START_DATE, 'YYYY-MM-DD HH24:MI:SS') AS START_DATE,
       TO_CHAR(U.END_DATE, 'YYYY-MM-DD HH24:MI:SS') AS END_DATE,
       U.RSRV_STR1,
       U.RSRV_STR2,
       U.RSRV_STR3,
       U.RSRV_STR4,
       U.RSRV_STR5
  FROM TF_F_USER_IMPU U
 WHERE U.USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD (TO_NUMBER(:USER_ID), 10000) 
   AND U.RSRV_STR1 = :RSRV_STR1
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE
