SELECT T.TRADE_ID
  FROM TF_BH_TRADE T
 WHERE 1 = 1
   AND T.ACCEPT_MONTH = TO_CHAR(SYSDATE, 'MM')
   AND T.TRADE_TYPE_CODE = '130'
   AND T.BRAND_CODE = 'CPE1'
   AND T.RSRV_STR4 = 'CPE OVER 60G'
   AND T.USER_ID = :USER_ID