SELECT
to_char(TRADE_ID) TRADE_ID, ACCEPT_MONTH, to_char(USER_ID) USER_ID, to_char(USER_ID_A) USER_ID_A, to_char(PLAN_ID) PLAN_ID,PLAN_TYPE_CODE, PLAN_NAME, PLAN_DESC, DEFAULT_TAG, to_char(RULE_ID) RULE_ID, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, MODIFY_TAG, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10
 FROM TF_B_TRADE_USER_PAYPLAN
        WHERE trade_id = :TRADE_ID
        AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
        AND modify_tag != '9'