SELECT A.ACCT_ID,A.PAY_NAME,TO_CHAR(A.OPEN_DATE,'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,A.PAY_MODE_CODE,A.EPARCHY_CODE,A.RSRV_STR8,A.RSRV_STR9,A.RSRV_STR10
,P.DEFAULT_TAG,P.ACT_TAG,P.START_CYCLE_ID,P.END_CYCLE_ID
,U.USER_ID,U.SERIAL_NUMBER,UP.PRODUCT_ID
 FROM TF_F_ACCOUNT A,TF_A_PAYRELATION P,TF_F_USER U,TF_F_USER_PRODUCT UP
 WHERE A.ACCT_ID = P.ACCT_ID(+)
 And A.REMOVE_TAG = '0'
 And (U.REMOVE_TAG = '0' or U.REMOVE_TAG is NULL)
 AND P.USER_ID = U.USER_ID(+)
 AND UP.USER_ID(+) = U.USER_ID
 AND (P.DEFAULT_TAG = '1' OR P.DEFAULT_TAG IS NULL)
 AND (P.ACT_TAG='1' OR P.ACT_TAG IS NULL)
 AND A.CUST_ID = :CUST_ID 
 and P.PARTITION_ID =U.PARTITION_ID(+) 
 AND UP.PARTITION_ID(+) = U.PARTITION_ID
 AND (UP.MAIN_TAG='1' OR UP.MAIN_TAG IS NULL)
 ORDER BY U.SERIAL_NUMBER