UPDATE TF_F_USER_CLUSTER_RELA
   SET  END_DATE  = TO_DATE(:END_DATE,'yyyy-MM-dd HH24:mi:ss'),UPDATE_TIME=SYSDATE
 WHERE GROUP_ID = TO_NUMBER(:GROUP_ID)
 AND END_DATE >TO_DATE(:END_DATE,'yyyy-MM-dd HH24:mi:ss')