INSERT INTO TF_F_USER_CLUSTER_RELA
  (GROUP_ID,
   USER_ID,
   ROLE_CODE,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID
   )
VALUES
  (TO_NUMBER(:GROUP_ID),
   TO_NUMBER(:USER_ID),
   :ROLE_CODE,
   TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID
   )