SELECT A.USER_ID,
       A.SERIAL_NUMBER AS SERIAL_NUMBER,
       A.PRODUCT_ID,
       A.BRAND_CODE,
       A.EPARCHY_CODE,
       A.CITY_CODE,
       A.NET_TYPE_CODE,
       '' REMOVE_TAG,
       '' USER_STATE_CODESET,
       A.ACCEPT_DATE IN_DATE,
       '' OPEN_DATE,
       A.CUST_ID,
       A.CUST_NAME,
       '' CUST_TYPE,
       A.RSRV_STR1 PSPT_TYPE_CODE,
       A.RSRV_STR2 PSPT_ID,
       B.GROUP_ID,
       B.ROLE_CODE,
       B.START_DATE,
       A.SERIAL_NUMBER SERIAL_NUMBER_BAK,
       C.STAND_ADDRESS,
       C.DETAIL_ADDRESS,
       A.TRADE_ID,
       A.ACCT_ID
  FROM TF_B_TRADE             A,
       TF_F_USER_CLUSTER_RELA B,
       TF_B_TRADE_WIDENET     C
 WHERE A.SERIAL_NUMBER LIKE 'W%'
   AND A.TRADE_TYPE_CODE = '101'
   AND B.USER_ID = A.USER_ID
   AND A.TRADE_ID = C.TRADE_ID
   AND A.NET_TYPE_CODE = '04'
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND B.GROUP_ID = :GROUP_ID