UPDATE TF_F_USER_CLUSTER_RELA
    SET ROLE_CODE   = :ROLE_CODE,
        UPDATE_TIME      = SYSDATE,
        UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
        UPDATE_DEPART_ID = :UPDATE_DEPART_ID
  WHERE GROUP_ID = TO_NUMBER(:GROUP_ID)
    AND USER_ID = TO_NUMBER(:USER_ID)
    AND sysdate between start_date AND end_date