--IS_CACHE=Y
SELECT CORP_NO, CORP_NAME, 
	F_RES_GETCODENAME('td_m_res_para', '4001', 'TERMINAL_COOP_TYPE', COOP_TYPE_CODE) COOP_TYPE, COOP_TYPE_CODE,
	COOP_LEVEL, CONTACT, LINK_PHONE, ADDRESS, CORPORATION, SERVICE_PHONE, POST_CODE, EMAIL, SERVICE_DESC, ERP_CODE,
	DECODE(VALID_FLAG,'0','有效','1','无效') VALID_DESC,VALID_FLAG,
	F_RES_GETCODENAME('staff_id', UPDATE_STAFF_ID, '', '') UPDATE_STAFF_NAME,
	TO_CHAR(UPDATE_TIME,'yyyy-MM-dd HH:mm:ss') UPDATE_TIME, REMARK
FROM TD_R_TERMINAL_CORP
WHERE 1=1
 AND (:CORP_NO IS NULL OR CORP_NO = :CORP_NO)
 AND (:CORP_NAME IS NULL OR CORP_NAME LIKE '%' || :CORP_NAME || '%')
 AND (:COOP_TYPE_CODE IS NULL OR COOP_TYPE_CODE = :COOP_TYPE_CODE)
 AND (:VVALID_FLAG IS NULL OR VALID_FLAG = :VVALID_FLAG)
ORDER BY CORP_NAME