SELECT C.SERIAL_NUMBER,C.USER_ID,A.CUST_NAME
  FROM TF_F_CUSTOMER A, TF_F_USER C
 WHERE A.CUST_ID = C.CUST_ID
   AND C.REMOVE_TAG = '0'
   AND A.REMOVE_TAG = '0'
   AND A.PSPT_TYPE_CODE IN ('0', 'A', 'C', 'J', 'I', 'H','2')
   AND 0= F_CHECK_CONTENT_IS_SAME(A.PSPT_ID,'0')
   AND 0= F_CHECK_CONTENT_IS_SAME(A.PSPT_ID,'1')
   AND EXISTS (SELECT 1
          FROM TF_F_CUSTOMER D
         WHERE D.CUST_ID = :CUST_ID
           AND A.PSPT_TYPE_CODE = D.PSPT_TYPE_CODE
           AND A.PSPT_ID = D.PSPT_ID
           AND A.CUST_NAME = D.CUST_NAME)
   AND EXISTS
 (SELECT 1
          FROM TF_F_USER_PRODUCT B
         WHERE B.USER_ID = C.USER_ID
           AND B.MAIN_TAG = '1'
           AND B.BRAND_CODE IN ('G001', 'G002', 'G010')
           AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE)
    AND ROWNUM<11