--IS_CACHE=N
SELECT DETAIL.DEPART_KIND_CODE 部门类型,DETAIL.SALE_DEPART_ID 受理部门,DETAIL.SALE_TIME 受理月份,DETAIL.BUSI_ID 台账标识, DETAIL.SALE_POLICY 终端费用, DETAIL.SUB_BUSI_TYPE 终端类型,DECODE(DETAIL.SUB_BUSI_TYPE,'CONTACTSALE','242','242') 业务编码
   FROM (SELECT TO_CHAR(T3.DONE_TIME, 'YYYYMM') SALE_TIME,
   T3.ORG_ID SALE_DEPART_ID,
   T3.RSRV_NUM1 SALE_POLICY,
   (CASE
    WHEN (SELECT COUNT(1)
            FROM UOP_CRM1.TD_S_COMMPARA CM
           WHERE CM.SUBSYS_CODE = 'CSM'
             AND CM.PARAM_ATTR = 8811
             AND CM.PARAM_CODE = 'CHK_TDSALEACTIVE'
             AND CM.PARA_CODE1 = TO_CHAR(T3.RSRV_STR3)
             AND (CM.PARA_CODE2 IS NULL OR
                 CM.PARA_CODE2 = TO_CHAR(T3.RSRV_STR4))
             AND SYSDATE BETWEEN CM.START_DATE AND CM.END_DATE) > 0 THEN
     'BARESALE'
    WHEN T3.BUSI_TYPE_ID IN ('41130') THEN
     'CONTACTSALE'
    WHEN T3.BUSI_TYPE_ID IN ('41120') THEN
     'BARESALE'
   END) SUB_BUSI_TYPE,
   E.DEPART_KIND_CODE DEPART_KIND_CODE,
   T3.RECORD_ID BUSI_ID
   FROM TD_M_DEPART E,UCR_RES.RES_SKU_ITEMVAL@DBLK_IUPCDB1 T, UCR_RES.TM_USED@DBLK_IUPCDB1 T1,UCR_RES.RES_RECORD_TERM@DBLK_IUPCDB1 T3
   WHERE T.RES_SKU_ID = T1.RES_SKU_ID
    AND T1.IMEI=T3.IMEI
    AND E.DEPART_ID=T3.ORG_ID
    AND T.ITEM_CODE = 'MOBTEL_ATTR_PRODUCTLEVEL'
    AND T.ITEM_VAL_CODE IN ('DEPTHCOOPERATION')
    AND T3.BUSI_TYPE_ID IN (41130,41120)
    AND T3.DONE_TIME > TRUNC(SYSDATE) - 3
    AND T3.IMEI=:SERIAL_NUMBER
   ORDER BY T3.DONE_TIME DESC) DETAIL