--IS_CACHE=Y
SELECT PARAM_CODE,PARAM_NAME,PARA_CODE1,PARA_CODE2,PARA_CODE3 FROM TD_S_COMMPARA
WHERE PARAM_ATTR = '3788' 
AND PARAM_CODE = :ORG_DOMAIN
AND (PARA_CODE1 = :BIZ_TYPE_CODE OR PARA_CODE1 = 'ZZZZ' )
AND (PARA_CODE2 = :SP_CODE OR PARA_CODE2 = 'ZZZZ' )
AND (PARA_CODE3 = :BIZ_CODE OR PARA_CODE3 = 'ZZZZ' )