--IS_CACHE=Y
SELECT A.DEPART_ID, A.DEPART_NAME, A.DEPART_CODE, A.AREA_CODE, A.USER_DEPART_CODE
  FROM TD_M_DEPART A, TD_M_DEPARTKIND B
 WHERE A.DEPART_KIND_CODE = B.DEPART_KIND_CODE
   AND B.CODE_TYPE_CODE = '0'
   AND VALIDFLAG = '0'
   AND A.DEPART_ID = :DEPART_ID