SELECT PARTITION_ID,SERIAL_NUMBER,USER_ID,SERVICE_ID,
SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,
OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,START_DATE,END_DATE,UPDATE_TIME
FROM TF_F_USER_PLATSVC 
WHERE USER_ID=:USER_ID
AND  (BIZ_TYPE_CODE=:BIZ_TYPE_CODE OR :BIZ_TYPE_CODE IS NULL)
AND  ORG_DOMAIN =:ORG_DOMAIN
AND  BIZ_STATE_CODE IN ('A','N')
AND  SP_CODE NOT LIKE 'SW%' 
AND  SYSDATE BETWEEN START_DATE AND END_DATE
