Select TRADE_ID,ACCEPT_MONTH,USER_ID,CANCEL_TAG,STAND_ADDRESS,DETAIL_ADDRESS,
SIGN_PATH,PORT_TYPE,SECRET,STAND_ADDRESS_CODE,MODIFY_TAG,START_DATE,END_DATE 
from Tf_b_Trade_Telephone t 
where trade_id = :TRADE_ID 
and accept_month = to_number(substr(:TRADE_ID,5,2))