SELECT A.INST_ID,A.START_DATE, FROM TF_F_USER_DISCNT A
 WHERE A.USER_ID = :USER_ID
   AND A.DISCNT_CODE = :DISCNT_CODE
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND NOT EXISTS (SELECT 1
          FROM TF_B_TRADE C, TF_B_TRADE_DISCNT D
         WHERE C.TRADE_ID = D.TRADE_ID
           AND C.USER_ID = :USER_ID
           AND D.DISCNT_CODE = :DISCNT_CODE
           AND D.MODIFY_TAG = '1')
