SELECT A.USER_ID,
       A.PARTITION_ID,
       A.UPDATE_TYPE,
       A.UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK
  FROM TF_F_USER_EXPAND A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.UPDATE_TYPE =
       (SELECT B.PARA_CODE1
          FROM TD_S_COMMPARA B
         WHERE B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_ATTR = '111'
           AND B.PARAM_CODE = :TRADE_TYPE_CODE)