UPDATE TF_F_CUST_FAMILYMEB
   SET MEMBER_CUST_ID   = TO_NUMBER(:MEMBER_CUST_ID),
       PARTITION_ID     = MOD(TO_NUMBER(:MEMBER_CUST_ID), 10000),
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       UPDATE_TIME      = SYSDATE
 WHERE PARTITION_ID = MOD(TO_NUMBER(:RSRV_STR1), 10000)
   AND MEMBER_CUST_ID = TO_NUMBER(:RSRV_STR1)
   AND REMOVE_TAG = :REMOVE_TAG