SELECT DECODE(F_CSB_ENCRYPT_NETPWD(:USER_PASSWD, :USER_ID),
              RSRV_STR5,
              '0',
              '-1') RS
  FROM TF_F_USER
 WHERE USER_ID = :USER_ID
 	AND PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)