SELECT IMEI TERMINAL_ID, RESULT, '0' PRE_TERMINAL_STATE, UNSUCREASON UNSUC_REASON, 
	decode(RESULT,'0','6','1','1') TERMINAL_STATE,
	REMARK UNSUC_COMMENT, OPRNUMB OPER_TRADE_ID
FROM TI_R_ARRIVALDATA_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')