INSERT INTO TF_F_USER_PLAT_ORDER
  (PARTITION_ID,
   USER_ID,
   SERIAL_NUMBER,
   BIZ_CODE,
   SP_CODE,
   PRODUCT_NO,
   BIZ_TYPE_CODE,
   ORG_DOMAIN,
   OPR_SOURCE,
   BIZ_STATE_CODE,
   START_DATE,
   END_DATE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   BILL_TYPE,
   PRICE,
   SUBSCRIBE_ID,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_STR6,
   RSRV_STR7,
   RSRV_STR8,
   RSRV_STR9,
   RSRV_STR10,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_DATE4,
   RSRV_DATE5,
   REMARK,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   UPDATE_TIME)
  SELECT MOD(TO_NUMBER(USER_ID),10000) PARTITION_ID,
         to_char(USER_ID) USER_ID,
         SERIAL_NUMBER,
         BIZ_CODE,
         SP_CODE,
         PRODUCT_NO,
         BIZ_TYPE_CODE,
         ORG_DOMAIN,
         OPR_SOURCE,
         :BIZ_STATE_CODE,
         TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
         TO_DATE('2049-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
         FIRST_DATE,
         FIRST_DATE_MON,
         GIFT_SERIAL_NUMBER,
         GIFT_USER_ID,
         BILL_TYPE,
         PRICE,
         to_char(SUBSCRIBE_ID) SUBSCRIBE_ID,
         RSRV_NUM1,
         RSRV_NUM2,
         RSRV_NUM3,
         to_char(RSRV_NUM4) RSRV_NUM4,
         to_char(RSRV_NUM5) RSRV_NUM5,
         RSRV_STR1,
         RSRV_STR2,
         RSRV_STR3,
         RSRV_STR4,
         RSRV_STR5,
         RSRV_STR6,
         RSRV_STR7,
         RSRV_STR8,
         RSRV_STR9,
         RSRV_STR10,
         RSRV_DATE1,
         RSRV_DATE2,
         RSRV_DATE3,
         RSRV_DATE4,
         RSRV_DATE5,
         REMARK,
         UPDATE_STAFF_ID,
         UPDATE_DEPART_ID,
         UPDATE_TIME
    FROM TF_B_TRADE_PLAT_ORDER_BAK a
   WHERE a.partition_id=MOD(TO_NUMBER(:TRADE_ID),10000)
       AND a.trade_id = :TRADE_ID  
     AND sysdate BETWEEN a.start_date AND a.end_date
     AND EXISTS
   (SELECT 1
            FROM td_s_commpara
           WHERE param_attr = :PARAM_ATTR
             AND param_code = to_char(a.BIZ_TYPE_CODE)
             AND sysdate BETWEEN start_date AND end_date)