select t.* 
from TF_F_USER_DISCNT t 
where 1=1 
and (SYSDATE between START_DATE and END_DATE) 
and USER_ID =TO_NUMBER(:USER_ID) 
and PARTITION_ID = MOD(:USER_ID, 10000) 
and RELATION_TYPE_CODE =:RELATION_TYPE_CODE
and RSRV_STR4 = :RSRV_STR4