SELECT T.EXTRA_ID,
       T.EXTRA_TYPE,
       T.EXTRA_KEY,
       T.EXTRA_VALUE,
       T.EXTRA_NAME,
       T.EXTRA_DESC,
       T.VALID_TAG,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4
  FROM TD_B_EOP_EXTRA T
 WHERE T.EXTRA_ID = :EXTRA_ID
   AND T.EXTRA_TYPE = :EXTRA_TYPE
   AND T.EXTRA_KEY = :EXTRA_KEY
   AND T.VALID_TAG = :VALID_TAG
