--IS_CACHE=Y
SELECT *
  FROM TD_S_COMMPARA B
 WHERE B.PARA_CODE1 = :PARA_CODE1
   AND SUBSYS_CODE = :SUBSYS_CODE
   AND PARAM_ATTR = :PARAM_ATTR
   AND PARAM_CODE = :PARAM_CODE
   AND PARA_CODE2 = :PARA_CODE2
   AND (eparchy_code = :EPARCHY_CODE or eparchy_code = 'ZZZZ')
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE