SELECT T.PRODUCT_ORDER_ID,
       CASE
         WHEN T.MODIFY_TAG = '0' THEN
          '增加'
         WHEN T.MODIFY_TAG = '1' THEN
          '删除'
         WHEN T.MODIFY_TAG = '2' THEN
          '修改'
       END MODIFY_TAG,
       '等待归档' AS STATE,
       T.GROUP_ID,
       T.MERCH_SPEC_CODE,
       T.PRODUCT_SPEC_CODE,
       T1.ACCEPT_DATE,
       T1.FINISH_DATE,
       T1.TRADE_STAFF_ID
  FROM TF_B_TRADE_GRP_MERCHP T, TF_B_TRADE T1, TF_B_TRADE_GRP_MERCH T2
 WHERE T.TRADE_ID = T1.TRADE_ID
   AND T.TRADE_ID = T2.TRADE_ID
   AND T.PRODUCT_SPEC_CODE = :PRODUCTSPECNUMBER
   AND T.MERCH_SPEC_CODE = :POSPECNUMBER
   AND T.GROUP_ID = :GROUP_ID
   AND T.PRODUCT_ORDER_ID = :PRODUCT_ORDER_ID
   AND SYSDATE > T.START_DATE
   AND SYSDATE < T.END_DATE
   AND SYSDATE > T2.START_DATE
   AND SYSDATE < T2.END_DATE
