SELECT  TRADE_ID,
				ACCEPT_MONTH,
				PAY_MONEY_CODE,
				MONEY,
				TO_CHAR(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'),
				UPDATE_STAFF_ID,
				UPDATE_DEPART_ID,
				REMARK,
				RSRV_STR1,
				RSRV_STR2,
				RSRV_STR3,
				RSRV_STR4,
				RSRV_STR5,
				RSRV_STR6,
				RSRV_STR7,
				RSRV_STR8,
				RSRV_STR9,
				RSRV_STR10,
				ORDER_ID
FROM TF_B_TRADEFEE_PAYMONEY
WHERE TRADE_ID = :TRADE_ID
AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))