SELECT /*+ use_nl(b t)*/T.SERIAL_NUMBER,B.TRADE_ID OTHER_TRADE_ID, T.USER_ID,B.RSRV_STR1,T.SERIAL_NUMBER,T.CUST_ID,T.TRADE_STAFF_ID,
                        T.TRADE_DEPART_ID,T.TRADE_ID,B.UPDATE_STAFF_ID,B.INST_ID
  FROM UOP_CRM1.TF_BH_TRADE T,UOP_CRM1.TF_F_USER_OTHER B 
 WHERE T.SUBSCRIBE_STATE = 'A' 
  AND  T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(b.rsrv_str5,5,2))  
 AND t.trade_id=to_number(b.rsrv_str5)  
   AND T.TRADE_TYPE_CODE = '600'
   AND T.FINISH_DATE >= TRUNC(SYSDATE, 'DD')
   AND T.FINISH_DATE < TRUNC(SYSDATE, 'DD') + 1 
   AND T.USER_ID=B.USER_ID  
   AND B.RSRV_TAG2 = '1'
   AND SYSDATE < B.END_DATE
   AND B.START_DATE < B.END_DATE
   AND B.RSRV_VALUE_CODE = 'FTTH_GROUP'