 UPDATE TF_B_ORDER_PRE
    SET END_DATE     = sysdate,
        ACCEPT_STATE = :ACCEPT_STATE,
        ACCEPT_RESULT = :ACCEPT_RESULT,
        REPLY_STATE = :REPLY_STATE_NEW
  WHERE SERIAL_NUMBER = :SERIAL_NUMBER
  	AND PRE_TYPE = :PRE_TYPE
  	AND REPLY_STATE = :REPLY_STATE_OLD