SELECT PRE_ID,PRE_TYPE, ACCEPT_MONTH ,ACCEPT_STATE ,REQUEST_ID, ORDER_ID, 
to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, 
to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, 
TRADE_TYPE_CODE, SERIAL_NUMBER ,REPLY_STATE ,REPLY_TIME, 
REPLY_CONTENT ,ACCEPT_RESULT, ACCEPT_DATA1, ACCEPT_DATA2, ACCEPT_DATA3 ,ACCEPT_DATA4, 
ACCEPT_DATA5, REMARK, SVC_NAME, RSRV_STR1 ,RSRV_STR2 ,RSRV_STR3 ,RSRV_STR4 ,RSRV_STR5
  from TF_B_ORDER_PRE
 WHERE PRE_TYPE = :PRE_TYPE
   AND SYSDATE BETWEEN START_DATE AND END_DATE
   AND (REPLY_STATE = :REPLY_STATE  OR REPLY_STATE IS NULL)
   AND ACCEPT_STATE = :ACCEPT_STATE
   AND SERIAL_NUMBER = :SERIAL_NUMBER
