SELECT 
       uu.partition_id,
       to_char(uu.user_id_a) user_id_a,
       to_char(uu.user_id_b) user_id_b,
       uu.relation_type_code,
       uu.role_code_a,
       uu.role_code_b,
       uu.orderno,
       uu.short_code,
       to_char(uu.start_date, 'yyyy-mm-dd hh24:mi:ss') start_date,
       to_char(uu.end_date, 'yyyy-mm-dd hh24:mi:ss') end_date,
       uu.serial_number_a,
       uu.serial_number_b,
       u.PARTITION_ID,
       TO_CHAR(u.USER_ID) USER_ID,
       TO_CHAR(u.CUST_ID) CUST_ID,
       TO_CHAR(u.USECUST_ID) USECUST_ID,
       u.BRAND_CODE,
       u.PRODUCT_ID,
       u.EPARCHY_CODE,
       u.CITY_CODE,
       u.USER_PASSWD,
       u.USER_TYPE_CODE,
       u.SERIAL_NUMBER,
       TO_CHAR(u.SCORE_VALUE) SCORE_VALUE,
       u.CREDIT_CLASS,
       TO_CHAR(u.BASIC_CREDIT_VALUE) BASIC_CREDIT_VALUE,
       TO_CHAR(u.CREDIT_VALUE) CREDIT_VALUE,
       u.ACCT_TAG,
       u.PREPAY_TAG,
       TO_CHAR(u.IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE,
       TO_CHAR(u.OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       u.REMOVE_TAG,
       TO_CHAR(u.DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME,
       TO_CHAR(u.PRE_DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') PRE_DESTROY_TIME,
       TO_CHAR(u.FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       TO_CHAR(u.LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,
       u.OPEN_MODE,
       u.USER_STATE_CODESET,
       u.MPUTE_MONTH_FEE,
       TO_CHAR(u.MPUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') MPUTE_DATE,
       u.RSRV_STR1,
       u.RSRV_STR2,
       u.RSRV_STR3,
       u.RSRV_STR4,
       u.RSRV_STR5,
       u.RSRV_STR6,
       u.RSRV_STR7,
       u.RSRV_STR8,
       u.RSRV_STR9,
       u.RSRV_STR10,
       TO_CHAR(u.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TF_F_RELATION_UU uu, TF_F_USER u
 WHERE 1=1
   AND u.CUST_ID = TO_NUMBER(:CUST_ID)  
   AND u.REMOVE_TAG='0'
   AND u.PRODUCT_ID = to_number(:PRODUCT_ID)
   AND uu.USER_ID_A = u.USER_ID
   AND SYSDATE BETWEEN uu.start_date AND uu.end_date