SELECT A.CUST_ID,A.SERIAL_NUMBER SERIAL_NUMBER,MAX(A.ACCEPT_DATE) ACCEPT_DATE
FROM TF_BH_TRADE A
WHERE A.ACCEPT_DATE >= TO_DATE(:START_DATE, 'yyyy-mm-dd')
AND A.ACCEPT_DATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd') + 1
AND A.TRADE_STAFF_ID BETWEEN :START_STAFF_ID AND :END_STAFF_ID
AND A.TRADE_CITY_CODE = :TRADE_CITY_CODE
AND A.TRADE_TYPE_CODE = 80
GROUP BY A.SERIAL_NUMBER,A.CUST_ID