INSERT INTO TI_BH_TRADE_INTERFACE
  SELECT *
    FROM TI_B_TRADE_INTERFACE
   WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND CANCEL_TAG = :CANCEL_TAG