   SELECT C.*,
       A.PRODUCT_ID,
       A.PACKAGE_ID, 
       A.PRODUCT_NAME,
       A.PACKAGE_NAME
  FROM TF_F_USER_SALE_ACTIVE A, TD_S_COMMPARA B,TF_F_USER_DISCNT C,TF_F_USER_OFFER_REL R
 WHERE A.PRODUCT_ID = TO_NUMBER(B.PARA_CODE1)
   AND A.PACKAGE_ID = TO_NUMBER(NVL(B.PARA_CODE2, A.PACKAGE_ID))
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 173
   AND B.PARAM_CODE = TO_CHAR(:PARAM_CODE)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND C.USER_ID = A.USER_ID
   AND R.USER_ID = C.USER_ID
   AND C.INST_ID = R.REL_OFFER_INS_ID
   AND R.REL_OFFER_TYPE = 'D'
   AND R.OFFER_CODE = A.PACKAGE_ID
   AND R.OFFER_TYPE = 'K'
   AND R.END_DATE > SYSDATE
   AND C.END_DATE > SYSDATE
   AND R.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND C.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND TO_CHAR(C.END_DATE, 'yyyymm') >= TO_CHAR(SYSDATE, 'yyyymm')