SELECT to_char(TRADE_ID) TRADE_ID,to_char(USER_ID) USER_ID,SERIAL_NUMBER,BIZ_TYPE_CODE,ORG_DOMAIN,OPR_SOURCE,PASSWD,BIZ_STATE_CODE,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,MODIFY_TAG,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,to_char(RSRV_NUM4) RSRV_NUM4,to_char(RSRV_NUM5) RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,REMARK,TRADE_STAFF_ID,TRADE_DEPART_ID,to_char(TRADE_TIME,'yyyy-mm-dd hh24:mi:ss') TRADE_TIME
  FROM TF_B_TRADE_MBMP
 WHERE trade_id=TO_NUMBER(:TRADE_ID)
  AND USER_ID=TO_NUMBER(:USER_ID)
  and BIZ_TYPE_CODE=:BIZ_TYPE_CODE
  and ORG_DOMAIN=:ORG_DOMAIN