--IS_CACHE=N
SELECT TO_CHAR(DEAL_TIME, 'yyyy-mm-dd hh24:MI:ss') 变更时间,
            ABS(CHANGE_SCORE) 变更积分
       FROM CHNL_CU_SMSREC_PARALLEL
      WHERE CUMU_ID = :CUMU_ID
        AND DEAL_TYPE = :DEAL_TYPE
        AND DEAL_TIME > SYSDATE - :SERIAL_NUMBER
      ORDER BY DEAL_TIME