--IS_CACHE=N
SELECT A.PARTITION_ID PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       A.INST_TYPE INST_TYPE,
       A.RELA_INST_ID RELA_INST_ID,
       A.INST_ID INST_ID,
       A.ATTR_CODE ATTR_CODE,
       A.ATTR_VALUE ATTR_VALUE,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(A.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       A.UPDATE_STAFF_ID UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID UPDATE_DEPART_ID,
       A.REMARK REMARK,
       A.RSRV_NUM1 RSRV_NUM1,
       A.RSRV_NUM2 RSRV_NUM2,
       A.RSRV_NUM3 RSRV_NUM3,
       TO_CHAR(A.RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(A.RSRV_NUM5) RSRV_NUM5,
       A.RSRV_STR1 RSRV_STR1,
       A.RSRV_STR2 RSRV_STR2,
       A.RSRV_STR3 RSRV_STR3,
       A.RSRV_STR4 RSRV_STR4,
       A.RSRV_STR5 RSRV_STR5,
       TO_CHAR(A.RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(A.RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(A.RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       A.RSRV_TAG1 RSRV_TAG1,
       A.RSRV_TAG2 RSRV_TAG2,
       A.RSRV_TAG3 RSRV_TAG3,
       :TRADE_ID TRADE_ID
  FROM TF_F_USER_ATTR A, UCR_CRM1.TF_B_TRADE_PLATSVC B
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND B.TRADE_ID = :TRADE_ID
   AND A.RELA_INST_ID = B.INST_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
