Insert into UCR_CRM1.TF_F_USER_REWARD
   (PARTITION_ID, USER_ID, BRAND_CODE, PRODUCT_ID, EPARCHY_CODE, 
    NET_TYPE_CODE, SERIAL_NUMBER, IN_DATE, IN_STAFF_ID, IN_DEPART_ID, 
    DEVELOP_STAFF_ID, DEVELOP_DATE, DEVELOP_DEPART_ID, REMOVE_TAG, UPDATE_TIME, 
    UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, 
    RSRV_NUM3, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_DATE1, 
    RSRV_DATE2, RSRV_DATE3)
 Values
   (TO_NUMBER(:PARTITION_ID), TO_NUMBER(:USER_ID), :BRAND_CODE, TO_NUMBER(:PRODUCT_ID), :EPARCHY_CODE, 
    :NET_TYPE_CODE, :SERIAL_NUMBER, to_date(:IN_DATE,'yyyy-mm-dd hh24:mi:ss'), :IN_STAFF_ID, :IN_DEPART_ID, 
    :DEVELOP_STAFF_ID, to_date(:DEVELOP_DATE,'yyyy-mm-dd hh24:mi:ss'), :DEVELOP_DEPART_ID, :REMOVE_TAG, to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss'), 
    :UPDATE_STAFF_ID, :UPDATE_DEPART_ID, :REMARK, TO_NUMBER(:RSRV_NUM1), TO_NUMBER(:RSRV_NUM2), 
    TO_NUMBER(:RSRV_NUM3), :RSRV_STR1, :RSRV_STR2, :RSRV_STR3,  to_date(:RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') , 
    to_date(:RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') , to_date(:RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss'))