UPDATE TI_B_PLATSVC a SET a.modify_tag = '2'
        WHERE EXISTS(SELECT 1 FROM ( SELECT PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                                     FROM TI_B_PLATSVC
                                     WHERE sync_sequence = to_number(:SYNC_SEQUENCE)
                                     AND modify_tag = '9'
                                     MINUS
                                     SELECT PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,SERVICE_ID,SERIAL_NUMBER,SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,GIFT_SERIAL_NUMBER,GIFT_USER_ID,SUBSCRIBE_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                                     FROM TF_B_TRADE_PLATSVC_BAK
                                     WHERE trade_id = to_number(:TRADE_ID)
                                     AND accept_month = :ACCEPT_MONTH ) t1
                     WHERE a.user_id = t1.user_id
                       AND a.service_id = t1.service_id
                       AND a.start_date = t1.start_date)
        AND sync_sequence = to_number(:SYNC_SEQUENCE)
        AND modify_tag = '9'