INSERT INTO TF_F_USER_SERVICE_TIMER
select　MOD(TO_NUMBER(USER_ID),10000),USER_ID,INTF_MODE, SALE_PROJECT_ID,ELEMENT_TYPE_CODE,ELEMENT_ID,PARA_CODE1,PARA_CODE2,PARA_CODE3,PARA_CODE4,PARA_CODE5,PARA_CODE6,PARA_CODE7,PARA_CODE8,MODIFY_TAG,TRADE_ID,EXEC_TIME,PROCESS_TAG,FINISH_TIME,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5
from tf_b_trade_service_timer
where trade_id=:TRADE_ID