SELECT TRADE_ID,CANCEL_TAG,'' ACCEPT_DATE,'' TRADE_DEPART_ID,
'' TRADE_STAFF_ID,-1 TRADE_TYPE_CODE,'' PARAM_CODE,'' REMARK,'' AUDIT_STAFF_ID,'' AUDIT_DATE,
'' AUDIT_TAG,
count(*) RSRV_STR1,'' RSRV_STR2,'' RSRV_STR3,'' RSRV_STR4,'' RSRV_STR5,'' RSRV_STR6,'' RSRV_STR7,'' RSRV_STR8
  FROM TS_A_DIFFERINFO
 WHERE TRADE_ID = to_number(:TRADE_ID)
   AND CANCEL_TAG = :CANCEL_TAG
  group by trade_id,cancel_tag