SELECT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, :TRADE_ID TRADE_ID, PARTITION_ID,
             USER_ID, FOREGIFT_CODE, MONEY, CUST_NAME, PSPT_ID, FOREGIFT_IN_DATE,
             FOREGIFT_OUT_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID,
             REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5,
             RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1,
             RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
        FROM TF_F_USER_FOREGIFT A
	WHERE USER_ID = :USER_ID
	AND PARTITION_ID = :PARTITION_ID