INSERT INTO TF_B_TRADE_PLATSVC
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   SP_CODE,
   BIZ_CODE,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   PRODUCT_NO,
   ORG_DOMAIN,
   OPER_CODE,
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   SUBSCRIBE_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_STR6,
   RSRV_STR7,
   RSRV_STR8,
   RSRV_STR9,
   RSRV_STR10,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  SELECT TO_NUMBER(:TRADE_ID),
         TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         USER_ID,
         PRODUCT_ID,
         PACKAGE_ID,
         SERVICE_ID,
         SERIAL_NUMBER,
         SP_CODE,
         BIZ_CODE,
         BIZ_TYPE_CODE,
         'E',
         PRODUCT_NO,
         ORG_DOMAIN,
         DECODE(ORG_DOMAIN, 'PPOC', '02', '07'),
         OPR_SOURCE,
         BILL_TYPE,
         PRICE,
         FIRST_DATE,
         FIRST_DATE_MON,
         GIFT_SERIAL_NUMBER,
         GIFT_USER_ID,
         SUBSCRIBE_ID,
         TO_DATE(:ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss'),
         TO_DATE('2050-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
         TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '用户销户需要退订预约SP业务',
         2,
         RSRV_NUM2,
         RSRV_NUM3,
         RSRV_NUM4,
         RSRV_NUM5,
         RSRV_STR1,
         RSRV_STR2,
         RSRV_STR3,
         RSRV_STR4,
         DECODE(A.ORG_DOMAIN,
                'EWPT',
                '731BIP2B263' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') ||
                TRUNC(DBMS_RANDOM.VALUE(100000, 999999)),
                A.RSRV_STR5),
         '0',
         RSRV_STR7,
         DECODE(A.ORG_DOMAIN,
                'CASH',
                '02',
                'CMMB',
                '02',
                '1258',
                '02',
                RSRV_STR8),
         RSRV_STR9,
         RSRV_STR10,
         RSRV_DATE1,
         RSRV_DATE2,
         RSRV_DATE3,
         RSRV_TAG1,
         DECODE(A.ORG_DOMAIN,
                'DSMP',
                '0',
                'MUSC',
                DECODE(A.BIZ_TYPE_CODE, '25', '0', '1'),
                'RINP',
                '0',
                'EWPT',
                '0',
                'STMM',
                '0',
                'MPAY',
                '0',
                'WLAN',
                '0',
                'RADI',
                '0',
                'PIMM',
                '0',
                'CMMB',
                '0',
                'VGOP',
                DECODE(A.BIZ_TYPE_CODE, '23', '0', '1'),
                'CMGP',
                '0',
                'MGIS',
                '0',
                'LCPT',
                '0',
                'BOSS', --无线音乐变态有时候org_domain=BOSS
                DECODE(A.BIZ_TYPE_CODE, '25', '0', '1'),
                '1'),
         RSRV_TAG3
    FROM TF_F_USER_PLATSVC A
   WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND A.USER_ID = TO_NUMBER(:USER_ID)
     AND A.BIZ_STATE_CODE IN ('A', 'N', 'L')
     AND A.START_DATE = TRUNC(LAST_DAY(SYSDATE) + 1)
     AND EXISTS (SELECT 1
            FROM TD_B_PLATSVC B
           WHERE A.SERVICE_ID = B.SERVICE_ID
             AND B.SERV_TYPE = '1')
     AND A.END_DATE > A.START_DATE