UPDATE TD_S_NONBOSSPARA T
   SET T.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       T.UPDATE_TIME      = SYSDATE,
			 T.END_DATE         = SYSDATE 
 WHERE T.TYPE_ID = :TYPE_ID
   AND T.DATA_ID = :DATA_ID  