SELECT 
INTF_NAME,
IN_MODE_CODE,
CHECK_NECESSARY_PARAM,
FORWORD_TYPE,
SVC_NAME,
SVC_DESCRIPTION,
TRADE_TYPE_CODE,
PARA_CODE1,
PARA_CODE2,
PARA_CODE3,
EPARCHY_CODE,
START_DATE,
END_DATE,
UPDATE_STAFF_ID,
UPDATE_DEPART_ID,
UPDATE_TIME,
REMARK
FROM  TD_S_SERVICE_COLLECTION_CONFIG T 
 WHERE T.INTF_NAME=:INTF_NAME 
  AND  (T.EPARCHY_CODE=:EPARCHY_CODE or T.EPARCHY_CODE='ZZZZ')
  AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE