INSERT INTO TI_B_USER_SHARE
      (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, SHARE_INST_ID, PARTITION_ID,
       SHARE_ID, USER_ID, TRADE_ID, RELA_INST_ID, DISCNT_CODE, DISCNT_CODE_A,
       SHARE_TYPE, END_DATE, START_DATE, REMARK, UPDATE_DEPART_ID,
       UPDATE_STAFF_ID, UPDATE_TIME, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4,
       RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5,
       RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
      SELECT :SYNC_SEQUENCE, substr(:SYNC_SEQUENCE,7,2), '8', B.SHARE_INST_ID,
             MOD(B.USER_ID, 10000), B.SHARE_ID, B.USER_ID, :TRADE_ID,
             B.RELA_INST_ID, B.DISCNT_CODE, B.DISCNT_CODE_A, B.SHARE_TYPE,
             B.END_DATE, B.START_DATE, B.REMARK, B.UPDATE_DEPART_ID,
             B.UPDATE_STAFF_ID, B.UPDATE_TIME, B.RSRV_NUM1, B.RSRV_NUM2,
             B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2,
             B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1, B.RSRV_DATE2,
             B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3
        FROM TF_F_USER_SHARE B
       WHERE B.SHARE_ID = :SHARE_ID  and end_date>sysdate
