UPDATE TF_BH_TRADE
   SET CANCEL_TAG = :CANCEL_TAG, UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_TIME = SYSDATE
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))