--IS_CACHE=Y
--IS_CACHE=N
select a.IMPORT_ID,a.SERV_TYPE,a.SP_CODE,a.SP_NAME,a.SP_NAME_EN,a.SP_SHORT_NAME,a.SP_TYPE,a.SP_STATUS,a.SERV_CODE,a.PROV_CODE,a.BAL_PROV,a.DEV_CODE,a.VALID_DATE,a.EXPIRE_DATE,a.SP_ATTR,a.SP_DESC,a.CS_TEL,a.CS_URL,a.OPER_TYPE,a.IMPORT_DATE,a.OPR_SOURCE,a.FILE_NAME,
b.DATA_TYPE,b.IMPORT_TIME,b.IMPORT_STAFF_ID,b.IMPORT_DEPART_ID,b.DEAL_FLAG,b.DEAL_TIME,b.DEAL_RESULT,b.REMARK
from TD_B_BUREDATA_IMPORT_SPDTL a,TD_B_BUREDATA_BATIMPORT b
where 1 = 1
AND (a.IMPORT_ID = b.IMPORT_ID)
AND (a.IMPORT_ID =:IMPORT_ID) 
AND (b.DEAL_FLAG =:DEAL_FLAG) 
AND (b.IMPORT_STAFF_ID  =:IMPORT_STAFF_ID)  
AND (b.import_time >=to_date(:IMPORT_DATE_START,'YYYY-MM-DD')) 
AND (b.import_time <=to_date(:IMPORT_DATE_END,'YYYY-MM-DD'))
AND (a.SP_STATUS =:SP_STATUS) 
AND (a.SP_CODE  =:SP_CODE)  
AND (a.SP_TYPE =:SP_TYPE) 
AND (a.SP_ATTR =:SP_ATTR)