SELECT COUNT(*) RECORDCOUNT
  FROM TF_F_USER_DISCNT A
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = :USER_ID
   AND A.DISCNT_CODE = :DISCNT_CODE
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE