--IS_CACHE=Y
SELECT SUBSYS_CODE,
       PARAM_ATTR,
       PARAM_CODE,
       PARAM_NAME,
       PARA_CODE1,
       PARA_CODE2,
       PARA_CODE3,
       PARA_CODE4,
       PARA_CODE5,
       PARA_CODE6,
       PARA_CODE7,
       PARA_CODE8,
       PARA_CODE9,
       PARA_CODE10,
       PARA_CODE11,
       PARA_CODE12,
       PARA_CODE13,
       PARA_CODE14,
       PARA_CODE15,
       PARA_CODE16,
       PARA_CODE17,
       PARA_CODE18,
       PARA_CODE19,
       PARA_CODE20,
       PARA_CODE21,
       PARA_CODE22,
       PARA_CODE23,
       PARA_CODE24,
       PARA_CODE25,
       TO_CHAR(PARA_CODE26, 'YYYY-MM-DD HH24:MI:SS') PARA_CODE26,
       TO_CHAR(PARA_CODE27, 'YYYY-MM-DD HH24:MI:SS') PARA_CODE27,
       TO_CHAR(PARA_CODE28, 'YYYY-MM-DD HH24:MI:SS') PARA_CODE28,
       TO_CHAR(PARA_CODE29, 'YYYY-MM-DD HH24:MI:SS') PARA_CODE29,
       TO_CHAR(PARA_CODE30, 'YYYY-MM-DD HH24:MI:SS') PARA_CODE30,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       EPARCHY_CODE,
       REMARK,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME
  FROM TD_S_COMMPARA A
 WHERE A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = '7686'
   AND A.PARA_CODE4 =
       (SELECT MIN(B.PARA_CODE4)
          FROM TD_S_COMMPARA B
         WHERE B.SUBSYS_CODE = A.SUBSYS_CODE
           AND B.PARAM_ATTR = A.PARAM_ATTR
           AND B.PARA_CODE4 IS NOT NULL
           AND SYSDATE < TO_DATE(B.PARA_CODE4, 'YYYY-MM-DD HH24:MI:SS'))