Select A.PARA_CODE1 BIZ_CODE,A.PARA_CODE2 BILL_TYPE,A.PARA_CODE3 PRICE,A.PARA_CODE4 BIZ_TYPE_CODE,
       A.PARA_CODE5 SP_CODE,A.PARA_CODE6 SERV_TYPE,A.PARA_CODE7 SP_NAME,A.PARA_CODE8 SERVICE_ID,
       A.PARA_CODE9 SERVICE_NAME,A.PARA_CODE10 ORG_DOMAIN,A.PARA_CODE11 BIZ_TYPE
 From UCR_CEN1.TD_S_COMMPARA A
Where 0=0
 And A.SUBSYS_CODE = 'CSM'
 And A.PARAM_ATTR = '9'
 And A.PARAM_CODE = 'KEYBUSINESS'
 And A.EPARCHY_CODE = '0898'
 And (Sysdate Between A.START_DATE And A.END_DATE)