SELECT TO_CHAR(IN_TIME, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE1,
       to_char(to_date(START_DATE, 'yyyy-mm-dd hh24:mi:ss'), 'yyyy-mm-dd hh24:mi:ss') PARA_CODE2,
       to_char(to_date(ENTER_DATE, 'yyyy-mm-dd hh24:mi:ss'), 'yyyy-mm-dd hh24:mi:ss') PARA_CODE3,
       SERIAL_NUMBER PARA_CODE4,
       X_CALL_EDMPHONECODE PARA_CODE5,
       REASON_CODE PARA_CODE7,
       DATA_TYPE PARA_CODE6,
       PROCESS_TAG PARA_CODE8,
       TRADE_NUMBER PARA_CODE9,
       MSG_ID PARA_CODE10,
       NOTICE_CONTENT PARA_CODE23,
       TO_CHAR(EXEC_TIME, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE11,
       RSRV_STR1 PARA_CODE12,
       RSRV_STR2 PARA_CODE13,
       RSRV_STR3 PARA_CODE14,
       REMARK PARA_CODE15,
       INTF_ID PARA_CODE16,
       MONTH PARA_CODE17,
       '' PARA_CODE18,
       '' PARA_CODE19,
       '' PARA_CODE20,
       '' PARA_CODE21,
       '' PARA_CODE22,
       '' PARA_CODE24,
       '' PARA_CODE25,
       '' PARA_CODE26,
       '' PARA_CODE27,
       '' PARA_CODE28,
       '' PARA_CODE29,
       '' PARA_CODE30,
       '' START_DATE,
       '' END_DATE,
       '' EPARCHY_CODE,
       '' REMARK,
       '' UPDATE_STAFF_ID,
       '' UPDATE_DEPART_ID,
       '' UPDATE_TIME,
       '' SUBSYS_CODE,
       0 PARAM_ATTR,
       '' PARAM_CODE,
       '' PARAM_NAME
  FROM TL_BH_MONITORFILE A
 WHERE A.SERIAL_NUMBER >= :PARA_CODE1
   AND A.SERIAL_NUMBER <= :PARA_CODE2
   AND (A.DATA_TYPE = :PARA_CODE3 OR :PARA_CODE3 IS NULL)