--IS_CACHE=Y
SELECT A.START_DATE,A.END_DATE
  FROM TD_S_COMMPARA A
 WHERE A.SUBSYS_CODE = :SUBSYS_CODE AND A.PARAM_ATTR = :PARAM_ATTR
   AND A.PARA_CODE2 = :PARA_CODE2
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE