select trade_id para_code1,
       serial_number para_code2,
       req_code para_code3,
       aim_number   para_aim_number,
       login_number para_code4,
       rsp_content para_code5,
       to_char(start_time,'YYYY-MM-DD HH24:MI:SS') para_code6,
       to_char(receive_time,'YYYY-MM-DD HH24:MI:SS') para_code7,
       to_number(to_char(receive_time,'MM')) para_code8,
       '' para_code9,
       '' para_code10,
       '' para_code11,
       '' para_code12,
       '' para_code13,
       '' para_code14,
       '' para_code15,
       '' para_code16,
       '' para_code17,
       '' para_code18,
       '' para_code19,
       '' para_code20,
       '' para_code21,
       '' para_code22,
       '' para_code23,
       '' para_code24,
       '' para_code25,
       '' para_code26,
       '' para_code27,
       '' para_code28,
       '' para_code29,
       '' para_code30,
       '' start_date,
       '' end_date,
       '' eparchy_code,
       '' remark,
       '' update_staff_id,
       '' update_depart_id,
       '' update_time,
       '' subsys_code,
       0 param_attr,
       '' param_code,
       '' param_name
  from tf_b_tradelog_sms_:STAT_MONTH_BEFORE
  where  serial_number = :PARA_CODE1
   and receive_time >= to_date(:PARA_CODE2, 'yyyy-mm-dd')
   and receive_time <= to_date(:PARA_CODE3, 'yyyy-mm-dd')+1
   and rsp_content not like '%密码%'
   UNION ALL   
select trade_id para_code1,
       serial_number para_code2,
       req_code para_code3,
       aim_number   para_aim_number,
       login_number para_code4,
       rsp_content para_code5,
       to_char(start_time,'YYYY-MM-DD HH24:MI:SS') para_code6,
       to_char(receive_time,'YYYY-MM-DD HH24:MI:SS') para_code7,
       to_number(to_char(receive_time,'MM')) para_code8,
       '' para_code9,
       '' para_code10,
       '' para_code11,
       '' para_code12,
       '' para_code13,
       '' para_code14,
       '' para_code15,
       '' para_code16,
       '' para_code17,
       '' para_code18,
       '' para_code19,
       '' para_code20,
       '' para_code21,
       '' para_code22,
       '' para_code23,
       '' para_code24,
       '' para_code25,
       '' para_code26,
       '' para_code27,
       '' para_code28,
       '' para_code29,
       '' para_code30,
       '' start_date,
       '' end_date,
       '' eparchy_code,
       '' remark,
       '' update_staff_id,
       '' update_depart_id,
       '' update_time,
       '' subsys_code,
       0 param_attr,
       '' param_code,
       '' param_name
  from tf_b_tradelog_sms_:STAT_MONTH_AFTER
  where  serial_number = :PARA_CODE1
   and receive_time >= to_date(:PARA_CODE2, 'yyyy-mm-dd')
   and receive_time <= to_date(:PARA_CODE3, 'yyyy-mm-dd')+1
   and rsp_content not like '%密码%'