SELECT TO_CHAR(IN_TIME, 'yyyy-mm-dd hh24:mi:ss') IN_TIME,
       to_date(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_date(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       SERIAL_NUMBER SERIAL_NUMBER,
       X_CALL_EDMPHONECODE X_CALL_EDMPHONECODE,
       REASON_CODE REASON_CODE,
       PROCESS_TAG PROCESS_TAG,
       TRADE_NUMBER TRADE_NUMBER,
       TO_CHAR(EXEC_TIME, 'yyyy-mm-dd hh24:mi:ss') EXEC_TIME,
       RSRV_STR1 RSRV_STR1,
       RSRV_STR2 RSRV_STR2,
       RSRV_STR3 RSRV_STR3,
       REMARK REMARK,
       INTF_ID INTF_ID,
       AUDIT_STAFF_ID,
       AUDIT_DEPART_ID,
       TO_CHAR(AUDIT_TIME, 'yyyy-mm-dd hh24:mi:ss') AUDIT_TIME,
       MONTH MONTH,
       PROV_CODE PROV_CODE,
       CITY_CODE CITY_CODE
  FROM TL_BH_HARASSPHONE A
 WHERE A.IN_TIME BETWEEN TO_DATE(:PARA_CODE1, 'yyyy-mm-dd hh24:mi:ss') AND
       TO_DATE(:PARA_CODE2, 'yyyy-mm-dd hh24:mi:ss')
 AND (A.REASON_CODE = :PARA_CODE4 OR A.REASON_CODE IS NULL)
 AND (A.PROCESS_TAG = :PARA_CODE5 OR A.PROCESS_TAG IS NULL)
 AND A.PROV_CODE = :PARA_CODE6
UNION  
SELECT TO_CHAR(IN_TIME, 'yyyy-mm-dd hh24:mi:ss') IN_TIME,
       to_date(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_date(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       SERIAL_NUMBER SERIAL_NUMBER,
       X_CALL_EDMPHONECODE X_CALL_EDMPHONECODE,
       REASON_CODE REASON_CODE,
       PROCESS_TAG PROCESS_TAG,
       TRADE_NUMBER TRADE_NUMBER,
       TO_CHAR(EXEC_TIME, 'yyyy-mm-dd hh24:mi:ss') EXEC_TIME,
       RSRV_STR1 RSRV_STR1,
       RSRV_STR2 RSRV_STR2,
       RSRV_STR3 RSRV_STR3,
       REMARK REMARK,
       INTF_ID INTF_ID,
       AUDIT_STAFF_ID,
       AUDIT_DEPART_ID,
       TO_CHAR(AUDIT_TIME, 'yyyy-mm-dd hh24:mi:ss') AUDIT_TIME,
       MONTH MONTH,
       PROV_CODE PROV_CODE,
       CITY_CODE CITY_CODE
  FROM TL_B_HARASSPHONE A
 WHERE A.IN_TIME BETWEEN TO_DATE(:PARA_CODE1, 'yyyy-mm-dd hh24:mi:ss') AND
       TO_DATE(:PARA_CODE2, 'yyyy-mm-dd hh24:mi:ss')
 AND (A.REASON_CODE = :PARA_CODE4 OR A.REASON_CODE IS NULL)
 AND (A.PROCESS_TAG = :PARA_CODE5 OR A.PROCESS_TAG IS NULL)
 AND A.PROV_CODE = :PARA_CODE6