SELECT SERIAL_NUMBER_A PARA_CODE1,
       FOREGIFT PARA_CODE2,
       DEPOSIT PARA_CODE3,
       PLAN_BEGIN PARA_CODE4,
       PLAN_END PARA_CODE5,
       START_DATE PARA_CODE6,
       END_DATE PARA_CODE7,
       TRANS_COUNT PARA_CODE8,
       OPEN_TAG PARA_CODE9,
       UPDATE_STAFF_ID PARA_CODE10,
       UPDATE_TIME PARA_CODE11,
       RSRV_STR1 PARA_CODE12,
       RSRV_STR2 PARA_CODE13,
       RSRV_STR3 PARA_CODE14,
       RSRV_STR4 PARA_CODE15,
       RSRV_STR5 PARA_CODE16,
       RSRV_DATE1 PARA_CODE17,
       RSRV_DATE2 PARA_CODE18,
       RSRV_DATE3 PARA_CODE19,
       RSRV_NUM1 PARA_CODE20,
       RSRV_NUM2 PARA_CODE21,
       RSRV_NUM3 PARA_CODE22,
       REMARK PARA_CODE23,
       '' PARA_CODE24,
       '' PARA_CODE25,
       '' PARA_CODE26,
       '' PARA_CODE27,
       '' PARA_CODE28,
       '' PARA_CODE29,
       '' PARA_CODE30,
       '' START_DATE,
       '' END_DATE,
       '' EPARCHY_CODE,
       '' REMARK,
       '' UPDATE_STAFF_ID,
       '' UPDATE_DEPART_ID,
       '' UPDATE_TIME,
       '' SUBSYS_CODE,
       0 PARAM_ATTR,
       '' PARAM_CODE,
       '' PARAM_NAME
FROM TF_SA_ACTION_CODE
 WHERE SERIAL_NUMBER_A = :PARA_CODE1
AND (:PARA_CODE2 = '' OR :PARA_CODE2 IS NULL)
AND (:PARA_CODE3 = '' OR :PARA_CODE3 IS NULL)
AND (:PARA_CODE4 = '' OR :PARA_CODE4 IS NULL)
AND (:PARA_CODE5 = '' OR :PARA_CODE5 IS NULL)
AND (:PARA_CODE6 = '' OR :PARA_CODE6 IS NULL)
AND (:PARA_CODE7 = '' OR :PARA_CODE7 IS NULL)
AND (:PARA_CODE8 = '' OR :PARA_CODE8 IS NULL)
AND (:PARA_CODE9 = '' OR :PARA_CODE9 IS NULL)
AND (:PARA_CODE10 = '' OR :PARA_CODE10 IS NULL)