SELECT b.SUBSYS_CODE,b.PARAM_ATTR,b.PARAM_CODE,b.PARAM_NAME,b.PARA_CODE1,b.PARA_CODE2,b.PARA_CODE3,b.PARA_CODE4,b.PARA_CODE5,b.PARA_CODE6,b.PARA_CODE7,b.PARA_CODE8,b.PARA_CODE9,b.PARA_CODE10,b.PARA_CODE11,b.PARA_CODE12,b.PARA_CODE13,b.PARA_CODE14,b.PARA_CODE15,b.PARA_CODE16,b.PARA_CODE17,b.PARA_CODE18,b.PARA_CODE19,b.PARA_CODE20,b.PARA_CODE21,b.PARA_CODE22,b.PARA_CODE23,b.PARA_CODE24,b.PARA_CODE25,b.PARA_CODE26,b.PARA_CODE27,b.PARA_CODE28,b.PARA_CODE29,b.PARA_CODE30,b.START_DATE,b.END_DATE,b.EPARCHY_CODE,b.REMARK,b.UPDATE_STAFF_ID,b.UPDATE_DEPART_ID,b.UPDATE_TIME 
   FROM tf_f_user_discnt a,td_s_commpara b      
    WHERE  a.discnt_code=to_number(b.para_code5) 
      AND  b.para_code2=:ADISITEM_CODE
      AND  a.partition_id=MOD(TO_NUMBER(:USER_ID),10000)
      AND  a.user_id=TO_NUMBER(:USER_ID)   
      AND  a.start_date<ADD_MONTHS(to_date(:END_TIME,'YYYYMM'),1)
      AND  a.end_date>=to_date(:END_TIME,'YYYYMM')     
      AND  b.param_attr='136'