--IS_CACHE=Y
SELECT SUBSYS_CODE,PARAM_ATTR,PARAM_CODE,PARAM_NAME,PARA_CODE1, PARA_CODE2,EPARCHY_CODE
 FROM TD_S_COMMPARA t
 WHERE t.para_code1=:USER_CLASS 
 AND t.param_code=:TRADE_TYPE_CODE 
 AND t.param_name=:PARAM_NAME
 AND t.subsys_code='CSM' 
 AND t.param_attr='4900'
 AND SYSDATE BETWEEN START_DATE AND END_DATE