SELECT '' SUBSYS_CODE, -1 PARAM_ATTR,
       TO_CHAR(TRUNC(NVL(AVG(NVL(SUM(fee),0)),0))/100) PARAM_CODE,
       '' PARAM_NAME,
       '' PARA_CODE1, '' PARA_CODE2, '' PARA_CODE3, '' PARA_CODE4, '' PARA_CODE5, '' PARA_CODE6,
       '' PARA_CODE7, '' PARA_CODE8, '' PARA_CODE9, '' PARA_CODE10, '' PARA_CODE11, '' PARA_CODE12,
       '' PARA_CODE13, '' PARA_CODE14, '' PARA_CODE15, '' PARA_CODE16, '' PARA_CODE17, '' PARA_CODE18,
       '' PARA_CODE19, '' PARA_CODE20, '' PARA_CODE21, '' PARA_CODE22, '' PARA_CODE23, '' PARA_CODE24,
       '' PARA_CODE25, '' PARA_CODE26, '' PARA_CODE27, '' PARA_CODE28, '' PARA_CODE29, '' PARA_CODE30,
       '' START_DATE, '' END_DATE, '' EPARCHY_CODE, '' REMARK, '' UPDATE_STAFF_ID, '' UPDATE_DEPART_ID, '' UPDATE_TIME
  FROM tf_o_credit_userbill a,td_a_acycpara b
 WHERE a.user_id = TO_NUMBER(:USER_ID)
   AND a.partition_id = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE BETWEEN b.acyc_start_time AND b.acyc_end_time
   AND a.acyc_id BETWEEN b.acyc_id - TO_NUMBER(:MONTHS_NUM) AND b.acyc_id -1
 GROUP BY a.acyc_id