--IS_CACHE=Y
SELECT STAFF_ID PARA_CODE1,
       DEPART_ID PARA_CODE2,
       STAFF_NAME PARA_CODE3,
       JOB_CODE PARA_CODE4,
       MANAGER_INFO PARA_CODE5,
       DECODE(SEX, '0', '男', '1', '女') PARA_CODE6,
       EMAIL PARA_CODE7,
       USER_PID PARA_CODE8,
       SERIAL_NUMBER PARA_CODE9,
       TO_CHAR(CUST_ID) PARA_CODE10,
       DECODE(DIMISSION_TAG, '0', '正常', '1', '已经离职') PARA_CODE11,
       TO_CHAR(BIRTHDAY, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE12,
       STAFF_GROUP_ID PARA_CODE13,
       CUST_HOBYY PARA_CODE14,
       MANAGER_STAFF_ID PARA_CODE15,
       RECEIVE_TYPE_CODE PARA_CODE16,
       LOGIN_FLAG PARA_CODE17,
       CUST_MANAGER_FLAG PARA_CODE18,
       CITY_CODE PARA_CODE19,
       EPARCHY_CODE PARA_CODE20,
       REMARK PARA_CODE21,
       RSVALUE1 PARA_CODE22,
       RSVALUE2 PARA_CODE23,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE24,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE25,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE26,
       UPDATE_STAFF_ID PARA_CODE27,
       UPDATE_DEPART_ID PARA_CODE28,
       '' PARA_CODE29,
       '' PARA_CODE30,
       '' START_DATE,
       '' END_DATE,
       '' EPARCHY_CODE,
       '' REMARK,
       '' UPDATE_STAFF_ID,
       '' UPDATE_DEPART_ID,
       '' UPDATE_TIME,
       '' SUBSYS_CODE,
       0 PARAM_ATTR,
       '' PARAM_CODE,
       '' PARAM_NAME
  FROM TD_M_STAFF A
 WHERE 1 = 1
   AND (:PARA_CODE1 IS NULL OR A.DEPART_ID = :PARA_CODE1)
   AND (:PARA_CODE2 IS NULL OR A.STAFF_ID = :PARA_CODE2)
   AND (:PARA_CODE3 IS NULL OR
       A.STAFF_NAME LIKE '%' || :PARA_CODE3 || '%')
   AND :PARA_CODE4 IS NULL
   AND :PARA_CODE5 IS NULL
   AND :PARA_CODE6 IS NULL
   AND :PARA_CODE7 IS NULL
   AND :PARA_CODE8 IS NULL
   AND :PARA_CODE9 IS NULL
   AND :PARA_CODE10 IS NULL
 ORDER BY STAFF_ID