SELECT TO_CHAR(IN_TIME, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE1,
       to_date(START_DATE, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE2,
       to_date(END_DATE, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE3,
       SERIAL_NUMBER PARA_CODE4,
       X_CALL_EDMPHONECODE PARA_CODE5,
       REASON_CODE PARA_CODE6,
       TO_CHAR(EXEC_TIME, 'yyyy-mm-dd hh24:mi:ss') PARA_CODE7,
       PROCESS_TAG PARA_CODE8,
       TRADE_NUMBER PARA_CODE9,
       EFFECT_TIME PARA_CODE10,
       RSRV_STR1 PARA_CODE11,
       RSRV_STR2 PARA_CODE12,
       RSRV_STR3 PARA_CODE13,
       REMARK PARA_CODE14,
       TO_CHAR(INTF_ID) PARA_CODE15,
       TO_CHAR(MONTH) PARA_CODE16,
       '' PARA_CODE17,
       '' PARA_CODE18,
       '' PARA_CODE19,
       '' PARA_CODE20,
       '' PARA_CODE21,
       '' PARA_CODE22,
       '' PARA_CODE23,
       '' PARA_CODE24,
       '' PARA_CODE25,
       '' PARA_CODE26,
       '' PARA_CODE27,
       '' PARA_CODE28,
       '' PARA_CODE29,
       '' PARA_CODE30,
       '' SUBSYS_CODE,
       0 PARAM_ATTR,
       '' PARAM_CODE,
       '' PARAM_NAME,
       '' REMARK,
       '' START_DATE,
       '' END_DATE,
       '' EPARCHY_CODE,
       '' UPDATE_STAFF_ID,
       '' UPDATE_DEPART_ID,
       '' UPDATE_TIME
  FROM TL_B_HARRYPHONE A
 WHERE A.IN_TIME BETWEEN TO_DATE(:PARA_CODE1, 'yyyy-mm-dd hh24:mi:ss') AND
       TO_DATE(:PARA_CODE2, 'yyyy-mm-dd hh24:mi:ss')
   AND ((:PARA_CODE3 = '' OR :PARA_CODE3 IS NULL) OR
       (REASON_CODE = :PARA_CODE3))
   AND ((:PARA_CODE4 = '' OR :PARA_CODE4 IS NULL) OR
       (PROCESS_TAG = :PARA_CODE4))