--IS_CACHE=Y
SELECT A.PARA_CODE23
  FROM TD_S_COMMPARA A
 WHERE A.SUBSYS_CODE = :SUBSYS_CODE AND A.PARAM_ATTR = :PARAM_ATTR
   AND A.PARA_CODE3 = :PARA_CODE3
   AND A.PARA_CODE4 = :PARA_CODE4
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE