SELECT T.*
  FROM TD_S_COMMPARA T
 WHERE T.SUBSYS_CODE = :SUBSYS_CODE
   AND T.PARAM_ATTR = :PARAM_ATTR
   AND T.PARA_CODE1 = :PARA_CODE1
   AND T.PARA_CODE20 = :PARA_CODE20
   AND (T.EPARCHY_CODE = :EPARCHY_CODE OR T.EPARCHY_CODE = 'ZZZZ')
