INSERT INTO TI_O_BANK_SIGN_FILE
  (SIGN_ID,
USER_TYPE,
USER_VALUE,
BANK_ACCT_ID,
BANK_ACCT_TYPE,
BANK_ID,
PAY_TYPE,
RECH_THRESHOLD,
RECH_AMOUNT,
USER_CAT,
MOBILE_TYPE,
APPLY_DATE,
START_DATE,
END_DATE,
ID_TYPE,
ID_VALUE,
DEAL_TYPE,
DEAL_STATUS,
UPDATE_DATE,
UPDATE_STAFF_ID,
UPDATE_DEPART_ID,
REMARK,
RSRV_STR1,
RSRV_STR2,
RSRV_STR3,
RSRV_STR4,
RSRV_STR5)
  SELECT m.SIGN_ID,
         m.sub_USER_TYPE,
         m.sub_USER_VALUE,
         :RSRV_STR19,
         :RSRV_STR20,
         :RSRV_STR21,
         :PAY_TYPE,
         :RSRV_STR22,
         :RSRV_STR23,
         :RSRV_STR24,
         '02',
         to_date(:APPLY_DATE,'yyyy-mm-dd hh24:mi:ss'),
         m.START_DATE,
         m.END_DATE,
         '',
         '',
         :DEAL_TYPE,
         '0',
         sysdate,
         m.UPDATE_STAFF_ID,
         m.UPDATE_DEPART_ID,
         m.REMARK,
         m.RSRV_STR1,
         m.RSRV_STR2,
         m.RSRV_STR3,
         m.RSRV_STR4,
         m.RSRV_STR5
    FROM Tf_f_Bank_subsign m 
   WHERE m.sub_user_type = :RSRV_STR14
     and m.sub_user_value = :RSRV_STR15 and m.main_user_type=:RSRV_STR11 and m.main_user_value=:RSRV_STR12
     and m.sign_id=:RSRV_STR18 and exists (select 1 from tf_f_user u where u.serial_number=:RSRV_STR15)