 SELECT A.SERVICE_ID,A.BIZ_STATE_CODE,A.INST_ID, 
        TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
        TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_USER_PLATSVC A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.BIZ_STATE_CODE ='E'
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)