SELECT BD.DISCNT_CODE,
       BD.DISCNT_NAME,
       BD.DISCNT_EXPLAIN,
       BD.C_DISCNT_CODE,
       BD.B_DISCNT_CODE,
       BD.A_DISCNT_CODE,
       BD.OBJ_TYPE_CODE,
       BD.DEFINE_MONTHS,
       BD.MONTHS,
       BD.TAG_SET,
       BD.EPARCHY_CODE,
       BD.UPDATE_STAFF_ID,
       BD.UPDATE_DEPART_ID,
       UD.PARTITION_ID,
       UD.USER_ID,
       UD.PRODUCT_ID,
       UD.PACKAGE_ID,
       UD.SPEC_TAG,
       UD.RELATION_TYPE_CODE,
       UD.INST_ID,
       UD.CAMPN_ID,
       PKE.PACKAGE_ID,
       PKE.ELEMENT_TYPE_CODE,
       PKE.ELEMENT_ID,
       PKE.MAIN_TAG,
       PKE.FORCE_TAG,
       PKE.ENABLE_TAG,
       PKE.CANCEL_TAG,
       TO_CHAR(PKE.START_ABSOLUTE_DATE, 'yyyy-MM-dd HH24:mi:ss') START_ABSOLUTE_DATE,
       TO_CHAR(PKE.CANCEL_ABSOLUTE_DATE, 'yyyy-MM-dd HH24:mi:ss') CANCEL_ABSOLUTE_DATE,
       TO_CHAR(UD.START_DATE, 'yyyy-MM-dd HH24:mi:ss') START_DATE,
       TO_CHAR(UD.END_DATE, 'yyyy-MM-dd HH24:mi:ss') END_DATE,
       TO_CHAR(UD.UPDATE_TIME, 'yyyy-MM-dd HH24:mi:ss') UPDATE_TIME
  FROM TF_F_USER_DISCNT UD, TD_B_DISCNT BD, TD_B_PACKAGE_ELEMENT PKE
 WHERE 1 = 1
   AND UD.PACKAGE_ID = PKE.PACKAGE_ID
   AND UD.DISCNT_CODE = BD.DISCNT_CODE
   AND UD.DISCNT_CODE = PKE.ELEMENT_ID
   AND PKE.PACKAGE_ID = :PACKAGE_ID
   AND UD.USER_ID = TO_NUMBER(:USER_ID)
   AND PKE.ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
   AND UD.PARTITION_ID= MOD(TO_NUMBER(:USER_ID),10000)
   AND SYSDATE> UD.END_DATE
   AND UD.END_DATE>= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD')||' 00:00:00','YYYY-MM-DD HH24:MI:SS')