select USER_ID,DISCNT_CODE,INST_ID,START_DATE,END_DATE 
from TF_F_USER_DISCNT
where DISCNT_CODE=:DISCNT_CODE
AND END_DATE= (TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss'))
AND ( RSRV_STR5!='A' or RSRV_STR5 is null)
