SELECT D.PARTITION_ID,
       TO_CHAR(D.USER_ID) USER_ID,
       TO_CHAR(D.USER_ID_A) USER_ID_A,
       TO_CHAR(D.PRODUCT_ID) PRODUCT_ID,
       TO_CHAR(D.PACKAGE_ID) PACKAGE_ID,
       TO_CHAR(D.DISCNT_CODE) DISCNT_CODE,
       D.SPEC_TAG,
       D.RELATION_TYPE_CODE,
       TO_CHAR(D.INST_ID) INST_ID,
       TO_CHAR(D.CAMPN_ID) CAMPN_ID,
       TO_CHAR(D.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(D.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(D.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       D.UPDATE_STAFF_ID,
       D.UPDATE_DEPART_ID,
       D.REMARK,
       TO_CHAR(D.RSRV_NUM1) RSRV_NUM1,
       TO_CHAR(D.RSRV_NUM2) RSRV_NUM2,
       TO_CHAR(D.RSRV_NUM3) RSRV_NUM3,
       TO_CHAR(D.RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(D.RSRV_NUM5) RSRV_NUM5,
       D.RSRV_STR1,
       D.RSRV_STR2,
       D.RSRV_STR3,
       D.RSRV_STR4,
       D.RSRV_STR5,
       TO_CHAR(D.RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(D.RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(D.RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       D.RSRV_TAG1,
       D.RSRV_TAG2,
       D.RSRV_TAG3
  FROM TF_F_USER_DISCNT D
 WHERE D.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND D.USER_ID = TO_NUMBER(:USER_ID)
   AND D.PACKAGE_ID = :PACKAGE_ID
   AND D.END_DATE > D.START_DATE
   AND D.START_DATE > TRUNC(SYSDATE,'MM')
   ORDER BY START_DATE DESC
