SELECT A.DISCNT_CODE ELEMENT_ID,
       'D' ELEMENT_TYPE_CODE,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_USER_DISCNT A
 WHERE  A.END_DATE > SYSDATE
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.END_DATE > A.START_DATE