SELECT A.*
  FROM tf_f_user_discnt A,TF_F_RELATION_XXT B
 WHERE a.user_id_a = :USER_ID_A
   AND a.user_id = :USER_ID
	 AND B.RELA_INST_ID=A.INST_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
	 AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE