SELECT to_char(USER_ID) USER_ID, DISCNT_CODE
  FROM TF_F_USER_DISCNT
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND DISCNT_CODE = :DISCNT_CODE
   AND START_DATE > SYSDATE
   AND END_DATE > START_DATE
