SELECT DISTINCT P.BRAND_CODE, P.PRODUCT_ID, DI.DISCNT_CODE
  FROM TF_F_USER US, TF_F_USER_DISCNT DI,TF_F_USER_PRODUCT P 
 WHERE US.SERIAL_NUMBER = :SN
   AND US.REMOVE_TAG = '0'
   AND DI.USER_ID = US.USER_ID
   AND DI.PARTITION_ID = US.PARTITION_ID
   AND P.USER_ID = US.USER_ID
   AND P.PARTITION_ID = US.PARTITION_ID
   AND P.MAIN_TAG = '1'
   AND SYSDATE BETWEEN DI.START_DATE AND DI.END_DATE