SELECT A.PARTITION_ID,A.USER_ID,A.USER_ID_A,A.DISCNT_CODE,A.SPEC_TAG,A.RELATION_TYPE_CODE,A.INST_ID,A.CAMPN_ID,
to_char(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
from TF_F_USER_DISCNT A
where 1=1 
and (SYSDATE between START_DATE and END_DATE) 
and USER_ID =TO_NUMBER(:USER_ID) 
and PARTITION_ID = MOD(:USER_ID, 10000) 
and DISCNT_CODE =:DISCNT_CODE 
and RELATION_TYPE_CODE =:RELATION_TYPE_CODE
