SELECT T.PARTITION_ID PARTITION_ID,
       T.USER_ID USER_ID, 
       T.DISCNT_CODE DISCNT_CODE, 
       TO_CHAR(T.START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, 
       TO_CHAR(T.END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_USER_DISCNT T, TD_S_COMMPARA A
 WHERE T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = :USER_ID
   AND T.END_DATE > SYSDATE
   AND A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 9024
   AND T.DISCNT_CODE = TO_NUMBER(A.PARAM_CODE)
   AND A.PARA_CODE1 = :PARA_CODE1
   AND A.END_DATE > SYSDATE