SELECT *
  FROM TF_F_USER_DISCNT
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND DISCNT_CODE = :DISCNT_CODE
   AND START_DATE BETWEEN TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS') AND TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
 ORDER BY START_DATE

 