SELECT COUNT(*) COUNT_NUM
  FROM TF_F_USER_DISCNT T
 WHERE USER_ID = TO_NUMBER(:USER_ID)
 AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND TO_CHAR(T.START_DATE, 'YYYYMM') = TO_CHAR(SYSDATE, 'YYYYMM')
   AND T.DISCNT_CODE = :DISCNT_CODE