SELECT B.PARAM_CODE,
       B.PARAM_NAME,
       B.PARA_CODE1,
       B.PARA_CODE2,
       B.PARA_CODE3,
       B.PARA_CODE4,
       B.PARA_CODE5
  FROM TF_F_USER_DISCNT A, TD_S_COMMPARA B
 WHERE 1 = 1
   AND A.USER_ID = :USER_ID
   AND A.END_DATE > SYSDATE
   AND B.PARAM_ATTR = '1655'
   AND A.DISCNT_CODE = B.PARAM_CODE