SELECT A.USER_ID,A.DISCNT_CODE
  FROM TF_F_USER_DISCNT A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE < A.END_DATE
   AND EXISTS (SELECT 1
          FROM TD_S_COMMPARA B
         WHERE B.PARA_CODE1 = '4G_PRODUCT_PROMOTE_SMS_DISNT'
           AND B.PARAM_ATTR = 9000
           AND B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_CODE = A.DISCNT_CODE)