SELECT T.PARTITION_ID PARTITION_ID,
       T.USER_ID      USER_ID,
       T.DISCNT_CODE   DISCNT_CODE,
       T.INST_ID      INST_ID
  FROM TF_F_USER_DISCNT T, TD_S_COMMPARA B
 WHERE T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.USER_ID = :USER_ID
   AND T.END_DATE > SYSDATE
   AND T.DISCNT_CODE = TO_NUMBER(B.PARA_CODE1)
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 4007
   AND B.PARAM_CODE = 'WlwNBDiscntPck'
   AND B.END_DATE > SYSDATE