UPDATE TF_F_USER_DISCNT
 SET END_DATE = START_DATE,
 UPDATE_TIME = SYSDATE
WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
 AND USER_ID = TO_NUMBER(:USER_ID)
 AND DISCNT_CODE = :DISCNT_CODE
 AND SYSDATE BETWEEN START_DATE AND END_DATE
 AND USER_ID_A <> -1