UPDATE TF_F_USER_DISCNT
   SET END_DATE    = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME = SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND DISCNT_CODE = :DISCNT_CODE
   AND INST_ID = :INST_ID
   AND END_DATE + 0 > SYSDATE