UPDATE TF_F_USER_DISCNT 
   SET RSRV_TAG1 = :RSRV_TAG1
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND DISCNT_CODE = :DISCNT_CODE
   AND SYSDATE BETWEEN START_DATE AND END_DATE