--IS_CACHE=Y
SELECT *
  FROM TD_B_QRY_RULE_CONFIG U
 WHERE U.ID_TYPE = :ID_TYPE
   AND U.ID = :ID
   AND (U.TAG IS NULL OR U.TAG <> 'N')
   AND (U.SERV_TYPE = 'S' OR U.SERV_TYPE = 'Z')
   AND (U.EPARCHY_CODE = :EPARCHY_CODE OR U.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE