SELECT A.*
  FROM TF_F_USER_PLATSVC A
 WHERE 1=1
   AND A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(:USER_ID, '10000')
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND (A.BIZ_STATE_CODE = 'A' OR A.BIZ_STATE_CODE = 'N' OR
       A.BIZ_STATE_CODE = 'L')
   AND NOT EXISTS
 (SELECT 1
          FROM TD_B_QRY_CONFIG K
         WHERE K.BUSI_TYPE = 'P'
           AND (K.ID_TYPE = 'Z' OR K.ID_TYPE = 'S')
           AND K.TAG = 'N'
           AND K.ID = A.SERVICE_ID
           AND SYSDATE BETWEEN K.START_DATE AND K.END_DATE)
