SELECT '00' PRODUCT_MODE,
       V.SERVICE_ID,
       V.TAG,
       V.RSRV_STR4 SMS_SHOW_MODE,
       W.DISCNT_CODE
  FROM TD_B_QRY_RULE_CONFIG V, TF_F_USER_DISCNT W
 WHERE V.ID_TYPE = :ID_TYPE
   AND (V.TAG IS NULL OR V.TAG <> 'N')
   AND V.ID = W.DISCNT_CODE
   AND W.END_DATE > SYSDATE
   AND W.USER_ID = :USER_ID
   AND W.PARTITION_ID = MOD(:USER_ID, '10000')
   AND (V.SERV_TYPE = 'S' OR V.SERV_TYPE = 'Z')
   AND (V.EPARCHY_CODE = :EPARCHY_CODE OR V.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN V.START_DATE AND V.END_DATE