UPDATE TF_F_USER_PURCHASE
   SET PROCESS_TAG  = decode(LEFT_MONTHS, 1, '1', '0'),
       LEFT_DEPOSIT = LEFT_DEPOSIT - :LEFT_DEPOSIT,
       LEFT_MONTHS  = LEFT_MONTHS - 1
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PURCHASE_ATTR = :PURCHASE_ATTR
   AND start_date = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND PROCESS_TAG = '0'