SELECT T.* FROM TF_F_ENTERPRISE T
 WHERE 1 = 1
   AND T.REGITNO = :REGITNO
   AND T.ENTERPRISENAME = :ENTERPRISENAME
   AND T.LEGALPERSON = :LEGALPERSON
   AND T.STARTDATE = :STARTDATE
   AND T.TERMSTARTDATE = :TERMSTARTDATE
   AND T.TERMENDDATE = :TERMENDDATE