--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER
 WHERE USER_ID = :USER_ID
   AND PARTITION_ID = MOD(:USER_ID, 10000)
   AND REMOVE_TAG = 0
   AND (USER_STATE_CODESET = '0' OR
       (USER_STATE_CODESET <> '0' AND
       LAST_STOP_TIME >= TO_DATE(TO_CHAR(SYSDATE, 'YYYYMM') || '01000000',
                                   'YYYYMMDDHH24MISS')))