--IS_CACHE=Y
SELECT TEMPLET_CODE, NOTE_ITEM_CODE, NOTE_ITEM, PRINT_TYPE, PRINT_LEVEL, DEFAULT_TAG, ZERO_PRINT, PRINT_ORDER, PARENT_ITEM_CODE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, UPDATE_CITY_CODE, UPDATE_EPARCHY_CODE
 FROM TD_B_NOTEITEM
 WHERE TEMPLET_CODE='50000001'
 AND PRINT_LEVEL='1'
 AND PARENT_ITEM_CODE=:PARENT_ITEM_CODE