SELECT T1.RECEIVE_TYPE, T1.RULE_ID, T.PRIORITY,T.CONDITION_ID
  FROM TD_B_EWE_NODE_TASK_RELA T, TD_B_EWE_TASK_RECEIVE_RULE T1
 WHERE T.TASK_TYPE = '1'
   AND T.RELA_ID = :RELA_ID
   AND T.TASK_ID = T1.RULE_ID
   AND T1.VALID_TAG = :VALID_TAG
   AND T.VALID_TAG = :VALID_TAG
   order by t.priority
