UPDATE TL_B_ABNORMAL_OPER SET STATE = '1' 
WHERE OPER_STAFF_ID = :TRADE_STAFF_ID AND TRADE_TYPE_CODE = to_number(:TRADE_TYPE_CODE) AND SERIAL_NUMBER = :SERIAL_NUMBER 
AND OPER_TIME BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE+1) - 1 / 24 / 3600 AND STATE = '0'