SELECT B.TERMINAL_CATEGORY_CODE,
       B.TERMINAL_TYPE_CODE,
       B.BRAND_CODE,
       B.MATERIAL_CODE,
       B.MODEL_CODE,
       B.COLOR_CODE,
       B.TERMINAL_SRC_CODE,
       B.TERMINAL_ID
  FROM TF_B_CEN_RES_BATCH_TMP A, TF_R_CEN_TERMINAL_ARCH B
 WHERE B.TERMINAL_ID = A.RES_NO
   AND A.LOG_ID = :LOG_ID