SELECT SUM(RECORDCOUNT) RECORDCOUNT FROM 
(
SELECT COUNT(1) RECORDCOUNT
FROM  TF_F_USER_OTHER T
 WHERE 1=1
   AND T.PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)
   AND T.USER_ID=TO_NUMBER(:USER_ID)
   AND T.RSRV_VALUE_CODE='ISBEAUTIFUAL'  
   AND T.RSRV_VALUE=:SERIAL_NUMBER  
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE

UNION

SELECT COUNT(1) RECORDCOUNT
FROM  TF_FH_USER_OTHER F
 WHERE 1=1
   AND F.PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)
   AND F.USER_ID=TO_NUMBER(:USER_ID)
   AND F.RSRV_VALUE_CODE='ISBEAUTIFUAL'  
   AND F.RSRV_VALUE=:SERIAL_NUMBER  
   AND SYSDATE BETWEEN F.START_DATE AND F.END_DATE
)
