--IS_CACHE=Y
SELECT A.RES_TYPE_CODE,
       A.RES_KIND_CODE,
       A.SALETYPE_CODE SALE_TYPE_CODE,
       A.SALETYPE_DESC SALE_TYPE,
       A.BRAND_CODE,
       A.MODEL_CODE,
       A.SALEPRICE SALE_FEE,
       A.REMARK,
       A.RSRV_STR1,
       A.RSRV_STR2
  FROM TD_S_MATERIAL_SALETYPE A
 WHERE A.RES_TYPE_CODE = :RES_TYPE_CODE  
   AND A.RES_KIND_CODE = :RES_KIND_CODE  
   AND A.VALID_TAG = '0'
   AND A.SALETYPE_CODE = :SALETYPE_CODE