INSERT INTO TI_B_USER_REMIND
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         INST_ID, REMIND_TYPE_CODE, START_DATE, END_DATE, UPDATE_TIME,
         UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_DATE1, RSRV_DATE2,
         RSRV_DATE3)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               B.TRADE_ID, MOD(B.USER_ID, 10000), B.USER_ID, B.INST_ID,
               B.SERVICE_ID, B.START_DATE, B.END_DATE, B.UPDATE_TIME,
               B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_STR1,
               B.RSRV_STR2, B.RSRV_STR3, B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3,
               B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3
          FROM TF_B_TRADE_SVC B
           WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH
           AND B.MODIFY_TAG IN ('0', '1', '2', 'U')