INSERT INTO TF_F_USER_PRODUCT(
PARTITION_ID, USER_ID, USER_ID_A, PRODUCT_ID, PRODUCT_MODE, BRAND_CODE, INST_ID, CAMPN_ID, START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3) 
SELECT 
MOD(TO_NUMBER(USER_ID),10000),USER_ID,USER_ID_A ,PRODUCT_ID,PRODUCT_MODE,BRAND_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,sysdate,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
FROM TF_B_TRADE_PRODUCT
WHERE trade_id=to_number(:TRADE_ID)
  AND USER_ID=to_number(:USER_ID)
  AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND user_id_a = to_number(:USER_ID_A)
  AND product_id=:PRODUCT_ID
  AND NOT EXISTS
  (SELECT 1 FROM TF_F_USER_PRODUCT u 
  WHERE u.user_id = to_number(:USER_ID)
    AND u.partition_id = to_number(substr(:USER_ID,5,2))
     AND u.user_id_a = to_number(:USER_ID_A)
    AND u.start_date = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss')
    AND u.product_id = to_number(:PRODUCT_ID))