SELECT CTRM_PRODUCT_ID,
       CTRM_PRODUCT_TYPE,
       CONTRACT_ID,
       PRODUCT_ID,
       PACKAGE_ID,
       ELEMENT_ID,
       ELEMENT_TYPE_CODE,
       CHECK_ELEMENT_TYPE,
       CHECK_ELEMENT_ID,
       START_DATE,
       END_DATE,
       EPARCHY_CODE,
       UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TD_B_CTRM_RELATION t
   WHERE t.CTRM_PRODUCT_ID   IN  
    (SELECT  d.PRODUCT_ID  FROM  TD_B_CTRM_GOODS_PRODUCT d WHERE d.GOODS_ID=:GOODS_ID)