SELECT RSRV_VALUE_CODE,RSRV_VALUE,RSRV_STR1,RSRV_STR2,
RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,
RSRV_STR8,RSRV_STR9,RSRV_STR10,START_DATE,END_DATE 
FROM TF_F_USER_OTHER 
WHERE RSRV_VALUE_CODE='MZON'
AND USER_ID = :PARA_CODE1 
AND RSRV_VALUE = :PARA_CODE2
AND RSRV_STR1 = :PARA_CODE3
AND (:PARA_CODE4 = '' OR :PARA_CODE4 IS NULL)
AND (:PARA_CODE5 = '' OR :PARA_CODE5 IS NULL)
AND (:PARA_CODE6 = '' OR :PARA_CODE6 IS NULL)
AND (:PARA_CODE7 = '' OR :PARA_CODE7 IS NULL)
AND (:PARA_CODE8 = '' OR :PARA_CODE8 IS NULL)
AND (:PARA_CODE9 = '' OR :PARA_CODE9 IS NULL)
AND (:PARA_CODE10 = '' OR :PARA_CODE10 IS NULL)