UPDATE TI_BI_ROLIST
   SET DEAL_TAG = :DEAL_TAG2,
       FINISH_TIME = SYSDATE,
       RESULT_CODE = :RESULT_CODE,
       RESULT_INFO = :RESULT_INFO
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER
   AND DEAL_TAG = :DEAL_TAG1