UPDATE TF_F_USER_MEB_CENPAY T 
SET T.END_DATE=TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS')
WHERE T.USER_ID=:USER_ID
AND T.PARTITION_ID = MOD(:USER_ID, 10000) 
AND T.SERIAL_NUMBER=:SERIAL_NUMBER
AND T.PRODUCT_OFFER_ID=:PRODUCT_OFFER_ID
AND T.PAY_TYPE='2'
AND T.OPER_TYPE='3'
AND T.ELEMENT_ID='201'
AND T.RSRV_STR2='0'