--IS_CACHE=Y
SELECT 
	A.CONTENT_CODE,
	A.CHAN_ID,
	A.CONTENT_NAME,
	A.CONTENT_CLASS,
	A.CONTENT_KIND,
	A.CONTENT_TYPE,
	A.STORAGE_CODE,
	A.CONTENT,
	A.CONTENT_URL,
	A.START_DATE,
	A.END_DATE,
	B.NODE_CODE,
	B.NODE_NAME 
FROM 
	TD_S_CONTENT A 
LEFT JOIN 
	TD_S_CONT_CATEGORY_RELATION B 
ON 
 	A.CONTENT_CODE = B.CONTENT_CODE 
WHERE 1=1
 AND A.CONTENT_NAME=:CONTENT_NAME
 AND A.CHAN_ID=:CHAN_ID
 AND A.CONTENT_KIND=:CONTENT_KIND
 AND to_char(START_DATE ,'yyyy-MM-dd') >= :START_DATE
 AND to_char(END_DATE ,'yyyy-MM-dd') <= :END_DATE
 AND B.NODE_CODE=:NODE_CODE