SELECT A1.SERVICE_ID     AS ELEMENT_ID,
       A2.OFFER_CODE     AS PRODUCT_ID,
       A2.GROUP_ID       AS PACKAGE_ID,
       A2.REL_OFFER_TYPE AS ELEMENT_TYPE_CODE
  FROM TF_B_TRADE_SVC A1, TF_B_TRADE_OFFER_REL A2
 WHERE 1 = 1
   AND A1.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A1.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A1.TRADE_ID = A2.TRADE_ID
   AND A2.REL_OFFER_TYPE = 'S'

UNION ALL
SELECT B1.DISCNT_CODE    AS ELEMENT_ID,
       B2.OFFER_CODE     AS PRODUCT_ID,
       B2.GROUP_ID       AS PACKAGE_ID,
       B2.REL_OFFER_TYPE AS ELEMENT_TYPE_CODE
  FROM TF_B_TRADE_DISCNT B1, TF_B_TRADE_OFFER_REL B2
 WHERE 1 = 1
   AND B1.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND B1.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND B1.TRADE_ID = B2.TRADE_ID
   AND B2.REL_OFFER_TYPE = 'D'
  
