--IS_CACHE=N
SELECT B.ACCT_ID 账户标识
FROM TF_F_USER A, TF_A_PAYRELATION B
WHERE A.USER_ID = B.USER_ID
 AND A.REMOVE_TAG = '0'
 AND B.PAYITEM_CODE = '-1'
 AND B.DEFAULT_TAG = '1'
 AND B.ACT_TAG = '1'
 AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN B.START_CYCLE_ID AND B.END_CYCLE_ID
 AND A.USER_ID = TO_NUMBER(:USER_ID)
 AND A.Partition_Id =mod(TO_NUMBER(:USER_ID),10000)