UPDATE TF_F_CUST_GROUPMEMBER T 
SET T.REMOVE_TAG='1',T.REMOVE_DATE=SYSDATE,T.REMOVE_STAFF_ID=:STAFF_ID,T.REMOVE_REASON='REMOVE GROUP MEMBER RECORD!'
WHERE T.SERIAL_NUMBER=:SERIAL_NUMBER
AND T.JOIN_DATE=TO_DATE(:JOIN_DATE,'YYYY-MM-DD HH24:MI:SS')
AND T.REMOVE_TAG='0'