select * 
 FROM TF_F_USER_LIMIT
   WHERE USER_ID = :USER_ID
      AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE
      AND ELEMENT_ID=:ELEMENT_ID
      AND IN_MODE_CODE=:IN_MODE_CODE
      AND RSRV_STR1=:RSRV_STR1
      AND RSRV_STR2=:RSRV_STR2