SELECT A.SERIAL_NUMBER
  FROM TF_F_USER_SALE_ACTIVE A
 WHERE A.PRODUCT_ID IN (SELECT B.PARA_CODE1
                          FROM TD_S_COMMPARA B
                         WHERE B.PARAM_ATTR = '178'
                           AND B.PARAM_CODE = 'noDeposit')
   AND A.PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
union all
SELECT C.SERIAL_NUMBER
  FROM TF_F_USER_SALEACTIVE_BOOK C
 WHERE C.PRODUCT_ID IN (SELECT D.PARA_CODE1
                          FROM TD_S_COMMPARA D
                         WHERE D.PARAM_ATTR = '178'
                           AND D.PARAM_CODE = 'noDeposit')
   AND C.DEAL_STATE_CODE = '0'
   AND C.PROCESS_TAG = '0'
   AND C.END_DATE > SYSDATE
   AND C.SERIAL_NUMBER = :SERIAL_NUMBER
