insert into TF_F_USER_SALE_STOP
  (
    TRADE_ID,
    USER_ID,
    SERIAL_NUMBER,
    PRODUCT_NAME,
    PACKAGE_NAME,
    CAMPN_TYPE,
    ADVANCE_PAY,
    SEND_PAY,
    RETURNFEE,
    ACCEPT_DATE,
    TRADE_STAFF_ID,
    TRADE_CITY_CODE,
    START_DATE,
    END_DATE,
    RSRV_STR1,
    RSRV_STR2,
    RSRV_STR3,
    REMARK,
    INST_ID
  )
values
  (
    :TRADE_ID,
    :USER_ID,
    :SERIAL_NUMBER,
    :PRODUCT_NAME,
    :PACKAGE_NAME,
    :CAMPN_TYPE,
    :ADVANCE_PAY,
    :SEND_PAY,
    :RETURNFEE,
    TO_DATE(:ACCEPT_DATE,'YYYY-MM-DD HH24:MI:SS'),
    :TRADE_STAFF_ID,
    :TRADE_CITY_CODE,
    TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
    :RSRV_STR1,
    :RSRV_STR2,
    :RSRV_STR3,
    :REMARK,
    :INST_ID
   )