SELECT A.SERIAL_NUMBER
  FROM TF_F_USER_SALE_ACTIVE A
 WHERE A.END_DATE > SYSDATE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND INSTR(:RSRV_STR5, '|' || A.PRODUCT_ID || '|') > 0
UNION ALL
SELECT B.SERIAL_NUMBER
  FROM TF_F_USER_SALEACTIVE_BOOK B
 WHERE B.END_DATE > SYSDATE
   AND B.DEAL_STATE_CODE = '0'
   AND B.PROCESS_TAG = '0'
   AND B.SERIAL_NUMBER = :SERIAL_NUMBER
   AND INSTR(:RSRV_STR5, '|' || B.PRODUCT_ID || '|') > 0
