SELECT A.USER_ID, A.PRODUCT_ID
  FROM UCR_CRM1.TF_F_USER_SALE_ACTIVE A
 WHERE A.USER_ID = :USER_ID
   AND A.PRODUCT_ID IN
       (SELECT B.PARA_CODE1
          FROM TD_S_COMMPARA B
         WHERE B.PARAM_ATTR = '3800'
           AND B.PARAM_CODE = 'FREE_DISCNT')
   AND A.START_DATE < A.END_DATE
   AND A.END_DATE > SYSDATE
UNION
SELECT A.USER_ID, A.PRODUCT_ID
  FROM UCR_CRM1.TF_F_USER_SALEACTIVE_BOOK A
 WHERE A.USER_ID = :USER_ID
   AND A.PRODUCT_ID IN
       (SELECT B.PARA_CODE1
          FROM TD_S_COMMPARA B
         WHERE B.PARAM_ATTR = '3800'
           AND B.PARAM_CODE = 'FREE_DISCNT')
   AND A.START_DATE < A.END_DATE
   AND A.END_DATE > SYSDATE
   AND A.DEAL_STATE_CODE = '0'