SELECT T.PARTITION_ID,TO_CHAR(T.USER_ID) USER_ID,T.SERIAL_NUMBER,T.SERIAL_NUMBER_B,T.PRODUCT_MODE,T.PRODUCT_ID,
       T.PRODUCT_NAME,T.PACKAGE_ID,T.PACKAGE_NAME,TO_CHAR(T.CAMPN_ID) CAMPN_ID,T.CAMPN_CODE,T.CAMPN_NAME,T.CAMPN_TYPE,
       TO_CHAR(T.OPER_FEE) OPER_FEE,TO_CHAR(T.FOREGIFT) FOREGIFT,
       TO_CHAR(T.ADVANCE_PAY) ADVANCE_PAY,TO_CHAR(T.SCORE_CHANGED) SCORE_CHANGED,
       TO_CHAR(T.CREDIT_VALUE) CREDIT_VALUE,T.MONTHS,T.END_MODE,T.ACTOR_PSPT_ID,
       T.ACTOR_PSPT_TYPE_CODE,T.ACTOR_PHONE,T.ACTOR_NAME,
       T.APPR_STAFF_ID,TO_CHAR(T.APPR_TIME, 'yyyy-mm-dd hh24:mi:ss') APPR_TIME,
       T.OUT_NET_PHONE,T.CONTRACT_ID,T.PROCESS_TAG,TO_CHAR(T.ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       T.TRADE_STAFF_ID,TO_CHAR(T.RELATION_TRADE_ID) RELATION_TRADE_ID,
       TO_CHAR(T.CANCEL_DATE, 'yyyy-mm-dd hh24:mi:ss') CANCEL_DATE,
       T.CANCEL_STAFF_ID,T.CANCEL_CAUSE,TO_CHAR(T.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(T.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,TO_CHAR(T.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       T.UPDATE_STAFF_ID,T.UPDATE_DEPART_ID,T.REMARK,
       T.RSRV_NUM1,T.RSRV_NUM2,T.RSRV_NUM3,T.RSRV_NUM4,T.RSRV_NUM5,
       T.RSRV_STR1,T.RSRV_STR2,T.RSRV_STR3,T.RSRV_STR4,T.RSRV_STR5,
       T.RSRV_STR6,T.RSRV_STR7,T.RSRV_STR8,T.RSRV_STR9,
       T.RSRV_STR10,T.RSRV_STR11,T.RSRV_STR12,T.RSRV_STR13,T.RSRV_STR14,
       T.RSRV_STR15,T.RSRV_STR17,T.RSRV_STR18,T.RSRV_STR19,T.RSRV_STR20,
       T.RSRV_STR21,T.RSRV_STR22,T.RSRV_STR23,T.RSRV_STR24,T.RSRV_STR25,
       TO_CHAR(nvl(T.RSRV_DATE1, T.START_DATE), 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(nvl(T.RSRV_DATE2, T.END_DATE), 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(T.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       T.RSRV_TAG1,T.RSRV_TAG2,T.RSRV_TAG3,T.INST_ID
  FROM TF_F_USER_SALE_ACTIVE T
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.RELATION_TRADE_ID = TO_NUMBER(:RELATION_TRADE_ID)
