SELECT /*+index(a IDX_TF_F_USER_SALE_ACTIVE_SN)*/A.PRODUCT_ID, A.PACKAGE_ID, A.SERIAL_NUMBER, A.RSRV_TAG2
  FROM TF_F_USER_SALE_ACTIVE A, TD_S_COMMPARA B
 WHERE A.PRODUCT_ID = B.PARA_CODE2
   AND A.PACKAGE_ID = B.PARA_CODE3
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = 85
   AND B.PARAM_CODE = :PRODUCT_ID
   AND B.PARA_CODE1 = :PACKAGE_ID
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE