SELECT NVL(B.A_DISCNT_CODE, '0') ACTION_CODE, A.*
  FROM TF_F_USER_SALE_NEW A, TF_F_USER_SALE_DEPOSIT B
 WHERE A.PARTITION_ID = B.PARTITION_ID(+)
   AND A.USER_ID = B.USER_ID(+)
   AND A.PRODUCT_ID = B.PRODUCT_ID(+)
   AND A.PACKAGE_ID = B.PACKAGE_ID(+)
   AND A.RELATION_TRADE_ID = B.RELATION_TRADE_ID(+)
   AND A.PROCESS_TAG = '0'
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND NVL(A.RSRV_DATE2, A.END_DATE) >
       TO_DATE(:CANCEL_DATE, 'yyyy-mm-dd hh24:mi:ss')
   AND EXISTS
 (SELECT 1
          FROM TD_S_COMMPARA C
         WHERE C.SUBSYS_CODE = 'CSM'
           AND C.PARAM_ATTR = 1528
           AND C.PARAM_CODE = '1'
           AND C.PARA_CODE1 = :OLD_PRODUCT_ID
           AND (C.PARA_CODE2 = '-1' OR C.PARA_CODE2 = :NEW_PRODUCT_ID)
           AND A.PRODUCT_ID = TO_NUMBER(C.PARA_CODE3)
           AND A.PACKAGE_ID = TO_NUMBER(NVL(C.PARA_CODE4, A.PACKAGE_ID))
           AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
        UNION
        SELECT 1
          FROM TD_S_COMMPARA C
         WHERE C.SUBSYS_CODE = 'CSM'
           AND C.PARAM_ATTR = 1528
           AND C.PARAM_CODE = '2'
           AND C.PARA_CODE1 = :OLD_BRAND_CODE
           AND (C.PARA_CODE2 = 'ZZZZ' OR C.PARA_CODE2 = :NEW_BRAND_CODE)
           AND A.PRODUCT_ID = TO_NUMBER(C.PARA_CODE3)
           AND A.PACKAGE_ID = TO_NUMBER(NVL(C.PARA_CODE4, A.PACKAGE_ID))
           AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE)
   AND NOT EXISTS
 (SELECT 1
          FROM TD_S_COMMPARA C1
         WHERE C1.SUBSYS_CODE = 'CSM'
           AND C1.PARAM_ATTR = 1529
           AND C1.PARAM_CODE = '1'
           AND C1.PARA_CODE1 = :OLD_PRODUCT_ID
           AND (C1.PARA_CODE2 = '-1' OR C1.PARA_CODE2 = :NEW_PRODUCT_ID)
           AND A.PRODUCT_ID = TO_NUMBER(C1.PARA_CODE3)
           AND A.PACKAGE_ID = TO_NUMBER(NVL(C1.PARA_CODE4, A.PACKAGE_ID))
           AND SYSDATE BETWEEN C1.START_DATE AND C1.END_DATE
        UNION
        SELECT 1
          FROM TD_S_COMMPARA C
         WHERE C.SUBSYS_CODE = 'CSM'
           AND C.PARAM_ATTR = 1529
           AND C.PARAM_CODE = '2'
           AND C.PARA_CODE1 = :OLD_BRAND_CODE
           AND (C.PARA_CODE2 = 'ZZZZ' OR C.PARA_CODE2 = :NEW_BRAND_CODE)
           AND A.PRODUCT_ID = TO_NUMBER(C.PARA_CODE3)
           AND A.PACKAGE_ID = TO_NUMBER(NVL(C.PARA_CODE4, A.PACKAGE_ID))
           AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE)
 ORDER BY A.ACCEPT_DATE ASC