UPDATE TF_F_USER_SALEACTIVE_BOOK A
   SET A.PROCESS_TAG     = '1',
       A.RES_TYPE_CODE   = :RES_TYPE_CODE,
       A.RES_CODE        = :RES_CODE,
       A.UPDATE_TIME     = SYSDATE,
       A.UPDATE_STAFF_ID = :UPDATE_STAFF_ID
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.PRODUCT_ID = :PRODUCT_ID
   AND A.PACKAGE_ID = :PACKAGE_ID
   AND A.RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND A.PROCESS_TAG = '0'