UPDATE TF_F_USER_SALE_ACTIVE
   SET RSRV_DATE1 = TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE2 = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       UPDATE_TIME = SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND PRODUCT_ID = :PRODUCT_ID
   AND PACKAGE_ID = :PACKAGE_ID
   AND CAMPN_ID = :CAMPN_ID
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID