UPDATE TF_F_USER_SALE_NEW
   SET END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND PRODUCT_ID = TO_NUMBER(:PRODUCT_ID)
   AND PACKAGE_ID = TO_NUMBER(:PACKAGE_ID)
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND CAMPN_ID + 0 = :CAMPN_ID
   AND SYSDATE < END_DATE + 0