UPDATE TF_F_USER_SALE_ACTIVE
   SET END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       CANCEL_DATE = TO_DATE(:CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       CANCEL_STAFF_ID = :CANCEL_STAFF_ID, REMARK = :REMARK,
       UPDATE_TIME = SYSDATE,
       RSRV_DATE2 =  TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND PRODUCT_ID = :PRODUCT_ID
   AND PACKAGE_ID = :PACKAGE_ID
   AND CAMPN_ID = :CAMPN_ID
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')