SELECT 
 product.PRODUCT_ID,adjust.MATERIAL_CODE,adjust.AIM_PRICE A_PRICE,adjust.PROTECT_VALUE P_PRICE ,adjust.START_DATE,
 product.MODEL_DESC,product.BRAND_DESC,
 F_RES_GETCODENAME('terminal_vendor',VENDOR_CODE,'','')VENDOR,
  F_RES_GETCODENAME('customer_type',CUSTOMER_TYPE,'','')T_TYPE,
  decode(VALID_TAG,'0','有效','1','无效')VALID_TAG_DESC
 FROM TF_B_CPPRICE_ADJUST_LOG adjust,TF_R_PRODUCT_GRP product
WHERE 1=1 
 AND adjust.MATERIAL_CODE=product.MATERIAL_CODE
 AND (:BRAND_CODE IS NULL OR product.BRAND_CODE=:BRAND_CODE) 
 AND (:MODEL_CODE IS NULL OR product.MODEL_CODE=:MODEL_CODE) 
 AND (:MATERIAL_CODE IS NULL OR product.MATERIAL_CODE=:MATERIAL_CODE) 
 AND (:VENDOR_CODE IS NULL OR  product.VENDOR_CODE=:VENDOR_CODE)
 AND (:VALID_TAG IS NULL OR product.VALID_TAG=:VALID_TAG)
 AND (:CUSTOMER_TYPE IS NULL OR  product.CUSTOMER_TYPE=:CUSTOMER_TYPE)
  AND (:TERMINAL_CATEGORY_CODE IS NULL OR  product.TERMINAL_CATEGORY_CODE=:TERMINAL_CATEGORY_CODE)