SELECT TO_CHAR(T.USER_ID) USER_ID,
       T.SERIAL_NUMBER,
       T.USER_CLASS,
       T.BIRTHDAY,
       TO_CHAR(T.IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE
  FROM TF_F_USER_INFO_CLASS T
 WHERE 1 = 1
   AND T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.SERIAL_NUMBER = :SERIAL_NUMBER
   AND T.RSRV_STR1 = '0'