SELECT USER_ID,
       PARTITION_ID,
       TO_CHAR(IN_TIME,'YYYY-MM-DD HH24:MI:SS') AS IN_TIME,
       IS_BACK,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID
  FROM TF_F_TOPSET_ONLINE A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)