INSERT INTO TF_B_TRADE_GRP_MERCH_MEB
(TRADE_ID, ACCEPT_MONTH, USER_ID,SERVICE_ID, SERIAL_NUMBER, EC_USER_ID, EC_SERIAL_NUMBER, PRODUCT_ORDER_ID, PRODUCT_OFFER_ID, STATUS, START_DATE, END_DATE, MODIFY_TAG, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)   
SELECT :TRADE_ID, :ACCEPT_MONTH, M.USER_ID, M.SERVICE_ID, M.SERIAL_NUMBER, M.EC_USER_ID, M.EC_SERIAL_NUMBER, M.PRODUCT_ORDER_ID, M.PRODUCT_OFFER_ID,'N', M.START_DATE, to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss'),:MODIFY_TAG, to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , :UPDATE_STAFF_ID, :UPDATE_DEPART_ID, M.REMARK, :RSRV_NUM1, M.RSRV_NUM2, M.RSRV_NUM3, M.RSRV_NUM4, M.RSRV_NUM5, M.RSRV_STR1, M.RSRV_STR2, M.RSRV_STR3, M.RSRV_STR4, M.RSRV_STR5, M.RSRV_DATE1, M.RSRV_DATE2, M.RSRV_DATE3, M.RSRV_TAG1, M.RSRV_TAG2, '0'
FROM TF_F_USER_GRP_MERCH_MEB M
WHERE M.PARTITION_ID=MOD(TO_NUMBER(:USER_ID), 10000)
AND M.USER_ID=:USER_ID
AND SYSDATE <= M.END_DATE