SELECT TO_CHAR(a.CUST_ID) CUST_ID, a.GROUP_ID, VPMN_ID, TO_CHAR(MEMBER_CUST_ID) MEMBER_CUST_ID, a.CUST_NAME, PSPT_ID,
	   PSPT_ADDR, AGE, PSPT_POST_CODE, VIP_TYPE_CODE, a.CLASS_ID, SHORT_NUMBER, MEMBER_KIND, PAY_FOR_WAY, PAY_LIMIT,
	   WRITE_OFF_FLAG, WRITE_OFF_LIMIT, CUST_MANAGER_ID, CHKOFF_ID, IMPORTANT_FLAG, MEMBER_BELONG, MEMBER_STATUS, a.SEX,
	   TO_CHAR(a.BIRTHDAY, 'yyyy-mm-dd') BIRTHDAY, WORK_NAME, WORK_DEPART, JOB, MARRIGE, EDUCATE_DEGREE_CODE,
	   REVENUE_LEVEL_CODE, CONTACT_PHONE, a.FAX_NBR, a.EMAIL, a.COMPANY_ADDRESS, BILL_ADDRESS, a.POST_CODE, VIP_NO, OWE_LEVEL,
	   ALARM_STATUS, IN_MODE_CODE, PAY_MODE_CODE, BANK_ACCOUNT_NO, TO_CHAR(IN_DATE, 'yyyy-mm-dd') IN_DATE, IN_TYPE,
	   a.CONSUME, TO_CHAR(CREATE_DATE, 'yyyy-mm-dd') CREATE_DATE, TO_CHAR(DESTROY_DATE, 'yyyy-mm-dd') DESTROY_DATE,
	   a.REMOVE_TAG, CONSUME_HABIT, TO_CHAR(SCORE_VALUE) SCORE_VALUE, TO_CHAR(CREDIT_VALUE) CREDIT_VALUE,
	   CUST_MANAGER_APPR, BRAND_CODE, REGISTER_NAME, REGISTER_PSPT_ID, VIP_TAG, a.DUTY, TECHNICAL_POST, FOLK_CODE,
	   POLITICAL, RELIGION_CODE, a.HOME_PHONE, OTHER_CONTACT_MODE, TO_CHAR(BECOME_VIP_DATE, 'yyyy-mm-dd') BECOME_VIP_DATE,
	   FAMILY_CARD_FLAG, SPECICAL_DEMAND, VALUE_BOOK_NUMBER, COMMUNION_HABIT, a.REMARK,
	   TO_CHAR(OPEN_DATE, 'yyyy-mm-dd') OPEN_DATE, IS_HIGH_VALUE, SCORE_LEVEL, VIPCARD_POST_WAY,
	   TO_CHAR(a.UPDATE_TIME, 'yyyy-mm-dd') UPDATE_TIME, a.UPDATE_STAFF_ID, a.UPDATE_DEPART_ID,
	    c.SERIAL_NUMBER PREVALUEC1, d.DEPART_NAME PREVALUEC2,
	   a.PREVALUEC3, a.PREVALUEC4, a.RSRV_1, a.RSRV_2, TO_CHAR(a.PREVALUED1, 'yyyy-mm-dd') PREVALUED1,
	   TO_CHAR(a.PREVALUED2, 'yyyy-mm-dd') PREVALUED2, TO_CHAR(a.PREVALUEN1) PREVALUEN1, TO_CHAR(a.PREVALUEN2) PREVALUEN2,
	   TO_CHAR(a.PREVALUEN3) PREVALUEN3, OPEN_LIMIT, DEVELOP_DEPART_ID, DEVELOP_STAFF_ID, PSPT_TYPE_CODE,
	   TO_CHAR(PSPT_END_DATE, 'yyyy-mm-dd') PSPT_END_DATE, TO_CHAR(USER_ID) USER_ID, NATIONALITY_CODE, LOCAL_NATIVE_CODE,
	   POPULATION, LANGUAGE_CODE, POST_ADDRESS, CONTACT, a.HOME_ADDRESS, CHARACTER_TYPE_CODE, WEBUSER_ID, WEB_PASSWD,
	   CONTACT_TYPE_CODE, COMMUNITY_ID, a.SERIAL_NUMBER
FROM   TF_F_CUST_GROUPMEMBER_OTHER A, TF_F_CUST_GROUP B,TF_F_MANAGERSTAFF c,TD_M_DEPART d,td_m_staff e
WHERE  A.SERIAL_NUMBER = :SERIAL_NUMBER
	   AND A.REMOVE_TAG = '0'
	   AND A.GROUP_ID = B.GROUP_ID
	   AND B.REMOVE_TAG = '0'
	   AND (B.GROUP_TYPE = :GROUP_TYPE OR :GROUP_TYPE IS NULL)
	   AND a.CUST_MANAGER_ID(+)=c.VIP_MANAGER_ID
	   AND e.STAFF_ID(+)=a.CUST_MANAGER_ID
	   AND e.DEPART_ID=d.DEPART_ID