--IS_CACHE=N
SELECT NVL(SUM(deposit_balance), 0) / 100 余额
FROM UCR_ACT1.TF_B_ACCOUNTDEPOSIT_'||v_ASM_SYSCYCLE_1||'@DBLNK_ACTDBN1
WHERE ACCT_ID=:ACCT_ID
 AND DEPOSIT_CODE = :DEPOSIT_CODE
 AND END_DATE > SYSDATE