INSERT INTO TI_B_USER_SPECIALEPAY(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID, USER_ID, USER_ID_A, ACCT_ID, ACCT_ID_B, PAYITEM_CODE, START_CYCLE_ID, END_CYCLE_ID, BIND_TYPE, LIMIT_TYPE, LIMIT, COMPLEMENT_TAG, RSRV_STR1, RSRV_STR2, RSRV_STR3, UPDATE_STAFF_ID, UPDATE_DEPART_ID, UPDATE_TIME)
SELECT :SYNC_SEQUENCE,'1',:TRADE_ID, MOD(a.USER_ID,10000),a.USER_ID, a.USER_ID_A, a.ACCT_ID, a.ACCT_ID_B, a.PAYITEM_CODE, a.START_CYCLE_ID, a.END_CYCLE_ID, a.BIND_TYPE, a.LIMIT_TYPE, a.LIMIT, a.COMPLEMENT_TAG, a.RSRV_STR1, a.RSRV_STR2, a.RSRV_STR3, a.UPDATE_STAFF_ID, a.UPDATE_DEPART_ID, a.UPDATE_TIME
FROM TF_B_TRADE_SPECIALEPAY_BAK a,TF_F_USER_SPECIALEPAY b
where a.trade_id=:TRADE_ID
 AND a.accept_month = :ACCEPT_MONTH
 AND b.user_id(+) = a.user_id
 and b.acct_id(+)=a.acct_id
 AND b.PAYITEM_CODE(+)=a.PAYITEM_CODE
 AND b.START_CYCLE_ID(+) = a.START_CYCLE_ID
 and not exists (select 1 from ti_b_user_specialepay
                 where sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                 and a.user_id=user_id
                 and a.acct_id=acct_id
                 and a.PAYITEM_CODE=PAYITEM_CODE
                 and a.START_CYCLE_ID=START_CYCLE_ID
 )