select a.SERIAL_NUMBER,a.CUST_NAME,a.GROUP_ID,a.GROUP_NAME,a.CITY_CODE,a.SEND_COUNT,
       a.EMPLOYEE_NUM,a.CUST_MANAGER_ID,b.PARA_CODE3 SEND_GIFT  
       from TF_F_SEND_GIFT a 
       left join (SELECT * FROM td_s_commpara WHERE SUBSYS_CODE='CSM' AND PARAM_ATTR='9866') b 
       on(a.SEND_GIFT=b.PARA_CODE1)
 where a.SEND_TIME >= TO_DATE(:START_DATE,'YYYY-MM-DD') 
 AND a.SEND_TIME <= TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS')