--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_DISCNT D
 WHERE D.DISCNT_CODE = TO_NUMBER(:PRE_CHAR2)
   AND D.USER_ID = TO_NUMBER(:USER_ID)
   AND D.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND D.END_DATE >=
       ADD_MONTHS(TRUNC(LAST_DAY(SYSDATE) + 1) - 1 / 86400, -1)