SELECT T.SERIAL_NUMBER,B.TRADE_ID OTHER_TRADE_ID, T.USER_ID,B.RSRV_STR1,T.SERIAL_NUMBER,T.CUST_ID,T.TRADE_STAFF_ID,
       T.TRADE_DEPART_ID,T.TRADE_ID,B.UPDATE_STAFF_ID,B.INST_ID,'1' TEMP_TAG
  FROM TF_BH_TRADE T,TF_BH_TRADE_FTTH  A, TF_F_USER_OTHER B
 WHERE T.TRADE_ID = A.TRADE_ID
   AND T.USER_ID = B.USER_ID
	 AND T.TRADE_TYPE_CODE = '600'
	 AND T.SUBSCRIBE_STATE = 'A'
   AND B.RSRV_VALUE_CODE = 'FTTH_GROUP'
   AND B.RSRV_TAG2 = '1'
	 AND SYSDATE < B.END_DATE
   AND B.START_DATE < B.END_DATE  
   AND A.DEAL_TAG = '4'