SELECT * FROM TF_F_USER_ALTSN where ( SERIAL_NUMBER = :SERIAL_NUMBER or RELA_SERIAL_NUMBER = :SERIAL_NUMBER ) and STATUS = '1'
UNION ALL
SELECT * FROM TF_F_USER_ALTSN where ( SERIAL_NUMBER = :SERIAL_NUMBER or RELA_SERIAL_NUMBER = :SERIAL_NUMBER ) and STATUS ='3' and add_months (ACTIVATE_TIME ,:ALT_INTERVAL ) > sysdate