UPDATE TF_A_BADDEBT_DEALLOG SET DEAL_STATUS='1',DEAL_DATE=SYSDATE,
      DEAL_DEPART_ID=:DEAL_DEPART_ID,DEAL_STAFF_ID=:DEAL_STAFF_ID,
      BADDEBT_REASON_ID=:BADDEBT_REASON_ID,REMARK=:REMARK 
WHERE PARTITION_ID=:PARTITION_ID AND USER_ID=:USER_ID 
  AND ACCT_ID=:ACCT_ID AND BILL_ID=:BILL_ID AND ACYC_ID=:ACYC_ID 
  AND INTEGRATE_ITEM_CODE=:INTEGRATE_ITEM_CODE AND DEAL_STATUS='0'