SELECT T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5,
       T.RSRV_STR6,
       T.RSRV_VALUE
  FROM TF_F_USER_OTHER T
 WHERE 1 = 1
   AND T.RSRV_VALUE_CODE = 'DIFF_AREA_TAG'
   AND T.RSRV_STR8 = :RSRV_STR8
   AND T.RSRV_STR2 = :RSRV_STR2
   AND TO_DATE(RSRV_STR1, 'YYYY-MM-DD HH24:MI:SS') BETWEEN
       TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS') AND
       TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
 ORDER BY TO_DATE(RSRV_STR1, 'YYYY-MM-DD HH24:MI:SS') DESC