INSERT INTO TI_B_BANKSIGN_DESTROY_DAYSYN
  (RECORD_ID, ACTION_CODE, SUB_ID, USERID_TYPE, USERID, IN_DATE, STATE,BANKID,CHECKDAY)
VALUES
  (:RECORD_ID,
   '1',
   :SUB_ID,
   :USER_TYPE,
   :USER_ID,
   TO_DATE(:IN_DATE, 'yyyy-mm-dd hh24:mi:ss'),
   :STATE,
   :BANK_ID,
   to_char(SYSDATE,'yyyyMMdd'))