SELECT B.TRADE_ID, B.USER_ID,   B.Update_Staff_Id  as Trade_Staff_Id,
       TO_CHAR(B.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') AS ACCEPT_DATE,
       DECODE(B.RSRV_VALUE, '1', '退订', '2', '变更', '其他') AS RSRV_VALUE,
       B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5,
       B.RSRV_STR6, B.RSRV_STR7, B.RSRV_STR8, B.RSRV_STR9 / 100 AS RSRV_STR9,
       B.RSRV_STR10
     FROM TF_F_USER_OTHER B
     WHERE B.RSRV_VALUE_CODE = :RSRV_VALUE_CODE
         AND B.UPDATE_STAFF_ID >= :START_STAFF_ID
         AND B.UPDATE_STAFF_ID <= :END_STAFF_ID
         AND B.UPDATE_TIME >= TO_DATE(:START_DATE, 'yyyy-mm-dd')
         AND B.UPDATE_TIME <= TO_DATE(:END_DATE, 'yyyy-mm-dd') + 1 - 0.00001
         AND B.RSRV_VALUE = :TRANS_TYPE
         AND B.RSRV_STR7 = :CAMPUS_ID