  SELECT
  '' UPDATE_TIME,
  A.SERIAL_NUMBER, 
  B.RSRV_VALUE, 
  B.RSRV_DATE1, 
  B.RSRV_DATE2,
  '' GPRS_USED,
  '' GPRS_FREE,
  '' FREE_PERCENT
 FROM  TF_F_USER A,TF_F_USER_OTHER B
 WHERE 1=1
       AND A.SERIAL_NUMBER = :SERIAL_NUMBER 
        AND B.USER_ID = A.USER_ID 
        AND B.RSRV_VALUE_CODE = 'GPRS_LIMIT'
