SELECT T.USER_ID,
       T.RSRV_VALUE_CODE,
       T.RSRV_VALUE,
       T.START_DATE,
       T.END_DATE,
       T.UPDATE_TIME
  FROM TF_F_USER_OTHER T
 WHERE T.PARTITION_ID=MOD(:USER_ID,10000)
   AND T.USER_ID = :USER_ID
   AND T.RSRV_VALUE_CODE = 'PWDLOCK'
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE