update TF_f_USER_OTHER t
set t.rsrv_str1=:RES_NO,T.RSRV_STR6=:RES_KIND_CODE,T.UPDATE_STAFF_ID=:UPDATE_STAFF_ID,T.UPDATE_DEPART_ID=:UPDATE_DEPART_ID,T.RSRV_STR12=:TRADE_ID
WHERE t.rsrv_value_code = 'FTTH_GROUP' 
AND SYSDATE < t.END_DATE
and user_id = :USER_ID