UPDATE TF_F_USER_OTHER T
   SET T.END_DATE         = SYSDATE,
       T.UPDATE_TIME      = SYSDATE,
       T.UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       T.RSRV_STR1        = :TRADE_ID,
       T.REMARK           = :REMARK
 WHERE T.PARTITION_ID=MOD(to_number(:USER_ID),10000)
   AND T.USER_ID = to_number(:USER_ID)
   AND T.RSRV_VALUE_CODE = 'PWDLOCK'
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE