--IS_CACHE=Y
SELECT
   ACT_ID,
   ACT_KIND,
   ACT_KIND_DESC,
   ACT_SUB_KIND,
   ACT_SUB_KIND_DESC,
   CHAN_ID,
   TMPL_ID,
   CONTENT_CODE,
   ACT_START_DATE,
   ACT_END_DATE,
   REMARK,
   STAFF_ID,
   OPER_TIME
FROM
  TD_S_ACT_CONTENT
WHERE
	1=1
	AND ACT_KIND = :ACT_KIND
	AND ACT_SUB_KIND = :ACT_SUB_KIND
	AND CHAN_ID = :CHAN_ID
	AND to_char(ACT_START_DATE ,'yyyy-MM-dd') >= :ACT_START_DATE
    AND to_char(ACT_END_DATE ,'yyyy-MM-dd') <= :ACT_END_DATE