SELECT U.USER_ID, U.SERIAL_NUMBER, U.REMOVE_TAG, UP.PRODUCT_ID, PAY.ACCT_ID
  FROM TF_F_USER U, TF_F_USER_PRODUCT UP, TF_A_PAYRELATION PAY
 WHERE SYSDATE BETWEEN UP.START_DATE AND UP.END_DATE
   AND UP.BRAND_CODE = 'ADCG'
   AND UP.MAIN_TAG = '1'
   AND PAY.END_CYCLE_ID = (SELECT MAX(END_CYCLE_ID)
                             FROM TF_A_PAYRELATION T
                            WHERE T.USER_ID = PAY.USER_ID
                              AND T.PARTITION_ID = PAY.PARTITION_ID
                              AND T.DEFAULT_TAG = '1')
   AND PAY.DEFAULT_TAG = '1'
   AND PAY.USER_ID = U.USER_ID
   AND PAY.PARTITION_ID = U.PARTITION_ID
   AND UP.USER_ID = U.USER_ID
   AND UP.PARTITION_ID = U.PARTITION_ID
   AND U.REMOVE_TAG = '0'
   AND U.CUST_ID = :CUST_ID
