insert into tf_b_trade_user_acctday_bak
  (TRADE_ID,
   ACCEPT_MONTH,
   PARTITION_ID,
   USER_ID,
   ACCT_DAY,
   CHG_TYPE,
   CHG_MODE,
   CHG_DATE,
   FIRST_DATE,
   INST_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  select TO_NUMBER(:TRADE_ID),
         TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         PARTITION_ID,
         USER_ID,
         ACCT_DAY,
         CHG_TYPE,
         CHG_MODE,
         CHG_DATE,
         FIRST_DATE,
         INST_ID,
         START_DATE,
         END_DATE,
         UPDATE_TIME,
         UPDATE_STAFF_ID,
         UPDATE_DEPART_ID,
         REMARK,
         RSRV_NUM1,
         RSRV_NUM2,
         RSRV_NUM3,
         RSRV_NUM4,
         RSRV_NUM5,
         RSRV_STR1,
         RSRV_STR2,
         RSRV_STR3,
         RSRV_STR4,
         RSRV_STR5,
         RSRV_DATE1,
         RSRV_DATE2,
         RSRV_DATE3,
         RSRV_TAG1,
         RSRV_TAG2,
         RSRV_TAG3
    FROM TF_F_USER_ACCTDAY a
   WHERE USER_ID = TO_NUMBER(:USER_ID)
     AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND NOT EXISTS
   (SELECT 1
            FROM tf_b_trade_user_acctday_bak
           WHERE trade_id = TO_NUMBER(:TRADE_ID)
             AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
             AND user_id = a.user_id)