SELECT 
       C.TRADE_TYPE, 
       D.STAFF_NAME
  FROM  TD_S_TRADETYPE C, TD_M_STAFF D
 WHERE 
   C.TRADE_TYPE_CODE=:TRADE_TYPE_CODE
   AND D.STAFF_ID=:STAFF_ID
   AND C.EPARCHY_CODE =:EPARCHY_CODE
   

