--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
  FROM ucr_crm1.TF_BH_TRADE A, ucr_crm1.TF_B_TRADE_SVC B, TD_M_DEPART D, ucr_crm1.TF_B_TRADE_DISCNT T
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.TRADE_TYPE_CODE IN ('283', '286')
   AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
   AND A.CANCEL_TAG = '0'
   AND A.TRADE_ID = B.TRADE_ID
   AND A.TRADE_ID = T.TRADE_ID
   AND B.TRADE_ID = T.TRADE_ID
   AND T.DISCNT_CODE = 3410
   AND B.SERVICE_ID = '831'
   AND B.MODIFY_TAG = '0'
   AND A.TRADE_DEPART_ID = D.DEPART_ID
   AND ROWNUM < 2