--IS_CACHE=Y
SELECT S.STAFF_ID STAFF_ID,
       NVL(F_SYS_GETCODENAME('staff_id', RTRIM(S.STAFF_ID), '', ''), ' ') STAFF_NAME,
       F.MOD_CODE MENU_ID,
       N.DATA_NAME MENU_TITLE,
       F.RIGHT_CODE RIGHT_CODE,
       F.RIGHT_NAME RIGHT_NAME,
       '1' RIGHT_TAG
  FROM TF_M_STAFFFUNCRIGHT S,
       TD_M_FUNCRIGHT      F,
       TD_S_MODFILE        M,
       TD_S_STATIC         N
 WHERE S.RIGHT_ATTR = '0'
   AND S.RIGHT_TAG = '1'
   AND F.RIGHT_ATTR = '0'
   AND M.MOD_CODE = F.MOD_CODE
   AND S.RIGHT_CODE = F.RIGHT_CODE
   AND (S.RSVALUE1 IS NULL OR S.RSVALUE1 != '1')
   AND S.STAFF_ID = :STAFF_ID
   AND M.MOD_CODE = N.DATA_ID
   AND N.TYPE_ID = 'CMWP_BOSS_MENU_RIGHT'
UNION
SELECT DISTINCT S.STAFF_ID STAFF_ID,
                NVL(F_SYS_GETCODENAME('staff_id', RTRIM(S.STAFF_ID), '', ''),
                    ' ') STAFF_NAME,
                F.MOD_CODE MENU_ID,
                N.DATA_NAME MENU_TITLE,
                NVL(F.RIGHT_CODE, ' ') RIGHT_CODE,
                F.RIGHT_NAME RIGHT_NAME,
                '1' RIGHT_TAG
  FROM TF_M_STAFFFUNCRIGHT S,
       TD_M_FUNCRIGHT      F,
       TF_M_ROLEFUNCRIGHT  R,
       TD_S_MODFILE        M,
       TD_S_STATIC         N
 WHERE S.RIGHT_ATTR = '1'
   AND S.RIGHT_TAG = '1'
   AND S.RIGHT_CODE = R.ROLE_CODE
   AND R.RIGHT_CODE = F.RIGHT_CODE
   AND M.MOD_CODE = F.MOD_CODE
   AND (R.RSVALUE1 IS NULL OR R.RSVALUE1 != '1')
   AND (S.RSVALUE1 IS NULL OR S.RSVALUE1 != '1')
   AND NOT EXISTS (SELECT 1
          FROM TF_M_STAFFFUNCRIGHT
         WHERE STAFF_ID = S.STAFF_ID
           AND RIGHT_CODE = R.RIGHT_CODE
           AND (RIGHT_TAG = '0' OR RSVALUE1 = '1'))
   AND S.STAFF_ID = :STAFF_ID
   AND M.MOD_CODE = N.DATA_ID
   AND N.TYPE_ID = 'CMWP_BOSS_MENU_RIGHT'
UNION
SELECT S.STAFF_ID STAFF_ID,
       NVL(F_SYS_GETCODENAME('staff_id', RTRIM(S.STAFF_ID), '', ''), ' ') STAFF_NAME,
       F.MOD_CODE MENU_ID,
       N.DATA_NAME MENU_TITLE,
       NVL(S.RIGHT_CODE, ' ') RIGHT_CODE,
       F.RIGHT_NAME RIGHT_NAME,
       '1' RIGHT_TAG
  FROM TF_M_STAFFTEMPFUNCRIGHT S,
       TD_M_FUNCRIGHT          F,
       TD_S_MODFILE            M,
       TD_S_STATIC             N
 WHERE 1 = 1
   AND S.STAFF_ID = :STAFF_ID
   AND S.RIGHT_CODE = F.RIGHT_CODE
   AND F.MOD_CODE = M.MOD_CODE
   AND ((S.USE_TAG = '1' AND SYSDATE >= S.START_DATE AND
       SYSDATE <= S.END_DATE) OR
       (S.USE_TAG = '0' AND S.USED_TIMES < S.TIMES))
   AND (S.RSVALUE1 IS NULL OR S.RSVALUE1 != '1')
   AND N.DATA_ID = M.MOD_CODE
   AND N.TYPE_ID = 'CMWP_BOSS_MENU_RIGHT'