NSERT INTO TD_B_INFORMATION_PROMPT 
(TRADE_TYPE_CODE,TRADE_TYPE,CONSTRAINT_TYPE_CODE,CONSTRAINT_TYPE,END_DATE,CONSTRAINT_ATTR,CONSTRAINT_ATTR_NAME,PROMPT_INFO,RSRV_STR4,
RSRV_STR5,UPDATE_STAFF_ID,UPDATE_DEPART_ID,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,VALID_TAG,UPDATE_TIME
 )
VALUES(:TRADE_TYPE_CODE,:TRADE_TYPE,:CONSTRAINT_TYPE_CODE,:CONSTRAINT_TYPE,TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
:CONSTRAINT_ATTR,:CONSTRAINT_ATTR_NAME,:PROMPT_INFO,:RSRV_STR4, :RSRV_STR5,:UPDATE_STAFF_ID,
:UPDATE_DEPART_ID,:RSRV_NUM1,:RSRV_NUM2,:RSRV_NUM3,:RSRV_STR1,:RSRV_STR2,:RSRV_STR3,:RSRV_NUM1,TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS'),
TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS'),:VALID_TAG,SYSDATE)