DELETE FROM TF_F_USER_ATTR A
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADE_ATTR B
         WHERE B.TRADE_ID = TO_NUMBER(:TRADE_ID)
           AND B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND B.USER_ID = A.USER_ID
           AND B.INST_ID = A.INST_ID)