SELECT C.PARA_CODE1 套餐,
       C.PARA_CODE2 业务编码,
       C.PARA_CODE4 套餐价值,
       C.PARA_CODE6 是否自选,
       TO_CHAR(D.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') 变更时间,
       D.UPDATE_DEPART_ID 变更部门
  FROM TD_S_COMMPARA C, TF_F_USER_DISCNT D
 WHERE C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = :COMMPARA_ATTR ----- '179'
   AND C.PARAM_CODE = 'CUMU'
   AND D.PARTITION_ID = MOD(:USER_ID, 10000)
   AND D.USER_ID = TO_NUMBER(:USER_ID)
   AND TRUNC(D.END_DATE) = TO_DATE('2050-12-31', 'YYYY-MM-DD') ----将要生效或者在用未结束的套餐
   AND (TO_CHAR(D.UPDATE_TIME, 'YYYYMM') = TO_CHAR(SYSDATE, 'YYYYMM') OR
       (TO_DATE('2018-05-01', 'yyyy-mm-dd') > SYSDATE AND
       D.UPDATE_TIME > TO_DATE('2018-01-01', 'yyyy-mm-dd')))
   AND D.DISCNT_CODE = C.PARA_CODE1
   AND ROWNUM < 2