select USER_ID,
INST_ID,
SERIAL_NUMBER,
SERVICE_ID,
EC_USER_ID,
EC_SERIAL_NUMBER,
PRODUCT_ORDER_ID,
PRODUCT_OFFER_ID,
START_DATE,
END_DATE,
UPDATE_TIME,
UPDATE_STAFF_ID,
UPDATE_DEPART_ID,
RSRV_STR1,
RSRV_STR2,
RSRV_STR3,
RSRV_STR4,
RSRV_STR5,
RSRV_TAG1,
RSRV_TAG2,
RSRV_TAG3
from TF_F_USER_ECRECEP_MEB
where 1=1
and USER_ID=:USER_ID
and EC_USER_ID=:EC_USER_ID