INSERT INTO TF_F_NONBOSSFEE_LOG                
  (LOG_ID
	,OPER_TYPE_NAME
	,OPER_DATE
	,OPER_MONTH
	,TRADE_STAFF_ID
	,TRADE_DEPART_ID
	,TRADE_CITY_CODE
	,TRADE_EPARCHY_CODE
	,PAY_MODE
	,PAY_NAME
	,PAY_NAME_REMARK
	,OPER_FEE
	,OPER_UNIT
	,OPER_PRICE
	,OPER_NUM
	,REFUND_TAG
	,RSRV_STR1
	,RSRV_STR2
	,RSRV_STR3
	,RSRV_STR4
	,RSRV_STR5
	,REMARK
	,NOTAX_FEE
	,TAX_FEE
	,TAX_RATE
	,RATE_TYPE
	,RSRV_NUM1
	,RSRV_NUM2
	,TRADE_ID
	,RSRV_STR6
	,RSRV_STR7
	,RSRV_STR8
	,RSRV_STR9
	,OPER_TYPE_NAME_DESC
	,REFUND_LOG_ID
	,TICKET_ID
	,RSRV_STR10
	,TICKET_TYPE
  )                                   
  SELECT :LOG_ID,
         L.OPER_TYPE_NAME,
         sysdate,            --today
         :OPER_MONTH,
         :TRADE_STAFF_ID,
         :TRADE_DEPART_ID,
         :TRADE_CITY_CODE,
         :TRADE_EPARCHY_CODE
         ,PAY_MODE           
				,l.PAY_NAME           
				,l.PAY_NAME_REMARK    
				,l.OPER_FEE*-1           
				,l.OPER_UNIT          
				,l.OPER_PRICE         
				,l.OPER_NUM           
				,'2'         
				,l.RSRV_STR1          
				,l.RSRV_STR2          
				,l.RSRV_STR3          
				,l.RSRV_STR4          
				,l.RSRV_STR5          
				,l.REMARK             
				,l.NOTAX_FEE*-1          
				,l.TAX_FEE*-1           
				,l.TAX_RATE           
				,l.RATE_TYPE          
				,l.RSRV_NUM1          
				,l.RSRV_NUM2          
				,l.TRADE_ID           
				,l.RSRV_STR6          
				,l.RSRV_STR7          
				,l.OPER_DATE          
				,l.RSRV_STR9          
				,l.OPER_TYPE_NAME_DESC
				,:REFUND_LOG_ID     
				,l.TICKET_ID          
				,l.RSRV_STR10         
				,l.TICKET_TYPE 
	 FROM TF_F_NONBOSSFEE_LOG l
   WHERE l.LOG_ID = :REFUND_LOG_ID
