select partition_id,
	   to_char(cust_id) cust_id,
	   pspt_type_code,
	   pspt_id,
	   to_char(pspt_end_date, 'YYYY-MM-DD HH24:MI:SS') pspt_end_date,
	   pspt_addr,
	   cust_name,
	   sex,
	   eparchy_code,
	   city_code,
	   to_char(birthday, 'YYYY-MM-DD HH24:MI:SS') birthday,
	   birthday_lunar,
	   birthday_flag,
	   post_address,
	   post_code,
	   post_person,
	   phone,
	   fax_nbr,
	   email,
	   home_address,
	   home_phone,
	   work_name,
	   work_kind,
	   work_address,
	   work_phone,
	   work_post_code,
	   calling_type_code,
	   sub_calling_type_code,
	   work_depart,
	   job,
	   contact,
	   contact_phone,
	   contact_type_code,
	   contact_freq,
	   nationality_code,
	   local_native_code,
	   population,
	   language_code,
	   folk_code,
	   religion_code,
	   job_type_code,
	   revenue_level_code,
	   educate_degree_code,
	   educate_grade_code,
	   graduate_school,
	   speciality,
	   character_type_code,
	   health_state_code,
	   marriage,
	   webuser_id,
	   web_passwd,
	   community_id,
	   remove_tag,
	   to_char(remove_date, 'YYYY-MM-DD HH24:MI:SS') remove_date,
	   remove_staff_id,
	   remove_change,
	   to_char(update_time, 'YYYY-MM-DD HH24:MI:SS') update_time,
	   update_staff_id,
	   update_depart_id,
	   remark,
	   rsrv_num1,
	   rsrv_num2,
	   rsrv_num3,
	   rsrv_str1,
	   rsrv_str2,
	   rsrv_str3,
	   rsrv_str4,
	   rsrv_str5,
	   rsrv_str6,
	   rsrv_str7,
	   rsrv_str8,
	   to_char(rsrv_date1, 'YYYY-MM-DD HH24:MI:SS') rsrv_date1,
	   to_char(rsrv_date2, 'YYYY-MM-DD HH24:MI:SS') rsrv_date2,
	   to_char(rsrv_date3, 'YYYY-MM-DD HH24:MI:SS') rsrv_date3,
	   rsrv_tag1,
	   rsrv_tag2,
	   rsrv_tag3
  from tf_f_cust_person
 where cust_id = to_number(:CUST_ID)
   and partition_id = mod(to_number(:CUST_ID), 10000)