SELECT '0' AS FEE_MODE,
       '291' AS FEE_TYPE_CODE,
       T.RSRV_STR6 AS OLDFEE,
       T.RSRV_STR5 AS FEE
  FROM TF_BH_TRADE T
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))