SELECT
 RECORD_ID       
,OPR_NUMB        
,MOBILE_NO       
,IMEI            
,MATERIAL_CODE   
,PACKAGE_CODE    
,RECEDE_TIME     
,DEAL_FLAG       
,UPDATE_STAFF_ID 
,UPDATE_DEPART_ID
,UPDATE_TIME     
,REMARK          
,RSRV_STR1       
,RSRV_STR2       
,RSRV_STR3       
,RSRV_STR4       
,RSRV_FLAG1      
,RSRV_FLAG2      
,RSRV_FLAG3      
,RSRV_FLAG4      
,RSRV_DATE1      
,RSRV_DATE2      
,RSRV_DATE3      
,RSRV_DATE4 
 FROM TI_B_USRRETURNDATA_DOWN 
 WHERE OPR_NUMB = :OPR_NUMB
 AND DEAL_FLAG = :DEAL_FLAG