--IS_CACHE=Y
SELECT A.PAGESET_PAGE_ID,
       A.PAGESET_ID,
       A.PAGE_ID,
       B.PAGE_NAME,
       B.LISTENER,
       A.PARAMS,
       B.PAGE_DESC,
       B.SUBSYS_CODE,
       B.RULESET_ID,
       B.IS_GET_PAGE_DATA,
       B.IS_DATA_MUST
  FROM TD_B_PAGESET_PAGE A, TD_B_PAGE B
 WHERE A.PAGE_ID = B.PAGE_ID
   AND A.PAGESET_ID = :PAGESET_ID
   AND A.STATE = '1'
   AND B.STATE = '1'
 ORDER BY A.SEQ_NO
