SELECT USER_ID,
       SERIAL_NUMBER,
       PRODUCT_ID,
       PACKAGE_ID,
       CAMPN_TYPE,
       START_DATE,
       END_DATE,
       UPDATE_TIME,
       RELATION_TRADE_ID,
       REMARK
  FROM TF_F_USER_SALE_ACTIVE
  WHERE PRODUCT_ID = :PRODUCT_ID
    AND TO_CHAR(SYSDATE,'YYYYMM') > TO_CHAR(START_DATE,'YYYYMM')
    AND END_DATE >=SYSDATE