--IS_CACHE=N
SELECT A.DEPART_KIND_CODE 部门类型,TO_CHAR(B.ACCEPT_DATE, 'YYYYMM') 受理月份,B.TRADE_ID 台账标识
          FROM TD_M_DEPART A, ucr_crm1.TF_BH_TRADE B, TD_M_STAFF C
         WHERE B.USER_ID = TO_NUMBER(:USER_ID)
           AND B.TRADE_TYPE_CODE IN ('40')
           AND B.CANCEL_TAG = '0'
           AND B.TRADE_EPARCHY_CODE = '0898'
           AND B.TRADE_STAFF_ID = C.STAFF_ID
           AND C.DEPART_ID = A.DEPART_ID
           AND TRUNC(B.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
           AND ROWNUM < 2