SELECT T1.*
  FROM TF_BH_TRADE T, TF_B_TRADE_SVCSTATE T1
 WHERE T.TRADE_ID = T1.TRADE_ID
   AND T.USER_ID = :USER_ID
   AND T1.SERVICE_ID = '0'
   AND T.ACCEPT_DATE >=TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')
   AND (T1.MODIFY_TAG = 1 OR
       (T1.MODIFY_TAG = '0' AND
       T1.START_DATE =
       (SELECT MAX(B.START_DATE)
            FROM TF_BH_TRADE A, TF_B_TRADE_SVCSTATE B
           WHERE A.TRADE_ID = B.TRADE_ID
             AND B.SERVICE_ID = '0'
             AND A.USER_ID = :USER_ID
             AND A.ACCEPT_DATE >=TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'))))
 ORDER BY T1.UPDATE_TIME, T1.END_DATE ASC