SELECT SUBSTR(SERIAL_NUMBER, 3) SERIAL_NUMBER, USER_ID,DECODE(PROCESS_TAG, 1, '新增', 2, '删除','未知') PROCESS_TAG, to_char(BEGIN_DATE,'yyyy-mm-dd hh24:mi:ss') BEGIN_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,EXEC_TIME, REMARK
  FROM TL_B_BLACKUSER 
 WHERE 1 = 1
   AND SUBSTR(SERIAL_NUMBER, 3) = :SERIAL_NUMBER
   AND (:START_TIME IS NULL OR :START_TIME = '' OR
       BEGIN_DATE >= TO_DATE(:START_TIME, 'yyyy-mm-dd'))
   AND (:END_TIME IS NULL OR :END_TIME = '' OR
       BEGIN_DATE < TO_DATE(:END_TIME, 'yyyy-mm-dd') + 1)
   AND END_DATE > SYSDATE
	ORDER BY EXEC_TIME DESC ,END_DATE DESC