UPDATE TF_F_USER_OTHERSERV
   SET PROCESS_TAG = :PROCESS_TAG,
       END_DATE    = SYSDATE,
       REMARK      = :REMARK,
       STAFF_ID    = :STAFF_ID,
       DEPART_ID   = :DEPART_ID,
       RSRV_STR3   = :RSRV_STR3
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND serial_number=:SERIAL_NUMBER   
   AND RSRV_NUM1 = :RSRV_NUM1
   AND SERVICE_MODE = :SERVICE_MODE
   AND END_DATE > SYSDATE