SELECT A.PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       TO_CHAR(A.USER_ID_A) USER_ID_A,
       A.SERVICE_ID,
       A.MAIN_TAG,
       A.INST_ID,
       A.CAMPN_ID,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(A.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_DATE1,
       A.RSRV_DATE2,
       A.RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3
  FROM TF_F_USER_SVC A,TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = :USER_ID   
   AND A.SERVICE_ID = TO_NUMBER(C.PARA_CODE1)
   AND MONTHS_BETWEEN(TRUNC(SYSDATE, 'MM'), TRUNC(A.END_DATE, 'MM')) < 3
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = :PARAM_ATTR
   AND C.PARAM_CODE = :PARAM_CODE
   AND (C.EPARCHY_CODE = :EPARCHY_CODE OR C.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE