INSERT INTO TF_B_TRADE_PLATSVC
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   SP_CODE,
   BIZ_CODE,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   PRODUCT_NO,
   ORG_DOMAIN,
   OPER_CODE,
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   SUBSCRIBE_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_STR6,
   RSRV_STR7,
   RSRV_STR8,
   RSRV_STR9,
   RSRV_STR10,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  SELECT :TRADE_ID,
         SUBSTR(:TRADE_ID, 5, 2),
         A.USER_ID,
         A.PRODUCT_ID,
         A.PACKAGE_ID,
         A.SERVICE_ID,
         A.SERIAL_NUMBER,
         A.SP_CODE,
         A.BIZ_CODE,
         A.BIZ_TYPE_CODE,
         'A',
         A.PRODUCT_NO,
         A.ORG_DOMAIN,
         --DECODE(SUBSTR(B.RSRV_STR4, 4, 1), '1', '04', '14'),
         '05',
         '08',
         A.BILL_TYPE,
         A.PRICE,
         A.FIRST_DATE,
         A.FIRST_DATE_MON,
         A.GIFT_SERIAL_NUMBER,
         A.GIFT_USER_ID,
         A.SUBSCRIBE_ID,
         TO_DATE(:ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss'),
         TO_DATE('2050-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
         TO_DATE(:UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss'),
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '用户开机特殊处理手机报业务',
         2,
         A.RSRV_NUM2,
         A.RSRV_NUM3,
         A.RSRV_NUM4,
         A.RSRV_NUM5,
         A.RSRV_STR1,
         A.RSRV_STR2,
         A.RSRV_STR3,
         A.RSRV_STR4,
         DECODE(A.ORG_DOMAIN,
                'EWPT',
                '220BIP2B263' || TO_CHAR(SYSDATE, 'YYMMDDHH24MISS') ||
                TRUNC(DBMS_RANDOM.VALUE(100000, 999999)),
                A.RSRV_STR5),
         A.RSRV_STR6,
         A.RSRV_STR7,
         A.RSRV_STR8,
         A.RSRV_STR9,
         A.RSRV_STR10,
         A.RSRV_DATE1,
         A.RSRV_DATE2,
         A.RSRV_DATE3,
         A.RSRV_TAG1,
         DECODE(A.ORG_DOMAIN,
                'EWPT',
                '0',
                'STMM',
                '0',
                'MPAY',
                '0',
                'WLAN',
                '0',
                'RADI',
                '0',
                'PIMM',
                '0',
                '1'),
         A.RSRV_TAG3
    FROM TF_F_USER_PLATSVC A, TD_B_PLATSVC B
   WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND A.USER_ID = :USER_ID
     AND A.BIZ_STATE_CODE = 'A'
     AND A.SERVICE_ID = B.SERVICE_ID
     AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
     AND A.BIZ_TYPE_CODE = '05'
     AND A.SP_CODE='801234'