SELECT STMT_ID,
       STMT_TYPE,
       STMT_NAME,
       STMT_CONTENT,
       START_TIME,
       END_TIME,
       UPDATE_DEPART_ID,
       UPDATE_STAFF_ID,
       UPDATE_TIME,
       REMARK,
       RSRV_STR1,
       RSRV_STR2
  FROM TB_B_DATA_MAINTAIN
 WHERE 1 = 1
   AND SYSDATE BETWEEN START_TIME AND END_TIME
   AND STMT_TYPE = :STMT_TYPE
   AND STMT_NAME LIKE '%' || :STMT_NAME || '%'