--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型,TO_CHAR(ACCEPT_DATE, 'YYYYMM') 受理月份,B.TRADE_ID 台账标识
FROM UCR_CRM1.TF_BH_TRADE       A,
     UCR_CRM1.TF_B_TRADE_DISCNT B,
     TF_F_USER_DISCNT  C,
     TD_M_DEPART       E
WHERE A.USER_ID = TO_NUMBER(:USER_ID)
 AND B.USER_ID = TO_NUMBER(:USER_ID)
 AND A.TRADE_TYPE_CODE IN (10, 110) --开户和产品变更
 AND A.CANCEL_TAG = '0' --未返销
 AND A.TRADE_ID = B.TRADE_ID
 AND B.DISCNT_CODE IN
     (SELECT D.PARA_CODE1
        FROM TD_S_COMMPARA D
       WHERE D.SUBSYS_CODE = 'CSM'
         AND D.PARAM_ATTR = :COMMPARA_ATTR  ----'8888'
         AND D.PARAM_CODE = '1'
         AND D.EPARCHY_CODE = '0898'
         AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
         AND D.PARA_CODE3 = :OPER_CODE)
 AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE) --20101008 qiand 统一修改判断条件。
 AND B.END_DATE > SYSDATE
 AND B.MODIFY_TAG = '0'
 AND C.USER_ID = B.USER_ID
 AND B.INST_ID = C.INST_ID
 AND C.END_DATE > SYSDATE
 AND A.TRADE_DEPART_ID = E.DEPART_ID
 AND ROWNUM < 2