SELECT A.USER_ID,
       B.END_DATE,
       B.MONTHS,
       A.A_DISCNT_CODE,
       B.RELATION_TRADE_ID,
       B.UPDATE_STAFF_ID,
       B.UPDATE_DEPART_ID,
       ((EXTRACT(year FROM C.END_DATE) - EXTRACT(year FROM B.END_DATE)) * 12 +
       EXTRACT(month FROM C.END_DATE) - EXTRACT(month FROM B.END_DATE)) END_OFFSET,
       ((EXTRACT(year FROM B.END_DATE) - EXTRACT(year FROM B.START_DATE)) * 12 +
       EXTRACT(month FROM B.END_DATE) - EXTRACT(month FROM B.START_DATE)) START_OFFSET
  FROM TF_F_USER_SALE_DEPOSIT     A,
       TF_B_TRADE_SALE_ACTIVE     B,
       TF_B_TRADE_SALE_ACTIVE_BAK C
 WHERE B.TRADE_ID = :TRADE_ID
   AND B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND B.MODIFY_TAG = :MODIFY_TAG
   AND C.TRADE_ID = :TRADE_ID
   AND C.RELATION_TRADE_ID = B.RELATION_TRADE_ID
   AND C.USER_ID = B.USER_ID
   AND C.PARTITION_ID = MOD(TO_NUMBER(B.USER_ID), 10000)
   AND A.RELATION_TRADE_ID = B.RELATION_TRADE_ID
   AND A.USER_ID = B.USER_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(B.USER_ID), 10000)