SELECT T.PARTITION_ID, 
       T.CUST_ID, 
       T.USE_NAME, 
       T.USE_PSPT_TYPE_CODE, 
       T.USE_PSPT_ID, 
       T.USE_PSPT_ADDR,
       T.CREATE_TIME,
       T.UPDATE_TIME,
       T.UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID,
       T.REMARK,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5
  FROM TF_F_CUST_PERSON_OTHER T
 WHERE T.CUST_ID = :CUST_ID
   AND T.PARTITION_ID = MOD(:CUST_ID, 10000)
