SELECT TRADE_ID,
       SERIAL_NUMBER,
       CHANNEL_TYPE,
       ACCEPT_DATE,
       STATUS,
       REMARK,
       FILE_NAME
  FROM TI_B_ELECTCARD_BAT_RECH T
     WHERE TRADE_ID = :TRADE_ID
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
     AND SERIAL_NUMBER = :SERIAL_NUMBER