SELECT U.PARTITION_ID,
       TO_CHAR(U.USER_ID) USER_ID,
       U.RSRV_VALUE_CODE,
       U.RSRV_VALUE,
       U.RSRV_NUM1,
       U.RSRV_NUM2,
       U.RSRV_NUM3,
       U.RSRV_NUM4,
       U.RSRV_NUM5,
       U.RSRV_NUM6,
       U.RSRV_NUM7,
       U.RSRV_NUM8,
       U.RSRV_NUM9,
       U.RSRV_NUM10,
       U.RSRV_NUM11,
       U.RSRV_NUM12,
       U.RSRV_NUM13,
       U.RSRV_NUM14,
       U.RSRV_NUM15,
       U.RSRV_NUM16,
       U.RSRV_NUM17,
       U.RSRV_NUM18,
       U.RSRV_NUM19,
       U.RSRV_NUM20,
       U.RSRV_STR1,
       U.RSRV_STR2,
       U.RSRV_STR3,
       U.RSRV_STR4,
       U.RSRV_STR5,
       U.RSRV_STR6,
       U.RSRV_STR7,
       U.RSRV_STR8,
       U.RSRV_STR9,
       U.RSRV_STR10,
       U.RSRV_STR11,
       U.RSRV_STR12,
       U.RSRV_STR13,
       U.RSRV_STR14,
       U.RSRV_STR15,
       U.RSRV_STR16,
       U.RSRV_STR17,
       U.RSRV_STR18,
       U.RSRV_STR19,
       U.RSRV_STR20,
       U.RSRV_STR21,
       U.RSRV_STR22,
       U.RSRV_STR23,
       U.RSRV_STR24,
       U.RSRV_STR25,
       U.RSRV_STR26,
       U.RSRV_STR27,
       U.RSRV_STR28,
       U.RSRV_STR29,
       U.RSRV_STR30,
       TO_CHAR(U.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(U.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(U.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       TO_CHAR(U.RSRV_DATE4, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE4,
       TO_CHAR(U.RSRV_DATE5, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE5,
       TO_CHAR(U.RSRV_DATE6, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE6,
       TO_CHAR(U.RSRV_DATE7, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE7,
       TO_CHAR(U.RSRV_DATE8, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE8,
       TO_CHAR(U.RSRV_DATE9, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE9,
       TO_CHAR(U.RSRV_DATE10, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE10,
       U.RSRV_TAG1,
       U.RSRV_TAG2,
       U.RSRV_TAG3,
       U.RSRV_TAG4,
       U.RSRV_TAG5,
       U.RSRV_TAG6,
       U.RSRV_TAG7,
       U.RSRV_TAG8,
       U.RSRV_TAG9,
       U.RSRV_TAG10,
       U.PROCESS_TAG,
       U.STAFF_ID,
       U.DEPART_ID,
       TO_CHAR(U.TRADE_ID) TRADE_ID,
       TO_CHAR(U.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(U.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(U.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       U.UPDATE_STAFF_ID,
       U.UPDATE_DEPART_ID,
       U.REMARK,
       TO_CHAR(U.INST_ID) INST_ID 
	   FROM TF_B_TRADE_OTHER T, TF_F_USER_OTHER U WHERE T.TRADE_ID = TO_NUMBER(:TRADE_ID)
       AND T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
	   AND T.MODIFY_TAG = '0'
       AND T.USER_ID = U.USER_ID
       AND U.PARTITION_ID = MOD(TO_NUMBER(T.USER_ID), 10000)
	   AND U.USER_ID = :USER_ID
       AND T.RSRV_STR7 = U.RSRV_STR7
       AND U.RSRV_STR7 = :PRODUCT_NO
       AND U.END_DATE > SYSDATE