--IS_CACHE=Y
SELECT LOG_TAG,FORCE_TAG,AREA_CODE,DEPART_ID FROM TF_M_TERMIPADDR
 WHERE NET_SEG =SUBSTR(:IP_ADDR,INSTR(:IP_ADDR,'.',1,2)+1,INSTR(:IP_ADDR,'.',1,3)-INSTR(:IP_ADDR,'.',1,2)-1)
 AND ADDR_START <=TO_NUMBER(SUBSTR(:IP_ADDR,INSTR(:IP_ADDR,'.',1,3)+1,20))
 AND ADDR_END >= TO_NUMBER(SUBSTR(:IP_ADDR,INSTR(:IP_ADDR,'.',1,3)+1,20))
 AND SUBSTR(IP_START, 1, INSTR(IP_START,'.',1,2)) = SUBSTR(IP_END, 1, INSTR(IP_END,'.',1,2))
 AND SUBSTR(IP_START, 1, INSTR(IP_START,'.',1,2)-1) = SUBSTR(:IP_ADDR, 1, INSTR(:IP_ADDR,'.',1,2)-1)
 AND ROWNUM < 2