select count(1) NUM from TF_F_USER_PLATSVC A where A.USER_ID = :USER_ID
     AND A.BIZ_STATE_CODE = 'A'  AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
     AND A.BIZ_TYPE_CODE = '05'
     AND A.SP_CODE='801234'