SELECT T.BIZ_NAME,T.OLD_SP_CODE,T.OLD_BIZ_CODE,T.OLD_BIZ_TYPE,T.OLD_PRICE,T.NEW_SP_CODE,T.NEW_BIZ_CODE,
T.NEW_BIZ_TYPE,T.NEW_PRICE,T.REMARK,T.RSRV_STR1,T.RSRV_STR2,T.RSRV_STR3,T.RSRV_STR4,T.RSRV_STR5 FROM TD_B_OFFICEDATA_RELATION T 
WHERE T.OLD_SP_CODE = :OLD_SP_CODE AND T.OLD_BIZ_CODE = :OLD_BIZ_CODE
