--IS_CACHE=Y
SELECT 
	RULE_ID,
	RULE_NAME,
	PARAM_TYPE,
	PARAM_A,
	PARAM_B,
	to_char(START_TIME, 'yyyy-MM-dd') START_TIME,
	to_char (END_TIME, 'yyyy-MM-dd') END_TIME,
	MONITOR_OBJECT,
	CYCLE_TYPE,
	CLASS_NAME,
	ALARM_LEVEL,
	DEAL_METHOD,
	REMOVE_TAG,
	USE_TAG,
	TASK_ID,
	UPDATE_STAFF_ID,
	UPDATE_DEPART_ID,
	RSRV_NUM1,
	RSRV_NUM2,
	RSRV_NUM3,
	RSRV_NUM4,
	RSRV_NUM5,
	RSRV_STR1,
	RSRV_STR2,
	RSRV_STR3,
	RSRV_STR4,
	RSRV_STR5,
	RSRV_DATE1,
	RSRV_DATE2,
	RSRV_DATE3
FROM TD_RULE_FORALARM
WHERE REMOVE_TAG = '0'
  AND RULE_NAME like '%'||:RULE_NAME||'%'
  AND (CLASS_NAME = :CLASS_NAME OR :CLASS_NAME IS NULL)
  AND START_TIME >= to_date(:START_TIME, 'yyyy-MM-dd')
  AND END_TIME <= to_date(:END_TIME, 'yyyy-MM-dd')
  AND USE_TAG = :USE_TAG	
order by RULE_ID