--IS_CACHE=Y
select RES_ID, RES_NAME, EPARCHY_CODE, RES_TYPE_CODE, RES_KIND_CODE,
CARD_KIND_CODE, CARD_KIND_P, CLASS_ID, VALID_TAG, USE_TAG,
CAMPN_ID, PRODUCT_ID, PACKAGE_ID, SCORE_CODE, VALUE_CODE,
BRAND_CODE, MODEL_CODE, REMARK, UPDATE_TIME, UPDATE_DEPART_ID, 
UPDATE_STAFF_ID,  RSRV_TAG1, RSRV_TAG2, to_date(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') rsrv_date1, to_date(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') rsrv_date2,
RSRV_NUM1, RSRV_STR1, RSRV_STR2, RSRV_STR3
from td_m_resgift 
where res_id=:RES_ID
  and eparchy_code=:EPARCHY_CODE