SELECT LOG_ID,SUBSCRIBE_ID,TRADE_ID,ORDER_ID,NET_TYPE_CODE,TRADE_TYPE_CODE ,EPARCHY_CODE,USER_ID ,SERIAL_NUMBER,BATCH_ID,BATCH_COUNT ,ORDER_INFO,SUBSCRIBE_INFO,SVC_INFO,SVCATTR_INFO,SVCSTATE_INFO,RES_INFO,PARAMS_INFO ,USERSVC_INFO,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9
 FROM Tf_b_Subscriber t
 WHERE trade_id = TO_NUMBER(:TRADE_ID)