insert	into TF_F_USER_RENT
		(PARTITION_ID,USER_ID, RENT_TYPE_CODE, SERIAL_NUMBER, SIM_CARD_NO, IMSI, 
		RENT_SIM_CARD, RENT_IMSI, RENT_DEVICE_NO, RENT_IMEI, RENT_SERIAL_NUMBER, 
		NATIONALITY_AREACODE, START_DATE, END_DATE, UPDATE_TIME, 
		RENT_TAG, OPEN_STAFF_ID, 
		OPEN_DEPART_ID, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, 
		RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, 
		RSRV_STR5, RSRV_DATE1, RSRV_DATE2, 
		RSRV_DATE3)
values (MOD(to_number(:USER_ID),10000), to_number(:USER_ID), :RENT_TYPE_CODE, :SERIAL_NUMBER, :SIM_CARD_NO, :IMSI, 
		:RENT_SIM_CARD, :RENT_IMSI, :RENT_DEVICE_NO, :RENT_IMEI, :RENT_SERIAL_NUMBER, 
		:NATIONALITY_AREACODE, to_date(:START_DATE,'YYYY-MM-DD HH24:MI:SS'), to_date(:END_DATE,'YYYY-MM-DD HH24:MI:SS'), SYSDATE, 
		:RENT_TAG, :OPEN_STAFF_ID, 
		:OPEN_DEPART_ID, to_number(:RSRV_NUM1), to_number(:RSRV_NUM2), to_number(:RSRV_NUM3), to_number(:RSRV_NUM4), 
		to_number(:RSRV_NUM5), :RSRV_STR1, :RSRV_STR2, :RSRV_STR3, :RSRV_STR4, 
		:RSRV_STR5, to_date(:RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS'), to_date(:RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS'), 
		to_date(:RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS'))