select to_char(USER_ID), RENT_TYPE_CODE, SERIAL_NUMBER, SIM_CARD_NO, IMSI, 
		RENT_SIM_CARD, RENT_IMSI, RENT_DEVICE_NO, RENT_IMEI, RENT_SERIAL_NUMBER, 
		NATIONALITY_AREACODE, to_char(START_DATE,'YYYY-MM-DD HH24:MI:HH'), to_char(END_DATE,'YYYY-MM-DD HH24:MI:HH'), 
		RENT_TAG, OPEN_STAFF_ID, 
		OPEN_DEPART_ID, to_char(RSRV_NUM1), to_char(RSRV_NUM2), to_char(RSRV_NUM3), to_char(RSRV_NUM4), 
		to_char(RSRV_NUM5), RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, 
		RSRV_STR5, to_char(RSRV_DATE1,'YYYY-MM-DD HH24:MI:HH'), to_char(RSRV_DATE2,'YYYY-MM-DD HH24:MI:HH'), 
		to_char(RSRV_DATE3,'YYYY-MM-DD HH24:MI:HH')
from TF_F_USER_RENT
where user_id = to_number(:USER_ID)
and sysdate between start_date and end_date