--IS_CACHE=N
SELECT decode(count(1),0,0,1) 前三月是否办理
  FROM TF_F_RELATION_UU U
 WHERE U.USER_ID_B = :USER_ID
   AND U.RELATION_TYPE_CODE = '56' ---- 统一付费关系
   AND U.ROLE_CODE_B = '1' --主号码
   AND U.START_DATE >=ADD_MONTHS(TO_DATE(:ACCEPT_MONTH, 'YYYYMM'), -3)
   AND U.START_DATE < TO_DATE(:ACCEPT_MONTH, 'YYYYMM')