--IS_CACHE=Y
SELECT DEAL_PRICE D_PRICE ,SALE_PRICE S_PRICE ,PRICE_ID,
F_RES_GETCODENAME('staff_id',UPDATE_STAFF_ID, '', '')UPDATE_STAFF_ID,
F_RES_GETCODENAME('depart_id',UPDATE_DEPART_ID, '', '') UPDATE_DEPART_ID,
START_DATE,END_DATE FROM TD_R_TERMINAL_PRICE 
WHERE VALID_TAG='0' AND AUDIT_STATUS='0' AND :PRICE_ID IS NULL OR PRICE_ID =:PRICE_ID