SELECT T.USER_TYPE, T.USER_ID, 
       T.CUST_ID, T.CUST_NAME,
       T.PSPT_TYPE_CODE, T.PSPT_ID, 
       T.INSERT_DATE, T.INSERT_STAFF_ID, T.INSERT_DEPART_ID, 
       T.REMOVE_TAG, T.REMARK, T.RSRV_STR1, T.RSRV_STR2,
       T.RSRV_STR3, T.RSRV_STR4, T.RSRV_STR5
FROM TF_F_USER_PSPT T,TF_F_USER U, TF_F_USER_PRODUCT P, TF_F_CUSTOMER C
WHERE 1=1
   AND T.PSPT_ID = :PSPT_ID
   AND T.CUST_NAME <> :CUST_NAME 
   AND U.CUST_ID = C.CUST_ID
   AND T.CUST_ID = C.CUST_ID   
   AND T.USER_ID = P.USER_ID
   AND T.USER_ID = U.USER_ID
   AND T.CUST_NAME IS NOT NULL
   AND T.PSPT_TYPE_CODE IN ('0', '1','2') 
   AND P.BRAND_CODE IN ('G001','G002','G010','G005','PWLW','IMSG')
