SELECT T.RSRV_STR1,
       T.RSRV_TAG1,
       T.RSRV_STR2,
       T.RSRV_TAG2,
       T.EXTEND_VALUE
FROM TF_F_CUST_GROUP_EXTEND T
WHERE 1 = 1
AND   T.EXTEND_TAG = 'BNUMB'
AND   T.EXTEND_VALUE = :CUST_ID
AND   T.RSRV_TAG1 = '1'