INSERT INTO TF_B_TRADE_PAYRELATION(TRADE_ID,ACCEPT_MONTH,USER_ID,INST_ID,ACCT_ID,PAYITEM_CODE,MODIFY_TAG,ACCT_PRIORITY,ACT_TAG,USER_PRIORITY,
       BIND_TYPE,START_CYCLE_ID,END_CYCLE_ID,DEFAULT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK)
SELECT :TRADE_ID,SUBSTR(:TRADE_ID, 5, 2),TO_CHAR(USER_ID) USER_ID,INST_ID,TO_CHAR(ACCT_ID) ACCT_ID,PAYITEM_CODE,:MODIFY_TAG,ACCT_PRIORITY,ACT_TAG,USER_PRIORITY,
       BIND_TYPE,START_CYCLE_ID,to_char(:END_CYCLE_ID),DEFAULT_TAG,LIMIT_TYPE,TO_CHAR(LIMIT) LIMIT,COMPLEMENT_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK 
  FROM TF_A_PAYRELATION A
 WHERE USER_ID=TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND ACT_TAG = '1'
   AND to_char(:END_CYCLE_ID) BETWEEN START_CYCLE_ID AND END_CYCLE_ID
   AND A.ACCT_ID IN (
   SELECT ACCT_ID  FROM  TF_F_ACCOUNT B,TF_F_CUSTOMER C WHERE  C.CUST_TYPE='1' AND B.Acct_Id=A.ACCT_ID AND B.CUST_ID=C.CUST_ID 
   )