UPDATE /*+INDEX(a PK_TD_M_RES_COMMPARA)*/ td_m_res_commpara a 
   SET para_value2=:PARA_VALUE2,para_value3=:PARA_VALUE3,para_value4=:PARA_VALUE4,para_value5=:PARA_VALUE5,
       para_value6=:PARA_VALUE6,para_value7=:PARA_VALUE7,para_value8=:PARA_VALUE8,para_value11=:PARA_VALUE11,
       para_value9=(:PARA_VALUE2+:PARA_VALUE3+:PARA_VALUE4+:PARA_VALUE5+:PARA_VALUE6+:PARA_VALUE7+:PARA_VALUE8+:PARA_VALUE11),rdvalue1=SYSDATE,update_time=SYSDATE,update_staff_id=:UPDATE_STAFF_ID,update_depart_id=:UPDATE_DEPART_ID
WHERE eparchy_code=:EPARCHY_CODE
   AND para_attr=:PARA_ATTR
   AND (:PARA_CODE1 IS NULL OR (:PARA_CODE1 IS NOT NULL AND para_code1=:PARA_CODE1))
   AND (:PARA_CODE2 IS NULL OR (:PARA_CODE2 IS NOT NULL AND para_code2=:PARA_CODE2))