DECLARE
  V_TRADE_ID          NUMBER(16)	:= TO_NUMBER(:TRADE_ID);
  V_USER_ID           NUMBER(16)	:= TO_NUMBER(:USER_ID);
  V_RSRV_VALUE_CODE   VARCHAR2(100)	:= :RSRV_VALUE_CODE;
  V_RES_NO            VARCHAR2(100)	:= :RES_NO;
  V_DEVICE_MODEL_CODE VARCHAR2(100)	:= :DEVICE_MODEL_CODE;
  V_DEVICE_MODEL      VARCHAR2(100)	:= :DEVICE_MODEL;
  V_DEVICE_COST       VARCHAR2(100)	:= :DEVICE_COST;
  V_DEVICE_BRAND_CODE VARCHAR2(100)	:= :DEVICE_BRAND_CODE;
  V_DEVICE_BRAND      VARCHAR2(100)	:= :DEVICE_BRAND;
  V_SUPPLY_COOP_ID    VARCHAR2(100)	:= :SUPPLY_COOP_ID;
  V_RSRV_STR7         VARCHAR2(100)	:= :RSRV_STR7;
  V_RSRV_TAG1         VARCHAR2(100)	:= :RSRV_TAG1;
  
  -- 分区条件
  V_PARTITION_ID      NUMBER(4);
  V_ACCEPT_MONTH      NUMBER(2);
BEGIN
  V_PARTITION_ID := MOD(V_USER_ID, 10000);
  V_ACCEPT_MONTH := TO_NUMBER(SUBSTR(TO_CHAR(V_TRADE_ID), 5, 2));
  
  UPDATE TF_F_USER_SALE_GOODS T
     SET T.DEVICE_MODEL_CODE = V_DEVICE_MODEL_CODE,
         T.DEVICE_MODEL      = V_DEVICE_MODEL,
         T.DEVICE_COST       = V_DEVICE_COST,
         T.DEVICE_BRAND_CODE = V_DEVICE_BRAND_CODE,
         T.DEVICE_BRAND      = V_DEVICE_BRAND,
         T.RES_TAG           = '1',
         T.RES_CODE          = V_RES_NO,
         T.RSRV_STR1         = V_SUPPLY_COOP_ID,
         T.RSRV_STR7         = V_RSRV_STR7,
         T.RSRV_TAG1         = V_RSRV_TAG1
   WHERE T.PARTITION_ID      = V_PARTITION_ID
     AND T.RELATION_TRADE_ID = V_TRADE_ID;
     
  UPDATE TF_B_TRADE_SALE_GOODS T
     SET T.DEVICE_MODEL_CODE = V_DEVICE_MODEL_CODE,
         T.DEVICE_MODEL      = V_DEVICE_MODEL,
         T.DEVICE_COST       = V_DEVICE_COST,
         T.DEVICE_BRAND_CODE = V_DEVICE_BRAND_CODE,
         T.DEVICE_BRAND      = V_DEVICE_BRAND,
         T.RES_TAG           = '1',
         T.RES_CODE          = V_RES_NO,
         T.RSRV_STR1         = V_SUPPLY_COOP_ID,
         T.RSRV_STR7         = V_RSRV_STR7,
         T.RSRV_TAG1         = V_RSRV_TAG1
   WHERE T.ACCEPT_MONTH      = V_ACCEPT_MONTH
     AND T.TRADE_ID          = V_TRADE_ID;
     
  UPDATE TF_F_USER_OTHER T
     SET T.RSRV_TAG1         = '1'
   WHERE T.PARTITION_ID      = V_PARTITION_ID
     AND T.USER_ID           = V_USER_ID
     AND T.RSRV_VALUE_CODE   = V_RSRV_VALUE_CODE
     AND T.TRADE_ID          = V_TRADE_ID;
  
END;