SELECT
  T.SYS_CODE, T.OPER_TYPE, T.PARAM_CODE, T.DIRECTION, T.PROD_ID, T.PARAM_DESC, T.CHG_PARAM_CODE, T.CHG_PARAM_DESC,
  T.VALID_TAG, T.ACCEPT_DEPART_ID, T.UPDATE_DEPART_ID, T.UPDATE_STAFF_ID, T.ACCEPT_STAFF_ID, T.CREATE_DATE,
  T.UPDATE_DATE
FROM TD_B_EOP_PARAM_TRANS T
WHERE T.OPER_TYPE = :OPER_TYPE