SELECT COUNT(*) RECORDCOUNT
  FROM TF_B_TRADE_RES A
 WHERE A.TRADE_ID = :TRADE_ID
   AND a.accept_month = to_number(substr(:TRADE_ID,5,2))
   AND A.MODIFY_TAG = '1'
   AND NOT EXISTS
 (SELECT 1
          FROM TF_F_USER_RES B
         WHERE B.USER_ID = :USER_ID
           AND B.RES_TYPE_CODE = A.RES_TYPE_CODE
           AND B.PARTITION_ID = MOD(:USER_ID, 10000)
           AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
           AND B.RES_CODE = A.RES_CODE)