--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份, A.TRADE_ID 台账标识,A.TRADE_DEPART_ID 受理部门,A.TRADE_STAFF_ID 受理工号
FROM UCR_CRM1.TF_BH_TRADE A, TD_M_DEPART D
WHERE A.USER_ID = TO_NUMBER(:USER_ID)
 AND A.TRADE_TYPE_CODE IN ('10','60')
 AND A.IN_MODE_CODE = 'SD'
 AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
 AND A.CANCEL_TAG = '0'
 AND A.TRADE_DEPART_ID = D.DEPART_ID
 AND EXISTS(
     SELECT 1 FROM TF_F_USER U WHERE U.USER_ID = TO_NUMBER(:USER_ID) AND U.REMOVE_TAG='0'
     AND TRUNC(U.OPEN_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
 )
 AND ROWNUM < 2