INSERT INTO TF_B_TRADE_ATTR(TRADE_ID,ACCEPT_MONTH,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,MODIFY_TAG,
   UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1)
SELECT a.TRADE_ID,a.ACCEPT_MONTH,a.USER_ID,'S',a.INST_ID,:ATTR_CODE,
   DECODE(:MODE, '0', NULL, TO_CHAR(ADD_MONTHS(TRUNC(b.open_date,'mm'),TO_NUMBER(:MONTHS))-1/24/3600,'yyyy-mm-dd hh24:mi:ss')),
   a.START_DATE,a.END_DATE,'0',a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,a.REMARK,:SERVICE_ID
FROM TF_B_TRADE_SVC a,tf_b_trade_user b
WHERE a.TRADE_ID = to_number(:TRADE_ID)
  AND a.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND a.USER_ID = to_number(:USER_ID)
  AND a.SERVICE_ID = :SERVICE_ID
  AND a.MODIFY_TAG = '0'
  AND b.TRADE_ID = to_number(:TRADE_ID)
  AND b.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND trim(:MODE) is not null
  AND :MODE != '0'