SELECT C.USER_ID_A, C.SERIAL_NUMBER_A, C.USER_ID_B, C.SERIAL_NUMBER_B
  FROM TF_F_RELATION_UU C
 WHERE C.USER_ID_A = :USER_ID_A
   AND C.END_DATE > SYSDATE
   AND NOT EXISTS (SELECT 1
          FROM TF_F_USER_DISCNT A, TD_S_COMMPARA B
         WHERE C.USER_ID_B = A.USER_ID
           AND C.PARTITION_ID = A.PARTITION_ID
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
		   AND A.END_DATE > TRUNC(LAST_DAY(SYSDATE))+ 1 + 1/24/60/60
           AND TO_CHAR(A.DISCNT_CODE) = B.PARAM_CODE
           AND B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_ATTR = 9018
           AND B.END_DATE > SYSDATE)