SELECT TO_CHAR(U.OPEN_DATE, 'YYYYMM') OPEN_DATE
  FROM TF_F_USER U
 WHERE U.USER_ID = TO_NUMBER(:USER_ID)
   AND U.PARTITION_ID = MOD(:USER_ID, 10000)
   AND U.REMOVE_TAG = 0
   AND U.ACCT_TAG = 0
   AND (TO_CHAR(U.OPEN_DATE, 'YYYYMM') = TO_CHAR(SYSDATE, 'YYYYMM') OR
       (:OPER_CODE IN ('408','409','410','416','417') AND
       TO_DATE('2018-05-01', 'yyyy-mm-dd') > SYSDATE AND
       U.OPEN_DATE > TO_DATE('2018-01-01', 'yyyy-mm-dd')))