SELECT A.VPN_SCARE_CODE,
       B.USER_ID,
       A.VPN_NO,
       A.VPN_NAME,
       A.CUST_MANAGER,
       B.CITY_CODE,
       B.IN_DATE
  FROM TF_F_USER_VPN A, TF_F_USER B
 WHERE B.USER_ID = A.USER_ID(+)
   AND B.PARTITION_ID = MOD(B.USER_ID, 10000)
   AND A.REMOVE_TAG = '0'
   AND B.REMOVE_TAG = '0'
   AND B.USER_ID = TO_NUMBER(:USER_ID)