SELECT 
t.ACCEPT_MONTH,
t.FEE_CYCLE,
t.SERIAL_NUMBER,
t.AGENT_ID,
t.AGENT_NAME,
t.ACCEPT_CHANNEL,
t.BANK,
t.BANK_NO,
t.BANK_NAME,
(t.ALLFEE/100) ALLFEE,
(t.OLDFEE/100) OLDFEE,
(t.REMAINFEE/100) REMAINFEE,
t.IN_TIME,
DECODE(t.PROCESS_TAG,  '0','待处理','1','生成文件',  '2','没回缴文件','3','未回缴完','8','全部回缴完成','全部回缴完成') PROCESS_TAG ,
t.PROCESS_TAG PROCESS_TAG_NUM,
t.EXEC_TIME,
t.DEAL_TIMES,
t.RSRV_STR1,
t.RSRV_STR2,
t.RSRV_STR3,
t.RSRV_STR4,
t.RSRV_STR5,
t.REMARK,
ROWIDTOCHAR(ROWID) RECORDROWID


FROM  TL_O_FEEAGENTLOG  T  
WHERE 1=1   
AND T.FEE_CYCLE= :FEE_CYCLE
AND T.AGENT_ID= :AGENT_ID
AND T.PROCESS_TAG= :PROCESS_TAG
AND T.BANK_NAME= :BANK_NAME
AND T.IN_TIME> ( SELECT (SYSDATE-90) RECORDDATE FROM   DUAL )

