SELECT :SYNC_DAY SYNC_DAY, :SYNC_SEQUENCE SYNC_SEQUENCE, '8' MODIFY_TAG, :TRADE_ID TRADE_ID,
               INTEGRAL_PLAN_INST_ID, MOD(USER_ID, 10000) PARTITION_ID, USER_ID,
               INTEGRAL_ACCT_ID, INTEGRAL_PLAN_ID, START_DATE, END_DATE, STATUS,
               REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5,
               RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_DATE1,
               RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
          FROM TF_F_INTEGRAL_PLAN
         WHERE USER_ID = :USER_ID
           AND PARTITION_ID = MOD(:USER_ID, 10000)