INSERT INTO TS_M_STAFF_CLCTTIME_TEMP
      (CLCT_DAY,STAFF_ID,DEPART_ID,CITY_CODE,START_DATE,END_DATE)
SELECT :CLCT_DAY,:STAFF_ID,:DEPART_ID,:CITY_CODE,TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE
  FROM DUAL