--IS_CACHE=Y
SELECT TRADE_TYPE_CODE, IN_MODE_CODE, VIP_CLASS_ID, PRODUCT_ID, PACKAGE_ID, ELEMENT_TYPE_CODE, ELEMENT_ID, to_char(CAMPN_ID) CAMPN_ID, FEE_MODE, FEE_TYPE_CODE, to_char(FEE) FEE, to_char(LIMIT_MONEY) LIMIT_MONEY, PAY_MODE, IN_DEPOSIT_CODE, OUT_DEPOSIT_CODE, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, EPARCHY_CODE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10, TRADE_FEE_TYPE, RULE_BIZ_KIND_CODE
  from TD_B_PRODUCT_TRADEFEE t
 where (t.TRADE_TYPE_CODE = :TRADE_TYPE_CODE Or TRADE_TYPE_CODE ='-1')    
   and (t.PRODUCT_ID = :PRODUCT_ID or t.PRODUCT_ID = '-1')
   and (t.PACKAGE_ID = :PACKAGE_ID or t.PACKAGE_ID = '-1')
   and t.TRADE_FEE_TYPE =:TRADE_FEE_TYPE
  and sysdate between t.START_DATE and t.END_DATE