UPDATE TF_F_USER_RECOMM
SET end_date = SYSDATE
WHERE user_id = :USER_ID
AND partition_id=MOD(:USER_ID, 10000)
AND EPARCHY_CODE = :EPARCHY_CODE
AND RECOMM_TYPE = :RECOMM_TYPE
AND ELEMENT_ID = :ELEMENT_ID
AND RECOMM_TAG = '0'
AND END_DATE > SYSDATE