delete from  tf_f_user_recomm 
WHERE USER_ID=TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')
   AND RECOMM_TYPE=:RECOMM_TYPE
   AND RECOMM_TRADE_ID=:RECOMM_TRADE_ID
   AND ELEMENT_ID=:ELEMENT_ID