SELECT  RECOMM_ID,USER_ID,PARTITION_ID,CUST_NAME,SERIAL_NUMBER,EPARCHY_CODE,RECOMM_EVENT,RECOMM_TYPE,RECOMM_SOURCE,RECOMM_PRIORITY,
        PRODUCT_ID,PACKAGE_ID,ELEMENT_ID,ELEMENT_NAME,RECOMM_TAG,REPLY_CODE,REPLY_NOTES,RECOMM_DATE,RECOMM_STAFF_ID,RECOMM_DEPART_ID,
        RECOMM_TRADE_ID,ACCEPT_STAFF_ID,ACCEPT_DEPART_ID,ACCEPT_TIME,ACCEPT_TRADE_ID,RSRV_INFO1,RSRV_INFO2,RSRV_INFO3,RSRV_INFO4,RSRV_INFO5,
        INFO_TAG_SET,CREATE_TIME,CREATE_STAFF_ID,CREATE_DEPART_ID,REMARK,START_DATE,END_DATE,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_STR1,
        RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3      
   FROM TF_F_USER_RECOMM a
   WHERE 1=1
   AND a.USER_ID=TO_NUMBER(:USER_ID)
   AND a.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND a.RECOMM_TYPE = '2'
   AND a.RECOMM_TAG = '0'   
   AND SYSDATE BETWEEN a.START_DATE AND a.END_DATE
   AND NOT EXISTS(SELECT * FROM tf_f_user_svc
                   WHERE 1=1
                     AND partition_id = MOD(TO_NUMBER(:USER_ID),10000)
                     AND user_id = TO_NUMBER(:USER_ID)
                     AND service_id+0 = to_number(a.element_id)
                     AND SYSDATE < end_date)