UPDATE TF_f_USER_RECOMM
   SET RECOMM_TAG = '1',REPLY_CODE=:REPLY_CODE,RECOMM_TRADE_ID=:RECOMM_TRADE_ID,
       RECOMM_DATE=TO_DATE(:RECOMM_DATE,'yyyy-mm-dd hh24:mi:ss'),
       RECOMM_STAFF_ID=:RECOMM_STAFF_ID,RECOMM_DEPART_ID=:RECOMM_DEPART_ID,
       REPLY_NOTES=:REPLY_NOTES
 WHERE user_id = TO_NUMBER(:USER_ID)
   AND partition_id = MOD(TO_NUMBER(:USER_ID),10000)
   AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')
   AND RECOMM_TYPE=:RECOMM_TYPE
   AND ELEMENT_ID=:ELEMENT_ID
   AND RECOMM_TAG=:RECOMM_TAG