SELECT *
  FROM TF_F_USER_DISCNT T
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.DISCNT_CODE = :DISCNT_CODE
   AND T.START_DATE >= TRUNC(TO_DATE(:BOOK_DATE, 'yyyy-mm-dd hh24:mi:ss'), 'yyyy')
   AND T.START_DATE < add_months(TRUNC(TO_DATE(:BOOK_DATE, 'yyyy-mm-dd hh24:mi:ss'), 'yyyy'),12)
   AND T.END_DATE > T.START_DATE