--IS_CACHE=Y
SELECT A.DEPART_ID, A.DEPART_CODE, A.DEPART_NAME
  FROM TD_M_DEPART A
 WHERE A.DEPART_ID = :PARENT_DEPART_ID
   AND A.VALIDFLAG = :VALIDFLAG
   AND A.END_DATE > SYSDATE
 START WITH A.DEPART_ID = :DEPART_ID
CONNECT BY PRIOR A.PARENT_DEPART_ID = A.DEPART_ID