INSERT INTO TF_B_TRADE_PAYRELATION_BAK
  (TRADE_ID, ACCEPT_MONTH, PARTITION_ID, USER_ID, ACCT_ID, PAYITEM_CODE,
   ACCT_PRIORITY, USER_PRIORITY, ADDUP_MONTHS, ADDUP_METHOD, BIND_TYPE,
   DEFAULT_TAG, ACT_TAG, LIMIT_TYPE, LIMIT, COMPLEMENT_TAG, INST_ID,
   START_CYCLE_ID, END_CYCLE_ID, UPDATE_TIME, UPDATE_STAFF_ID,
   UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
   RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10)
  SELECT TO_NUMBER(:TRADE_ID), TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         PARTITION_ID, USER_ID, ACCT_ID, PAYITEM_CODE, ACCT_PRIORITY,
         USER_PRIORITY, ADDUP_MONTHS, ADDUP_METHOD, BIND_TYPE, DEFAULT_TAG,
         ACT_TAG, LIMIT_TYPE, LIMIT, COMPLEMENT_TAG, INST_ID, START_CYCLE_ID,
         END_CYCLE_ID, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID,
         REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5,
         RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10
    FROM TF_A_PAYRELATION A
   WHERE A.USER_ID = TO_NUMBER(:USER_ID)
     AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND A.DEFAULT_TAG = :DEFAULT_TAG
     AND A.ACT_TAG = :ACT_TAG
     AND TO_CHAR(SYSDATE, 'YYYYMM') BETWEEN A.START_CYCLE_ID AND
         A.END_CYCLE_ID
     AND NOT EXISTS (SELECT 1
            FROM TF_B_TRADE_PAYRELATION_BAK B
           WHERE B.TRADE_ID = :TRADE_ID
             AND B.USER_ID = :USER_ID
             AND B.DEFAULT_TAG = A.DEFAULT_TAG
             AND B.ACT_TAG = A.ACT_TAG
             AND B.INST_ID = A.INST_ID
             AND B.START_CYCLE_ID = A.START_CYCLE_ID
             AND B.END_CYCLE_ID = A.END_CYCLE_ID)