DELETE FROM TF_F_USER_SVC
WHERE PARTITION_ID=MOD(to_number(:USER_ID),10000)
AND user_id =to_number(:USER_ID)
AND SERVICE_ID=:SERVICE_ID
And user_id_A =:USER_ID_A
And PRODUCT_ID=:PRODUCT_ID
And PACKAGE_ID =:PACKAGE_ID
AND START_DATE=TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')