SELECT US.SERVICE_ID ELEMENT_ID,
       US.USER_ID,
       'S' ELEMENT_TYPE_CODE,
       US.INST_ID,
	   US.MAIN_TAG,
       TO_CHAR(US.START_DATE, 'yyyy-mm-dd') START_DATE,
       TO_CHAR(US.END_DATE, 'yyyy-mm-dd') END_DATE
  FROM TF_F_USER_SVC US 
 WHERE US.USER_ID = TO_NUMBER(:USER_ID)
   AND US.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE < US.END_DATE + 0
   AND US.START_DATE < US.END_DATE + 0
UNION
SELECT UD.DISCNT_CODE ELEMENT_ID,
       UD.USER_ID,
       'D' ELEMENT_TYPE_CODE,
       UD.INST_ID,
	   '0' MAIN_TAG,
       TO_CHAR(UD.START_DATE, 'yyyy-mm-dd') START_DATE,
       TO_CHAR(UD.END_DATE, 'yyyy-mm-dd') END_DATE
  FROM TF_F_USER_DISCNT UD 
 WHERE UD.USER_ID = TO_NUMBER(:USER_ID)
   AND UD.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE < UD.END_DATE + 0
   AND UD.START_DATE < UD.END_DATE + 0
UNION  
SELECT UP.SERVICE_ID ELEMENT_ID,
       UP.USER_ID,
       'Z' ELEMENT_TYPE_CODE,
	   UP.INST_ID,
       '0' MAIN_TAG,
       TO_CHAR(UP.START_DATE, 'YYYY-MM-DD') START_DATE,
       TO_CHAR(UP.END_DATE, 'YYYY-MM-DD') END_DATE
  FROM TF_F_USER_PLATSVC UP
 WHERE UP.USER_ID = TO_NUMBER(:USER_ID)
   AND UP.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE BETWEEN UP.START_DATE AND UP.END_DATE