SELECT US.SERVICE_ID ELEMENT_ID,
       US.USER_ID,
       US.USER_ID_A,
       'S' ELEMENT_TYPE_CODE,
       US.INST_ID,
       TO_CHAR(US.START_DATE, 'yyyy-mm-dd') START_DATE,
       TO_CHAR(US.END_DATE, 'yyyy-mm-dd') END_DATE
  FROM TF_F_USER_SVC US 
 WHERE US.USER_ID = :USER_ID_A
   AND US.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_A), 10000)
   AND SYSDATE < US.END_DATE
UNION
SELECT UD.DISCNT_CODE ELEMENT_ID,
       UD.USER_ID,
       UD.USER_ID_A,
       'D' ELEMENT_TYPE_CODE,
       UD.INST_ID,
       TO_CHAR(UD.START_DATE, 'yyyy-mm-dd') START_DATE,
       TO_CHAR(UD.END_DATE, 'yyyy-mm-dd') END_DATE
  FROM TF_F_USER_DISCNT UD 
 WHERE UD.USER_ID = :USER_ID
   AND UD.USER_ID_A = :USER_ID_A
   AND UD.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE < UD.END_DATE
