SELECT A.SERVICE_ID ELEMENT_ID, 
       'S' ELEMENT_TYPE_CODE, A.MAIN_TAG, A.INST_ID,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE, 'EXIST' STATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE, B.ATTR_CODE,
       B.ATTR_VALUE
  FROM TF_F_USER_SVC A, TF_F_USER_ATTR B
 WHERE A.PARTITION_ID = B.PARTITION_ID
   AND A.USER_ID = B.USER_ID
   AND A.INST_ID = B.RELA_INST_ID
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND B.INST_TYPE = 'S'
   AND A.END_DATE > SYSDATE
   AND B.END_DATE > SYSDATE
UNION
SELECT A.SERVICE_ID ELEMENT_ID, 
       'S' ELEMENT_TYPE_CODE, A.MAIN_TAG, A.INST_ID, 
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE, 'EXIST' STATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE, '' ATTR_CODE,
       '' ATTR_VALUE
  FROM TF_F_USER_SVC A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.END_DATE > SYSDATE
   AND NOT EXISTS (SELECT 1
          FROM TF_F_USER_ATTR C
         WHERE A.USER_ID = C.USER_ID
           AND C.PARTITION_ID = MOD(A.USER_ID, 10000)
           AND A.INST_ID = C.RELA_INST_ID
           AND C.INST_TYPE = 'S'
           AND C.END_DATE > SYSDATE)
