UPDATE TF_F_USER_SVC
   SET START_DATE       = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       REMARK           = :REMARK,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       RSRV_DATE2       = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE3       = TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SERVICE_ID = TO_NUMBER(:SERVICE_ID)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND PRODUCT_ID = TO_NUMBER(:PRODUCT_ID)
   AND PACKAGE_ID = TO_NUMBER(:PACKAGE_ID)
   AND INST_ID = TO_NUMBER(:INST_ID)
   AND END_DATE + 0 > SYSDATE