UPDATE TF_F_USER_WIDENET_ACT T
   SET T.ACCT_PASSWD = :ACCT_PASSWD,
       T.UPDATE_TIME = sysdate,
       T.UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       T.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.USER_ID = :USER_ID
   AND T.ACCT_ID = :ACCT_ID
   AND T.START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')