INSERT INTO TF_B_TRADE_DISCNT_BAK (TRADE_ID,ACCEPT_MONTH,PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,DISCNT_CODE,SPEC_TAG,RELATION_TYPE_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:TRADE_ID),TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,DISCNT_CODE,SPEC_TAG,RELATION_TYPE_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_DISCNT a
 WHERE USER_ID in( select user_id
                     from tf_b_trade_discnt
                     where trade_id = TO_NUMBER(:TRADE_ID)
                     and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2)))
AND NOT EXISTS (SELECT 1 FROM tf_b_trade_discnt_bak
                   WHERE  trade_id = TO_NUMBER(:TRADE_ID)
                   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2)) 
                   AND user_id_a = a.user_id_a
                   AND user_id = a.user_id
                   AND discnt_code = a.discnt_code
                   AND start_date = a.start_date)