(SELECT to_char(a.user_id) user_id,a.serial_number,a.purchase_attr,a.purchase_desc,a.purchase_mode,a.purchase_info,to_char(a.trade_id) trade_id,to_char(a.rpay_mpfee) rpay_mpfee,a.feeitem_code,to_char(a.rpay_foregift) rpay_foregift,a.foregift_code,to_char(a.rpay_deposit) rpay_deposit,a.rpay_deposit_code,to_char(a.left_deposit) left_deposit,to_char(a.mrtn_fee) mrtn_fee,a.rtn_type,a.rtn_months,a.left_months,to_char(a.gpay_deposit) gpay_deposit,a.gpay_deposit_code,to_char(a.left_gdeposit) left_gdeposit,to_char(a.mgift_fee) mgift_fee,a.gift_type,a.gtotal_months,a.gleft_months,to_char(a.month_fee) month_fee,a.ntotal_months,a.nleft_months,a.device_type,a.imei,a.assure_no,a.discnt_code,a.rsrv_str1,a.rsrv_str2,a.rsrv_str3,a.rsrv_str4,a.rsrv_str5,a.rsrv_str6,a.rsrv_str7,a.rsrv_str8,'PU' rsrv_str9,b.rsrv_str1 rsrv_str10,a.process_tag,a.staff_id,a.depart_id,to_char(a.start_date,'yyyy-mm-dd hh24:mi:ss') start_date,to_char(a.end_date,'yyyy-mm-dd hh24:mi:ss') end_date,to_char(a.finish_date,'yyyy-mm-dd hh24:mi:ss') finish_date,a.remark 
  FROM tf_f_user_purchase a,tf_b_trade_other b
 WHERE a.serial_number=:SERIAL_NUMBER
 AND a.trade_id = b.trade_id(+)
 AND b.rsrv_value_code = 'CITY')    
UNION    
(SELECT to_char(a.user_id) user_id, a.serial_number, a.rsrv_str2 purchase_attr, ( select param_name from td_s_commpara where PARAM_ATTR = 49 and PARAM_CODE = a.rsrv_str2 and rownum = 1 ) purchase_desc, a.rsrv_str1 purchase_mode, a.process_info purchase_info, a.rsrv_str8 trade_id, to_char(to_number(a.rsrv_str5)*a.rsrv_num2 + a.rsrv_num3)  rpay_mpfee, 0 feeitem_code, '' rpay_foregift, 0 foregift_code, to_char(a.rsrv_num3) rpay_deposit, 0 rpay_deposit_code, '' left_deposit, to_char(a.rsrv_num2) mrtn_fee, '' rtn_type,  to_number(a.rsrv_str5) rtn_months, to_number(a.rsrv_str5)-to_number(a.rsrv_str6) left_months,'' gpay_deposit, 0 gpay_deposit_code, '' left_gdeposit, '' mgift_fee, '' gift_type, 0 gtotal_months, 0 gleft_months, '' month_fee, 0 ntotal_months, 0 nleft_months, '' device_type, '' imei, '' assure_no, 0 discnt_code, a.rsrv_str1, a.rsrv_str2, a.rsrv_str3, a.rsrv_str4, a.rsrv_str5, a.rsrv_str6, a.rsrv_str7, a.rsrv_str8, 'A5' rsrv_str9,b.rsrv_str1 rsrv_str10, decode( a.process_tag, '0', '0', '1', '3', '' )process_tag, a.staff_id, a.depart_id, to_char(a.start_date,'yyyy-mm-dd hh24:mi:ss') start_date, to_char( add_months( a.start_date, to_number(a.rsrv_str5) ), 'yyyy-mm-dd hh24:mi:ss' ) end_date,'' finish_date, a.remark
FROM tf_f_user_otherserv a,tf_b_trade_other b               
WHERE a.serial_number=:SERIAL_NUMBER  
    AND a.service_mode = 'A5'
    AND a.rsrv_str8 = b.trade_id(+)
    AND b.rsrv_value_code = 'CITY')