SELECT *
FROM 
(SELECT SUBSTR(A.RES_NO,0,6) RES_NO_STR ,
'此串号定制终端TAC码信息表不存在!' AS ERROR_REASON,A.LOG_ID,'请处理此串号!' AS PROMPT,
A.RES_NO AS TERMINAL_ID
FROM TF_B_CEN_RES_BATCH_TMP A WHERE LOG_ID=:LOG_ID ) B
WHERE NOT EXISTS
(
  SELECT C.TAC_CODE FROM TF_R_TACDATA_GRP C WHERE B.RES_NO_STR=C.TAC_CODE 
     AND C.MATERIAL_CODE=:MATERIAL_CODE AND C.VALID_TAG='0'
)