SELECT to_char(a.TRADE_ID) TRADE_ID,a.CHECK_CARD_NO,a.CHECK_CARD_NAME,a.CHECK_BANK_CODE,to_char(a.CHECK_MONEY) CHECK_MONEY,to_char(a.CHECK_LIMIT) CHECK_LIMIT,a.CHECK_TAG,to_char(a.RECEIVE_DATE,'yyyy-mm-dd hh24:mi:ss') RECEIVE_DATE
  FROM TF_B_TRADEFEE_CHECK a, TF_BH_TRADE b
 WHERE (a.TRADE_ID = to_number(:TRADE_ID) OR :TRADE_ID is NULL)
   AND (CHECK_CARD_NO = :CHECK_CARD_NO OR :CHECK_CARD_NO is NULL)
   AND (CHECK_BANK_CODE = :CHECK_BANK_CODE OR :CHECK_BANK_CODE is NULL)
   AND  a.TRADE_ID = b.TRADE_ID
   AND (b.accept_date >= TRUNC(TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')) OR :START_DATE IS NULL)
   AND (b.accept_date <TRUNC(TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'))+1 OR :END_DATE IS NULL)