--IS_CACHE=N
SELECT ACCOUNT_ID,
       STATE,
       SELECT_TIME,
       PREEMPTION_TIME,
       OCCUPATION_TIME,
       EMANCIPATION_TIME,
       START_DATE,
       END_DATE,
       UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_DATE1,
       RSRV_DATE2,
       RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TD_B_WIDENET_ACCOUNT T
 WHERE (:ACCOUNT_ID IS NULL OR T.ACCOUNT_ID=:ACCOUNT_ID)
   AND (:STATE IS NULL OR T.STATE=:STATE)
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE