INSERT INTO TF_F_USER_PLAT_PARAPLUS(PARTITION_ID,USER_ID,INFO_TYPE,INFO_TAG,INFO_CODE,INFO_VALUE,INFO_NAME,RSRV_STR11,RSRV_STR12,RSRV_STR13,UPDATE_TIME)
 SELECT /*+ index(a PK_TF_B_TRADE_PLAT_PARAPLUS_BA)*/PARTITION_ID,USER_ID,INFO_TYPE,INFO_TAG,INFO_CODE,INFO_VALUE,INFO_NAME,RSRV_STR11,RSRV_STR12,RSRV_STR13,SYSDATE
  FROM TF_B_TRADE_PLAT_PARAPLUS_BAK a
  WHERE TRADE_ID = (SELECT max(a.trade_id)
                      FROM tf_bh_trade a
                     WHERE a.USER_ID=:USER_ID
                       AND a.cancel_tag=:CANCEL_TAG)