INSERT INTO td_b_feecodetype
(eparchy_code,fee_code_rule_code,
fee_code_type_code,fee_type_code,
net_type_code,
fee_code_rule,fee_code_fee,
class_id,order_serial,
update_time,
update_staff_id,update_depart_id,remark,
rsrv_tag1,rsrv_tag2,rsrv_tag3,
rsrv_date1,rsrv_date2,rsrv_date3,
rsrv_str1,rsrv_str2,rsrv_str3)
VALUES(:EPARCHY_CODE,:FEE_CODE_RULE_CODE,
:FEE_CODE_TYPE_CODE,:FEE_TYPE_CODE,
:NET_TYPE_CODE,
:FEE_CODE_RULE,TO_NUMBER(:FEE_CODE_FEE),
:CLASS_ID,:ORDER_SERIAL,
SYSDATE,
:UPDATE_STAFF_ID,:UPDATE_DEPART_ID,:REMARK,
:RSRV_TAG1,:RSRV_TAG2,:RSRV_TAG3,
TO_DATE(:RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS'),
TO_DATE(:RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS'),
TO_DATE(:RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS'),
:RSRV_STR1,:RSRV_STR2,:RSRV_STR3)