DELETE FROM TD_B_EWE_ROLE_TEMPLET T
 WHERE T.BPM_TEMPLET_ID = :BPM_TEMPLET_ID
   AND T.BUSI_TYPE = :BUSI_TYPE
   AND T.BUSI_CODE = :BUSI_CODE
   AND T.NODE_ID = :NODE_ID
   AND T.VALID_TAG = :VALID_TAG
