SELECT T.BPM_TEMPLET_ID,
       T.NODE_ID,
       T.BUSI_TYPE,
       T.BUSI_CODE,
       T.ROLE_ID,
       T.EOS_ROLE_ID,
       T.REMARK,
       T.VALID_TAG,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_ROLE_TEMPLET T
 WHERE T.ROLE_ID = :ROLE_ID
   AND T.VALID_TAG = :VALID_TAG
