
UPDATE TF_R_KKKL_GGCARD A

   SET A.CHANGE_SERIAL_NUMBER = :CHANGE_SERIAL_NUMBER,
       
       A.CHANGE_TIME = SYSDATE,
       
       A.CARD_STATE_CODE = :CARD_STATE_CODE

 WHERE A.CARD_NO = :CARD_NO
