SELECT A.*
  FROM TF_F_USER_PLATSVC A
  WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
  AND   A.USER_ID = :USER_ID
  --AND   A.SERIAL_NUMBER = iv_serial_number
  AND   (A.SERVICE_ID = '99817947' OR A.SERVICE_ID = '99817948' OR A.SERVICE_ID = '99817949')
  AND   (A.BIZ_STATE_CODE = 'A' OR A.BIZ_STATE_CODE = 'N' OR A.BIZ_STATE_CODE = 'L')
  AND   SYSDATE BETWEEN A.START_DATE AND A.END_DATE