--IS_CACHE=Y
SELECT STAFF_ID,DEPART_ID,STAFF_NAME,JOB_CODE,MANAGER_INFO,SEX,EMAIL,USER_PID,SERIAL_NUMBER,to_char(CUST_ID) CUST_ID,DIMISSION_TAG,to_char(BIRTHDAY,'yyyy-mm-dd hh24:mi:ss') BIRTHDAY,STAFF_GROUP_ID,CUST_HOBYY,MANAGER_STAFF_ID,RECEIVE_TYPE_CODE,LOGIN_FLAG,CUST_MANAGER_FLAG,CITY_CODE,EPARCHY_CODE,REMARK,RSVALUE1,RSVALUE2,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID
  FROM TD_M_STAFF
 WHERE depart_id=:DEPART_ID
   AND dimission_tag=:DIMISSION_TAG
   and CUST_MANAGER_FLAG in('3','6','7','8')