SELECT A.USER_ID,B.SERIAL_NUMBER, A.VPN_NO,B.in_date
  FROM TF_F_USER B, TF_F_USER_VPN A,TF_F_USER_PRODUCT P
 WHERE B.USER_ID = A.USER_ID
   AND B.PARTITION_ID = MOD(B.USER_ID, 10000)
   AND B.USER_ID = P.USER_ID
   AND P.PARTITION_ID = MOD(P.USER_ID, 10000)
   AND B.REMOVE_TAG = '0'
   AND A.REMOVE_TAG = '0'
   AND B.CUST_ID = TO_NUMBER(:CUST_ID)
   AND P.PRODUCT_ID IN ('2222', '8016', '6130','8001')