--IS_CACHE=Y
SELECT NVL(PARA_VALUE1, '1') PARA_VALUE1 FROM TD_S_SYSPARA_DEFLIST
 WHERE (EPARCHY_CODE= (SELECT RSVALUE2 FROM TD_M_DEPART
                       WHERE DEPART_ID=(SELECT DEPART_ID FROM TD_M_STAFF WHERE STAFF_ID =:STAFF_ID)) OR EPARCHY_CODE='ZZZZ')
 AND PARA_ATTR = '1000'
 AND PARA_CODE1 = 'IP_ADDR_LIMIT'
 AND PARA_CODE2 = '0'