SELECT USER_ID,
       LTEB_USER_ID,
       CUST_ID,
       ACCT_ID,
       SERIAL_NUMBER,
       IMSI,
       TO_CHAR(OPEN_DATE, 'YYYY-MM-DD HH24:MI:SS') OPEN_DATE,
       REMOVE_TAG,
       TO_CHAR(DESTROY_TIME, 'YYYY-MM-DD HH24:MI:SS') DESTROY_TIME,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
  FROM TF_F_LTEB_USER
    WHERE LTEB_USER_ID = :USER_ID
       AND REMOVE_TAG= :REMOVE_TAG