UPDATE tf_f_user
   SET USER_STATE_CODESET='6',
       REMOVE_TAG=:REMOVE_TAG,
       DESTROY_TIME=SYSDATE,
       REMOVE_EPARCHY_CODE=:REMOVE_EPARCHY_CODE,
       REMOVE_CITY_CODE=:REMOVE_CITY_CODE,
       REMOVE_DEPART_ID=:REMOVE_DEPART_ID,
       REMARK=:REMARK,
       UPDATE_TIME=SYSDATE,
       UPDATE_STAFF_ID=:CANCEL_STAFF_ID,
       UPDATE_DEPART_ID=:CANCEL_DEPART_ID
 WHERE partition_id=MOD(TO_NUMBER(:USER_ID),10000)
   AND user_id=TO_NUMBER(:USER_ID)