SELECT A.CUST_ID, A.DEVICE_PRICE FACE_VALUE, A.SALE_PRICE*100 SAIL_VALUE
  FROM TL_B_VALUECARD_DETAILED A
 WHERE 1 = 1
   AND A.TRADE_TYPE_CODE = 461
   AND A.CARD_NUMBER = :CARD_NUMBER
   AND A.STATE_CODE = '2'