UPDATE TF_F_USER_INFOCHANGE
   SET END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND (END_DATE > SYSDATE OR EXISTS
        (SELECT 1
           FROM TF_B_TRADE_INFOCHANGE_BAK B
          WHERE B.TRADE_ID = :TRADE_ID
            AND B.USER_ID = USER_ID
            AND B.START_DATE = START_DATE))