--IS_CACHE=Y
SELECT TRADE_TYPE_CODE,
       IN_MODE_CODE,
       VIP_CLASS_ID,
       PRODUCT_ID,
       PACKAGE_ID,
       ELEMENT_TYPE_CODE,
       ELEMENT_ID,
       TO_CHAR(CAMPN_ID) CAMPN_ID,
       FEE_MODE,
       FEE_TYPE_CODE,
       TO_CHAR(FEE) FEE,
       TO_CHAR(LIMIT_MONEY) LIMIT_MONEY,
       PAY_MODE,
       IN_DEPOSIT_CODE,
       OUT_DEPOSIT_CODE,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       EPARCHY_CODE,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10,
       TRADE_FEE_TYPE,
       RULE_BIZ_KIND_CODE
  FROM TD_B_PRODUCT_TRADEFEE T
 WHERE (T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE OR TRADE_TYPE_CODE = '-1')
   AND (T.IN_MODE_CODE = :IN_MODE_CODE OR IN_MODE_CODE IS NULL)
   AND (T.VIP_CLASS_ID = :VIP_CLASS_ID OR VIP_CLASS_ID IS NULL)
   AND (T.PRODUCT_ID = :PRODUCT_ID OR T.PRODUCT_ID = '-1')
   AND (T.PACKAGE_ID = :PACKAGE_ID OR T.PACKAGE_ID = '-1')
   AND (T.ELEMENT_ID = :ELEMENT_ID OR T.ELEMENT_ID = '-1')
   AND (T.ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE OR ELEMENT_TYPE_CODE IS NULL)
   AND (T.EPARCHY_CODE = :EPARCHY_CODE OR T.EPARCHY_CODE = 'ZZZZ')
   AND T.TRADE_FEE_TYPE = :TRADE_FEE_TYPE
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
