SELECT AGENT_ID,
       CITY_CODE,
       SERIAL_NUMBER,
       DEPART_ID,
       AGENT_CODE,
       AGENT_NAME,
       ACCOUNT_CODE,
       ACCOUNT_NAME,
       BANK_CODE,
       BANK_NAME,
       PAY_CHANNEL,
       REMOVE_TAG,
       TO_CHAR(ADD_DATE, 'yyyy-mm-dd hh24:mi:ss') ADD_DATE,
       TO_CHAR(MODIFY_DATE, 'yyyy-mm-dd hh24:mi:ss') MODIFY_DATE,
       TO_CHAR(DEL_DATE, 'yyyy-mm-dd hh24:mi:ss') DEL_DATE,
       OPER_STAFF_ID,
       OPER_STAFF_NAME,
       MODIFY_STAFF_ID,
       MODIFY_STAFF_NAME,
       DEL_STAFF_ID,
       DEL_STAFF_NAME,
       REMARK,
       RSRV_NUM1,
       RSRV_STR1,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1
  FROM TF_F_AGENTBANK_ACCOUNTINFO T
 WHERE AGENT_CODE = :AGENT_CODE 
 AND REMOVE_TAG = :REMOVE_TAG 
 AND AGENT_ID <> :AGENT_ID
