SELECT
to_char(TRADE_ID) TRADE_ID,INST_ID, ACCEPT_MONTH, MODIFY_TAG,to_char(USER_ID) USER_ID, DECODE(SUBSTR(TEL_URL,'0','4'),'0898',SUBSTR(TEL_URL,'2'),TEL_URL) TEL_URL, DECODE(SUBSTR(SIP_URL,'0','4'),'0898',SUBSTR(SIP_URL,'2'),SIP_URL) SIP_URL, DECODE(SUBSTR(IMPI,'0','4'),'0898',SUBSTR(IMPI,'2'),IMPI) IMPI, DECODE(SUBSTR(IMS_USER_ID,'0','4'),'0898',SUBSTR(IMS_USER_ID,'2'),IMS_USER_ID) IMS_USER_ID, IMS_PASSWORD, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5
 FROM TF_B_TRADE_IMPU
        WHERE trade_id = :TRADE_ID
        AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
