UPDATE TF_F_USER_SALE_DEPOSIT
   SET END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       RSRV_DATE2       = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE3       = TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = :USER_ID
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND (INST_ID = :INST_ID OR :INST_ID IS NULL)
   AND (DISCNT_GIFT_ID = :DISCNT_GIFT_ID OR :DISCNT_GIFT_ID IS NULL)
   AND RELATION_TRADE_ID = :RELATION_TRADE_ID
   AND END_DATE + 0 > SYSDATE