SELECT C.PARA_CODE3
  FROM TF_F_USER A, TF_F_USER_DISCNT B, TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND B.PARTITION_ID = MOD(:USER_ID, 10000)
   AND B.USER_ID = :USER_ID
   AND A.USER_ID = B.USER_ID
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
      
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '957'
   AND C.PARAM_CODE = '2'
   AND C.PARA_CODE4 = '98'
   AND C.PARA_CODE1 <> '*'
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
      
   AND A.EPARCHY_CODE = C.EPARCHY_CODE
   AND TO_CHAR(B.DISCNT_CODE) = C.PARA_CODE1