--IS_CACHE=Y
select t.CUST_MANAGER_ID, t.CUST_MANAGER_NAME, t.JOB_TYPE, t.VALID_TAG, t.INVALID_DATE, t.DEPART_ID, t.DEPART_FRAME, t.AREA_CODE, t.AREA_FRAME, t.LINK_PHONE, t.SERIAL_NUMBER, t.DUTY, t.LOCAL_NATIVE, t.SEX, t.BIRTHDAY, t.USER_PID, t.GRADUATE_SCHOOL, t.EDUCATE_GRADE_CODE, t.SPECIALITY, t.HOME_ADDRESS, t.HOME_PHONE, t.WORK_BOUND, t.WORK_STORY, t.WORK_DATE, t.WORK_FUNC, t.POLITY, t.FAX, t.EMAIL, t.TRAIT, t.HOBBY, t.TRAIN_RECORD, t.APPRAISE_TAG, t.UPDATE_TIME, t.UPDATE_STAFF_ID, t.UPDATE_DEPART_ID, t.REMARK, t.ID, t.BELONG_TEAM_ID, t.MANAGER_LEVEL, t.RSRV_NUM1, t.RSRV_NUM2, t.RSRV_NUM3, t.RSRV_STR1, t.RSRV_STR2, t.RSRV_STR3, t.RSRV_STR4, t.RSRV_STR5, t.RSRV_STR6, t.RSRV_DATE1, t.RSRV_DATE2, t.RSRV_DATE3, t.RSRV_TAG1, t.RSRV_TAG2, t.RSRV_TAG3, t.CREATE_STAFF_ID, t.CREATE_TIME, t.MANAGER_KIND, t.BBOSS_MANAGER_ID, t.BBOSS_MANAGER_NAME 
  from TF_F_CUST_MANAGER_STAFF t 
    where 1=1 
      and t.job_type = :JOB_TYPE 
      and t.cust_manager_id = :CUST_MANAGER_ID 