INSERT INTO TF_F_INTERNETOFTHINGS_BOOK
  (INST_ID,
   USER_ID,
   SERIAL_NUMBER,
   OLD_STATE_CODE,
   NEW_STATE_CODE,
   TRAN_DATE,
   DEAL_TAG,
   EXEC_TIME,
   RESULT_CODE,
   RESULT_INFO,
   TRADE_ID,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID)
values
  (to_number(:INST_ID),
   to_number(:USER_ID),
   :SERIAL_NUMBER,
   :OLD_STATE_CODE,
   :NEW_STATE_CODE,
   to_date(:TRAN_DATE, 'yyyy-MM-dd hh24:mi:ss'),
   :DEAL_TAG,
   to_date(:EXEC_TIME, 'yyyy-MM-dd hh24:mi:ss'),
   :RESULT_CODE,
   :RESULT_INFO,
   to_number(:TRADE_ID),
   to_date(:UPDATE_TIME, 'yyyy-MM-dd hh24:mi:ss'),
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID)
