INSERT INTO TF_F_USER_PLATSVC_ATTR
  (PARTITION_ID,
   USER_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   INFO_CODE,
   INFO_VALUE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK)
  SELECT :PARTITION_ID,
         :USER_ID,
         :SERVICE_ID,
         :SERIAL_NUMBER,
         :INFO_CODE,
         :INFO_VALUE,
         to_date(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         :REMARK
    FROM DUAL