INSERT INTO TF_F_USER_PLATSVC_ATTR
  (PARTITION_ID,
   USER_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   INFO_CODE,
   INFO_VALUE,
   INFO_NAME,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3)
  SELECT MOD(USER_ID, 10000),
         USER_ID,
         SERVICE_ID,
         SERIAL_NUMBER,
         INFO_CODE,
         INFO_VALUE,
         INFO_NAME,
         UPDATE_TIME,
         UPDATE_STAFF_ID,
         UPDATE_DEPART_ID,
         REMARK,
         RSRV_NUM1,
         RSRV_NUM2,
         RSRV_STR1,
         RSRV_STR2,
         RSRV_DATE1,
         RSRV_DATE2,
         RSRV_DATE3
    FROM TF_B_TRADE_PLATSVC_ATTR
   WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND TRADE_ID = :TRADE_ID
     AND USER_ID = :USER_ID
     AND SERVICE_ID = :SERVICE_ID