SELECT INFO_CODE, INFO_VALUE
  FROM TF_F_USER_PLATSVC_ATTR A
 WHERE A.PARTITION_ID =  MOD(TO_NUMBER(:USER_ID),10000) 
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.INFO_CODE = :INFO_CODE