SELECT A.USER_ID,
       A.SERVICE_ID,
       A.INFO_CODE,
       A.INFO_VALUE,
       CC.PARA_CODE2,
       CC.PARA_CODE10,
       C.INFO_CODE INFO1,
       C.INFO_VALUE INFO2,
       DD.PARA_CODE2 PARA2,
       DD.PARA_CODE10 PARA_VALUE10
  FROM TF_B_TRADE_PLATSVC_ATTR C,
       TF_F_USER_PLATSVC_ATTR  A,
       TD_S_COMMPARA           CC,
       TD_S_COMMPARA           DD
 WHERE C.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND C.TRADE_ID = :TRADE_ID
   AND C.USER_ID = :USER_ID
   AND C.SERVICE_ID = :SERVICE_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND C.INFO_CODE = A.INFO_CODE      
   AND CC.SUBSYS_CODE = 'CSM'
   AND CC.PARAM_ATTR = 3700
   AND CC.PARAM_CODE = :SERVICE_ID
   AND CC.PARA_CODE3 = A.INFO_CODE
   AND CC.PARA_CODE1 = A.INFO_VALUE 
   AND CC.PARA_CODE4 IS NULL     
   AND DD.SUBSYS_CODE = 'CSM'
   AND DD.PARAM_ATTR = 3700
   AND DD.PARAM_CODE = :SERVICE_ID
   AND DD.PARA_CODE3 = C.INFO_CODE
   AND DD.PARA_CODE1 = C.INFO_VALUE
   AND DD.PARA_CODE4 IS NULL