SELECT B.INFO_CODE, B.INFO_VALUE
  FROM TF_F_USER_PLATSVC A, TF_F_USER_PLATSVC_ATTR B
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.BIZ_TYPE_CODE = :BIZ_TYPE_CODE
   AND A.BIZ_STATE_CODE = 'A' 
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND A.USER_ID = B.USER_ID
   AND A.SERVICE_ID = B.SERVICE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND B.INFO_CODE = :INFO_CODE