UPDATE TF_F_USER_PLATSVC_ATTR A
   SET A.INFO_VALUE       = :INFO_VALUE,
       A.UPDATE_TIME      = to_date(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
       A.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND USER_ID = :USER_ID
   AND SERVICE_ID = :SERVICE_ID
   AND INFO_CODE = :INFO_CODE