SELECT A.USER_ID,
       A.SERVICE_ID,
       B.PARA_CODE1,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID
  FROM TF_B_TRADE_PLATSVC A, TD_S_COMMPARA B
 WHERE A.TRADE_ID = :TRADE_ID
   AND B.PARAM_ATTR = '3746'
   AND B.PARAM_CODE = 'Z'
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND A.SERVICE_ID = B.PARA_CODE2
   AND A.BIZ_STATE_CODE = 'E'
UNION
SELECT C.USER_ID,
       C.SERVICE_ID,
       D.PARA_CODE1,
       C.UPDATE_STAFF_ID,
       C.UPDATE_DEPART_ID
  FROM TF_B_TRADE_SVC C, TD_S_COMMPARA D
 WHERE C.TRADE_ID = :TRADE_ID
   AND D.PARAM_ATTR = '3746'
   AND D.PARAM_CODE = 'S'
   AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
   AND C.SERVICE_ID = D.PARA_CODE2
   AND C.MODIFY_TAG = '1'