--IS_CACHE=Y
SELECT A.STAFF_ID, A.DATA_CODE RIGHT_CODE, A.DATA_TYPE RIGHT_TYPE
  FROM TF_M_STAFFDATARIGHT A
 WHERE A.STAFF_ID = :STAFF_ID
   AND A.RIGHT_ATTR = '0'
   AND A.RIGHT_TAG = '1'
UNION
SELECT DISTINCT A.STAFF_ID, C.DATA_CODE RIGHT_CODE, C.DATA_TYPE RIGHT_TYPE
  FROM TF_M_STAFFDATARIGHT A, TD_M_ROLE B, TF_M_ROLEDATARIGHT C
 WHERE 1 = 1
   AND A.STAFF_ID = :STAFF_ID
   AND A.RIGHT_ATTR = '1'
   AND A.RIGHT_TAG = '1'
   AND A.DATA_CODE = B.ROLE_CODE
   AND B.ROLE_CODE = C.ROLE_CODE
   AND A.DATA_TYPE = B.ROLE_ATTR
   AND B.ROLE_ATTR = C.DATA_TYPE
   AND B.VALIDFLAG = '0'
UNION
SELECT A.STAFF_ID, A.DATA_CODE RIGHT_CODE, A.DATA_TYPE RIGHT_TYPE
  FROM TF_M_STAFFTEMPDATARIGHT A
 WHERE 1 = 1
   AND A.STAFF_ID = :STAFF_ID