--IS_CACHE=Y
SELECT *
  FROM TD_S_COMMPARA A
 WHERE A.PARAM_ATTR = :PARAM_ATTR
   AND A.PARAM_CODE = :PARAM_CODE
   AND A.PARA_CODE1 = :PARA_CODE1
   AND (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE