SELECT NULL eparchy_code,
       NULL print_id,
       1 partition_id,
       NULL  batch_id,
       NULL charge_id,
       templet_code,
       NULL note_no,
       NULL  acct_id,
       NULL pay_name,
       NULL serial_number,
       NULL  user_id,
       NULL  min_bill_id,
       NULL  max_bill_id,
       NULL  score_value,
       NULL  credit_value,
       NULL  round_fee,
       NULL last_balance,
       count(1)  real_fee,
       SUM(NVL(PRESENT_FEE, 0))  present_fee,
       NULL  total_fee,
       NULL  late_fee,
       NULL start_date,
       NULL end_date,
       NULL cheque_no,
       NULL print_mode,
       NULL print_time,
       NULL print_staff_id,
       NULL print_depart_id,
       NULL print_city_code,
       NULL print_eparchy_code,
       NULL reprint_flag,
       NULL print_reason,
       '0' cancel_tag,
       NULL cancel_staff_id,
       NULL cancel_depart_id,
       NULL cancel_city_code,
       NULL cancel_eparchy_code,
       NULL cancel_reason,
       NULL cancel_time,
       NULL post_tag,
       NULL rsrv_fee1,
       NULL rsrv_fee2,
       NULL rsrv_info1,
       NULL rsrv_info2
  FROM TF_A_NOTEPRINTLOG
 WHERE print_staff_id = :PRINT_STAFF_ID
   and print_time >= trunc(sysdate)
   and partition_id = to_number(to_char(sysdate, 'mm'))
   AND CANCEL_TAG = '0'
 GROUP BY templet_CODE