SELECT T.RID,
    T.CTRM_PRODUCT_ID,
    T.CTRM_PRODUCT_TYPE,
    T.CONTRACT_ID,
    T.PRODUCT_ID,
    T.PACKAGE_ID,
    T.ELEMENT_ID,
    T.ELEMENT_TYPE_CODE,
    T.ITEM_INDEX,
    to_char(T.START_DATE, 'YYYY-MM-DD HH24MISS') START_DATE,
    to_char(T.END_DATE, 'YYYY-MM-DD HH24MISS') END_DATE,
    T.EPARCHY_CODE,
    to_char(T.UPDATE_TIME, 'yyyy-mm-dd hh24miss') UPDATE_TIME,
    T.UPDATE_STAFF_ID,
    T.UPDATE_DEPART_ID,
    T.REMARK,
    RSRV_STR1,
    RSRV_STR2,
    RSRV_STR3,
    RSRV_STR4,
    RSRV_STR5,
    T.CHECK_ELEMENT_TYPE,
    T.CHECK_ELEMENT_ID,    
    T.RSRV_TAG1,
    T.RSRV_TAG2,
    T.RSRV_TAG3
FROM TD_B_CTRM_RELATION T
WHERE 1=1
    AND (T.PRODUCT_ID=:PRODUCT_ID OR T.PRODUCT_ID= -1)
    AND (T.PACKAGE_ID=:PACKAGE_ID OR T.PACKAGE_ID= -1)
    AND T.ELEMENT_ID=:ELEMENT_ID
    AND T.ELEMENT_TYPE_CODE=:ELEMENT_TYPE_CODE
    AND (T.EPARCHY_CODE=:EPARCHY_CODE OR T.EPARCHY_CODE = 'ZZZZ')
    AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
