SELECT TASK_ID,
       APPLYID,
       TASKTYPE,
       SEARCHNUMBER,
       TO_CHAR(STARTTIME, 'yyyy-mm-dd hh24:mi:ss') STARTTIME,
	    DECODE(ENDTIME,
              '',
              '',
              TO_CHAR(ENDTIME, 'yyyy-mm-dd') || ' 23:59:59') ENDTIME,
       LETTERNUM,
       TABLE_NAME,
       FILE_NAME,
       STATEUPDATETIME1,
       PROCESS_TAG,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REASON
FROM TL_O_INSPECTIONLOG
WHERE 1 = 1
AND (  TASKTYPE = :TASKTYPE  OR :TASKTYPE IS NULL)
AND (  PROCESS_TAG = :PROCESS_TAG OR :PROCESS_TAG IS NULL )
AND (  TASK_ID = :TASK_ID OR :TASK_ID IS NULL )
AND (  APPLYID = :APPLYID OR :APPLYID IS NULL )
AND (  LETTERNUM = :LETTERNUM OR :LETTERNUM IS NULL )