SELECT  PARTITION_ID
       ,USER_ID
       ,DISCNT_CODE     
       ,START_DATE
       ,END_DATE
FROM  TF_F_USER_DISCNT
	WHERE 
			DISCNT_CODE = :DISCNT_CODE
			AND USER_ID = TO_NUMBER(:USER_ID)
			AND PARTITION_ID = MOD(:USER_ID, 10000)
			AND SYSDATE BETWEEN START_DATE AND END_DATE
