UPDATE TL_B_HARASSPHONE A
   SET A.PROCESS_TAG     = :PROCESS_TAG,
       A.REMARK          = :REMARK,
       A.AUDIT_STAFF_ID  = :AUDIT_STAFF_ID,
       A.AUDIT_DEPART_ID = :AUDIT_DEPART_ID,
       A.AUDIT_TIME      = SYSDATE
 WHERE A.INTF_ID = :INTF_ID
   AND A.PROCESS_TAG = 'A'
