UPDATE TI_B_RELATION_UU t SET t.modify_tag = '2'
        WHERE EXISTS (SELECT 1 FROM (SELECT trade_id ,PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                               FROM TI_B_RELATION_UU
                               WHERE sync_sequence = to_number(:SYNC_SEQUENCE)
                               AND MODIFY_TAG='9'
                             MINUS
                             SELECT trade_id ,PARTITION_ID,USER_ID_A,SERIAL_NUMBER_A,USER_ID_B,SERIAL_NUMBER_B,RELATION_TYPE_CODE,ROLE_TYPE_CODE,ROLE_CODE_A,ROLE_CODE_B,ORDERNO,SHORT_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
                               FROM TF_B_TRADE_RELATION_UU_BAK
                               WHERE TRADE_ID=:TRADE_ID
                               AND accept_month=:ACCEPT_MONTH ) b
                      WHERE t.user_id_b = b.user_id_b
                      AND t.user_id_a = b.user_id_a
                      AND t.relation_type_code = b.relation_type_code
                      AND t.start_date = b.start_date )
       AND sync_sequence = to_number(:SYNC_SEQUENCE)
       AND modify_tag = '9'