UPDATE TF_F_LTEB_USER_STATE 
   SET RSRV_STR1        = :RSRV_STR1,
       END_DATE         = SYSDATE,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE LTEB_USER_ID = :LTEB_USER_ID
