UPDATE TF_F_USER_NETNP
   SET STATE           = :STATE,
     PORT_OUT_DATE= to_date(:PORT_OUT_DATE, 'YYYY-MM-DD HH24:MI:SS'),
     NETNP_STAFF_ID=:NETNP_STAFF_ID,
     NETNP_DEPART_ID=:NETNP_DEPART_ID
 WHERE SERIAL_NUMBER = :SERIAL_NUMBER
     AND STATE = '0'
   AND SYSDATE+0 < PORT_OUT_DATE