--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型, ACCEPT_DATE 受理月份, TRADE_ID 台账标识
FROM (SELECT D.DEPART_KIND_CODE,
          TO_CHAR(B.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
          B.TRADE_ID
     FROM ucr_crm1.TF_B_TRADE_SVC A, ucr_crm1.TF_BH_TRADE B, TD_M_DEPART D
    WHERE B.USER_ID =:USER_ID
      AND B.TRADE_TYPE_CODE in (613,600)
      AND B.CANCEL_TAG = '0'
      AND A.TRADE_ID = B.TRADE_ID
      AND TRUNC(B.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
      AND A.MODIFY_TAG = '0'
      AND B.TRADE_DEPART_ID = D.DEPART_ID
      AND A.SERVICE_ID IN (20150060,20150160)
      AND ROWNUM < 2
   UNION
   SELECT D.DEPART_KIND_CODE,
          TO_CHAR(B.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
          B.TRADE_ID
     FROM ucr_crm1.TF_B_TRADE_SVC A, ucr_crm1.TF_B_TRADE B, TD_M_DEPART D
    WHERE B.USER_ID = TO_NUMBER(:USER_ID)
      AND B.TRADE_TYPE_CODE in (613,600)
      AND B.CANCEL_TAG = '0'
      AND A.TRADE_ID = B.TRADE_ID
      AND TRUNC(B.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
      AND A.MODIFY_TAG = '0'
      AND B.TRADE_DEPART_ID = D.DEPART_ID
      AND A.SERVICE_ID IN (20150060,20150160)
      AND ROWNUM < 2
      UNION
     SELECT E.DEPART_KIND_CODE,
           TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
           A.RELATION_TRADE_ID TRADE_ID
      FROM TF_F_USER_SALE_ACTIVE A, TD_M_DEPART E
     WHERE A.UPDATE_DEPART_ID = E.DEPART_ID
       AND A.USER_ID = TO_NUMBER(:USER_ID)
       AND A.PRODUCT_ID IN (66000602)
       AND A.PROCESS_TAG = '0'
       AND A.END_DATE > SYSDATE
       AND (TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE) OR (A.ACCEPT_DATE <= TO_DATE('2017-12-24', 'yyyy-mm-dd')))
       AND ROWNUM < 2) TRADE
WHERE ROWNUM < 2