 UPDATE TF_F_WIDENET_SYNC
  SET UPDATE_TIME= SYSDATE, RSRV_NUM1 = :RSRV_NUM1, RSRV_STR1 = :RSRV_STR1, RSRV_STR2 = :RSRV_STR2, RSRV_NUM2 = :RSRV_NUM2
 WHERE 1 = 1
  AND SERIAL_NUMBER = :SERIAL_NUMBER
  AND WIDENET_SYNC_ID = :WIDENET_SYNC_ID