UPDATE TF_B_TERMINAL_AUTHORIZE_LOG
SET  OPR_CODE =:OPR_CODE, OPR_DATE =SYSDATE, 
	UPDATE_TIME =SYSDATE, UPDATE_STAFF_ID =:UPDATE_STAFF_ID, UPDATE_DEPART_ID =:UPDATE_DEPART_ID,
    OPER_TRADE_ID = :OPER_TRADE_ID
WHERE 1 = 1 
    AND TERMINAL_ID=:TERMINAL_ID