select t.*  from TF_F_USER T,TF_F_CUSTOMER T1,TL_B_STOPUSER T2
where T.CUST_ID=T1.CUST_ID
AND T.SERIAL_NUMBER=T2.SERIAL_NUMBER
AND T.USER_STATE_CODESET='5'
AND T.REMOVE_TAG='0'
AND (T1.IS_REAL_NAME='0' OR T1.IS_REAL_NAME IS NULL)
AND T2.DEAL_STATUS not in ('0','5')
AND T.PARTITION_ID=MOD(:USER_ID,10000)
AND T.USER_ID=:USER_ID