SELECT B.PAY_MODE_CODE PAY_MODE_CODE,B.PAY_NAME PAY_NAME,B.BANK_CODE BANK_CODE,B.BANK_ACCT_NO BANK_ACCT_NO
FROM  TF_F_ACCOUNT B
WHERE  B.CUST_ID= :CUST_ID
AND B.PAY_MODE_CODE = :PAY_MODE_CODE
GROUP BY B.CUST_ID,B.PAY_NAME, B.PAY_MODE_CODE,B.BANK_CODE,B.BANK_ACCT_NO