--IS_CACHE=Y
SELECT
  CONTENT_CODE,
  PARAM_ID,
  TMPL_ID,
  CONTENT_NUM,
  PARAM_TYPE,
  PARAM_ORDER,
  PARAM_DESC,
  ELEMENT_NAME,
  REMARK,
  STAFF_ID,
  OPER_DATE
FROM
  TD_S_CONTENT_PARAM 
WHERE 1=1
  AND TMPL_ID = :TMPL_ID
  AND PARAM_ID = :PARAM_ID
  AND PARAM_TYPE = :PARAM_TYPE