--IS_CHACHE=Y
SELECT COUNT(1) 业务数
  FROM TF_F_USER_SALE_ACTIVE A
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PRODUCT_ID IN (69900930, 69900931)
   AND A.END_DATE > SYSDATE