--IS_CACHE=Y
SELECT SUBSYS_CODE, PARAM_ATTR, PARAM_CODE, PARAM_NAME, PARA_CODE1, PARA_CODE2, PARA_CODE23, PARA_CODE24, PARA_CODE25,
			 START_DATE, END_DATE, EPARCHY_CODE, REMARK, UPDATE_STAFF_ID, UPDATE_DEPART_ID,
			 TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME
FROM TD_S_COMMPARA
WHERE SUBSYS_CODE = :SUBSYS_CODE AND PARAM_ATTR = TO_NUMBER(:PARAM_ATTR) AND PARAM_CODE = :PARAM_CODE AND SYSDATE BETWEEN START_DATE AND END_DATE