SELECT DISTINCT SERIAL_NUMBER_B
  FROM TF_F_RELATION_XXT
 WHERE PARTITION_ID = MOD(TO_NUMBER(:EC_USER_ID), 10000)
   AND SERIAL_NUMBER_A = :SERIAL_NUMBER_A
   AND EC_USER_ID = :EC_USER_ID
   AND ELEMENT_TYPE_CODE='D'
   AND SYSDATE BETWEEN START_DATE AND END_DATE

