SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, :TRADE_ID TRADE_ID,
                        MOD(A.USER_ID, 10000) PARTITION_ID, A.USER_ID, A.USER_TYPE_CODE,
                        A.MONITOR_TYPE, A.SERIAL_NUMBER, A.EPARCHY_CODE,
                        A.STATUS, A.START_DATE, A.END_DATE, A.UPDATE_TIME,
                        A.UPDATE_STAFF_ID, A.UPDATE_DEPART_ID, A.REMARK,
                        A.RSRV_NUM1, A.RSRV_NUM2, A.RSRV_NUM3, A.RSRV_NUM4,
                        A.RSRV_NUM5, A.RSRV_STR1, A.RSRV_STR2, A.RSRV_STR3,
                        A.RSRV_STR4, A.RSRV_STR5, A.RSRV_DATE1, A.RSRV_DATE2,
                        A.RSRV_DATE3, A.RSRV_TAG1, A.RSRV_TAG2, A.RSRV_TAG3,
                        A.RSRV_STR1, A.INST_ID, A.BIZ_TYPE, A.MONITOR_FLAG,
                        A.MONITOR_RULE_CODE
          FROM TF_F_USER_OCS A
         WHERE A.USER_ID = :USER_ID
           AND A.PARTITION_ID = MOD(:USER_ID, 10000)