SELECT TO_CHAR(P.TRADE_ID) TRADE_ID,
       P.ACCEPT_MONTH,
       TO_CHAR(P.USER_ID) USER_ID,
       to_char(P.INST_ID) INST_ID,
       P.SERVICE_ID,
       P.SERV_CODE,
       P.SERIAL_NUMBER,
       P.GROUP_ID,
       P.BIZ_TYPE_CODE,
       P.BIZ_CODE,
       BIZ_ATTR,
       P.BIZ_NAME,
       P.BIZ_IN_CODE,
       P.BIZ_STATUS,
       P.BIZ_STATE_CODE,
       P.BIZ_PRI,
       P.AUTH_CODE,
       P.USAGE_DESC,
       P.INTRO_URL,
       P.BILLING_TYPE,
       P.BILLING_MODE,
       P.PRICE,
       P.PRE_CHARGE,
       P.CS_TEL,
       P.CS_URL,
       P.ACCESS_MODE,
       P.ACCESS_NUMBER,
       P.SI_BASE_IN_CODE,
       P.SI_BASE_IN_CODE_A,
       P.EC_BASE_IN_CODE,
       P.EC_BASE_IN_CODE_A,
       TO_CHAR(P.MAX_ITEM_PRE_DAY) MAX_ITEM_PRE_DAY,
       TO_CHAR(P.MAX_ITEM_PRE_MON) MAX_ITEM_PRE_MON,
       TO_CHAR(P.DELIVER_NUM) DELIVER_NUM,
       P.FORBID_START_TIME_A,
       P.FORBID_END_TIME_A,
       P.FORBID_START_TIME_B,
       P.FORBID_END_TIME_B,
       P.FORBID_START_TIME_C,
       P.FORBID_END_TIME_C,
       P.FORBID_START_TIME_D,
       P.FORBID_END_TIME_D,
       P.IS_TEXT_ECGN,
       P.DEFAULT_ECGN_LANG,
       P.TEXT_ECGN_EN,
       P.TEXT_ECGN_ZH,
       TO_CHAR(P.OPR_EFF_TIME, 'yyyy-mm-dd hh24:mi:ss') OPR_EFF_TIME,
       P.OPR_SEQ_ID,
       P.OPER_STATE,
       P.ADMIN_NUM,
       P.MAS_ID,
       TO_CHAR(P.FIRST_DATE, 'yyyy-mm-dd hh24:mi:ss') FIRST_DATE,
       P.PLAT_SYNC_STATE,
       TO_CHAR(P.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(P.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       P.MODIFY_TAG,
       P.UPDATE_DEPART_ID,
       P.UPDATE_STAFF_ID,
       TO_CHAR(P.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       P.REMARK,
       P.RSRV_NUM1,
       P.RSRV_NUM2,
       P.RSRV_NUM3,
       TO_CHAR(P.RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(P.RSRV_NUM5) RSRV_NUM5,
       P.RSRV_STR1,
       P.RSRV_STR2,
       P.RSRV_STR3,
       P.RSRV_STR4,
       P.RSRV_STR5,
       TO_CHAR(P.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(P.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(P.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       P.RSRV_TAG1,
       P.RSRV_TAG2,
       P.RSRV_TAG3
  FROM TF_B_TRADE_GRP_PLATSVC P, TF_B_TRADE B
 WHERE P.TRADE_ID = :TRADE_ID
   AND P.TRADE_ID = B.TRADE_ID
   AND B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(P.TRADE_ID, 5, 2))