  SELECT T.PARTITION_ID,T.USER_ID,T.ORDER_ID,T.SUB_ORDER_ID,T.SERIAL_NUMBER,T.DISCNT_CODE,T.GOODS_ID,T.DISCNT_NAME,TO_CHAR(T.INSERT_TIME,'YYYY-MM-DD HH24:MI:SS') INSERT_TIME,
  T.DEAL_STATE,TO_CHAR(T.DEAL_DATE,'YYYY-MM-DD HH24:MI:SS') DEAL_DATE,T.RESULT_INFO,T.REMARK  FROM TF_F_USER_RIGHTS_INTERESTS T 
    WHERE T.ORDER_ID=:ORDER_ID AND T.SUB_ORDER_ID=:SUB_ORDER_ID
