INSERT INTO TI_B_ACCOUNT_CONSIGN
          (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, ACCT_ID,
           INST_ID, PAY_MODE_CODE, EPARCHY_CODE, CITY_CODE, SUPER_BANK_CODE,
           BANK_CODE, BANK_ACCT_NO, BANK_ACCT_NAME, CONTRACT_ID, CONTRACT_NAME,
           CONTACT, CONTACT_PHONE, POST_ADDRESS, POST_CODE, CONSIGN_MODE,
           PRIORITY, PAYMENT_ID, PAY_FEE_MODE_CODE, ASSISTANT_TAG,
           ACCT_BALANCE_ID, ACT_TAG, START_CYCLE_ID, END_CYCLE_ID)
          SELECT DISTINCT :SYNC_SEQUENCE, :SYNC_DAY, '8', :TRADE_ID,
                          MOD(B.ACCT_ID, 10000), B.ACCT_ID,
                          :INST_ID, '0',
                          NULL, NULL, -1, -1, -1, '0', NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, -1, '0', NULL, NULL, '1',
                          TO_CHAR(SYSDATE, 'YYYYMM'),
                          TO_CHAR(SYSDATE - 0.1, 'YYYYMM')
            FROM TF_B_TRADE_ACCT_CONSIGN B
           WHERE B.TRADE_ID = :TRADE_ID
             AND B.ACCEPT_MONTH = :ACCEPT_MONTH