
	SELECT POID_CODE,POID_LABLE,MEM_LABLE,role_code_b FROM  TF_B_FAMILY_OTHER
			WHERE 1=1
			AND FINISH_TAG='1'
			AND CUSTOMER_PHONE=:CUSTOMER_PHONE
			AND PRODUCT_OFFERING_ID=:PRODUCT_OFFERING_ID
			ORDER BY ADD_TIME desc