--IS_CACHE=Y
SELECT A.NODE_CODE,A.NODE_NAME,A.NODE_TYPE,A.PARENT_NODE_CODE,A.NODE_LEVEL,(B.NODE_NAME)PARENT_NODE_NAME
FROM TD_S_CONTENT_CATEGORY A,TD_S_CONTENT_CATEGORY B
WHERE A.PARENT_NODE_CODE = B.NODE_CODE
 AND A.NODE_CODE=:NODE_CODE
 AND A.NODE_NAME=:NODE_NAME
 AND A.NODE_TYPE=:NODE_TYPE
 AND A.PARENT_NODE_CODE=:PARENT_NODE_CODE
 AND A.NODE_LEVEL=:NODE_LEVEL