INSERT INTO TF_B_IDENTCARD_MANAGE(IDENT_CODE, USER_ID, CUST_ID, USER_TYPE,
				IDENT_CODE_LEVEL, IDENT_CODE_TYPE, HOME_PROVINCE,START_DATE,END_DATE,SERIAL_NUMBER,RSRV_STR1) values(:IDENT_CODE,:USER_ID,
				:CUST_ID,:USER_TYPE,:IDENT_CODE_LEVEL,:IDENT_CODE_TYPE,:HOME_PROVINCE,sysdate,sysdate+to_number(:EFFECTIVE_TIME)/24/60/60,:SERIAL_NUMBER,:BUSINESS_CODE)