SELECT A.ATTR_CODE,A.ATTR_VALUE 
FROM TF_F_USER_PLATSVC T, TF_F_USER_ATTR  A
WHERE T.USER_ID = :USER_ID
AND A.USER_ID = T.USER_ID
AND T.PARTITION_ID = MOD(:USER_ID, 10000)
AND A.PARTITION_ID = MOD(:USER_ID, 10000)
AND T.SERVICE_ID = :SERVICE_ID
AND A.RELA_INST_ID = T.INST_ID
AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE