SELECT CONTRACT_ID,
       CONTRACT_CODE,
       MATERIAL_CODE,
       CUSTOMER_BRAND,
       CONTRACT_TYPE,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       TO_CHAR(RSRV_DATE1, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE3,
       CONTRACT_STATUS,
       EPARCHY_CODE
  FROM TD_B_CONTRACT T
 WHERE T.MATERIAL_CODE IN
       (SELECT S.MATERIAL_CODE
          FROM TI_B_CONTRACT_MEASURE S
         WHERE S.DEVICE_MODE_CODE = :DEVICE_MODE_CODE)
   AND T.CONTRACT_STATUS = '2'
   AND T.CONTRACT_TYPE = :CONTRACT_TYPE
   AND ( T.EPARCHY_CODE = :EPARCHY_CODE OR T.EPARCHY_CODE ='ZZZZ')