UPDATE TF_F_LTEB_USER 
   SET REMOVE_TAG       = :REMOVE_TAG,
       DESTROY_TIME     = SYSDATE,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE LTEB_USER_ID = :LTEB_USER_ID