SELECT A.CLASS_ID, A.CUST_ID, A.CUST_NAME,
       B.MEMBER_KIND,
       (SELECT C.CUST_MANAGER_NAME
          FROM TF_F_CUST_MANAGER_STAFF C
         WHERE A.CUST_MANAGER_ID = C.CUST_MANAGER_ID) CUST_MANAGER_NAME,
       (SELECT C.SERIAL_NUMBER
          FROM TF_F_CUST_MANAGER_STAFF C
         WHERE A.CUST_MANAGER_ID = C.CUST_MANAGER_ID) CUST_MANAGER_SN
  FROM TF_F_CUST_GROUP A, TF_F_CUST_GROUPMEMBER B
 WHERE A.GROUP_ID = B.GROUP_ID
   AND A.REMOVE_TAG = '0'
   AND B.REMOVE_TAG = '0'
   AND B.USER_ID = :USER_ID