SELECT MSISDN,
       PORT_OUT_NETID,
       PORT_IN_NETID,
       HOME_NETID,
       TO_CHAR(BEGIN_TIME, 'YYYY-MM-DD HH24:MI:SS') BEGIN_TIME,
       TO_CHAR(END_TIME, 'YYYY-MM-DD HH24:MI:SS') END_TIME
  FROM TF_F_USER_NP_ALL
 WHERE MSISDN = :SERIAL_NUMBER
 ORDER BY END_TIME DESC