UPDATE TI_O_TRADE_SMS T
   SET T.RSRV_TAG1   = '1',
       T.RSRV_STR5   = SUBSTR(:REVERT_SMS_CONTENT,1,190),
       T.RSRV_DATE1  = SYSDATE
 WHERE T.SERIAL_NUMBER = :SERIAL_NUMBER
   AND T.SOURCE_NUMBER = :REPLY_NUMBER
   AND T.ACCEPT_DATE >= TRUNC(SYSDATE - :DAYS)
   AND MONTHID IN (TO_NUMBER(TO_CHAR(SYSDATE, 'mm')), TO_NUMBER(TO_CHAR(SYSDATE - :DAYS, 'mm')))