UPDATE TF_F_FAMILY_REMIND A
   SET A.RELATION_TRADE_ID = :TRADE_ID,
       A.END_DATE          = SYSDATE,
       A.BACK_TIME         = SYSDATE,
       A.UPDATE_TIME       = SYSDATE,
       A.UPDATE_STAFF_ID   = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID  = :UPDATE_DEPART_ID,
       A.REMARK            = '已回复办理亲亲网'
 WHERE A.SERIAL_NUMBER_A = :SERIAL_NUMBER_A
   AND A.END_DATE > SYSDATE
   AND A.SERIAL_NUMBER_B = :SERIAL_NUMBER_B