SELECT A.DISCNT_CODE,C.PARA_CODE1 DISCNT_NAME,TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_F_SHIP_INFO A, TD_S_COMMPARA C
 WHERE TO_CHAR(A.DISCNT_CODE)=C.PARAM_CODE
   AND A.USER_ID = :USER_ID   
   AND A.END_DATE>SYSDATE