--IS_CACHE=Y 
SELECT *
  FROM TD_B_TRADEACTION T
 WHERE T.STATE = '1'
   AND (T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE OR T.TRADE_TYPE_CODE='-1')
   AND T.Act_Type = 'calElementDate'
 ORDER BY T. ORDER_NO ASC