SELECT r.TID,
       r.OID,
       r.OUT_OID,
       r.GOODS_ID,
       r.TITLE,
       r.NUM,
       r.PRICE,
       r.PROVINCE,
       r.CITY,
       r.TOTAL,
       r.ADJEST_FEE,
       r.ADJEST_REASON,
       r.MOBILE_NO,
       r.PHONE,
       r.USER_NAME,
       r.CERTIFICATE_TYPE,
       r.CERTIFICATE_NO,
       r.ORDER_STATUS,
       r.ACCEPT_DATE,
       r.ACCEPT_RESULT,
       r.ERROR_RESULT,
       r.RSP_TIME,
       r.UPDATE_TIME,
       r.UPDATE_STAFF_ID,
       r.UPDATE_DEPART_ID,
       r.REMARK,
       r.RSRV_STR1,
       r.RSRV_STR2,
       r.RSRV_STR3,
       r.RSRV_STR4,
       r.RSRV_STR5
  FROM TF_B_CTRM_ORDER r
 WHERE r.tid = :TID
