SELECT T.*,
DECODE(T.SUPPLIER_TYPE_ID,'M','供应商','手机卖场') SUPPLIER_TYPE_ID_TRAN
FROM  RES_SUPPLIER T  
WHERE 1=1 
AND T.SUPPLIER_TYPE_ID=:SUPPLIER_TYPE_ID    
AND T.SUPPLIER_NAME LIKE  '%'||:SUPPLIER_NAME||'%'
AND T.STATE=:STATE
ORDER BY T.SUPPLIER_NAME