SELECT T.SERIAL_NUMBER ,T.SMS_CONTENT,T.SMS_TYPE,TO_NUMBER(T.SMS_ID) SMS_ID
    FROM TF_B_USER_SMSSEND T
    WHERE T.USER_ID = TO_NUMBER(:USER_ID)
    AND T.TRADE_ID = TO_NUMBER(:TRADE_ID)
    AND T.SMS_TYPE IN ('01','03','05')