SELECT T.SERIAL_NUMBER ,TO_NUMBER(T.SMS_ID) SMS_ID,T.SMS_TYPE,
		T.SMS_CONTENT
FROM TF_B_USER_SMSSEND T
WHERE T.USER_ID = TO_NUMBER(:USER_ID)
AND T.TRADE_ID = TO_NUMBER(:TRADE_ID)
AND T.SMS_TYPE IN ( '02','04')