INSERT INTO TI_B_CONTRACT_PROMOTION
	( OPR_NUMB ,                  
   VERIFY_TIME,
   ORDER_CODE,               
   CONTRACT_TYPE,                    
   CONTRACT_START_DATE,                           
   COMPANY_CODE,                     
   SHOP_CODE,                  
   SALES_PERSON_ID,
   SERIAL_NUMBER,
   MATERIAL_CODE,                  
   IMEI ,                   
   COMPENSATE_FEE,                      
   DEPOSIT_FEE,
   CONTRACT_ID,                  
   GRADE_LOW_LIMIT,                     
   PROMISE_DURATION,                      
   RESOURCE_CODE,
   TRADE_ID,                       
   IS_VERIFY_SUCCESS,
   RSRV_DATE1,
   RSRV_DATE2,
   STATUS ,
   RSRV_TAG2 ,
   REMARK,
   RSRT_TAG1,
   RSRT_TAG2,
   RSRT_STR1,
   RSRT_STR2,
   RSRT_STR3,
   RSRT_STR4,
   RSRT_STR6,
   RSRT_STR7,
   ORDER_TYPE_CODE,
   RSRT_STR5)
VALUES
	( :OPR_NUMB ,                  
   TO_DATE(:VERIFY_TIME, 'YYYY-MM-DD HH24:MI:SS'),
   :ORDER_CODE,               
   :CONTRACT_TYPE,                    
   TO_DATE(:CONTRACT_START_DATE, 'YYYY-MM-DD HH24:MI:SS') ,                           
   :COMPANY_CODE,                     
   :SHOP_CODE,                  
   :SALES_PERSON_ID,
   :SERIAL_NUMBER,
   :MATERIAL_CODE,                  
   :IMEI,                   
   to_number(:COMPENSATE_FEE),                      
   to_number(:DEPOSIT_FEE),
   :CONTRACT_ID,                  
   to_number(:GRADE_LOW_LIMIT),                     
    to_number(:PROMISE_DURATION),                      
   :RESOURCE_CODE,
  to_number( :TRADE_ID),                       
   :IS_VERIFY_SUCCESS,
   TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
   :STATUS ,
   :RSRV_TAG2 ,
   :REMARK,
   :RSRT_TAG1,
   :RSRT_TAG2,
   :RSRT_STR1,
   :RSRT_STR2,
   :RSRT_STR3,
   :RSRT_STR4,
   :RSRT_STR6,
   :RSRT_STR7,
   :ORDER_TYPE_CODE,
   :RSRT_STR5)