SELECT T.BUSIFORM_ID,
       T.BI_SN,
       T.ACCEPT_MONTH,
       T.BPM_TEMPLET_ID,
       T.TEMPLET_TYPE,
       T.BUSIFORM_OPER_TYPE,
       T.IN_MODE_CODE,
       T.BUSI_TYPE,
       T.BUSI_CODE,
       T.REMARK,
       T.STATE,
       T.EPARCHY_CODE,
       T.CITY_CODE,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE,
       C.GROUP_ID,
       C.CUST_NAME,
       P.USER_ID USER_ID_A
  FROM TF_B_EWE T,TF_B_EOP_SUBSCRIBE C,TF_B_EOP_PRODUCT P
  WHERE T.BPM_TEMPLET_ID = :BPM_TEMPLET_ID
  AND T.BI_SN = :IBSYSID
  AND C.IBSYSID = T.BI_SN
  AND P.IBSYSID = T.BI_SN
  UNION
  
  SELECT T.BUSIFORM_ID,
       T.BI_SN,
       T.ACCEPT_MONTH,
       T.BPM_TEMPLET_ID,
       T.TEMPLET_TYPE,
       T.BUSIFORM_OPER_TYPE,
       T.IN_MODE_CODE,
       T.BUSI_TYPE,
       T.BUSI_CODE,
       T.REMARK,
       T.STATE,
       T.EPARCHY_CODE,
       T.CITY_CODE,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE,
       C.GROUP_ID,
       C.CUST_NAME,
       P.USER_ID USER_ID_A
  FROM TF_BH_EWE T,TF_BH_EOP_SUBSCRIBE C,TF_BH_EOP_PRODUCT P
  WHERE T.BPM_TEMPLET_ID = :BPM_TEMPLET_ID
  AND T.BI_SN = :IBSYSID
  AND C.IBSYSID = T.BI_SN
  AND P.IBSYSID = T.BI_SN