SELECT R.BUSIFORM_NODE_ID,
       R.ACCEPT_MONTH,
       R.SUB_BUSIFORM_ID,
       R.BUSIFORM_ID,
       R.RELE_CODE,
       R.RELE_VALUE,
       R.REMARK,
       R.VALID_TAG,
       R.EPARCHY_CODE,
       R.CREATE_DATE,
       E.BUSI_CODE,
       E.BPM_TEMPLET_ID,
       E.ACCEPT_STAFF_ID  
  FROM TF_B_EWE E, TF_B_EWE_RELE R
 WHERE E.BUSIFORM_ID = R.SUB_BUSIFORM_ID
   AND E.BI_SN = :IBSYSID
   AND R.RELE_VALUE = :RECORD_NUM
   AND R.RELE_CODE='RECORD_NUM'