SELECT T.BUSIFORM_ID,
       T.BI_SN,
       T.ACCEPT_MONTH,
       T.BPM_TEMPLET_ID,
       T.TEMPLET_TYPE,
       T.BUSIFORM_OPER_TYPE,
       T.IN_MODE_CODE,
       T.BUSI_TYPE,
       T.BUSI_CODE,
       T.REMARK,
       T.STATE,
       T.EPARCHY_CODE,
       T.CITY_CODE,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TF_B_EWE T
 WHERE T.BI_SN = :BI_SN
   AND T.TEMPLET_TYPE = :TEMPLET_TYPE