SELECT BUSIFORM_NODE_ID,
       ACCEPT_MONTH,
       BUSIFORM_ID,
       PRE_BUSIFORM_NODE_ID,
       NODE_ID,
       PRE_NODE_ID,
       SUB_BI_SN,
       STATE,
       DEAL_EOS_ROLE_ID,
       DEAL_STAFF_ID,
       DEAL_EPARCHY_CODE,
       EPARCHY_CODE,
       DEAL_DEPART_ID,
       FLOW_EXPECT_TIME,
       ACCEPT_DEPART_ID,
       UPDATE_DEPART_ID,
       UPDATE_STAFF_ID,
       ACCEPT_STAFF_ID,
       TO_CHAR(T.FLOW_EXPECT_TIME, 'YYYY-MM-DD HH24:MI:SS') FLOW_EXPECT_TIME,
       TO_CHAR(T.FLOW_REAL_TIME, 'YYYY-MM-DD HH24:MI:SS') FLOW_REAL_TIME,
       TO_CHAR(T.AUTO_TIME, 'YYYY-MM-DD HH24:MI:SS') AUTO_TIME,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
FROM TF_B_EWE_NODE
WHERE DEAL_STAFF_ID IS NOT NULL
AND STATE = '0'
AND DEAL_STAFF_ID = :STAFF_ID
