UPDATE TF_B_EWE_NODE SET DEAL_EOS_ROLE_ID = :DEAL_EOS_ROLE_ID, DEAL_STAFF_ID = :DEAL_STAFF_ID, DEAL_EPARCHY_CODE = :DEAL_EPARCHY_CODE, DEAL_DEPART_ID = :DEAL_DEPART_ID
WHERE BUSIFORM_NODE_ID = :BUSIFORM_NODE_ID
