SELECT CUSTOMER_PHONE,MEM_NUMBER,PRODUCT_OFFERING_ID,ACTION,PRODUCT_CODE FROM TF_B_FAMILY_LOG
WHERE 1=1
AND MEM_TYPE=:MEM_TYPE 
AND CUSTOMER_PHONE=:CUSTOMER_PHONE
AND MEM_NUMBER=:MEM_NUMBER
AND ACTION=:ACTION
AND PRODUCT_OFFERING_ID=:PRODUCT_OFFERING_ID
AND RSRV_STR3='0'