SELECT MSISDN,
       SRC_NETID,
       DES_NETID,
       OWN_NETID,
       BEGIN_TIME,
       END_TIME,
       UPDATE_TIME,
       DECODE(LENGTH(OWN_NETID), 6, '00' || OWN_NETID, OWN_NETID) AS_OWN_NETID
  FROM TD_NP
 WHERE MSISDN = :MSISDN
   AND SYSDATE BETWEEN to_date(BEGIN_TIME,'yyyy-MM-dd hh24:miss') AND to_date(END_TIME,'yyyy-MM-dd hh24:miss')
 ORDER BY BEGIN_TIME DESC
