SELECT PLAT_CODE,TO_DATE(ACCEPT_TIME,'YYYY-MM-DD HH24:MI:SS') ACCEPT_TIME,SERIAL_NUMBER,
       USER_ID,RECV_OBJECT,TO_DATE(EXPIRE_TIME,'YYYY-MM-DD HH24:MI:SS') EXPIRE_TIME,
       TO_DATE(REPLY_TIME,'YYYY-MM-DD HH24:MI:SS') REPLY_TIME,REPLY_STATUS,SMS_CONTENT,REPLY_CONTENT
  FROM TL_B_PLAT_TRADE T 
  WHERE (RECV_OBJECT = :RECV_OBJECT OR :RECV_OBJECT IS NULL OR :RECV_OBJECT='')
        AND SERIAL_NUMBER=:SERIAL_NUMBER
        AND TO_DATE(ACCEPT_TIME,'YYYY-MM-DD HH24:MI:SS')>=TO_DATE(:ACCEPT_TIME,'YYYY-MM-DD HH24:MI:SS')
        AND PLAT_CODE=:PLAT_CODE
        AND REPLY_STATUS = '1'