--IS_CACHE=Y
SELECT EPARCHY_CODE,
       CARD_KIND_CODE,
       CARD_KIND_NAME,
       RES_TYPE_CODE,
       RES_KIND_CODE,
       CARD_KIND_P,
       VALUE_CODE,
       ACTIVE_ID,
       BRAND_CODE,
       PRODUCT_ID,
       ERP_CODE,
       UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_DATE1,
       RSRV_DATE2,
       VALID_TAG
  FROM TD_S_CARDKIND
 WHERE RES_TYPE_CODE = :RES_TYPE_CODE
   AND CARD_KIND_CODE = :CARD_KIND_CODE
   AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE = 'ZZZZ')