--IS_CACHE=Y
SELECT RULE_ID,BIZ_PRI,SERVICE_ID,BIZ_TYPE_CODE,ORG_DOMAIN,IN_MODE_CODE,OPER_CODE,ISFIRST_DATE,ISFIRST_DATE_MON,SEC_CONFIRM,SP_CONFIRM
       ,RSRV_TAG1,RSRV_STR1 FROM TD_B_PLATSVC_OPERRULE
       WHERE 1=1 
       AND SERVICE_ID=:SERVICE_ID
       AND BIZ_TYPE_CODE=:BIZ_TYPE_CODE
       AND ORG_DOMAIN =:ORG_DOMAIN
       AND IN_MODE_CODE=:IN_MODE_CODE
       AND OPER_CODE  =:OPER_CODE
       AND RULE_ID    =:RULE_ID