UPDATE TF_F_USER_OTHER T
 SET T.RSRV_STR1=:RES_NO,T.RSRV_STR6=:RES_KIND_CODE,T.UPDATE_STAFF_ID=:UPDATE_STAFF_ID,T.UPDATE_DEPART_ID=:UPDATE_DEPART_ID,T.RSRV_STR12=:TRADE_ID
 where T.RSRV_VALUE_CODE='FTTH'
 AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
 AND T.USER_ID = (select t1.USER_ID from TF_F_USER t1 where T1.SERIAL_NUMBER=:SERIAL_NUMBER AND T1.REMOVE_TAG='0')