SELECT T.PARTITION_ID,TO_CHAR(T.USER_ID) USER_ID,T.SERIAL_NUMBER,T.SERIAL_NUMBER_B,T.PRODUCT_MODE,T.PRODUCT_ID,T.PRODUCT_NAME,
T.PACKAGE_ID,T.PACKAGE_NAME,TO_CHAR(T.CAMPN_ID) CAMPN_ID,T.CAMPN_CODE,T.CAMPN_NAME,T.CAMPN_TYPE,
TO_CHAR(T.OPER_FEE) OPER_FEE,TO_CHAR(T.FOREGIFT) FOREGIFT,TO_CHAR(T.ADVANCE_PAY) ADVANCE_PAY,
TO_CHAR(T.SCORE_CHANGED) SCORE_CHANGED,TO_CHAR(T.CREDIT_VALUE) CREDIT_VALUE,T.MONTHS,T.END_MODE,
T.ACTOR_PSPT_ID,T.ACTOR_PSPT_TYPE_CODE,T.ACTOR_PHONE,T.ACTOR_NAME,T.APPR_STAFF_ID,TO_CHAR(T.APPR_TIME, 'YYYY-MM-DD HH24:MI:SS') APPR_TIME,
T.OUT_NET_PHONE,T.CONTRACT_ID,T.PROCESS_TAG,TO_CHAR(T.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
T.TRADE_STAFF_ID,TO_CHAR(T.RELATION_TRADE_ID) RELATION_TRADE_ID,TO_CHAR(T.CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS') CANCEL_DATE,
T.CANCEL_STAFF_ID,T.CANCEL_CAUSE,TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
TO_CHAR(T.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,T.UPDATE_STAFF_ID,T.UPDATE_DEPART_ID,T.REMARK,T.RSRV_NUM1,
T.RSRV_NUM2,T.RSRV_NUM3,TO_CHAR(T.RSRV_NUM4) RSRV_NUM4,TO_CHAR(T.RSRV_NUM5) RSRV_NUM5,T.RSRV_STR1,C.PARAM_NAME
  FROM TF_F_USER_SALE_ACTIVE T, TD_S_COMMPARA C
 WHERE C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '9088'
   AND C.PARAM_CODE = T.PRODUCT_ID
   AND T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.PROCESS_TAG = '0'
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
union all
SELECT T.PARTITION_ID,TO_CHAR(T.USER_ID) USER_ID,T.SERIAL_NUMBER,T.SERIAL_NUMBER_B,T.PRODUCT_MODE,T.PRODUCT_ID,T.PRODUCT_NAME,
T.PACKAGE_ID,T.PACKAGE_NAME,TO_CHAR(T.CAMPN_ID) CAMPN_ID,T.CAMPN_CODE,T.CAMPN_NAME,T.CAMPN_TYPE,
TO_CHAR(T.OPER_FEE) OPER_FEE,TO_CHAR(T.FOREGIFT) FOREGIFT,TO_CHAR(T.ADVANCE_PAY) ADVANCE_PAY,
TO_CHAR(T.SCORE_CHANGED) SCORE_CHANGED,TO_CHAR(T.CREDIT_VALUE) CREDIT_VALUE,T.MONTHS,T.END_MODE,
T.ACTOR_PSPT_ID,T.ACTOR_PSPT_TYPE_CODE,T.ACTOR_PHONE,T.ACTOR_NAME,T.APPR_STAFF_ID,TO_CHAR(T.APPR_TIME, 'YYYY-MM-DD HH24:MI:SS') APPR_TIME,
T.OUT_NET_PHONE,T.CONTRACT_ID,T.PROCESS_TAG,TO_CHAR(T.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
T.TRADE_STAFF_ID,TO_CHAR(T.RELATION_TRADE_ID) RELATION_TRADE_ID,TO_CHAR(T.CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS') CANCEL_DATE,
T.CANCEL_STAFF_ID,T.CANCEL_CAUSE,TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
TO_CHAR(T.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,T.UPDATE_STAFF_ID,T.UPDATE_DEPART_ID,T.REMARK,T.RSRV_NUM1,
T.RSRV_NUM2,T.RSRV_NUM3,TO_CHAR(T.RSRV_NUM4) RSRV_NUM4,TO_CHAR(T.RSRV_NUM5) RSRV_NUM5,T.RSRV_STR1,C.PARAM_NAME
  FROM TF_F_USER_SALE_NEW T, TD_S_COMMPARA C
 WHERE C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '9088'
   AND C.PARAM_CODE = T.PRODUCT_ID
   AND T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.PROCESS_TAG = '0'
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE