UPDATE TF_F_USER_SALEACTIVE_BOOK A
   SET A.PROCESS_TAG  = '1',
       A.UPDATE_TIME  = SYSDATE,
       A.END_DATE     = SYSDATE,
       A.DEAL_STATE_CODE = '2'
 WHERE A.PROCESS_TAG = '0'
   AND A.DEAL_STATE_CODE = '0'
   AND NVL(A.RSRV_DATE2, A.END_DATE) > SYSDATE
   AND A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.ACCEPT_TRADE_ID = :TRADE_ID