select   SIGN_ID          ,
  USER_TYPE        ,
  USER_VALUE       ,
  HOME_AREA        ,
  BANK_ACCT_ID     ,
  BANK_ACCT_TYPE   ,
  BANK_ID          ,
  CHNL_TYPE        ,
  PAY_TYPE         ,
  RECH_THRESHOLD   ,
  RECH_AMOUNT      ,
  SIGN_STATE       ,
  to_char(APPLY_DATE,'yyyy-mm-dd hh24:mi:ss') APPLY_DATE,
  to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,
  to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,
  USER_NAME        ,
  ID_TYPE          ,
  ID_VALUE         ,
  to_char(UPDATE_DATE,'yyyy-mm-dd hh24:mi:ss') UPDATE_DATE,
  UPDATE_STAFF_ID  ,
  UPDATE_DEPART_ID ,
  REMARK           ,
  RSRV_NUM1        ,
  RSRV_NUM2        ,
  RSRV_NUM3        ,
  RSRV_NUM4        ,
  RSRV_NUM5        ,
  RSRV_STR1        ,
  RSRV_STR2        ,
  RSRV_STR3        ,
  RSRV_STR4        ,
  RSRV_STR5        ,
  RSRV_STR6        ,
  RSRV_STR7        ,
  RSRV_STR8        ,
  RSRV_STR9        ,
  RSRV_STR10       ,
  to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
  to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
  to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
  RSRV_TAG1        ,
  RSRV_TAG2        ,
  RSRV_TAG3        
  from TF_F_BANK_MAINSIGN
 where user_type = :USER_TYPE
   and user_value = :USER_VALUE
   and start_date=(select max(start_date) from  TF_F_BANK_MAINSIGN
 where user_type = :USER_TYPE
   and user_value = :USER_VALUE and sign_state='1')
   and sign_state = '1'