--IS_CACHE=Y
SELECT T.CONTRACT_CODE, T.ATTR_CODE, T.ATTR_NAME, T.ATTR_VALUE,T.RSRV_STR5
     FROM TD_B_CONTRACT_ATTR T, TD_B_CONTRACT S
    WHERE S.CONTRACT_CODE = T.CONTRACT_CODE
      AND S.CONTRACT_CODE = :CONTRACT_CODE
      AND S.STATUS = '2' ORDER BY ATTR_CODE,ATTR_VALUE