--IS_CACHE=Y
SELECT CONTRACT_ID,
	   CONTRACT_NAME,       
       CONTRACT_TYPE,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       TO_CHAR(RSRV_DATE1, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'YYYY-MM-DD hh24:mi:ss') RSRV_DATE3,
       EPARCHY_CODE
  FROM TD_B_CONTRACT T
  WHERE CONTRACT_ID=:CONTRACT_ID