SELECT T.RSRV_STR1, T.RSRV_TAG1, T.RSRV_STR2, T.RSRV_STR3, T.RSRV_TAG2,
       T.EXTEND_VALUE
  FROM TF_F_CUST_GROUP_EXTEND T, TF_F_CUST_GROUP G
 WHERE 1 = 1
   AND T.EXTEND_TAG = 'vpntag'
   AND T.EXTEND_VALUE = TO_CHAR(G.CUST_ID)
   AND G.REMOVE_TAG = '0'
   AND T.RSRV_TAG1 = :RSRV_TAG1
   AND T.RSRV_TAG2 = :RSRV_TAG2
   AND G.GROUP_ID = :GROUP_ID
   AND T.RSRV_STR1 = :VPN_NO
