SELECT to_char(TRADE_ID) TRADE_ID, ACCEPT_MONTH, to_char(USER_ID) USER_ID, FEE_MODE, FEE_TYPE_CODE, to_char(OLDFEE) OLDFEE, to_char(FEE) FEE, to_char(CHARGE_ID) CHARGE_ID, DISCNT_GIFT_ID, to_char(LIMIT_MONEY) LIMIT_MONEY, MONTHS, to_char(EFFICET_DATE,'yyyy-mm-dd hh24:mi:ss') EFFICET_DATE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10
  FROM tf_b_tradefee_sub
 WHERE trade_id = TO_NUMBER(:TRADE_ID)
   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
   AND fee_mode = :FEE_MODE