DELETE FROM TF_F_USER_PLATSVC_TRACE
 WHERE  RELA_INST_ID = :RELA_INST_ID
   AND SERVICE_ID = :SERVICE_ID
   AND USER_ID = :USER_ID
    AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND END_DATE > SYSDATE