SELECT TO_CHAR(OPERATE_ID) OPERATE_ID,
       SERIAL_NUMBER,
       BATCH_OPER_TYPE,
       TO_CHAR(REFER_TIME, 'yyyy-mm-dd hh24:mi:ss') REFER_TIME,
       DEAL_STATE
  FROM TF_B_TRADE_BATDEAL
 WHERE BATCH_OPER_TYPE IN
       (SELECT BATCH_OPER_TYPE
          FROM TD_B_BATCHTYPE
         WHERE CANCELABLE_FLAG = '1'
           AND BATCH_OPER_TYPE IN
               (SELECT DISTINCT BATCH_OPER_TYPE
                  FROM TF_B_TRADE_BATDEAL
                 WHERE BATCH_ID = :BATCH_ID))
   AND CANCEL_TAG = '0'
   AND DEAL_STATE IN ('0', '1', '3', '6', '9', 'A')
   AND BATCH_ID = :BATCH_ID