SELECT P.BATCH_COUNT
  FROM TF_B_TRADE_BAT P
 WHERE P.BATCH_ID IN
       (SELECT T.BATCH_ID
          FROM TF_B_TRADE_BATDEAL T
         WHERE T.OPERATE_ID = TO_NUMBER(:OPERATE_ID)
           AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:OPERATE_ID, 5, 2)))
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(P.BATCH_ID, 5, 2))