UPDATE TF_B_TRADE_BATDEAL T
   SET T.DEAL_STATE  = :DEAL_STATE,
       T.DEAL_TIME   = SYSDATE,
       T.DEAL_RESULT = :DEAL_RESULT,
       T.TRADE_ID    = to_number(:TRADE_ID)
 WHERE T.OPERATE_ID = :OPERATE_ID