SELECT DISTINCT A.*,B.RSRV_STR1 BUSINESS_CLASS,B.TITLE_NAME CAMPN_NAME,B.SALE_ACT_SCRIPT TEMPLET_CONTENT,B.SMS_SCRIPT SMS_CONTENT,B.IS_ONE_KEY MOD_NAME,B.*,B.PRO_TYPE_CODE CAMPN_ID,B.STEP_ID  OBJECT_ID,A.PROCESS_TAG APROCESS_TAG
FROM TL_O_REALTIMEMARKETING A, TL_O_REALTIMEMARKETINGTRADE B , TD_S_COMMPARA D
WHERE A.REQ_ID = B.REQ_ID
AND A.USER_ID = :USER_ID
AND A.SERIAL_NUMBER = :SERIAL_NUMBER
AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
AND A.PROCESS_TAG IN ('0', '2', '3')
and b.process_tag is null
AND D.SUBSYS_CODE = 'CSM'
AND D.PARAM_ATTR = 6534
AND D.PARAM_CODE =  'RealTimeMarketing_PRIORITY_LEVEL'
AND D.PARA_CODE1 = B.PRIORITY_LEVEL
AND D.END_DATE > SYSDATE
AND (D.EPARCHY_CODE = '0898' OR D.EPARCHY_CODE = 'ZZZZ')

union
SELECT DISTINCT A.*,B.RSRV_STR1 BUSINESS_CLASS,B.TITLE_NAME CAMPN_NAME,B.SALE_ACT_SCRIPT TEMPLET_CONTENT,B.SMS_SCRIPT SMS_CONTENT,B.IS_ONE_KEY MOD_NAME,B.*,B.PRO_TYPE_CODE CAMPN_ID,B.STEP_ID  OBJECT_ID,A.PROCESS_TAG APROCESS_TAG
FROM TL_O_REALTIMEMARKETING A,
TL_O_REALTIMEMARKETINGTRADE B,
TD_S_COMMPARA C,
TD_S_COMMPARA D
WHERE A.REQ_ID = B.REQ_ID
AND A.USER_ID = :USER_ID
AND A.SERIAL_NUMBER = :SERIAL_NUMBER
AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
AND A.PROCESS_TAG IN ('0', '2', '3')
AND C.SUBSYS_CODE = 'CSM'
AND C.PARAM_ATTR = 5211
AND C.PARAM_CODE = 'REALTIMEMARKETING'
AND C.PARA_CODE1 = B.PROCESS_TAG
AND B.PROCESS_TAG = '1'
AND C.PARA_CODE2 >= NVL(B.RSRV_NUM1, 0)
AND C.END_DATE > SYSDATE
AND (C.EPARCHY_CODE = '0898' OR C.EPARCHY_CODE = 'ZZZZ')
AND D.SUBSYS_CODE = 'CSM'
AND D.PARAM_ATTR = 6534
AND D.PARAM_CODE =  'RealTimeMarketing_PRIORITY_LEVEL'
AND D.PARA_CODE1 = B.PRIORITY_LEVEL
AND D.END_DATE > SYSDATE
AND (D.EPARCHY_CODE = '0898' OR D.EPARCHY_CODE = 'ZZZZ')
union
SELECT DISTINCT A.*,B.RSRV_STR1 BUSINESS_CLASS,B.TITLE_NAME CAMPN_NAME,B.SALE_ACT_SCRIPT TEMPLET_CONTENT,B.SMS_SCRIPT SMS_CONTENT,B.IS_ONE_KEY MOD_NAME,B.*,B.PRO_TYPE_CODE CAMPN_ID,B.STEP_ID  OBJECT_ID,A.PROCESS_TAG APROCESS_TAG
FROM TL_O_REALTIMEMARKETING A,
TL_O_REALTIMEMARKETINGTRADE B,
TD_S_COMMPARA C,
TD_S_COMMPARA D
WHERE A.REQ_ID = B.REQ_ID
AND A.USER_ID = :USER_ID
AND A.SERIAL_NUMBER = :SERIAL_NUMBER
AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
AND A.PROCESS_TAG IN ('0', '2', '3')
AND C.SUBSYS_CODE = 'CSM'
AND C.PARAM_ATTR = 5211
AND C.PARAM_CODE = 'REALTIMEMARKETING'
AND C.PARA_CODE1 = B.PROCESS_TAG
AND B.PROCESS_TAG = '2'
AND C.PARA_CODE2 >= NVL(B.RSRV_NUM2, 0)
AND C.END_DATE > SYSDATE
AND (C.EPARCHY_CODE = '0898' OR C.EPARCHY_CODE = 'ZZZZ')
AND D.SUBSYS_CODE = 'CSM'
AND D.PARAM_ATTR = 6534
AND D.PARAM_CODE =  'RealTimeMarketing_PRIORITY_LEVEL'
AND D.PARA_CODE1 = B.PRIORITY_LEVEL
AND D.END_DATE > SYSDATE
AND (D.EPARCHY_CODE = '0898' OR D.EPARCHY_CODE = 'ZZZZ')