INSERT INTO tf_f_user_product
(PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PRODUCT_MODE,BRAND_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT MOD(TO_NUMBER(USER_ID),10000),USER_ID,USER_ID_A,PRODUCT_ID,PRODUCT_MODE,BRAND_CODE,INST_ID,CAMPN_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
FROM tf_b_trade_product p
WHERE trade_id=:TRADE_ID
And Not Exists 
(Select 1 From tf_f_user_product Where user_id=p.user_id And partition_id=Mod(p.user_id,10000) And product_id= p.product_id And end_date>=start_date And end_date>Sysdate )