SELECT to_char(a.trade_id) trade_id,
       a.trade_type_code,
       to_char(a.batch_id) batch_id,
       a.priority,
       to_char(a.charge_id) charge_id,
       to_char(a.acct_id) acct_id,
       to_char(a.user_id) user_id,
       a.serial_number,
       a.writeoff_mode,
       a.channel_id,
       a.payment_id,
       a.payment_op,
       a.pay_fee_mode_code,
       to_char(a.recv_fee) recv_fee,
       a.outer_trade_id,
       a.bill_start_cycle_id start_cycle_id,
       a.bill_end_cycle_id end_cycle_id,
       to_char(a.start_date, 'yyyy-mm-dd hh24:mi:ss') start_date,
       to_char(a.end_date, 'yyyy-mm-dd hh24:mi:ss') end_date,
       a.months,
       to_char(a.limit_money) limit_money,
       a.payment_reason_code,
       a.extend_tag,
       a.action_code,
       to_char(a.action_event_id) action_event_id,
       to_char(a.acct_balance_id) acct_balance_id,
       a.deposit_code,
       a.private_tag,
       a.remark,
       a.input_no,
       a.input_mode,
       to_char(a.acct_id2) acct_id2,
       to_char(a.user_id2) user_id2,
       a.deposit_code2,
       to_char(a.rel_charge_id) rel_charge_id,
       to_char(a.trade_time, 'yyyy-mm-dd hh24:mi:ss') recv_time,
       a.trade_eparchy_code recv_eparchy_code,
       a.trade_city_code recv_city_code,
       a.trade_depart_id recv_depart_id,
       a.trade_staff_id recv_staff_id,
       a.cancel_tag,
       a.deal_tag,
       to_char(a.deal_time, 'yyyy-mm-dd hh24:mi:ss') deal_time,
       a.result_code,
       a.result_info,
       to_char(a.rsrv_fee1) rsrv_fee1,
       to_char(a.rsrv_fee2) rsrv_fee2,
       a.rsrv_info1,
       b.payment,c.action_name
  FROM tf_b_paylog_dmn a,td_b_payment b,td_b_discnt_action c
 WHERE a.user_id = TO_NUMBER(:USER_ID)
  AND a.deal_tag = '0'
  AND a.trade_time>=TO_DATE(:BEGIN_RECV_TIME, 'YYYY-MM-DD HH24:MI:SS')
  AND a.trade_time<=TO_DATE(:END_RECV_TIME, 'YYYY-MM-DD HH24:MI:SS')
  AND a.action_code=c.action_code(+) AND a.payment_id=b.payment_id(+)