SELECT B.*,M.SERIAL_NUMBER LINK_PHONE FROM TF_B_GRP_BUSAPPLY B, TF_F_CUST_MANAGER_STAFF M
WHERE B.SERIAL_NUMBER = :SERIAL_NUMBER 
      AND B.OBJ_TYPE_CODE = :OBJ_TYPE_CODE
      AND B.CUST_MANAGER_ID = M.CUST_MANAGER_ID(+)