SELECT ACCT.CUST_ID,
       ACCT.ACCT_ID,
       ACCT.PAY_NAME,
       ACCT.BANK_CODE,
       ACCT.PAY_MODE_CODE,
       ACCT.BANK_ACCT_NO,
       U.SERIAL_NUMBER,
       PAY.PAYITEM_CODE,
       PAY.START_CYCLE_ID,
       PAY.END_CYCLE_ID,
       PAY.UPDATE_TIME,
       PAY.UPDATE_STAFF_ID,
       U.CITY_CODE,
       U.USER_ID
  FROM TF_A_PAYRELATION PAY, TF_F_ACCOUNT ACCT, TF_F_USER U
 WHERE ACCT.REMOVE_TAG = '0'
   AND ACCT.PARTITION_ID = MOD(PAY.ACCT_ID, 10000)
   AND ACCT.ACCT_ID = PAY.ACCT_ID
   AND ACCT.RSRV_STR5 = 'UnifyPayProduct'
   AND TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) BETWEEN PAY.START_CYCLE_ID AND
       PAY.END_CYCLE_ID
   AND PAY.DEFAULT_TAG = '0'
   AND PAY.ACT_TAG = '1'
   AND PAY.PARTITION_ID = U.PARTITION_ID
   AND PAY.USER_ID = U.USER_ID
   AND U.REMOVE_TAG = '0'
   AND U.SERIAL_NUMBER = :SERIAL_NUMBER
