INSERT INTO TF_A_PAYRELATION
  (PARTITION_ID,USER_ID,ACCT_ID,PAYITEM_CODE,ACCT_PRIORITY,USER_PRIORITY,ADDUP_MONTHS,ADDUP_METHOD,BIND_TYPE,START_CYCLE_ID,END_CYCLE_ID,DEFAULT_TAG,ACT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,INST_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME)
  SELECT MOD(USER_ID, 10000),USER_ID,ACCT_ID,PAYITEM_CODE,'0','0',ADDUP_MONTHS,ADDUP_METHOD,BIND_TYPE,START_CYCLE_ID,END_CYCLE_ID,DEFAULT_TAG,ACT_TAG,LIMIT_TYPE,LIMIT,COMPLEMENT_TAG,INST_ID,:TRADE_STAFF_ID,:TRADE_DEPART_ID,SYSDATE
    FROM TF_B_TRADE_PAYRELATION
   WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))