INSERT INTO TF_B_TRADE_TELEPHONE
(TRADE_ID,ACCEPT_MONTH,USER_ID,STAND_ADDRESS,DETAIL_ADDRESS,SIGN_PATH,PORT_TYPE,STAND_ADDRESS_CODE,INST_ID,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,MODIFY_TAG,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT :TRADE_ID,TO_NUMBER(SUBSTR(:TRADE_ID,5,2)),:USER_ID,STAND_ADDRESS,DETAIL_ADDRESS,SIGN_PATH,PORT_TYPE,STAND_ADDRESS_CODE,SEQ_INST_ID.Nextval,START_DATE,to_date(:ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss'),UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,'1',RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
  FROM TF_F_USER_TELEPHONE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
   AND NOT EXISTS (SELECT 1 FROM TF_B_TRADE_TELEPHONE A
                    WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
                      AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                      AND A.USER_ID = USER_ID)
   AND SYSDATE > START_DATE AND SYSDATE < END_DATE