INSERT INTO TF_B_TRADE_RELATION_UU_BAK
  (TRADE_ID, ACCEPT_MONTH, PARTITION_ID, USER_ID_A, SERIAL_NUMBER_A,
   USER_ID_B, SERIAL_NUMBER_B, RELATION_TYPE_CODE, ROLE_TYPE_CODE,
   ROLE_CODE_A, ROLE_CODE_B, ORDERNO, SHORT_CODE, INST_ID, START_DATE,
   END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK,
   RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1,
   RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2,
   RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
  SELECT TO_NUMBER(:TRADE_ID), TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         PARTITION_ID, USER_ID_A, SERIAL_NUMBER_A, USER_ID_B,
         SERIAL_NUMBER_B, RELATION_TYPE_CODE, ROLE_TYPE_CODE, ROLE_CODE_A,
         ROLE_CODE_B, ORDERNO, SHORT_CODE, INST_ID, START_DATE, END_DATE,
         UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1,
         RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3,
         RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
    FROM TF_F_RELATION_UU A
   WHERE (USER_ID_A, USER_ID_B, RELATION_TYPE_CODE, START_DATE) IN
         (SELECT USER_ID_A, USER_ID_B, RELATION_TYPE_CODE, START_DATE
            FROM TF_B_TRADE_RELATION
           WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
             AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
             AND MODIFY_TAG = :MODIFY_TAG
             AND USER_ID_B <> :USER_ID_B)
     AND SYSDATE < END_DATE
     AND NOT EXISTS
   (SELECT 1
            FROM TF_B_TRADE_RELATION_UU_BAK C
           WHERE C.TRADE_ID = TO_NUMBER(:TRADE_ID)
             AND C.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
             AND A.USER_ID_A = C.USER_ID_A
             AND A.USER_ID_B = C.USER_ID_B
             AND A.RELATION_TYPE_CODE = C.RELATION_TYPE_CODE
             AND A.START_DATE = C.START_DATE)