SELECT COUNT(1) RECORDCOUNT
  FROM TF_A_PAYRELATION A
 WHERE A.ACCT_ID = :ACCT_ID
   AND TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) BETWEEN A.START_CYCLE_ID AND
       A.END_CYCLE_ID
   AND A.DEFAULT_TAG = '0'
   AND A.ACT_TAG = '1'