--IS_CACHE=Y
SELECT A.AMONTHS,A.BRAND_CODE,A.CLASS_LIMIT,A.DEPOSIT_CODE,A.END_DATE,A.EPARCHY_CODE,A.EXCHANGE_LIMIT,A.EXCHANGE_MODE,A.EXCHANGE_TYPE_CODE,A.FMONTHS,A.GIFT_TYPE_CODE,A.MONEY_RATE,A.REMARK,A.REWARD_LIMIT,A.RIGHT_CODE,A.RSRV_STR1,A.RSRV_STR2,A.RSRV_STR3,A.RSRV_STR4,A.RSRV_STR5,A.RULE_ID,A.RULE_NAME,A.SCORE,A.SCORE_NUM,A.SCORE_TYPE_CODE,A.START_DATE,A.STATUS,A.UNIT,A.UPDATE_DEPART_ID,A.UPDATE_STAFF_ID,A.UPDATE_TIME,B.EXCHANGE_TYPE
FROM TD_B_EXCHANGE_RULE A,TD_B_SCORE_EXCHANGE_TYPE B
WHERE A.EXCHANGE_TYPE_CODE(+) = B.EXCHANGE_TYPE_CODE 
AND   A.STATUS = '0'
AND   A.END_DATE >= SYSDATE
AND   (A.EPARCHY_CODE = B.EPARCHY_CODE OR B.EPARCHY_CODE = 'ZZZZ')
AND   A.SCORE <= :SCORE
AND   (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
AND   (A.BRAND_CODE = :BRAND_CODE OR A.BRAND_CODE = 'G000' OR A.BRAND_CODE = 'ZZZZ')