UPDATE TF_B_TRADE_DISCNT T
   SET T.END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
 WHERE T.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND T.DISCNT_CODE = :DISCNT_CODE
