UPDATE TF_F_USER_SALE_DEPOSIT
   SET END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME = SYSDATE, UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID, REMARK = :REMARK
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND DISCNT_GIFT_ID = :DISCNT_GIFT_ID
   AND PACKAGE_ID = :PACKAGE_ID
   AND PRODUCT_ID = :PRODUCT_ID
   AND SYSDATE + 0 < END_DATE