UPDATE TF_F_USER_SALE_ACTIVE SET RSRV_TAG3 = '1' ,UPDATE_STAFF_ID = :UPDATE_STAFF_ID,UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
  UPDATE_TIME = TO_DATE(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss')
  WHERE USER_ID = :USER_ID
  AND PARTITION_ID=MOD(:USER_ID,10000)
  AND PACKAGE_ID = :PACKAGE_ID
  AND PRODUCT_ID = :PRODUCT_ID
  AND PROCESS_TAG = :PROCESS_TAG
  AND START_DATE = TO_DATE(:START_DATE,'yyyy-mm-dd hh24:mi:ss')
  AND END_DATE = TO_DATE(:END_DATE,'yyyy-mm-dd hh24:mi:ss')
  AND (RSRV_TAG3 IS NULL OR RSRV_TAG3='' OR RSRV_TAG3 <>'1')