SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_USER_DISCNT A
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND A.DISCNT_CODE IN :DISCNT_CODE
   AND ((A.DISCNT_CODE IN (2101, 2102, 2103) AND 'S' =:DISCNT_TYPE_CODE)
    OR (A.DISCNT_CODE IN (971, 972, 973, 1002, 1010) AND 'Q' = :DISCNT_TYPE_CODE))
   AND END_DATE > SYSDATE
   AND START_DATE < END_DATE