SELECT A.USER_ID,
       A.SERVICE_ID,
       A.INFO_CODE,
       A.INFO_VALUE,
       C.PARA_CODE2,
       C.PARA_CODE10
  FROM TF_F_USER_PLATSVC_ATTR A, TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = 3700
   AND C.PARAM_CODE = :SERVICE_ID
   AND C.PARA_CODE3 = A.INFO_CODE
   AND C.PARA_CODE1 = A.INFO_VALUE