SELECT B.BI_SN,T.EPARCHY_CODE,T.GROUP_ID,T.CUST_NAME,C.PRODUCT_NAME,C.PRODUCT_ID, 
		  CASE WHEN T.DEAL_STATE ='0' THEN '待资费审批' 
		  WHEN T.DEAL_STATE ='1' THEN '资费审批完成'
		  WHEN T.DEAL_STATE ='2' THEN '待签约'
		  WHEN T.DEAL_STATE ='3' THEN '待派单'
		  WHEN T.DEAL_STATE ='4' THEN '待审核'
		  WHEN T.DEAL_STATE ='5' THEN '待补录'
		  WHEN T.DEAL_STATE ='6' THEN '待订单执行'
		  WHEN T.DEAL_STATE ='7' THEN '已归档' END DEAL_STATE,
		  TO_CHAR(B.CREATE_DATE,'YYYYMMDDHH24MISS') CREATE_DATE
		  FROM TF_B_EOP_SUBSCRIBE T ,TF_B_EOP_PRODUCT C ,TF_B_EWE B 
		  WHERE 1=1 AND C.RECORD_NUM =0 AND B.BI_SN=T.IBSYSID AND B.BI_SN=C.IBSYSID
		  AND B.ACCEPT_STAFF_ID = :ACCEPT_STAFF_ID 
		  AND (:IBSYSID IS NULL OR C.IBSYSID = :IBSYSID) 
		  AND (:EPARCHY_CODE IS NULL OR T.EPARCHY_CODE= :EPARCHY_CODE) 
		  AND (:GROUP_ID IS NULL OR T.GROUP_ID=:GROUP_ID) 
		  AND ( :CUST_NAME IS NULL OR T.CUST_NAME LIKE '%'|| :CUST_NAME ||'%') 