SELECT T.REQ_ID,
       T.ACCEPT_MONTH,
       T.ACCEPT_DATE,
       T.SALE_ACT_ID,
       T.SALE_ACT_NAME,
       T.ACT_BEGIN_DATE,
       T.ACT_END_DATE,
       T.STEP_ID,
       T.SALE_ACT_SCRIPT,
       T.SMS_SCRIPT,
       T.SALE_ACT_TYPE,
       T.PRIORITY_LEVEL,
       T.PRO_TYPE,
       T.PRO_TYPE_CODE,
       T.TITLE_NAME,
       T.IS_ONE_KEY,
       T.PRO_SUB_TYPE,
       T.SMS_PORT,
       T.TRADE_STAFF_ID,
       T.TRADE_DEPART_ID,
       T.TRADE_CITY_CODE,
       T.TRADE_EPARCHY_CODE,
       T.PROCESS_TAG,
       T.EXEC_DESC,
       T.EXEC_RESULT,
       T.EXEC_TIME,
       T.REMARK,
       T.RSRV_NUM1,
       T.RSRV_NUM2,
       T.RSRV_NUM3,
       T.RSRV_NUM4,
       T.RSRV_NUM5,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5,
       T.RSRV_STR6,
       T.RSRV_STR7,
       T.RSRV_STR8,
       T.RSRV_STR9,
       T.RSRV_STR10,
       T.RSRV_STR11,
       T.RSRV_STR12,
       T.RSRV_STR13,
       T.RSRV_STR14,
       T.RSRV_DATE1,
       T.RSRV_DATE2,
       T.RSRV_DATE3,
       T.RSRV_TAG1,
       T.RSRV_TAG2,
       T.RSRV_TAG3 FROM TL_O_REALTIMEMARKETINGTRADE T
       WHERE 1 = 1
       AND T.REQ_ID = :REQ_ID
       AND T.SALE_ACT_ID = :SALE_ACT_ID
       ORDER BY T.ACT_BEGIN_DATE DESC