--IS_CACHE=N
select A.BARCODE_ID, A.BARCODE_TYPE, B.X_TRANS_CODE
  from TD_B_BARCODE A, TD_S_BARCODE_TYPE B
 where A.BARCODE_ID = :BARCODE_ID
   and (A.EPARCHY_CODE = :EPARCHY_CODE or A.EPARCHY_CODE = 'ZZZZ')
   and A.STATE = '1'
   and sysdate between A.START_DATE and A.END_DATE
   and A.BARCODE_TYPE = B.BARCODE_TYPE
   and (B.EPARCHY_CODE = :EPARCHY_CODE or B.EPARCHY_CODE = 'ZZZZ')
   and B.STATE = '1'