SELECT T.SYSCODE,
       T.CONFIGNAME,
       T.CONFIGDESC,
       T.PARAMNAME,
       T.VALUESEQ,
       T.PARAMVALUE,
       T.VALUEDESC,
       T.REMARK,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.VALID_TAG,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_CONFIG T
 WHERE T.VALID_TAG = :VALID_TAG
   AND T.PARAMNAME = :PARAMNAME
   AND T.SYSCODE = :SYSCODE
   AND T.CONFIGNAME = :CONFIGNAME
   AND T.VALUESEQ = :VALUESEQ
