SELECT
  T.SYSCODE, T.CONFIGNAME, T.CONFIGDESC, T.PARAMNAME, T.VALUESEQ, T.PARAMVALUE, T.VALUEDESC, T.REMARK, T.RSRV_STR1,
  T.RSRV_STR2, T.RSRV_STR3, T.VALID_TAG, T.ACCEPT_DEPART_ID, T.UPDATE_DEPART_ID, T.UPDATE_STAFF_ID, T.ACCEPT_STAFF_ID,
  T.CREATE_DATE, T.UPDATE_DATE
FROM TD_B_EWE_CONFIG T
WHERE T.CONFIGNAME = :CONFIGNAME
      AND T.PARAMVALUE = :PARAMVALUE
      AND T.VALUEDESC = :VALUEDESC
      AND T.RSRV_STR1 = :RSRV_STR1