--IS_CACHE=Y
SELECT B.PRODUCT_NAME,
       B.PRODUCT_EXPLAIN,
       B.PACKAGE_NAME,
       B.PROPERTY_ID PROPERTY,
       B.DISPOSITION_CODE ACCT_ID,
       B.ARTICLES_NUM SALE_NUM
  FROM TD_B_PACKAGE_ARTICLES B
 WHERE B.PRODUCT_ID = :PRODUCT_ID
   AND B.PACKAGE_ID = :PACKAGE_ID
   AND B.ELEMENT_ID = :ELEMENT_ID
   AND B.CITY_CODE = :CITY_CODE
   AND (:ELEMENT_TYPE_CODE IS NULL OR
       B.ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE)
   AND (:DISPOSITION_CODE IS NULL OR
       B.DISPOSITION_CODE = :DISPOSITION_CODE)
   AND SYSDATE BETWEEN b.start_date AND b.end_date