--IS_CACHE=N
INSERT INTO CHNL_CU_REGI_PARALLEL
(REGI_NUM,
 REGI_VARS,
 CUMU_ACYC,
 CUMU_ID,
 OPER_CODE,
 USER_ID,
 MOBILE_NUM,
 SCORE_TYPE,
 IN_TYPE,
 SEND_TIME,
 AREA_CODE,
 CAL_FLAG,
 KEEPMONTHID,
 SCORE_1,
 SCORE_2,
 PRE_CHAR1,
 PRE_CHAR2,
 PRE_NUM1,
 RELATION_TRADE_ID)
SELECT
SEQ_CHNL_EMPINTEGRAL_REGINUM.NEXTVAL,
 :REGI_VARS,
 :REGI_MONTH,
 :CUMU_ID,
 :OPER_CODE,
 :USER_ID,
 :SERIAL_NUMBER,
 1,
 :IN_MODE_CODE,
 TO_DATE(:REGI_TIME, 'YYYYMMDDHH24MISS'),
 :AREA_CODE,
 :CAL_FLAG,----:CAL_FLAG,-------2,3,0,12,22,(7登记成功计算成功,0未计算)登记
 0,
 ROUND(TO_NUMBER(:CAL_SCORE),2),------实时积分值
 0,
 ROUND(TO_NUMBER(:REGI_SCORE),2),---V_SMS.PRE_CHAR1; --发放的总积分
 ROUND(TO_NUMBER(:PRE_CHAR2),2),---PRODUCT_ID V_SMS.PRE_CHAR2; --升档的套餐价值 x
 ROUND(TO_NUMBER(:PRE_NUM1),2),---V_SMS.PRE_NUM1; --用于计算积分的套餐价值 x
 :TRADE_ID
FROM DUAL
