SELECT COUNT(1) 业务数
  FROM TF_F_USER_PLATSVC A, TF_F_USER B
 WHERE A.SERVICE_ID IN ('80002009')
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.USER_ID = B.USER_ID
   AND A.PARTITION_ID = B.PARTITION_ID
   AND B.REMOVE_TAG = '0'
   AND A.END_DATE > SYSDATE