--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_PLATSVC A
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.START_DATE > TO_DATE(:SEND_TIME, 'YYYYMMDD')
   AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT C WHERE C.COLLECT_ID=:COLLECT_ID AND C.COLLECT_DEF=A.SERVICE_ID) 