--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_SVC D
 WHERE D.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND D.USER_ID = TO_NUMBER(:USER_ID)
   AND D.END_DATE > SYSDATE
   AND D.SERVICE_ID IN (20150060, 20150160)
   AND ROWNUM < 2