--IS_CACHE=N
SELECT U.USER_ID_A A用户编码
  FROM TF_F_RELATION_UU U
 WHERE U.USER_ID_B = TO_NUMBER(:USER_ID)
   AND U.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND U.RELATION_TYPE_CODE = '56'
   AND U.ROLE_CODE_B = '1'
   AND U.START_DATE <=
       ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM'), -2) +
       1 / 86400
   AND U.END_DATE >=
       TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1)) + 1) - 1 / 86400
   AND ROWNUM < 2