--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型, ACCEPT_DATE 受理月份, TRADE_DEPART_ID 受理部门, TRADE_ID 台账标识
FROM (SELECT E.DEPART_KIND_CODE,
             TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
             A.TRADE_DEPART_ID,
             A.TRADE_ID
        FROM UCR_CRM1.TF_BH_TRADE A, UCR_CRM1.TF_B_TRADE_PRODUCT B, TD_M_DEPART E
       WHERE A.TRADE_ID = B.TRADE_ID
         AND A.TRADE_DEPART_ID = E.DEPART_ID
         AND A.USER_ID = B.USER_ID
         AND A.USER_ID = TO_NUMBER(:USER_ID)
         AND A.TRADE_TYPE_CODE IN (10, 40, 110)
         AND B.PRODUCT_ID IN (10003385, 10003388,84001658)
         AND B.MODIFY_TAG IN (0, 2)
         AND A.CANCEL_TAG = '0'
         AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
      UNION
      SELECT E.DEPART_KIND_CODE,
             TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
             A.TRADE_DEPART_ID,
             A.TRADE_ID
        FROM UCR_CRM1.TF_BH_TRADE A, TD_M_DEPART E
       WHERE A.TRADE_DEPART_ID = E.DEPART_ID
         AND A.USER_ID = TO_NUMBER(:USER_ID)
         AND A.TRADE_TYPE_CODE IN (60)
         AND EXISTS
       (SELECT 1
                FROM TF_F_USER U, TF_F_USER_PRODUCT UP
               WHERE U.PARTITION_ID = UP.PARTITION_ID
                 AND U.USER_ID = UP.USER_ID
                 AND U.USER_ID = A.USER_ID
                 AND U.REMOVE_TAG = '0'
                 AND U.ACCT_TAG = '0'
                 AND U.OPEN_DATE >= TRUNC(SYSDATE) - 7
                 AND UP.MAIN_TAG = '1'
                 AND UP.PRODUCT_ID IN (10003385, 10003388,84001658)
                 AND SYSDATE BETWEEN UP.START_DATE AND UP.END_DATE)) TRADE
WHERE ROWNUM < 2