--IS_CACHE=N
 SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(B.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
   FROM ucr_crm1.TF_B_TRADE_DISCNT A, ucr_crm1.TF_BH_TRADE B, TD_M_DEPART D
  WHERE B.USER_ID = TO_NUMBER(:USER_ID)
    AND B.TRADE_TYPE_CODE IN ('10', '110')
    AND B.CANCEL_TAG = '0'
    AND A.TRADE_ID = B.TRADE_ID
    AND TRUNC(B.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
    AND A.DISCNT_CODE = :DISCNT_CODE
    AND A.MODIFY_TAG = '0'
    AND B.TRADE_DEPART_ID = D.DEPART_ID
    AND ROWNUM < 2