--IS_CACHE=N
SELECT COUNT(1) 是否开通
FROM TF_F_USER_DISCNT
WHERE USER_ID = TO_NUMBER(:USER_ID)
AND PARTITION_ID = MOD( TO_NUMBER(:USER_ID),10000)
AND DISCNT_CODE IN (902) --0元的GPRS 套餐
AND SYSDATE BETWEEN START_DATE AND END_DATE
AND TRUNC(START_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)