--IS_CACHE=N
SELECT COUNT(1) 平台业务数
  FROM TF_F_USER_PLATSVC C
 WHERE C.USER_ID = TO_NUMBER(:USER_ID)
   AND C.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND C.START_DATE <=
       ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM'),-1)
   AND C.END_DATE >
       TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1)) + 1) - 1 / 86400
   AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT A WHERE A.COLLECT_ID=:COLLECT_ID AND A.COLLECT_DEF=C.SERVICE_ID)