--IS_CACHE=N
SELECT B.DEPART_KIND_CODE 部门类型,TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
FROM UCR_CRM1.TF_BH_TRADE A, TD_M_DEPART B, UCR_CRM1.TF_B_TRADE_DISCNT C
WHERE A.USER_ID = TO_NUMBER(:USER_ID)
AND A.TRADE_ID = C.TRADE_ID
AND A.TRADE_TYPE_CODE IN (10, 110)
AND A.CANCEL_TAG = '0'
AND A.TRADE_DEPART_ID = B.DEPART_ID
AND B.DEPART_KIND_CODE NOT IN ('100', '500','201')
AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND
     TRUNC(SYSDATE)
AND C.DISCNT_CODE IN
   (SELECT D.PARA_CODE1
      FROM TD_S_COMMPARA D
     WHERE D.SUBSYS_CODE = 'CSM'
       AND D.PARAM_ATTR = '1798'
       AND D.PARAM_CODE = '6'
       AND D.EPARCHY_CODE = '0898'
       AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
       AND D.PARA_CODE3 = :OPER_CODE)
AND C.MODIFY_TAG = '0'
AND ROWNUM < 2