--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_DISCNT
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND DISCNT_CODE IN (4900, 4902)
   AND START_DATE < TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -3)) + 1)
   AND END_DATE >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1)) + 1) - 1 / 86400