--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER U, TF_F_ACCOUNT ACC
 WHERE U.CUST_ID = ACC.CUST_ID
   AND U.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND U.USER_ID = TO_NUMBER(:USER_ID)
   AND U.REMOVE_TAG = '0'
   AND ACC.ACCT_TAG = '0' --宽带PBOSS完工由2改为0