--IS_CACHE=N
SELECT COUNT(1) 业务数
  FROM TF_SM_BI_PP T
 WHERE T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.OPER_DATE = TO_CHAR(ADD_MONTHS(SYSDATE, TO_NUMBER(:V_OPER_DATE)), 'YYYYMM')