SELECT FEE 费用
  FROM (SELECT NVL(MAX(NVL(R.PRE_CHAR2, R.PRE_NUM1)), 0) * 100 * 0.93 FEE
          FROM CHNL_CU_REGI_PARALLEL R
         WHERE R.USER_ID = :USER_ID
           AND R.OPER_CODE = :OPER_CODE
           AND R.REGI_NUM = :REGI_NUM)