--IS_CACHE=N
SELECT COUNT(1) 业务数
  FROM TF_F_RELATION_UU B
 WHERE B.RELATION_TYPE_CODE = '47'
   AND B.SERIAL_NUMBER_B = 'KD_' || :MOBILE_NUM
   AND B.END_DATE > SYSDATE
   AND EXISTS (SELECT 1
          FROM TF_F_USER US, TF_F_USER_PRODUCT UP
         WHERE US.PARTITION_ID = UP.PARTITION_ID
           AND US.USER_ID = UP.USER_ID
           AND US.SERIAL_NUMBER = :MOBILE_NUM
           AND US.REMOVE_TAG = '0'
           AND UP.PRODUCT_ID IN (10003385, 10003388,84001658)
           AND UP.END_DATE > SYSDATE)
   AND ROWNUM < 2