--IS_CACHE=N
SELECT COUNT(A.USER_ID) 业务数
  FROM TF_F_USER_DISCNT A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   and a.partition_id = mod(TO_NUMBER(:USER_ID), 10000)
   AND A.DISCNT_CODE = :V_DISCNT_CODE
   AND A.END_DATE > SYSDATE