--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型, ACCEPT_DATE 受理月份, TRADE_DEPART_ID 受理部门, TRADE_ID 台账标识
 FROM (SELECT E.DEPART_KIND_CODE,
              TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
              A.TRADE_DEPART_ID,
              A.TRADE_ID
         FROM ucr_crm1.TF_BH_TRADE A, TD_M_DEPART E
        WHERE A.TRADE_DEPART_ID = E.DEPART_ID
          AND A.USER_ID = TO_NUMBER(:USER_ID)
          AND A.TRADE_TYPE_CODE IN (230,240)
          AND A.RSRV_STR1 IN ('67220429')
          AND A.CANCEL_TAG = '0'
          AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
       ) TRADE
WHERE ROWNUM < 2