--IS_CACHE=N
SELECT A.USER_ID_B B用户编码
  FROM TF_F_RELATION_UU A
 WHERE A.RELATION_TYPE_CODE = 45
   AND A.ROLE_CODE_B = 1
   AND A.END_DATE > SYSDATE
   AND EXISTS
 (SELECT 1
          FROM TF_F_RELATION_UU T
         WHERE T.RELATION_TYPE_CODE = '45'
           AND T.ROLE_CODE_B = 2
           AND T.USER_ID_B = TO_NUMBER(:USER_ID)
           AND T.END_DATE >=
               ADD_MONTHS(TRUNC(LAST_DAY(SYSDATE) + 1) - 1 / 86400, -1)
           AND T.USER_ID_A = A.USER_ID_A
           AND T.START_DATE <
               TO_DATE(:SEND_TIME_SS,'YYYY-MM-DD hh24:mi:ss'))