--IS_CACHE=N
SELECT I.CU_PASS 店员密码, I.AREA_CODE 归属业务区, I.CUMU_DEPART_ID 归属部门, I.MOBILE_NUM 手机号码, I.CUMU_NAME 店员名称, I.BANK_ACCT_NAME 账户名称,I.BANK_ACCT 账户账号,I.BIND_STAFF_ID 绑定工号,I.*
  FROM CHNL_CU_CUMUINFO I
 WHERE I.CUMU_ID =:CUMU_ID
   AND I.UPDATE_STATE = '1'
