--IS_CACHE=N
SELECT C.PARA_CODE1 套餐,C.PARA_CODE6 是否自选,TO_NUMBER(C.PARA_CODE4) 套餐价值,TO_CHAR(D.END_DATE, 'YYYYMM') 结束月份,C.PARA_CODE2, C.PARAM_NAME, TO_CHAR(D.UPDATE_TIME, 'YYYYMM') 变更月份,TO_CHAR(D.UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') 变更时间,D.UPDATE_DEPART_ID 变更部门
FROM TD_S_COMMPARA C, TF_F_USER_DISCNT D
WHERE C.SUBSYS_CODE = 'CSM'
 AND C.PARAM_ATTR =:COMMPARA_ATTR
 AND C.PARAM_CODE = 'CUMU'
 AND D.PARTITION_ID = MOD(:USER_ID, 10000)
 AND D.USER_ID = TO_NUMBER(:USER_ID)
 AND TRUNC(D.END_DATE) <> TO_DATE('2050-12-31', 'YYYY-MM-DD') ----失效了
 ---AND TO_CHAR(D.UPDATE_TIME, 'YYYYMM') = :REGI_MONTH ----登记月份有做变更
 AND TO_CHAR(D.UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') = :UPDATE_TIME
 AND D.DISCNT_CODE = C.PARA_CODE1
 AND ROWNUM < 2