--IS_CACHE=N
SELECT A.SERVICE_ID
FROM TF_F_USER_PLATSVC A
WHERE  A.END_DATE > SYSDATE
 AND A.USER_ID = TO_NUMBER(:USER_ID)
 AND A.PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)
 AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT C WHERE C.COLLECT_ID=:COLLECT_ID AND C.COLLECT_DEF=A.SERVICE_ID)