--IS_CACHE=N
SELECT A.RSRV_STR2 活动产品,D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_DEPART_ID 受理部门,A.TRADE_ID 台账标识
 FROM UCR_CRM1.TF_BH_TRADE A, TD_M_DEPART D, TF_F_USER_SALE_ACTIVE C
WHERE A.TRADE_TYPE_CODE = '240'
  AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
  AND A.CANCEL_TAG = '0'
  AND A.RSRV_STR1 = :SALEACTIVE_PACKAGE
  AND C.USER_ID = TO_NUMBER(:USER_ID)
  AND A.TRADE_DEPART_ID = D.DEPART_ID
  AND A.TRADE_ID = C.RELATION_TRADE_ID
  AND ROWNUM < 2