--IS_CACHE=N
SELECT DECODE(COUNT(1),0,0,1) 前三月是否办理
 FROM TF_F_USER_SVC B, TF_F_RELATION_UU U
WHERE B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
  AND B.USER_ID = TO_NUMBER(:USER_ID)
  AND B.SERVICE_ID = 831
  AND B.START_DATE >= ADD_MONTHS(TO_DATE(:ACCEPT_MONTH, 'YYYYMM'), -3) --该用户前三个月办理过亲亲网（家庭网）业务不能登记积分=
  AND B.START_DATE < TO_DATE(:ACCEPT_MONTH, 'YYYYMM')
  AND B.USER_ID = U.USER_ID_B
  AND U.RELATION_TYPE_CODE = '45' -- 家庭网关系
  AND U.ROLE_CODE_B = '1'