--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型, ACCEPT_DATE 受理月份, UPDATE_DEPART_ID 受理部门, RELATION_TRADE_ID 台账标识
FROM (SELECT E.DEPART_KIND_CODE,
             TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
             A.UPDATE_DEPART_ID,
             A.RELATION_TRADE_ID
        FROM TF_F_USER_SALE_ACTIVE A, TD_M_DEPART E
       WHERE A.UPDATE_DEPART_ID = E.DEPART_ID
         AND A.PARTITION_ID = MOD(:USER_ID, 10000)
         AND A.USER_ID = TO_NUMBER(:USER_ID)
         AND A.PRODUCT_ID IN (68800751)
         AND A.PACKAGE_ID IN (68034409)
         AND A.PROCESS_TAG = '0'
         AND A.END_DATE > SYSDATE) TRADE
WHERE ROWNUM < 2