--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
FROM ucr_crm1.TF_BH_TRADE    A, ucr_crm1.TF_B_TRADE_SVC B,TF_F_USER_SVC  C,TD_M_DEPART    D
WHERE A.USER_ID = :USER_ID
AND A.TRADE_TYPE_CODE IN (10, 110)
AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
AND CANCEL_TAG = '0'
AND B.SERVICE_ID IN (59, 60)
AND B.MODIFY_TAG = '0'
AND B.USER_ID = C.USER_ID
AND A.TRADE_ID = B.TRADE_ID
AND B.INST_ID = C.INST_ID
AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
AND A.TRADE_DEPART_ID = D.DEPART_ID
AND ROWNUM < 2