--IS_CACHE=N
SELECT DETAIL.SALE_TIME, DETAIL.SALE_POLICY 终端费用, DETAIL.SUB_BUSI_TYPE 终端类型
FROM (SELECT TO_CHAR(A.CREATE_DATE, 'YYYY-MM-DD') SALE_TIME,
A.CONSUME_LIMIT SALE_POLICY,
B.SUB_BUSI_TYPE
FROM IM.PSI_SALE_DETAIL@DB_ZDGL           A,
IM.PSI_BUSI_OPERA@DB_ZDGL            B,
IM.IM_INV_MOBTEL_USE@DB_ZDGL         C,
IM_DICT.IM_RES_TYPE_ATTR_SET@DB_ZDGL D
WHERE A.BUSI_ID = B.BUSI_ID
AND A.START_INV_ID = C.INV_ID
AND C.BUSI_STATUS = 'USED'
AND A.INOUT_FLAG = 'OUTSTORE'
AND A.CREATE_DATE > TRUNC(SYSDATE) - 3
AND B.SUB_BUSI_TYPE IN ('CONTACTSALE', 'BARESALE')
AND A.REGION = B.REGION
AND B.REGION = C.REGION
AND C.REGION = 898
AND C.RES_TYPE_ID = D.RES_TYPE_ID
AND D.ATTR_ID = 'MOBTEL_ATTR_PRODUCTLEVEL'
AND D.ATTR_VALUE IN ('DEPTHCOOPERATION','STRATEGIC')
AND C.INV_ID = :USER_ID
ORDER BY A.BUSI_ID DESC) DETAIL
WHERE 1 = 1
AND ROWNUM < 2