--IS CACHE=Y
SELECT count(1) 业务数
            FROM TF_F_USER_PLATSVC B
           WHERE B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
             AND B.USER_ID = TO_NUMBER(:USER_ID)
             AND B.START_DATE >=
             ADD_MONTHS(TO_DATE(:ACCEPT_MONTH, 'YYYYMM'), -3)
			 AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT L WHERE L.COLLECT_ID=:COLLECT_ID AND L.COLLECT_DEF=to_char(B.SERVICE_ID))	 
             AND B.START_DATE < TO_DATE(:ACCEPT_MONTH, 'YYYYMM')