--IS_CACHE=N
SELECT COUNT(1) 用户关系数
  FROM TF_F_RELATION_UU U
 WHERE U.USER_ID_A = :USER_ID_A
   AND U.RELATION_TYPE_CODE = '56'
   AND U.ROLE_CODE_B = '2'
   AND U.START_DATE <
       ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYYMM'), 'YYYYMM'), TO_NUMBER(:V_START_DATE))
   AND U.END_DATE >=
       TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, TO_NUMBER(:V_END_DATE))) + 1) - 1 / 86400
   AND ROWNUM < 2