--IS_CACHE=N
SELECT DECODE(COUNT(1),0,1,0) 统计数 
  FROM TF_F_USER_SVC A
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.SERVICE_ID =:V_SERVICE_ID
   AND TO_DATE(:SEND_TIME, 'YYYYMMDD') BETWEEN TRUNC(A.START_DATE) AND
       A.END_DATE
   AND ADD_MONTHS(TRUNC(TO_DATE(TO_CHAR(A.START_DATE, 'YYYYMM'), 'YYYYMM')),
                  2) <=
       TRUNC(TO_DATE(TO_CHAR(A.END_DATE, 'YYYYMM'), 'YYYYMM'))