UPDATE  CHNL_CU_INTEGRAL_MONTH
   SET INTEGRAL_FLAG = :INTEGRAL_FLAG,
       KEEPMONTHID   = :KEEPMONTHID,
       SCORE_1       = :SCORE_1,
       CAL_FLAG      = :CAL_FLAG,
       INTRGRAL_MSG  = :INTRGRAL_MSG,
       AUDIT_INFO_FLAG = :AUDIT_INFO_FLAG,
       UPDATE_VERSION=MOD(UPDATE_VERSION+1,1000000000),
       START_TIME = TO_DATE(:START_TIME,'YYYY-MM-DD HH24:MI:SS'),
       END_TIME = SYSDATE
 WHERE MONTH_TRADE_ID = :MONTH_TRADE_ID
       AND UPDATE_VERSION =:UPDATE_VERSION