--IS_CACHE=Y
SELECT EPARCHY_CODE, MOFFICE_ID, SWITCH_ID, SERIALNUMBER_S, SERIALNUMBER_E, IMSI_S, IMSI_E, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1, to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2, to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7
  FROM TD_M_MOFFICE
 WHERE to_number(SERIALNUMBER_S)<=to_number(:SERIAL_NUMBER)
   AND to_number(SERIALNUMBER_E)>=to_number(:SERIAL_NUMBER)