INSERT INTO TL_B_USERBACK_EXTEND
  (USER_ID,
   OPEN_DATE,
   ACCEPT_MONTH,
   EXTEND_TIME,
   TRADE_STAFF_ID,
   TRADE_DEPART_ID,
   TRADE_DATE,
   SERIAL_NUMBER)
VALUES
  (:USER_ID,
   TO_DATE(:OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss'),
   TO_NUMBER(TO_CHAR(SYSDATE, 'mm')),
   :EXTEND_MONTH,
   :TRADE_STAFF_ID,
   :TRADE_DEPART_ID,
   SYSDATE,
   :SERIAL_NUMBER)