--IS_CACHE=Y
SELECT PRODUCT_TYPE_CODE paracode,PRODUCT_TYPE_NAME paraname FROM td_s_product_type
WHERE sysdate BETWEEN start_date AND end_date
   AND (:TRADE_EPARCHY_CODE IS NULL OR :TRADE_EPARCHY_CODE IS NOT NULL)