--IS_CACHE=Y
select IN_MODE_CODE,SP_CODE,BIZ_CODE,BIZ_PRI,SMS_ID,SMS_CODE,SMS_PROCESS_TAG,OPER_CODE,RSRV_NUM1,RSRV_NUM2,RSRV_STR1,RSRV_STR2,RSRV_STR3
  FROM TD_B_INMODE_SMS_PARA
 WHERE  SP_CODE = :SP_CODE
   AND BIZ_CODE = :BIZ_CODE
   AND SMS_CODE = :SMS_CODE