SELECT RECORDID LOG_ID, MATERIALCODE MATERIAL_CODE, AIMPRICE AIM_PRICE, PROTECTVALUE PROTECT_VALUE, 
	STARTDATE START_DATE, OPRNUMB OPER_TRADE_ID
FROM TI_R_PRICEADJUSTMENT_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')