DELETE FROM TF_F_USER_SVC A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND (END_DATE > SYSDATE OR EXISTS
        (SELECT 1
           FROM TF_B_TRADE_SVC_BAK B
          WHERE B.USER_ID = A.USER_ID
            AND B.SERVICE_ID = A.SERVICE_ID
            AND B.START_DATE = A.START_DATE
            AND B.TRADE_ID = TO_NUMBER(:TRADE_ID)))