SELECT ROWNUM,T1.* FROM ( 
SELECT ROWNUM,T.SUBORDER_ID,T.SUBEXTORDER_ID,T.ORDER_ID,T.STATE,T.DEAL_STATE,T.DEAL_DESC,T.NUMBER_OPRTYPE,T.SERVICENO,T.SERVICENO_TYPE,
T.NUMBER_BRAND,T.QUANTITY,T.NUMBER_PRICE,T.SIM_PRICE,T.LEGAL_NAME,T.CERTIFICATE_TYPE,T.CERTIFICATE_NO,T.ACTIVITY_CODE,T.ACTIVITY_TYPE,
T.ACTIVITY_NAME,T.ACTIVITY_DESC,T.ORDER_STATUS,T.RSRV_STR1,T.CREATE_TIME,T.UPDATE_TIME,T.STATUS_DESC,T.OP_CONTACT_NO 
FROM TF_B_CTRM_GERLSUBORDER T 
WHERE T.RSRV_STR1 IS NULL 
AND ( (T.NUMBER_OPRTYPE='20' AND T.STATE IN('AC','AF','FA')) OR (T.NUMBER_OPRTYPE='06' AND T.STATE IN('SC','FA')) OR T.NUMBER_OPRTYPE NOT IN('06','20','08','09','13','21','23','24','30','31') 
     OR (T.NUMBER_OPRTYPE='08' AND T.STATE IN('OC','OF','AC','FA')) OR (T.NUMBER_OPRTYPE='09' AND T.STATE IN('OC','OF','AC','FA')) OR (T.NUMBER_OPRTYPE='21' AND T.STATE IN('AC','AF','FA','PC')) 
     OR (T.NUMBER_OPRTYPE='23' AND T.STATE IN('PC','PF','AC','FA','AF'))
     OR (T.NUMBER_OPRTYPE='24' AND T.STATE IN('PC','PF','VC','VF','AC','AF','FA'))
     OR (T.NUMBER_OPRTYPE='31' AND T.STATE IN('SC','FA'))
     OR (T.NUMBER_OPRTYPE='30' AND T.STATE IN('ST','SE','RE','AC','SC','FA'))
	 OR (T.NUMBER_OPRTYPE='13' AND T.STATE IN('PC','PD','PS','PU','RS','RU'))
     ) 
ORDER BY RSRV_DATE 
) T1 WHERE ROWNUM<=500 AND ROWNUM>0