SELECT A.PACKAGECODE PACKAGE_CODE, A.PACKAGETYPE PACKAGE_TYPE,
	   A.STARTDATE START_DATE, A.ENDDATE END_DATE, A.SALESPRICE SALES_PRICE, A.DEPOSIT DEPOSIT,
	   A.USEDLOYALNUM USED_LOYAL_NUM, A.FLOATLOYALNUM FLOAT_LOYAL_NUM, A.CONSUMELIMIT CONSUME_LIMIT,
	   A.JOINMONTH JOIN_MONTH, A.COSTPMTMONEY COST_PMT_MONEY, A.FLOATCOST FLOAT_COST,A.COSTPMTMONTH COST_PMT_MONTH,
	   A.FAREPMTMONEY FARE_PMT_MONEY, A.FLOATFARE FLOAT_FARE, A.FAREPMTMONTH FARE_PMT_MONTH,
	   A.ISVALUEADD IS_VALUEADD, A.VALUEADDCOMMENT VALUEADD_COMMENT, A.PROMOTIONCOMMENT PROMOTION_COMMENT,
	   A.OPRNUMB IN_TRADE_ID, A.OPRNUMB OPER_TRADE_ID, DECODE(TRANSTYPE,'1','0','2','1') VALID_TAG,
	   A.PACKAGENAME PACKAGE_NAME,A.ISHQOPERATION IS_HQOPERATION,A.AVERAGEFARE AVERAGE_FARE,A.LASTFARE LAST_FARE
FROM TI_R_PACKAGE_DOWN A
WHERE 1 = 1
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')