--IS_CACHE=Y
SELECT MGMT_DISTRICT EPARCHY_CODE,
       SUPPLIER_TYPE_ID RES_TYPE_CODE,
       SUPPLIER_NO CORP_NO,
       SUPPLIER_NAME CORP_NAME,
       TO_CHAR(DONE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       OP_ID UPDATE_STAFF_ID,
       ORG_ID UPDATE_DEPART_ID,
       REMARKS REMARK,
       '' RSRV_STR1,
       0 X_TAG
  FROM res_supplier
 WHERE (MGMT_DISTRICT = :EPARCHY_CODE OR MGMT_DISTRICT = 'ZZZZ') 
 AND ((:RES_TYPE_CODE IS NOT NULL AND SUPPLIER_TYPE_ID = :RES_TYPE_CODE) OR :RES_TYPE_CODE IS NULL) ORDER BY SUPPLIER_NO