SELECT A.TRADE_ID,
       A.TRADE_STAFF_ID,
       A.TRADE_DEPART_ID,
       A.ACCEPT_DATE,
       A.SERIAL_NUMBER,
       B.RULE_ID,
       B.GOODS_NAME RULE_NAME,
       B.ACTION_COUNT,
       B.SCORE_CHANGED
  FROM TF_B_TRADE_SCORE B,TF_BH_TRADE A
 WHERE A.TRADE_ID = B.TRADE_ID
   AND A.CANCEL_TAG = '0'
   AND A.TRADE_TYPE_CODE = '330'
   AND A.ACCEPT_DATE BETWEEN TO_DATE(:ACCEPT_STARTDATA, 'YYYY-MM-DD') AND
       TO_DATE(:ACCEPT_END, 'YYYY-MM-DD') + 1
   AND A.TRADE_EPARCHY_CODE = :EPARCHY_CODE
   AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND A.TRADE_DEPART_ID = :TRADE_DEPART_ID
UNION ALL
SELECT A.TRADE_ID,
       A.TRADE_STAFF_ID,
       A.TRADE_DEPART_ID,
       A.ACCEPT_DATE,
       A.SERIAL_NUMBER,
       B.RULE_ID,
       B.GOODS_NAME RULE_NAME,
       B.ACTION_COUNT,
       B.SCORE_CHANGED
  FROM TF_B_TRADE_SCORE B, TF_B_TRADE A
 WHERE  A.TRADE_ID =B.TRADE_ID
   AND A.CANCEL_TAG = '0'
   AND A.TRADE_TYPE_CODE = '330'
   AND A.ACCEPT_DATE BETWEEN TO_DATE(:ACCEPT_STARTDATA, 'YYYY-MM-DD') AND
       TO_DATE(:ACCEPT_END, 'YYYY-MM-DD') + 1
   AND A.TRADE_EPARCHY_CODE = :EPARCHY_CODE
   AND A.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND A.TRADE_DEPART_ID = :TRADE_DEPART_ID