UPDATE TI_B_USRPACKAGEDATA_DOWN
   SET DEAL_FLAG = :NEW_DEAL_FLAG, REMARK = :REMARK,
       RSRV_DATE1 = TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_FLAG1 = '0'
 WHERE OPR_NUMB = :OPR_NUMB
   AND DEAL_FLAG = :DEAL_FLAG