SELECT /*+ use_nl(a,b)*/TO_CHAR(A.TRADE_ID) TRADE_ID,
       A.ACCEPT_MONTH,
       TO_CHAR(A.USER_ID) USER_ID,
       A.SERIAL_NUMBER,
       TO_CHAR(A.SCORE) SCORE,
       TO_CHAR(A.SCORE_CHANGED) SCORE_CHANGED,
       TO_CHAR(B.TRADE_TYPE_CODE) VALUE_CHANGED,
       B.ACCEPT_DATE REMARK
  FROM ucr_crm1.TF_B_TRADE_SCORE A, ucr_crm1.TF_BH_TRADE B
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.TRADE_ID = B.TRADE_ID
   AND B.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd HH24:MI:SS') AND
       TO_DATE(:END_DATE, 'yyyy-mm-dd HH24:MI:SS')
   AND b.accept_month=a.accept_month
   AND a.accept_month=substr(a.trade_id,5,2)
 ORDER BY B.ACCEPT_DATE DESC