UPDATE TF_F_USER
   SET REMOVE_TAG          = :REMOVE_TAG,
       DESTROY_TIME        = TO_DATE(:FINISH_DATE,'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME         = TO_DATE(:FINISH_DATE,'YYYY-MM-DD HH24:MI:SS'),
       REMOVE_EPARCHY_CODE = :REMOVE_EPARCHY_CODE,
       REMOVE_CITY_CODE    = :REMOVE_CITY_CODE,
       REMOVE_DEPART_ID    = :REMOVE_DEPART_ID,
       REMOVE_REASON_CODE  = :REMOVE_REASON_CODE,
       REMARK              = :REMARK
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)