SELECT B.USER_ID
  FROM TF_F_USER B, TF_F_CUSTOMER C
 WHERE 1 = 1
   AND B.REMOVE_TAG='0'
   AND C.REMOVE_TAG='0'
   AND B.CUST_ID = C.CUST_ID
   AND C.IS_REAL_NAME='1'
   AND C.PSPT_ID = :PSPT_ID
   AND C.PARTITION_ID = MOD(TO_NUMBER(B.CUST_ID), 10000)