SELECT UU.PARTITION_ID,
       TO_CHAR(UU.USER_ID_A) USER_ID_A,
       TO_CHAR(UU.USER_ID_B) USER_ID_B,
       UU.RELATION_TYPE_CODE,
       UU.ROLE_CODE_A,
       UU.ROLE_CODE_B,
       UU.ORDERNO,
       UU.SHORT_CODE,
       TO_CHAR(UU.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(UU.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       UU.SERIAL_NUMBER_A,
       UU.SERIAL_NUMBER_B,
       U.PARTITION_ID,
       TO_CHAR(U.USER_ID) USER_ID,
       TO_CHAR(U.CUST_ID) CUST_ID,
       TO_CHAR(U.USECUST_ID) USECUST_ID,
       U.EPARCHY_CODE,
       U.CITY_CODE,
       U.USER_PASSWD,
       U.USER_TYPE_CODE,
       U.SERIAL_NUMBER,
       U.ACCT_TAG,
       U.PREPAY_TAG,
       TO_CHAR(U.IN_DATE, 'YYYY-MM-DD HH24:MI:SS') IN_DATE,
       TO_CHAR(U.OPEN_DATE, 'YYYY-MM-DD HH24:MI:SS') OPEN_DATE,
       U.REMOVE_TAG,
       TO_CHAR(U.DESTROY_TIME, 'YYYY-MM-DD HH24:MI:SS') DESTROY_TIME,
       TO_CHAR(U.PRE_DESTROY_TIME, 'YYYY-MM-DD HH24:MI:SS') PRE_DESTROY_TIME,
       TO_CHAR(U.FIRST_CALL_TIME, 'YYYY-MM-DD HH24:MI:SS') FIRST_CALL_TIME,
       TO_CHAR(U.LAST_STOP_TIME, 'YYYY-MM-DD HH24:MI:SS') LAST_STOP_TIME,
       U.OPEN_MODE,
       U.USER_STATE_CODESET,
       U.MPUTE_MONTH_FEE,
       TO_CHAR(U.MPUTE_DATE, 'YYYY-MM-DD HH24:MI:SS') MPUTE_DATE,
       U.RSRV_STR1,
       U.RSRV_STR2,
       U.RSRV_STR3,
       U.RSRV_STR4,
       U.RSRV_STR5,
       U.RSRV_STR6,
       U.RSRV_STR7,
       U.RSRV_STR8,
       U.RSRV_STR9,
       U.RSRV_STR10,
       TO_CHAR(U.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME
  FROM TF_F_RELATION_UU UU, TF_F_USER U
 WHERE 1 = 1
   AND U.CUST_ID = TO_NUMBER(:CUST_ID)
   AND U.REMOVE_TAG = '0'
   AND UU.USER_ID_A = U.USER_ID
   AND U.PARTITION_ID = MOD(:USER_ID_A,10000)
   AND UU.USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND UU.USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND UU.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND SYSDATE BETWEEN UU.START_DATE AND UU.END_DATE
