SELECT A.PARTITION_ID, A.USER_ID, A.CUST_ID, A.SERIAL_NUMBER, A.CITY_CODE,
       A.OPEN_DEPART_ID, A.OPEN_STAFF_ID, A.OPEN_DATE, P.PRODUCT_ID, C.CUST_NAME
  FROM TF_F_USER A, TF_F_USER_RES B, TF_F_USER_PRODUCT P, TF_F_CUSTOMER C
 WHERE A.OPEN_DATE > TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss')
   AND A.OPEN_DATE < TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
   AND A.REMOVE_TAG = '0'
   AND A.OPEN_MODE = '0'
   AND A.USER_ID = B.USER_ID
   AND B.RES_TYPE_CODE = '0'
   AND B.RES_CODE = A.SERIAL_NUMBER
   AND B.RSRV_TAG2 = '1'
   AND B.END_DATE > SYSDATE
   AND A.USER_ID = P.USER_ID
   AND SYSDATE BETWEEN P.START_DATE AND P.END_DATE
   AND P.MAIN_TAG = '1'
   AND A.CUST_ID = C.CUST_ID
   AND C.PARTITION_ID = MOD(A.CUST_ID, 10000)
   AND A.PARTITION_ID = B.PARTITION_ID
   AND A.PARTITION_ID = P.PARTITION_ID
