SELECT TO_CHAR(A.USER_ID) USER_ID,
       TO_CHAR(A.CUST_ID) CUST_ID,
       A.USER_PASSWD,
       B.PSPT_TYPE_CODE RSRV_STR1,
       B.PSPT_ID RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_STR6,
       A.RSRV_STR7,
       A.RSRV_STR8,
       A.RSRV_STR9,
       A.RSRV_STR10
  FROM TF_F_USER A, TF_F_CUSTOMER B
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND ((:TRADE_TYPE_CODE != 191 AND A.REMOVE_TAG = '0') OR
       (:TRADE_TYPE_CODE = 191 AND A.REMOVE_TAG = '1'))
   AND A.CUST_ID = B.CUST_ID
   AND b.partition_id = MOD(a.cust_id,10000)