SELECT 
    TO_CHAR(A.USER_ID) USER_ID,
    TO_CHAR(A.CUST_ID) CUST_ID,
    A.SERIAL_NUMBER,
    A.REMOVE_TAG,
	A.USER_STATE_CODESET
    FROM TF_F_USER A, TF_F_USER_PRODUCT P
    WHERE 1=1
    AND A.REMOVE_TAG = '0'
    AND A.PARTITION_ID = MOD(A.USER_ID,10000)
    AND A.USER_ID = P.USER_ID
    AND P.BRAND_CODE IN ('G001','G002','G010')
    AND (SYSDATE BETWEEN P.START_DATE AND P.END_DATE)
    AND A.CUST_ID IN
    (
        SELECT C.CUST_ID 
		FROM TF_F_CUSTOMER C 
		WHERE C.PSPT_ID=:PSPT_ID
		AND C.REMOVE_TAG='0'
		AND C.PARTITION_ID = MOD(C.CUST_ID,10000)
    )