SELECT A.USER_ID,
	 A.CUST_ID,
	 B.BRAND_CODE,
	 A.USER_STATE_CODESET,
	 A.CITY_CODE,
	 A.USER_TYPE_CODE,
	 A.EPARCHY_CODE,
	 B.PRODUCT_ID
FROM TF_F_USER A, TF_F_USER_PRODUCT B
WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
 AND A.USER_ID = B.USER_ID
 AND A.PARTITION_ID = B.PARTITION_ID
 AND A.PARTITION_ID = MOD(B.USER_ID, 10000)
 AND A.REMOVE_TAG = '0'
 AND A.OPEN_DATE < TO_DATE(:OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss')
 AND B.BRAND_CODE IN ('G001', 'G002', 'G010')
 AND A.USER_TYPE_CODE NOT IN ('A', 'a')
 AND B.MAIN_TAG = '1'
 AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
