SELECT SUM(REAL_COUNT) REAL_COUNT
  FROM (SELECT COUNT(DISTINCT U.USER_ID) REAL_COUNT
          FROM TF_F_USER U, TF_F_CUST_PERSON C
         WHERE U.CUST_ID = C.CUST_ID
           AND C.PARTITION_ID = MOD(U.CUST_ID, 10000)
           AND U.REMOVE_TAG = '0'
           AND U.RSRV_TAG1 = 'N'
           AND C.PSPT_ID = :PSPT_ID
           AND C.REMOVE_TAG = '0'
        UNION ALL
        SELECT COUNT(DISTINCT U.USER_ID) REAL_COUNT
          FROM TF_F_USER U, TF_F_CUST_PERSON C
         WHERE U.CUST_ID = C.CUST_ID
           AND C.PARTITION_ID = MOD(U.CUST_ID, 10000)
           AND U.REMOVE_TAG = '0'
           AND (U.RSRV_TAG1 <> 'N' OR U.RSRV_TAG1 IS NULL)
           AND U.SERIAL_NUMBER LIKE 'KD_1%'
           AND C.PSPT_ID = :PSPT_ID
           AND C.REMOVE_TAG = '0')