SELECT /*+ index(b IDX_TF_F_CUSTOMER_CUSTNAME)*/ 
	   A.CITY_CODE,
       A.SERIAL_NUMBER SERIAL_NUMBER,
       B.CUST_NAME CUST_NAME,
       DECODE(A.REMOVE_TAG, '4', '欠费销号', '0', '欠费停机', '未知') REMOVE_TAG,
       TO_CHAR(A.DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME
FROM TF_F_USER A, TF_F_CUSTOMER B
WHERE A.CUST_ID = B.CUST_ID
   AND (A.REMOVE_TAG IN  ('4','0') )
   AND (INSTR(A.USER_STATE_CODESET, '9', 1) > 0 OR INSTR(A.USER_STATE_CODESET, '5', 1) > 0)
   AND B.CUST_NAME = :CUST_NAME 
   AND B.PSPT_ID = :PSPT_ID
   AND B.PSPT_TYPE_CODE = :PSPT_KIND