SELECT A.PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       TO_CHAR(A.CUST_ID) CUST_ID,
       TO_CHAR(USECUST_ID) USECUST_ID,
       BRAND_CODE,
       PRODUCT_ID,
       A.EPARCHY_CODE,
       A.CITY_CODE,
       USER_PASSWD,
       USER_TYPE_CODE,
       SERIAL_NUMBER,
       TO_CHAR(A.SCORE_VALUE) SCORE_VALUE,
       A.CREDIT_CLASS,
       TO_CHAR(A.BASIC_CREDIT_VALUE) BASIC_CREDIT_VALUE,
       TO_CHAR(A.CREDIT_VALUE) CREDIT_VALUE,
       ACCT_TAG,
       PREPAY_TAG,
       TO_CHAR(A.IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE,
       TO_CHAR(OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       A.REMOVE_TAG,
       TO_CHAR(A.DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME,
       TO_CHAR(PRE_DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') PRE_DESTROY_TIME,
       TO_CHAR(FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       TO_CHAR(LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,
       OPEN_MODE,
       USER_STATE_CODESET,
       MPUTE_MONTH_FEE,
       TO_CHAR(MPUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') MPUTE_DATE,
       C.CUST_NAME CUST_NAME,
       A.DEVELOP_STAFF_ID
FROM TF_F_USER A, TF_F_CUSTOMER C
WHERE A.CUST_ID = C.CUST_ID
   AND A.REMOVE_TAG = '0'
   AND (A.CITY_CODE = :CITY_CODE OR :CITY_CODE IS NULL)
   AND OPEN_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
       TO_DATE(:END_DATE, 'yyyy-mm-dd')
   AND A.DEVELOP_STAFF_ID BETWEEN :START_STAFF_ID AND :END_STAFF_ID