SELECT /*+INDEX(p IDX_TF_F_USER_PRODUCT_U)*/ U.SERIAL_NUMBER,
       DECODE(U.ACCT_TAG, 0, '已激活', '未激活') ACCT_TAG,
       P.PRODUCT_ID
  FROM TF_F_USER U, TF_F_USER_PRODUCT P
 WHERE 1 = 1
   AND U.USER_ID = P.USER_ID
   AND U.REMOVE_TAG = '0'
   AND P.MAIN_TAG = 1
   AND SYSDATE BETWEEN P.START_DATE AND P.END_DATE
   AND EXISTS (SELECT 1 FROM TF_F_USER_QUERY_IMPORT I WHERE U.SERIAL_NUMBER = I.SERIAL_NUMBER)
   AND U.SERIAL_NUMBER >= :START_SERIALNUMBER
   AND U.SERIAL_NUMBER <= :END_SERIALNUMBER