SELECT A.USER_ID,
       A.SERIAL_NUMBER,
       A.PRODUCT_ID,
       A.BRAND_CODE,
       A.EPARCHY_CODE,
       A.CITY_CODE,
       A.NET_TYPE_CODE,
       A.REMOVE_TAG,
       A.USER_STATE_CODESET,
       A.IN_DATE,
       A.OPEN_DATE,
       B.CUST_ID,
       B.CUST_NAME,
       B.CUST_TYPE,
       B.PSPT_TYPE_CODE,
       B.PSPT_ID,
       '' SERIAL_NUMBER_BAK,
       '' STAND_ADDRESS,
       '' DETAIL_ADDRESS
  FROM TF_F_USER A, TF_F_CUSTOMER B
 WHERE A.USER_ID = :USER_ID
   AND A.CUST_ID = B.CUST_ID
   AND A.NET_TYPE_CODE = '00'
   AND A.REMOVE_TAG = '0'
   AND B.CUST_TYPE = '0'
   AND B.REMOVE_TAG = '0'
UNION ALL
SELECT A.USER_ID,
       A.SERIAL_NUMBER AS SERIAL_NUMBER,
       A.PRODUCT_ID,
       A.BRAND_CODE,
       A.EPARCHY_CODE,
       A.CITY_CODE,
       A.NET_TYPE_CODE,
       A.REMOVE_TAG,
       A.USER_STATE_CODESET,
       A.IN_DATE,
       A.OPEN_DATE,
       B.CUST_ID,
       B.CUST_NAME,
       B.CUST_TYPE,
       B.PSPT_TYPE_CODE,
       B.PSPT_ID,
       A.SERIAL_NUMBER SERIAL_NUMBER_BAK,
       E.STAND_ADDRESS,
       E.DETAIL_ADDRESS
  FROM TF_F_USER             A,
       TF_F_CUSTOMER         B,
       TF_F_USER_WIDENET     E
 WHERE A.USER_ID = :USER_ID
   AND A.CUST_ID = B.CUST_ID
   AND A.USER_ID = E.USER_ID(+)
   AND A.NET_TYPE_CODE = '04'
   AND A.REMOVE_TAG = '0'
   AND B.CUST_TYPE = '0'
   AND B.REMOVE_TAG = '0'