UPDATE TF_F_USER_TRUNK T
   SET T.END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS') -
                    1 / 24 / 3600
 WHERE T.TRUNK_ID = TO_NUMBER(:RSRV_STR1)
   AND T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.END_DATE > SYSDATE