UPDATE TF_F_USER
   SET USECUST_ID        = TO_NUMBER(:USECUST_ID),
       USER_TYPE_CODE    = :USER_TYPE_CODE,
       ASSURE_CUST_ID    = TO_NUMBER(:ASSURE_CUST_ID),
       ASSURE_TYPE_CODE  = :ASSURE_TYPE_CODE,
       ASSURE_DATE       = TO_DATE(:ASSURE_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       DEVELOP_DEPART_ID = :DEVELOP_DEPART_ID,
       DEVELOP_STAFF_ID  = :DEVELOP_STAFF_ID,
       DEVELOP_NO        = :DEVELOP_NO,
       REMARK            = :REMARK,
       RSRV_TAG1         = :RSRV_TAG1,
       RSRV_TAG2         = :RSRV_TAG2
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)