UPDATE TF_F_USER
   SET CUST_ID    = :CUST_ID,
       USECUST_ID = :USECUST_ID,
       SERIAL_NUMBER = :SERIAL_NUMBER
 WHERE (PARTITION_ID, USER_ID) IN
       (SELECT MOD(USER_ID_A, 10000), USER_ID_A
          FROM TF_B_TRADE_RELATION A
         WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
           AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)))