UPDATE TF_F_USER_TRUNK T
   SET T.USER_ID     = TO_NUMBER(:USER_ID_A),
       T.UPDATE_TIME = SYSDATE,
       T.REMARK      = '修改USER_ID'
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.END_DATE > SYSDATE