UPDATE TF_F_USER_FAMILY_CIRCLE T SET T.STATUS = :STATUS,T.START_DATE = SYSDATE 
,T.END_DATE = to_date('20501230235959','YYYYMMDDHH24MISS'),T.TARGET_NAME = :TARGET_NAME 
WHERE T.GROUP_TYPE = :GROUP_TYPE AND T.MAIN_MSISDN = :MAIN_MSISDN AND 
T.TARGET_MSISDN = :TARGET_MSISDN
