SELECT T.ASYN_ID,
       T.BUSIFORM_ID,
       T.ACCEPT_MONTH,
       T.BUSIFORM_NODE_ID,
       T.NODE_ID,
       T.BI_SN,
       T.SUB_BI_SN,
       T.ATTR_CODE,
       T.VALID_TAG,
       T.ATTR_VALUE,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.REMARK,
       T.EPARCHY_CODE,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TF_B_EWE_ASYN T
 WHERE T.BUSIFORM_ID = :BUSIFORM_ID
   AND T.NODE_ID = :NODE_ID
   AND T.ATTR_CODE = :ATTR_CODE
   AND T.ATTR_VALUE = :ATTR_VALUE