UPDATE TF_B_NOTEPRINTLOG 
SET CANCEL_TAG='1',CANCEL_TIME=TO_DATE(:CANCEL_TIME,'YYYY-MM-DD HH24:MI:SS'),
    CANCEL_STAFF_ID=:CANCEL_STAFF_ID,CANCEL_DEPART_ID=:CANCEL_DEPART_ID,
    CANCEL_CITY_CODE=:CANCEL_CITY_CODE,CANCEL_EPARCHY_CODE=:CANCEL_EPARCHY_CODE,
    CANCEL_REASON_CODE=TO_NUMBER(:CANCEL_REASON_CODE)
WHERE TRADE_ID=to_number(:TRADE_ID)