--IS_CACHE=N
SELECT SUBSYS_CODE,
       PARAM_ATTR,
       PARAM_CODE,
       PARAM_NAME,
       PARA_CODE1,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       EPARCHY_CODE,
       REMARK,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TD_S_COMMPARA
 WHERE SUBSYS_CODE = :SUBSYS_CODE
   AND PARAM_ATTR = :PARAM_ATTR
   AND (PARAM_CODE = :PARAM_CODE OR 'HAIN' = :PARAM_CODE)
   AND SYSDATE BETWEEN START_DATE AND END_DATE
   AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE = 'ZZZZ')