INSERT INTO TF_F_USER_ELEMENT(PARTITION_ID,USER_ID,PRODUCT_ID,PACKAGE_ID,ELEMENT_TYPE_CODE,ELEMENT_ID,START_DATE,END_DATE,UPDATE_DEPART_ID,UPDATE_STAFF_ID,UPDATE_TIME)
SELECT MOD(USER_ID,10000),USER_ID,PRODUCT_ID,PACKAGE_ID,ELEMENT_TYPE_CODE,ELEMENT_ID,START_DATE,END_DATE,UPDATE_DEPART_ID,UPDATE_STAFF_ID,UPDATE_TIME
FROM   TF_B_TRADE_ELEMENT a
WHERE  TO_CHAR(TRADE_ID) = :TRADE_ID
AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
AND TO_CHAR(USER_ID) = :USER_ID
AND PRODUCT_ID = :PRODUCT_ID
AND PACKAGE_ID = :PACKAGE_ID
AND ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
AND ELEMENT_ID = :ELEMENT_ID
AND MODIFY_TAG = '0'
AND NOT EXISTS (SELECT 1 FROM TF_F_USER_ELEMENT 
                 WHERE TO_CHAR(USER_ID) = :USER_ID
                 AND   PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
                 AND   PRODUCT_ID = :PRODUCT_ID
                 AND   PACKAGE_ID = :PACKAGE_ID
                 AND   ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
                 AND   ELEMENT_ID  = :ELEMENT_ID
                 AND   END_DATE > START_DATE
                 AND   END_DATE > a.START_DATE)