SELECT A.RECORDID ARRIVAL_ID, A.RECORDID ORDER_ID, 
	A.PURCHASEPROJECTNO PURCHASE_NO, A.ORDERNO ORDER_NO, A.ORDERTYPE ORDER_TYPE, A.VENDORCODE VENDOR_CODE,
    A.PROVINCEID PROVINCE_ID, A.ORDERDATE ORDER_DATE, A.MATERIALCODE MATERIAL_CODE, A.QUANITY QUANTITY,
    A.COLOR COLOR_DESC, A.PRICE PURCHASE_PRICE, '0' ORDER_SRC_FLAG, '1' ORDER_STATE, '0' VALID_TAG
FROM TI_R_ORDERDATA_DOWN A
WHERE 1 = 1
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')