SELECT COUNT(1) AS TOTAL_NUMBER
  FROM (SELECT A.USER_ID
          FROM TF_F_USER A
         WHERE A.SERIAL_NUMBER = 'KD_' || :SERIAL_NUMBER
           AND A.USER_ID = TO_NUMBER(:USER_ID)
           AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
        UNION ALL
        SELECT A.USER_ID
          FROM TF_FH_USER A
         WHERE A.SERIAL_NUMBER = 'KD_' || :SERIAL_NUMBER
           AND A.USER_ID = TO_NUMBER(:USER_ID)
           AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000))