--IS_CACHE=Y
SELECT A.TRADE_TYPE_CODE TRADE_TYPE_CODE,
       A.BRAND_CODE      BRAND_CODE,
       A.PRODUCT_ID      PRODUCT_ID,
       A.SMS_CODE        SMS_CODE,
       A.SMS_TYPE_CODE   SMS_TYPE_CODE,
       A.SMS_CONTENT     SMS_CONTENT,
       A.BILLING_TYPE    BILLING_TYPE,
       A.SMS_INFO        SM_COMMENT,
       A.EPARCHY_CODE    EPARCHY_CODE,
       A.IN_MODE_CODE    IN_MODE_CODE,
       A.BIZ_PRI         BIZ_PRI,
       A.SMS_PROCESS_TAG SMS_PROCESS_TAG,
       A.OPER_CODE       OPER_CODE,
       A.RSRV_STR4       RSRV_STR4,
       A.BIZ_TYPE_CODE   BIZ_TYPE_CODE
  FROM TD_B_PLATSVC_SMS A
 WHERE (A.SERVICE_ID = :SERVICE_ID OR A.SERVICE_ID = '-1')
   AND (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
   AND (A.IN_MODE_CODE = :IN_MODE_CODE OR A.IN_MODE_CODE = 'Q')
   AND (A.BIZ_TYPE_CODE = :BIZ_TYPE_CODE OR A.BIZ_TYPE_CODE = '-1')
   AND A.ORG_DOMAIN = :ORG_DOMAIN
   AND (A.RSRV_STR1 = :SP_CODE OR A.RSRV_STR1 = 'ZZZZ')
   AND (A.RSRV_STR2 = :BIZ_CODE OR A.RSRV_STR2 = 'ZZZZ')
   AND SUBSTR(A.SMS_PROCESS_TAG, 2, 1) = SUBSTR(:SMS_PROCESS_TAG, 2, 1)
   AND (A.OPER_CODE = :OPER_CODE)
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND A.BIZ_PRI =
       (SELECT MAX(B.BIZ_PRI)
          FROM TD_B_PLATSVC_SMS B
         WHERE (B.EPARCHY_CODE = :EPARCHY_CODE OR B.EPARCHY_CODE = 'ZZZZ')
           AND (B.IN_MODE_CODE = :IN_MODE_CODE OR B.IN_MODE_CODE = 'Q')
           AND (B.OPER_CODE = :OPER_CODE)
           AND B.ORG_DOMAIN = :ORG_DOMAIN
   AND (B.RSRV_STR1 = :SP_CODE OR B.RSRV_STR1 = 'ZZZZ')
   AND (B.RSRV_STR2 = :BIZ_CODE OR B.RSRV_STR2 = 'ZZZZ')
           AND SUBSTR(B.SMS_PROCESS_TAG, 2, 1) =
               SUBSTR(:SMS_PROCESS_TAG, 2, 1)
           AND (B.BIZ_TYPE_CODE = :BIZ_TYPE_CODE OR B.BIZ_TYPE_CODE = '-1')
           AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
           AND B.BIZ_PRI <> -1)