SELECT TRANSTYPE, VENDORID VENDOR_ID, VENDORCODE VENDOR_CODE, VENDORNAME VENDOR_NAME, VENDORALIAS VENDOR_ALIAS, 
	ENGLISHNAME ENGLISH_NAME, EPPSYSACCOUNT EPP_SYS_ACCOUNT, REGISTRYNUMBER REGISTRY_NUMBER, REGISTRYADDRESS REGISTRY_ADDRESS, 
	DUNSNUMBER DUNS_NUMBER, OFFICEADDRESS OFFICE_ADDRESS, REGISTRYMONEY REGISTRY_MONEY, COMPANYTYPE COMPANY_TYPE, 
	BUSINESSRANGE BUSINESS_RANGE, MAINPRODUCT MAIN_PRODUCT, BUSINESSTIMELIMIT BUSINESS_TIME_LIMIT,
	BANK BANK, BASEACCOUNT BASE_ACCOUNT, ORGCERTNUMBER ORG_CERT_NUMBER, TAXREGISTRYNUMBER TAX_REGISTRY_NUMBER,
	FICTITIOUSPERSON FICTITIOUS_PERSON, PHONE PHONE, FAX FAX, AUTHORIZEDMOBILEPHONE AUTHORIZED_MOBILEPHONE,
	AUTHORIZEDEMAIL AUTHORIZED_EMAIL, COOPERATESTARTDATE COOPERATE_STARTDATE, ANNUALSURVEYDATE ANNUALSURVEY_DATE,
	NEXTANNUALSURVEYDATE NEXT_ANNUALSURVEY_DATE, REMARK REMARK, ZIPCODE ZIPCODE, WEBSITE WEBSITE, COUNTRY COUNTRY,
	STATE STATE, CITY CITY, STATUS STATUS, VENDORGRADE VENDOR_GRADE, GROUPCODE GROUP_CODE, PARENTCOMPANYCODE PARENT_COMPANY_CODE,
	INITDATASOURCE INIT_DATA_SOURCE, OLDEPPCODE OLD_EPP_CODE, CREATETIME CREATE_TIME, MODIFYTIME MODIFY_TIME,VENDORTYPE VENDOR_TYPE
FROM TI_R_VENDOR_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')