INSERT INTO TF_F_NONBOSSFEE_LOG
  (LOG_ID,                              
   OPER_TYPE_NAME,                      
   OPER_DATE,                           
   OPER_MONTH,                          
   TRADE_STAFF_ID,                      
   TRADE_DEPART_ID,                     
   TRADE_CITY_CODE,                     
   TRADE_EPARCHY_CODE,                  
   PAY_MODE,                            
   PAY_NAME,                            
   PAY_NAME_REMARK,                     
   OPER_FEE,                                     
   REFUND_TAG,                                     
   NOTAX_FEE,                           
   TAX_FEE,                             
   TAX_RATE,                            
   RATE_TYPE,                           
   RSRV_NUM1,                           
   RSRV_STR1,                           
   RSRV_STR2,                           
   RSRV_STR3,                           
   RSRV_STR4,                           
   RSRV_STR5,                           
   RSRV_STR6,                           
   RSRV_STR7,                           
   RSRV_STR8,                           
   RSRV_STR9,                           
   REMARK,                              
   OPER_TYPE_NAME_DESC,                 
   REFUND_LOG_ID)                   		
  SELECT :LOG_ID,                                                         
         L.OPER_TYPE_NAME,
         L.OPER_DATE,
         :OPER_MONTH,
         :TRADE_STAFF_ID,
         :TRADE_DEPART_ID,
         :TRADE_CITY_CODE,
         :TRADE_EPARCHY_CODE,
         L.PAY_MODE,
         L.PAY_NAME,
         L.PAY_NAME_REMARK,
         L.OPER_FEE * -1,                 
         '2',
         L.NOTAX_FEE * (-1),
         L.TAX_FEE * (-1),
         L.TAX_RATE,
         L.RATE_TYPE,
         L.RSRV_NUM1,
         L.RSRV_STR1,
			   L.RSRV_STR2,
			   L.RSRV_STR3,
			   L.RSRV_STR4,
			   L.RSRV_STR5,
			   L.RSRV_STR6,
			   L.RSRV_STR7,
			   sysdate,
			   L.RSRV_STR9,
			   L.REMARK,
			   L.OPER_TYPE_NAME_DESC,
			   L.LOG_ID
    FROM TF_F_NONBOSSFEE_LOG L
   WHERE L.LOG_ID = :REFUND_LOG_ID
