SELECT a.IMPORT_ID,a.SERIAL_NUMBER,a.SP_CODE,a.BIZ_CODE,a.BIZ_TYPE_CODE,a.IMPORT_TIME,a.DEAL_RESULT,a.DEAL_INFO,a.DEAL_TIME,a.TRADE_ID,
b.DATA_TYPE,b.IMPORT_STAFF_ID,b.IMPORT_DEPART_ID,b.REMARK
from TI_B_PLATDATA_BATDEAL a,TI_B_PLATDATA_BAT b
where 1 = 1
AND (a.IMPORT_ID = b.IMPORT_ID)
AND (a.IMPORT_ID =:IMPORT_ID) 
AND (a.DEAL_RESULT =:DEAL_RESULT) 
AND (b.IMPORT_STAFF_ID  =:IMPORT_STAFF_ID)  
AND (b.import_time >=to_date(:IMPORT_DATE_START,'YYYY-MM-DD')) 
AND (b.import_time <=to_date(:IMPORT_DATE_END,'YYYY-MM-DD'))
AND (a.SP_CODE =:SP_CODE) 
AND (a.BIZ_CODE  =:BIZ_CODE)
AND (a.SERIAL_NUMBER  =:SERIAL_NUMBER)