UPDATE tf_f_accountdeposit_trans
   SET money=TO_NUMBER(:MONEY)  
 WHERE  acct_id=TO_NUMBER(:ACCT_ID)
   AND partition_id=MOD(TO_NUMBER(:ACCT_ID),10000)
   AND bcyc_id=:BCYC_ID
   AND deposit_code=:DEPOSIT_CODE
   AND money=TO_NUMBER(:OLD_MONEY)
   AND start_acyc_id=:START_ACYC_ID
   AND end_acyc_id=:END_ACYC_ID