UPDATE TF_F_USER
   SET REMOVE_TAG       = '0',
       DESTROY_TIME     = NULL,
       PRE_DESTROY_TIME = NULL,
       UPDATE_TIME      = SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)