--IS_CACHE=Y
SELECT T.SERVICE_ID OBJ_CODE, T.SERVICE_NAME OBJ_NAME
  FROM TD_B_PLATSVC T
 WHERE 1 = 1
   AND T.END_DATE > SYSDATE
   AND T.BIZ_STATE_CODE='A'
   AND T.BIZ_TYPE_CODE = :BIZ_TYPE_CODE
 ORDER BY T.SERVICE_ID, T.SERVICE_NAME