SELECT A.OPR_SOURCE FROM TF_F_USER_PLATSVC A
       WHERE A.USER_ID=TO_NUMBER(:USER_ID)
       AND  A.SERVICE_ID = :SERVICE_ID
       AND  A.BIZ_STATE_CODE IN ('A','N')
       ORDER BY A.END_DATE DESC