--IS_CACHE=Y
SELECT *
  FROM TD_B_ATTR_BIZ B
 WHERE B.ID = TO_NUMBER(:ID)
   AND B.ID_TYPE = :ID_TYPE
   AND B.ATTR_OBJ = :ATTR_OBJ
   AND B.ATTR_CODE = :ATTR_CODE
   AND B.ATTR_VALUE = :ATTR_VALUE
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE