SELECT A.ATTR_CODE, A.ATTR_VALUE
  FROM TF_F_USER_ATTR A
 WHERE A.PARTITION_ID =MOD(:USER_ID,10000)
       AND A.USER_ID = :USER_ID 
       AND A.RELA_INST_ID = :RELA_INST_ID
       AND A.START_DATE < sysdate
       AND a.END_DATE > sysdate