--IS_CACHE=Y
SELECT A.SERVICE_ID, 
       A.BIZ_TYPE_CODE,
       A.OPER_CODE,
       A.SERVICE_ID_L,
       A.SVC_STATE,
       A.SVC_TYPE,
       A.LIMIT_TYPE,
       A.STATE,
       A.RSRV_STR3
  FROM TD_B_PLATSVC_LIMIT A
 WHERE (A.SERVICE_ID = :SERVICE_ID OR A.SERVICE_ID = '90000000')
   AND A.BIZ_TYPE_CODE = :BIZ_TYPE_CODE 
   AND (A.OPER_CODE = :OPER_CODE OR A.OPER_CODE = 'ZZ')
   AND A.LIMIT_TYPE = '6'