SELECT COUNT(1) AS TOTAL_NUMBER
  FROM TL_B_TRADE_RECORD A
 WHERE A.TRADE_ELEMENT = :TRADE_ELEMENT
   AND A.TRADE_TYPE= '330'
   AND A.ACCEPT_TIME >= TO_DATE(:BEGIN_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND A.ACCEPT_TIME <= TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')