INSERT INTO TI_B_USER_INFOCHANGE (SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,TRADE_TYPE_CODE,RELATION_TRADE_ID,PRODUCT_ID,BRAND_CODE,SERIAL_NUMBER,IMSI,NET_TYPE_CODE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),:MODIFY_TAG,TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,TRADE_TYPE_CODE,RELATION_TRADE_ID,PRODUCT_ID,BRAND_CODE,SERIAL_NUMBER,IMSI,NET_TYPE_CODE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
 FROM TF_F_USER_INFOCHANGE a
 WHERE (PARTITION_ID,USER_ID) in
                (select mod(user_id, 10000),user_id
                 from tf_b_trade_user
                 where trade_id = TO_NUMBER(:TRADE_ID)
                 and accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2)))
 AND NOT EXISTS(select 1 from TI_B_USER_INFOCHANGE
                where sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                AND a.user_id = user_id
                AND a.partition_id = partition_id)