INSERT INTO TF_B_CTRM_PRODUCTINTEREST
  (PID,
   POORDERNUMBER,
   BIZTYPE,
   GOODSID,
   ORDERID,
   CUSTOMERPHONE,
   SERVICECODE,
   SERVICESTATUS,
   RECEIVETIME,
   EFFTIME,
   EXPTIME,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID
)
  SELECT :PID,
		 :POORDERNUMBER,
         :BIZTYPE,
         :GOODSID,
         :ORDERID,
         :CUSTOMERPHONE,
         :SERVICECODE,
         :SERVICESTATUS,
         :RECEIVETIME,
         :EFFTIME,
         :EXPTIME,
         SYSDATE,
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID
    FROM DUAL T
   WHERE 1 = 1
     AND NOT EXISTS (SELECT 1 FROM TF_B_CTRM_PRODUCTINTEREST P WHERE P.PID = :PID)