   SELECT * FROM 
   (SELECT ROW_.*, ROWNUM ROWNUM_ FROM 
   ( SELECT distinct P.OID,P.TID,R.REFUND_ID, R.CHANNEL_ID, R.REFUND_TYPE, RS.RSP_TIME ,RS.REFUND_FEE,RS.RSP_RESULT
   FROM TF_B_CTRM_ORDER_PRODUCT P,TF_B_CTRM_REFUND  R,TF_B_CTRM_REFUND_SUB  RS
   WHERE P.TID = R.TID AND R.TID = RS.TID AND RS.RSRV_STR6='IS_ABILITY_TRANS'
     and exists(SELECT 1 FROM  TF_B_CTRM_TLIST  WHERE distribution ='2' and tid = R.tid) 
     AND P.OID = RS.OID  AND P.STATUS IN ('4', '5') AND RS.RSRV_STR1 IS NULL ) 
	 ROW_ WHERE ROWNUM <= 500) WHERE ROWNUM_ > 0