
update TF_R_GGCARD
   set PROCESS_TAG      = :PROCESS_TAG,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       ITEM_NAME        = :ITEM_NAME,
       GIFT_CODE        = :GIFT_CODE,
       GIFT_NAME        = :GIFT_NAME,
       TERMINAL_CODE    = :TERMINAL_CODE,
       RSRV_DATE1  = TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS')
 WHERE CARD_CODE = SUBSTR(:CARD_CODE,'1','6')
   AND CARD_PASS_WORD = :CARD_PASS_WORD
   AND SYSDATE > START_DATE
   AND SYSDATE < END_DATE
