SELECT
  INFO_ID,
  INFO_TYPE,
  SEND_OBJECT,
  SEND_OBJECT SERIAL_NUMBER,
  TMPL_ID,
  INFO_CONTENT,
  STAFF_ID,
  SEND_STATUS,
  EXE_TIME,
  OPERATE_TIME
FROM TF_B_SEND_INFO
WHERE
  1=1
    AND INFO_TYPE = :INFO_TYPE
  AND SEND_OBJECT = :SERIAL_NUMBER
  AND SEND_OBJECT = :SEND_OBJECT
  AND TMPL_ID = :TMPL_ID
  AND STAFF_ID = :STAFF_ID
	AND SEND_STATUS = :SEND_STATUS
	AND to_char(OPERATE_TIME ,'yyyy-MM-dd') = :OPERATE_TIME