SELECT U.SERIAL_NUMBER, TO_CHAR(R.INST_ID) INST_ID, R.PARTITION_ID,
       TO_CHAR(R.SHARE_ID) SHARE_ID, TO_CHAR(R.USER_ID_B) USER_ID_B,
       R.EPARCHY_CODE, R.ROLE_CODE,
       TO_CHAR(R.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(R.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(R.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       R.UPDATE_STAFF_ID, R.UPDATE_DEPART_ID, R.REMARK, R.RSRV_NUM1, R.RSRV_NUM2,
       R.RSRV_NUM3, R.RSRV_STR1, R.RSRV_STR2, R.RSRV_STR3,
       TO_CHAR(R.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(R.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2, R.RSRV_TAG1,
       R.RSRV_TAG2
  FROM TF_F_USER_SHARE_RELA R, TF_F_USER U
 WHERE R.USER_ID_B = U.USER_ID
   AND U.PARTITION_ID = MOD(R.USER_ID_B, 10000)
   AND R.SHARE_ID = (SELECT MAX(SHARE_ID)
                       FROM TF_F_USER_SHARE_RELA
                      WHERE USER_ID_B = :USER_ID
                        AND PARTITION_ID = MOD(:USER_ID, 10000)
                        AND END_DATE > SYSDATE
                        AND END_DATE > START_DATE)
   AND END_DATE > SYSDATE
   AND END_DATE > START_DATE
