SELECT :SYNC_SEQUENCE SYNC_SEQUENCE, substr(:SYNC_SEQUENCE,7,2) SYNC_DAY, '8' MODIFY_TAG, B.INST_ID, PARTITION_ID,
             B.SHARE_ID, B.SERIAL_NUMBER, B.USER_ID_B, :TRADE_ID TRADE_ID,
             B.EPARCHY_CODE, B.ROLE_CODE, B.START_DATE, B.END_DATE,
             B.UPDATE_TIME, B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK,
             B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_STR1, B.RSRV_STR2,
             B.RSRV_STR3, B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_TAG1, B.RSRV_TAG2
        FROM TF_F_USER_SHARE_RELA B
       WHERE B.SHARE_ID = :SHARE_ID