UPDATE TF_F_RELATION_BANK T
   SET T.END_DATE = SYSDATE
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND T.SUB_ID = :SUB_ID
   AND T.END_DATE >= SYSDATE