SELECT product.PRODUCT_ID,product.MATERIAL_CODE,product.CUSTOMER_TYPE,product.BRAND_DESC,
product.MODEL_DESC,product.RECOMMEND_PRICE,product.MAX_PRICE,price.DEAL_PRICE,price.SALE_PRICE,
price.START_DATE,price.END_DATE,price.VALID_TAG,price.AUDIT_STATUS,price.UPDATE_STAFF_ID,
price.UPDATE_DEPART_ID,price.UPDATE_TIME,price.AUDIT_STAFF_ID,price.AUDIT_DEPART_ID,
price.AUDIT_TIME from  TF_R_PRODUCT_GRP product , TD_R_TERMINAL_PRICE price  
WHERE 1=1 
AND product.MATERIAL_CODE=price.MATERIAL_CODE
AND (:BRAND_CODE IS NULL OR product.BRAND_CODE=:BRAND_CODE)
AND (:CUCTOMER_TYPE IS NULL OR product.CUSTOMER_TYPE=:CUSTOMER_TYPE)
AND (:MODEL_CODE IS NULL OR product.MODEL_CODE=:MODEL_CODE)
AND (:MATERIAL_CODE IS NULL OR product.MATERIAL_CODE=:MATERINAL_CODE)
AND (:AUDIT_STATUS IS NULL OR price.AUDIT_STATUS=:AUDIT_STATUS)
AND (:VALID_TAG IS NULL OR price.VALID_TAG=:VALID_TAG)