--IS_CACHE=Y
SELECT TRADE_TYPE_CODE,
       BRAND_CODE,
       PRODUCT_ID,
       CANCEL_TAG,
       ITEM_INDEX,
       ORDER_NO,
       OBJ_TYPE_CODE,
       OBJ_CODE,
       MODIFY_TAG,
       SEND_DELAY,
       START_DATE,
       END_DATE,
       EPARCHY_CODE,
       IN_MODE_CODE,
       TEMPLATE_ID,
       SMS_TYPE,
       EVENT_TYPE,
       ROLE_CODE
   FROM TD_B_TRADE_SMS T
 WHERE 1 = 1
   AND T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND (T.BRAND_CODE = :BRAND_CODE OR T.BRAND_CODE = 'ZZZZ')
   AND (T.PRODUCT_ID = :PRODUCT_ID OR PRODUCT_ID = '-1')
   AND T.CANCEL_TAG = :CANCEL_TAG
   AND T.EVENT_TYPE = :EVENT_TYPE
   AND (T.EPARCHY_CODE = :EPARCHY_CODE OR T.EPARCHY_CODE = 'ZZZZ')
   AND (INSTR(T.IN_MODE_CODE, ',' || :IN_MODE_CODE || ',', 1, 1) > 0 OR T.IN_MODE_CODE = :IN_MODE_CODE OR T.IN_MODE_CODE = '-1')
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
   ORDER BY order_no,item_index