--IS_CACHE=Y
SELECT TEMPLATE_ID
   FROM TD_B_TRADE_SMS
 WHERE TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND (BRAND_CODE = :BRAND_CODE OR BRAND_CODE = 'ZZZZ')
   AND (PRODUCT_ID = :PRODUCT_ID OR PRODUCT_ID = -1)
   AND (IN_MODE_CODE =:IN_MODE_CODE OR IN_MODE_CODE = '-1')
   AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE = 'ZZZZ')
   AND OBJ_TYPE_CODE = :OBJ_TYPE_CODE
   AND OBJ_CODE = :OBJ_CODE
   AND MODIFY_TAG = :MODIFY_TAG
   AND EVENT_TYPE = 'SecSms'
   AND SYSDATE BETWEEN START_DATE AND END_DATE
 ORDER BY ORDER_NO,ITEM_INDEX
