SELECT to_char(TRADE_ID) TRADE_ID,ACCEPT_MONTH,to_char(USER_ID) USER_ID,SALE_PROJECT_ID,to_char(SIGN_UP,'yyyy-mm-dd hh24:mi:ss') SIGN_UP,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,MODIFY_TAG,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_B_TRADE_SALEPROJECT

 WHERE trade_id=TO_NUMBER(:TRADE_ID)

   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))