WITH PRODUCT_MANAGER AS
 (SELECT T.GROUP_ID,
         T.GROUP_MGR_SN,
         T.PRODUCT_MGR_SN,
         T.PRODUCT_MGR_NAME,
         T.DEPART_NAME,
         T.EMAIL,
         T.PRODUCT_ID,
         T.VALID_TAG
    FROM TF_F_GRP_PRODUCT_MANAGER T)
SELECT PRODUCT_MANAGER.GROUP_ID,
       PRODUCT_MANAGER.GROUP_MGR_SN,
       PRODUCT_MANAGER.PRODUCT_MGR_SN,
       PRODUCT_MANAGER.PRODUCT_MGR_NAME,
       PRODUCT_MANAGER.DEPART_NAME,
       PRODUCT_MANAGER.EMAIL,
       PRODUCT_MANAGER.VALID_TAG,
       SUBSTR(',' || PRODUCT_MANAGER.PRODUCT_ID,
              INSTR(',' || PRODUCT_MANAGER.PRODUCT_ID, ',', 1, TEMP.RN) + 1,
              INSTR(PRODUCT_MANAGER.PRODUCT_ID || ',', ',', 1, TEMP.RN) -
              INSTR(',' || PRODUCT_MANAGER.PRODUCT_ID, ',', 1, TEMP.RN)) PRODUCT_ID
  FROM PRODUCT_MANAGER,
       (SELECT ROWNUM RN FROM DUAL CONNECT BY ROWNUM < 2000) TEMP
 WHERE LENGTH(PRODUCT_MANAGER.PRODUCT_ID) -
       LENGTH(REPLACE(PRODUCT_MANAGER.PRODUCT_ID, ',')) + 1 >= TEMP.RN
       AND GROUP_ID = :GROUP_ID
       AND GROUP_MGR_SN = :GROUP_MGR_SN
       AND VALID_TAG = '0'
 ORDER BY 1, TEMP.RN