UPDATE TF_F_GRP_PRODUCT_MANAGER
   SET VALID_TAG = :VALID_TAG,
   	   UPDATE_DATE = to_date(:UPDATE_DATE, 'yyyy-mm-dd hh24:mi:ss'),
       REMARK =:REMARK
 WHERE GROUP_ID = :GROUP_ID
   AND GROUP_MGR_SN = :GROUP_MGR_SN