--IS_CACHE=Y
SELECT TEMP_ID,SMS_TYPE,SP_CODE,BIZ_CODE,SMS_CONTENT,DEAL_TAG,IMPORT_TIME,FILE_NAME,RSRV_STR4 FROM TD_B_PLATSVC_SMS_TEMP 
WHERE 1=1 
AND  SMS_TYPE=:SMS_TYPE
AND  DEAL_TAG =:DEAL_TAG
AND  TEMP_ID =:TEMP_ID
AND  IMPORT_TIME BETWEEN to_date(:START_DATE,'YYYY-MM-DD') AND TO_DATE(:END_DATE,'YYYY-MM-DD')