--IS_CACHE=Y
select effect_cond_item_code RSRV_NUM1,0 RSRV_NUM2,0 RSRV_NUM3, '' PARA_CODE1,'' PARA_CODE2,'' PARA_CODE3,'' PARA_CODE4,'' PARA_CODE5,'' PARA_CODE6,
'' PARA_CODE7,'' PARA_CODE8,effect_cond_item PARA_CODE9,'SEL_EFFECT_ITEM' CALLING_TYPE_CODE from TD_A_EFFECTCONDITEM