SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(USER_ID_A) USER_ID_A,
       DISCNT_CODE,
       SPEC_TAG,
       RELATION_TYPE_CODE,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') UPDATE_DATE
  FROM TF_F_USER_DISCNT
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND SYSDATE > START_DATE
   AND SYSDATE < END_DATE