UPDATE TF_F_USER_PVPN SET USER_ID_A=TO_NUMBER(:USER_ID_A),SERIAL_NUMBER=:SERIAL_NUMBER,MON_FEE_LIMIT=TO_NUMBER(:MON_FEE_LIMIT),
                          SHORT_CODE=:SHORT_CODE
WHERE USER_ID=TO_NUMBER(:USER_ID)
     AND PARTITION_ID=MOD(TO_NUMBER(:USER_ID),10000)