INSERT INTO TI_B_USER_INFOCHANGE
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         TRADE_TYPE_CODE, RELATION_TRADE_ID, PRODUCT_ID, BRAND_CODE,
         SERIAL_NUMBER, IMSI, NET_TYPE_CODE, START_DATE, END_DATE, UPDATE_TIME,
         INST_ID)
      VALUES
        (:SYNC_SEQUENCE, :SYNC_DAY, '8', :TRADE_ID,
         MOD(:USER_ID, 10000), :USER_ID, :TRADE_TYPE_CODE, :TRADE_ID, -1,
         -1, -1, -1, '00', SYSDATE, SYSDATE - 0.1, SYSDATE,
         :INST_ID)