INSERT INTO TI_B_USER_OCS
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         USER_TYPE_CODE, MONITOR_TYPE, SERIAL_NUMBER, EPARCHY_CODE, STATUS,
         START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID,
         REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5,
         RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1,
         RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, CITY_CODE,
         INST_ID, BIZ_TYPE, MONITOR_FLAG, MONITOR_RULE_CODE)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(A.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               A.TRADE_ID, MOD(A.USER_ID, 10000), A.USER_ID, A.USER_TYPE_CODE,
               A.MONITOR_TYPE, A.SERIAL_NUMBER, A.EPARCHY_CODE, A.STATUS,
               A.START_DATE, A.END_DATE, A.UPDATE_TIME, A.UPDATE_STAFF_ID,
               A.UPDATE_DEPART_ID, A.REMARK, A.RSRV_NUM1, A.RSRV_NUM2,
               A.RSRV_NUM3, A.RSRV_NUM4, A.RSRV_NUM5, A.RSRV_STR1, A.RSRV_STR2,
               A.RSRV_STR3, A.RSRV_STR4, A.RSRV_STR5, A.RSRV_DATE1, A.RSRV_DATE2,
               A.RSRV_DATE3, A.RSRV_TAG1, A.RSRV_TAG2, A.RSRV_TAG3, A.RSRV_STR1,
               A.INST_ID, A.BIZ_TYPE, A.MONITOR_FLAG, A.MONITOR_RULE_CODE
          FROM TF_B_TRADE_OCS A
         WHERE A.TRADE_ID = :TRADE_ID
           AND A.ACCEPT_MONTH = :ACCEPT_MONTH