INSERT INTO TF_B_TRADE_CUSTOMER
(
ACCEPT_MONTH,BASIC_CREDIT_VALUE,CITY_CODE,CREDIT_CLASS,CREDIT_VALUE,CUST_ID,CUST_KIND,CUST_NAME,CUST_PASSWD,CUST_STATE,CUST_TYPE,DEVELOP_DEPART_ID,DEVELOP_STAFF_ID,EPARCHY_CODE,IN_DATE,IN_DEPART_ID,IN_STAFF_ID,OPEN_LIMIT,PSPT_ID,PSPT_TYPE_CODE,REMARK,REMOVE_CHANGE,REMOVE_DATE,REMOVE_STAFF_ID,REMOVE_TAG,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4,RSRV_DATE5,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR10,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,RSRV_TAG4,RSRV_TAG5,SCORE_VALUE,SIMPLE_SPELL,TRADE_ID,UPDATE_DEPART_ID,UPDATE_STAFF_ID,UPDATE_TIME
)
SELECT
TO_NUMBER(SUBSTR(':TRADE_ID',5,2)),BASIC_CREDIT_VALUE,CITY_CODE,CREDIT_CLASS,CREDIT_VALUE,CUST_ID,CUST_KIND,CUST_NAME,CUST_PASSWD,CUST_STATE,CUST_TYPE,DEVELOP_DEPART_ID,DEVELOP_STAFF_ID,EPARCHY_CODE,IN_DATE,IN_DEPART_ID,IN_STAFF_ID,OPEN_LIMIT,PSPT_ID,PSPT_TYPE_CODE,REMARK,:REMOVE_CHANGE,:REMOVE_DATE,:REMOVE_STAFF_ID,:REMOVE_TAG,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4,RSRV_DATE5,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR10,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,RSRV_TAG4,RSRV_TAG5,SCORE_VALUE,SIMPLE_SPELL,:TRADE_ID,UPDATE_DEPART_ID,UPDATE_STAFF_ID,UPDATE_TIME
FROM tf_f_customer A
WHERE CUST_ID = TO_NUMBER(:CUST_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:CUST_ID),10000)
   AND NOT EXISTS (SELECT 1 FROM TF_B_TRADE_CUSTOMER
                    WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
                      AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
                      AND CUST_ID = A.CUST_ID)