--IS_CACHE=Y
SELECT PRODUCT_ID, FORCE_TAG, GIFT_DISCNT_CODE
  FROM TD_B_DEFPRODUCT_CODETYPE
 WHERE CODE_TYPE_CODE = :CODE_TYPE_CODE
   AND SYSDATE BETWEEN START_DATE AND END_DATE
   AND (EPARCHY_CODE = 'ZZZZ' OR EPARCHY_CODE = :TRADE_EPARCHY_CODE)