UPDATE TF_F_PLATVM_OPEN
SET (CLIENT_ID,LOGIN_ID,PASSWORD,USER_NAME,USER_ROLE,PAY_TYPE,USER_STATE,SUB_USER_NUM,SERIAL_NUMBER,IDCARDNUM,EMAIL,LIMIT_TIME,TIME_STAMP,IS_FORBID,START_DATE,END_DATE,REMARK,TRADE_ID,USER_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2)
=(SELECT CLIENT_ID,LOGIN_ID,PASSWORD,USER_NAME,USER_ROLE,PAY_TYPE,USER_STATE,SUB_USER_NUM,SERIAL_NUMBER,IDCARDNUM,EMAIL,LIMIT_TIME,TIME_STAMP,IS_FORBID,START_DATE,END_DATE,REMARK,TRADE_ID,USER_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2 FROM TF_B_TRADE_PLATVM_OPEN WHERE TRADE_ID = :TRADE_ID)
WHERE LOGIN_ID = :LOGIN_ID 
  AND SYSDATE BETWEEN START_DATE AND END_DATE 
  AND USER_STATE <> '2'