UPDATE TF_B_TRADE_RELATION_BANK T
   SET T.RECH_THRESHOLD = TO_NUMBER(:RECH_THRESHOLD),
       T.RECH_AMOUNT = TO_NUMBER(:RECH_AMOUNT),
       T.SUB_ID = :SUB_ID,
       T.SUB_TIME = :SUB_TIME,
       T.ACCOUNT_CAT = :ACCOUNT_CAT,
       T.PAY_TYPE = :PAY_TYPE,
       T.USER_ACCOUNT = :USER_ACCOUNT,
       T.BANK_ID = :BANK_ID
 WHERE TRADE_ID = :TRADE_ID