--IS_CACHE=Y
SELECT A.NAVIGATE_ID,
       A.NAVIGATE_TYPE,
       A.NAVIGATE_KIND,
       A.NAVIGATE_NAME,
       A.NAVIGATE_HINT,
       A.NAVIGATE_DESC
  FROM TD_B_NAVIGATE_DEF A
 WHERE  A.END_DATE>SYSDATE
   AND A.NAVIGATE_ID = :NAVIGATE_ID
   ORDER BY A.UPDATE_TIME ASC