SELECT A.INST_ID,
A.NAVIGATE_ID,
A.INST_STATE NAVIGATE_STATE,
A.USER_ID        ,
A.SERIAL_NUMBER  ,
A.UPDATE_STAFF_ID,
B.FLOW_ID        ,
B.FLOW_ORDER     ,
B.INST_STATE     ,
B.ORDER_ID       ,
B.TRADE_ID       ,
B.EPARCHY_CODE   
FROM TF_B_NAVIGATE_INST A,
(SELECT INST_ID,FLOW_ID,INST_STATE,FLOW_ORDER,ORDER_ID,TRADE_ID,EPARCHY_CODE 
 FROM TF_B_NAVIGATE_FLOW_INST C
 WHERE C.START_DATE = (SELECT MAX(START_DATE) FROM TF_B_NAVIGATE_FLOW_INST D
                       WHERE C.FLOW_ID = D.FLOW_ID
                       AND C.INST_ID = D.INST_ID)
 AND C.INST_ID = :INST_ID
 ) B
WHERE A.INST_ID = B.INST_ID
AND A.INST_ID = :INST_ID