INSERT INTO TI_B_PAYRELATION
          (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
           ACCT_ID, PAYITEM_CODE, ACCT_PRIORITY, USER_PRIORITY, ADDUP_MONTHS,
           ADDUP_METHOD, BIND_TYPE, DEFAULT_TAG, ACT_TAG, LIMIT_TYPE, LIMIT,
           COMPLEMENT_TAG, INST_ID, START_CYCLE_ID, END_CYCLE_ID, UPDATE_TIME,
           UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
           RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8,
           RSRV_STR9, RSRV_STR10)
          SELECT DISTINCT :SYNC_SEQUENCE, :SYNC_DAY, '8', :TRADE_ID,
                          MOD(USER_ID, 10000), A.USER_ID, -1, -1, 0, 0, 0, NULL,
                          '0', '1', '1', '0', '0', '0',
                          :INST_ID,
                          TO_CHAR(SYSDATE, 'YYYYMMDD'),
                          TO_CHAR(SYSDATE - 0.1, 'YYYYMMDD'), SYSDATE, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL
            FROM TF_B_TRADE_PAYRELATION A
           WHERE A.TRADE_ID = :TRADE_ID
             AND A.ACCEPT_MONTH = :ACCEPT_MONTH