INSERT INTO TI_B_ACCOUNT_CONSIGN
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, ACCT_ID,
         INST_ID, PAY_MODE_CODE, EPARCHY_CODE, CITY_CODE, SUPER_BANK_CODE,
         BANK_CODE, BANK_ACCT_NO, BANK_ACCT_NAME, CONTRACT_ID, CONTRACT_NAME,
         CONTACT, CONTACT_PHONE, POST_ADDRESS, POST_CODE, CONSIGN_MODE, PRIORITY,
         PAYMENT_ID, PAY_FEE_MODE_CODE, ASSISTANT_TAG, ACCT_BALANCE_ID, ACT_TAG,
         START_CYCLE_ID, END_CYCLE_ID, UPDATE_STAFF_ID, UPDATE_DEPART_ID,
         UPDATE_TIME, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
         RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8, RSRV_STR9, RSRV_STR10)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               B.TRADE_ID, MOD(B.ACCT_ID, 10000), B.ACCT_ID, INST_ID,
               B.PAY_MODE_CODE, B.EPARCHY_CODE, B.CITY_CODE, B.SUPER_BANK_CODE,
               B.BANK_CODE, B.BANK_ACCT_NO, B.BANK_ACCT_NAME, B.CONTRACT_ID,
               B.CONTRACT_NAME, B.CONTACT, B.CONTACT_PHONE, B.POST_ADDRESS,
               B.POST_CODE, B.CONSIGN_MODE, B.PRIORITY, B.PAYMENT_ID,
               B.PAY_FEE_MODE_CODE, B.ASSISTANT_TAG, B.ACCT_BALANCE_ID,
               B.ACT_TAG, B.START_CYCLE_ID, B.END_CYCLE_ID, B.UPDATE_STAFF_ID,
               B.UPDATE_DEPART_ID, B.UPDATE_TIME, B.REMARK, B.RSRV_STR1,
               B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_STR6,
               B.RSRV_STR7, B.RSRV_STR8, B.RSRV_STR9, B.RSRV_STR10
          FROM TF_B_TRADE_ACCT_CONSIGN B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH