INSERT INTO TI_B_USER_DISCNT
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         USER_ID_A, PRODUCT_ID, PACKAGE_ID, DISCNT_CODE, SPEC_TAG,
         RELATION_TYPE_CODE, INST_ID, CAMPN_ID, START_DATE, END_DATE,
         UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1,
         RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3,
         RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, ID_TYPE)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'), TRADE_ID,
               MOD(USER_ID, 10000), USER_ID, USER_ID_A, '-1', '-1',
               DISCNT_CODE, SPEC_TAG, RELATION_TYPE_CODE, INST_ID, CAMPN_ID,
               START_DATE, END_DATE, UPDATE_TIME, UPDATE_STAFF_ID,
               UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3,
               RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4,
               RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1,
               RSRV_TAG2, RSRV_TAG3, '0'
          FROM TF_B_TRADE_DISCNT
         WHERE TRADE_ID = :TRADE_ID
           AND ACCEPT_MONTH = :ACCEPT_MONTH
           AND MODIFY_TAG IN ('0', '1', '2', 'U')