INSERT INTO TI_B_PAYRELATION
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         ACCT_ID, PAYITEM_CODE, ACCT_PRIORITY, USER_PRIORITY, ADDUP_MONTHS,
         ADDUP_METHOD, BIND_TYPE, DEFAULT_TAG, ACT_TAG, LIMIT_TYPE, LIMIT,
         COMPLEMENT_TAG, INST_ID, START_CYCLE_ID, END_CYCLE_ID, UPDATE_TIME,
         UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8,
         RSRV_STR9, RSRV_STR10)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               B.TRADE_ID, MOD(B.USER_ID, 10000), B.USER_ID, B.ACCT_ID,
               B.PAYITEM_CODE, B.ACCT_PRIORITY, B.USER_PRIORITY, B.ADDUP_MONTHS,
               B.ADDUP_METHOD, B.BIND_TYPE, B.DEFAULT_TAG, B.ACT_TAG,
               B.LIMIT_TYPE, B.LIMIT, B.COMPLEMENT_TAG, B.INST_ID,
               B.START_CYCLE_ID, B.END_CYCLE_ID, B.UPDATE_TIME,
               B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_STR1,
               B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_STR6,
               B.RSRV_STR7, B.RSRV_STR8, B.RSRV_STR9, B.RSRV_STR10
          FROM TF_B_TRADE_PAYRELATION B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH