INSERT INTO TI_B_USER_IMPU
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         INST_ID, TEL_URL, SIP_URL, IMPI, IMS_USER_ID, IMS_PASSWORD, START_DATE,
         END_DATE, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               B.TRADE_ID, MOD(B.USER_ID, 10000), B.USER_ID, B.INST_ID,
               B.TEL_URL, B.SIP_URL, B.IMPI, B.IMS_USER_ID, B.IMS_PASSWORD,
               B.START_DATE, B.END_DATE, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3,
               B.RSRV_STR4, B.RSRV_STR5
          FROM TF_B_TRADE_IMPU B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH