INSERT INTO TI_B_USER_DEFER
      (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
       FEE_MODE, FEE_TYPE_CODE, DEFER_CYCLE_ID, DEFER_ITEM_CODE, MONEY, ACT_TAG,
       UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1,
       RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7,
       RSRV_STR8, RSRV_STR9, RSRV_STR10)
      SELECT :SYNC_SEQUENCE, :SYNC_DAY, '0', :TRADE_ID,
             MOD(USER_ID, 10000), USER_ID, FEE_MODE, FEE_TYPE_CODE,
             DEFER_CYCLE_ID, DEFER_ITEM_CODE, MONEY, ACT_TAG, UPDATE_TIME,
             UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
             RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8,
             RSRV_STR9, RSRV_STR10
        FROM TF_B_TRADEFEE_DEFER
       WHERE TRADE_ID = :TRADE_ID
         AND ACCEPT_MONTH = :ACCEPT_MONTH