INSERT INTO TI_B_INTEGRAL_ACCT
        (SYNC_DAY, SYNC_SEQUENCE, MODIFY_TAG, TRADE_ID, INTEGRAL_ACCT_ID,
         INTEGRAL_ACCOUNT_TYPE, NAME, PARTITION_ID, USER_ID, ACCT_ID, CUST_ID,
         CONTRACT_PHONE, PASSWORD, EMAIL, PSPT_TYPE_CODE, PSPT_ID, ADDRESS,
         USE_LIMIT, START_DATE, END_DATE, STATUS, REMARK, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, RSRV_STR8,
         RSRV_STR9, RSRV_STR10, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4,
         RSRV_NUM5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG3,
         RSRV_TAG2)
        SELECT :SYNC_DAY, :SYNC_SEQUENCE,
               '8', TRADE_ID,
               INTEGRAL_ACCT_ID, INTEGRAL_ACCOUNT_TYPE, NAME,
               MOD(INTEGRAL_ACCT_ID, 10000), USER_ID, ACCT_ID, CUST_ID,
               CONTRACT_PHONE, PASSWORD, EMAIL, PSPT_TYPE_CODE, PSPT_ID, ADDRESS,
               USE_LIMIT, START_DATE, SYSDATE, '10E', REMARK, RSRV_STR1,
               RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7,
               RSRV_STR8, RSRV_STR9, RSRV_STR10, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3,
               RSRV_NUM4, RSRV_NUM5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3,
               RSRV_TAG1, RSRV_TAG3, RSRV_TAG2
          FROM TF_B_TRADE_INTEGRALACCT
         WHERE TRADE_ID = :TRADE_ID
           AND ACCEPT_MONTH = :ACCEPT_MONTH
           AND MODIFY_TAG = '0'