INSERT INTO TI_B_USER_SVC_ATTR
          (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
           RELA_INST_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE,
           END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK,
           RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1,
           RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2,
           RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, SERVICE_ID)
        VALUES
          (:SYNC_SEQUENCE, :SYNC_DAY, '8', :TRADE_ID,
           MOD(:USER_ID, 10000), :USER_ID, 0, 'S',
           :INST_ID, '-1', '-1', SYSDATE,
           SYSDATE - 0.1, SYSDATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
           NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
           NULL, '-1')