INSERT INTO TI_B_USER_SPECIALEPAY
      (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, INST_ID, TRADE_ID, USER_ID,
       USER_ID_A, ACCT_ID, ACCT_ID_B, PAYITEM_CODE, START_CYCLE_ID, END_CYCLE_ID,
       BIND_TYPE, LIMIT_TYPE, LIMIT, COMPLEMENT_TAG, UPDATE_TIME,
       UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2,
       RSRV_STR3, PARTITION_ID)
      SELECT :SYNC_SEQUENCE, :SYNC_DAY,
             DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'), B.INST_ID,
             B.TRADE_ID, B.USER_ID, B.USER_ID_A, B.ACCT_ID, B.ACCT_ID_B,
             B.PAYITEM_CODE, B.START_CYCLE_ID, B.END_CYCLE_ID, B.BIND_TYPE,
             B.LIMIT_TYPE, B.LIMIT, B.COMPLEMENT_TAG, B.UPDATE_TIME,
             B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_STR1,
             B.RSRV_STR2, B.RSRV_STR3, MOD(B.USER_ID, 10000)
        FROM TF_B_TRADE_USER_SPECIALEPAY B
       WHERE B.TRADE_ID = :TRADE_ID
         AND B.ACCEPT_MONTH = :ACCEPT_MONTH