INSERT INTO TI_B_BANK_SUBSIGN
      (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, SIGN_ID, MAIN_USER_TYPE,
       MAIN_USER_VALUE, MAIN_SIGN_TYPE, SUB_USER_TYPE, SUB_USER_VALUE,
       SUB_SIGN_TYPE, MAIN_EPARCHY_CODE, CHNL_TYPE, INST_ID, START_DATE,
       END_DATE, UPDATE_DATE, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK,
       RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5)
      SELECT :SYNC_SEQUENCE, :SYNC_DAY,
             DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'), B.TRADE_ID,
             B.SIGN_ID, B.MAIN_USER_TYPE, B.MAIN_USER_VALUE, B.MAIN_SIGN_TYPE,
             B.SUB_USER_TYPE, B.SUB_USER_VALUE, B.SUB_SIGN_TYPE,
             B.MAIN_EPARCHY_CODE, B.CHNL_TYPE, B.INST_ID, B.START_DATE,
             B.END_DATE, B.UPDATE_DATE, B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID,
             B.REMARK, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4,
             B.RSRV_STR5
        FROM TF_B_TRADE_BANK_SUBSIGN B
       WHERE B.TRADE_ID = :TRADE_ID
         AND ACCEPT_MONTH = :ACCEPT_MONTH