INSERT INTO TI_B_POSTINFO
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, INST_ID, PARTITION_ID,
         ID, ID_TYPE, CUST_TYPE, POST_NAME, POST_TAG, POST_CONTENT, POST_TYPESET,
         POST_CYC, POST_ADDRESS, POST_CODE, EMAIL, FAX_NBR, START_DATE, END_DATE,
         UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1,
         RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2,
         RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3,
         RSRV_TAG1, RSRV_TAG2, RSRV_TAG3)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               B.TRADE_ID, INST_ID, MOD(B.ID, 10000), B.ID, B.ID_TYPE,
               B.CUST_TYPE, B.POST_NAME, B.POST_TAG, B.POST_CONTENT,
               B.POST_TYPESET, B.POST_CYC, B.POST_ADDRESS, B.POST_CODE, B.EMAIL,
               B.FAX_NBR, B.START_DATE, B.END_DATE, B.UPDATE_TIME,
               B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_NUM1,
               B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1,
               B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1,
               B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3
          FROM TF_B_TRADE_POST B
         WHERE B.TRADE_ID = :TRADE_ID
           AND ACCEPT_MONTH = :ACCEPT_MONTH