INSERT INTO TI_B_USER_GRP_MERCH(SYNC_SEQUENCE,SYNC_DAY,MODIFY_TAG ,TRADE_ID ,USER_ID,SERIAL_NUMBER,MERCH_SPEC_CODE,MERCH_ORDER_ID ,MERCH_OFFER_ID ,GROUP_ID ,OPR_SOURCE ,BIZ_MODE ,STATUS ,HOST_COMPANY ,START_DATE ,END_DATE ,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID ,REMARK ,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1 ,RSRV_DATE2 ,RSRV_DATE3 ,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3,INST_ID,ID_TYPE)
SELECT :SYNC_SEQUENCE,:SYNC_DAY,DECODE(A.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),A.TRADE_ID ,A.USER_ID,A.SERIAL_NUMBER,A.MERCH_SPEC_CODE,A.MERCH_ORDER_ID ,A.MERCH_OFFER_ID ,A.GROUP_ID ,A.OPR_SOURCE ,A.BIZ_MODE ,B.SVC_STATUS ,A.HOST_COMPANY ,A.START_DATE ,A.END_DATE ,A.UPDATE_TIME,A.UPDATE_STAFF_ID,A.UPDATE_DEPART_ID ,A.REMARK ,A.RSRV_NUM1,A.RSRV_NUM2,A.RSRV_NUM3,A.RSRV_NUM4,A.RSRV_NUM5,A.RSRV_STR1,A.RSRV_STR2,A.RSRV_STR3,A.RSRV_STR4,A.RSRV_STR5,A.RSRV_DATE1 ,A.RSRV_DATE2 ,A.RSRV_DATE3,A.RSRV_TAG1,A.RSRV_TAG2,A.RSRV_TAG3,A.INST_ID,'0' 
FROM TF_B_TRADE_ECRECEP_OFFER A,TF_B_TRADE_ECRECEP_PROCEDURE B
WHERE A.TRADE_ID=B.TRADE_ID
AND A.ACCEPT_MONTH=B.ACCEPT_MONTH
AND A.TRADE_ID = :TRADE_ID
AND A.ACCEPT_MONTH = :ACCEPT_MONTH