INSERT INTO TI_B_USER_DISCNT_ATTR
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID, USER_ID,
         RELA_INST_ID, INST_TYPE, INST_ID, ATTR_CODE, ATTR_VALUE, START_DATE,
         END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK,
         RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1,
         RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2,
         RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3, DISCNT_CODE, ID_TYPE)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(B.MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
         B.TRADE_ID, MOD(B.USER_ID, 10000), B.USER_ID, B.RELA_INST_ID,
               B.INST_TYPE, B.INST_ID, DECODE(B.ATTR_CODE, 'Discount', '9980168','BottomPrice', '9980169', B.ATTR_CODE) ATTR_CODE, DECODE(B.ATTR_CODE,'BottomPrice',TO_CHAR((B.ATTR_VALUE) * 100),B.ATTR_VALUE) ATTR_VALUE, B.START_DATE,
               B.END_DATE, B.UPDATE_TIME, B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID,
               B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4,
               B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4,
               B.RSRV_STR5, B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3,
               B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3, B.ELEMENT_ID, '0'
          FROM TF_B_TRADE_ATTR B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH
           AND B.INST_TYPE = 'D'
           AND B.ATTR_VALUE IS NOT NULL
           AND B.MODIFY_TAG IN ('0', '1', '2', 'U')
		   AND NOT EXISTS (
		    SELECT T.PARA_CODE1
				FROM TD_S_COMMPARA T
				WHERE T.SUBSYS_CODE = 'CSM'
					AND T.PARAM_ATTR = '3994'
					AND T.PARAM_CODE = 'FILTERWLWATTRCODE'
					AND T.PARA_CODE1 = B.ATTR_CODE )