SELECT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY,
               '8' MODIFY_TAG, B.TRADE_ID,
               B.USER_ID, B.SERIAL_NUMBER, B.SERV_TYPE, B.STATE_CODE,
               B.START_DATE, B.END_DATE, B.UPDATE_DATE, B.REMARK, B.RSRV_STR1,
               B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1,
               B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3,
               B.ACCEPT_MONTH
          FROM TL_F_USER_SERTRACK_LOG B
         WHERE B.TRADE_ID = :TRADE_ID
           AND B.ACCEPT_MONTH = :ACCEPT_MONTH
		   AND B.END_DATE > TRUNC(SYSDATE) - 60