SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, :TRADE_ID TRADE_ID,
                        B.PARTITION_ID, B.USER_ID, B.RELA_INST_ID, B.INST_TYPE,
                        B.INST_ID, B.ATTR_CODE, B.ATTR_VALUE, B.START_DATE,
                        B.END_DATE, B.UPDATE_TIME, B.UPDATE_STAFF_ID,
                        B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2,
                        B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1,
                        B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5,
                        B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1,
                        B.RSRV_TAG2, B.RSRV_TAG3, B.ELEMENT_ID SERVICE_ID
          FROM TF_F_USER_ATTR B
         WHERE B.USER_ID = :USER_ID
           AND B.PARTITION_ID = MOD(:USER_ID, 10000)
           AND B.INST_TYPE = 'Z'
           AND B.ATTR_VALUE IS NOT NULL