SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, :TRADE_ID TRADE_ID,
                        B.PARTITION_ID, B.USER_ID, B.ACCT_DAY, B.CHG_TYPE,
                        B.CHG_MODE, B.CHG_DATE, B.FIRST_DATE, B.INST_ID,
                        B.START_DATE, B.END_DATE, B.UPDATE_TIME,
                        B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK,
                        B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4,
                        B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3,
                        B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1, B.RSRV_DATE2,
                        B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2, B.RSRV_TAG3
          FROM TF_F_USER_ACCTDAY B
         WHERE B.USER_ID = :USER_ID
           AND B.PARTITION_ID = MOD(:USER_ID, 10000)
           AND EXISTS(SELECT 1 FROM TF_F_USER_PRODUCT P WHERE B.USER_ID = P.USER_ID AND P.PARTITION_ID = B.PARTITION_ID AND P.MAIN_TAG = '1')