SELECT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, A.RSRV_TAG3 MODIFY_TAG, :TRADE_ID TRADE_ID,
               MOD(A.USER_ID, 10000) PARTITION_ID, A.USER_ID, A.PRODUCT_ID, A.PACKAGE_ID,
               A.SERVICE_ID, :SERIAL_NUMBER SERIAL_NUMBER, A.BIZ_STATE_CODE,
               --PRODUCT_NO,
               A.OPER_CODE, A.OPR_SOURCE,
               A.FIRST_DATE, A.FIRST_DATE_MON, A.GIFT_SERIAL_NUMBER,
               A.GIFT_USER_ID, A.SUBSCRIBE_ID, A.START_DATE, A.END_DATE,
               A.UPDATE_TIME, A.UPDATE_STAFF_ID, A.UPDATE_DEPART_ID, A.REMARK,
               A.RSRV_NUM1, A.RSRV_NUM2, A.RSRV_NUM3, A.RSRV_NUM4, A.RSRV_NUM5,
               A.RSRV_STR1, A.RSRV_STR2, A.RSRV_STR3, A.RSRV_STR4, A.RSRV_STR5,
               A.RSRV_STR6, A.RSRV_STR7, A.RSRV_STR8, A.RSRV_STR9, A.RSRV_STR10,
               A.RSRV_DATE1, A.RSRV_DATE2, A.RSRV_DATE3, A.RSRV_TAG1,
               A.RSRV_TAG2, A.RSRV_TAG3, A.INST_ID
          FROM TF_F_USER_PLATSVC_TRACE A
         WHERE A.SERVICE_ID NOT IN
               (98008003, 98008004, 98008005, 98008013, 98009044)
           AND A.SUBSCRIBE_ID = :TRADE_ID
           AND A.USER_ID = :USER_ID
           AND A.PARTITION_ID = MOD(:USER_ID, 10000)