SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, :TRADE_ID TRADE_ID,
                        B.PARTITION_ID, B.USER_ID, B.RELA_INST_ID, B.INST_TYPE,
                        B.INST_ID, DECODE(B.ATTR_CODE, 'Discount', '9980168','BottomPrice', '9980169', B.ATTR_CODE) ATTR_CODE, DECODE(B.ATTR_CODE,'BottomPrice',TO_CHAR((B.ATTR_VALUE) * 100),B.ATTR_VALUE) ATTR_VALUE, B.START_DATE,
                        B.END_DATE, B.UPDATE_TIME, B.UPDATE_STAFF_ID,
                        B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2,
                        B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1,
                        B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5,
                        B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1,
                        B.RSRV_TAG2, B.RSRV_TAG3, B.ELEMENT_ID DISCNT_CODE, '0' ID_TYPE
          FROM TF_F_USER_ATTR B
         WHERE B.USER_ID = :USER_ID
           AND B.PARTITION_ID = MOD(:USER_ID, 10000)
           AND B.INST_TYPE = 'D'
           AND B.ATTR_VALUE IS NOT NULL
		   AND NOT EXISTS (
		    SELECT T.PARA_CODE1
				FROM TD_S_COMMPARA T
				WHERE T.SUBSYS_CODE = 'CSM'
					AND T.PARAM_ATTR = '3994'
					AND T.PARAM_CODE = 'FILTERWLWATTRCODE'
					AND T.PARA_CODE1 = B.ATTR_CODE )