SELECT DISTINCT A.USER_ID, C.BRAND_CODE, C.PRODUCT_ID
FROM TF_B_TRADE_USER A, TF_B_TRADE_PRODUCT C
WHERE A.TRADE_ID = :TRADE_ID
AND A.ACCEPT_MONTH = :ACCEPT_MONTH
AND A.USER_ID = C.USER_ID
AND C.MAIN_TAG = '1'
AND C.TRADE_ID = :TRADE_ID