SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID, B.PARTITION_ID, B.USER_ID_A, B.SERIAL_NUMBER_A,
		B.USER_ID_B, B.SERIAL_NUMBER_B, B.RELATION_TYPE_CODE,
		B.ROLE_TYPE_CODE, B.ROLE_CODE_A, B.ROLE_CODE_B,
		B.ORDERNO, B.SHORT_CODE, B.INST_ID, B.START_DATE,
		B.END_DATE, B.UPDATE_TIME, B.UPDATE_STAFF_ID,
		B.UPDATE_DEPART_ID, B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2,
		B.RSRV_NUM3, B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1,
		B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5,
		B.RSRV_DATE1, B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1,
		B.RSRV_TAG2, B.RSRV_TAG3
  FROM TF_F_RELATION_UU B
 WHERE B.USER_ID_B = :USER_ID_B
   AND B.PARTITION_ID = MOD(:USER_ID_B, 10000)