SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID TRADE_ID, B.PARTITION_ID, B.USER_ID, B.USER_ID_A, '-1' PRODUCT_ID, '-1' PACKAGE_ID, B.SERVICE_ID, B.MAIN_TAG, B.INST_ID,
		B.CAMPN_ID, B.START_DATE, B.END_DATE, B.UPDATE_TIME,
		B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK,
		B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3, B.RSRV_NUM4,
		B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3,
		B.RSRV_STR4, B.RSRV_STR5, B.RSRV_STR6, B.RSRV_STR7,
		B.RSRV_STR8, B.RSRV_STR9, B.RSRV_STR10, B.RSRV_DATE1,
		B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2,
		B.RSRV_TAG3
	FROM TF_F_USER_SVC B
	WHERE B.USER_ID = :USER_ID
	AND B.PARTITION_ID = MOD(:USER_ID, 10000)