SELECT :SYNC_SEQUENCE SYNC_SEQUENCE,'8' MODIFY_TAG, RELATION_TRADE_ID TRADE_ID, A.PARTITION_ID,
             A.USER_ID, A.TRADE_TYPE_CODE, A.RELATION_TRADE_ID, A.PRODUCT_ID,
             A.BRAND_CODE, A.SERIAL_NUMBER, A.IMSI, A.NET_TYPE_CODE,
             A.START_DATE, A.END_DATE, A.UPDATE_TIME, A.UPDATE_STAFF_ID,
             A.UPDATE_DEPART_ID, A.REMARK, A.RSRV_NUM1, A.RSRV_NUM2, A.RSRV_NUM3,
             A.RSRV_NUM4, A.RSRV_NUM5, A.RSRV_STR1, A.RSRV_STR2, A.RSRV_STR3,
             A.RSRV_STR4, A.RSRV_STR5, A.RSRV_DATE1, A.RSRV_DATE2, A.RSRV_DATE3,
             A.RSRV_TAG1, A.RSRV_TAG2, A.RSRV_TAG3, A.INST_ID,
			 to_number(substr(:SYNC_SEQUENCE, 7, 2)) SYNC_DAY
        FROM TF_F_USER_INFOCHANGE A
	WHERE A.USER_ID = :USER_ID
	AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
	AND PRODUCT_ID = :PRODUCT_ID
    AND TRADE_TYPE_CODE = '500'
	AND END_DATE > SYSDATE