SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID, B.PARTITION_ID, B.USER_ID, B.ACCT_ID, B.PAYITEM_CODE,
		B.ACCT_PRIORITY, B.USER_PRIORITY, B.ADDUP_MONTHS,
		B.ADDUP_METHOD, B.BIND_TYPE, B.DEFAULT_TAG, B.ACT_TAG,
		B.LIMIT_TYPE, B.LIMIT, B.COMPLEMENT_TAG, B.INST_ID,
		B.START_CYCLE_ID, B.END_CYCLE_ID, B.UPDATE_TIME,
		B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID, B.REMARK,
		B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4,
		B.RSRV_STR5, B.RSRV_STR6, B.RSRV_STR7, B.RSRV_STR8,
		B.RSRV_STR9, B.RSRV_STR10
	FROM TF_A_PAYRELATION B
	WHERE B.USER_ID = :USER_ID
	AND B.PARTITION_ID = MOD(:USER_ID, 10000)