INSERT INTO TF_B_TRADE_OCS(TRADE_ID,ACCEPT_MONTH,INST_ID,USER_ID,USER_TYPE_CODE,MONITOR_TYPE,SERIAL_NUMBER,EPARCHY_CODE,STATUS,BIZ_TYPE,MONITOR_FLAG,MONITOR_RULE_CODE,START_DATE,END_DATE,MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK)
SELECT :TRADE_ID,SUBSTR(:TRADE_ID, 5, 2),'-1',:USER_ID,USER_TYPE_CODE,MONITOR_TYPE,SERIAL_NUMBER,EPARCHY_CODE,STATUS,BIZ_TYPE,:MONITOR_FLAG,MONITOR_RULE_CODE,START_DATE,SYSDATE, :MODIFY_TAG,SYSDATE,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK 
FROM TF_F_USER_OCS
   WHERE USER_ID = TO_NUMBER(:USER_ID)
     AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND  START_DATE < SYSDATE AND
         END_DATE > SYSDATE