UPDATE TF_B_GRP_SCOREDONATE T
   SET T.STATUS = :STATUS, T.DONATE_RESULT = :DONATE_RESULT
 WHERE T.BATCH_ID = :BATCH_ID
   AND T.SERIAL_NUMBER_OUT = :SERIAL_NUMBER_OUT
   AND T.SERIAL_NUMBER_IN = :SERIAL_NUMBER_IN