SELECT TO_CHAR(T.TRADE_ID) TRADE_ID,
       TO_CHAR(T.USER_ID) USER_ID,
       T.TRADE_TYPE_CODE,
       T.NP_SERVICE_TYPE,
       T.SERIAL_NUMBER,
     T.ACCEPT_MONTH,
       T.FLOW_ID,
       T.MESSAGE_ID,
       T.BRC_ID,
       T.MSG_CMD_CODE,
       T.MD5,
       T.PORT_OUT_NETID,
       T.PORT_IN_NETID,
       T.HOME_NETID,
       T.B_NP_CARD_TYPE,
       T.A_NP_CARD_TYPE,
       T.CUST_NAME,
       T.CRED_TYPE,
       T.PSPT_ID,
       T.PHONE,
       T.ACTOR_CUST_NAME,
       T.ACTOR_CRED_TYPE,
       T.ACTOR_PSPT_ID,
       TO_CHAR(T.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
       TO_CHAR(T.NP_START_DATE, 'YYYY-MM-DD HH24:MI:SS') NP_START_DATE,
       TO_CHAR(T.CREATE_TIME, 'YYYY-MM-DD HH24:MI:SS') CREATE_TIME,
       TO_CHAR(T.BOOK_SEND_TIME, 'YYYY-MM-DD HH24:MI:SS') BOOK_SEND_TIME,
       T.SEND_TIMES,
       T.RESULT_CODE,
       T.RESULT_MESSAGE,
       T.ERROR_MESSAGE,
       T.CANCEL_TAG,
       T.STATE,
       T.REMARK,
       T.RSRV_STR1,
       T.RSRV_STR2,
       T.RSRV_STR3,
       T.RSRV_STR4,
       T.RSRV_STR5,
       DECODE(T.RSRV_STR1, '1', '已处理', '未处理') DEALTAG,
       DECODE(T.STATE,
              '000',
              '请求等待发送',
              '009',
              '请求正在发送',
              '011',
              '请求发送失败',
              '020',
              '响应结果-成功',
              '021',
              '响应结果-失败',
              '030',
              '告知结果-成功',
              '031',
              '告知结果-失败',
              '040',
              '生效请求等待发送',
              '041',
              '生效请求发送失败',
              '050',
              '生效响应结果-成功',
              '051',
              '生效响应结果-失败',
              '060',
              '生效告知结果-成功',
              '061',
              '生效告知结果-失败',
              '100',
              '请求/指示正确接受',
              '130',
              '告知结果-成功',
              '131',
              '告知结果-失败',
              '未知') STATE_NAME      
       
  FROM TF_B_TRADE_NP T
 WHERE T.ACCEPT_DATE >= sysdate - :RSRV_NUM1 / 24 / 60
   AND T.CANCEL_TAG = :CANCEL_TAG
   AND T.STATE = :STATE
   AND T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE