UPDATE TD_B_PICTURE_INFO A SET
			CARD_ID = :CARD_ID,
			PIC_NNAME_Z = :PIC_NNAME_Z,
			PIC_NNAME_F = :PIC_NNAME_F,
			PIC_NNAME_R = :PIC_NNAME_R,
			RSRV_TAG1 = :RSRV_TAG1
WHERE 1=1
AND A.TRANSACTION_ID=:TRANSACTION_ID