SELECT TRADE_ID, ACCEPT_MONTH, 
'BBOSS_'||to_char(sysdate,'MMDDhh24mmss') ||:INDEX as ATTR_CODE, 
T.PRODUCT_SPEC_CODE 
FROM TF_B_TRADE_GRP_MERCHP T 
WHERE T.PRODUCT_ORDER_ID = :PRODUCT_ORDER_ID 
and T.TRADE_ID=TO_NUMBER(:TRADE_ID) 
and T.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID, 5,2)) 