SELECT RECORDID, VENDORCODE, PROTECTTYPE, STARTDATE, ENDDATE, REMARK, DEALFLAG, MATERIALCODE
FROM TI_R_PPFORMULA_DOWN
WHERE 1=1
     AND DEALFLAG =:DEALFLAG
     AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')