SELECT ibsysid,apply_type,operateid,resultstatus,to_char(accept_date,'yyyy-mm-dd hh24:mi:ss') accept_date,to_char(replydate,'yyyy-mm-dd hh24:mi:ss') replydate,phonenum,imeinum,terminalid,softwareeditionnum,configureagreement,to_char(begintime,'yyyy-mm-dd hh24:mi:ss') begintime,to_char(endtime,'yyyy-mm-dd hh24:mi:ss') endtime,add_tag,failtype,failreason,trade_eparchy_code,trade_city_code,trade_depart_id,trade_staff_id,cancel_tag,to_char(cancel_time,'yyyy-mm-dd hh24:mi:ss') cancel_time,cancel_eparchy_code,cancel_city_code,cancel_depart_id,cancel_staff_id,rsrv_str1,rsrv_str2,rsrv_str3 
  FROM TI_B_DM_BUSI
 WHERE (:APPLY_TYPE IS NULL OR apply_type=:APPLY_TYPE)
   AND (:OPERATEID IS NULL OR operateid=:OPERATEID)
   AND (:RESULTSTATUS IS NULL OR resultstatus=:RESULTSTATUS)
   AND (:STARTDATE IS NULL OR accept_date>=TO_DATE(:STARTDATE, 'YYYY-MM-DD HH24:MI:SS'))
   AND (:ENDDATE IS NULL OR accept_date<=TO_DATE(:ENDDATE, 'YYYY-MM-DD HH24:MI:SS'))   
   AND (:PHONENUM IS NULL OR phonenum=:PHONENUM)
   AND (:IMEINUM IS NULL OR imeinum=:IMEINUM)
   AND (:BAGID IS NULL OR bagid=:BAGID)
   AND (:TERMINALID IS NULL OR terminalid=:TERMINALID)
   AND (:SOFTWAREEDITIONNUM IS NULL OR softwareeditionnum=:SOFTWAREEDITIONNUM)
   AND (:CONFIGUREAGREEMENT IS NULL OR configureagreement=:CONFIGUREAGREEMENT)
   AND (:FAILTYPE IS NULL OR failtype=:FAILTYPE)
   AND (:TRADE_EPARCHY_CODE IS NULL OR trade_eparchy_code=:TRADE_EPARCHY_CODE)
   AND (:TRADE_CITY_CODE IS NULL OR trade_city_code=:TRADE_CITY_CODE)
   AND (:TRADE_DEPART_ID IS NULL OR trade_depart_id=:TRADE_DEPART_ID)
   AND (:TRADE_STAFF_ID IS NULL OR trade_staff_id=:TRADE_STAFF_ID)
   AND (:ACCOUNTNUM IS NULL OR accountnum=:ACCOUNTNUM)
   AND (:CANCEL_TAG IS NULL OR cancel_tag=:CANCEL_TAG)
   AND (:CANCEL_EPARCHY_CODE IS NULL OR cancel_eparchy_code=:CANCEL_EPARCHY_CODE)
   AND (:CANCEL_CITY_CODE IS NULL OR cancel_city_code=:CANCEL_CITY_CODE)
   AND (:CANCEL_DEPART_ID IS NULL OR cancel_depart_id=:CANCEL_DEPART_ID)
   AND (:CANCEL_STAFF_ID IS NULL OR cancel_staff_id=:CANCEL_STAFF_ID)
   AND (:CANCEL_ACCOUNTNUM IS NULL OR cancel_accountnum=:CANCEL_ACCOUNTNUM)