SELECT A.TRADE_ID,
       A.PARTITION_ID,
       A.USER_ID,
       A.USER_ID_A,
       A.RES_TYPE_CODE,
       A.RES_CODE,
       A.IMSI,
       A.KI,
       A.ARTIFICAL_SERICES_TAG,
       A.RES_FEE,
       A.DEVICE_COST,
       A.PRODUCT_ID,
       A.BASE_PACKAGE,
       A.OPTIONAL_PACKAGE,
       A.RES_BRAND_INFO,
       A.WIDE_NET_ADDRESS,
       A.INST_ID,
       A.START_DATE,
       A.END_DATE,
       A.UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       TO_CHAR(A.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') AS RSRV_DATE1,
       TO_CHAR(A.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') AS RSRV_DATE2,
       TO_CHAR(A.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') AS RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3
  FROM TF_R_TOPSET_ROLLBACK A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)