--IS_CACHE=Y
SELECT DISTINCT B.PARAM_CODE SERVICE_ID, B.PARA_CODE1 ATTR_VALUE,
                B.PARA_CODE2 DISCNT_CODE, B.PARA_CODE3 ATTR_CODE,
                B.PARA_CODE4 RELATED_VALUE, B.PARA_CODE5 IS_NEXTMONTH,
                B.PARA_CODE6 DISCNT_LEVEL, NVL(B.PARA_CODE7, '0') DISCNT_TYPE,
                B.PARA_CODE8 VALID_PERIOD, B.PARA_CODE9 VIP_TYPE_CODES,
                B.PARA_CODE11 IN_MODE_CODES, B.PARA_CODE12 TIME_TYPE,
                B.PARA_CODE13 TIME_VALUE, B.PARA_CODE16 REPLACE_PERIOD,
                B.PARA_CODE17 REPLACE_STAFF_ID, B.PARA_CODE18 NODO_STAFF_ID,
                B.PARA_CODE19 PARA_CODE19, B.PARA_CODE24 PARA_CODE24
  FROM TD_S_COMMPARA B
 WHERE B.PARAM_ATTR = '3700'
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_CODE = :PARAM_CODE
   AND B.PARA_CODE1 = :PARA_CODE1
   AND B.PARA_CODE3 = :PARA_CODE3
   AND B.PARA_CODE4 = :PARA_CODE4
   AND (B.EPARCHY_CODE = 'ZZZZ' OR B.EPARCHY_CODE = :EPARCHY_CODE)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
