--IS_CACHE=N
SELECT NVL(T.FEE, 0) * 0.93 费用
  FROM PM_PRICE_PLAN@DBLK_IUPCDB1 T
 WHERE 1 = 1
   AND T.STATUS = '1'
   AND EXISTS
 (SELECT 1
          FROM TD_S_COMMPARA A
         WHERE A.PARAM_ATTR = 156
           AND A.SUBSYS_CODE = 'CSM'
           AND A.PARAM_CODE = 'CUMU'
           AND T.REF_BILLING_ID = A.PARA_CODE2
           AND A.PARA_CODE1 = :OPER_CODE
           AND (A.EPARCHY_CODE = '0898' OR A.EPARCHY_CODE = 'ZZZZ')
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE)