SELECT T1.TIMER_ID,
       T1.TIMER_TYPE,
       T1.TIMER_OBJECT,
       T1.OFFSET_LOCATION,
       T1.OFFSET_MODE,
       T1.OFFSET_TYPE,
       T1.OFFSET_VALUE,
       T1.OFFSET_EXP,
       T1.OFFSET_EXCLUDE,
       T1.WARN_NUM,
       T1.WARN_CONTENT,
       T1.WARN_SVC,
       T.CONDITION_ID
  FROM TD_B_EWE_NODE_TASK_RELA T, TD_B_EWE_TASK_TIMER T1
 WHERE T.TASK_TYPE = '3'
   AND T1.TIMER_TYPE = :TIMER_TYPE
   AND T.RELA_ID = :RELA_ID
   AND T.TASK_ID = T1.TIMER_ID
   AND T1.VALID_TAG = :VALID_TAG
   AND T.VALID_TAG = :VALID_TAG
