SELECT A.RES_NO,A.RES_NO as TERMINAL_ID,'此终端串号存在于发货记录表' ERROR_REASON,
'如需入库，请删除此串号' PROMPT ,:LOG_ID AS LOG_ID
FROM TF_B_CEN_RES_BATCH_TMP A 
WHERE A.LOG_ID=:LOG_ID 
AND  EXISTS (SELECT 1 FROM TF_R_CEN_TERMINAL_DIS B WHERE  A.res_no=B.terminal_id)