SELECT A.RES_NO ,A.RES_NO as TERMINAL_ID,'此终端串号已于'||TO_CHAR(B.UPDATE_TIME, 'YYYY-MM-DD HH24:MI')||'由'|| B.UPDATE_STAFF_ID ||'入库' ERROR_REASON,
   '如需入库，请先将此终端串号退库处理' PROMPT
   FROM TF_B_CEN_RES_BATCH_TMP A,TD_M_RES_STORE_NOSEQ B 
   WHERE A.LOG_ID = :LOG_ID 
     AND A.RES_NO = B.RES_NO 
     AND B.RES_TYPE_CODE = '4'