SELECT B.CLASS_ID
  FROM TF_F_CUST_GROUPMEMBER A, TF_F_CUST_GROUP B
 WHERE A.GROUP_ID = B.GROUP_ID
   AND A.USER_ID = :USER_ID
   AND A.REMOVE_TAG = '0'
   AND B.REMOVE_TAG = '0'
   AND B.CLASS_ID IN ('5', '6', '7', '8', '9')
   AND B.CUST_ID = :CUST_ID