SELECT T.ASYN_ID,
       T.BUSIFORM_ID,
       T.ACCEPT_MONTH,
       T.BUSIFORM_NODE_ID,
       T.NODE_ID,
       T.STATE,
       T.VALID_TAG,
       T.REMARK,
       T.EPARCHY_CODE,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TF_B_EWE_ASYN T
 WHERE T.BUSIFORM_ID = :BUSIFORM_ID
