INSERT INTO TI_B_USER_IMPU(SYNC_SEQUENCE,MODIFY_TAG,TRADE_ID,PARTITION_ID,USER_ID,TEL_URL,SIP_URL,IMPI,IMS_USER_ID,IMS_PASSWORD,START_DATE,END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5)
 SELECT TO_NUMBER(:SYNC_SEQUENCE),'2',TO_NUMBER(:TRADE_ID),PARTITION_ID,USER_ID,TEL_URL,SIP_URL,IMPI,IMS_USER_ID,IMS_PASSWORD,START_DATE,START_DATE - 1/24/3600,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5
       FROM TF_B_TRADE_IMPU_BAK a
      WHERE a.trade_id = :TRADE_ID
        AND a.accept_month = :ACCEPT_MONTH
        AND NOT EXISTS (SELECT 1 FROM TI_B_USER_IMPU
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.user_id = user_id
                           AND a.start_date=start_date)