SELECT TO_CHAR(TRADE_ID) TRADE_ID, ACCEPT_MONTH, TO_CHAR(USER_ID) USER_ID,PRODUCT_ID, PACKAGE_ID,ELEMENT_TYPE_CODE,ELEMENT_ID,MODIFY_TAG,to_char(start_date,'yyyy-mm-dd hh24:mi:ss') start_date,to_char(end_date,'yyyy-mm-dd hh24:mi:ss') end_date 
FROM TF_B_TRADE_ELEMENT A 
WHERE TO_CHAR(TRADE_ID) = :TRADE_ID
AND   ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
AND   TO_CHAR(USER_ID) = :USER_ID
AND   PRODUCT_ID = :PRODUCT_ID