UPDATE TF_B_TRADE_OTHER
   SET RSRV_TAG1  = :RSRV_TAG1,
       REMARK  = :REMARK,
       RSRV_STR17 = :RSRV_STR17,
       RSRV_STR18 = :RSRV_STR18
 WHERE TRADE_ID = :TRADE_ID
   AND RSRV_VALUE_CODE = :RSRV_VALUE_CODE