SELECT T.TRADE_CITY_CODE,
       T.TRADE_STAFF_ID,
       T.ACCEPT_DATE,
       T.PRODUCT_NAME,
       T.SERIAL_NUMBER,
       T.REMARK,
       TRUNC(TO_NUMBER(T.ADVANCE_PAY) * 0.01, 2) RSRV_STR4,
       TRUNC(TO_NUMBER(T.SEND_PAY) * 0.01, 2) RSRV_STR5,
       TRUNC(TO_NUMBER(T.RETURNFEE) * 0.01, 2) RSRV_STR6
  FROM TF_F_USER_SALE_STOP T
  WHERE (T.TRADE_STAFF_ID = :TRADE_STAFF_ID OR :TRADE_STAFF_ID IS NULL OR  :TRADE_STAFF_ID = '')
   AND (T.TRADE_CITY_CODE = :TRADE_CITY_CODE OR :TRADE_CITY_CODE IS NULL OR  :TRADE_CITY_CODE = '')
   AND T.ACCEPT_DATE >= TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND T.ACCEPT_DATE <= TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND T.RSRV_STR1 = '1'