--IS_CACHE=N
SELECT COUNT(1) 增加副号码
FROM TF_F_RELATION_UU B
WHERE B.RELATION_TYPE_CODE = '45'
AND B.ROLE_CODE_B = '2'
AND B.END_DATE > SYSDATE
AND EXISTS (SELECT 1 ---主号码组建亲亲网的同时，须至少增加一个副号码>0
       FROM TF_F_RELATION_UU A
      WHERE A.USER_ID_B = TO_NUMBER(:USER_ID)
        AND A.USER_ID_A = B.USER_ID_A
        AND A.RELATION_TYPE_CODE = '45'
        AND A.ROLE_CODE_B = '1'
        AND A.END_DATE > SYSDATE)