UPDATE TF_B_VIPAIRDROME_SERVICE
   SET STATE          = :STATE,
       RESERVICE_ID   = :RESERVICE_ID,
       RETURN_EXPLAIN = :RETURN_EXPLAIN,
       RETURN_DATE    = SYSDATE,
       RETURN_STAFF   = :RETURN_STAFF,
       REMARK         = :REMARK,
       RSRV_TAG1      = :RSRV_TAG1
 WHERE SERVICE_ID = :SERVICE_ID