SELECT A.SERIAL_NUMBER,
       A.CUST_NAME,
       TO_CHAR(A.VIP_NO) VIP_NO,
       A.AIRDROME_NAME,
       A.PLANE_LINE,
       A.FOLLOW_NUM,
       A.SERVICE_TYPE,
       A.SERVICE_CONTENT,
       A.OLD_SCORE_VALUE,
       A.CONSUME_SCORE,
       A.HANDING_CHARGE,
       A.SERVICE_CHARGE,
       A.STATE,
       A.SERVICE_STAFF,
       TO_CHAR(A.SERVICE_DATE, 'yyyy-mm-dd hh24:mi:ss') SERVICE_DATE,
       A.INDIV_INFO,
       A.FEEDBACK,
       A.INNOVATION,
       A.ADVICES,
       A.OTHERS,
       B.USER_ID
  FROM TF_B_VIPAIRDROME_SERVICE A,
       TF_F_CUST_VIP B,
       (SELECT MAX(SERVICE_DATE) SVC_DATE
          FROM TF_B_VIPAIRDROME_SERVICE
         WHERE 1 = 1
           AND (SERIAL_NUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
           AND (VIP_NO = :VIP_NO OR :VIP_NO IS NULL)
           AND STATE = '0') C
 WHERE 1 = 1
   AND A.STATE = '0'
   AND A.VIP_ID = B.VIP_ID
   AND (A.SERIAL_NUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
   AND (A.VIP_NO = :VIP_NO OR :VIP_NO IS NULL)
   AND SERVICE_DATE = C.SVC_DATE
 ORDER BY SERVICE_DATE DESC