DELETE TF_F_USER_PLATSVC T
 WHERE T.USER_ID = :USER_ID
   AND T.PARTITION_ID = MOD(:USER_ID, 10000)
   AND T.END_DATE < SYSDATE
   AND T.OPER_CODE = '04'
   AND T.BIZ_STATE_CODE = 'N'
   AND T.BIZ_TYPE_CODE = '53'