SELECT A.*
  FROM TF_F_USER_PLATSVC A
 WHERE A.SERVICE_ID = '40112066'
   AND A.USER_ID = :USER_ID
   AND A.BIZ_STATE_CODE IN ('A', 'N')
   AND A.PARTITION_ID= MOD( :USER_ID ,10000 )
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE