SELECT USER_ID,
        SERVICE_ID,
        SP_CODE,
        BIZ_CODE,
        BIZ_TYPE_CODE,
        SERIAL_NUMBER,
        ORG_DOMAIN,
        PRICE,
        BILL_TYPE
   FROM TF_F_USER_PLATSVC A
  WHERE A.BIZ_TYPE_CODE = 'LY'
    AND A.USER_ID = TO_NUMBER(:USER_ID)
    AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
    AND A.END_DATE > SYSDATE
    AND A.BIZ_STATE_CODE != 'E'
    AND NOT EXISTS (SELECT 1
           FROM TD_B_PLATSVC_LIMIT T
          WHERE T.SERVICE_ID = TO_NUMBER(:SERVICE_ID)
            AND T.SERVICE_ID_L = A.SERVICE_ID
            AND T.SVC_TYPE = 'Z'
            AND T.BIZ_TYPE_CODE = '19'
            AND T.OPER_CODE IN ('02', '08')
            AND T.LIMIT_TYPE = '4')