SELECT A.USER_ID,
       A.BRAND_CODE,
       A.EPARCHY_CODE,
       A.USER_PASSWD,
       A.USER_STATE_CODESET,
       A.NET_TYPE_CODE,
       A.SERIAL_NUMBER,
       A.SCORE_VALUE,
       A.CITY_CODE,
       A.REMOVE_TAG
  FROM TF_F_USER A
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND A.REMOVE_TAG = :REMOVE_TAG