SELECT A.SERVICE_ID SERVICE_ID
  FROM TF_F_USER_PLATSVC A
 WHERE PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND to_char(A.SERVICE_ID) IN (:SERVICE_ID)
   AND A.BIZ_STATE_CODE IN ('A', 'N')
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE