SELECT A.SERVICE_ID SERVICE_ID
  FROM TF_F_USER_PLATSVC A
 WHERE PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID NOT IN ('99008753', '99008755', '99009009')
   AND A.BIZ_STATE_CODE IN ('A', 'N')
   AND A.BIZ_TYPE_CODE = '16'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE