SELECT PLATSVC.SERVICE_ID ELEMENT_ID,
       PLATSVC.INST_ID,
       'Z' ELEMENT_TYPE_CODE,
       TO_CHAR(PLATSVC.START_DATE, 'yyyy-mm-dd') START_DATE,
       TO_CHAR(PLATSVC.END_DATE, 'yyyy-mm-dd') END_DATE,
       TO_CHAR(PLATSVC.RSRV_DATE1, 'yyyy-mm-dd') RSRV_DATE1
  FROM TF_F_USER_PLATSVC PLATSVC 
 WHERE PLATSVC.USER_ID = TO_NUMBER(:USER_ID)
   AND PLATSVC.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND PLATSVC.BIZ_STATE_CODE = 'A'
   AND SYSDATE < PLATSVC.END_DATE
