SELECT C.PARA_CODE3
  FROM TF_F_USER A, TD_S_COMMPARA C
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
      
   AND C.SUBSYS_CODE = 'CSM'
   AND C.PARAM_ATTR = '957'
   AND C.PARAM_CODE = '2'
   AND C.PARA_CODE1 = '*'
   AND C.PARA_CODE4 = '98'
   AND SYSDATE BETWEEN C.START_DATE AND C.END_DATE
      
   AND A.EPARCHY_CODE = C.EPARCHY_CODE
   AND A.BRAND_CODE = C.PARA_CODE2