--IS_CACHE=Y
SELECT A.SERVICE_ID,A.OPER_CODE,A.OPR_SOURCE,A.SERVICEID_SET,A.BOOK_TAG
  FROM TD_B_PLATSVCBOOK_CONFIG A
 WHERE A.SERVICE_ID = :SERVICE_ID
   AND A.OPER_CODE = :OPER_CODE
   AND (A.OPR_SOURCE = 'ZZ' OR A.OPR_SOURCE = :OPR_SOURCE)
   AND A.BOOK_TAG = '0'