SELECT A.USER_ID,
       A.SERVICE_ID,
       A.BIZ_STATE_CODE,
       A.START_DATE,
       A.END_DATE
  FROM TF_F_USER_PLATSVC A
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE