SELECT A.*
  FROM TF_F_USER_PLATSVC A, TF_F_USER B
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = B.USER_ID
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.BIZ_STATE_CODE IN ('A', 'N')
   AND B.REMOVE_TAG = '0'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
