SELECT A.SERVICE_ID SERVICE_ID_L,
       --C.SERVICE_NAME SERVICE_NAME_L,
       'S' SVC_TYPE
  from TF_F_USER_SVC A--, TD_B_SERVICE C
 where A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   --AND A.SERVICE_ID = C.SERVICE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND EXISTS
 (SELECT 1
          FROM TD_S_COMMPARA B
         WHERE B.PARA_CODE1 = to_char(A.SERVICE_ID)
           AND SUBSYS_CODE = 'CSM'
           AND PARAM_ATTR = :PARAM_ATTR
           AND PARAM_CODE = :SERVICE_ID
           AND PARA_CODE2 = 'S'
           AND (eparchy_code = :EPARCHY_CODE or eparchy_code = 'ZZZZ')
           AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE)
