SELECT TO_CHAR(A.END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE,A.SERVICE_ID,A.SERIAL_NUMBER,A.OPR_SOURCE FROM TF_F_USER_PLATSVC A
		WHERE 1=1
  		AND A.USER_ID =:USER_ID
  		AND A.SERVICE_ID =:SERVICE_ID
 		AND A.SP_CODE =:SP_CODE
  		AND A.BIZ_CODE =:BIZ_CODE
  		AND (SYSDATE BETWEEN A.START_DATE AND A.END_DATE)