SELECT *
FROM TF_F_USER_PLATSVC
WHERE USER_ID = TO_NUMBER(:USER_ID)
  AND PARTITION_ID = MOD(:USER_ID,10000)
  AND BIZ_TYPE_CODE =:BIZ_TYPE_CODE
  AND BIZ_STATE_CODE='A'
  AND SYSDATE BETWEEN START_DATE AND END_DATE