--IS_CACHE=Y
SELECT A.TYPE_ID,
       A.DATA_ID,
       A.DATA_NAME,
       A.PDATA_ID,
       A.SUBSYS_CODE,
       A.EPARCHY_CODE,
       A.REMARK,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.UPDATE_TIME
  FROM TD_S_STATIC A
 WHERE A.TYPE_ID = '3700'
 AND   A.DATA_ID = :DATA_ID