SELECT FIRST_DATE,FIRST_DATE_MON,RSRV_STR4,RSRV_STR5 INTF_TRADE_ID,RSRV_DATE2
FROM TF_F_USER_PLATSVC A
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND A.BIZ_STATE_CODE = 'L'
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADE_PLATSVC B
         WHERE B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND B.TRADE_ID = :TRADE_ID
           AND B.USER_ID = :USER_ID
           AND B.SERVICE_ID = :SERVICE_ID
           AND B.USER_ID = A.USER_ID
           AND B.SERVICE_ID = A.SERVICE_ID)