SELECT SERIAL_NUMBER,USER_ID,SERVICE_ID,
SP_CODE,BIZ_CODE,BIZ_TYPE_CODE,BIZ_STATE_CODE,PRODUCT_NO,ORG_DOMAIN,OPER_CODE,
OPR_SOURCE,BILL_TYPE,PRICE,FIRST_DATE,FIRST_DATE_MON,START_DATE,END_DATE,UPDATE_TIME
FROM TF_F_USER_PLATSVC 
WHERE USER_ID=TO_NUMBER(:USER_ID)
AND  SP_CODE=:SP_CODE
AND  BIZ_TYPE_CODE=:BIZ_TYPE_CODE
AND  BIZ_CODE =:BIZ_CODE
AND  BIZ_STATE_CODE ='A'
AND  NOT (SP_CODE LIKE 'SW%' AND OPER_CODE ='19')
AND  SYSDATE BETWEEN START_DATE AND END_DATE
UNION
SELECT A.SERIAL_NUMBER,A.USER_ID,A.SERVICE_ID,
A.SP_CODE,A.BIZ_CODE,A.BIZ_TYPE_CODE,A.BIZ_STATE_CODE,A.PRODUCT_NO,A.ORG_DOMAIN,A.OPER_CODE,
A.OPR_SOURCE,A.BILL_TYPE,A.PRICE,A.FIRST_DATE,A.FIRST_DATE_MON,A.START_DATE,A.END_DATE,A.UPDATE_TIME
FROM TF_B_TRADE_PLATSVC A ,TF_B_TRADE B
WHERE A.TRADE_ID = B.TRADE_ID
AND  A.USER_ID = B.USER_ID
AND  A.USER_ID=TO_NUMBER(:USER_ID)
AND  A.SP_CODE=:SP_CODE
AND  A.BIZ_TYPE_CODE=:BIZ_TYPE_CODE
AND  A.BIZ_CODE =:BIZ_CODE
AND  A.BIZ_STATE_CODE ='A'
AND  NOT (A.SP_CODE LIKE 'SW%' AND A.OPER_CODE ='19')