SELECT A.USER_ID,
       A.RSRV_VALUE_CODE,
       A.RSRV_VALUE,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       A.RSRV_STR6,
       A.RSRV_STR7,
       A.RSRV_STR8,
       A.RSRV_STR9,
       A.RSRV_STR30,
       A.RSRV_STR10,
       A.RSRV_STR11,
       A.START_DATE,
       A.END_DATE
  FROM TF_F_USER_OTHER A
 WHERE A.PARTITION_ID = MOD(:USER_ID,10000)
 AND   A.USER_ID = :USER_ID
 AND   A.RSRV_STR10 IS NOT NULL
 AND	 A.RSRV_VALUE_CODE = 'V2CP'
 AND   A.RSRV_VALUE = '32'
 AND   SYSDATE BETWEEN A.START_DATE AND A.END_DATE
 AND   to_date(A.RSRV_STR5,'yyyymmddhh24miss') > SYSDATE