SELECT PARTITION_ID,
       USER_ID,
       SERVICE_ID,
       SERIAL_NUMBER,
       SP_CODE,
       BIZ_CODE,
       BIZ_TYPE_CODE BIZ_STATE_CODE,
       DISCNT_CODE,
       DISCNT_NAME,
       SMS_TAG,
       SMS_DATE,
       SMS_DATE+1 END_SMS_DATE,
       RESMS_TAG,
       RESMS_DATE,
       RESMS_CONTENT
  FROM TF_F_USER_PLATSVC_SHL
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SERVICE_ID = :SERVICE_ID