SELECT A.*,B.OPER_CODE,B.OPR_SOURCE 
  FROM TF_F_USER_PLATSVC A,TF_F_USER_PLATSVC_TRACE B
 WHERE A.PARTITION_ID = MOD(:USER_ID,'10000')
   AND A.USER_ID = :USER_ID
   AND A.USER_ID = B.USER_ID
   AND A.INST_ID = B.RELA_INST_ID
   AND A.BIZ_STATE_CODE = 'A'
   AND NOT SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND NOT SYSDATE BETWEEN B.START_DATE AND B.END_DATE
