SELECT A.SERVICE_ID FROM TF_F_USER_PLATSVC A
       WHERE A.USER_ID=TO_NUMBER(:USER_ID)
       AND  A.BIZ_TYPE_CODE='16' 
       AND  A.BIZ_STATE_CODE IN ('A','N')
       AND  A.BIZ_CODE IN('+MAILBZ','+MAILMF','+MAILVIP')
       AND  SYSDATE BETWEEN START_DATE AND END_DATE