SELECT A.START_DATE, A.INST_ID
    FROM TF_F_USER_SVC A
   WHERE A.PARTITION_ID = MOD(:USER_ID, '10000')
     AND A.USER_ID = :USER_ID
     AND A.SERVICE_ID = :SERVICE_ID
     AND A.PRODUCT_ID = :PRODUCT_ID
     AND A.PACKAGE_ID = :PACKAGE_ID
     AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE