UPDATE TF_F_USER_PLATSVC
SET BIZ_STATE_CODE=:BIZ_STATE_CODE，
    UPDATE_TIME=SYSDATE,
    UPDATE_STAFF_ID=:UPDATE_STAFF_ID,
    UPDATE_DEPART_ID=:UPDATE_DEPART_ID
WHERE PARTITION_ID=TO_NUMBER(MOD(:USER_ID,10000))
AND USER_ID=TO_NUMBER(:USER_ID)
AND SERVICE_ID=TO_NUMBER(:SERVICE_ID)
AND SYSDATE BETWEEN START_DATE AND END_DATE