UPDATE TF_F_USER_PLATSVC
   SET END_DATE = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS') -
                  1 / 24 / 3600,
       REMARK   = :REMARK
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND BIZ_STATE_CODE IN('A','N')
   AND SP_CODE = :SP_CODE
   AND TO_DATE(:ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') BETWEEN START_DATE AND
       END_DATE