UPDATE TF_F_USER_PLATSVC A
   SET A.END_DATE         = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS') -
                            1 / 24 / 3600,
       A.UPDATE_TIME      = to_date(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
       A.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE