UPDATE TF_F_USER_PLATSVC A
   SET A.BIZ_STATE_CODE = 'E',
       A.UPDATE_TIME    = SYSDATE,
       A.END_DATE = SYSDATE,
       A.REMARK         = '补换卡退订BOSS多的手机支付业务'
 WHERE A.SERVICE_ID IN
       (SELECT B.SERVICE_ID
          FROM TD_B_PLATSVC B
         WHERE B.BIZ_TYPE_CODE = :BIZ_TYPE_CODE)
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.BIZ_STATE_CODE IN ('N', 'A')
   AND A.END_DATE > SYSDATE