UPDATE TF_F_USER_PLATSVC A
   SET A.END_DATE         = SYSDATE - 1 / 24 / 3600,
       A.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND USER_ID = :USER_ID
   AND SERVICE_ID = :SERVICE_ID
   AND BIZ_STATE_CODE = 'N'
   AND RSRV_TAG1 = 'T'
   AND SYSDATE < END_DATE
   AND BIZ_TYPE_CODE = '53'
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADE_PLATSVC
         WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND TRADE_ID = :TRADE_ID
           AND USER_ID = :USER_ID
           AND SERVICE_ID = :SERVICE_ID
           AND OPER_CODE = :OPER_CODE
           AND USER_ID = A.USER_ID
           AND SERVICE_ID = A.SERVICE_ID
           AND BIZ_TYPE_CODE = '53'
           AND RSRV_STR2 = 'YY')