INSERT INTO TF_B_TRADE_WIDENET_ACT
					(TRADE_ID,
					ACCEPT_MONTH,
					USER_ID,
					ACCT_ID,
					ACCT_PASSWD,
					MAIN_TAG,
					START_DATE,
					END_DATE,
					UPDATE_TIME,
					UPDATE_STAFF_ID,
					UPDATE_DEPART_ID,
					MODIFY_TAG,
					REMARK,
          			RSRV_NUM1,
          			RSRV_NUM2,
          			RSRV_NUM3,
          			RSRV_NUM4,
          			RSRV_NUM5,
          			RSRV_STR1,
          			RSRV_STR2,
          			RSRV_STR3,
          			RSRV_STR4,
          			RSRV_STR5,
          			RSRV_DATE1,
			        RSRV_DATE2,
          			RSRV_DATE3,
          			RSRV_TAG1,
          			RSRV_TAG2,
          			RSRV_TAG3)
				VALUES
				(
				 	TO_NUMBER(:TRADE_ID),
				 	TO_NUMBER(:ACCEPT_MONTH),
				 	TO_NUMBER(:USER_ID),
				 	:ACCT_ID,
				 	:ACCT_PASSWD,
				 	:MAIN_TAG,
				 	TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
				 	TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
				 	TO_DATE(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
				 	:UPDATE_STAFF_ID,
				 	:UPDATE_DEPART_ID,
				 	:MODIFY_TAG,
				 	:REMARK,
                    TO_NUMBER(:RSRV_NUM1),
                    TO_NUMBER(:RSRV_NUM2),
             		TO_NUMBER(:RSRV_NUM3),
          			TO_NUMBER(:RSRV_NUM4),
          			TO_NUMBER(:RSRV_NUM5),
        			:RSRV_STR1,
        			:RSRV_STR2,
        			:RSRV_STR3,
        			:RSRV_STR4,
        			:RSRV_STR5,
        			TO_DATE(:RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS'),
          			TO_DATE(:RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS'),
          			TO_DATE(:RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS'),
          			:RSRV_TAG1,
        			:RSRV_TAG2,
        			:RSRV_TAG3          
				)