--IS_CACHE=Y
SELECT  TRADE_TYPE_CODE,PRODUCT_ID,FEEITEM_CODE,FEEITEM_NAME,FEE,TAX_RATE,TAX_TYPE,DISCOUNT,EPARCHY_CODE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_DATE1,RSRV_DATE3,RSRV_DATE2,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
FROM TD_B_FEEITEM_TAX 
WHERE TRADE_TYPE_CODE =:TRADE_TYPE_CODE
  AND PRODUCT_ID =:PRODUCT_ID
  AND (EPARCHY_CODE =:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')