UPDATE TF_F_PLATVM_DEVICEINFO
SET (TRADE_ID,ID,TYPE,LOGIN_ID,NAME,STATE,POSITION,TIME_STAMP,CLIENT_ID,START_DATE,END_DATE,USER_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4)
=(SELECT TRADE_ID,ID,TYPE,LOGIN_ID,NAME,STATE,POSITION,TIME_STAMP,CLIENT_ID,START_DATE,END_DATE,USER_ID,UPDATE_STAFF_ID,UPDATE_DEPART_ID,UPDATE_TIME,REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_DATE4 FROM TF_B_TRADE_PLATVM_DEVICEINFO WHERE TRADE_ID = :TRADE_ID)
WHERE ID = :ID 
  AND SYSDATE BETWEEN START_DATE AND END_DATE