INSERT INTO TL_B_CANCELSECCONFIRM_LOG
        (SERIAL_NUMBER, USER_ID, ORDER_ID, TRADE_ID1, TRADE_ID2, INST_TYPE,
         INST_ID, COMMODITY_CODE, SERV_TYPE, SP_CODE, OPERATOR_CODE, MEMBER_TYPE,
         CHANNEL_SOURCE, RE_WAY, BOOK_TIME, CONFIRM_TIME, CREATE_TIME,
         CONFIRM_LOG, ELEMENT_ID, SOURCE_TAG, UPLOAD_TAG, RSRV_STR1,
         RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5)
        SELECT B.SERIAL_NUMBER, B.USER_ID,
               B.ORDER_ID, B.TRADE_ID1, :TRADE_ID2, B.INST_TYPE, B.INST_ID,
               B.COMMODITY_CODE, B.SERV_TYPE, B.SP_CODE, B.OPERATOR_CODE, B.MEMBER_TYPE,
               B.CHANNEL_SOURCE, B.RE_WAY, B.BOOK_TIME, B.CONFIRM_TIME,
               to_date(:CREATE_TIME, 'yyyy-mm-dd hh24:mi:ss'), B.CONFIRM_LOG, B.ELEMENT_ID, B.SOURCE_TAG, 
               B.UPLOAD_TAG, B.RSRV_STR1, B.RSRV_STR2, B.RSRV_STR3, B.RSRV_STR4,
               B.RSRV_STR5
          FROM TL_B_ACCEPTSECCONFIRM_LOG B
         WHERE B.INST_ID = :INST_ID
           AND B.USER_ID = :USER_ID