SELECT TO_CHAR(POS_TRADE_ID) POS_TRADE_ID,
       TO_CHAR(TRADE_ID) TRADE_ID,
       SERIAL_NUMBER,
       TO_CHAR(USER_ID) USER_ID,
       STATUS,
       TRANS_TYPE,
       AMOUNT,
       POS_ID,
       CARD_NO,
       BANK_NO,
       TO_CHAR(ACCEPT_TIME, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_TIME,
       TO_CHAR(TRANS_DATE_TIME, 'YYYY-MM-DD HH24:MI:SS') TRANS_DATE_TIME,
       CERT_NO,
       REF_NO,
       BATCH_NO,
       RESP,
       RESP_INFO,
       MERCH_ID,
       OPER_STAFF_ID,
       AUTH_NO,
       TO_CHAR(CANCEL_POS_TRADE_ID) CANCEL_POS_TRADE_ID,
       TO_CHAR(CANCEL_TRADE_ID) CANCEL_TRADE_ID,
       CANCEL_CERT_NO,
       CANCEL_REF_NO,
       LOCAL_ADDR,
       S_RESP,
       TRUNC(SYSDATE) - TRUNC(TRANS_DATE_TIME) TODAY_PAY,
       TO_CHAR(trans_date_time, 'YYYYMMDD') TRANS_YYYYMMDD,
       DECODE(TRUNC(CANCEL_DATE), TRUNC(SYSDATE), 0, 1) CAN_CANCEL,
       TO_CHAR(TRANS_DATE_TIME + 30, 'YYYY-MM-DD HH24:MI:SS') EXP_DATE,
       DECODE(TRUNC(a.PRINT_RECEIPTS), '1', '是', '否') PRINT_RECEIPTS
  FROM TL_B_POS_LOG A
 WHERE A.SERIAL_NUMBER = :SERIAL_NUMBER
   AND ((a.TRANS_TYPE = 'S' and A.STATUS = '0') or
       (a.TRANS_TYPE = 'M' and A.STATUS = '4'))
   AND NOT EXISTS
 (SELECT TRADE_ID
          FROM TF_B_TRADE
         WHERE TRADE_ID = a.TRADE_ID
           AND ACCEPT_MONTH = SUBSTR(TO_NUMBER(a.TRADE_ID), 5, 2))
   AND NOT EXISTS
 (SELECT TRADE_ID
          FROM TF_BH_TRADE
         WHERE TRADE_ID = a.TRADE_ID
           AND ACCEPT_MONTH = SUBSTR(TO_NUMBER(a.TRADE_ID), 5, 2))
