UPDATE TF_B_TRADE_PLATSVC A
   SET RSRV_STR1 = 'U'
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND EXISTS (SELECT 1
            FROM TD_B_PLATSVC B
           WHERE A.SERVICE_ID = B.SERVICE_ID
             AND (B.SERV_TYPE = '1'))