SELECT EXECUTE_ID,EXECUTE_DESC,SERIAL_NUMBER,ID_TYPE,ID,PRIORITY,DESCRIPTION,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,EPARCHY_CODE,to_char(UPDATE_DATE,'yyyy-mm-dd hh24:mi:ss') UPDATE_DATE,UPDATE_TAG,UPDATE_STAFF_ID,ACCEPT_MONTH,RSRV_STR1,RSRV_STR2
  FROM TF_F_RECOMMEND
 WHERE (SERIAL_NUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
   AND (ID_TYPE = :ID_TYPE OR :ID_TYPE IS NULL)
   AND (ID = TO_NUMBER(:ID) OR :ID IS NULL)
   AND ( (:EXECUTE_DESC IS NOT NULL AND EXECUTE_DESC LIKE '%'||:EXECUTE_DESC||'%') OR (:EXECUTE_DESC IS NULL) )
   AND (EPARCHY_CODE = :EPARCHY_CODE OR :EPARCHY_CODE IS NULL)