SELECT TRANSACTION_ID,
       SERIAL_NUMBER,
       ORDER_NO,
       CHANNEL_TYPE,
       ACCEPT_DATE,
       CARD_TYPE,
       CARD_MONEY,
       BUY_COUNT,
       HOME_PRO,
       PAYMENT,
       SETTLE_DATE,
       CARD_BUSIPROP,
       PUBLIC_KEY_ID,
       STATUS,
       FILE_NAME
  FROM TI_B_ELECTCARD_BATSELL T
     WHERE RSRV_STR2 = :TRANSACTION_ID
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRANSACTION_ID,5,2))
     AND SERIAL_NUMBER = :SERIAL_NUMBER