--IS_CACHE=Y
SELECT /*+INDEX(a IDX_TD_M_DEPART_RSVALUE2)*/
 DEPART_ID PARA_CODE1,
 DEPART_ID||'|'||DEPART_NAME PARA_CODE2,
 DEPART_CODE PARA_CODE3,
 '' PARA_CODE4,
 '' PARA_CODE5,
 '' PARA_CODE6,
 '' PARA_CODE7,
 '' PARA_CODE8,
 '' PARA_CODE9,
 '' PARA_CODE10,
 '' PARA_CODE11,
 '' PARA_CODE12,
 '' PARA_CODE13,
 '' PARA_CODE14,
 '' PARA_CODE15,
 '' PARA_CODE16,
 '' PARA_CODE17,
 '' PARA_CODE18,
 '' PARA_CODE19,
 '' PARA_CODE20,
 '' PARA_CODE21,
 '' PARA_CODE22,
 '' PARA_CODE23,
 '' PARA_CODE24,
 '' PARA_CODE25,
 '' PARA_CODE26,
 '' PARA_CODE27,
 '' PARA_CODE28,
 '' PARA_CODE29,
 '' PARA_CODE30,
 '' START_DATE,
 '' END_DATE,
 '' EPARCHY_CODE,
 '' REMARK,
 '' UPDATE_STAFF_ID,
 '' UPDATE_DEPART_ID,
 '' UPDATE_TIME,
 '' SUBSYS_CODE,
 0 PARAM_ATTR,
 '' PARAM_CODE,
 '' PARAM_NAME
  FROM TD_M_DEPART A
 WHERE RSVALUE2 = :PARA_CODE1
   AND VALIDFLAG = '0'
   AND START_DATE <= SYSDATE
   AND END_DATE >= SYSDATE
   AND EXISTS (SELECT 1
          FROM TD_M_DEPARTKIND B
         WHERE B.DEPART_KIND_CODE = A.DEPART_KIND_CODE
           AND B.CODE_TYPE_CODE = '0')
   AND (:PARA_CODE2 IS NULL OR :PARA_CODE2 = '' OR
       A.AREA_CODE = :PARA_CODE2)
   AND :PARA_CODE3 IS NULL
   AND :PARA_CODE4 IS NULL
   AND :PARA_CODE5 IS NULL
   AND :PARA_CODE6 IS NULL
   AND :PARA_CODE7 IS NULL
   AND :PARA_CODE8 IS NULL
   AND :PARA_CODE9 IS NULL
   AND :PARA_CODE10 IS NULL
 ORDER BY PARA_CODE3