SELECT T.PARTITION_ID,
       TO_CHAR(INST_ID) INST_ID,
       TO_CHAR(FAMILY_USER_ID) FAMILY_USER_ID,
       TO_CHAR(MEMBER_USER_ID) MEMBER_USER_ID,
       CHA_TYPE,
       TO_CHAR(REL_INST_ID) REL_INST_ID,
       CHA_CODE,
       CHA_VALUE,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3 RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       TO_CHAR(RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
  FROM TF_F_FAMILY_MEMBER_CHA T
 WHERE MEMBER_USER_ID = TO_NUMBER(:MEMBER_USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:MEMBER_USER_ID), 10000)
   AND CHA_CODE = :CHA_CODE
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE