SELECT SERVICE_ID FROM TF_F_USER_PLATSVC T WHERE 1=1
And T.USER_ID = TO_NUMBER(:USER_ID)  
AND T.PARTITION_ID =  MOD(TO_NUMBER(:USER_ID),10000)
And T.BIZ_TYPE_CODE='99'
And T.SERVICE_ID In ('98009901','98009903')
And T.BIZ_STATE_CODE In('A','N')
AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE