INSERT INTO TF_B_EOP_BOMC
  (BOMC_ID, WORKFORMID, WORKFORM_NAME, ACCEPT_MONTH, OPER_TYPE, DEAL_STATE, BOMC_ORDER_CODE, INSERT_TIME, UPDATE_TIME, SHEETTYPE, DEAL_LIMIT, ATTACHREF, OPDETAIL, ERRLIST, RESULT_TIME, CITY_CODE,
   EPARCHY_CODE, DEPART_ID, DEPART_NAME, STAFF_ID, STAFF_NAME, STAFF_PHONE, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7, REMARK, RENEW_REASON)
VALUES
  (:BOMC_ID, :WORKFORMID, :WORKFORM_NAME, :ACCEPT_MONTH, :OPER_TYPE, :DEAL_STATE, :BOMC_ORDER_CODE, to_date(:INSERT_TIME, 'yyyy-MM-dd hh24:Mi:ss'), to_date(:UPDATE_TIME, 'yyyy-MM-dd hh24:Mi:ss'),
   :SHEETTYPE, to_date(:DEAL_LIMIT, 'yyyy-MM-dd hh24:Mi:ss'), :ATTACHREF, :OPDETAIL, :ERRLIST, to_date(:RESULT_TIME, 'yyyy-MM-dd hh24:Mi:ss'), :CITY_CODE, :EPARCHY_CODE, :DEPART_ID, :DEPART_NAME,
   :STAFF_ID, :STAFF_NAME, :STAFF_PHONE, :RSRV_STR1, :RSRV_STR2, :RSRV_STR3, :RSRV_STR4, :RSRV_STR5, :RSRV_STR6, :RSRV_STR7, :REMARK, :RENEW_REASON)
