--IS_CACHE=Y
SELECT A.PARAM_CODE,DECODE(A.PARA_CODE1,'ZZZZ',:INFO_VALUE,A.PARAM_NAME) PARAM_NAME,A.PARA_CODE1,A.PARA_CODE2,A.PARA_CODE3 
FROM TD_S_COMMPARA A
WHERE A.PARAM_ATTR = '3790' 
AND A.PARAM_CODE = '%'||:PARAM_CODE
AND A.PARA_CODE2 = :SERVICE_ID
AND A.PARA_CODE3 = :INFO_CODE
AND A.PARA_CODE1 = :INFO_VALUE