--IS_CACHE=N
SELECT 
T.ECONFIG_ID,T.BARCODE_ID,T.ELEMENT_TYPE,T.ELEMENT_ID
,T.ELEMENT_NAME,T.ELEMENT_EXPLAIN,T.START_DATE
,T.END_DATE,T.UPDATE_STAFF_ID,T.UPDATE_DEPART_ID
,T.UPDATE_TIME,T.REMARK
  FROM TD_B_BARCODE_CONFIG T
WHERE T.BARCODE_ID =:BARCODE_ID
AND (:ECONFIG_ID IS NULL OR T.ECONFIG_ID =:ECONFIG_ID)
