SELECT decode(B.PSPT_TYPE_CODE,'H','Z','I','Z',B.PSPT_TYPE_CODE) PSPT_TYPE_CODE, B.PSPT_ID, B.CUST_NAME
  FROM TF_F_USER A, TF_F_CUSTOMER B
 WHERE A.CUST_ID = B.CUST_ID
   AND A.USER_ID = :USER_ID
   AND A.REMOVE_TAG = '0'
   AND B.IS_REAL_NAME = '1'