UPDATE TF_F_ACCOUNT SET 
REMOVE_TAG = :REMOVE_TAG, REMOVE_DATE = to_date(:REMOVE_DATE,'yyyy-mm-dd hh24:mi:ss') , UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, UPDATE_TIME = to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , REMARK = :REMARK
WHERE 
PARTITION_ID = MOD(to_number(:ACCT_ID),10000) and ACCT_ID = to_number(:ACCT_ID)