--IS_CACHE=N
SELECT COUNT(1) 统计数
  FROM TF_F_USER_SVC A
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.SERVICE_ID = '231'
   AND TO_DATE(:SEND_TIME, 'YYYYMMDD') BETWEEN TRUNC(A.START_DATE) AND
       A.END_DATE
   AND A.END_DATE < TO_DATE(:SEND_TIME, 'YYYYMMDD') + 1