UPDATE tf_b_resapply_main
   SET CANCEL_REASON = :CANCEL_REASON ,AUDIT_STATE_CODE = :AUDIT_STATE_CODE,CLOSE_TYPE_CODE = :CLOSE_TYPE_CODE,
CLOSE_DATE = sysdate,CLOSE_STAFF_ID = :STAFF_ID   
 WHERE APPLY_NO = :APPLY_NO
   AND APPLY_BATCH_ID = :APPLY_BATCH_ID