--IS_CACHE=Y
SELECT ID_VALUE SID,SERIAL_NUMBER
        FROM TD_S_ECHANNAL_STAFF
       WHERE 1=1
       AND ID_TYPE='0'
       AND OPER_STAFF_ID=:OSID
       AND CHAN_ID=:CHAN_ID
       AND SERIAL_NUMBER=:SERIAL_NUMBER
       AND STAFF_TYPE=:STYPE