INSERT INTO TF_F_USER_PLATSVC
  (PARTITION_ID,
   USER_ID,
   PRODUCT_ID,
   PACKAGE_ID,
   SERVICE_ID,
   SERIAL_NUMBER,
   SP_CODE,
   BIZ_CODE,
   BIZ_TYPE_CODE,
   BIZ_STATE_CODE,
   PRODUCT_NO,
   ORG_DOMAIN,
   OPER_CODE, 
   OPR_SOURCE,
   BILL_TYPE,
   PRICE,
   FIRST_DATE,
   FIRST_DATE_MON,
   GIFT_SERIAL_NUMBER,
   GIFT_USER_ID,
   SUBSCRIBE_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK)
VALUES
   (MOD(:USER_ID, 10000),
    :USER_ID,
    :PRODUCT_ID,
    :PACKAGE_ID,
    :SERVICE_ID,
    :SERIAL_NUMBER,
    :SP_CODE,
    :BIZ_CODE,
    :BIZ_TYPE_CODE,
    'E',
    :PRODUCT_NO,
    :ORG_DOMAIN,
    DECODE(:ORG_DOMAIN,
                'MRBT',
                '02',
                '07'),
    :OPR_SOURCE,
    :BILL_TYPE,
    :PRICE,
    TO_DATE(:FIRST_DATE,'YYYY-MM-DD HH24:MI:SS'),
    TO_DATE(:FIRST_DATE_MON,'YYYY-MM-DD HH24:MI:SS'),
    :GIFT_SERIAL_NUMBER,
    :GIFT_USER_ID,
    :SUBSCRIBE_ID,
    DECODE(:SP_CODE || '_' || :BIZ_CODE,
                                   '699013_20830001',
                                   DECODE(TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'),
                                          TRUNC(LAST_DAY(SYSDATE) + 1),
                                          SYSDATE,
                                          TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')),
                                   TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')),
    TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'),
    SYSDATE,
    :UPDATE_STAFF_ID,
    :UPDATE_DEPART_ID,
    '全业务退订须终止相关订购关系')