UPDATE TF_R_FEE_MARKET
   SET STATUS = '1', UPDATE_STAFF = :UPDATE_STAFF, UPDATE_TIME = SYSDATE,RSRV_STR2 = :RSRV_STR2 
 WHERE trim(CHNL_ID) = :CHNL_ID
   AND trim(FACTORY_CODE) = :FACTORY_CODE
   AND trim(YEAR) = :YEAR
   AND trim(ACCEPT_MONTH) = TO_NUMBER(:ACCEPT_MONTH)
   AND RSRV_STR3 = :RSRV_STR3