SELECT DISTINCT U.USER_ID USER_ID,T.CUST_ID CUST_ID, U.SERIAL_NUMBER SERIAL_NUMBER, T.PSPT_ID PSPT_ID
FROM TF_F_CUSTOMER T, TF_F_USER U, TF_F_USER_PRODUCT P
WHERE 1 = 1
   AND T.PSPT_ID= :PSPT_ID
   AND T.CUST_NAME<>:PSPT_NAME		
   AND U.SERIAL_NUMBER<>:SERIAL_NUMBER	   
   AND T.PARTITION_ID = MOD(TO_NUMBER(T.CUST_ID),10000)
   AND U.PARTITION_ID = MOD(TO_NUMBER(U.USER_ID),10000)
   AND P.PARTITION_ID = MOD(TO_NUMBER(P.USER_ID),10000)
   AND T.CUST_ID = U.CUST_ID
   AND U.USER_ID = P.USER_ID
   AND T.CUST_NAME IS NOT NULL
   AND P.BRAND_CODE IN ('G001','G002','G010','G005','PWLW','IMSG')
   AND T.PSPT_TYPE_CODE IN ('0', '1','2','3') 
   AND U.REMOVE_TAG='0'
   AND T.IS_REAL_NAME='1'
   AND NOT EXISTS ( SELECT 1 FROM TF_F_ONEPSPTMORENAME O WHERE O.USER_ID=U.USER_ID AND O.SERIAL_NUMBER=U.SERIAL_NUMBER AND O.REMOVE_TAG='0')
