UPDATE TF_F_RELATION_UU
   SET END_DATE         = TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss'),
       UPDATE_TIME      = SYSDATE
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND role_code_b = :ROLE_CODE_B
   AND START_DATE = TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss')