INSERT INTO TF_F_RELATION_UU
  (PARTITION_ID,
   USER_ID_A,
   SERIAL_NUMBER_A,
   USER_ID_B,
   INST_ID,
   SERIAL_NUMBER_B,
   RELATION_TYPE_CODE,
   ROLE_CODE_A,
   ROLE_CODE_B,
   ORDERNO,
   SHORT_CODE,
   START_DATE,
   END_DATE,
   UPDATE_TIME)
  SELECT MOD(A.USER_ID_B, 10000),
         A.USER_ID_A,
         A.SERIAL_NUMBER_A,
         A.USER_ID_B,
         A.INST_ID,
         A.SERIAL_NUMBER_B,
         A.RELATION_TYPE_CODE,
         A.ROLE_CODE_A,
         A.ROLE_CODE_B,
         A.ORDERNO,
         A.SHORT_CODE,
         TRUNC(SYSDATE),
         A.END_DATE,
         SYSDATE
    FROM TF_B_TRADE_RELATION_UU_BAK A, TF_F_USER_DISCNT B
   WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND A.USER_ID_B = TO_NUMBER(:USER_ID_B)
     AND B.USER_ID = A.USER_ID_B
     AND A.RELATION_TYPE_CODE = B.RELATION_TYPE_CODE
     AND A.RELATION_TYPE_CODE IN
         (SELECT RELATION_TYPE_CODE
            FROM TD_S_RELATION
           WHERE RELATION_KIND = 'F')
     AND A.END_DATE > SYSDATE
     AND B.END_DATE > SYSDATE