SELECT A.SERIAL_NUMBER_A,
       A.SERIAL_NUMBER_B,
       A.USER_ID_A,
       A.USER_ID_B,
       B.PARAM_NAME
  FROM TF_F_RELATION_UU A, TD_S_COMMPARA B
 WHERE A.RELATION_TYPE_CODE = B.PARA_CODE1
   AND A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID_B = TO_NUMBER(:USER_ID)
   AND A.ROLE_CODE_B = :ROLE_CODE_B
   AND A.END_DATE > SYSDATE
   AND B.PARAM_ATTR = 699
   AND B.PARAM_CODE = :PARAM_CODE
   AND B.END_DATE > SYSDATE