SELECT PARTITION_ID, TO_CHAR(USER_ID_A) USER_ID_A, SERIAL_NUMBER_A, TO_CHAR(USER_ID_B) USER_ID_B, SERIAL_NUMBER_B, RELATION_TYPE_CODE, ROLE_TYPE_CODE, ROLE_CODE_A, ROLE_CODE_B, ORDERNO, SHORT_CODE, INST_ID, TO_CHAR(START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
  FROM TF_F_RELATION_UU
 WHERE USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') >= START_DATE
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') <= END_DATE
   AND END_DATE > START_DATE
UNION ALL 
SELECT PARTITION_ID, TO_CHAR(USER_ID_A) USER_ID_A, SERIAL_NUMBER_A, TO_CHAR(USER_ID_B) USER_ID_B, SERIAL_NUMBER_B, RELATION_TYPE_CODE, ROLE_TYPE_CODE, ROLE_CODE_A, ROLE_CODE_B, ORDERNO, SHORT_CODE, INST_ID, TO_CHAR(START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE, UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_NUM4, RSRV_NUM5, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3, RSRV_TAG1, RSRV_TAG2, RSRV_TAG3
  FROM TF_F_RELATION_BB
 WHERE USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') >= START_DATE
   AND TO_DATE(:TIME_POINT, 'YYYYMMDDHH24MISS') <= END_DATE
   AND END_DATE > START_DATE