SELECT     			     
	A.SERIAL_NUMBER_A,A.USER_ID_A
 FROM UOP_CRM1.TF_F_RELATION_UU A
WHERE 1=1
 AND A.SERIAL_NUMBER_B = :SERIAL_NUMBER_B
 AND A.RELATION_TYPE_CODE = 'M2'
 AND (SYSDATE BETWEEN A.START_DATE and A.END_DATE) 