SELECT COUNT(1) POOL_NUM  FROM TF_F_RELATION_UU A, TF_F_USER B
 WHERE A.USER_ID_A = B.USER_ID
   AND B.USER_TYPE_CODE <> 'E'
   AND B.USER_TYPE_CODE <> 'F'
   AND B.USER_STATE_CODESET = '0'
   AND A.USER_ID_A = :USER_ID