SELECT RSRV_STR2,SERIAL_NUMBER_B,ROLE_CODE_B,RSRV_STR3,RSRV_STR4,START_DATE,END_DATE,REMARK
FROM TF_F_RELATION_UU  
WHERE SERIAL_NUMBER_A in(
SELECT SERIAL_NUMBER_A 
FROM TF_F_RELATION_UU 
WHERE 1=1
AND RELATION_TYPE_CODE='MF'
AND RSRV_STR2=:RSRV_STR2
AND SERIAL_NUMBER_B=:SERIAL_NUMBER_B
AND ROLE_CODE_B=:ROLE_CODE_B
)
AND sysdate between START_DATE and END_DATE