select t.partition_id,
       to_char(t.user_id_a) USER_ID_A,
       t.serial_number_a,
       to_char(t.user_id_b) USER_ID_B,
       t.serial_number_b,
       t.relation_type_code,
       t.role_type_code,
       t.role_code_a,
       t.role_code_b,
       t.orderno,
       t.short_code,
       to_char(t.inst_id) INST_ID,
       to_char(t.start_date, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_char(t.end_date, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       to_char(t.update_time, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       t.update_staff_id,
       t.update_depart_id,
       t.remark,
       t.rsrv_num1,
       t.rsrv_num2,
       t.rsrv_num3,
       t.rsrv_num4,
       t.rsrv_num5,
       t.rsrv_str1,
       t.rsrv_str2,
       t.rsrv_str3,
       t.rsrv_str4,
       t.rsrv_str5,
       to_char(t.rsrv_date1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       to_char(t.rsrv_date2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       to_char(t.rsrv_date3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       t.rsrv_tag1,
       t.rsrv_tag2,
       t.rsrv_tag3
  from tf_f_relation_uu t
 where 1 = 1
   and t.USER_ID_A = :USER_ID_A
   and t.relation_type_code = :RELATION_TYPE_CODE
