SELECT PARTITION_ID,
       TO_CHAR(USER_ID_A) USER_ID_A,
       SERIAL_NUMBER_A,
       TO_CHAR(USER_ID_B) USER_ID_B,
       SERIAL_NUMBER_B,
       RELATION_TYPE_CODE,
       ROLE_TYPE_CODE,
       ROLE_CODE_A,
       ROLE_CODE_B,
       SHORT_CODE,
       TO_CHAR(INST_ID) INST_ID
  FROM TF_F_RELATION_UU
 where 1=1
   AND PARTITION_ID = MOD(TO_NUMBER(USER_ID_B),10000)
   AND USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND SERIAL_NUMBER_B = :SERIAL_NUMBER_B
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND END_DATE > SYSDATE