SELECT UU.PARTITION_ID,
       TO_CHAR(UU.USER_ID_A) USER_ID_A,
       UU.SERIAL_NUMBER_A,
       TO_CHAR(UU.USER_ID_B) USER_ID_B,
       UU.SERIAL_NUMBER_B,
       UU.RELATION_TYPE_CODE,
       UU.ROLE_TYPE_CODE,
       UU.ROLE_CODE_A,
       UU.ROLE_CODE_B,
       UU.ORDERNO,
       UU.SHORT_CODE,
       UU.INST_ID,
       TO_CHAR(UU.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(UU.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       U.PARTITION_ID,
       TO_CHAR(U.USER_ID) USER_ID,
       TO_CHAR(U.CUST_ID) CUST_ID,
       TO_CHAR(U.USECUST_ID) USECUST_ID,
       U.EPARCHY_CODE,
       U.CITY_CODE,
       U.CITY_CODE_A,
       U.USER_PASSWD,
       U.USER_DIFF_CODE,
       U.USER_TYPE_CODE,
       U.USER_TAG_SET,
       U.USER_STATE_CODESET,
       U.NET_TYPE_CODE,
       U.SERIAL_NUMBER,
       U.CONTRACT_ID,
       U.ACCT_TAG,
       U.PREPAY_TAG,
       U.MPUTE_MONTH_FEE,
       U.MPUTE_DATE,      
       U.CHANGEUSER_DATE,       
       TO_CHAR(U.FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       TO_CHAR(U.LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,       
       U.OPEN_MODE,
       U.OPEN_DATE,
       U.OPEN_STAFF_ID,
       U.OPEN_DEPART_ID,
       U.ASSURE_CUST_ID,
       U.ASSURE_TYPE_CODE,
       U.ASSURE_DATE,
       U.REMOVE_TAG,
       TO_CHAR(U.DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME,
       TO_CHAR(U.PRE_DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') PRE_DESTROY_TIME,
       U.REMARK,
       U.RSRV_NUM1,
       U.RSRV_NUM2,
       U.RSRV_NUM3,
       U.RSRV_NUM4,
       U.RSRV_NUM5,
       U.RSRV_STR1,
       U.RSRV_STR2,
       U.RSRV_STR3,
       U.RSRV_STR4,
       U.RSRV_STR5,
       U.RSRV_STR6,
       U.RSRV_STR7,
       U.RSRV_STR8,
       U.RSRV_STR9,
       U.RSRV_STR10,
       U.RSRV_DATE1,
       U.RSRV_DATE2,
       U.RSRV_DATE3,
       U.RSRV_TAG1,
       U.RSRV_TAG2,
       U.RSRV_TAG3
  FROM TF_F_RELATION_UU uu, TF_F_USER u
   WHERE 1=1
   AND u.CUST_ID = :CUST_ID
   AND u.REMOVE_TAG = '0' 
   AND uu.USER_ID_A = u.USER_ID
   AND uu.RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND uu.USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND uu.PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND SYSDATE BETWEEN uu.start_date AND uu.end_date