SELECT PARTITION_ID, TO_CHAR(USER_ID_A) USER_ID_A, TO_CHAR(USER_ID_B) USER_ID_B, 
       RELATION_TYPE_CODE, ROLE_CODE_A, ROLE_CODE_B, ORDERNO, SHORT_CODE, RSRV_STR2, RSRV_TAG1,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE 
  FROM TF_F_RELATION_UU 
 WHERE USER_ID_A = TO_NUMBER(:USER_ID_A) 
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND END_DATE > LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE), -1)) + 1 - 1 / 24 / 3600 
   AND END_DATE <= LAST_DAY(TRUNC(SYSDATE)) + 1 - 1 / 24 / 3600
