SELECT DISTINCT A.PARTITION_ID,
       TO_CHAR(A.USER_ID_A) USER_ID_A,
       A.SERIAL_NUMBER_A,
       TO_CHAR(A.USER_ID_B) USER_ID_B,
       A.SERIAL_NUMBER_B,
       A.RELATION_TYPE_CODE,
       A.ROLE_CODE_A,
       A.ROLE_CODE_B,
       A.ORDERNO,
       A.SHORT_CODE,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_RELATION_UU A, TD_A_ACYCPARA B
 WHERE A.USER_ID_A = TO_NUMBER(:USER_ID_A) 
 AND A.END_DATE >= (B.ACYC_END_TIME-1/24/60/60)
  AND B.ACYC_ID BETWEEN :START_ACYC_ID AND :END_ACYC_ID