SELECT PARTITION_ID,
       TO_CHAR(USER_ID_A) USER_ID_A,
       SERIAL_NUMBER_A,
       TO_CHAR(USER_ID_B) USER_ID_B,
       SERIAL_NUMBER_B,
       A.RELATION_TYPE_CODE,
       ROLE_CODE_A,
       ROLE_CODE_B,
       ORDERNO,
       SHORT_CODE,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_RELATION_UU A
 WHERE A.PARTITION_ID = MOD(TO_NUMBER(1117032433165630), 10000)
   AND A.USER_ID_B = TO_NUMBER(1117032433165630)
   AND A.RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND TO_CHAR(A.END_DATE, 'yyyy-MM') = TO_CHAR(SYSDATE, 'yyyy-MM')
   AND A.END_DATE < SYSDATE