SELECT * FROM TF_F_RELATION_UU A,TF_F_USER B,TF_F_CUST_GROUP C
WHERE A.USER_ID_A = B.USER_ID
AND B.CUST_ID = C.CUST_ID
AND A.USER_ID_B = TO_NUMBER(:USER_ID)
AND A.RELATION_TYPE_CODE='20'
AND A.END_DATE > SYSDATE