SELECT t.SERIAL_NUMBER_A,t.USER_ID_B,t.RELATION_TYPE_CODE,t.ROLE_TYPE_CODE,t.start_date,t.end_date 
FROM TF_F_RELATION_UU t
WHERE t.USER_ID_A=:USER_ID_A AND t.SERIAL_NUMBER_B=:SERIAL_NUMBER
AND (SYSDATE BETWEEN t.START_DATE AND t.END_DATE)