UPDATE TF_F_RELATION_UU T
   SET T.USER_ID_A       = TO_NUMBER(:USER_ID_A),
       T.SERIAL_NUMBER_A = :SERIAL_NUMBER_A
 WHERE T.USER_ID_A = TO_NUMBER(:USER_ID)
   AND T.USER_ID_B <> TO_NUMBER(:USER_ID_B)
   AND T.END_DATE > SYSDATE