DELETE FROM TS_A_AUDITRESULT_DETAIL
 WHERE TRADE_DEPART_ID = :TRADE_DEPART_ID
   AND TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND trunc(ACCEPT_DATE)=trunc(to_date(:ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss'))