SELECT PARTITION_ID,to_char(USER_ID) USER_ID,SERIAL_NUMBER,to_char(EC_USER_ID) EC_USER_ID,EC_SERIAL_NUMBER,PRODUCTID,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,to_char(RSRV_NUM1) RSRV_NUM1,to_char(RSRV_NUM2) RSRV_NUM2,to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,UPDATE_DEPART_ID,UPDATE_STAFF_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,REMARK
  FROM TF_F_PO_USER_MBMP
 WHERE USER_ID = to_number(:USER_ID)
   AND SERIAL_NUMBER = :SERIAL_NUMBER
   AND EC_USER_ID = to_number(:EC_USER_ID)
   AND end_date>sysdate