SELECT TO_CHAR(B.TRADE_ID) TRADE_ID,
       TO_CHAR(B.USER_ID) USER_ID,
       B.SHEET_TYPE SHEET_TYPE,
       B.PRODUCT_NO PRODUCT_NO,
       B.INST_ID INST_ID
       FROM TF_B_TRADE_DATALINE_ATTR B
 WHERE B.ATTR_CODE = 'CRMNO'
   AND B.ATTR_VALUE = :ATTR_VALUE