SELECT B.TRADE_ID TRADE_ID, 
	B.USER_ID USER_ID, 
	B.SERIAL_NUMBER SERIAL_NUMBER,
	B.TRADE_TYPE_CODE TRADE_TYPE_CODE
  FROM UCR_CRM1.TF_B_TRADE_USER_DATALINE T, TF_B_TRADE B
 WHERE T.PRODUCT_NO = :PRODUCT_NO
   AND B.TRADE_ID = T.TRADE_ID
   AND B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(T.TRADE_ID, 5, 2))