--IS_CACHE=Y
SELECT /*+INDEX(a PK_TD_B_SMS_PARA)*/
 A.TRADE_TYPE_CODE TRADE_TYPE_CODE,
 A.BRAND_CODE      BRAND_CODE,
 A.PRODUCT_ID      PRODUCT_ID,
 A.SMS_CODE        SMS_CODE,
 A.SMS_TYPE_CODE   SMS_TYPE_CODE,
 A.SMS_CONTENT     SMS_CONTENT,
 A.BILLING_TYPE    BILLING_TYPE,
 A.EPARCHY_CODE    EPARCHY_CODE,
 B.IN_MODE_CODE    IN_MODE_CODE,
 B.SP_CODE         SP_CODE,
 B.BIZ_CODE        BIZ_CODE,
 B.BIZ_PRI         BIZ_PRI,
 B.SMS_PROCESS_TAG SMS_PROCESS_TAG,
 B.OPER_CODE       OPER_CODE
  FROM TD_B_SMS_PARA A, TD_B_INMODE_SMS_PARA B
 WHERE (A.TRADE_TYPE_CODE = :TRADE_TYPE_CODE OR A.TRADE_TYPE_CODE = -1)
   AND (A.BRAND_CODE = :BRAND_CODE OR A.BRAND_CODE = 'ZZZZ')
   AND (A.PRODUCT_ID = TO_NUMBER(:PRODUCT_ID) OR A.PRODUCT_ID = -1)
   AND A.BILLING_TYPE LIKE :BILLING_TYPE
   AND A.SMS_CODE = B.SMS_CODE
   AND (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
   AND (B.IN_MODE_CODE = :IN_MODE_CODE OR B.IN_MODE_CODE = 'Q')
   AND (B.SP_CODE = :SP_CODE OR B.SP_CODE = 'ZZZZ')
   AND (B.BIZ_CODE = :BIZ_CODE OR B.BIZ_CODE = 'ZZZZ')
   AND B.SMS_PROCESS_TAG LIKE '__' || :SMS_PROCESS_TAG || '%'
   AND (B.OPER_CODE = :OPER_CODE)
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND A.SMS_ID = B.SMS_ID
   AND B.BIZ_PRI =
       (SELECT /*+INDEX(a PK_TD_B_SMS_PARA)*/
         MAX(B.BIZ_PRI)
          FROM TD_B_SMS_PARA A, TD_B_INMODE_SMS_PARA B
         WHERE (A.TRADE_TYPE_CODE = :TRADE_TYPE_CODE OR
               A.TRADE_TYPE_CODE = -1)
           AND (A.BRAND_CODE = :BRAND_CODE OR A.BRAND_CODE = 'ZZZZ')
           AND (A.PRODUCT_ID = TO_NUMBER(:PRODUCT_ID) OR A.PRODUCT_ID = -1)
           AND A.BILLING_TYPE LIKE :BILLING_TYPE
           AND A.SMS_CODE = B.SMS_CODE
           AND (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
           AND (B.IN_MODE_CODE = :IN_MODE_CODE OR B.IN_MODE_CODE = 'Q')
           AND (B.SP_CODE = :SP_CODE OR B.SP_CODE = 'ZZZZ')
           AND (B.BIZ_CODE = :BIZ_CODE OR B.BIZ_CODE = 'ZZZZ')
           AND B.SMS_PROCESS_TAG LIKE '__' || :SMS_PROCESS_TAG || '%'
           AND (B.OPER_CODE = :OPER_CODE)
           AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
           AND B.BIZ_PRI <> -1)