--IS_CACHE=Y
SELECT DISTINCT PARA_CODE3,PARA_CODE5
  FROM TD_S_COMMPARA
 WHERE SUBSYS_CODE = 'CSM'
   AND PARAM_ATTR = '3701'
   AND PARAM_CODE = :ORG_DOMAIN
   AND PARA_CODE1 = :BIZ_TYPE_CODE
   AND PARA_CODE2 = :OPER_CODE
   AND PARA_CODE5 = '1'