--IS_CACHE=Y
SELECT IN_MODE_CODE,
       BIZ_TYPE_CODE,
       SP_CODE,
       BIZ_CODE,
       BIZ_PRI,
       TEMPLATE_ID,
       SMS_PROCESS_TAG,
       EVENT_TYPE,
       SMS_TYPE, 
       OPER_CODE,
       OPR_SOURCE,
       BILL_TYPE,
       SERV_MODE,
       FEEMODE_TAG,
       SCRIPT_ID,
       MVEL_EXPR,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3
  FROM TD_B_TRADE_PLATSMS T
 WHERE (T.IN_MODE_CODE = '-1' OR T.IN_MODE_CODE = :IN_MODE_CODE)
   AND (T.BIZ_TYPE_CODE = :BIZ_TYPE_CODE OR T.BIZ_TYPE_CODE = 'ZZ')
   AND (T.SP_CODE = :SP_CODE OR T.SP_CODE = 'ZZZZ')
   AND (T.BIZ_CODE = :BIZ_CODE OR T.BIZ_CODE = 'ZZZZ')
   AND  (T.OPER_CODE = :OPER_CODE  OR T.OPER_CODE = 'ZZ')
   AND (T.OPR_SOURCE = :OPR_SOURCE OR T.OPR_SOURCE = '-1')
   AND (T.BILL_TYPE = :BILL_TYPE OR T.BILL_TYPE = '-1')
   AND (T.SERV_MODE = :SERV_MODE OR T.SERV_MODE IS NULL)
   AND (T.FEEMODE_TAG = :FEEMODE_TAG OR T.FEEMODE_TAG IS NULL)
   AND  SYSDATE BETWEEN  START_DATE AND END_DATE
 ORDER BY BIZ_PRI DESC
