--IS_CACHE=Y
SELECT PARA_CODE1
  FROM TD_S_COMMPARA
 WHERE SUBSYS_CODE = 'CSM'
   AND PARAM_ATTR = 916
   AND PARA_CODE2 = 'Z'
   AND PARAM_CODE = :IN_MODE_CODE
   AND EPARCHY_CODE = 'ZZZZ'
   AND SYSDATE BETWEEN START_DATE AND END_DATE