SELECT OPRNUMB OPER_TRADE_ID, EVENTTYPE EVENT_TYPE, SOLDIMEI SOLD_IMEI, RETURNIMEI RETURN_IMEI, EVENTTIME EVENT_TIME,
	RESULT, UNSUCREASON UNSUC_REASON, REMARK UNSUC_COMMENT
FROM TI_R_SALESDATA_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')