SELECT B.START_VALUE,
		B.END_VALUE,
       B.SIM_TYPE_CODE,
       '补卡费' AS FEE_NAME,
       TO_CHAR(B.FEE) FEE,
       B.PAY_MONEY_CODE,
       B.REMARK
  from TF_B_TRADE_SIMCARDCOMPFEE B
 where 1 = 1
   AND B.UPDATE_STAFF_ID >= :START_STAFF_ID
   AND B.UPDATE_STAFF_ID <= :END_STAFF_ID
   AND B.UPDATE_TIME >= TO_DATE(:START_DATE, 'yyyy-mm-dd')
   AND B.UPDATE_TIME <= TO_DATE(:END_DATE, 'yyyy-mm-dd') + 1 - 0.00001