SELECT TO_CHAR(A.TRADE_ID) TRADE_ID, 
       B.TRADE_TYPE_CODE,
       A.NOTE_TYPE,
       TO_CHAR(B.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
       B.USER_ID,
	   B.CUST_ID,
       B.SERIAL_NUMBER,
       B.CUST_NAME,
       B.BRAND_CODE BRAND_CODE,
       DECODE(SIGN(LENGTH(B.PROCESS_TAG_SET) - 20),-1,'Z',SUBSTR(B.PROCESS_TAG_SET, 20, 1)) VERIFY_MODE,
       B.TRADE_STAFF_ID,
       B.TRADE_DEPART_ID ORG_INFO,
       A.RECEIPT_INFO1,
       A.RECEIPT_INFO2,
       A.RECEIPT_INFO3,
       A.RECEIPT_INFO4,
       A.RECEIPT_INFO5,
       A.NOTICE_CONTENT,
       A.RSRV_STR1
  FROM TF_B_TRADE_CNOTE_INFO A, TF_B_TRADE B , TF_B_TRADE E
 WHERE A.TRADE_ID = B.TRADE_ID
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND E.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND E.TRADE_ID=:TRADE_ID   
   and B.order_id=E.order_id
   and B.trade_id!=:TRADE_ID   
UNION ALL
SELECT TO_CHAR(A.TRADE_ID) TRADE_ID,
       B.TRADE_TYPE_CODE,
       A.NOTE_TYPE,
       TO_CHAR(B.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
       B.USER_ID,
	   B.CUST_ID,
       B.SERIAL_NUMBER,
       B.CUST_NAME,
       B.BRAND_CODE BRAND_CODE,
       DECODE(SIGN(LENGTH(B.PROCESS_TAG_SET) - 20),-1,'Z',SUBSTR(B.PROCESS_TAG_SET, 20, 1)) VERIFY_MODE,
       B.TRADE_STAFF_ID,
       B.TRADE_DEPART_ID ORG_INFO,
       A.RECEIPT_INFO1,
       A.RECEIPT_INFO2,
       A.RECEIPT_INFO3,
       A.RECEIPT_INFO4,
       A.RECEIPT_INFO5,
       A.NOTICE_CONTENT,
       A.RSRV_STR1
  FROM TF_B_TRADE_CNOTE_INFO A, TF_BH_TRADE B , TF_BH_TRADE E
 WHERE A.TRADE_ID = B.TRADE_ID
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND E.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND E.TRADE_ID=:TRADE_ID   
   and B.order_id=E.order_id
   and B.trade_id!=:TRADE_ID