DELETE FROM TD_S_SERVICELIMIT
WHERE SERVICE_ID_A = :SERVICE_ID_A
AND SERVICE_ID_B = :SERVICE_ID_B
and LIMIT_TAG = :LIMIT_TAG
AND START_DATE = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss')
AND EPARCHY_CODE = :EPARCHY_CODE