SELECT TAC TAC_CODE, TERMINALNAME TERMINAL_NAME, MATERIALCODE MATERIAL_CODE, TERMINALVENDER VENDER_CODE,
    TERMINALTYPE TERMINAL_TYPE_CODE,
	DECODE(TRANSTYPE,'1','0','2','1') VALID_TAG, OPRNUMB OPER_TRADE_ID, OPRNUMB IN_TRADE_ID
FROM TI_R_TACDATA_DOWN
WHERE 1 = 1
AND DEALFLAG = :DEALFLAG
AND OPRFLAG = :OPRFLAG
AND RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')