--IS_CACHE=Y
SELECT A.DEPART_ID, A.DEPART_NAME, A.DEPART_CODE, A.AREA_CODE
  FROM td_m_depart a, td_m_departkind b
 WHERE A.DEPART_KIND_CODE = B.DEPART_KIND_CODE
   AND B.CODE_TYPE_CODE = '0'
   AND VALIDFLAG = '0'
   AND A.DEPART_ID = :DEPART_CODE