update TD_B_SALE_GOODS_EXT T
set T.END_DATE       =SYSDATE      
,T.UPDATE_TIME       =SYSDATE     
,T.UPDATE_STAFF_ID   =:UPDATE_STAFF_ID 
,T.UPDATE_DEPART_ID  =:UPDATE_DEPART_ID 
where t.EXT_ID=to_number(:EXT_ID)