SELECT POOL_ID,
       POOL_NAME,
       POOL_CODE,
       POOL_VALUE,
       POOL_LEVEL,
       STATE,
       REL_IBSYSID,
       CREATE_DATE,
       UPDATE_DATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3
  FROM TF_B_EOP_SUBSCRIBE_POOL
 WHERE REL_IBSYSID = :REL_IBSYSID
   AND POOL_VALUE = :POOL_VALUE