SELECT TO_CHAR(U.SERIAL_NUMBER_A) SERIAL_NUMBER_A,TO_CHAR(U.SERIAL_NUMBER_B) SERIAL_NUMBER_B,TO_CHAR(M.IMS_PASSWORD) IMS_PASSWORD
  FROM TF_F_USER         T,
       TF_F_USER_PRODUCT P,
       TF_F_RELATION_UU  U,
       TF_F_USER_IMPU    M
 WHERE T.CUST_ID = :CUST_ID
   AND T.REMOVE_TAG = '0'
   AND T.PARTITION_ID = P.PARTITION_ID
   AND T.USER_ID = P.USER_ID
   AND P.END_DATE > SYSDATE
   AND P.BRAND_CODE = 'CTRX'
   AND U.USER_ID_A = T.USER_ID
   AND U.END_DATE > SYSDATE
   AND U.RELATION_TYPE_CODE = 'S1'
   AND U.USER_ID_B = M.USER_ID
   AND U.PARTITION_ID = M.PARTITION_ID
   AND M.END_DATE > SYSDATE