select '' SUBSYS_CODE, 0 PARAM_ATTR, '' PARAM_CODE, '' PARAM_NAME,
user_id para_code1, RSRV_STR1 para_code2, RSRV_STR2 para_code3, 
RSRV_STR3 para_code4, RSRV_STR4 para_code5,RSRV_STR9 para_code6, 
RSRV_STR5 para_code7, '' para_code8, '' PARA_CODE9 , 
'' PARA_CODE10 ,'' PARA_CODE11 ,'' PARA_CODE12 , '' PARA_CODE13 ,
'' PARA_CODE14 , '' PARA_CODE15 ,
'' PARA_CODE16 , '' PARA_CODE17 , '' PARA_CODE18 , '' PARA_CODE19 ,
'' PARA_CODE20 , '' PARA_CODE21 , '' PARA_CODE22 , '' PARA_CODE23 ,
'' PARA_CODE24 , '' PARA_CODE25 , '' PARA_CODE26 , '' PARA_CODE27 ,
'' PARA_CODE28 , '' PARA_CODE29 , '' PARA_CODE30 , '' START_DATE , 
'' END_DATE , '' EPARCHY_CODE , '' REMARK , '' UPDATE_STAFF_ID , 
'' UPDATE_DEPART_ID , '' UPDATE_TIME
from tf_f_user_other
WHERE RSRV_VALUE_CODE  = :PARA_CODE1
and USER_ID = TO_NUMBER(:PARA_CODE2)
and PARTITION_ID = mod(TO_NUMBER(:PARA_CODE2),10000)
and END_DATE > SYSDATE
and (:PARA_CODE3 = '' OR :PARA_CODE3 IS NULL)
and (:PARA_CODE4 = '' OR :PARA_CODE4 IS NULL) 
and (:PARA_CODE5 = '' OR :PARA_CODE5 IS NULL) 
and (:PARA_CODE6 = '' OR :PARA_CODE6 IS NULL) 
and (:PARA_CODE7 = '' OR :PARA_CODE7 IS NULL) 
and (:PARA_CODE8 = '' OR :PARA_CODE8 IS NULL) 
and (:PARA_CODE9 = '' OR :PARA_CODE9 IS NULL)
and (:PARA_CODE10 = '' OR :PARA_CODE10 IS NULL)