SELECT DISCNT_CODE FROM TF_F_USER_DISCNT A
WHERE USER_ID = TO_NUMBER(:USER_ID)
AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
AND SYSDATE BETWEEN START_DATE AND END_DATE
AND EXISTS (
 SELECT 1 FROM TD_S_COMMPARA
 WHERE SUBSYS_CODE = 'CSM'
 AND PARAM_ATTR = 1910
 AND PARAM_CODE = TO_CHAR(A.DISCNT_CODE)
 AND PARA_CODE23 like '%41%'
 AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE = 'ZZZZ')
 AND SYSDATE BETWEEN START_DATE AND END_DATE)