UPDATE TF_F_USER_PLATSVC_ATTR A
	 SET A.RSRV_STR1       = 'OVER_FLAG',
       A.UPDATE_TIME      = SYSDATE,
       A.UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
   AND A.USER_ID = :USER_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND EXISTS
 (SELECT 1
          FROM TF_B_TRADE_PLATSVC_ATTR B
         WHERE B.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND B.TRADE_ID = :TRADE_ID
           AND B.USER_ID = :USER_ID
           AND B.SERVICE_ID = :SERVICE_ID
           AND B.USER_ID = A.USER_ID
           AND B.SERVICE_ID = A.SERVICE_ID
           AND B.INFO_CODE = A.INFO_CODE)