INSERT INTO TF_BH_SHOPPING_CART_DETAIL
  (SHOPPING_CART_ID,
   CUST_ID,
   USER_ID,
   DETAIL_ORDER_ID,
   DETAIL_STATE_CODE,
   DISCNT_RULE_ID,
   OLDFEE,
   FREE_FEE,
   FEE,
   JOIN_TYPE,
   JOIN_SEQ,
   TRADE_STAFF_ID,
   TRADE_DEPART_ID,
   ACCEPT_DATE,
   DETAIL_TYPE_CODE,REQUEST_DATA,ACCEPT_MONTH)
  select SHOPPING_CART_ID,
         CUST_ID,
         USER_ID,
         DETAIL_ORDER_ID,
         DETAIL_STATE_CODE,
         DISCNT_RULE_ID,
         OLDFEE,
         FREE_FEE,
         FEE,
         JOIN_TYPE,
	 JOIN_SEQ,
         TRADE_STAFF_ID,
         TRADE_DEPART_ID,
         ACCEPT_DATE,
         DETAIL_TYPE_CODE,REQUEST_DATA,TO_CHAR(SYSDATE, 'MM')
    from TF_B_SHOPPING_CART_DETAIL
    where SHOPPING_CART_ID = :SHOPPING_CART_ID
    and DETAIL_ORDER_ID = :DETAIL_ORDER_ID
