UPDATE TF_F_USER_PAYITEM SET 
END_CYCLE_ID = :END_CYCLE_ID, UPDATE_TIME = to_date(:UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') , UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, REMARK = :REMARK
WHERE 
PARTITION_ID = MOD(to_number(:USER_ID),10000) and USER_ID = to_number(:USER_ID) and PLAN_ID = to_number(:PLAN_ID) and PAYITEM_CODE = :PAYITEM_CODE and START_CYCLE_ID = :START_CYCLE_ID