SELECT   
     to_char(a.PARTITION_ID) PARTITION_ID, to_char(a.USER_ID) USER_ID, to_char(b.ACCT_ID) ACCT_ID, to_char(a.PLAN_ID) PLAN_ID, to_char(a.PAYITEM_CODE) PAYITEM_CODE, to_char(b.ACCT_PRIORITY) ACCT_PRIORITY, to_char(b.USER_PRIORITY) USER_PRIORITY, to_char(b.ADDUP_MONTHS) ADDUP_MONTHS, b.ADDUP_METHOD, b.DEFAULT_TAG, a.BIND_TYPE, a.ACT_TAG, a.LIMIT_TYPE, to_char(a.LIMIT) LIMIT, a.COMPLEMENT_TAG, to_char(b.INST_ID) INST_ID, a.RULE_ID, a.START_CYCLE_ID, a.END_CYCLE_ID, to_char(a.UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, a.UPDATE_STAFF_ID, a.UPDATE_DEPART_ID, a.REMARK, a.RSRV_STR1, a.RSRV_STR2, a.RSRV_STR3, a.RSRV_STR4, a.RSRV_STR5, a.RSRV_STR6, a.RSRV_STR7, a.RSRV_STR8, a.RSRV_STR9, a.RSRV_STR10
 FROM TF_F_USER_PAYITEM a, TF_A_PAYRELATION b 
 WHERE a.USER_ID=:USER_ID AND a.PARTITION_ID = MOD(TO_NUMBER(:USER_ID),10000)
  AND a.USER_ID=b.USER_ID
  AND a.PARTITION_ID=b.PARTITION_ID
  AND a.PLAN_ID=:PLAN_ID
  AND a.PAYITEM_CODE=b.PAYITEM_CODE
  AND a.ACT_TAG='1'
  AND b.ACT_TAG='1'
  AND TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN a.start_cycle_id AND a.end_cycle_id
  AND TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN b.start_cycle_id AND b.end_cycle_id