--IS_CACHE=Y
select * from (SELECT 1 ITEM_NUM, A.ITEM_ID, A.ITEM_NAME, A.ITEM_TYPE, A.ITEM_TYPE_ANAME,
A.ITEM_TYPE_A, A.ITEM_TYPE_BNAME, A.ITEM_TYPE_B, A.STORE_TYPE,
A.ITEM_NET_TYPE, A.PROVINCE, A.ITEM_EPRICE, A.ITEM_BPRICE,
A.VENDOR_ID, A.VENDOR_NAME, A.ITEM_STATUS, A.STATE,
TO_CHAR(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
A.RSRV_STR1, A.RSRV_STR2, A.RSRV_STR3, A.RSRV_STR4, A.RSRV_STR5,
A.RSRV_STR6, A.RSRV_STR7, A.RSRV_STR8, A.RSRV_STR9, A.RSRV_STR10,
B.SCORE_VALUE,B.LEVEL_TYPE,B.LEVEL_TYPE_CODE,B.LEVEL_TYPE_DESC
FROM UCR_CEN1.TD_B_UPMS_GIFT A, UCR_CEN1.TD_B_UPMS_GIFT_SCORE B
WHERE 1 = 1
AND A.ITEM_ID = :ITEM_ID
AND B.ITEM_ID = A.ITEM_ID
AND B.STATE='0'
AND A.STATE='0'
ORDER BY A.update_time desc,B.update_time DESC)C
where rownum=1