INSERT INTO TI_B_SCORERELATION
        (SYNC_SEQUENCE, SYNC_DAY, MODIFY_TAG, TRADE_ID, PARTITION_ID,
         PAYRELATION_ID, USER_ID, LIMIT_TYPE, LIMIT_VALUE, INTEGRAL_ACCT_ID,
         DEFAULT_TAG, ACT_TAG, START_DATE, END_DATE, UPDATE_TIME,
         UPDATE_DEPART_ID, UPDATE_STAFF_ID, RSRV_STR1, RSRV_STR2, RSRV_STR3,
         RSRV_NUM1, RSRV_NUM2, RSRV_NUM3, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3)
        SELECT :SYNC_SEQUENCE, :SYNC_DAY,
               DECODE(MODIFY_TAG, '0', '0', '1', '2', '2', '2', '2'),
               :TRADE_ID, MOD(USER_ID, 10000), PAYRELATION_ID, USER_ID,
               LIMIT_TYPE, LIMIT_VALUE, INTEGRAL_ACCT_ID, DEFAULT_TAG, ACT_TAG,
               START_DATE, END_DATE, UPDATE_TIME, UPDATE_DEPART_ID,
               UPDATE_STAFF_ID, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_NUM1,
               RSRV_NUM2, RSRV_NUM3, RSRV_DATE1, RSRV_DATE2, RSRV_DATE3
          FROM TF_B_TRADE_SCORERELATION
         WHERE TRADE_ID = :TRADE_ID
           AND ACCEPT_MONTH = :ACCEPT_MONTH