SELECT *
  FROM TF_B_GRP_SCOREDONATE T
 WHERE 1 = 1
   AND T.BATCH_ID = :BATCH_ID
   AND T.TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND T.IMPORT_TIME + 0 >= TO_DATE(:IMPORT_START, 'YYYY-MM-DD') 
   AND T.IMPORT_TIME + 0 <= TO_DATE(:IMPORT_END, 'YYYY-MM-DD') + 1
   AND T.SERIAL_NUMBER_OUT = :SERIAL_NUMBER_OUT
   AND T.SERIAL_NUMBER_IN = :SERIAL_NUMBER_IN
   AND T.STATUS = :STATUS