SELECT COUNT(1) recordcount
  FROM TF_F_USER A
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND REMOVE_TAG = '0'
   AND USER_TAG_SET IS NOT NULL
   AND SUBSTR(USER_TAG_SET, 0, 1) = '3'
   AND rownum < 2