SELECT *
  FROM TF_B_NPCHECK T
 WHERE 1 = 1
   AND T.ACCEPT_DATE + 0 >= TO_DATE(:ACT_START, 'YYYY-MM-DD') 
   AND T.ACCEPT_DATE + 0 <= TO_DATE(:ACT_END, 'YYYY-MM-DD') + 1
   AND T.SERIAL_NUMBER = :SERIAL_NUMBER
   AND T.STATE = :STATE