update TF_B_TRADE_RECEIPT
 SET END_DATE = SYSDATE,
     VERIFY_STAFF_ID=:ERIFY_STAFF_ID,
     VERIFY_DEPART_ID=:ERIFY_DEPART_ID,
     VERIFY_TIME=:ERIFY_TIME,
     VERIFY_STATUE=:ERIFY_STATUE,
     VERIFY_SUGGESTION=:ERIFY_SUGGESTION,
     OP_TAG=:OP_TAG
     WHERE 
     TRADE_TYPE_CODE = :TRADE_TYPE_CODE 
    AND  BRAND_CODE = :BRAND_CODE
    AND  PRODUCT_ID = :PRODUCT_ID
    AND  TRADE_ATTR = :TRADE_ATTR
    AND  START_DATE =TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')
    AND  EPARCHY_CODE =:EPARCHY_CODE