--IS_CACHE=Y
SELECT EPARCHY_CODE,PARA_ATTR,PARA_CODE,PARA_NAME,PARA_CODE1,PARA_CODE2,PARA_CODE3,PARA_CODE4,PARA_CODE5,PARA_CODE6,to_char(PARA_DATE7,'yyyy-mm-dd hh24:mi:ss') PARA_DATE7,to_char(PARA_DATE8,'yyyy-mm-dd hh24:mi:ss') PARA_DATE8,to_char(PARA_DATE9,'yyyy-mm-dd hh24:mi:ss') PARA_DATE9,to_char(PARA_DATE10,'yyyy-mm-dd hh24:mi:ss') PARA_DATE10,REMARK,UPDATE_STAFF_ID,UPDATE_DEPART_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TD_A_INGW_COMMPARA
 WHERE EPARCHY_CODE = :EPARCHY_CODE
   AND PARA_ATTR = :PARA_ATTR