SELECT A.ATTR_VALUE
FROM TF_F_USER T, TF_F_USER_OTHER O,TF_F_USER_ATTR A  
WHERE 1=1  
AND T.CUST_ID= :CUST_ID
AND T.PRODUCT_ID = :PRODUCT_ID
AND A.ATTR_CODE = :ATTR_CODE
AND T.REMOVE_TAG = '0'
AND A.INST_TYPE = 'P'    
AND T.USER_ID = O.USER_ID  
AND A.USER_ID = O.USER_ID
AND T.PARTITION_ID = O.PARTITION_ID
AND T.PARTITION_ID = A.PARTITION_ID
AND T.PARTITION_ID = MOD(T.USER_ID, 10000)
AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE