SELECT * FROM (
SELECT A.TRADE_ID DEAL_ID,
       '2' DEAL_TAG,
       '1' DEAL_STATE,
       A.TRADE_EPARCHY_CODE DEAL_EPARCHY_CODE
  FROM TI_B_EC A
 WHERE EXISTS (SELECT 1
          FROM TF_B_TRADE B
         WHERE A.OPR_SEQ = B.TRADE_ID
           AND B.SUBSCRIBE_STATE IN ('M'))
   AND A.MODIFY_TAG = '1'
   AND A.STATUS = '2'
   AND A.OPR_SEQ NOT LIKE 'crm%'
   $CONDITIONSQL)
WHERE ROWNUM <= :ROW_COUNT