SELECT * FROM TF_B_GONET_REG_LOG T WHERE T.KF_TRADE_ID =:KF_TRADE_ID AND
TO_DATE(:START_TIME,'yyyy-MM-dd HH24:mi:ss')=START_TIME AND TO_DATE(:END_TIME,'yyyy-MM-dd HH24:mi:ss')=END_TIME
ORDER BY T.QUERY_END_TIME