SELECT     T.TRADE_TYPE_CODE,
	T.IN_MODE_CODE,
	T.ORDER_TYPE_CODE,
	T.FUNC_TYPE,
	T.CHECK_PARAM,
	T.SVC_NAME,
	T.SVC_DESCRIPTION,
	T.PARA_CODE1,
	T.PARA_CODE2,
	T.PARA_CODE3,
                   T.FORWORD_TYPE,
	T.EPARCHY_CODE,
	T.START_DATE,
	T.END_DATE
FROM  TD_S_SVC_COLLE_CONFIG T 
 WHERE T.FUNC_TYPE=:FUNC_TYPE 
  AND  T.EPARCHY_CODE=:EPARCHY_CODE
  AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE