UPDATE TF_F_CUST_FAMILY
   SET REMOVE_TAG       = '0',
       REMOVE_DATE      = '',
       REMOVE_STAFF_ID  = '',
       REMOVE_DEPART_ID = '',
       REMOVE_REASON    = '',
       UPDATE_TIME      = TO_DATE(:UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
WHERE PARTITION_ID = MOD(TO_NUMBER(:HOME_CUST_ID), 10000)
   AND HOME_CUST_ID = TO_NUMBER(:HOME_CUST_ID)
   AND REMOVE_TAG = '1'
   and REMOVE_DATE > TO_DATE(:UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS')