SELECT GROUP_NAME,
       GROUP_ID,
       ORDER_ID,
       ANNUAL_REVIEW_RESULT,
       TO_CHAR(ANNUAL_REVIEW_DATE, 'yyyy-MM-dd') ANNUAL_REVIEW_DATE,
       VIOLATION_RECORD
  FROM TD_B_EOP_VOICELINE_ANNUAL
 where 1 = 1
   AND GROUP_NAME = :GROUP_NAME
   AND GROUP_ID = :GROUP_ID
   AND ORDER_ID = :ORDER_ID