--IS_CACHE=Y
SELECT
  A.STORAGE_ID,
  A.SERVER_IP,
  A.DIR_NAME,
  A.FILE_NAME,
  A.OPER_DATE
FROM
  TD_S_CONT_STORAGE A
WHERE 1=1
  AND A.STORAGE_ID = :STORAGE_ID
  AND to_char(A.OPER_DATE ,'yyyy-MM-dd') = :OPER_DATE