select DISCNT_GIFT_ID ELEMENT_ID,
       'A' ELEMENT_TYPE_CODE,
       '0' MODIFY_TAG,
       :START_DATE START_DATE,
       :END_DATE END_DATE
  from TF_B_TRADE_SALE_DEPOSIT
 where TRADE_ID = TO_NUMBER(:TRADE_ID)
   and ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))