INSERT INTO TF_B_TRADE_DISCNT
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   USER_ID_A,
   PACKAGE_ID,
   PRODUCT_ID,
   DISCNT_CODE,
   SPEC_TAG,
   RELATION_TYPE_CODE,
   INST_ID,
   CAMPN_ID,
   START_DATE,
   END_DATE,
   MODIFY_TAG,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  SELECT TO_NUMBER(:TRADE_ID),
          TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         c.USER_ID,
         c.USER_ID_A,
         c.PACKAGE_ID,
         c.PRODUCT_ID,
         c.DISCNT_CODE,
         c.SPEC_TAG,
         c.RELATION_TYPE_CODE,
         c.INST_ID,
         c.CAMPN_ID,
         c.START_DATE,
         trunc(add_months(sysdate, 1), 'mm') - 1 / 24 / 3600,
         :MODIFY_TAG,
         SYSDATE,
         :UPDATE_STAFF_ID,
         :UPDATE_DEPART_ID,
         '状态变更终止平台的所有优惠',
         c.RSRV_NUM1,
         c.RSRV_NUM2,
         c.RSRV_NUM3,
         c.RSRV_NUM4,
         c.RSRV_NUM5,
         c.RSRV_STR1,
         c.RSRV_STR2,
         c.RSRV_STR3,
         c.RSRV_STR4,
         c.RSRV_STR5,
         c.RSRV_DATE1,
         c.RSRV_DATE2,
         c.RSRV_DATE3,
         c.RSRV_TAG1,
         c.RSRV_TAG2,
         c.RSRV_TAG3
    FROM TF_F_USER_DISCNT c
   WHERE c.USER_ID = TO_NUMBER(:USER_ID)
     AND c.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND c.discnt_code IN (select to_number(a.para_code2)
                             from td_s_commpara a
                            where a.subsys_code = 'CSM'
                              and a.param_attr = 3700) 
     AND SYSDATE between c.start_date and c.end_date