SELECT ATTR_VALUE FROM TF_F_USER_ATTR A WHERE
A.PARTITION_ID =  MOD(TO_NUMBER(:USER_ID),10000) 
AND A.USER_ID = :USER_ID
AND A.SERVICE_ID = :SERVICE_ID
AND A.ATTR_CODE='302'
AND A.RELA_INST_ID = :RELA_INST_ID
AND A.END_DATE > SYSDATE