select  
  ORDER_ID,      
  SUBORDER_ID,   
  SERIAL_NUMBER, 
  ORDER_STATU,   
  ORDER_TYPE,    
  PREV_STATU,    
  OPRTIME,       
  UPDATE_DESC,   
  LOGISTID,      
  SHIP_SEQ,      
  SHIP_ADDR,     
  SHIP_DATE,     
  SHIP_REMARK,   
  DELIV_PERSON,  
  REC_TIME,     
  REC_PERSON,    
  REC_REMARK,    
  PROC_STATU
  from  TI_B_SCORE_ORDER_STATUS_SYN
  where (ORDER_ID = :ORDER_ID OR :ORDER_ID IS NULL)
  AND (SUBORDER_ID = :SUBORDER_ID OR :SUBORDER_ID IS NULL)
  AND (SERIAL_NUMBER = :SERIAL_NUMBER OR :SERIAL_NUMBER IS NULL)
  AND (OPRTIME BETWEEN TO_DATE(':START_DATE', 'yyyy-mm-dd hh24:mi:ss') AND TO_DATE(':END_DATE', 'yyyy-mm-dd hh24:mi:ss'))