SELECT to_char(TRADE_ID) TRADE_ID,CANCEL_TAG,to_char(ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,TRADE_DEPART_ID,TRADE_STAFF_ID,TRADE_TYPE_CODE,PARAM_CODE,REMARK,AUDIT_STAFF_ID,to_char(AUDIT_DATE,'yyyy-mm-dd hh24:mi:ss') AUDIT_DATE,AUDIT_TAG,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8
  FROM TS_A_DIFFERINFO
 WHERE trunc(ACCEPT_DATE)=trunc(TO_DATE(:AUDIT_DATE,'YYYY-MM-DD HH24:MI:SS'))
   AND TRADE_DEPART_ID = :TRADE_DEPART_ID