SELECT B.SERIAL_NUMBER,
       A.PAY_NAME,
       A.ACCT_ID,
       A.PAY_MODE_CODE,
       A.RSRV_STR3     POST_CODE,
       A.RSRV_STR10    POST_ADDRESS,
       A.CONTRACT_NO
  FROM TF_F_ACCOUNT A, TF_F_USER B, TF_A_PAYRELATION C
 WHERE 1 = 1
   AND A.BANK_CODE = :BANK_CODE
   AND A.REMOVE_TAG = '0'
   AND A.BANK_ACCT_NO = :BANK_ACCT_NO
   AND A.ACCT_ID = C.ACCT_ID
   AND C.USER_ID = B.USER_ID
   AND C.DEFAULT_TAG = '1'
   AND C.ACT_TAG = '1'
   AND B.REMOVE_TAG || NULL = '0'
   AND A.PAY_MODE_CODE NOT IN ('0', '5')
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN C.START_CYCLE_ID AND
       C.END_CYCLE_ID