--IS_CACHE=N
SELECT A.EPARCHY_CODE 归属地州,TO_CHAR(A.USER_ID) 用户标识,ACCT_TAG 是否激活, B.BRAND_CODE 用户品牌, A.CITY_CODE 用户业务区, A.CUST_ID 客户标识,TO_CHAR(A.OPEN_DATE,'YYYYMM') 入网月份,TRUNC(SYSDATE)-TRUNC(A.OPEN_DATE) 入网天数,TO_CHAR(A.OPEN_DATE,'YYYYMMDD') 入网日期
  FROM TF_F_USER A, TF_F_USER_PRODUCT B
 WHERE A.REMOVE_TAG = '0'
   AND A.SERIAL_NUMBER =:SERIAL_NUMBER
   AND A.USER_ID = B.USER_ID
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND B.MAIN_TAG='1'
