insert into TF_B_POPRODUCT_MBMP(TRADE_ID           ,PARTITION_ID       ,USER_ID            ,POSPECNUMBER   
,PRODUCTSPECNUMBER  ,PRODUCTORDERNUMBER ,PRODUCTID        ,OPER_CODE          ,BIZ_CODE           ,RB_LIST            ,RSRV_STR1      
,RSRV_STR2          ,RSRV_STR3          ,RSRV_STR4,RSRV_STR5,RSRV_NUM1          ,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5          ,RSRV_DATE1         ,RSRV_DATE2     
,RSRV_DATE3,START_DATE         ,END_DATE  ,REMARK  ,UPDATE_STAFF_ID       , UPDATE_DEPART_ID,UPDATE_TIME          )
Values(:TRADE_ID, MOD(TO_NUMBER(:USER_ID),10000), :USER_ID,
:POSpecNumber,:ProductSpecNumber,:ProductOrderNumber,:PRODUCT_ID,:OPER_CODE,:BIZ_CODE, :RB_LIST,:RSRV_STR1, :RSRV_STR2, :RSRV_STR3,:RSRV_STR4
,:RSRV_STR5,:RSRV_NUM1, :RSRV_NUM2,:RSRV_NUM3,:RSRV_NUM4,:RSRV_NUM5,  :RSRV_DATE1, :RSRV_DATE2,:RSRV_DATE3,TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS'), TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS'), :REMARK,            :UPDATE_STAFF_ID,   :UPDATE_DEPART_ID ,:UPDATE_TIME)