select  TO_CHAR(a.trade_id) trade_id,
        a.accept_month,
        a.inst_id,
        a.user_id,
        a.serial_number,
        a.merch_spec_code,
        a.merch_order_id,
        a.merch_offer_id,
        a.group_id,
        a.opr_source,
        a.biz_mode,
        a.status,
        a.host_company,
        a.RSRV_STR5,
        a.modify_tag,
        a.start_date,
        a.end_date,
        a.RSRV_NUM1	,
a.RSRV_NUM2	,
a.RSRV_NUM3	,
a.RSRV_NUM4	,
a.RSRV_NUM5	,
a.RSRV_STR1	,
a.RSRV_STR2	,
a.RSRV_STR3	,
a.RSRV_STR4	,
a.RSRV_STR5	,
a.RSRV_DATE1,
a.RSRV_DATE2,
a.RSRV_DATE3,
a.RSRV_TAG1	,
a.RSRV_TAG2	,
a.RSRV_TAG3	 
   FROM TF_B_TRADE_GRP_MERCH a
 WHERE a.trade_id = TO_NUMBER(:TRADE_ID)
   AND a.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))