SELECT NVL(SUM(A.BATCH_COUNT), 0) MONTH_COUNT
  FROM TF_B_TRADE_BAT A, TF_B_TRADE_BAT_TASK B
 WHERE 1 = 1
   AND B.BATCH_TASK_ID = A.BATCH_TASK_ID
   AND TO_CHAR(A.ACCEPT_DATE, 'YYYY-MM') = :YEAR_MONTH
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:YEAR_MONTH, 5, 6))
   AND B.BATCH_OPER_CODE = :BATCH_OPER_TYPE
   AND A.BATCH_OPER_TYPE = :BATCH_OPER_TYPE
   AND A.REMOVE_TAG = '0'
