SELECT A.BATCH_TASK_ID,
       A.BATCH_ID,
       A.BATCH_OPER_TYPE,
       TO_CHAR(A.ACCEPT_DATE, 'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE,
       A.STAFF_ID,
       A.DEPART_ID,
       A.CITY_CODE,
       A.EPARCHY_CODE,
       A.TERM_IP,
       A.IN_MODE_CODE,
       A.BATCH_COUNT,
       A.REMOVE_TAG,
       A.ACTIVE_FLAG,
       TO_CHAR(A.ACTIVE_TIME, 'YYYY-MM-DD HH24:MI:SS') ACTIVE_TIME,
       A.AUDIT_STATE,
       A.AUDIT_REMARK,
       TO_CHAR(A.AUDIT_DATE, 'YYYY-MM-DD HH24:MI:SS') AUDIT_DATE,
       A.AUDIT_STAFF_ID,
       A.AUDIT_DEPART_ID,
       A.AUDIT_INFO,
       A.ACCEPT_MONTH,
       A.DST_ONE_KEY_FLAG
  FROM TF_B_TRADE_BAT A
 WHERE 1 = 1
   AND EXISTS (SELECT 1
          FROM TD_B_BATCHTYPE T
         WHERE T.BATCH_OPER_TYPE = A.BATCH_OPER_TYPE
           AND T.TRADE_ATTR = :TRADE_ATTR
           AND T.USE_TAG = '1')
   AND EXISTS (SELECT 1 FROM TF_B_TRADE_BATDEAL E WHERE E.BATCH_ID = A.BATCH_ID  AND E.ACCEPT_MONTH = TO_NUMBER(SUBSTR(A.BATCH_ID, 5, 2)) AND E.SERIAL_NUMBER = :SERIAL_NUMBER)
   AND A.AUDIT_REMARK LIKE '%' || :AUDIT_REMARK || '%'
   AND A.DST_ONE_KEY_FLAG = :DST_ONE_KEY_FLAG
   AND A.BATCH_OPER_TYPE = :BATCH_OPER_TYPE
   AND A.STAFF_ID = :STAFF_ID
   AND A.ACCEPT_DATE >= TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')
   AND A.ACCEPT_DATE <= TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS') + 1
   AND A.ACTIVE_FLAG = :ACTIVE_FLAG
   AND A.AUDIT_STATE = :AUDIT_STATE
   AND A.BATCH_TASK_ID = :BATCH_TASK_ID
   AND A.BATCH_ID = :BATCH_ID
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:BATCH_ID, 5, 2))
   AND REMOVE_TAG = :REMOVE_TAG
 ORDER BY A.ACCEPT_DATE DESC
