SELECT T.TIMER_ID,
	   T.TIMER_TYPE,
	   T.TIMER_OBJECT,
       T.OFFSET_LOCATION,
       T.OFFSET_MODE,
       T.OFFSET_TYPE,
       T.OFFSET_VALUE,
       T.OFFSET_EXP,
       T.OFFSET_EXCLUDE,
       T.WARN_NUM,
       T.WARN_CONTENT,
       T.WARN_SVC,
       T.VALID_TAG,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TD_B_EWE_TASK_TIMER T
 WHERE T.TIMER_ID = :TIMER_ID
   AND T.TIMER_TYPE = :TIMER_TYPE
   AND T.VALID_TAG = :VALID_TAG
