SELECT TO_CHAR(A.TRADE_ID) TRADE_ID,
       A.ACCEPT_MONTH,
       A.PARTITION_ID,
       TO_CHAR(A.USER_ID) USER_ID,
       TO_CHAR(A.USER_ID_A) USER_ID_A,
       A.DISCNT_CODE,
       A.SPEC_TAG,
       A.RELATION_TYPE_CODE,
       TO_CHAR(A.INST_ID) INST_ID,
       TO_CHAR(A.CAMPN_ID) CAMPN_ID,
       TO_CHAR(A.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(A.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       A.RSRV_NUM4,
       A.RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       TO_CHAR(A.RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_CHAR(A.RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_CHAR(A.RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3
  FROM TF_B_TRADE_DISCNT_BAK A,TF_F_USER_OFFER_REL B
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.END_DATE > SYSDATE
   AND A.USER_ID=B.USER_ID
   AND A.DISCNT_CODE=B.REL_OFFER_CODE
   AND B.OFFER_TYPE='K'
   AND A.INST_ID=B.REL_OFFER_INS_ID