--IS_CACHE=Y
SELECT EPARCHY_CODE  ,CODE_TYPE_CODE,CODE_TYPE,REMARK,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_I 
  FROM TD_M_CODETYPE
 WHERE EPARCHY_CODE=:EPARCHY_CODE
   AND CODE_TYPE_CODE=:CODE_TYPE_CODE
   AND CODE_TYPE=:CODE_TYPE