INSERT INTO TF_F_USER_TRUNK
  (USER_TRUNK_ID,
   MSC_ID,
   TRUNK_ID,
   USER_ID,
   START_DATE,
   END_DATE,
   INST_ID,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK)
VALUES
  (TO_NUMBER(:RSRV_STR1),
   TO_NUMBER(:RSRV_STR2),
   :RSRV_NUM1,
   TO_NUMBER(:USER_ID),
   TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
   TO_NUMBER(:INST_ID),
   SYSDATE,
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID,
   :REMARK)