SELECT A.SERIAL_NUMBER_B,
       A.SHORT_CODE,
       A.SERIAL_NUMBER_A,
       B.VPN_NAME,
       B.CUST_MANAGER,
       C.CITY_CODE
  FROM uop_crm1.TF_F_RELATION_UU A, uop_crm1.TF_F_USER_VPN B, uop_crm1.TF_F_USER C
 WHERE A.USER_ID_A = B.USER_ID 
   AND B.USER_ID = C.USER_ID
   AND B.PARTITION_ID = MOD(A.USER_ID_A, 10000)
   AND C.PARTITION_ID = B.PARTITION_ID
   AND A.RELATION_TYPE_CODE =:RELATION_TYPE_CODE
   AND A.USER_ID_A = TO_NUMBER(:USER_ID_A) 
   AND B.REMOVE_TAG = '0'
   AND C.REMOVE_TAG = '0'
   AND (TRIM(A.SHORT_CODE) IS NULL OR SUBSTR(A.SHORT_CODE, 1, 1) != '6' OR
       LENGTH(A.SHORT_CODE) < 3 OR LENGTH(A.SHORT_CODE) > 6)
   AND A.END_DATE > SYSDATE