insert into TF_F_PO_MBMP
(PARTITION_ID      ,USER_ID           ,SERIAL_NUMBER     ,OPR_SOURCE        ,POSPECNUMBER 
,STATUS,PRODUCTOFFERINGID,POORDERNUMBER     ,BUSINESSMODE      ,HOSTCOMPANY       ,START_DATE      
,END_DATE     
,RSRV_STR1         ,RSRV_STR2         ,RSRV_STR3         ,RSRV_STR4         ,RSRV_STR5         ,RSRV_NUM1    
,RSRV_NUM2         ,RSRV_DATE1        ,RSRV_DATE2        ,     
REMARK  ,UPDATE_STAFF_ID       , UPDATE_DEPART_ID,UPDATE_TIME)
select PARTITION_ID      ,USER_ID           ,SERIAL_NUMBER     ,OPR_SOURCE        ,POSPECNUMBER 
,decode(b.oper_code,'1','A','2','E','3','N','4','A',5,'A'),PRODUCTOFFERINGID,POORDERNUMBER     ,BUSINESSMODE     
,HOSTCOMPANY       ,START_DATE      
,END_DATE     
,RSRV_STR1         ,RSRV_STR2         ,RSRV_STR3         ,RSRV_STR4         ,RSRV_STR5         ,RSRV_NUM1    
,RSRV_NUM2         ,RSRV_DATE1        ,RSRV_DATE2        ,     
REMARK  ,UPDATE_STAFF_ID       , UPDATE_DEPART_ID,UPDATE_TIME
from TF_B_TRADE_PO_MBMP b where trade_id=TO_NUMBER(:TRADE_ID)