SELECT IBSYSID,
       RECORD_NUM,
       BUSI_STATE,
       ACCEPT_MONTH,
       PRODUCT_NO,
       SERIALNO,
       TRADE_ID,
       CREATE_DATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3
  FROM TF_B_EOP_EOMS_STATE A
 WHERE 1 = 1
   AND (A.IBSYSID = :IBSYSID OR :IBSYSID is null)
   AND A.PRODUCT_NO = :PRODUCT_NO
   ORDER BY CREATE_DATE DESC