UPDATE TF_F_USER_PLATSVC_ATTR
SET END_DATE=TO_DATE(:END_DATE,'yyyy-mm-dd hh24:mi:ss'),
    UPDATE_TIME=SYSDATE,
    UPDATE_STAFF_ID=:UPDATE_STAFF_ID,
    UPDATE_DEPART_ID=:UPDATE_DEPART_ID
     WHERE  PARTITION_ID=TO_NUMBER(mod(:USER_ID,10000))
		and USER_ID=TO_NUMBER(:USER_ID)
		and SERVICE_ID=TO_NUMBER(:SERVICE_ID)
		and END_DATE>TO_DATE(:END_DATE,'yyyy-mm-dd hh24:mi:ss')
		and INFO_CODE=:INFO_CODE