SELECT A.ID,
       A.BILL_ID,
       A.ID_TYPE,
       A.PARTITION_ID,
       A.EFFECT_ITEM_CODE,
       A.ACT_MODE,
       A.EFFECT_MODE,
       A.ADDUP_MODE,
       A.EFFECT_VALUE_TYPE,
       TO_CHAR(A.EFFECT_VALUE) EFFECT_VALUE,
       TO_CHAR(A.REFER_FEE) REFER_FEE,
       A.START_ACYC_ID,
       A.END_ACYC_ID,
       TO_CHAR(A.REMAINFEE) REMAINFEE,
       TO_CHAR(A.USE_FEE1) USE_FEE1,
       TO_CHAR(A.USE_FEE2) USE_FEE2,
       TO_CHAR(A.LIMIT_FEE) LIMIT_FEE,
       A.RECV_TAG,
       A.ADJUST_REASON_ID,
       TO_CHAR(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       A.ADJUST_DEPART_ID,
       A.ADJUST_STAFF_ID,
       A.ADJUST_EPARCHY_CODE
  FROM TF_A_ADJUSTBBILL A, TF_F_USER B,TF_A_PAYRELATION C
 WHERE A.ID = C.ACCT_ID
   AND C.USER_ID = B.USER_ID
   AND B.REMOVE_TAG = '0'
   AND C.DEFAULT_TAG='1'
   AND A.ID_TYPE='1'
   AND (B.SERIAL_NUMBER >= :START_SERIAL_NUMBER OR
       :START_SERIAL_NUMBER IS NULL)
   AND (B.SERIAL_NUMBER <= :END_SERIAL_NUMBER OR
       :END_SERIAL_NUMBER IS NULL)
   AND (A.ADJUST_STAFF_ID >= :X_START_STAFF_ID OR
       :X_START_STAFF_ID IS NULL)
   AND (A.ADJUST_STAFF_ID <= :X_END_STAFF_ID OR :X_END_STAFF_ID IS NULL)
   AND (A.UPDATE_TIME >= TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss') OR
       :START_DATE IS NULL)
   AND (A.UPDATE_TIME <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss') OR
       :END_DATE IS NULL)