SELECT TO_CHAR(UU.USER_ID_B) USER_ID_B, TO_CHAR(UU.USER_ID_A) USER_ID_A,
       UU.SERIAL_NUMBER_B, UU.SHORT_CODE, D.DISCNT_CODE,
       TO_CHAR(UU.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(UU.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(UU.INST_ID) U_INST_ID, TO_CHAR(D.INST_ID) D_INST_ID
  FROM TF_F_RELATION_UU UU, TF_F_USER U, TF_F_USER_DISCNT D
 WHERE U.USER_ID = UU.USER_ID_B
   AND U.PARTITION_ID = MOD(UU.USER_ID_B, 10000)
   AND UU.USER_ID_A = TO_NUMBER(:USER_ID_A)
   AND UU.END_DATE > TRUNC(LAST_DAY(SYSDATE)+1)+0
   AND UU.USER_ID_A = D.USER_ID_A
   AND U.USER_ID = D.USER_ID
   AND U.PARTITION_ID = D.PARTITION_ID
   AND D.RELATION_TYPE_CODE = '45'
   AND UU.RELATION_TYPE_CODE = '45'
   AND U.REMOVE_TAG = '0'
   AND SYSDATE BETWEEN UU.START_DATE AND UU.END_DATE
   AND SYSDATE BETWEEN D.START_DATE AND D.END_DATE
 ORDER BY UU.START_DATE
