SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_RELATION_UU A
 WHERE A.ROLE_CODE_B=:ROLE_CODE_B
   AND A.PARTITION_ID=MOD(TO_NUMBER(:USER_ID_B),10000)
   AND A.USER_ID_B=TO_NUMBER(:USER_ID_B)
   AND A.RELATION_TYPE_CODE=:RELATION_TYPE_CODE
   AND A.END_DATE < TRUNC(ADD_MONTHS(SYSDATE,1),'mm')
   AND A.END_DATE > TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1)))+1-1/24/3600
