SELECT T.SERIAL_NUMBER,T.USER_ID,T.SERIAL_NUMBER,T.CUST_ID,T.TRADE_STAFF_ID,
       T.TRADE_DEPART_ID,T.TRADE_ID,'1' TEMP_TAG
  FROM TF_BH_TRADE T
 WHERE T.TRADE_ID = :TRADE_ID
 	 AND T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
	 AND T.SUBSCRIBE_STATE = :SUBSCRIBE_STATE