SELECT 
A.PARTITION_ID,
A.USER_ID_A,
A.SERIAL_NUMBER_A,
A.USER_ID_B,
A.SERIAL_NUMBER_B,
A.RELATION_TYPE_CODE,
A.ROLE_TYPE_CODE,
A.ROLE_CODE_A,
A.ROLE_CODE_B,
A.ORDERNO,
A.SHORT_CODE,
A.INST_ID,
TO_CHAR(A.START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,
TO_CHAR(A.END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE,
TO_CHAR(A.UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
A.UPDATE_STAFF_ID,
A.UPDATE_DEPART_ID,
A.REMARK,
A.RSRV_NUM1,
A.RSRV_NUM2,
A.RSRV_NUM3,
A.RSRV_NUM4,
A.RSRV_NUM5,
A.RSRV_STR1,
A.RSRV_STR2,
A.RSRV_STR3,
A.RSRV_STR4,
A.RSRV_STR5,
TO_CHAR(A.RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
TO_CHAR(A.RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
TO_CHAR(A.RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,
A.RSRV_TAG1,
A.RSRV_TAG2,
A.RSRV_TAG3
FROM TF_F_RELATION_UU A
 WHERE A.partition_id=MOD(TO_NUMBER(:USER_ID_B),10000)
   AND A.user_id_b=TO_NUMBER(:USER_ID_B)
   AND A.relation_type_code=:RELATION_TYPE_CODE
   AND A.role_code_b=:ROLE_CODE_B
   AND A.end_date>sysdate