--IS_CACHE=Y
SELECT RULE_ID, PRODUCT_ID, PACKAGE_ID, ELEMENT_TYPE_CODE, ELEMENT_ID, to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE, to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE, EPARCHY_CODE, to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME, UPDATE_STAFF_ID, UPDATE_DEPART_ID, REMARK, RSRV_STR1, RSRV_STR2, RSRV_STR3, RSRV_STR4
 FROM TD_B_GROUP_DESIGN_DETAILRULE
 WHERE RULE_ID=TO_NUMBER(:RULE_ID)
 AND SYSDATE BETWEEN START_DATE AND END_DATE