SELECT TO_CHAR(USER_ID) USER_ID,
       STAND_ADDRESS,
       DETAIL_ADDRESS,
       SIGN_PATH,
       PORT_TYPE,
       TO_CHAR(INST_ID) INST_ID,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       ACCT_PASSWD,
       TO_CHAR(STAND_ADDRESS_CODE) STAND_ADDRESS_CODE,
       PHONE,
       CONTACT,
       CONTACT_PHONE,
	   CONSTRUCTION_ADDR,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5
FROM TF_F_USER_WIDENET
WHERE USER_ID = TO_NUMBER(:USER_ID) AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
and sysdate >=start_date
and end_date>=sysdate