SELECT TO_CHAR(A.TRADE_ID) TRADE_ID,A.TRADE_TYPE_CODE,A.USER_ID, A.BPM_ID, A.SUBSCRIBE_STATE, B.BPM_CODE ,A.CANCEL_TAG, A.EPARCHY_CODE,
substr(B.tag_set,9,1) TRADE_SPLIT,
TO_CHAR(EXEC_TIME,'YYYY-MM-DD HH24:MI:SS') ACCEPT_DATE  
FROM TF_B_TRADE A ,TD_S_TRADETYPE B 
 WHERE  A.TRADE_TYPE_CODE = B.TRADE_TYPE_CODE 
AND A.CANCEL_TAG=:CANCEL_TAG AND A.TRADE_ID=:TRADE_ID 
AND A.accept_month = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))