--IS_CACHE=Y
SELECT STAFF_ID, DEPART_ID, STAFF_NAME, JOB_CODE, MANAGER_INFO, SEX, EMAIL,
       USER_PID, SERIAL_NUMBER, CUST_ID, DIMISSION_TAG,
       TO_CHAR(BIRTHDAY, 'yyyy-mm-dd hh24:mi:ss') BIRTHDAY, STAFF_GROUP_ID,
       CUST_HOBYY, MANAGER_STAFF_ID, RECEIVE_TYPE_CODE, LOGIN_FLAG,
       CUST_MANAGER_FLAG, CITY_CODE, EPARCHY_CODE, REMARK, RSVALUE1,
       RSVALUE2, START_DATE, END_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID, UPDATE_DEPART_ID, OPERATOR_KIND_CODE, RSVALUE3,
       RSVALUE4, RSVALUE5, RSVALUE6, RSRV_TAG1, RSRV_TAG2, RSRV_NUM1,
       RSRV_NUM2, RSRV_DATE1, RSRV_DATE2
  FROM TD_M_STAFF
 WHERE STAFF_ID = :STAFF_ID
   AND DIMISSION_TAG = '0'
   AND END_DATE > SYSDATE