Select B.EPARCHY_CODE,
       B.STAFF_ID AUDIT_STAFF_ID,
       B.STAFF_NAME,
       B.SERIAL_NUMBER STAFF_PHONE,
       B.DEPART_ID,
       C.DEPART_NAME,
       B.CITY_CODE
  From TD_M_STAFF B, TD_M_DEPART C, TF_M_STAFFDATARIGHT D
 Where 1=1
   And B.STAFF_ID = D.STAFF_ID
   And B.DEPART_ID = C.DEPART_ID
   And D.DATA_CODE = 'ESOP_AUDITSTAFF'
   And B.STAFF_NAME Like '%' || :STAFF_NAME || '%'
   And B.STAFF_ID <> :TRADE_STAFF_ID
 Order By B.STAFF_ID