--IS_CACHE=Y
SELECT B.EPARCHY_CODE,
       B.STAFF_ID,
       B.STAFF_NAME,
       B.SERIAL_NUMBER STAFF_PHONE,
       B.DEPART_ID,
       C.DEPART_NAME,
       B.CITY_CODE,
       D.AREA_NAME
  FROM TF_M_STAFFFUNCRIGHT A, TD_M_STAFF B, TD_M_DEPART C, TD_M_AREA D
 WHERE B.STAFF_ID = A.STAFF_ID
   AND B.DEPART_ID = C.DEPART_ID
   AND B.CITY_CODE = D.AREA_CODE
   AND A.RIGHT_CODE = :RIGHT_CODE
   AND B.CITY_CODE = :CITY_CODE 
   AND B.STAFF_NAME Like '%' || :STAFF_NAME || '%'