--IS_CACHE=Y
SELECT A.RULESET_ID,
       B.RULE_ID,
       B.RULE_TRIGGER_TYPE,
       B.OBJ_NAME,
       B.EVENT_NAME,
       B.SEQ_NO,
       C.FILE_NAME,
       C.FUNC_NAME
  FROM TD_B_RULESET A, TD_B_RULESET_RULE B, TD_B_RULE C
 WHERE A.RULESET_ID = :RULESET_ID
   AND A.RULESET_ID = B.RULESET_ID
   AND B.RULE_ID = C.RULE_ID
   AND A.STATE = '1'
   AND B.STATE = '1'
   AND C.STATE = '1'
