SELECT COUNT(1) RECORDCOUNT
  FROM TF_F_RELATION_UU
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID_B), 10000)
   AND USER_ID_B = TO_NUMBER(:USER_ID_B)
   AND RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND END_DATE < SYSDATE