UPDATE TD_RULE_FORALARM
  SET RULE_NAME = :RULE_NAME,
      PARAM_TYPE = :PARAM_TYPE,
      PARAM_A = :PARAM_A,
      PARAM_B = :PARAM_B,
      START_TIME = TO_DATE(:START_TIME, 'YYYY-MM-DD'),
      END_TIME = TO_DATE(:END_TIME, 'YYYY-MM-DD'),
      CLASS_NAME = trim(:CLASS_NAME),
      ALARM_LEVEL = :ALARM_LEVEL,
      MONITOR_OBJECT = :MONITOR_OBJECT,
      CYCLE_TYPE = :CYCLE_TYPE
WHERE RULE_ID = :RULE_ID