INSERT INTO TF_F_USER_SVC(PARTITION_ID,USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,INST_ID,CAMPN_ID,SERVICE_ID,
         MAIN_TAG,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,
         RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,
         RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT MOD(TO_NUMBER(USER_ID), 10000),TO_CHAR(USER_ID) USER_ID,USER_ID_A,PRODUCT_ID,PACKAGE_ID,INST_ID,CAMPN_ID,SERVICE_ID,
       NVL(MAIN_TAG, '0') MAIN_TAG,:START_DATE,:END_DATE,sysdate,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,
       RSRV_NUM3,TO_CHAR(RSRV_NUM4) RSRV_NUM4,TO_CHAR(RSRV_NUM5) RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,
       RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
    FROM TF_B_TRADE_SVC
   WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND MODIFY_TAG = :MODIFY_TAG
     AND USER_ID = TO_NUMBER(:USER_ID)
     AND USER_ID_A = TO_NUMBER(:USER_ID_A)
     AND PRODUCT_ID = :PRODUCT_ID
     AND PACKAGE_ID = :PACKAGE_ID
     AND SERVICE_ID = :SERVICE_ID
     AND START_DATE = TO_DATE(:TRADE_START_DATE, 'YYYY-MM-DD HH24:MI:SS')