INSERT INTO TD_S_STATIC
  (TYPE_ID,
   DATA_ID,
   DATA_NAME,
   PDATA_ID,
   SUBSYS_CODE,
   EPARCHY_CODE,
   REMARK,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   UPDATE_TIME,
   VALID_FLAG)
VALUES
  ('PAY_ITEM_NAME',
   (SELECT MAX(TO_NUMBER(DATA_ID)) + 1 FROM TD_S_STATIC WHERE TYPE_ID = 'PAY_ITEM_NAME'),
   :DATA_NAME,
   '',
   'CSM',
   '0898',
   :REMARK,
   :UPDATE_STAFF_ID,
   :UPDATE_DEPART_ID,
   SYSDATE,
   '0')