--IS_CACHE=N
SELECT D.DEPART_ID,D.DEPART_CODE,D.DEPART_NAME,D.AREA_CODE
FROM TD_M_DEPART D, TD_M_DEPARTKIND K
WHERE D.VALIDFLAG = '0'
AND D.DEPART_KIND_CODE = K.DEPART_KIND_CODE
AND K.CODE_TYPE_CODE = '0'
AND D.DEPART_ID = :DEPART_ID
AND D.DEPART_CODE LIKE '%'||:DEPART_CODE ||'%'
AND D.DEPART_NAME LIKE '%'||:DEPART_NAME ||'%'
AND D.AREA_CODE = :AREA_CODE
AND D.RSVALUE2 = :EPARCHY_CODE
AND (D.PARENT_DEPART_ID = :PARENT_DEPART_ID OR DEPART_ID = :PARENT_DEPART_ID)