--IS_CACHE=Y
SELECT PARA_CODE25
  FROM TD_S_COMMPARA a
 WHERE SUBSYS_CODE = 'CSM'
   AND PARAM_ATTR = 3701
   AND PARA_CODE5 ='4'
   AND PARA_CODE1=:BIZ_TYPE_CODE
   AND PARA_CODE2=:OPER_CODE
   AND PARA_CODE3=:SP_CODE
   AND PARA_CODE4=:BIZ_CODE