INSERT INTO TF_B_TRADE_ATTR(TRADE_ID,ACCEPT_MONTH,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,MODIFY_TAG,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT DISTINCT :TRADE_ID,TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),a.USER_ID,b.INST_TYPE, c.inst_id ,b.ATTR_CODE,b.ATTR_VALUE,c.start_date,to_date(:END_DATE,'yyyy-mm-dd hh24:mi:ss') end_date,c.modify_tag,SYSDATE,b.UPDATE_STAFF_ID,b.UPDATE_DEPART_ID,b.REMARK,b.RSRV_NUM1,b.RSRV_NUM2,b.RSRV_NUM3,b.RSRV_NUM4,b.RSRV_NUM5,b.RSRV_STR1,b.RSRV_STR2,b.RSRV_STR3,b.RSRV_STR4,b.RSRV_STR5,b.RSRV_DATE1,b.RSRV_DATE2,b.RSRV_DATE3,b.RSRV_TAG1,b.RSRV_TAG2,b.RSRV_TAG3
from tf_b_trade_svc_bak a,tf_b_trade_attr_bak b, tf_b_trade_svc c
WHERE a.trade_id = TO_NUMBER(:OLDTRADE_ID)
  AND b.trade_id = TO_NUMBER(:OLDTRADE_ID)
  AND a.inst_id =  b.inst_id
  AND c.trade_id = TO_NUMBER(:TRADE_ID)
  AND c.service_id = a.service_id
  AND c.user_id = a.user_id
  AND c.user_id_a = a.user_id_a
  AND c.product_id = a.product_id
  AND c.package_id = a.package_id
  AND a.end_date > SYSDATE