INSERT INTO TF_B_TRADE_ATTR
  (TRADE_ID,
   ACCEPT_MONTH,
   USER_ID,
   INST_TYPE,
   INST_ID,
   ATTR_CODE,
   ATTR_VALUE,
   START_DATE,
   END_DATE,
   MODIFY_TAG,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1, 
   RSRV_NUM2, 
   RSRV_NUM3, 
   RSRV_NUM4, 
   RSRV_NUM5, 
   RSRV_STR1, 
   RSRV_STR2, 
   RSRV_STR3, 
   RSRV_STR4, 
   RSRV_STR5, 
   RSRV_DATE1, 
   RSRV_DATE2, 
   RSRV_DATE3, 
   RSRV_TAG1, 
   RSRV_TAG2, 
   RSRV_TAG3  
   )
  SELECT TO_NUMBER(:TRADE_ID),
         TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2)),
         USER_ID,
         INST_TYPE,
         TO_NUMBER(:INST_ID),
         ATTR_CODE,
         ATTR_VALUE,
         START_DATE,
         SYSDATE,
         '1',
         SYSDATE,
         UPDATE_STAFF_ID,
         UPDATE_DEPART_ID,
         REMARK,
         RSRV_NUM1, 
   		 RSRV_NUM2, 
         RSRV_NUM3, 
         RSRV_NUM4, 
         RSRV_NUM5, 
         RSRV_STR1, 
         RSRV_STR2, 
         RSRV_STR3, 
         RSRV_STR4, 
         RSRV_STR5, 
         RSRV_DATE1, 
         RSRV_DATE2, 
         RSRV_DATE3, 
         RSRV_TAG1, 
         RSRV_TAG2, 
         RSRV_TAG3
    FROM TF_F_USER_ATTR A
   WHERE USER_ID = TO_NUMBER(:USER_ID)
     AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
     AND END_DATE > SYSDATE
     AND END_DATE > START_DATE
     AND NOT EXISTS
   (SELECT 1
            FROM TF_B_TRADE_ATTR
           WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
             AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
             AND USER_ID = A.USER_ID
             AND INST_TYPE = A.INST_TYPE
             AND ATTR_CODE = A.ATTR_CODE)