INSERT INTO TF_B_TRADE_ATTR(TRADE_ID,ACCEPT_MONTH,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,MODIFY_TAG,
    UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1)
SELECT TRADE_ID,ACCEPT_MONTH,USER_ID,'S',INST_ID,:ATTR_CODE,:ATTR_VALUE,START_DATE,END_DATE,'0',
   UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,:SERVICE_ID
FROM TF_B_TRADE_SVC
WHERE TRADE_ID = to_number(:TRADE_ID)
  AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND USER_ID = to_number(:USER_ID)
  AND SERVICE_ID = :SERVICE_ID
  AND MODIFY_TAG = '0'