SELECT t1.RELA_INST_ID, t1.TRADE_ID, t1.ACCEPT_MONTH, t1.USER_ID, t1.INST_TYPE, t1.INST_ID, t1.ATTR_CODE, t1.ATTR_VALUE, t1.START_DATE, t1.END_DATE,
t1.MODIFY_TAG, t1.UPDATE_TIME, t1.UPDATE_STAFF_ID, t1.UPDATE_DEPART_ID, t1.REMARK, t1.RSRV_NUM1, t1.RSRV_NUM2, t1.RSRV_NUM3, t1.RSRV_NUM4, t1.RSRV_NUM5,
t1.RSRV_STR1, t1.RSRV_STR2, t1.RSRV_STR3, t1.RSRV_STR4, t1.RSRV_STR5, t1.RSRV_DATE1, t1.RSRV_DATE2, t1.RSRV_DATE3, t1.RSRV_TAG1, t1.RSRV_TAG2, t1.RSRV_TAG3 
FROM TF_B_TRADE_ATTR t1,TF_B_TRADE t2 
   WHERE  t1.ATTR_CODE=:ATTR_CODE 
           AND t1.TRADE_ID = t2.TRADE_ID  
      AND t1.ATTR_VALUE=:ATTR_VALUE 
      AND SYSDATE BETWEEN t1.START_DATE AND t1.END_DATE
