SELECT b.service_id,TO_CHAR(t.TRADE_ID) TRADE_ID,t.ACCEPT_MONTH,TO_CHAR(t.USER_ID) USER_ID,t.inst_type,t.inst_id,t.ATTR_CODE,t.ATTR_VALUE,TO_CHAR(t.START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,TO_CHAR(t.END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE,
t.MODIFY_TAG,TO_CHAR(t.UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,t.UPDATE_STAFF_ID,t.UPDATE_DEPART_ID,t.REMARK,t.RSRV_NUM1,t.RSRV_NUM2,t.RSRV_NUM3,t.RSRV_NUM4,t.RSRV_NUM5,t.RSRV_STR1,t.RSRV_STR2,t.RSRV_STR3,
t.RSRV_STR4,t.RSRV_STR5,TO_CHAR(t.RSRV_DATE1,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,TO_CHAR(t.RSRV_DATE2,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,TO_CHAR(t.RSRV_DATE3,'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3,t.RSRV_TAG1,t.RSRV_TAG2,t.RSRV_TAG3,TO_CHAR(t.START_DATE,'YYYY-MM-DD HH24:MI:SS') START_DATE,
TO_CHAR(t.END_DATE,'YYYY-MM-DD HH24:MI:SS') END_DATE
  FROM TF_B_TRADE_ATTR t,Tf_b_Trade_svc b
 WHERE b.TRADE_ID=TO_NUMBER(:TRADE_ID)
   AND b.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
   AND inst_type = 'S'
   AND t.inst_id = b.inst_id
   AND t.TRADE_ID = b.TRADE_ID
   AND t.accept_month = b.accept_month