SELECT  
    
    T1.DISCNT_CODE,
    T1.SPEC_TAG,
    T1.RELATION_TYPE_CODE,
    T1.CAMPN_ID,
    to_char(T2.TRADE_ID) TRADE_ID,
    to_char(T2.USER_ID) USER_ID,
    to_char(T2.RELA_INST_ID) RELA_INST_ID,
    T2.INST_TYPE,
    to_char(T2.INST_ID) AS INST_ID,
    T2.ATTR_CODE,
    T2.ATTR_VALUE,
    to_char(T2.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
    to_char(T2.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
    to_char(T2.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
    T2.UPDATE_STAFF_ID,
    T2.UPDATE_DEPART_ID,
    T2.REMARK,
    T2.RSRV_NUM1,
    T2.RSRV_NUM2,
    T2.RSRV_NUM3,
    to_char(T2.RSRV_NUM4) RSRV_NUM4,
    to_char(T2.RSRV_NUM5) RSRV_NUM5,
    T2.RSRV_STR1,
    T2.RSRV_STR2,
    T2.RSRV_STR3,
    T2.RSRV_STR4,
    T2.RSRV_STR5,
    to_char(T2.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
    to_char(T2.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
    to_char(T2.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
    T2.RSRV_TAG1,
    T2.RSRV_TAG2,
    T2.RSRV_TAG3,
    T2.IS_NEED_PF,
    T2.ELEMENT_ID
FROM TF_B_TRADE T,TF_B_TRADE_DISCNT T1,TF_B_TRADE_ATTR T2
WHERE T.TRADE_ID=T1.TRADE_ID
    AND T1.TRADE_ID=T2.TRADE_ID
    AND T1.INST_ID=T2.RELA_INST_ID
    AND T1.USER_ID=T2.USER_ID
    AND SYSDATE BETWEEN T1.START_DATE AND T1.END_DATE
    AND SYSDATE BETWEEN T2.START_DATE AND T2.END_DATE
    AND T1.DISCNT_CODE=:DISCNT_CODE 
	AND T2.ATTR_VALUE=:ATTR_VALUE
    AND T2.INST_TYPE=:INST_TYPE
    AND T2.USER_ID=:USER_ID