Select to_char(A.TRADE_ID) TRADE_ID,
       A.ACCEPT_MONTH,
       to_char(A.USER_ID) USER_ID,
       A.INST_TYPE,
       to_char(A.INST_ID) INST_ID,
       A.ATTR_CODE,
       A.ATTR_VALUE,
       to_char(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_char(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       A.MODIFY_TAG,
       to_char(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       A.REMARK,
       A.RSRV_NUM1,
       A.RSRV_NUM2,
       A.RSRV_NUM3,
       to_char(A.RSRV_NUM4) RSRV_NUM4,
       to_char(A.RSRV_NUM5) RSRV_NUM5,
       A.RSRV_STR1,
       A.RSRV_STR2,
       A.RSRV_STR3,
       A.RSRV_STR4,
       A.RSRV_STR5,
       to_char(A.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       to_char(A.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       to_char(A.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       A.RSRV_TAG1,
       A.RSRV_TAG2,
       A.RSRV_TAG3,
       A.ELEMENT_ID, 
       A.RELA_INST_ID
  From TF_B_TRADE_ATTR A, TF_B_TRADE B
 WHERE B.TRADE_ID = A.TRADE_ID
 AND B.USER_ID = :USER_ID
 AND B.SUBSCRIBE_STATE<>'A'