UPDATE TF_B_TRADE_ATTR
   set MODIFY_TAG = :MODIFY_TAG,end_date=Sysdate,rsrv_str1= :RSRV_STR1,rsrv_str5= :RSRV_STR5,IS_NEED_PF= :IS_NEED_PF,update_time=Sysdate,rsrv_str3= :ATTR_NAME
 where TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND INST_TYPE = :INST_TYPE
   AND ATTR_CODE = :ATTR_CODE
    AND ATTR_VALUE = :ATTR_VALUE
   AND MODIFY_TAG='0'
   AND END_DATE >SYSDATE
 