Update TF_B_TRADE_ATTR
SET ATTR_VALUE = DECODE(:MODE, '0', ATTR_VALUE, TO_CHAR(ADD_MONTHS(TRUNC(START_DATE,'mm'),TO_NUMBER(:MONTHS))-1/24/3600,'yyyy-mm-dd hh24:mi:ss'))
WHERE TRADE_ID = to_number(:TRADE_ID)
  AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND USER_ID = to_number(:USER_ID)
  AND INST_TYPE = :INST_TYPE
  AND INST_ID = to_number(:INST_ID)
  AND ATTR_CODE = :ATTR_CODE
  AND MODIFY_TAG = :MODIFY_TAG