UPDATE TF_B_TRADE_ATTR
SET ATTR_VALUE = :ATTR_VALUE,
   UPDATE_TIME = sysdate,
   UPDATE_STAFF_ID = :UPDATE_STAFF_ID,
   UPDATE_DEPART_ID = :UPDATE_DEPART_ID
WHERE  TRADE_ID = to_number(:TRADE_ID)
  AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))
  AND USER_ID = to_number(:USER_ID)
  AND INST_TYPE = :INST_TYPE 
  AND INST_ID = to_number(:INST_ID)
  AND ATTR_CODE = :ATTR_CODE
  AND MODIFY_TAG in ('4','5')