SELECT T.PRODUCT_LEVEL,
       T.PRODUCT_TYPE,
       T.PRODUCT_ID ELEMENT_ID,
       T.SP_CODE,
       T.BIZ_CODE,
       DECODE(T.BIZ_NAME,'',T.BIZ_DESC,null,T.BIZ_DESC,T.BIZ_NAME) ELEMENT_NAME,
       T.PRODUCT_DESC ELEMENT_EXPLAIN,
       t.ADDED_STATUS STATUS,
       T.EFFECTIVE_TYPE EFFECT_TYPE,
       DECODE(T.BRAND_CODE,'G001','01','G002','02','G010','03','09') BRAND_CODE,
       TO_CHAR(T.ADDED_BDATE, 'YYYYMMDDHH24MISS') START_DATE,
       TO_CHAR(T.ADDED_EDATE, 'YYYYMMDDHH24MISS') END_DATE,
       TO_CHAR(T.BIZ_PRICE, '9999990.00') PRICE,
       T.RSRV_STR1 IDENT_CODE_LEVEL
  FROM TD_B_MARKET_PRODUCT T
 WHERE 1=1
 AND T.PROVINCE = :PROVINCE
