INSERT INTO ti_o_sms
  (sms_notice_id,
   partition_id,
   send_count_code,
   refered_count,
   eparchy_code,
   in_mode_code,
   chan_id,
   recv_object_type,
   recv_object,
   recv_id,
   sms_type_code,
   sms_kind_code,
   notice_content_type,
   notice_content,
   force_refer_count,
   sms_priority,
   refer_time,
   refer_staff_id,
   refer_depart_id,
   deal_time,
   deal_state,
   remark,
   send_time_code,
   send_object_code,
   force_object,
   FORCE_START_TIME,
   FORCE_END_TIME)
VALUES
  (TO_NUMBER(:SMS_NOTICE_ID),
   mod(TO_NUMBER(:SMS_NOTICE_ID), 1000),
   '1',
   '0',
   :EPARCHY_CODE,
   :IN_MODE_CODE,
   'C006',
   '00',
   :SERIAL_NUMBER,
   NVL(TO_NUMBER(:USER_ID), 0),
   '20', 
   '08',
   '0',
   substrb(:NOTICE_CONTENT, 0, 1000),
   1,
   :PRIORITY,
   SYSDATE,
   :STAFF_ID,
   :DEPART_ID,
   SYSDATE,
   '15',
   :REMARK,
   1,
   6,
   :FORCE_OBJECT,
   TO_DATE(:FORCE_START_TIME, 'YYYY-MM-DD HH24:MI:SS'),
   TO_DATE(:FORCE_END_TIME, 'YYYY-MM-DD HH24:MI:SS'))