INSERT INTO TI_O_SMS
   (SMS_NOTICE_ID, EPARCHY_CODE,IN_MODE_CODE,SMS_CHANNEL_CODE, SEND_OBJECT_CODE, SEND_TIME_CODE,
    SEND_COUNT_CODE, RECV_OBJECT_TYPE, RECV_OBJECT, ID, SMS_TYPE_CODE, SMS_KIND_CODE, NOTICE_CONTENT_TYPE,
    NOTICE_CONTENT, REFERED_COUNT, FORCE_REFER_COUNT, FORCE_OBJECT, FORCE_START_TIME, FORCE_END_TIME,
    SMS_PRIORITY, REFER_TIME, REFER_STAFF_ID, REFER_DEPART_ID, DEAL_TIME, DEAL_STAFFID, DEAL_DEPARTID,
    DEAL_STATE, REMARK, REVC1, REVC2, REVC3, REVC4)
VALUES
   (TO_NUMBER(F_SYS_GETSEQID(:EPARCHY_CODE, 'seq_smssend_id')), :EPARCHY_CODE,
    :IN_MODE_CODE, '11', '1', :SEND_TIME_CODE, NULL, '00', :SERIAL_NUMBER,
    TO_NUMBER(:USER_ID), '20', '02', '0', :NOTICE_CONTENT, NULL, 1, :FORCE_OBJECT,
    TO_DATE(:FORCE_START_TIME, 'YYYY-MM-DD HH24:MI:SS'), TO_DATE(:FORCE_END_TIME, 'YYYY-MM-DD HH24:MI:SS'),
    :PRIORITY, SYSDATE, :STAFF_ID, :DEPART_ID, SYSDATE, NULL, NULL, '0', :REMARK, NULL, NULL, NULL, NULL)