SELECT  PARTITION_ID,
				PAYRELATION_ID,
				USER_ID,
				LIMIT_TYPE,
				LIMIT_VALUE,
				INTEGRAL_ACCT_ID,
				DEFAULT_TAG,
				ACT_TAG,
				START_DATE,
				END_DATE,
				REMARK,
				UPDATE_TIME,
				UPDATE_DEPART_ID,
				UPDATE_STAFF_ID,
				RSRV_STR1,
				RSRV_STR2,
				RSRV_STR3,
				RSRV_NUM1,
				RSRV_NUM2,
				RSRV_NUM3,
				RSRV_DATE1,
				RSRV_DATE2,
				RSRV_DATE3
  FROM TF_F_SCORERELATION
 WHERE 1 = 1
   AND ACT_TAG = :ACT_TAG
   AND USER_ID = :USER_ID
   AND TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD')) BETWEEN START_DATE AND END_DATE
