--IS_CACHE=Y
SELECT 
  A.TMPL_ID,
  C.TMPL_NAME,
  A.CONTENT_NUM,
  A.NUMBER_DESC,
  A.CONTENT_CODE,
  B.CONTENT_NAME,
  B.CONTENT,
  A.EFF_DATE,
  A.EXP_DATE
FROM TD_S_CONT_TMPL_REL A, TD_S_CONTENT B, TD_S_FORMAT_TMPL C
WHERE 
     A.TMPL_ID = :TMPL_ID
     AND A.TMPL_ID = C.TMPL_ID
     AND A.CONTENT_CODE = B.CONTENT_CODE