SELECT A.SERIAL_NUMBER_B,
       A.SHORT_CODE,
       A.SERIAL_NUMBER_A,
       B.VPN_NAME,
       B.CUST_MANAGER,
       C.CITY_CODE
  FROM TF_F_RELATION_UU A, TF_F_USER_VPN B, TF_F_USER C
 WHERE A.USER_ID_A in (:USER_ID_A)
   AND A.RELATION_TYPE_CODE = :RELATION_TYPE_CODE
   AND A.USER_ID_A = B.USER_ID
   AND B.PARTITION_ID = MOD(B.USER_ID, 10000)
   AND B.REMOVE_TAG = '0'
   AND C.USER_ID = B.USER_ID
   AND C.REMOVE_TAG = '0'
   AND (TRIM(A.SHORT_CODE) IS NULL OR SUBSTR(A.SHORT_CODE, 1, 1) != '6' OR
       LENGTH(A.SHORT_CODE) < 3 OR LENGTH(A.SHORT_CODE) > 6)
   AND A.END_DATE > SYSDATE