SELECT COUNT(1) RECORDCOUNT
  FROM TF_B_TRADE_SVC a
 WHERE a.TRADE_ID = :TRADE_ID
   AND a.ACCEPT_MONTH = to_number(substr(:TRADE_ID,5,2))
   AND a.USER_ID = :USER_ID
   AND (a.MODIFY_TAG = :MODIFY_TAG OR :MODIFY_TAG = '*')
   AND EXISTS (SELECT 1 FROM TD_B_PRODUCT_SVC b
        WHERE b.PRODUCT_ID = :PRODUCT_ID
          AND b.SERVICE_ID = a.SERVICE_ID
          AND b.END_DATE > SYSDATE)