UPDATE TF_F_USER_INFO_CLASS
 SET END_DATE = TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss'),
 RSRV_DATE1 = NULL,
 REMARK=:REMARK 
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
 AND USER_ID = TO_NUMBER(:USER_ID)
 AND SERIAL_NUMBER = TO_NUMBER(:SERIAL_NUMBER)
 AND USER_CLASS = :USER_CLASS
 AND RSRV_STR1 = :RSRV_STR1
 AND END_DATE > SYSDATE