SELECT to_char(TRADE_ID) trade_id,ACCEPT_MONTH,to_char(USER_ID) user_id,FACTORY_CODE,FACTORY,ACTION_NAME,SCORE_TYPE_CODE,
SCORE_CHANGED_SUB,VALUE_CHANGED_SUB,ACTION_COUNT,REMARK
FROM TF_B_TRADE_SCOREFACTORY
WHERE TRADE_ID=to_number(:TRADE_ID)
AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))