SELECT u.PARTITION_ID,
       TO_CHAR(u.USER_ID) USER_ID,
       TO_CHAR(u.CUST_ID) CUST_ID,
       TO_CHAR(u.USECUST_ID) USECUST_ID,
       BRAND_CODE,
       PRODUCT_ID,
       EPARCHY_CODE,
       CITY_CODE,
       CITY_CODE_A,
       USER_PASSWD,
       USER_DIFF_CODE,
       USER_TYPE_CODE,
       USER_TAG_SET,
       USER_STATE_CODESET,
       NET_TYPE_CODE,
       SERIAL_NUMBER,
       CONTRACT_ID,
       ACCT_TAG,
       PREPAY_TAG,
       MPUTE_MONTH_FEE,
       TO_CHAR(MPUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') MPUTE_DATE,
       TO_CHAR(FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       TO_CHAR(LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,
       TO_CHAR(CHANGEUSER_DATE, 'yyyy-mm-dd hh24:mi:ss') CHANGEUSER_DATE,
       IN_NET_MODE,
       TO_CHAR(IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE,
       IN_STAFF_ID,
       IN_DEPART_ID,
       OPEN_MODE,
       TO_CHAR(OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       OPEN_STAFF_ID,
       OPEN_DEPART_ID,
       DEVELOP_STAFF_ID,
       TO_CHAR(DEVELOP_DATE, 'yyyy-mm-dd hh24:mi:ss') DEVELOP_DATE,
       DEVELOP_DEPART_ID,
       DEVELOP_CITY_CODE,
       DEVELOP_EPARCHY_CODE,
       DEVELOP_NO,
       TO_CHAR(ASSURE_CUST_ID) ASSURE_CUST_ID,
       ASSURE_TYPE_CODE,
       TO_CHAR(ASSURE_DATE, 'yyyy-mm-dd hh24:mi:ss') ASSURE_DATE,
       REMOVE_TAG,
       TO_CHAR(PRE_DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') PRE_DESTROY_TIME,
       TO_CHAR(DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME,
       REMOVE_EPARCHY_CODE,
       REMOVE_CITY_CODE,
       REMOVE_DEPART_ID,
       REMOVE_REASON_CODE,
       TO_CHAR(u.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       u.UPDATE_STAFF_ID,
       u.UPDATE_DEPART_ID,
       u.REMARK,
       u.RSRV_NUM1,
       u.RSRV_NUM2,
       u.RSRV_NUM3,
       TO_CHAR(u.RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(u.RSRV_NUM5) RSRV_NUM5,
       u.RSRV_STR1,
       u.RSRV_STR2,
       u.RSRV_STR3,
       u.RSRV_STR4,
       u.RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10,
       TO_CHAR(u.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(u.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(u.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       u.RSRV_TAG1,
       u.RSRV_TAG2,
       u.RSRV_TAG3
  FROM TF_F_USER u, TF_F_USER_PRODUCT P
 WHERE u.CUST_ID = to_number(:CUST_ID)
   AND p.PRODUCT_ID = to_number(:PRODUCT_ID)
   AND u.REMOVE_TAG = '0'
   AND P.USER_ID = u.USER_ID
   AND P.PARTITION_ID = u.PARTITION_ID
   AND SYSDATE BETWEEN P.START_DATE AND P.END_DATE
   AND P.MAIN_TAG = '1'
