--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_DEPART_ID 受理部门,a.trade_staff_id 受理工号,A.TRADE_ID 台账标识
 FROM UCR_CRM1.TF_BH_TRADE A, TD_M_DEPART D
WHERE A.USER_ID = TO_NUMBER(:USER_ID)
  AND A.TRADE_TYPE_CODE = 10
  AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
  AND A.CANCEL_TAG = '0'
  AND A.TRADE_DEPART_ID = D.DEPART_ID
  AND A.PRODUCT_ID = 10001001
  AND A.BRAND_CODE = 'CPE1'
  AND ROWNUM < 2