UPDATE TF_A_HANG_ACCT_DEALLOG SET DEAL_STATUS='1',HANG_ACCT_DATE=SYSDATE,
      DEPART_ID=:DEPART_ID,STAFF_ID=:STAFF_ID,
      HANG_ACCT_REASON=:HANG_ACCT_REASON,REMARK1=:REMARK1 
WHERE PARTITION_ID=:PARTITION_ID AND USER_ID=:USER_ID 
  AND ACCT_ID=:ACCT_ID AND BILL_ID=:BILL_ID AND ACYC_ID=:ACYC_ID 
  AND INTEGRATE_ITEM_CODE=:INTEGRATE_ITEM_CODE AND DEAL_STATUS='0'