SELECT COUNT(1) FLAG
  FROM TF_B_TRADE_SALE_ACTIVE A
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.PRODUCT_ID = :PARAM_CODE1
   AND A.PACKAGE_ID = :PARAM_CODE2