SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID, B.PARTITION_ID, B.USER_ID, B.INST_ID, B.SERVICE_ID,
		B.MAIN_TAG, B.STATE_CODE, B.START_DATE, B.END_DATE,
		B.UPDATE_TIME, B.UPDATE_STAFF_ID, B.UPDATE_DEPART_ID,
		B.REMARK, B.RSRV_NUM1, B.RSRV_NUM2, B.RSRV_NUM3,
		B.RSRV_NUM4, B.RSRV_NUM5, B.RSRV_STR1, B.RSRV_STR2,
		B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5, B.RSRV_DATE1,
		B.RSRV_DATE2, B.RSRV_DATE3, B.RSRV_TAG1, B.RSRV_TAG2,
		B.RSRV_TAG3
  FROM TF_F_USER_SVCSTATE B
 WHERE B.USER_ID = :USER_ID
   AND B.PARTITION_ID = MOD(:USER_ID, 10000)
   AND B.END_DATE > TRUNC(SYSDATE) - 60