SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(CUST_ID) CUST_ID,
       GROUP_ID,
       GROUP_CUST_NAME,
       GROUP_TYPE,
       MEMBER_BELONG,
       MEMBER_KIND,
       MEMBER_RELA,
       TO_CHAR(MEMBER_CUST_ID) MEMBER_CUST_ID,
       TO_CHAR(USECUST_ID) USECUST_ID,
       SERIAL_NUMBER,
       NET_TYPE_CODE,
       CUST_NAME,
       USECUST_NAME,
       USEPSPT_TYPE_CODE,
       USEPSPT_ID,
       TO_CHAR(USEPSPT_END_DATE, 'yyyy-mm-dd hh24:mi:ss') USEPSPT_END_DATE,
       USEPSPT_ADDR,
       USEPHONE,
       USEPOST_ADDR,
       EPARCHY_CODE,
       CITY_CODE,
       TO_CHAR(STRU_ID) STRU_ID,
       VPMN_GROUP_ID,
       VIP_ID,
       VIP_TYPE_CODE,
       VIP_CLASS_ID,
       VIP_TYPE_CODE_B,
       VIP_CLASS_ID_B,
       TO_CHAR(ASSIGN_DATE, 'yyyy-mm-dd hh24:mi:ss') ASSIGN_DATE,
       ASSIGN_STAFF_ID,
       JOIN_TYPE,
       TO_CHAR(JOIN_DATE, 'yyyy-mm-dd hh24:mi:ss') JOIN_DATE,
       JOIN_STAFF_ID,
       JOIN_DEPART_ID,
       CONTRACT_NO,
       TO_CHAR(MONTH_FEE) MONTH_FEE,
       FEE_PAYMODE,
       DEPART,
       DUTY,
       HVALUE_TAG,
       TO_CHAR(CLUB_ID) CLUB_ID,
       TO_CHAR(BIRTHDAY, 'yyyy-mm-dd hh24:mi:ss') BIRTHDAY,
       BIRTHDAY_LUNAR,
       BIRTHDAY_FLAG,
       CUST_MANAGER_ID,
       CUST_MANAGER_APPR,
       LIKE_MOBILE_BUSI,
       LIKE_DISCNT_TYPE,
       LIKE_ACT,
       SVC_MODE_CODE,
       CONTACT_ORDER,
       GROUP_BRAND_CODE,
       BRAND_CODE,
       PRODUCT_ID,
       USER_TYPE_CODE,
       USER_STATE_CODESET,
       TO_CHAR(OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       TO_CHAR(FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       TO_CHAR(LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,
       TO_CHAR(SCORE_VALUE) SCORE_VALUE,
       CREDIT_CLASS,
       TO_CHAR(CREDIT_VALUE) CREDIT_VALUE,
       CTAG_SET,
       CHECK_NO,
       TO_CHAR(TRADE_ID) TRADE_ID,
       CANCEL_TAG,
       REMOVE_TAG,
       TO_CHAR(REMOVE_DATE, 'yyyy-mm-dd hh24:mi:ss') REMOVE_DATE,
       REMOVE_STAFF_ID,
       REMOVE_REASON,
       TO_CHAR(SYNC_TIME, 'yyyy-mm-dd hh24:mi:ss') SYNC_TIME,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       TO_CHAR(RSRV_NUM4) RSRV_NUM4,
       TO_CHAR(RSRV_NUM5) RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       TO_CHAR(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       TO_CHAR(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       TO_CHAR(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       TO_CHAR(RSRV_DATE4, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE4,
       TO_CHAR(RSRV_DATE5, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE5,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3,
       RSRV_TAG4,
       RSRV_TAG5
  FROM TF_F_CUST_GROUPMEMBER
 WHERE REMOVE_TAG = '0'
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)