SELECT to_char(TRADE_ID) TRADE_ID,
       ACCEPT_MONTH,
       MAIN_USER_TYPE RSRV_STR11,
       MAIN_USER_VALUE RSRV_STR12,
       MAIN_SIGN_TYPE RSRV_STR13,
       SUB_USER_TYPE RSRV_STR14,
       SUB_USER_VALUE RSRV_STR15,
       SUB_SIGN_TYPE RSRV_STR16,
       MAIN_EPARCHY_CODE RSRV_STR17,
       CHNL_TYPE,
       to_char(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_char(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       MODIFY_TAG,
       to_char(UPDATE_DATE, 'yyyy-mm-dd hh24:mi:ss') UPDATE_DATE,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       to_char(RSRV_STR4) RSRV_STR4,
       to_char(RSRV_STR5) RSRV_STR5,
       m.rsrv_str6,
       m.rsrv_str7,
       m.rsrv_str8,
       m.rsrv_str9,
       m.rsrv_str10,
       to_char(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       to_char(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       to_char(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3,m.sign_id rsrv_str18
  FROM tf_b_trade_bank_subsign m
 WHERE trade_id = TO_NUMBER(:TRADE_ID)
   AND accept_month = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))