UPDATE TF_B_TRADE_BOOK T
   SET T.BOOK_STATUS    = :BOOK_STATUS,
       T.TRADE_STAFF_ID = :TRADE_STAFF_ID,
       T.RSRV_DATE1     = TO_DATE(:RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS'),
       T.RSRV_STR5 = :RSRV_STR5
 WHERE T.TRADE_ID = :TRADE_ID