SELECT ACCT.ACCT_ID, ACCT.PAY_NAME, ACCT.EPARCHY_CODE, ACCT.PAY_MODE_CODE,
       ACCT.BANK_CODE, ACCT.BANK_ACCT_NO, ACCT.CONTRACT_NO, U.USER_ID,
       U.SERIAL_NUMBER, UP.PRODUCT_ID
  FROM TF_F_ACCOUNT ACCT, TF_F_USER U, TF_F_USER_PRODUCT UP,
       TF_A_PAYRELATION PAY
 WHERE ACCT.CUST_ID = TO_NUMBER(:CUST_ID)
   AND U.CUST_ID = TO_NUMBER(:CUST_ID)
   AND ACCT.REMOVE_TAG = '0'
   AND U.REMOVE_TAG = '0'
   AND PAY.ACCT_ID = ACCT.ACCT_ID
   AND U.USER_ID = PAY.USER_ID
   AND ACCT.PAY_MODE_CODE <> 1
   AND U.PARTITION_ID = MOD(PAY.USER_ID, 10000)
   AND U.USER_ID = UP.USER_ID
   AND UP.PARTITION_ID = MOD(U.USER_ID, 10000)
   AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN PAY.START_CYCLE_ID AND
       PAY.END_CYCLE_ID
UNION ALL
SELECT ACCT.ACCT_ID, ACCT.PAY_NAME, ACCT.EPARCHY_CODE, ACCT.PAY_MODE_CODE,
       ACCT.BANK_CODE, ACCT.BANK_ACCT_NO, ACCT.CONTRACT_NO, NULL, NULL, NULL
  FROM TF_F_ACCOUNT ACCT
 WHERE ACCT.CUST_ID = TO_NUMBER(:CUST_ID)
   AND ACCT.PAY_MODE_CODE <> 1
   AND NOT EXISTS
 (SELECT *
          FROM TF_A_PAYRELATION PAYRE
         WHERE PAYRE.ACCT_ID = ACCT.ACCT_ID
           AND TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN PAYRE.START_CYCLE_ID AND
               PAYRE.END_CYCLE_ID)
