--IS_CACHE=Y
select BIZ_CODE, PARM_ID, PARM_NAME, PARM_NULLABLE, RSRV_STR7, PARM_VALUE, PARM_LENGTH, PARM_CODE, RSRV_PARM, RSRV_NUM1, RSRV_STR4, RSRV_NUM3, RSRV_STR1, RSRV_STR2, PARM_TYPE, RSRV_NUM2, RSRV_STR5, RSRV_STR6, RSRV_STR3, RSRV_STR8 from tf_cop_service_parms 
where BIZ_CODE=:BIZ_CODE