--IS_CACHE=Y
SELECT para_code1,para_code2,para_code3,para_code4
  FROM TD_S_COMMPARA
 WHERE param_attr = :PARAM_ATTR
   AND subsys_code = :SUBSYS_CODE
   AND PARAM_CODE = :PARAM_CODE
   AND PARA_CODE1 = :PARA_CODE1
   AND (PARA_CODE2 = :PARA_CODE2 OR PARA_CODE2 IS NULL)
   AND (PARA_CODE3 = :PARA_CODE3 OR PARA_CODE3 IS NULL)
   AND (PARA_CODE4 = :PARA_CODE4 OR PARA_CODE4 IS NULL)
   AND (EPARCHY_CODE = :EPARCHY_CODE OR EPARCHY_CODE IS NULL)
   AND SYSDATE BETWEEN START_DATE AND END_DATE