UPDATE TF_F_BANK_RECVFEE
SET (ACNTBALANCE,AIMP_FEE,BANK_TAG,BOSS_TAG,BANK_TRADE_ID,BANK_RETURN_CODE,BANK_RETURN_INFO,CANCEL_TAG,CANCEL_BANK_TRADE_ID,CANCEL_TRADE_TIME,CANCEL_BANK_RETURN_CODE,CANCEL_BANK_RETURN_INFO,REMARK,PREVALUE1,PREVALUE2,PREVALUE3,PREVALUE4,PREVALUE5,charge_id)
=(
SELECT 
DECODE(:ACNTBALANCE,NULL,ACNTBALANCE,:ACNTBALANCE),
DECODE(:AIMP_FEE,NULL,AIMP_FEE,:AIMP_FEE),
DECODE(:BANK_TAG,NULL,BANK_TAG,:BANK_TAG),
DECODE(:BOSS_TAG,NULL,BOSS_TAG,:BOSS_TAG),
DECODE(:BANK_TRADE_ID,NULL,BANK_TRADE_ID,:BANK_TRADE_ID),
DECODE(:BANK_RETURN_CODE,NULL,BANK_RETURN_CODE,:BANK_RETURN_CODE),
DECODE(:BANK_RETURN_INFO,NULL,BANK_RETURN_INFO,:BANK_RETURN_INFO),
DECODE(:CANCEL_TAG,NULL,CANCEL_TAG,:CANCEL_TAG),
DECODE(:CANCEL_BANK_TRADE_ID,NULL,CANCEL_BANK_TRADE_ID,:CANCEL_BANK_TRADE_ID),
DECODE(:CANCEL_TRADE_TIME,NULL,CANCEL_TRADE_TIME,:CANCEL_TRADE_TIME),
DECODE(:CANCEL_BANK_RETURN_CODE,NULL,CANCEL_BANK_RETURN_CODE,:CANCEL_BANK_RETURN_CODE),
DECODE(:CANCEL_BANK_RETURN_INFO,NULL,CANCEL_BANK_RETURN_INFO,:CANCEL_BANK_RETURN_INFO)
,:REMARK
,:PREVALUE1
,:PREVALUE2
,:PREVALUE3
,:PREVALUE4 
,:PREVALUE5,DECODE(:CHARGE_ID,NULL,CHARGE_ID,:CHARGE_ID) FROM TF_F_BANK_RECVFEE WHERE TRADE_ID=:TRADE_ID)
WHERE TRADE_ID=:TRADE_ID