--IS_CACHE=Y
SELECT ID_VALUE SID,
        ID_NAME SNAME,
        DEPART_ID DEPART,
        JOB_CODE JOB,
        CHAN_ID CID,
        SERIAL_NUMBER PHONE,
        STAFF_TYPE STYPE,
        STAFF_CLASS SCLASS,
        EMAIL EMAIL,
        OPER_STAFF_ID OSID
        FROM TD_S_ECHANNAL_STAFF
       WHERE 1=1
       AND ID_TYPE='0'
       AND STAFF_TYPE IN('1','2','5')
       AND OPER_STAFF_ID=:OSID
       AND CHAN_ID=:CHAN_ID
       AND SERIAL_NUMBER=:SERIAL_NUMBER
       AND STAFF_TYPE=:STYPE