UPDATE TF_B_TRADE_OTHER T
 SET T.RSRV_STR1=:RES_NO,T.RSRV_STR6=:RES_KIND_CODE,T.UPDATE_STAFF_ID=:UPDATE_STAFF_ID,T.UPDATE_DEPART_ID=:UPDATE_DEPART_ID,T.RSRV_STR12=:TRADE_ID
 where T.RSRV_VALUE_CODE='FTTH'
 AND T.RSRV_TAG2 = '1'
 AND T.MODIFY_TAG = '0'
 AND T.TRADE_ID = :TRADE_ID
 AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
 AND T.USER_ID = :USER_ID