select   U.PARTITION_ID,
    U.USER_ID,
    U.SERIAL_NUMBER,
    U.IMSI,
    U.APN1,
    U.APN2,
    U.APN3,
    U.APN4,
    U.APN5,
    TO_CHAR(U.OPEN_DATE, 'YYYY-MM-DD HH24:MM:SS') OPEN_DATE,
    U.CALLING_TYPE_CODE,
    U.GROUP_NAME,
    U.PROVINCIAL_ROAM_TAG,
    U.OPRFLAG,
    U.CUST_MANAGER_NAME,
    TO_CHAR(U.IN_DATE, 'YYYY-MM-DD HH24:MM:SS') IN_DATE,
    TO_CHAR(U.UPDATE_TIME, 'YYYY-MM-DD HH24:MM:SS') UPDATE_TIME
  FROM TF_F_IOT_USER U
    WHERE U.PARTITION_ID BETWEEN :PARTITION_START AND :PARTITION_END