SELECT B.PARA_CODE1 PRODUCT_CODE,
       B.PARA_CODE2 PACKAGE_ID,
       C.PROD_INST_ID PRODUCT_INST_ID,
       D.SUBS_ID,
       TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
       CASE
         WHEN E.TRADE_TYPE_CODE = '273' THEN
          DECODE(T.STATE_CODE, '0', '05', 'E', '04', STATE_CODE)
         ELSE
          A.MODIFY_TAG
       END MODIFY_TAG
  FROM TF_B_TRADE_SVC      A,
       TD_S_COMMPARA       B,
       TF_F_INSTANCE_PF    C,
       TF_F_INSTANCE_PF    D,
       TF_B_TRADE          E,
       TF_B_TRADE_SVCSTATE T
 WHERE TO_CHAR(A.SERVICE_ID) = B.PARAM_CODE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = '9014'
   AND A.USER_ID = D.USER_ID
   AND D.INST_ID = -1
   AND A.INST_ID = C.INST_ID
   AND C.INST_TYPE = 'S'
   AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG IN ('0', '1', '2')
   AND A.TRADE_ID = T.TRADE_ID(+)
   AND A.ACCEPT_MONTH = T.ACCEPT_MONTH(+)
   AND A.SERVICE_ID = T.SERVICE_ID(+)
   AND (T.MODIFY_TAG = '0' OR T.MODIFY_TAG IS NULL)
   AND E.TRADE_ID = TO_NUMBER(:TRADE_ID)
UNION
SELECT B.PARA_CODE1 PRODUCT_CODE,
       B.PARA_CODE2 PACKAGE_ID,
       C.PROD_INST_ID PRODUCT_INST_ID,
       D.SUBS_ID,
       TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
       A.MODIFY_TAG
  FROM TF_B_TRADE_DISCNT A,
       TD_S_COMMPARA     B,
       TF_F_INSTANCE_PF  C,
       TF_F_INSTANCE_PF  D
 WHERE TO_CHAR(A.DISCNT_CODE) = B.PARAM_CODE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = '9013'
   AND A.USER_ID = D.USER_ID
   AND D.INST_ID = -1
   AND A.INST_ID = C.INST_ID
   AND C.INST_TYPE = 'S'
   AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG IN ('0', '1', '2')
UNION
SELECT B.PARA_CODE1 PRODUCT_CODE,
       'NULL' PACKAGE_ID,
       C.PROD_INST_ID PRODUCT_INST_ID,
       D.SUBS_ID,
       TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
       TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
       A.MODIFY_TAG
  FROM TF_B_TRADE_PRODUCT A,
       TD_S_COMMPARA      B,
       TF_F_INSTANCE_PF   C,
       TF_F_INSTANCE_PF   D,
       TF_B_TRADE         T
 WHERE TO_CHAR(A.PRODUCT_ID) = B.PARAM_CODE
   AND B.SUBSYS_CODE = 'CSM'
   AND B.PARAM_ATTR = '9015'
   AND A.USER_ID = D.USER_ID
   AND D.INST_ID = -1
   AND A.INST_ID = C.INST_ID
   AND C.INST_TYPE = 'S'
   AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG IN ('0', '1', '2')
   AND T.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND T.TRADE_TYPE_CODE IN ('6110', '6111', '6113')
UNION /*包信息,当作产品传;用MIN.MAX函数避免按时间分组*/
SELECT PACKAGE_ID PRODUCT_CODE,
       'NULL' AS PACKAGE_ID,
       PRODUCT_INST_ID,
       SUBS_ID,
       MIN(START_DATE) START_DATE,
       MAX(END_DATE) END_DATE,
       MODIFY_TAG
  FROM (SELECT B.PARA_CODE2 PACKAGE_ID,
               C.PROD_INST_ID PRODUCT_INST_ID,
               D.SUBS_ID,
               TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
               TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
               A.MODIFY_TAG,
               C.RSRV_STR1
          FROM TF_B_TRADE_SVC   A,
               TD_S_COMMPARA    B,
               TF_F_INSTANCE_PF C,
               TF_F_INSTANCE_PF D
         WHERE TO_CHAR(A.SERVICE_ID) = B.PARAM_CODE
           AND B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_ATTR = '9014'
           AND A.USER_ID = D.USER_ID
           AND D.INST_ID = -1
           AND A.INST_ID = C.INST_ID
           AND C.INST_TYPE = 'P'
           AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
           AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND A.MODIFY_TAG IN ('0', '1', '2')
        UNION
        SELECT B.PARA_CODE2 PACKAGE_ID,
               C.PROD_INST_ID PRODUCT_INST_ID,
               D.SUBS_ID,
               TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MMSS') START_DATE,
               TO_CHAR(A.END_DATE, 'YYYYMMDDHH24MMSS') END_DATE,
               A.MODIFY_TAG,
               C.RSRV_STR1
          FROM TF_B_TRADE_DISCNT A,
               TD_S_COMMPARA     B,
               TF_F_INSTANCE_PF  C,
               TF_F_INSTANCE_PF  D
         WHERE TO_CHAR(A.DISCNT_CODE) = B.PARAM_CODE
           AND B.SUBSYS_CODE = 'CSM'
           AND B.PARAM_ATTR = '9013'
           AND A.USER_ID = D.USER_ID
           AND D.INST_ID = -1
           AND A.INST_ID = C.INST_ID
           AND C.INST_TYPE = 'P'
           AND A.TRADE_ID = TO_NUMBER(:TRADE_ID)
           AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
           AND A.MODIFY_TAG IN ('0', '1', '2'))
 WHERE (MODIFY_TAG = '0' AND NVL(RSRV_STR1, '0') <> 'USER_PRE_INST_ID')
    OR (MODIFY_TAG = '1' AND NOT EXISTS
        (SELECT 1
           FROM TF_B_TRADE
          WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
            AND TRADE_TYPE_CODE IN ('6111', '6115')))
 GROUP BY PACKAGE_ID, PRODUCT_INST_ID, SUBS_ID, MODIFY_TAG