SELECT A.INST_ID
  FROM TF_B_TRADE_PRODUCT A
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG = '0'
   AND NOT EXISTS (SELECT 1
          FROM TF_F_INSTANCE_PF
         WHERE INST_ID = A.INST_ID
           AND INST_TYPE = 'S')
UNION ALL
SELECT A.INST_ID
  FROM TF_B_TRADE_SVC A
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG = '0'
   AND NOT EXISTS (SELECT 1
          FROM TF_F_INSTANCE_PF
         WHERE INST_ID = A.INST_ID
           AND INST_TYPE = 'S')
UNION ALL
SELECT A.INST_ID
  FROM TF_B_TRADE_DISCNT A
 WHERE A.TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND A.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND A.MODIFY_TAG = '0'
   AND NOT EXISTS (SELECT 1
          FROM TF_F_INSTANCE_PF
         WHERE INST_ID = A.INST_ID
           AND INST_TYPE = 'S')