INSERT INTO TF_B_TRADE_BATDEAL(BATCH_TASK_ID, BATCH_ID, OPERATE_ID, BATCH_OPER_TYPE, PRIORITY, REFER_TIME, EXEC_TIME, SERIAL_NUMBER, ROUTE_EPARCHY_CODE, CANCEL_TAG,  DEAL_STATE, DEAL_TIME,  DEAL_DESC) 
select to_number(:BATCH_TASK_ID) , to_number(:BATCH_ID) , f_sys_getseqid('0898','BATCH_ID') , 'PAYRELATIONCHG', '500', sysdate , sysdate , B.SERIAL_NUMBER, :ROUTE_EPARCHY_CODE,'0', '1',sysdate , 'VPMN自动终止统付'
FROM  tf_f_user_specialepay A , TF_F_USER B
where A.user_id_a=:USER_ID_A
 AND TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) BETWEEN  A.START_CYCLE_ID  AND A.END_CYCLE_ID
 AND A.USER_ID=B.USER_ID
 AND A.PARTITION_ID=B.PARTITION_ID
 AND B.REMOVE_TAG='0'