SELECT   A.IDVALUE SERIAL_NUMBER,A.ACTIONTIME ACTION_TIME,A.CHARGEMONEY CHARGEMONEY,A.ORGANID ORGAN_ID FROM  TO_O_REPLENISH A
WHERE A.ACTIONTIME>= :START_ACTION_TIME 
AND A.ACTIONTIME<= :END_ACTION_TIME 
AND A.IDVALUE= :SERIAL_NUMBER 
UNION
SELECT   A.IDVALUE SERIAL_NUMBER,A.ACTIONTIME ACTION_TIME,A.CHARGEMONEY CHARGEMONEY,A.ORGANID ORGAN_ID FROM  TO_O_HISREPLENISH A
WHERE A.ACTIONTIME>= :START_ACTION_TIME 
AND A.ACTIONTIME<= :END_ACTION_TIME 
AND A.IDVALUE= :SERIAL_NUMBER 