--IS_CACHE=Y
SELECT T.PARAM_VALUE,T.PARA_NAME,T.PARA_CODE,T.PARA_CODE1,T.PARA_CODE2,T.PARA_CODE3,T.PARA_CODE4,
T.PARA_CODE5,T.PARA_CODE6,T.PARA_CODE7,T.PARA_CODE8,T.PARA_CODE9,T.PARA_CODE10,T.EPARCHY_CODE
 from TD_B_SALESERV_COMMPARA T
 WHERE PARAM_VALUE=:PARAM_VALUE
 AND (PARA_CODE=:PARA_CODE OR :PARA_CODE IS NULL)
 AND (PARA_CODE1=:PARA_CODE1 OR :PARA_CODE1 IS NULL)
 AND (PARA_CODE2=:PARA_CODE2 OR :PARA_CODE2 IS NULL)
 AND (PARA_CODE3=:PARA_CODE3 OR :PARA_CODE3 IS NULL)
 AND (PARA_CODE4=:PARA_CODE4 OR :PARA_CODE4 IS NULL)
 AND (PARA_CODE5=:PARA_CODE5 OR :PARA_CODE5 IS NULL)
 AND (EPARCHY_CODE=:EPARCHY_CODE OR EPARCHY_CODE='ZZZZ')
 AND END_DATE>SYSDATE