--IS_CACHE=Y
SELECT NVL(RSP_EXEC_CODE,'') RSP_EXEC_CODE,NVL(RSP_CHAN_ID,'') RSP_CHAN_ID,NVL(RSP_EXEC_TYPE,'') RSP_EXEC_TYPE,
NVL(RSP_EXEC_METHOD,'') RSP_EXEC_METHOD,NVL(START_DATE,'') START_DATE,NVL(END_DATE,'') END_DATE
 FROM TD_S_RSPEXEC WHERE 1=1
 AND RSP_CHAN_ID = :RSP_CHAN_ID
 AND RSP_EXEC_TYPE = :RSP_EXEC_TYPE
 AND to_char(START_DATE ,'yyyy-MM-dd') >= :START_DATE
 AND to_char(END_DATE ,'yyyy-MM-dd') <= :END_DATE