SELECT to_char(TRADE_ID) TRADE_ID,TRADE_DEPART_ID,TRADE_STAFF_ID,to_char(ACCEPT_DATE,'yyyy-mm-dd') ACCEPT_DATE,TRADE_TYPE_CODE,TRADE_NUMBER,REMARK,UPDATE_STAFF_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,AUDIT_TAG,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8
  FROM TS_A_TRADE_INFORMAL
 WHERE TRADE_DEPART_ID = :TRADE_DEPART_ID
   AND TRADE_STAFF_ID = :TRADE_STAFF_ID
   AND ACCEPT_DATE = to_date(:ACCEPT_DATE,'yyyy-mm-dd hh24:mi:ss')