UPDATE TF_F_POPULARITY
  SET UPDATE_TIME = TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS'), UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, PRIORITY = PRIORITY + 1
 WHERE 1 = 1
   AND POPULARITY_TRADE_TYPE = :POPULARITY_TRADE_TYPE
   AND POPULARITY_TYPE = :POPULARITY_TYPE
   AND PRIORITY >= :PRIORITY
   AND UPDATE_TIME != TO_DATE(:UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS')
