SELECT PARTITION_ID,
       TO_CHAR(INST_ID) INST_ID,
       TO_CHAR(USER_ID) USER_ID,
       USER_TYPE_CODE,
       TO_CHAR(EC_USER_ID) EC_USER_ID,
       SERVICE_ID,
       BIZ_IN_CODE,
       BIZ_IN_CODE_A,
       SERV_CODE,
       SERIAL_NUMBER,
       EC_SERIAL_NUMBER,
       GROUP_ID,
       BIZ_CODE,
       BIZ_NAME,
       BIZ_DESC,
       BOOK_DATE,
       CONTRACT_ID,
       PRICE,
       BILLING_TYPE,
       OPR_EFF_TIME,
       OPR_SEQ_ID,
       OPER_STATE,
       PLAT_SYNC_STATE,
       TO_CHAR(EXPECT_TIME, 'yyyy-mm-dd hh24:mi:ss') EXPECT_TIME,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_DATE1,
       RSRV_DATE2,
       RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3
FROM TF_F_USER_BLACKWHITE  
 WHERE EC_USER_ID=:EC_USER_ID
   AND USER_ID=:USER_ID
	    AND SERVICE_ID = :SERVICE_ID 
  AND SYSDATE BETWEEN START_DATE AND END_DATE