SELECT G.GROUP_ID,G.CUST_ID,G.CUST_NAME,G.CLASS_ID,G.JURISTIC_TYPE_CODE,
       G.JURISTIC_NAME,G.ENTERPRISE_TYPE_CODE,G.CALLING_TYPE_CODE, 
       U.SERIAL_NUMBER,U.PRODUCT_ID,T.START_DATE,T.END_DATE
  FROM TF_F_USER_BLACKWHITE T,TF_F_CUST_GROUP G,TF_F_USER U
 WHERE T.GROUP_ID = G.GROUP_ID
   AND SYSDATE BETWEEN T.START_DATE AND T.END_DATE
   AND G.CUST_ID = U.CUST_ID
   AND U.REMOVE_TAG = '0'
   AND G.REMOVE_TAG='0'
   AND T.SERIAL_NUMBER =:SERIAL_NUMBER