SELECT MONTH, USER_ID, SERIAL_NUMBER, DEAL_FLAG, ACCEPT_DATE, PRIZE_TYPE_CODE,
       EXEC_FLAG, EXEC_TIME, REVC1, REVC2, REVC3, REVC4, REVC5, REMARK
  FROM TF_F_USER_LOTTERY
 WHERE 1 = 1
   AND (MONTH = :MONTH)
   AND (USER_ID = :USER_ID)
   AND (:SERIAL_NUMBER IS NULL OR SERIAL_NUMBER = :SERIAL_NUMBER)
   AND (:PRIZE_TYPE_CODE IS NULL OR PRIZE_TYPE_CODE = :PRIZE_TYPE_CODE)
   AND (:START_DATE IS NULL OR
       ACCEPT_DATE >= TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss'))
   AND (:END_DATE IS NULL OR
       ACCEPT_DATE < TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss'))
   AND (:DEAL_FLAG IS NULL OR DEAL_FLAG = :DEAL_FLAG)
 ORDER BY ACCEPT_DATE DESC
