UPDATE TF_F_USER_LOTTERY
   SET EXEC_FLAG        = '1',
       EXEC_TIME        = SYSDATE,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :STAFF_ID,
       UPDATE_DEPART_ID = :DEPART_ID
 WHERE 1 = 1
   AND MONTH = :MONTH
   AND USER_ID = :USER_ID
   AND EXEC_FLAG = '0'