SELECT LOG_ID, SUB_LOG_ID, PARTITION_ID, INVENT_ORG_ID, EPARCHY_CODE,
       CITY_CODE, OPER_DEPART_ID, OPER_STAFF_ID, STOCK_ID_O, STOCK_ID_N,
       OPER_TAG, COST_CEN_ID,
       TO_DATE(OPER_TIME, 'YYYY-MM-DD HH24:MI:SS') OPER_TIME,
       TO_DATE(ASSIGN_TIME, 'YYYY-MM-DD HH24:MI:SS') ASSIGN_TIME,
       RES_TYPE_CODE, RES_KIND_CODE, CAPACITY_TYPE_CODE, DEVICE_TYPE_CODE,
       DEVICE_FACTORY_CODE, DEVICE_MODEL_CODE, DEVICE_COLOR_CODE, ORDER_ID,
       SUPPLY_ID, SUPPLY_TYPE, AGENCY_ID, PROCUREMENT_TYPE, RES_STATE,
       OPER_TYPE_CODE, CAMPN_ID, PRODUCT_ID, SALE_TYPE_CODE, OPER_NUM,
       DC_TAG, CANCEL_SUB_LOG_ID,
       TO_DATE(RSRV_DATE1, 'YYYY-MM-DD HH24:MI:SS') CANCEL_DATE, REMARK,
       RSRV_TAG1, RSRV_TAG2, RSRV_TAG3,
       TO_DATE(CANCEL_DATE, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE1,
       TO_DATE(RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE2,
       TO_DATE(RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS') RSRV_DATE3, RSRV_STR1,
       RSRV_STR2, RSRV_STR3, RSRV_STR4, RSRV_STR5, RSRV_STR6, RSRV_STR7,
       RSRV_NUM1, RSRV_NUM2, RSRV_NUM3
  FROM TF_B_TRADE_RESOURCE_INTER
 WHERE LOG_ID = :LOG_ID
 	AND PARTITION_ID = TO_NUMBER(SUBSTR(:LOG_ID, 7, 2))