SELECT A.INST_ID,
A.NAVIGATE_ID,
A.INST_STATE NAVIGATE_STATE,
A.USER_ID        ,
A.SERIAL_NUMBER  ,
B.FLOW_ID        ,
B.INST_STATE     ,
B.ORDER_ID       ,
B.TRADE_ID       ,
B.EPARCHY_CODE   ,
B.UPDATE_TIME	 ,
B.UPDATE_DEPART_ID,
B.UPDATE_STAFF_ID,
C.FLOW_ORDER	 ,
D.FLOW_NAME
FROM TF_B_NAVIGATE_INST A,tf_b_navigate_flow_inst B,TD_B_NAVIGATE_CFG C,TD_B_NAVIGATE_FLOW D
WHERE A.INST_ID = B.INST_ID
AND A.INST_ID = :INST_ID
AND A.NAVIGATE_ID = C.NAVIGATE_ID
AND B.FLOW_ID = C.FLOW_ID
AND C.FLOW_ID = D.FLOW_ID
AND B.FLOW_ORDER = C.FLOW_ORDER
ORDER BY C.FLOW_ORDER ASC