SELECT DECODE(A.PRODUCTID,'',A.RECORDID,A.PRODUCTID)  PRODUCT_ID, A.MATERIALCODE MATERIAL_CODE, A.CUSTOMERTYPE CUSTOMER_TYPE, A.VENDORCODE VENDOR_CODE,
	A.NAME NAME, A.COLOR COLOR, A.INDATE IN_DATE, A.RECOMMENDPRICE RECOMMEND_PRICE, A.MAXPRICE MAX_PRICE, 
	A.PRODUCTIONSTATUS PRODUCTION_STATUS, A.PRODUCTSTATUS PRODUCT_STATUS, A.PICTURETYPE PICTURE_TYPE,
	A.CUSTOMERPICTURE CUSTOMER_PICTURE, A.VERSIONS VERSIONS, A.PRODUCTPACKAGE PRODUCT_PACKAGE,
	A.LOWEND LOW_END, A.STEERFLAG STEER_FLAG, A.PILOTPRODUCT PILOT_PRODUCT, A.OPRNUMB IN_TRADE_ID, A.OPRNUMB OPER_TRADE_ID,
	DECODE(A.TRANSTYPE,'1','0','2','1') VALID_TAG,DECODE(A.MODELTYPE,'','0',A.MODELTYPE) MODELTYPE,A.RETAILPRICE RETAILPRICE,A.JOINTYPE JOINTYPE
FROM TI_R_PRODUCT_DOWN A
WHERE 1 = 1
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND A.MODELTYPE ='1'