SELECT  SEND_ID,
  MAIL_ADDR,
  MAIL_TITLE,
  MAIL_CONTENT,
  FILE_NAME,
  CREATE_TIME,
  SEND_STATUS,
  SEND_TIME,
  SEND_STAFF_ID,
  CREATE_STAFF_ID,
  TASK_ID,
  ORDER_ID,
  VALID_FLAG,
  REMARK,
  RSRV_STR1
  FROM TF_F_MAIL_SEND
WHERE 1=1
AND SEND_STATUS = :SEND_STATUS
AND VALID_FLAG = :FLAG