insert into TF_O_CUSTOMERCLUB(SEQ_ID,TRADE_ID,SERIAL_NUMBER,CLUB_TYPE,AGREEMENT_TAG,ENTRY_TIME,IN_MODE_CODE,RELATED_ACTIVITY_ID,ACCEPT_TAG,
REASON,SINGNING_TIME,START_DATE,END_DATE,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,CUST_NAME,UPDATE_TIME,TRADE_STAFF_ID)
select :SEQ_ID,:TRADE_ID,SERIAL_NUMBER,CLUB_TYPE,AGREEMENT_TAG,ENTRY_TIME,:IN_MODE_CODE,RELATED_ACTIVITY_ID,'1',
:REASON,SINGNING_TIME,sysdate,to_date('2050-12-31 23:59:59','yyyy-mm-dd hh24:mi:ss'),RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,
CUST_NAME,sysdate,:TRADE_STAFF_ID
from TF_O_CUSTOMERCLUB a
where a.serial_number=:SERIAL_NUMBER
and sysdate < a.end_date
AND  CLUB_TYPE = :CLUB_TYPE
and a.accept_tag='0'