SELECT to_char(O.USER_ID) USER_ID,O.RSRV_VALUE_CODE,O.RSRV_VALUE,O.RSRV_NUM1,O.RSRV_NUM2,O.RSRV_NUM3,O.RSRV_NUM4,O.RSRV_NUM5,O.RSRV_NUM6,O.RSRV_NUM7,O.RSRV_NUM8,O.RSRV_NUM9,O.RSRV_NUM10,O.RSRV_NUM11,O.RSRV_NUM12,O.RSRV_NUM13,O.RSRV_NUM14,O.RSRV_NUM15,O.RSRV_NUM16,O.RSRV_NUM17,O.RSRV_NUM18,O.RSRV_NUM19,O.RSRV_NUM20,O.RSRV_STR1,O.RSRV_STR2,O.RSRV_STR3,O.RSRV_STR4,O.RSRV_STR5,O.RSRV_STR6,O.RSRV_STR7,O.RSRV_STR8,O.RSRV_STR9,O.RSRV_STR10,O.RSRV_STR11,O.RSRV_STR12,
O.RSRV_STR13,O.RSRV_STR14,O.RSRV_STR15,O.RSRV_STR16,O.RSRV_STR17,O.RSRV_STR18,O.RSRV_STR19,O.RSRV_STR20,O.RSRV_STR21,O.RSRV_STR22,O.RSRV_STR23,O.RSRV_STR24,
O.RSRV_STR25,O.RSRV_STR26,O.RSRV_STR27,O.RSRV_STR28,O.RSRV_STR29,O.RSRV_STR30,to_char(O.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,to_char(O.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,to_char(O.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,to_char(O.RSRV_DATE4, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE4,
to_char(O.RSRV_DATE5, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE5,to_char(O.RSRV_DATE6, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE6,to_char(O.RSRV_DATE7, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE7,to_char(O.RSRV_DATE8, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE8,to_char(O.RSRV_DATE9, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE9,to_char(O.RSRV_DATE10, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE10,O.RSRV_TAG1,O.RSRV_TAG2,O.RSRV_TAG3,O.RSRV_TAG4,O.RSRV_TAG5,O.RSRV_TAG6,O.RSRV_TAG7,O.RSRV_TAG8,O.RSRV_TAG9,O.RSRV_TAG10,O.PROCESS_TAG,O.STAFF_ID,O.DEPART_ID,to_char(O.TRADE_ID) TRADE_ID,to_char(O.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(O.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,to_char(O.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,O.UPDATE_STAFF_ID,O.UPDATE_DEPART_ID,O.REMARK,to_char(O.INST_ID) INST_ID
  FROM TF_B_TRADE_OTHER O,TF_B_TRADE T
 WHERE O.user_id = TO_NUMBER(:USER_ID)
   AND O.TRADE_ID = T.TRADE_ID
   AND cancel_tag='0'
   AND trade_type_code=4300
   AND O.rsrv_value_code = :RSRV_VALUE_CODE
   AND sysdate between O.start_date AND O.end_date