SELECT T.*  FROM TF_B_TRADE_OTHER T, 
	WHERE T.TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND T.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND T.MODIFY_TAG = '0'
       AND T.USER_ID = :USER_ID
	   AND T.INST_ID = :INST_ID