UPDATE TF_B_TRADE_OTHER
   SET RSRV_TAG1  = :RSRV_TAG1,
       RSRV_TAG2  = :RSRV_TAG2,
       REMARK  = :REMARK,
       RSRV_STR19 = :RSRV_STR19,
       RSRV_STR20 = :RSRV_STR20
 WHERE TRADE_ID = :TRADE_ID
   AND RSRV_VALUE_CODE = :RSRV_VALUE_CODE
