SELECT SESSION_ID, SERIAL_NUMBER, CREDENCE_NO, ACCEPT_START, ACCEPT_END
  FROM TF_B_WAP_SESSION
 WHERE SESSION_ID = :SESSION_ID AND SERIAL_NUMBER = :SERIAL_NUMBER AND (SYSDATE 
  BETWEEN ACCEPT_START AND ACCEPT_END)