SELECT USER_ID,
       RSRV_STR1        CHARGE_ID,
       RSRV_STR2        BOSS_SEQ,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8        RECV_FEE,
       RSRV_STR9        CANCEL_TAG,
       START_DATE       RECV_TIME,
       END_DATE         CANCEL_TIME,
       DEPART_ID        RECV_DEPART_ID,
       UPDATE_DEPART_ID CANCEL_DEPART_ID,
       STAFF_ID         RECV_STAFF_ID,
       UPDATE_STAFF_ID  CANCEL_STAFF_ID
  FROM TF_F_USER_OTHER A
 WHERE PARTITION_ID = TO_NUMBER(MOD(:SERIAL_NUMBER, 10000))
   AND USER_ID = :SERIAL_NUMBER
   AND TO_CHAR(A.START_DATE, 'YYYYMMDDHH24MISS') >
       TO_CHAR(SYSDATE, 'YYYYMMDD') || '000000'
   AND RSRV_VALUE_CODE = 'BIP2B085_T2040015'
   AND RSRV_VALUE = 'IBOSSACCOUNTPAY'
   AND RSRV_STR9 = :CANCEL_TAG
 ORDER BY A.START_DATE DESC
