SELECT TRADE_CITY_CODE,
       TRADE_STAFF_ID,
       SUM(ACTIVE_OLD_USER_NUM) ACTIVE_OLD_USER_NUM,
       SUM(ACTIVE_USER_OPEN_NUM) ACTIVE_USER_OPEN_NUM,
       SUM(ACTIVE_NEW_USER_NUM) ACTIVE_NEW_USER_NUM
  FROM (SELECT T.TRADE_CITY_CODE,
               T.TRADE_STAFF_ID,
               COUNT(1) ACTIVE_OLD_USER_NUM,
               0 ACTIVE_USER_OPEN_NUM,
               0 ACTIVE_NEW_USER_NUM
          FROM TF_BH_TRADE_STAFF T
         WHERE T.TRADE_TYPE_CODE = '240'
           AND T.CANCEL_TAG = '0'
           AND T.RSRV_STR1 = :PRODUCT_ID
           AND T.RSRV_STR2 = :PACKAGE_ID_A
           AND T.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
               TO_DATE(:END_DATE, 'yyyy-mm-dd')
           AND T.TRADE_STAFF_ID BETWEEN :X_START_STAFF_ID AND
               :X_END_STAFF_ID
           AND (T.TRADE_CITY_CODE = :TRADE_CITY_CODE OR
               :TRADE_CITY_CODE IS NULL)
         GROUP BY T.TRADE_CITY_CODE, T.TRADE_STAFF_ID
        UNION
        SELECT T.TRADE_CITY_CODE,
               T.TRADE_STAFF_ID,
               0 ACTIVE_OLD_USER_NUM,
               COUNT(1) ACTIVE_USER_OPEN_NUM,
               0 ACTIVE_NEW_USER_NUM
          FROM TF_BH_TRADE_STAFF T
         WHERE T.TRADE_TYPE_CODE = '10'
           AND T.CANCEL_TAG = '0'
           AND T.RSRV_STR5 = 'true'
           AND T.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
               TO_DATE(:END_DATE, 'yyyy-mm-dd')
           AND T.TRADE_STAFF_ID BETWEEN :X_START_STAFF_ID AND
               :X_END_STAFF_ID
           AND (T.TRADE_CITY_CODE = :TRADE_CITY_CODE OR
               :TRADE_CITY_CODE IS NULL)
         GROUP BY T.TRADE_CITY_CODE, T.TRADE_STAFF_ID
        UNION
        SELECT T.TRADE_CITY_CODE,
               T.TRADE_STAFF_ID,
               0 ACTIVE_OLD_USER_NUM,
               0 ACTIVE_USER_OPEN_NUM,
               COUNT(1) ACTIVE_NEW_USER_NUM
          FROM TF_BH_TRADE_STAFF T
         WHERE T.TRADE_TYPE_CODE = '240'
           AND T.CANCEL_TAG = '0'
           AND T.RSRV_STR1 = :PRODUCT_ID
           AND T.RSRV_STR2 = :PACKAGE_ID_B
           AND T.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
               TO_DATE(:END_DATE, 'yyyy-mm-dd')
           AND T.TRADE_STAFF_ID BETWEEN :X_START_STAFF_ID AND
               :X_END_STAFF_ID
           AND (T.TRADE_CITY_CODE = :TRADE_CITY_CODE OR
               :TRADE_CITY_CODE IS NULL)
         GROUP BY T.TRADE_CITY_CODE, T.TRADE_STAFF_ID)
 GROUP BY TRADE_CITY_CODE, TRADE_STAFF_ID