SELECT BATCH_TASK_ID,
       BATCH_TASK_NAME,
       BATCH_OPER_CODE,
       BATCH_OPER_NAME,
       TO_CHAR(START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(CREATE_TIME, 'YYYY-MM-DD HH24:MI:SS') CREATE_TIME,
       CREATE_STAFF_ID,
       CREATE_DEPART_ID,
       CREATE_CITY_CODE,
       CREATE_EPARCHY_CODE,
       SMS_FLAG,
       AUDIT_NO,
       REMARK,
       CODING_STR1,
       CODING_STR2,
       CODING_STR3,
       CODING_STR4,
       CODING_STR5,
       CONDITION1,
       CONDITION2,
       CONDITION3,
       CONDITION4,
       CONDITION5
  FROM TF_B_TRADE_BAT_TASK
  WHERE BATCH_TASK_ID = :BATCH_TASK_ID
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:BATCH_TASK_ID, 5, 2))
   AND BATCH_OPER_CODE = :BATCH_OPER_CODE
   AND BATCH_OPER_NAME = :BATCH_OPER_NAME
   AND CREATE_STAFF_ID = :CREATE_STAFF_ID
   AND CREATE_EPARCHY_CODE = :CREATE_EPARCHY_CODE
   AND CREATE_CITY_CODE = :CREATE_CITY_CODE
   AND CREATE_TIME >= TO_DATE(:START_DATE,'YYYY-MM-DD HH24:MI:SS')
   AND CREATE_TIME <= TO_DATE(:END_DATE,'YYYY-MM-DD HH24:MI:SS') + 1