UPDATE TF_F_USER_TELEPHONE
   SET START_DATE       = TO_DATE(:FINISH_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       REMARK           = :REMARK
 WHERE PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND USER_ID = TO_NUMBER(:USER_ID)
   AND START_DATE = TO_DATE(:START_DATE, 'YYYY-MM-DD HH24:MI:SS')