UPDATE TF_F_USER
   SET USER_TAG_SET     = :USER_TAG_SET,
   	   USER_STATE_CODESET = :USER_STATE_CODESET,
       REMOVE_TAG       = '0',
       LAST_STOP_TIME   = NULL,
       DESTROY_TIME     = NULL,
       PRE_DESTROY_TIME = NULL,
       UPDATE_TIME      = SYSDATE
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND REMOVE_TAG IN ('1', '2', '3', '4', '5', '6', '7')