UPDATE TF_B_TRADE_PAYRELATION
   SET START_CYCLE_ID =to_char(TO_DATE(:START_CYCLE_ID, 'YYYY-MM-DD HH24:MI:SS'),'yyyymmdd')
 WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))