--IS_CACHE=N
SELECT D.DEPART_ID 受理部门,D.DEPART_KIND_CODE 部门类型, TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') 受理月份,A.TRADE_ID 台账标识
FROM ucr_crm1.TF_BH_TRADE A, TD_M_DEPART D
 WHERE A.TRADE_TYPE_CODE = '325'
   AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
   AND A.CANCEL_TAG = '0'
   AND A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.TRADE_DEPART_ID = D.DEPART_ID
   AND ROWNUM < 2