SELECT A.PARA_CODE1, A.PARA_CODE3, to_char(B.END_DATE, 'YYYY-MM-DD')END_DATE,B.DISCNT_CODE
  FROM TD_S_COMMPARA A,TF_F_USER_DISCNT B
 WHERE A.SUBSYS_CODE = 'CSM'
   AND A.PARAM_ATTR = 2005
   AND A.PARAM_CODE = 'OUTNPLIMIT'
   AND A.PARA_CODE2 = 'D'
   AND (A.EPARCHY_CODE = :EPARCHY_CODE OR A.EPARCHY_CODE = 'ZZZZ')
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   AND B.USER_ID = TO_NUMBER(:USER_ID)
   AND TO_NUMBER(DECODE(A.PARA_CODE4,NULL,'1',A.PARA_CODE4)) <= TO_NUMBER( DECODE(A.PARA_CODE4,NULL,'1',:STAR_LEVEL )) 
   AND B.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND SYSDATE BETWEEN B.START_DATE AND B.END_DATE
   AND A.PARA_CODE1 = TO_CHAR(B.DISCNT_CODE)