SELECT IMSI
  FROM TF_F_USER_RES A
 WHERE RES_TYPE_CODE = '1'
   AND SYSDATE < END_DATE
   AND EXISTS (SELECT 1
          FROM TF_F_USER B, TF_F_USER_SVC C
         WHERE A.USER_ID = B.USER_ID
           AND A.PARTITION_ID = B.PARTITION_ID
           AND B.PARTITION_ID = C.PARTITION_ID
           AND B.USER_ID = C.USER_ID
           AND B.REMOVE_TAG = '0'
           AND C.SERVICE_ID = 22
           AND SYSDATE < C.END_DATE)