UPDATE TF_B_TRADE_OTHER
   SET RSRV_STR10       = :RSRV_STR10,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = 'DATACOMP',
       UPDATE_DEPART_ID = 'DATAC',
 WHERE ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
   AND TRADE_ID = :TRADE_ID
   AND RSRV_VALUE_CODE = 'V2CP'
   AND RSRV_VALUE = '32'
   AND RSRV_STR11 = '12'