SELECT PARTITION_ID,
       TO_CHAR(USER_ID) USER_ID,
       TO_CHAR(ACCT_ID) ACCT_ID,
       PAYITEM_CODE,
       ACCT_PRIORITY,
       USER_PRIORITY,
       TO_CHAR(ADDUP_MONTHS) ADDUP_MONTHS,
       ADDUP_METHOD,
       BIND_TYPE,
       DEFAULT_TAG,
       ACT_TAG,
       LIMIT_TYPE,
       TO_CHAR(LIMIT) LIMIT,
       COMPLEMENT_TAG,
       TO_CHAR(INST_ID) INST_ID,
       START_CYCLE_ID,
       END_CYCLE_ID,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_STR6,
       RSRV_STR7,
       RSRV_STR8,
       RSRV_STR9,
       RSRV_STR10
  FROM TF_A_PAYRELATION A
 WHERE ACCT_ID = TO_NUMBER(:ACCT_ID)
   AND DEFAULT_TAG = '1'
   AND END_CYCLE_ID > START_CYCLE_ID
   AND END_CYCLE_ID > TO_CHAR(SYSDATE, 'YYYYMMDD')
   AND ACT_TAG = '1'
   AND EXISTS (SELECT 1
          FROM TF_F_USER
         WHERE PARTITION_ID = MOD(TO_NUMBER(A.USER_ID), 10000)
           AND USER_ID = A.USER_ID
           AND REMOVE_TAG = '0')
 ORDER BY START_CYCLE_ID