--IS_CACHE=N
SELECT COUNT(1) 统计数
   FROM (SELECT 1
           FROM TF_F_USER_SVC A
          WHERE A.USER_ID = :USER_ID
            AND A.PARTITION_ID = MOD(:USER_ID, 10000)
            AND A.SERVICE_ID = '21'
            AND TO_DATE(:SEND_TIME, 'YYYYMMDD') BETWEEN TRUNC(A.START_DATE) AND
                A.END_DATE
            AND TRUNC(A.UPDATE_TIME) < TO_DATE('2016-04-20', 'YYYY-MM-DD')
            AND A.END_DATE < TO_DATE(:SEND_TIME, 'YYYYMMDD') + 1
         UNION
         SELECT 1
           FROM TF_F_USER_PLATSVC A
          WHERE A.PARTITION_ID = MOD(:USER_ID, 10000)
            AND A.USER_ID = :USER_ID
            AND TO_DATE(:SEND_TIME, 'YYYYMMDD') BETWEEN TRUNC(A.START_DATE) AND
                A.END_DATE
            AND TRUNC(A.UPDATE_TIME) >= TO_DATE('2016-04-20', 'YYYY-MM-DD')
            AND A.END_DATE < TO_DATE(:SEND_TIME, 'YYYYMMDD') + 1
			AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT C WHERE C.COLLECT_ID=:COLLECT_ID AND C.COLLECT_DEF=A.SERVICE_ID))