 UPDATE TF_F_WIDENET_SYNC
  SET CANCEL_DATE= SYSDATE, UPDATE_STAFF_ID = :UPDATE_STAFF_ID, UPDATE_DEPART_ID = :UPDATE_DEPART_ID, ACCEPT_TAG = :ACCEPT_TAG,
    REMARKS = :REMARKS
 WHERE 1 = 1
  AND SERIAL_NUMBER = :SERIAL_NUMBER
  AND WIDENET_SYNC_ID = :WIDENET_SYNC_ID