SELECT PARTITION_ID,
       ID,
       ID_TYPE,
       CUST_TYPE,
       POST_NAME,
       POST_TAG,
       POST_CONTENT,
       POST_TYPESET,
       POST_CYC,
       POST_ADDRESS,
       POST_CODE,
       EMAIL,
       FAX_NBR,
       to_char(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       to_char(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       to_char(UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       UPDATE_STAFF_ID,
       UPDATE_DEPART_ID,
       REMARK,
       RSRV_NUM1,
       RSRV_NUM2,
       RSRV_NUM3,
       RSRV_NUM4,
       RSRV_NUM5,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       to_char(RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       to_char(RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       to_char(RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       RSRV_TAG1,
       RSRV_TAG2,
       RSRV_TAG3,
       to_char(INST_ID) INST_ID
  FROM tf_f_postinfo
 WHERE id = TO_NUMBER(:ID)
   AND id_type = :ID_TYPE
   AND sysdate BETWEEN start_date AND end_date
