SELECT t.PARTITION_ID,
       to_char(t.USER_ID) USER_ID,
       to_char(t.CUST_ID) CUST_ID,
       to_char(t.USECUST_ID) USECUST_ID,
       t.EPARCHY_CODE,
       t.CITY_CODE,
       t.CITY_CODE_A,
       t.USER_PASSWD,
       t.USER_DIFF_CODE,
       t.USER_TYPE_CODE,
       t.USER_TAG_SET,
       t.USER_STATE_CODESET,
       t.NET_TYPE_CODE,
       t.SERIAL_NUMBER,
       t.CONTRACT_ID,
       t.ACCT_TAG,
       t.PREPAY_TAG,
       t.MPUTE_MONTH_FEE,
       to_char(t.MPUTE_DATE, 'yyyy-mm-dd hh24:mi:ss') MPUTE_DATE,
       to_char(t.FIRST_CALL_TIME, 'yyyy-mm-dd hh24:mi:ss') FIRST_CALL_TIME,
       to_char(t.LAST_STOP_TIME, 'yyyy-mm-dd hh24:mi:ss') LAST_STOP_TIME,
       to_char(t.CHANGEUSER_DATE, 'yyyy-mm-dd hh24:mi:ss') CHANGEUSER_DATE,
       t.IN_NET_MODE,
       to_char(t.IN_DATE, 'yyyy-mm-dd hh24:mi:ss') IN_DATE,
       t.IN_STAFF_ID,
       t.IN_DEPART_ID,
       t.OPEN_MODE,
       to_char(t.OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       t.OPEN_STAFF_ID,
       t.OPEN_DEPART_ID,
       t.DEVELOP_STAFF_ID,
       to_char(t.DEVELOP_DATE, 'yyyy-mm-dd hh24:mi:ss') DEVELOP_DATE,
       t.DEVELOP_DEPART_ID,
       t.DEVELOP_CITY_CODE,
       t.DEVELOP_EPARCHY_CODE,
       t.DEVELOP_NO,
       to_char(t.ASSURE_CUST_ID) ASSURE_CUST_ID,
       t.ASSURE_TYPE_CODE,
       to_char(t.ASSURE_DATE, 'yyyy-mm-dd hh24:mi:ss') ASSURE_DATE,
       t.REMOVE_TAG,
       to_char(t.PRE_DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') PRE_DESTROY_TIME,
       to_char(t.DESTROY_TIME, 'yyyy-mm-dd hh24:mi:ss') DESTROY_TIME,
       t.REMOVE_EPARCHY_CODE,
       t.REMOVE_CITY_CODE,
       t.REMOVE_DEPART_ID,
       t.REMOVE_REASON_CODE,
       to_char(t.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       t.UPDATE_STAFF_ID,
       t.UPDATE_DEPART_ID,
       t.REMARK,
       t.RSRV_NUM1,
       t.RSRV_NUM2,
       t.RSRV_NUM3,
       to_char(t.RSRV_NUM4) RSRV_NUM4,
       to_char(t.RSRV_NUM5) RSRV_NUM5,
       t.RSRV_STR1,
       t.RSRV_STR2,
       t.RSRV_STR3,
       t.RSRV_STR4,
       t.RSRV_STR5,
       t.RSRV_STR6,
       t.RSRV_STR7,
       t.RSRV_STR8,
       t.RSRV_STR9,
       t.RSRV_STR10,
       to_char(t.RSRV_DATE1, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,
       to_char(t.RSRV_DATE2, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,
       to_char(t.RSRV_DATE3, 'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,
       t.RSRV_TAG1,
       t.RSRV_TAG2,
       t.RSRV_TAG3
  FROM tf_f_user t
 WHERE serial_number = :SERIAL_NUMBER
   AND remove_tag <> '0'
   AND open_date = (SELECT MAX(open_date)
                         FROM tf_f_user
                        WHERE serial_number = :SERIAL_NUMBER
                          AND remove_tag <> '0')
   AND NOT EXISTS (SELECT 1
          FROM tf_f_user
         WHERE serial_number = :SERIAL_NUMBER
           AND remove_tag = '0')