SELECT PARTITION_ID     ,
  ACCT_ID          ,
  ACCT_DAY         ,
  CHG_TYPE         ,
  CHG_MODE         ,
  CHG_DATE         ,
  FIRST_DATE       ,
  INST_ID          ,
  START_DATE       ,
  END_DATE         ,
  UPDATE_TIME      ,
  UPDATE_STAFF_ID  ,
  UPDATE_DEPART_ID ,
  REMARK           ,
  RSRV_NUM1        ,
  RSRV_NUM2        ,
  RSRV_NUM3        ,
  RSRV_NUM4        ,
  RSRV_NUM5        ,
  RSRV_STR1        ,
  RSRV_STR2        ,
  RSRV_STR3        ,
  RSRV_STR4        ,
  RSRV_STR5        ,
  RSRV_DATE1       ,
  RSRV_DATE2       ,
  RSRV_DATE3       ,
  RSRV_TAG1        ,
  RSRV_TAG2        ,
  RSRV_TAG3       
    FROM TF_F_ACCOUNT_ACCTDAY
    WHERE ACCT_ID = :ACCT_ID
     AND PARTITION_ID = MOD(TO_NUMBER(:ACCT_ID), 10000)
    MINUS
    SELECT 
    PARTITION_ID     ,
  ACCT_ID          ,
  ACCT_DAY         ,
  CHG_TYPE         ,
  CHG_MODE         ,
  CHG_DATE         ,
  FIRST_DATE       ,
  INST_ID          ,
  START_DATE       ,
  END_DATE         ,
  UPDATE_TIME      ,
  UPDATE_STAFF_ID  ,
  UPDATE_DEPART_ID ,
  REMARK           ,
  RSRV_NUM1        ,
  RSRV_NUM2        ,
  RSRV_NUM3        ,
  RSRV_NUM4        ,
  RSRV_NUM5        ,
  RSRV_STR1        ,
  RSRV_STR2        ,
  RSRV_STR3        ,
  RSRV_STR4        ,
  RSRV_STR5        ,
  RSRV_DATE1       ,
  RSRV_DATE2       ,
  RSRV_DATE3       ,
  RSRV_TAG1        ,
  RSRV_TAG2        ,
  RSRV_TAG3     
    FROM TF_B_TRADE_ACCOUNT_ACCTDAY_BAK
    WHERE TRADE_ID = :TRADE_ID
    AND ACCEPT_MONTH = :ACCEPT_MONTH