--IS_CACHE=Y
SELECT A.FRAME_ID,
       A.ROLE_CODE,
       B.NET_TYPE_CODE,
       B.ROLE_NAME,
       C.BUTTON_ID,
       C.BUTTON_TEXT,
       C.EVENT_CLICK
  FROM TD_B_FRAME_BUTTON A, TD_B_ROLE B, TD_B_BUTTON C
 WHERE A.ROLE_CODE = :ROLE_CODE
   AND A.FRAME_ID = :FRAME_ID
   AND A.ROLE_CODE = B.ROLE_CODE
   AND A.BUTTON_ID = C.BUTTON_ID
   AND A.STATE = '1'
   AND B.STATE = '1'
   AND C.STATE = '1'