SELECT a.SERIAL_NUMBER RES_NO,
       a.RSRV_STR6 STOCK_DEPART_NAME ,
       a.RSRV_STR5 STAFF_ID ,
       a.RSRV_STR7 USE_TERMINAL_MODEL ,
       b.brand_name||ai.res_type_name TERMINAL_MODEL_CODE,
       a.ORDER_ID TRADE_ID,
       to_char(a.START_TIME,'YYYY-MM-DD HH24:MI:SS') OCCUPY_TIME,
       to_char(a.END_TIME,'YYYY-MM-DD HH24:MI:SS') VALID_TIME,
       a.TRADE_STAFF_ID OCCUPY_STAFF_ID,
       decode(a.rsrv_str2,'0','未处理','1','已处理','2','取消','未知') RES_STATE_NAME,
       a.UPDATE_STAFF_ID USE_STAFF_ID,
       to_char(a.UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS') USE_TIME,
       a.ORDER_TYPE ORDER_TYPE,
       a.USE_PRODUCT_ID,
       a.USE_PACKAGE_ID,
       a.RSRV_STR3 RSRV_STR3,
       a.RSRV_STR4 RSRV_STR4,
       a.ORDER_PRICE ORDER_PRICE 
FROM TF_F_TERMINALORDER A,MV_IM_RES_TYPE ai,MV_PSI_CFG_RESBRAND b
WHERE 1 = 1
	AND ai.BRAND_ID=b.BRAND_ID 
  AND ai.RES_TYPE_ID =a.DEVICE_MODEL_CODE   
	AND (:SERIAL_NUMBER is null or A.SERIAL_NUMBER = :SERIAL_NUMBER)
  AND (:PROCESS_TAG is null or A.rsrv_str2=:PROCESS_TAG)
  AND A.START_TIME + 0 BETWEEN TO_DATE(:START_DATE, 'YYYY-MM-DD') AND TO_DATE(:END_DATE, 'YYYY-MM-DD')+1
 	ORDER BY A.START_TIME DESC