--IS_CACHE=Y
select adjust_reason_id RSRV_NUM1,0 RSRV_NUM2,
0 RSRV_NUM3,'' PARA_CODE1,'' PARA_CODE2,adjust_reason PARA_CODE3,
'' PARA_CODE4,'' PARA_CODE5,'' PARA_CODE6,
'' PARA_CODE7,'' PARA_CODE8,''PARA_CODE9 ,'SEL_AFTERADJUSTREASON' CALLING_TYPE_CODE
from TD_A_ADJUSTREASON where adjust_type='2'