--IS_CACHE=Y
select tag_number rsrv_Num1, 0 rsrv_Num2, 0 rsrv_Num3,'' PARA_CODE1,
'' PARA_CODE2,'' PARA_CODE3,'' PARA_CODE4,'' PARA_CODE4,'' PARA_CODE5,'' PARA_CODE6,
'' PARA_CODE7,'' PARA_CODE8,'' PARA_CODE9 FROM TD_S_TAG WHERE TAG_CODE ='ASM_NOTE_MGR_QPAYLOG_MONTHS'
AND USE_TAG='1'