--IS_CACHE=Y
SELECT t.PRODUCT_ID FROM TD_B_PRODUCT_MEB t
LEFT JOIN TD_B_PRODUCT_PACKAGE a ON t.PRODUCT_ID_B=a.PRODUCT_ID
LEFT JOIN TD_B_PRODUCT b ON a.PRODUCT_ID=b.PRODUCT_ID
LEFT JOIN TD_B_PACKAGE_ELEMENT c ON a.PACKAGE_ID=c.PACKAGE_ID
WHERE c.ELEMENT_ID=:SERVICE_ID
AND c.ELEMENT_TYPE_CODE='S'
 AND SYSDATE BETWEEN c.START_DATE AND c.END_DATE
 AND (b.product_mode='12' OR b.product_mode='13')
 AND SYSDATE BETWEEN a.start_date AND a.end_date