SELECT DECODE(A.PRODUCTID,'',A.RECORDID,A.PRODUCTID)  PRODUCT_ID,	C.PROVINCEID PROVINCEID,A.MATERIALCODE MATERIAL_CODE
FROM TI_R_PRODUCT_DOWN A, TI_R_PRODUCT_JOINPROV_DOWN C
WHERE 1 = 1
AND A.RECORDID = C.RECORDID
AND A.DEALFLAG = :DEALFLAG
AND A.OPRFLAG = :OPRFLAG
AND A.RECORDDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND A.MODELTYPE ='1'