SELECT /*+index (a PK_TF_B_TRADE_PLAT_REGISTER)*/ PARTITION_ID,to_char(TRADE_ID) TRADE_ID,to_char(USER_ID) USER_ID,SERIAL_NUMBER,BIZ_TYPE_CODE,ORG_DOMAIN,OPR_SOURCE,PASSWD,BIZ_STATE_CODE,OPEN_TAG,SVC_LEVEL,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,to_char(RSRV_NUM4) RSRV_NUM4,to_char(RSRV_NUM5) RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,to_char(RSRV_DATE1,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE1,to_char(RSRV_DATE2,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE2,to_char(RSRV_DATE3,'yyyy-mm-dd hh24:mi:ss') RSRV_DATE3,REMARK,UPDATE_STAFF_ID,UPDATE_DEPART_ID,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,OPER_CODE
  FROM TF_B_TRADE_PLAT_REGISTER a
 WHERE PARTITION_ID = MOD(a.trade_id,10000)
   AND USER_ID = to_number(:USER_ID)
   AND BIZ_TYPE_CODE = :BIZ_TYPE_CODE
   AND (EXISTS(SELECT 1 FROM TF_B_TRADE b 
               WHERE b.TRADE_ID = a.TRADE_ID) or EXISTS(SELECT 1 FROM tf_b_trade_predeal c 
               WHERE c.TRADE_ID = a.TRADE_ID))