SELECT   PRINT_ID,TRADE_ID,ACCEPT_MONTH,FEE,TICKET_ID,TAX_NO,TERM_ID,CHIP_ID,SECURITY_CODE,TRADE_TYPE_CODE,
TRADE_STAFF_ID,TRADE_DEPART_ID,TRADE_CITY_CODE,TRADE_EPARCHY_CODE,ACCEPT_TIME,SUCCESS_FLAG,COMMIT_TAG,
decode(TICKET_STATE_CODE,'0','正常发票','1','未使用报废处理','2','退票处理','3','错票处理','4','使用废票处理','5','重打发票','6','负值发票') TICKET_STATE_CODE,
DEAL_STATE,DEAL_DATE,DEAL_RESULT,PRIORITY,JMJ_STATE FROM TF_B_TICKET
 WHERE 1=1
 AND TAX_NO=:TAX_NO 
 AND TICKET_ID between :TICKET_START AND :TICKET_END
 AND TRADE_STAFF_ID=:TRADE_STAFF_ID
 AND ACCEPT_TIME> to_date(:START_DATE,'yyyy-mm-dd')
 AND  ACCEPT_TIME<to_date(:END_DATE,'yyyy-mm-dd')
 AND DEAL_STATE='2'