--IS_CACHE=Y
SELECT TYPE, RATE, FEE, FEE_TYPE_CODE,RES_TAG
  FROM TD_B_ELEMENT_TAX T
 WHERE T.TRADE_TYPE_CODE = :TRADE_TYPE_CODE
   AND T.ELEMENT_TYPE_CODE = :ELEMENT_TYPE_CODE
   AND T.PRODUCT_ID = :PRODUCT_ID 
   AND T.PACKAGE_ID =:PACKAGE_ID
   AND T.ELEMENT_ID =:ELEMENT_ID
   AND TO_DATE(:NOW_DATE, 'YYYY-MM-DD hh24:mi:ss') BETWEEN T.START_DATE AND
       T.END_DATE
   AND T.EPARCHY_CODE = :EPARCHY_CODE