SELECT OPR_SEQ,
       PROVINCE_ID,
       EC_ID,
       MAIN_PRODUCT,
       TO_CHAR(APPLICATION_ATTR) APPLICATION_ATTR,
       REPORT_NUM,
       CARDS_NUM,
       TO_CHAR(CONTRACT_AWARD_DATE, 'YYYY-MM-DD') CONTRACT_AWARD_DATE,
       TO_CHAR(CONTRACT_EFFEC_DATE, 'YYYY-MM-DD') CONTRACT_EFFEC_DATE,
       TO_CHAR(CONTRACT_EXPIRE_DATE, 'YYYY-MM-DD') CONTRACT_EXPIRE_DATE,
       PROV_DOC,
       APPLICANT,
       APPLICANT_PHONE,
       TO_CHAR(APPLY_DATE, 'YYYY-MM-DD') APPLY_DATE,
       APPLY_REASON,
       APPROVAL_RSLT,
       APPROVAL_NO,
       APPROVAL_COMM,
       APPROVAL_DOC,
       TO_CHAR(CREATE_TIME, 'YYYY-MM-DD HH24:MI:SS') CREATE_TIME,
       CREATE_STAFF_ID,
       TO_CHAR(UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3,
       RSRV_STR4,
       RSRV_STR5,
       RSRV_DATE1,
       RSRV_TAG1
  FROM TF_O_DISCNT_APPLY T
 WHERE 1 = 1
   AND EC_ID = :EC_ID
   AND CREATE_STAFF_ID = :CREATE_STAFF_ID 
   AND CREATE_TIME >= TO_DATE(:START_DATE, 'YYYY-MM-DD')
   AND CREATE_TIME <= TO_DATE(:END_DATE, 'YYYY-MM-DD')
   AND APPROVAL_RSLT = :APPROVAL_RSLT
   AND RSRV_STR1 = :RSRV_STR1