UPDATE  TF_O_DISCNT_APPLY SET   APPROVAL_RSLT =:APPROVAL_RSLT ,
  APPROVAL_NO =:APPROVAL_NO ,
  APPROVAL_COMM =:APPROVAL_COMM ,
  APPROVAL_DOC =:APPROVAL_DOC ,
  UPDATE_TIME = Sysdate
  WHERE OPR_SEQ =:OPR_SEQ