SELECT TO_CHAR(T.USER_TRUNK_ID) RSRV_STR1,
       TO_CHAR(T.MSC_ID) RSRV_STR2,
       TO_CHAR(T.TRUNK_ID) RSRV_STR3,
       TO_CHAR(T.USER_ID) USER_ID,
       TO_CHAR(T.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(T.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       TO_CHAR(T.INST_ID) INST_ID
  FROM TF_F_USER_TRUNK T
 WHERE T.USER_ID = TO_NUMBER(:USER_ID)
   AND T.END_DATE > SYSDATE