SELECT A.SERIAL_NUMBER,
       TO_CHAR(A.ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       A.MAKE_STATE MAKE_STATE,
       DECODE(A.MAKE_STATE, '0', '定制状态', 'D', '定制取消', '其他状态') MAKE_STATE_TEXT,
       DECODE(A.MAKE_TERMINAL, '11000040', '语音交易', '终端交易') MAKE_TERMINAL,
       A.COMMENDER_ID,
       TO_CHAR(A.UPDATE_TIME, 'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME,
       A.UPDATE_STAFF_ID,
       A.UPDATE_DEPART_ID,
       TO_CHAR(A.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       A.CANCEL_STAFF_ID,
       A.CANCEL_DEPART_ID,
       A.REMARK REMARK
FROM TF_A_BANKPACKET A, TF_F_USER B
WHERE A.USER_ID = B.USER_ID
   AND B.REMOVE_TAG = '0'
   AND B.SERIAL_NUMBER >= :START_SERIALNUMBER
   AND B.SERIAL_NUMBER <= :END_SERIALNUMBER   
   AND SYSDATE >= A.START_DATE
   AND A.ACCEPT_DATE BETWEEN TO_DATE(:START_DATE, 'yyyy-mm-dd') AND
       TO_DATE(:END_DATE, 'yyyy-mm-dd')
   AND A.MAKE_STATE = :MAKE_STATE