update TF_F_ACTIVE_TEMPLATE t
set T.RSRV_STR1=:RSRV_STR1,T.RSRV_STR2=:RSRV_STR2,T.RSRV_STR3=:RSRV_STR3,T.RSRV_STR4=:RSRV_STR4
where t.trade_type_code=:TRADE_TYPE_CODE
AND T.USER_ID=:USER_ID
AND T.DEAL_TAG='0'
and t.rsrv_str5=:TO_DAY