SELECT T.USER_ID_A,T.SERIAL_NUMBER_A,T.USER_ID_B,T.SERIAL_NUMBER_B,
        T.RELATION_TYPE_CODE,T.ROLE_TYPE_CODE, T.ROLE_CODE_A, T.ROLE_CODE_B,
        T.ORDERNO,T.SHORT_CODE,T.INST_ID,T.START_DATE,T.END_DATE,
				T.UPDATE_TIME,T.UPDATE_STAFF_ID,T.UPDATE_DEPART_ID,T.REMARK
FROM TF_F_RELATION_UU T
WHERE 1=1
AND T.USER_ID_A = :USER_ID_A
AND T.USER_ID_B = :USER_ID_B
AND T.RELATION_TYPE_CODE = :RELATION_TYPE_CODE
AND T.START_DATE <= TO_DATE(:START_DATE, 'yyyy-mm-dd hh24:mi:ss')
AND T.END_DATE >= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')