SELECT UU.PARTITION_ID,
       TO_CHAR(UU.USER_ID_A) USER_ID_A,
       TO_CHAR(UU.USER_ID_B) USER_ID_B,
       UU.RELATION_TYPE_CODE,
       UU.ROLE_CODE_A,
       UU.ROLE_CODE_B,
       UU.ORDERNO,
       UU.SHORT_CODE,
       TO_CHAR(UU.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(UU.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       TO_CHAR(UU.INST_ID) INST_ID,
       UU.SERIAL_NUMBER_A,
       UU.SERIAL_NUMBER_B
  FROM TF_F_USER_IMPU U,TF_F_RELATION_UU UU
 WHERE U.USER_ID = UU.USER_ID_B 
   AND UU.USER_ID_A = :USER_ID_A
   AND SYSDATE BETWEEN UU.START_DATE AND UU.END_DATE
   AND SYSDATE BETWEEN U.START_DATE AND U.END_DATE
   AND U.PARTITION_ID = UU.PARTITION_ID
   AND UU.SHORT_CODE = :SHORT_CODE