SELECT rsrv_str2 EPARCHY_CODE,rsrv_str5 USER_ID,TO_NUMBER(rsrv_str6) CREDIT_CLASS,rsrv_str8 CREDIT_VALUE 
 FROM Tf_f_User_Other 
WHERE USER_ID =to_number(:USER_ID) 
   AND RSRV_VALUE_CODE ='AGAC' 
   AND SYSDATE BETWEEN START_DATE AND END_DATE