SELECT TO_CHAR(CAMPN_ID) CAMPN_ID,
       SERIAL_NUMBER,
       CAMPN_CODE,
       CAMPN_NAME,
       PRODUCT_NAME,
       PACKAGE_NAME,
       CAMPN_TYPE,
       TO_CHAR(ACCEPT_DATE, 'yyyy-mm-dd hh24:mi:ss') ACCEPT_DATE,
       TO_CHAR(START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_USER_SALE_ACTIVE
 WHERE USER_ID = :USER_ID
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND PROCESS_TAG = '0'
   AND SYSDATE BETWEEN START_DATE AND END_DATE 