UPDATE TF_F_USER_COMP_RELA
   SET END_DATE =trunc(last_day(SYSDATE)+1)-1/24/3600,
	     UPDATE_TIME=TO_DATE(:UPDATE_TIME,'YYYY-MM-DD HH24:MI:SS'),
	     UPDATE_STAFF_ID=:UPDATE_STAFF_ID,
			 UPDATE_DEPART_ID=:UPDATE_DEPART_ID
  WHERE COMP_USER_ID = TO_NUMBER(:COMP_USER_ID)
  AND end_date>trunc(last_day(SYSDATE)+1)-1/24/3600