INSERT INTO TI_B_USER_INFOCHANGE (SYNC_SEQUENCE,  MODIFY_TAG,  trade_id , PARTITION_ID,USER_ID,TRADE_TYPE_CODE,RELATION_TRADE_ID,PRODUCT_ID,BRAND_CODE,SERIAL_NUMBER,IMSI,NET_TYPE_CODE,START_DATE,END_DATE,UPDATE_TIME,UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
        SELECT TO_NUMBER(:SYNC_SEQUENCE),'2',:TRADE_ID, a.PARTITION_ID,a.USER_ID,a.TRADE_TYPE_CODE,a.RELATION_TRADE_ID,a.PRODUCT_ID,a.BRAND_CODE,a.SERIAL_NUMBER,a.IMSI,a.NET_TYPE_CODE,a.START_DATE,a.START_DATE - 1/24/3600,a.UPDATE_TIME,a.UPDATE_STAFF_ID,a.UPDATE_DEPART_ID,'删除无效数据',a.RSRV_NUM1,a.RSRV_NUM2,a.RSRV_NUM3,a.RSRV_NUM4,a.RSRV_NUM5,a.RSRV_STR1,a.RSRV_STR2,a.RSRV_STR3,a.RSRV_STR4,a.RSRV_STR5,a.RSRV_DATE1,a.RSRV_DATE2,a.RSRV_DATE3,a.RSRV_TAG1,a.RSRV_TAG2,a.RSRV_TAG3
        FROM TF_B_TRADE_INFOCHANGE_BAK a 
        WHERE trade_id=:TRADE_ID
        AND accept_month=:ACCEPT_MONTH
        AND not exists (SELECT 1 from TI_B_USER_INFOCHANGE b
                        WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                        AND a.user_id=b.user_id
                        AND a.start_date=b.start_date)