   SELECT
          D.BRAND_CODE,
       D.RSRV_STR1 OLD_BRAND_CODE,
       to_char(D.UPDATE_TIME, 'YYYY-MM-DD HH24:MI:SS') AS UPDATE_TIME
	   FROM
	          TF_BH_TRADE D
   where  D.USER_ID=:USER_ID
   AND D.CUST_ID=:CUST_ID
   AND D.TRADE_ID = :TRADE_ID_A
   AND D.ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID_A, 5, 2))