UPDATE TF_B_ESIM_QRCODE T
SET RESULT_CODE = :BIZ_CODE,
    RESULT_MESSAGE = :BIZ_DESC,
    DOWNLOAD_URL = :DOWNLOAD_URL,
    ACTIVATION_CODE = :ACTIVATION_CODE,
    BIZ_TYPE_TIME = to_date(:BIZ_TYPE_TIME,'yyyyMMddHH24miss'),
    UPDATE_TIME = SYSDATE
 WHERE 1=1
   AND T.QR_CODE_ID = :QR_CODE_ID