SELECT T.INST_ID,T.PROD_INST_ID,T.INST_TYPE,T.USER_ID,T.SUBS_ID,T.PLAT_CODE,T.CREATE_TIME,T.REMARK,RSRV_STR1,RSRV_STR2,RSRV_STR3,T.RSRV_STR4,T.RSRV_STR5,T.RSRV_STR6
  FROM TF_F_INSTANCE_PF T
 WHERE T.USER_ID = :USER_ID
