insert into tf_f_user_family_circle(MAIN_MSISDN,TARGET_MSISDN,TARGET_NAME,TARGET_ROLE,GROUP_CODE,GROUP_TYPE,STATUS,GROUP_NAME,GROUP_AREA,START_DATE,END_DATE,REMARK,
RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,RSRV_STR5,RSRV_STR6,RSRV_STR7,RSRV_STR8,RSRV_STR9,RSRV_STR10) 
values(:MAIN_MSISDN,:TARGET_MSISDN,:TARGET_NAME,:TARGET_ROLE,:GROUP_CODE,:GROUP_TYPE,:STATUS,:GROUP_NAME,:GROUP_AREA,SYSDATE,
to_date('20501230235959','YYYYMMDDHH24MISS'),:REMARK,:RSRV_STR1,:RSRV_STR2,:RSRV_STR3,:RSRV_STR4,:RSRV_STR5,
:RSRV_STR6,:RSRV_STR7,:RSRV_STR8,:RSRV_STR9,:RSRV_STR10)
