SELECT SUSPECTIMEI TERMINAL_ID,CROREGTYPE CROSS_TYPE,CROREGDATE CROREG_DATE,CROREGRESULT CROSS_RESULT,REGPROVINCE REG_PROVINCE_ID 
FROM TI_R_CROSSREGIONAL_RSP 
WHERE STATE = '0' AND RSRVFLAG1 IS NULL
AND CROREGDATE <= TO_DATE(:END_DATE, 'yyyy-mm-dd hh24:mi:ss')