--IS_CACHE=Y
SELECT T.DEPART_ID,
       T.DEPART_CODE,
       '[' || T.DEPART_CODE || ']' || T.DEPART_NAME DEPART_NAME,
       T.DEPART_KIND_CODE,
       T.DEPART_FRAME,
       T.AREA_CODE,
       T.PARENT_DEPART_ID,
       T.DEPART_LEVEL,
       (SELECT COUNT(*) FROM TD_M_DEPART M WHERE M.PARENT_DEPART_ID = T.DEPART_ID AND M.VALIDFLAG = '0') NODE_COUNT
 FROM TD_M_DEPART T
 WHERE T.VALIDFLAG = '0'
  AND T.PARENT_DEPART_ID = :PARENT_DEPART_ID