--IS_CACHE=Y
SELECT A.DEPART_ID, A.DEPART_NAME,A.DEPART_NAME||'|'||A.DEPART_ID DEPART_NAME_ID
  FROM TD_M_DEPART A
 WHERE A.VALIDFLAG = '0'
   AND A.AREA_CODE = :AREA_CODE
   AND A.RSVALUE2 = :RSVALUE2
   AND A.DEPART_KIND_CODE NOT LIKE '0%'
   AND SYSDATE BETWEEN A.START_DATE AND A.END_DATE
   ORDER BY DEPART_ID DESC