--IS_CACHE=Y
 SELECT  ASRULE.DEPART_ID,ASRULE.DEPART_CODE||'|'||ASRULE.DEPART_NAME  DEPART_NAME,'0898' EPARCHY_CODE ,ASRULE.AREA_CODE
  FROM TD_M_DEPART ASRULE 
 WHERE  1=1  
 AND ASRULE.DEPART_LEVEL >= 3          
 AND ASRULE.AREA_CODE = :TRADE_CITY_CODE     
 AND ASRULE.VALIDFLAG='0'           
 AND  ASRULE.DEPART_ID = :DEPART_ID
 AND ASRULE.DEPART_NAME LIKE '%'||:DEPART_NAME||'%'
 AND ASRULE.DEPART_KIND_CODE  IN ( SELECT DEPART_KIND_CODE FROM  TD_M_DEPARTKIND  WHERE  CODE_TYPE_CODE='0'  AND EPARCHY_CODE=:TRADE_EPARCHY_CODE) 