--IS_CACHE=Y
SELECT A.AREA_CODE,
       A.AREA_CODE        CITY_CODE,
       B.AREA_LEVEL,
       B.PARENT_AREA_CODE,
       '0898'  EPARCHY_CODE,
       A.DEPART_ID        STOCK_ID,
       A.DEPART_NAME      STOCK_NAME,
       A.DEPART_FRAME     STOCK_FRAME,
       DECODE(C.CODE_TYPE_CODE,'0','0','S')  STOCK_LEVEL,
       A.PARENT_DEPART_ID PARENT_STOCK_ID
  FROM TD_M_DEPART A, TD_M_AREA B ,TD_M_DEPARTKIND C
 WHERE 
   A.VALIDFLAG='0' 
   AND A.DEPART_ID = :DEPART_ID
   AND A.AREA_CODE = B.AREA_CODE
   AND A.DEPART_KIND_CODE = C.DEPART_KIND_CODE
   