--IS_CACHE=Y
SELECT '0898' EPARCHY_CODE,
       A.DEPART_ID STOCK_ID,
       DEPART_CODE STOCK_CODE,
       A.DEPART_NAME STOCK_NAME,
       A.AREA_CODE PART_CODE,
       A.AREA_CODE CITY_CODE,
       A.DEPART_FRAME STOCK_FRAME,
       DECODE(D.CODE_TYPE_CODE,'0','0','S')  STOCK_LEVEL,
       A.PARENT_DEPART_ID PARENT_STOCK_ID,
       (SELECT PARENT_DEPART_ID
          FROM TD_M_DEPART C
         WHERE C.DEPART_ID = A.PARENT_DEPART_ID) GRAND_FATHER_ID,
       (SELECT DEPART_NAME
          FROM TD_M_DEPART B
         WHERE VALIDFLAG='0'
           AND B.DEPART_ID = A.PARENT_DEPART_ID) FATH_DEPART_NAME
  FROM TD_M_DEPART A,TD_M_DEPARTKIND D
 WHERE    A.VALIDFLAG='0'
   AND A.DEPART_ID = :DEPART_ID
   AND A.DEPART_KIND_CODE = D.DEPART_KIND_CODE