--IS_CACHE=Y
SELECT *
  FROM TD_M_DEPARTKIND B
 WHERE B.EPARCHY_CODE = :EPARCHY_CODE
   AND B.DEPART_KIND_CODE IN
       (SELECT A.DEPART_KIND_CODE
          FROM TD_M_DEPART A
         WHERE A.DEPART_ID = :DEPART_ID
           AND EPARCHY_CODE = :EPARCHY_CODE
           AND VALIDFLAG = '0'
         )