SELECT BUSI_TYPE,
       PARAM_CODE,
       ROLE_CODE,
       ROLE_TYPE,
       PARAM_VALUE1,
       PARAM_VALUE2,
       PARAM_VALUE3,
       PARAM_VALUE4,
       PARAM_VALUE5,
       PARAM_VALUE6,
       PARAM_VALUE7,
       PARAM_VALUE8,
       PARAM_VALUE9,
       PARAM_VALUE10,
       ORDER_NO,
       START_DATE,
       END_DATE,
       EPARCHY_CODE
FROM TD_S_FAMILY_PARAM T
WHERE BUSI_TYPE = :BUSI_TYPE
AND PARAM_CODE = :PARAM_CODE
AND sysdate between start_date and end_date
AND (EPARCHY_CODE ='ZZZZ' or EPARCHY_CODE=:EPARCHY_CODE)
