UPDATE TF_B_TRADE_NP
   SET STATE          = :STATE,
       MESSAGE_ID     = :MESSAGE_ID_NEW,
       FLOW_ID        = :FLOW_ID,
       MSG_CMD_CODE = :MSG_CMD_CODE,
       RESULT_CODE    = :RESULT_CODE,
       RESULT_MESSAGE = :RESULT_MESSAGE,
       RSRV_STR4      = :DEALMETHOD,
       REMARK         = :REMARK,
       AUTH_CODE      = :AUTH_CODE,
       AUTH_CODE_EXPIRED  = TO_DATE(:AUTH_CODE_EXPIRED,'yyyy-MM-dd HH24:mi:ss')
 WHERE TRADE_ID = :TRADE_ID
   AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))