SELECT PARTITION_ID,to_char(USER_ID) USER_ID,SERVICE_TYPE,DEAL_FLAG,to_char(START_DATE,'yyyy-mm-dd hh24:mi:ss') START_DATE,to_char(END_DATE,'yyyy-mm-dd hh24:mi:ss') END_DATE,to_char(UPDATE_TIME,'yyyy-mm-dd hh24:mi:ss') UPDATE_TIME
  FROM TF_F_USER_SVCSWITCH
 WHERE PARTITION_ID = mod(to_number(:USER_ID),10000)
   AND USER_ID = to_number(:USER_ID)
   AND SERVICE_TYPE = :SERVICE_TYPE
   AND DEAL_FLAG = :DEAL_FLAG
   AND SYSDATE BETWEEN START_DATE AND END_DATE