--IS_CACHE=Y
SELECT TPTTYPE.TEMPLET_NAME,
       TPT.TEMPLET_CODE,
       TPT.TEMPLET_PATH,
       TPT.PRINT_TYPE,
       TPT.PRINT_VERSION,
       TPTTYPE.TEMPLET_TYPE,
       TPTITEM.ITEM_CONTENT
  FROM TD_B_CNOTE_TEMPLET_ITEM TPTITEM,
       TD_B_CNOTE_TEMPLET      TPT,
       TD_B_CNOTE_TEMPLET_TYPE TPTTYPE
 WHERE TPT.TEMPLET_CODE = TPTITEM.TEMPLET_CODE
   AND TPT.TEMPLET_TYPE = TPTTYPE.TEMPLET_TYPE
   AND TPT.TEMPLET_CODE = :TEMPLET_CODE