--IS_CACHE=Y
SELECT 
A.ELEMENT_TYPE_CODE,
A.ELEMENT_ID,
A.RELA_ELEMENT_TYPE_CODE,
A.RELA_ELEMENT_ID,
A.RELA_ELEMENT_START,
A.START_OFFSET,
A.START_UNIT,
A.RELA_ELEMENT_END,
A.END_OFFSET,
A.END_UNIT,
A.REGEXP_SN,
A.TRADE_TYPE_CODE,
A.IN_MODE_CODE,
A.IS_RELA_DEL,
A.RSRV_STR1,
A.RSRV_STR2,
A.RSRV_STR3,
A.RSRV_STR4,
A.RSRV_STR5,
A.RSRV_STR6,
A.RSRV_STR7,
A.RSRV_STR8,
A.RSRV_STR9,
A.RSRV_STR10
FROM TD_B_ELEM_RELADEAL_ELEM A
where a.element_type_code = :ELEMENT_TYPE_CODE
and a.element_id = :ELEMENT_ID
and a.rela_element_type_code = :RELA_ELEMENT_TYPE_CODE
and sysdate between a.start_date and a.end_date
and (a.eparchy_code = :EPARCHY_CODE or a.eparchy_code = 'ZZZZ')