SELECT COUNT(1) SUC_COUNT
  FROM TF_B_CHANGETRADE A
 WHERE 1 = 1
   AND A.CHANGE_SERIAL_NUMBER = :CHANGE_SERIAL_NUMBER
   AND A.CHANGE_RESULT_CODE = '1'
   AND A.ACCEPT_MONTH = TO_NUMBER(TO_CHAR(SYSDATE, 'mm'))