--IS_CACHE=Y
SELECT PRODUCT_ID OBJ_CODE, PRODUCT_NAME OBJ_NAME
  FROM TD_B_PRODUCT T
 WHERE 1 = 1
   AND T.BRAND_CODE = :BRAND_CODE
   AND T.PRODUCT_STATE = 4
   AND T.END_DATE > SYSDATE
 ORDER BY PRODUCT_NAME, PRODUCT_ID