SELECT A.CUST_ID,
       A.VIP_ID,
       A.USER_ID,
       A.SERIAL_NUMBER,
       A.VIP_TYPE_CODE,
       A.VIP_CLASS_ID
  FROM TF_F_CUST_VIP A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND TO_CHAR(A.REMOVE_DATE, 'yyyy') = TO_CHAR(SYSDATE, 'yyyy')
   AND REMOVE_TAG IN ('2', '4')