SELECT A.USER_ID,
       A.PRODUCT_ID,
       A.PACKAGE_ID,
       A.RELATION_TRADE_ID,
       TO_CHAR(A.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE,
       PARAM_CODE,
       PARA_CODE1,
       PARA_CODE2,
       PARA_CODE3
  FROM TF_F_USER_SALE_ACTIVE A, TD_S_COMMPARA B
 WHERE A.USER_ID = :USER_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND A.PROCESS_TAG = '0'
   AND A.END_DATE > SYSDATE
   AND A.PRODUCT_ID = B.PARAM_CODE
   AND A.PACKAGE_ID = B.PARA_CODE1
   AND B.PARAM_ATTR = '50'
   AND B.END_DATE > SYSDATE