DELETE FROM TF_F_USER_ATTR A
 WHERE A.USER_ID = TO_NUMBER(:USER_ID)
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND EXISTS
        (SELECT 1 FROM TF_B_TRADE_ATTR_BAK
          WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
            AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID,5,2))            
            AND USER_ID = A.USER_ID
            AND INST_TYPE = A.INST_TYPE
            AND INST_ID = A.INST_ID 
            AND ATTR_CODE = A.ATTR_CODE
            AND START_DATE = A.START_DATE )