INSERT INTO TF_F_USER_ATTR(PARTITION_ID,USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,UPDATE_TIME,
    UPDATE_STAFF_ID,UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,
    RSRV_STR4,RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3)
SELECT MOD(USER_ID,10000),USER_ID,INST_TYPE,INST_ID,ATTR_CODE,ATTR_VALUE,START_DATE,END_DATE,sysdate,UPDATE_STAFF_ID,
    UPDATE_DEPART_ID,REMARK,RSRV_NUM1,RSRV_NUM2,RSRV_NUM3,RSRV_NUM4,RSRV_NUM5,RSRV_STR1,RSRV_STR2,RSRV_STR3,RSRV_STR4,
    RSRV_STR5,RSRV_DATE1,RSRV_DATE2,RSRV_DATE3,RSRV_TAG1,RSRV_TAG2,RSRV_TAG3
    FROM TF_B_TRADE_ATTR a
   WHERE TRADE_ID = TO_NUMBER(:TRADE_ID)
     AND ACCEPT_MONTH = TO_NUMBER(SUBSTR(:TRADE_ID, 5, 2))
     AND MODIFY_TAG in ('0','4')
     AND NOT EXISTS (SELECT 1 FROM TF_F_USER_ATTR
                      WHERE user_id = TO_NUMBER(:USER_ID)
                        AND partition_id = MOD(TO_NUMBER(:USER_ID), 10000)
                        AND inst_type = a.inst_type
                        AND inst_id = a.inst_id
                        AND ATTR_CODE = a.ATTR_CODE
                        AND ATTR_VALUE=A.ATTR_VALUE
                        AND end_date > start_date
                        AND end_date > a.start_date)