 SELECT T.ATTR_CODE INFO_CODE , T.ATTR_VALUE  INFO_VALUE
  FROM TF_F_USER_ATTR T, TF_F_USER_PLATSVC A
 WHERE T.USER_ID = A.USER_ID
   AND T.RELA_INST_ID = A.INST_ID
   AND A.SERVICE_ID = :SERVICE_ID
   AND A.USER_ID = :USER_ID
   AND A.PARTITION_ID = T.PARTITION_ID
   AND A.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)