UPDATE TF_F_USER_ATTR
   SET END_DATE         = TO_DATE(:END_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID,
       RSRV_DATE2       = TO_DATE(:RSRV_DATE2, 'YYYY-MM-DD HH24:MI:SS'),
       RSRV_DATE3       = TO_DATE(:RSRV_DATE3, 'YYYY-MM-DD HH24:MI:SS')
 WHERE USER_ID = TO_NUMBER(:USER_ID)
   AND PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
   AND INST_ID = TO_NUMBER(:INST_ID)
   AND INST_TYPE = :INST_TYPE
   AND ATTR_CODE = :ATTR_CODE