UPDATE TF_A_BADDEBT_TEXTDEALLOG 
SET DEAL_STATUS='4',DEALED_RECORDS=:DEALED_RECORDS, 
BEFORE_DEAL_DATE=SYSDATE,DEPART_ID=:DEPART_ID,STAFF_ID=:STAFF_ID,
REMARK=:REMARK  
WHERE TEXTFILE_NAME=:TEXTFILE_NAME