SELECT T.LOG_ID,
       T.BUSIFORM_NODE_ID,
       T.BUSIFORM_ID,
       T.STEP_ID,
       T.LOG_INFO,
       T.VALID_TAG,
       T.EXEC_MONTH,
       T.ACCEPT_DEPART_ID,
       T.UPDATE_DEPART_ID,
       T.UPDATE_STAFF_ID,
       T.ACCEPT_STAFF_ID,
       TO_CHAR(T.CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') CREATE_DATE,
       TO_CHAR(T.UPDATE_DATE, 'YYYY-MM-DD HH24:MI:SS') UPDATE_DATE
  FROM TF_BH_EWE_ERROR_LOG T
 WHERE T.LOG_ID = :LOG_ID
