--IS_CACHE=Y
SELECT 
 T.ACTIVE_NAME ELEMENT_NAME,T.ACTIVE_DESC ELEMENT_EXPLAIN,
 T.DISCOUNT_TYPE ,T.DISCOUNT_RATE DISCOUNT_VALUE,
 T.RECHARGE_MIN DISCOUNT_MIN,T.RECHARGE_MAX DISCOUNT_MAX,
 T.PREFERENTIAL_MIN AMOUNT_MIN ,T.PREFERENTIAL_MAX AMOUNT_MAX,
 T.EFFECTIVE_TYPE EFFECT_TYPE ,T.BRAND_CODE,TO_CHAR(T.ADDED_BDATE,'YYYYMMDDHH24MISS') START_DATE,
 TO_CHAR(T.ADDED_EDATE,'YYYYMMDDHH24MISS') END_DATE
FROM TD_B_MARKET_ACTIVE T
WHERE T.PROVINCE =:PROVINCE