DELETE FROM TD_S_DISCNT_SVC_LIMIT
WHERE DISCNT_CODE = :DISCNT_CODE
AND SERVICE_ID = :SERVICE_ID
AND LIMIT_TAG = :LIMIT_TAG
AND START_DATE = to_date(:START_DATE,'yyyy-mm-dd hh24:mi:ss')
AND EPARCHY_CODE = :EPARCHY_CODE