UPDATE TD_M_RES_PARA
   SET PARA_NAME        = :PARA_NAME,
       VALID_TAG        = :VALID_TAG,
       REMARK           = :REMARK,
       UPDATE_TIME      = SYSDATE,
       UPDATE_STAFF_ID  = :UPDATE_STAFF_ID,
       UPDATE_DEPART_ID = :UPDATE_DEPART_ID
 WHERE EPARCHY_CODE = :EPARCHY_CODE
   AND PARA_ATTR = :PARA_ATTR
   AND PARA_CODE1 = :PARA_CODE1
   AND PARA_CODE2 = :PARA_CODE2