--IS_CACHE=N
SELECT D.DEPART_KIND_CODE 部门类型,B.TRADE_STAFF_ID,TO_CHAR(B.ACCEPT_DATE, 'YYYYMM') 受理月份,B.TRADE_ID 台账标识,c.CUST_NAME 客户名称,c.PSPT_TYPE_CODE 证件类型,c.PSPT_ID 证件号码
FROM ucr_crm1.TF_BH_TRADE               B,
     TF_F_CUSTOMER             C,
     TD_M_DEPART D,
     UCR_CRM1.TF_B_TRADE_OTHER O
WHERE C.CUST_ID = B.CUST_ID
 AND C.CUST_ID = :CUST_ID
 AND C.PARTITION_ID = MOD(:CUST_ID, 10000)
 AND B.TRADE_TYPE_CODE = 60
 AND B.USER_ID = TO_NUMBER(:USER_ID)
 AND C.IS_REAL_NAME = '1'
 AND B.TRADE_DEPART_ID = D.DEPART_ID
 AND O.TRADE_ID = B.TRADE_ID
 AND O.RSRV_VALUE_CODE = 'CHRN'
 AND TRUNC(B.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
 AND ROWNUM < 2