select t.* from TI_B_MFC_SYNC t  
where  t.BUSINESS_TYPE=:BUSINESS_TYPE
AND t.PRODUCT_OFFERING_ID=:PRODUCT_OFFERING_ID
AND t.CUSTOMER_PHONE=:CUSTOMER_PHONE
AND t.MEM_TYPE=:MEM_TYPE
AND t.MEM_AREA_CODE=:MEM_AREA_CODE
AND t.MEN_NUMBER=:MEN_NUMBER
AND t.BIZ_VERSION=:BIZ_VERSION