SELECT a.*
  FROM TF_F_USER_PLATSVC a
 WHERE 1 = 1
   AND a.PARTITION_ID = MOD(:USER_ID, 10000)
   AND a.USER_ID = :USER_ID
   AND (a.BIZ_STATE_CODE = 'A' OR a.BIZ_STATE_CODE = 'N' OR
       a.BIZ_STATE_CODE = 'L')
   AND SYSDATE BETWEEN a.START_DATE AND a.END_DATE
