SELECT A.GROUP_ID, A.GROUP_CUST_NAME, B.CITY_CODE, B.CUST_MANAGER_ID
  FROM TF_F_CUST_GROUPMEMBER A, TF_F_CUST_GROUP B
 WHERE A.CUST_ID = B.CUST_ID
   AND A.REMOVE_TAG = '0'
   AND A.MEMBER_CUST_ID = :MEMBER_CUST_ID