INSERT INTO ti_b_user_acctday(SYNC_SEQUENCE    ,
  MODIFY_TAG       ,
  TRADE_ID         ,
  PARTITION_ID     ,
  USER_ID          ,
  ACCT_DAY         ,
  CHG_TYPE         ,
  CHG_MODE         ,
  CHG_DATE         ,
  FIRST_DATE       ,
  INST_ID          ,
  START_DATE       ,
  END_DATE         ,
  UPDATE_TIME      ,
  UPDATE_STAFF_ID  ,
  UPDATE_DEPART_ID ,
  REMARK           ,
  RSRV_NUM1        ,
  RSRV_NUM2        ,
  RSRV_NUM3        ,
  RSRV_NUM4        ,
  RSRV_NUM5        ,
  RSRV_STR1        ,
  RSRV_STR2        ,
  RSRV_STR3        ,
  RSRV_STR4        ,
  RSRV_STR5        ,
  RSRV_DATE1       ,
  RSRV_DATE2       ,
  RSRV_DATE3       ,
  RSRV_TAG1        ,
  RSRV_TAG2        ,
  RSRV_TAG3)  
  SELECT :SYNC_SEQUENCE,'2',:TRADE_ID,MOD(a.USER_ID,10000),
  a.USER_ID          ,
  a.ACCT_DAY         ,
  a.CHG_TYPE         ,
  a.CHG_MODE         ,
  a.CHG_DATE         ,
  a.FIRST_DATE       ,
  a.INST_ID          ,
  a.START_DATE       ,
  a.END_DATE         ,
  a.UPDATE_TIME      ,
  a.UPDATE_STAFF_ID  ,
  a.UPDATE_DEPART_ID ,
  a.REMARK           ,
  a.RSRV_NUM1        ,
  a.RSRV_NUM2        ,
  a.RSRV_NUM3        ,
  a.RSRV_NUM4        ,
  a.RSRV_NUM5        ,
  a.RSRV_STR1        ,
  a.RSRV_STR2        ,
  a.RSRV_STR3        ,
  a.RSRV_STR4        ,
  a.RSRV_STR5        ,
  a.RSRV_DATE1       ,
  a.RSRV_DATE2       ,
  a.RSRV_DATE3       ,
  a.RSRV_TAG1        ,
  a.RSRV_TAG2        ,
  a.RSRV_TAG3
       FROM TF_B_TRADE_USER_ACCTDAY_BAK a
      WHERE a.trade_id = :TRADE_ID
        AND a.accept_month = :ACCEPT_MONTH
        AND NOT EXISTS (SELECT 1 FROM ti_b_user_acctday
                         WHERE sync_sequence = TO_NUMBER(:SYNC_SEQUENCE)
                           AND a.user_id = user_id
                           and a.inst_id=inst_id )