SELECT D.VIP_CLASS_ID, D.VIP_CARD_NO, D.VIP_CARD_END_DATE
  FROM TF_F_CUST_VIP D
 WHERE D.USER_ID = :USER_ID
   AND D.JOIN_DATE =
       (SELECT MAX(JOIN_DATE)
          FROM TF_F_CUST_VIP
         WHERE USER_ID = :USER_ID)