SELECT P.TRADE_ID, 
       P.PRODUCT_ID, 
       TO_CHAR(P.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE,
       TO_CHAR(P.END_DATE, 'YYYY-MM-DD HH24:MI:SS') END_DATE,
       P.MODIFY_TAG
  FROM TF_B_TRADE T, TF_B_TRADE_PRODUCT P
 WHERE T.TRADE_ID = P.TRADE_ID
   AND T.SUBSCRIBE_TYPE = '600'
   AND T.ORDER_ID = :ORDER_ID
   AND P.MODIFY_TAG = :MODIFY_TAG