SELECT A.DISCNT_CODE, C.USER_ID_A, A.USER_ID
  FROM (SELECT B.*
          FROM (SELECT U.*
                  FROM TF_F_RELATION_UU U
                 WHERE U.USER_ID_A = :USER_ID_A
                   AND U.END_DATE > TRUNC(LAST_DAY(SYSDATE)) + 1 + 1 / 24 / 60 / 60
                 ORDER BY U.START_DATE DESC) B
         WHERE ROWNUM < 2) C,
       TF_F_USER_DISCNT A,
       TD_S_COMMPARA BB
 WHERE C.PARTITION_ID = A.PARTITION_ID
   AND C.USER_ID_B = A.USER_ID
   AND A.END_DATE > TRUNC(LAST_DAY(SYSDATE)) + 1 + 1 / 24 / 60 / 60
   AND TO_CHAR(A.DISCNT_CODE) = BB.PARAM_CODE
   AND BB.SUBSYS_CODE = 'CSM'
   AND BB.PARAM_ATTR = 9018 
   AND BB.END_DATE > SYSDATE