SELECT /*+ index(a,IDX_TF_F_USER_SVC_SERVID)*/ C.IMSI
  FROM TF_F_USER_SVC A, TF_F_USER_RES C
 WHERE A.SERVICE_ID = 15
   AND A.END_DATE > SYSDATE
   AND EXISTS (SELECT 1
          FROM TF_F_USER B
         WHERE B.USER_ID = A.USER_ID
           AND B.PARTITION_ID = MOD(A.USER_ID, 10000)
           AND B.REMOVE_TAG = '0'
           AND SUBSTR(B.BRAND_CODE, 1, 2) = 'G0')
   AND C.USER_ID = A.USER_ID
   AND C.END_DATE > SYSDATE
   AND C.RES_TYPE_CODE = '1'