SELECT A.USER_ID, A.VPN_NO
	FROM TF_F_USER B, TF_F_USER_VPN A
 WHERE B.USER_ID = A.USER_ID
	 AND B.PARTITION_ID = MOD(B.USER_ID, 10000)
	 AND B.REMOVE_TAG = '0'
	 AND A.REMOVE_TAG = '0'
	 AND B.CUST_ID = TO_NUMBER(:CUST_ID)
	 AND (B.PRODUCT_ID = '8000' AND (A.VPN_USER_CODE IS NULL OR A.VPN_USER_CODE != '2'))
	 AND (SELECT COUNT(1) NO1
					FROM TF_F_USER B, TF_F_USER_VPN A
				 WHERE B.USER_ID = A.USER_ID
					 AND B.PARTITION_ID = MOD(B.USER_ID, 10000)
					 AND B.REMOVE_TAG = '0'
					 AND A.REMOVE_TAG = '0'
					 AND B.CUST_ID = TO_NUMBER(:CUST_ID)
					 AND ((B.PRODUCT_ID IN ('2222', '8016', '6130')) OR
							 (B.PRODUCT_ID = '8000' AND A.VPN_USER_CODE = '2'))) = 0