SELECT A.GROUP_ID GROUP_ID,
       A.CLASS_ID CLASS_ID,
       C.CITY_CODE,
       B.SERIAL_NUMBER   SERIAL_NUMBER,
       A.CUST_MANAGER_ID MANAGER_STAFF_ID,
       A.CUST_NAME CUST_NAME,
       TO_CHAR(B.OPEN_DATE, 'yyyy-mm-dd hh24:mi:ss') OPEN_DATE,
       E.BIZ_CODE BIZ_CODE,
       F.PRODUCT_ID PRODUCT_ID,
       TO_CHAR(E.START_DATE, 'yyyy-mm-dd hh24:mi:ss') START_DATE,
       TO_CHAR(E.END_DATE, 'yyyy-mm-dd hh24:mi:ss') END_DATE
  FROM TF_F_CUST_GROUP A,
       TF_F_USER       B,
       TF_F_CUSTOMER   C,
       TF_F_USER_GRP_PLATSVC E,
       TF_F_USER_PRODUCT     F
 WHERE A.CUST_ID = B.CUST_ID
   AND A.CUST_ID = C.CUST_ID
   AND C.PARTITION_ID = MOD(A.CUST_ID, 10000)
   AND C.REMOVE_TAG = '0'
   AND B.USER_ID = E.USER_ID(+)
   AND B.PARTITION_ID = E.PARTITION_ID(+)
   AND F.USER_ID = B.USER_ID
   AND F.PARTITION_ID = MOD(B.USER_ID, 10000)
   AND NOT EXISTS
 (SELECT 1
          FROM TF_F_RELATION_UU D
         WHERE D.USER_ID_B = B.USER_ID
           AND D.PARTITION_ID = MOD(B.USER_ID, 10000)
           AND D.END_DATE > SYSDATE)
   AND A.REMOVE_TAG = '0'
   AND B.REMOVE_TAG = '0'
   AND (A.GROUP_ID = :GROUP_ID OR :GROUP_ID IS NULL)
