SELECT CG.GROUP_ID,
       CG.CUST_NAME,
       (SELECT C.DATA_NAME
          FROM TD_S_STATIC C
         WHERE C.TYPE_ID = 'CUSTGROUP_GROUPTYPE'
           AND C.DATA_ID = CG.GROUP_TYPE) GROUP_TYPE_NAME,
       (SELECT C.DATA_NAME
          FROM TD_S_STATIC C
         WHERE C.TYPE_ID = 'CUSTGROUP_CLASSID'
           AND C.DATA_ID = CG.CLASS_ID) CLASS_NAME,
       US.SERIAL_NUMBER GROUP_USER_CODE,
       US.USER_ID GROUP_USER_ID
  FROM TF_F_CUST_GROUP CG, TF_F_USER US
 WHERE CG.CUST_ID = US.CUST_ID
   AND CG.GROUP_ID = :GROUP_ID
   AND CG.REMOVE_TAG = '0'
   AND US.REMOVE_TAG = '0'
   AND EXISTS (SELECT 1
          FROM TF_F_USER_PRODUCT UP
         WHERE UP.PARTITION_ID = US.PARTITION_ID
           AND UP.USER_ID = US.USER_ID
           AND SYSDATE BETWEEN UP.START_DATE AND UP.END_DATE
           AND UP.PRODUCT_ID = :PRODUCT_ID)
