--IS_CACHE=N
SELECT DEPART_KIND_CODE 部门类型, ACCEPT_DATE 受理月份, TRADE_DEPART_ID 受理部门, TRADE_ID 台账标识
FROM (SELECT E.DEPART_KIND_CODE,
        TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
        A.TRADE_DEPART_ID,
        A.TRADE_ID
   FROM ucr_crm1.TF_B_TRADE A, TD_M_DEPART E
  WHERE A.UPDATE_DEPART_ID = E.DEPART_ID
    AND A.SERIAL_NUMBER = :KD_SERIAL_NUMBER
    AND A.TRADE_TYPE_CODE IN (680, 681)
    AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
    AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT C WHERE C.COLLECT_ID=:COLLECT_ID AND C.COLLECT_DEF=A.PRODUCT_ID)
 UNION
 SELECT E.DEPART_KIND_CODE,
        TO_CHAR(A.ACCEPT_DATE, 'YYYYMM') ACCEPT_DATE,
        A.TRADE_DEPART_ID,
        A.TRADE_ID
   FROM ucr_crm1.TF_BH_TRADE A, TD_M_DEPART E
  WHERE A.UPDATE_DEPART_ID = E.DEPART_ID
    AND A.SERIAL_NUMBER = :KD_SERIAL_NUMBER
    AND A.TRADE_TYPE_CODE IN (680, 681)
    AND TRUNC(A.ACCEPT_DATE) BETWEEN TRUNC(SYSDATE - 3) AND TRUNC(SYSDATE)
    AND EXISTS (SELECT 1 FROM TD_CHL_COLLECT C WHERE C.COLLECT_ID=:COLLECT_ID AND C.COLLECT_DEF=A.PRODUCT_ID)
     ) TRADE
WHERE ROWNUM < 2