SELECT DISTINCT :SYNC_SEQUENCE SYNC_SEQUENCE, :SYNC_DAY SYNC_DAY, '8' MODIFY_TAG, 
		:TRADE_ID TRADE_ID, MOD(B.USER_ID, 10000) PARTITION_ID, B.USER_ID, B.INST_ID, B.TEL_URL,
		B.SIP_URL, B.IMPI, B.IMS_USER_ID, B.IMS_PASSWORD,
		B.START_DATE, B.END_DATE, B.RSRV_STR1, B.RSRV_STR2,
		B.RSRV_STR3, B.RSRV_STR4, B.RSRV_STR5
  FROM TF_F_USER_IMPU B
 WHERE B.USER_ID = :USER_ID
   AND B.PARTITION_ID = MOD(:USER_ID, 10000)