UPDATE TF_F_USER_SALEACTIVE_BOOK A
   SET A.DEAL_STATE_CODE  = '1',
       A.UPDATE_TIME      = SYSDATE,
       A.RSRV_STR1      = :INTF_TRADE_ID,
       A.UPDATE_STAFF_ID  = :TRADE_STAFF_ID,
       A.UPDATE_DEPART_ID = :TRADE_DEPART_ID
 WHERE A.PROCESS_TAG = '0'
   AND A.DEAL_STATE_CODE = :DEAL_STATE_CODE
   AND NVL(A.RSRV_DATE2, A.END_DATE) > SYSDATE
   AND A.SERIAL_NUMBER = REPLACE(:SERIAL_NUMBER,'KD_','')
   AND A.PRODUCT_ID_B = :PRODUCT_ID
   AND A.PACKAGE_ID_B = :PACKAGE_ID
   AND A.ACCEPT_TRADE_ID = :TRADE_ID