INSERT INTO TF_F_USER_PRODUCT
  (PARTITION_ID,
   USER_ID,
   USER_ID_A,
   PRODUCT_ID,
   PRODUCT_MODE,
   BRAND_CODE,
   INST_ID,
   CAMPN_ID,
   START_DATE,
   END_DATE,
   UPDATE_TIME,
   UPDATE_STAFF_ID,
   UPDATE_DEPART_ID,
   REMARK,
   RSRV_NUM1,
   RSRV_NUM2,
   RSRV_NUM3,
   RSRV_NUM4,
   RSRV_NUM5,
   RSRV_STR1,
   RSRV_STR2,
   RSRV_STR3,
   RSRV_STR4,
   RSRV_STR5,
   RSRV_DATE1,
   RSRV_DATE2,
   RSRV_DATE3,
   RSRV_TAG1,
   RSRV_TAG2,
   RSRV_TAG3)
  SELECT b.PARTITION_ID,
         b.USER_ID,
         b.USER_ID_A,
         b.PRODUCT_ID,
         b.PRODUCT_MODE,
         b.BRAND_CODE,
         b.INST_ID,
         b.CAMPN_ID,
         b.START_DATE,
         b.end_date,
         SYSDATE,
         b.UPDATE_STAFF_ID,
         b.UPDATE_DEPART_ID,
         b.REMARK,
         b.RSRV_NUM1,
         b.RSRV_NUM2,
         b.RSRV_NUM3,
         b.RSRV_NUM4,
         b.RSRV_NUM5,
         b.RSRV_STR1,
         b.RSRV_STR2,
         b.RSRV_STR3,
         b.RSRV_STR4,
         b.RSRV_STR5,
         b.RSRV_DATE1,
         b.RSRV_DATE2,
         b.RSRV_DATE3,
         b.RSRV_TAG1,
         b.RSRV_TAG2,
         b.RSRV_TAG3
    FROM TF_B_TRADE_PRODUCT_BAK B,TD_B_PRODUCT D
   WHERE B.TRADE_ID=:TRADE_ID
     AND B.USER_ID = :USER_ID
     AND B.PARTITION_ID = MOD(:USER_ID, 10000)
     AND B.product_id=D.product_id
     AND SYSDATE BETWEEN D.start_date AND D.end_date