SELECT UP.USER_ID, UP.PRODUCT_ID, UP.PRODUCT_MODE
  FROM TF_F_USER_PRODUCT UP
 WHERE SYSDATE BETWEEN UP.START_DATE AND UP.END_DATE
   AND UP.USER_ID = :USER_ID
   AND UP.PARTITION_ID = MOD(TO_NUMBER(:USER_ID), 10000)
 ORDER BY UP.PRODUCT_ID
