SELECT IBSYSID,
       RECORD_NUM,
       BUSI_STATE,
       ACCEPT_MONTH,
       PRODUCT_NO,
       TRADE_ID,
       CREATE_DATE,
       REMARK,
       RSRV_STR1,
       RSRV_STR2,
       RSRV_STR3
  FROM TF_B_EOP_EOMS_STATE A
 WHERE 1 = 1
   AND A.TRADE_ID = :TRADE_ID
   AND A.IBSYSID = :IBSYSID